### ISSUE TITLE
issue G910

### ISSUE THREAD

**Issue by llGoldMemberll** [antonpup/Aurora#100]
Hi every one.

I got an issue whit the G910 
I can configurate the desktop , and all that stuff, but when I want to configurate for example league of legends, there's happend a problem , my keyboard did not change the colours. and meaby some of you can help me :D 

and look like this:

![aurora](https://cloud.githubusercontent.com/assets/21042712/17672806/75ea1230-62db-11e6-9df6-5f76ca39b909.png)

remember that the last version of league is:

...\RADS\solutions\lol_game_client_sln\releases\0.0.1.142 .... so meaby something is going wrong in the research or something.

and last I have a big question ... my Aurora folder look like this ... 

![folder](https://cloud.githubusercontent.com/assets/21042712/17672964/27f992de-62dc-11e6-9d0a-1171f1aa5e98.png)

so i wanna know if is right or not 

Thx and rewards!.
 

***-----------------------------***-----------------------------***-----------------------------***-------

I made the same whit other game Evolve 2 and works fine , every thing goes fine so meaby is something in the league config ? 

this is the evolve config 

![evolve](https://cloud.githubusercontent.com/assets/21042712/17673896/6dbbd2e2-62e0-11e6-9720-b58c4ded48d6.png)

and this is how the keyboard look like in the game:

 
![key](https://cloud.githubusercontent.com/assets/21042712/17673962/aa5fdbb2-62e0-11e6-949a-27e732bef054.png)

**Comment by antonpup** [comment]
Well, first of all, you downloaded both the source code and the release. You just need the latest release from here: https://github.com/antonpup/Aurora/releases

Then for League, you have to enable a lightfx setting in the config file of the game to allow for LightFX to work. The instructions for that can be found here: http://forums.na.leagueoflegends.com/board/showthread.php?t=2110253

I also noticed that your entire LoL profile is set as a rainbow effect, you will not be able to see the LightFX effects if Color Zones cover the entire canvas.

**Comment by llGoldMemberll** [comment]
@antonpup Thank you buddy it's actually works now , so if some one have some issue this can help out some other people :+1:

**Comment by antonpup** [comment]
Glad you got it fixed. I hope you enjoy Aurora! :smile:
