### ISSUE TITLE
Lightning effects are lagging

### ISSUE THREAD

**Issue by BastiJava** [antonpup/Aurora#1003]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (Logitech G910 Orion Spectrum)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [x] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
When i press a button the Lights should run "smooth".
### Actual behavior:
The lightning effects are lagging like in the Video below.
### How often does this problem occur?

This problem occurs... (Fill in here)
Every time 
### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Open Aurora
2. Enable Aurora to provide lighting effects for desktop checkbox
3. Press any key

### What is the version of Aurora you are experiencing this issue with?

My version is Aurora beta v.0.6.0b

### Does the previous version of Aurora have this issue?
I did not have the previous version.

### Please include any logs, screenshots, or files that are related to this issue:

YouTube-Video where you can see the problem:
https://youtu.be/Y2SrWJDMeOA

**Comment by BastiJava** [comment]
Updated to version beta v0.6.1-dev4, but i have still the same problem.

**Comment by simon-wh** [comment]
@BastiJava For that error you need to delete %appdata%/Aurora/Config.json

For the lagging, could you look at what is being shown in the Debug tab of settings for the Bitmap?

**Comment by BastiJava** [comment]
The bitmap is not lagging,

**Comment by simon-wh** [comment]
It must be an issue with the Logitech SDK taking a long time. Could you try restarting LGS and checking what the response time for the Logitech device is under Device Manager (when using v0.6.1-dev4)?

**Comment by BastiJava** [comment]
I restarted
Logitech: 0ms

**Comment by BastiJava** [comment]
I fixed the problem myself. I updated the Logitech Gaming Software from 8.88 to 8.96.88
Thank you

**Comment by simon-wh** [comment]
@BastiJava Glad you got it sorted!
