### ISSUE TITLE
Chroma effects stop working when I install the overwatch patch

### ISSUE THREAD

**Issue by Advocate7x70** [antonpup/Aurora#1005]
### What are you experiencing an issue with?

- [ ] Aurora
- [x] Aurora supported game, Overwatch
- [x] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
I have a Corsair k70 and a Razer Mamba. The Razer has always done the proper Chroma lighting effects before I had Aurora. I install the Overwatch patch in Aurora, which should enable the lighting effects on both the keyboard and on the mouse.

### Actual behavior:
The keyboard lights are enabled but the mouse defaults to the normal synapse profile instead of the chroma effects I used to see before patching overwatch for aurora.

### How often does this problem occur?

This problem occurs every time I load overwatch with the aurora patch installed.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. 
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... 0.6.0b

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.
I didn't have the previous version.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
1. Could you try using [v0.6.1-dev4](https://github.com/antonpup/Aurora/releases)?
2. Can you make sure the Razer integration is connected? As it appears that it isn't connected to the SDK.

**Comment by Advocate7x70** [comment]
I'm not sure how to confirm that the Razer inegration is connected. Can you walk me through that?

And I updated to that same version, but now I don't see anything happening in OW.

**Comment by simon-wh** [comment]
Go to this part of settings and see what it says for Logitech
![](https://user-images.githubusercontent.com/10797576/36235855-dcd4ebfe-11ea-11e8-983e-334564d3db46.png)

**Comment by Advocate7x70** [comment]
I use a razor mamba but it doesn’t show up at all on that screen. I’ll grab a screenshot later if I can.

**Comment by simon-wh** [comment]
You should see the line with Razer showing "Mouse connected" if it has connected to the SDK and can see your mouse.

**Comment by Advocate7x70** [comment]
this is what shows up for me. 
![aurora settings](https://user-images.githubusercontent.com/5192963/37883285-28abc94c-306f-11e8-988b-a124c3653142.PNG)

**Comment by Advocate7x70** [comment]
And when I have the Overwatch patch installed, I don't get ANY chroma effects. When I delete those files, I get the normal chroma effects on my mouse, but my keyboard just uses the corsair profile I use by default.

**Comment by simon-wh** [comment]
Do you have any desktop lighting effects that should be showing up that aren't? You might have the keyboard/global brightness down.

**Comment by Advocate7x70** [comment]
Yeah the only lighting that seems to show up in Aurora is the volume visualization, and none of the previews ever show up for me.

**Comment by Ricardonacif** [comment]
Did blizzard blocked the integration?

**Comment by simon-wh** [comment]
@Advocate7x70 Strange, could you try deleting %appdata%/Aurora?
