### ISSUE TITLE
Support for non-RGB devices

### ISSUE THREAD

**Issue by HexaCubist** [antonpup/Aurora#101]
Hi there, is there any support planned for devices which have per-key lighting but not RGB? I have a Corsair Strafe (non-RGB) and would love to use this with it. Obviously, the advanced lighting wouldn't work, but things such as health bars etc would work fine without colours.

**Comment by antonpup** [comment]
A friend of mine has a red, non rgb, Strafe. And it seems to work fine. Corsair SDK seems to treat all colors as "red", so you have to adjust colors in Aurora to be shades of red.

**Comment by HexaCubist** [comment]
Awesome, this works. Thank you!
