### ISSUE TITLE
Shortcut Assistant gets stuck when locking the screen

### ISSUE THREAD

**Issue by obstriegel** [antonpup/Aurora#1011]
Hi,

when I use Windows-Key + L to lock the screen and log back in, the assigned keys stay turned on.
In v 0.6.0b it seems it goes away once I just press the Windows key once. But I also had that it would not go away until Aurora was restarted.

In the dev version 0.6.1-dev4 the windows-key shortcut assistant simply stops working after logging back in. The keys are not lighting up anymore when the Windows key is pressed.

I use Windows 10 Build 1703 and a Corsair K70 RGB LUX keyboard.
Might be related to #929 but I don't think so.

**Comment by travis-teitsch** [comment]
In 0.6.1-dev4 I am experiencing a similar issue. I am also using two separate Corsair K70 RGB LUX keyboards on both Windows 10 Enterprise and Professional and am running Aurora with administrator privileges.

I have run into two different scenarios on both computers:

1. A shortcut key is detected in the opposite state (pressed vs. unpressed). No combination of key presses has been able to correct Aurora's shortcut key state detection. Restarting Aurora resolves the problem.

2. The shortcut assistants just appears to no longer detect keys, no combination of key presses seem to be able to trigger the lighting hints for any of the assistants. Restarting Aurora resolves the problem. This could be the same as the first scenario, and I just did not detect the proper key combination that was being falsely detected.

**Comment by travis-teitsch** [comment]
@simon-wh The build in the link you provided is causing problems for me. Upon opening 0.6.1-dev4-319, I received a configuration error and had to go through the setup process again. After completing that, my keyboard lighting shuts off entirely, and if I try to stop and start the device through the application's device manager, the application crashes. Within the application, the virtual keyboard lighting is behaving as expected, while my physical keyboard's lighting does not.

Reverting back to 0.6.1-dev4 from the web installer, I received the same configuration error and went through the setup process again. After completing that, the keyboard functions as expected.

I should also note that using the web installer build (0.6.1-dev4) is no longer giving me issues at home (Windows 10 Pro) with the windows+L combination.

**Comment by simon-wh** [comment]
@travis-teitsch Could you post your log file?
