### ISSUE TITLE
Logitech G502 Mouse not available.

### ISSUE THREAD

**Issue by RichHammond** [antonpup/Aurora#1012]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [X] Aurora supported device, (Logitech G502 Proteus Spectrum)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [X] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
In the "Preferred Mouse" section, my G502 should be an option in the dropdown menu.

### Actual behavior:
Explain here what happened instead.
It is not in the dropdown menu.

### How often does this problem occur?

This problem occurs... (Every time)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Plug in Logitech G502 Proteus Spectrum RGB Mouse
2. Retry for connected devices and make sure Logitech says connected (and that the mouse registers in Logitech Gaming Software)
3. Restart Aurora and open the Preferred Mouse dropdown in Devices and Wrappers under settings.

### What is the version of Aurora you are experiencing this issue with?

My version is... (beta 0.6.0)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.
This is my first version, I do not know.

### Please include any logs, screenshots, or files that are related to this issue:
https://i.imgur.com/J32qNTA.png

**Comment by juanj** [comment]
I have this exact same problem

**Comment by simon-wh** [comment]
See: #510 #710
