### ISSUE TITLE
Cooler Master MK750 Support Request

### ISSUE THREAD

**Issue by MithicalM** [antonpup/Aurora#1014]
### What are you experiencing an issue with?
- [x] Other, Requesting support for the Cooler Master MK750 Keyboard

### What is the version of Aurora you are experiencing this issue with?

My version is... beta v0.61-dev4

**Comment by simon-wh** [comment]
I don't see the MK750 mentioned anywhere in the CM SDK, so I'm not sure if it is supported, but it seems like it should be. Does it work when you select a similar layout? Just not properly working with the additional lights it has available?

**Comment by MithicalM** [comment]
I just went on the product page and clicked on download and there is a SDK available with a document which mentions the MK750. I am not 100% if it is the right think or not but I thought I would let you know!
http://www.coolermaster.com/peripheral/keyboards/masterkeys-mk750/

**Comment by MithicalM** [comment]
@simon-wh Were you able to check and see if that SDK I mentioned in my last comment is the right thing at all?

**Comment by simon-wh** [comment]
It looks right, it seems to just be an updated version of the current cm sdk. I'll try and see if I can just update the sdk and hopefully, that'll get the core of it working.

**Comment by MithicalM** [comment]
Awesome! I hope it works too! Thanks for your work :)

**Comment by simon-wh** [comment]
@MithicalM Could you try to use the build of the commit above? Found [here](https://ci.appveyor.com/project/antonpup/aurora/build/artifacts). That is only updating the SDK to the latest which should allow for basic support of the MK750 (i.e. just the normal parts of the keyboard, not any of the additional lights on the side yet). I can also see some optimisations I can make to the CM integration in Aurora using the latest SDK which, if you want to, you could test for me which would be very helpful.

**Comment by MithicalM** [comment]
@simon-wh I am at uni atm but I downloaded and gave it a quick look and I can't see the MK750 under Devices & Wrappers as a preferred device. But I will give it a shot within the next hour.

**Comment by simon-wh** [comment]
@MithicalM I haven't added a layout for the MK750, so you won't see it as an option. Just try using it with one that has a stock layout.

**Comment by MithicalM** [comment]
@simon-wh okay so it works perfectly fine on Aurora-v0.6.1-dev4-296 but when I go to use Aurora-v0.6.1-dev4-297 (the optimized one) it doesn't work at all. It recognizes the keyboard but none of the lighting effects work on 297.

**Comment by simon-wh** [comment]
Okay, I think I'll revert the commit for 297 and leave it as it is for now
as I can't really test it myself.

**Comment by MithicalM** [comment]
I just noticed another bug where for DotA the keyboard lights up light this (https://i.imgur.com/AUfQHvl.jpg) when it light up like this (https://i.imgur.com/95G0vD7.png).

**Comment by MithicalM** [comment]
Okay so it is the same for all games. It seems to be lighting all keys 1 off to the left.

**Comment by simon-wh** [comment]
I think I have a pretty good idea why that is happening, which may also explain why there were so many issues with the Num 4,5,6 on the Pro L keyboard. I'll try and implement a fix for it later when I'm able to work on this.

**Comment by MithicalM** [comment]
Sorry misclicked and closed the issue.

**Comment by simon-wh** [comment]
My theory turned out to not be the case. I've reverted the "optimisations" and made some changes which, I don't think will solve your issue, but should make sure that the other keyboards still work properly. If you could test it out, it'd be great, you can find it [here](https://ci.appveyor.com/project/antonpup/aurora/build/0.6.1-dev4-299/artifacts).

**Comment by MithicalM** [comment]
@simon-wh I think there is a bug or something with the build as I am getting this "The build job does not contain any artifacts." and under console it says "Command exited with code 1"

**Comment by simon-wh** [comment]
Yeah, it seems appveyor seems to be having issues building that commit, I didn't have any issues building it on my end, trying to sort it out right now.

**Comment by simon-wh** [comment]
@MithicalM Try [this](https://ci.appveyor.com/project/antonpup/aurora/build/0.6.1-dev4-302/artifacts) I had to update the build version appveyor was using.

**Comment by MithicalM** [comment]
@simon-wh 302 isn't work for my keyboard at all. It is doing the same thing as 297 did. Same goes for 303. All my lights are off but my keyboard is getting detected under Device Manager of Aurora

**Comment by simon-wh** [comment]
@MithicalM Could you test [this build](https://www.dropbox.com/s/s46vwjedyars4l9/Release.zip?dl=0)? Doing some debugging of why it isn't working. Could you also check if you're getting any errors in your log?

**Comment by MithicalM** [comment]
I just checked my logs folder and I have a log file from yesterday which is almost 30 GB big for some reason and I can't open it with notepad.exe or notepad++. The build you linked me from dropbox works again but the lights are misaligned like previously. [This is the log file](https://www.dropbox.com/s/uywg74n393k4kiz/2018-03-16%2021.17.41.log?dl=0) from running it for a couple seconds with the build you sent me from dropbox

**Comment by simon-wh** [comment]
It appears the error you're getting a lot is caused by the AtmoOrb device,
disable it in settings to make that error go away

**Comment by MithicalM** [comment]
@simon-wh Uhhh it already is off under device manager. 
![image](https://user-images.githubusercontent.com/1751395/37545680-ba3b30b0-2961-11e8-9af2-5ae413ea4cf9.png)

**Comment by MithicalM** [comment]
I noticed another thing where the bottom 2 rows of the keyboard, none of the LEDs work on those areas at all.

**Comment by MithicalM** [comment]
I have a feeling this might give you an idea of something that could be causing this bug where only the top 4 rows are being lit up and the bottom two aren't.
![image](https://user-images.githubusercontent.com/1751395/37549351-fe5a3a1a-2976-11e8-844b-5f88719bba06.png)

**Comment by simon-wh** [comment]
@MithicalM Temporary solution is to select a Mouse, which should make it return to normal. Currently trying to figure out why this is happening.

**Comment by simon-wh** [comment]
Looking into the issue, it turns out to be bigger than what I originally expected, however, if you set it to use a mouse in the layout it should be fine.

**Comment by MithicalM** [comment]
Yeah that is fine! Thanks! The only other big issue I have is the stuff constantly repeating in my log and create massive log files.
`[ERROR] 21:37:54: BitmapUtils.GetRegionColor() Exception: System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap.LockBits(Rectangle rect, ImageLockMode flags, PixelFormat format, BitmapData bitmapData)
   at System.Drawing.Bitmap.LockBits(Rectangle rect, ImageLockMode flags, PixelFormat format)
   at Aurora.Utils.BitmapUtils.GetRegionColor(Bitmap map, BitmapRectangle rectangle) in D:\Repos\Aurora\Project-Aurora\Project-Aurora\Utils\BitmapUtils.cs:line 23
[ERROR] 21:37:54: BitmapUtils.GetRegionColor() Exception: System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap.LockBits(Rectangle rect, ImageLockMode flags, PixelFormat format, BitmapData bitmapData)
   at System.Drawing.Bitmap.LockBits(Rectangle rect, ImageLockMode flags, PixelFormat format)
   at Aurora.Utils.BitmapUtils.GetRegionColor(Bitmap map, BitmapRectangle rectangle) in D:\Repos\Aurora\Project-Aurora\Project-Aurora\Utils\BitmapUtils.cs:line 23
[ERROR] 21:37:54: BitmapUtils.GetRegionColor() Exception: System.ArgumentException: Parameter is not valid.
   at System.Drawing.Bitmap.LockBits(Rectangle rect, ImageLockMode flags, PixelFormat format, BitmapData bitmapData)
   at System.Drawing.Bitmap.LockBits(Rectangle rect, ImageLockMode flags, PixelFormat format)`

**Comment by simon-wh** [comment]
Yeah, I noticed that happening as well, if it is still happening with the mouse selected then switch off of the pro l layout, I think there is an issue with it that makes that happening.

**Comment by simon-wh** [comment]
@MithicalM With what I mentioned above does the main keyboard lighting work as expected on your keyboard?

**Comment by MithicalM** [comment]
@simon-wh Yeah it works fine now. The only issue is that the keys lighting is still misaligned by one key. So the "-, + and ENTER" keys on numpad have no lighting. Other than that I have had no issues at all.

**Comment by BilbroSwaggins** [comment]
Any update on this issue with some keys not lighting up? As of now using the latest build simon sent out, the F4, R SHIFT, ENTER, FN, ', ], =, UP ARROW, and the right most keys on the numpad(return, +, -, skip song) arent lighting up. Along with all the side lighting. Thanks for making this work so far!

**Comment by MithicalM** [comment]
@simon-wh Hey any update on this at all?

**Comment by Junneh** [comment]
I cant get it working at all with my new MK750 and 2.61dev4 

Worked fine with masterkeys pro before. Doesnt seem to recognize the MK750 at all tho.

**Comment by Baralan** [comment]
I cannot seem to get it to work at all whatsoever with any version. With some versions i juts get no lighting on the keyboard. On the others the keyboard is connected, but it is still showing the original lighting, it also shows under device manager i have 3000-4000 ms.

**Comment by Moonart** [comment]
Any progress to full suport for this keyboard?

**Comment by simon-wh** [comment]
@MithicalM @Moonart I have gotten frustrated enough trying to fix CM and MK750 related issues that I've bought one, it should be arriving today and hopefully today/tomorrow I'll be able to get it mostly fixed up. Hopefully with full support coming shortly after.

**Comment by simon-wh** [comment]
@MithicalM @Moonart @BilbroSwaggins @Junneh @Baralan Have any of you tried using it while on the latest firmware?(V1.03.01) I got the keyboard and updated to that straight away and can't get the SDK to work (even just using the example) at all properly and I'm not sure if it is an issue with my particular keyboard or with the SDK not being updated for the firmware. Please let me know, as CM is being of no help in this matter.

**Comment by Moonart** [comment]
Strange, in my case there are no update like this: http://prntscr.com/jedbz4

**Comment by MithicalM** [comment]
https://imgur.com/kDjOmNK mine says its got an update but when I click update it comes up with this window and I can't click on any of the buttons though. That's through the Cooler Master Portal BTW

**Comment by MithicalM** [comment]
![image](https://user-images.githubusercontent.com/1751395/39675167-237ef858-514f-11e8-8e94-95f0b94bb784.png)
I just reinstalled the Cooler Master Portal and MK750 files by delting the files from the Program Files and deleting it from the Program and Files listing using CCleaner. I do have the option to update to the version you mentioned now @simon-wh

**Comment by simon-wh** [comment]
@Moonart You need to reinstall the MK750 software from the portal, according to [this](https://www.reddit.com/r/coolermaster/comments/7egxe5/product_announcement_masterkeys_mk750/dy7l05m/)

**Comment by simon-wh** [comment]
@MithicalM Thanks for the confirmation, I'm glad that it is not just me experiencing this (unfortunate that you're now stuck with this too). Hopefully we'll get an update soon so I can get the MK750 support fixed, depending on how the SDK is updated it may require everyone to update to the latest firmware once it's fixed.

**Comment by BilbroSwaggins** [comment]
I still have not updated to 1.03.01, as I am still running 1.01.23 and everything is running perfectly fine. The only problems with Aurora is that certain keys arent lit up (as mentioned before). I am also getting what Moonart has with the update version being the same as what I am running. Cooler master seems very strange with this whole setup. I would recommend maybe talking to /u/Braumm (i think) on coolermaster's subreddit

**Comment by simon-wh** [comment]
@BilbroSwaggins The cooler master software is really strange, the way it works is not great. Also, [I've tried that and haven't got any helpful response](https://www.reddit.com/r/coolermaster/comments/8gje0y/mk750_sdk_lighting_issues/). Pretty disappointed in CM tbh, I really like the keyboard, but the software and support have a lot to be desired.

**Comment by simon-wh** [comment]
I got this reply from CM support, hopefully we'll get the update soon.

>We have just received information that next week a new SDK will be released what supports also the MK750.
We suggest to keep an eye on our website for more information ;)
http://www.coolermaster.com/peripheral/keyboards/masterkeys-mk750/

**Comment by MithicalM** [comment]
I have an issue where Aurora won't open from any of the versions from this thread. It only launches if I launch the version from Aurora-v0.6.1-dev4. I am not sure if I missing something or not. I did reinstall windows which might have something to do with this.

Also when I went to install the Cooler Master MK750 drivers and I had an update for the keyboard firmware which could fix some of the bugs @simon-wh 
![image](https://user-images.githubusercontent.com/1751395/40338002-b839f250-5d6a-11e8-8b66-17199236b6f1.png)

**Comment by simon-wh** [comment]
@MithicalM Strange, you got anything in your log files?

Also, thanks for letting me know, I'll see if that sorts out the sdk, I wouldn't have known otherwise as I use linux most of the time

**Comment by MithicalM** [comment]
[2018-05-22 17.20.37.log](https://github.com/antonpup/Aurora/files/2027560/2018-05-22.17.20.37.log)
This is what I am getting in the logs.

**Comment by simon-wh** [comment]
@MithicalM Could you try [this build](https://ci.appveyor.com/project/antonpup/aurora/build/0.6.1-dev4-308/artifacts)? It should at least get rid of the errors that are appearing

**Comment by MithicalM** [comment]
[2018-05-23 02.15.04.log](https://github.com/antonpup/Aurora/files/2029127/2018-05-23.02.15.04.log)
I have tried that build and I still have the same issue where the window isn't showing up. Thats the log to the build you linked.

**Comment by MithicalM** [comment]
![image](https://user-images.githubusercontent.com/1751395/40716190-06e97de4-6400-11e8-8e96-080f2f385885.png)
Another FW update @simon-wh

**Comment by simon-wh** [comment]
@MithicalM I've updated to it and the SDK still appears to be broken unfortunately

**Comment by simon-wh** [comment]
@MithicalM Seems like the SDK has finally been updated to work with the MK750 again. Going to try and get basic support going again.

**Comment by simon-wh** [comment]
@MithicalM [Here is a build](https://ci.appveyor.com/project/antonpup/aurora/build/0.6.1-dev4-326/artifacts) that mostly has the MK750 working again (without a proper layout and still has some issues)

**Comment by MithicalM** [comment]
I am having the same issue as you @simon-wh as I have the UK Layout of the keyboard as well.

**Comment by simon-wh** [comment]
I believe the issue is specific to the ISO layout, as far as I can tell, it should work perfectly for US layout keyboards. @GameDragon2k I'll try and get the lightbar support going soon.

**Comment by simon-wh** [comment]
@MithicalM I've added an MK750 layout with the commit above, can you try it out with [this build](https://ci.appveyor.com/project/antonpup/aurora/build/0.6.1-dev4-342/artifacts) and let me know how it goes?

**Comment by MithicalM** [comment]
@simon-wh It works great. Everything seems to be working fine apart from the # key which is not being lit at all. Everything else seems to be lighting up fine and working fine so far. Including the light zones on the side of the keyboard.

**Comment by simon-wh** [comment]
@MithicalM the # key not lighting is part of the issue of the SDK not lighting non-us layout keys

**Comment by BilbroSwaggins** [comment]
Hmm strange. I just used that build and everything seems fine. The 3/# key is lit up for me but the FN and media keys are not. Also the side bars are not working. And strangely enough it keeps on freezing as i type up this comment. I am currently on v1.05.02 w/ software v2.21.

**Comment by simon-wh** [comment]
@BilbroSwaggins the # key we're talking about is beside enter in the iso layout. It's strange that the side lights and FN and media keys are not working. It could be an issue with the SDK similar to the issues we've been getting on the UK layout
