### ISSUE TITLE
Percent and Percent (Gradient) Effect Error

### ISSUE THREAD

**Issue by BastiJava** [antonpup/Aurora#1016]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
When i press Percent Effect Layer or Percent (Gradient) Effect Layer it should work.
### Actual behavior:
Explain here what happened instead.
Aurora crashed
### How often does this problem occur?

Every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. New Layer
2. Take Percent (Gradient) Effect Layer
3. Aurora crash

### What is the version of Aurora you are experiencing this issue with?

My version is v0.6.1 dev4

### Does the previous version of Aurora have this issue?
The previous version, (Aurora 0.6.0b Beta), did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

https://imgur.com/XIJPMUD

**Comment by simon-wh** [comment]
@BastiJava I'm unable to replicate your issue on the [latest build](https://ci.appveyor.com/project/antonpup/aurora/build/artifacts), could you test it and let me know if you still experience it?

**Comment by BastiJava** [comment]
I updated to the newest Version and now it works. thx
