### ISSUE TITLE
Key Color Toggle

### ISSUE THREAD

**Issue by RichHammond** [antonpup/Aurora#1017]
Hi!
I'm loving the software right now, it works wonders on my keyboard.

I'm wondering if it would be possible for you to add a toggle on keypress.
I want my pause key to be one color to start, then switch to another color once i press it, and the next time I press it switch back to the first color.

This would be useful for recording toggles like OBS so I can have one color when I'm recording, and one color when I'm not.

**Comment by diogotr7** [comment]
I'd like this too. I currently have my scroll lock key set like this and bound to mute on discord, but it would be useful if it were more flexible.

**Comment by piercy** [comment]
im not sure if its in the released build, but there is a lock color layer in the dev build im using, so might be available in the beta / alpha / nightly builds.  It does only support capital, scroll lock and numlock atm.  But maybe using scroll lock would be acceptable for you? 

![image](https://user-images.githubusercontent.com/1812670/37179333-3355af52-231d-11e8-99b5-d35fea329516.png)

**Comment by RichHammond** [comment]
I'm on beta 0.6.0 and have that, but I don't want it with the lock keys, I want it with pause.

**Comment by simon-wh** [comment]
Added thanks to @Wibble199 with #1139
