### ISSUE TITLE
Aurora Constantly uploading ~2000 B/s of data

### ISSUE THREAD

**Issue by JarrColl** [antonpup/Aurora#1019]
### What are you experiencing an issue with?
- [ x] Aurora

### What kind of an issue is it?
- [x ] Performance problems     ?

### Expected behavior:
Should not be using the network, or only occasionally.

### Actual behavior:
Aurora is constantly uploading ~2000 B/s. What is it uploading and why is it doing that/should it be doing that.

### How often does this problem occur?
Always

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:
1. Be connected to the internet
2. Open Aurora

### What is the version of Aurora you are experiencing this issue with?
0.6.0b

### Does the previous version of Aurora have this issue?
have not used the previous version

### Please include any logs, screenshots, or files that are related to this issue:
https://pastebin.com/Y2iV7mgX

## Other information
The minor background update option is turned off

**Comment by Piet1702** [comment]
[INFO] 4/03/2018 5:13:58 PM: Device, AtmoOrb, was initialized

Using AtmoOrb? If yes thats your Upload, cause data must be send. Having an AtmoOrb myself in use and getting an constant upload too.

**Comment by simon-wh** [comment]
See #985
