### ISSUE TITLE
Aurora Installer

### ISSUE THREAD

**Issue by HexaCubist** [antonpup/Aurora#102]
I'm not sure if this is the best place to put this, but I wanted to have this installed on my computer, so I made a quick script in Inno Installer to make the installer. Seems to work fine so far. No clue if this is useful or not for the project, but it worked for me:

```
; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{9444602B-C5D8-4EF5-9D5B-E76D06B53C71}
AppName=Aurora
AppVersion=0.5.1a
;AppVerName=Aurora 0.5.1a
AppPublisher=Last Bullet
AppPublisherURL=http://aurora.lastbullet.net/
AppSupportURL=http://aurora.lastbullet.net/
AppUpdatesURL=http://aurora.lastbullet.net/
DefaultDirName={pf}\Aurora
DisableProgramGroupPage=yes
OutputDir=YYYYYY
OutputBaseFilename=setup
SetupIconFile=XXXXXX\Aurora.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "XXXXXX\Aurora.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "XXXXXX\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{commonprograms}\Aurora"; Filename: "{app}\Aurora.exe"
Name: "{commondesktop}\Aurora"; Filename: "{app}\Aurora.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\Aurora.exe"; Description: "{cm:LaunchProgram,Aurora}"; Flags: nowait postinstall skipifsilent

```

Replace `XXXXXX` with the path to a folder containing the latest version, and `YYYYYY` with where you want the output to be. You'll need the Aurora.ico attached (in zip because github doesn't support the format) to be placed in the same folder as everything else for a nice icon to be used by the installer.

Above should be pretty self-explanatory if you want to change anything. You can get the software I used at http://www.jrsoftware.org/isinfo.php

Attached also is a copy of the .iss file (same as pasted above but with my values), and the compiled exe from the latest version (run this through a virus scanner or something!)

**Comment by antonpup** [comment]
Thank you for your input. But my plan is to make a web installer, so users can get the latest version.

Still neat though. I might include this as an "offline install" alternative. But I am not sure.

**Comment by HexaCubist** [comment]
Hey, so I did some more playing around and made a network install version. For it to automatically get the latest version (right now the script only downloads a manually set zip file from your git repo), you'll want to upload the latest version to a single point with direct download (eg http://aurora.lastbullet.net/latest.zip). I've looked around for GitHub providing a direct download location that automatically updates but couldn't see anything without using the API.

Like last time, attached is a link to a zip containing the inno script file, a compiled example (using the latest version), as well as some assets I used to create the wizard (background image sourced freely from https://unsplash.com/search/Aurora under a Creative Commons Zero license).

Let me know if you can't host the file this downloads as I'll try to find a place to host it on my servers (NZ). Also, if you'd rather not compile it yourself just pass me a url to the download zip, and I'll build it again with that.

### Photos of installation:
![image](https://cloud.githubusercontent.com/assets/8563277/17756281/02743308-6533-11e6-92e5-ec409433ef89.png)
![image](https://cloud.githubusercontent.com/assets/8563277/17756289/0bd2cbe4-6533-11e6-97bc-e126362a182a.png)
![image](https://cloud.githubusercontent.com/assets/8563277/17756295/11bb4220-6533-11e6-9345-fbc3acf74d09.png)
![image](https://cloud.githubusercontent.com/assets/8563277/17756297/1b66fee0-6533-11e6-8ff7-f2c7e3c43b8e.png)
![image](https://cloud.githubusercontent.com/assets/8563277/17756302/242ba7c4-6533-11e6-80e4-79ba38aaba5a.png)
![image](https://cloud.githubusercontent.com/assets/8563277/17756309/290d11e2-6533-11e6-96ad-1fbda257ece5.png)


### Instructions to compile (windows only)

- [Download Inno Setup](http://www.jrsoftware.org/isdl.php#qsp) - Quick start pack is what I used, but the normal version will work fine too
- [Download Inno Download Plugin](https://code.google.com/archive/p/inno-download-plugin/) - add this to your PATH
- Extract zip file to a location of your choice
- Open the "installer.iss" file with the Inno Script compiler/studio

**Comment by HexaCubist** [comment]
Classic. Forgot to actually attach the files. Here:
### [Aurora.zip](https://github.com/antonpup/Aurora/files/423799/Aurora.zip)

**Comment by antonpup** [comment]
Well done. Let me see what I can do server-side.

**Comment by HexaCubist** [comment]
Actually, just found this: http://stackoverflow.com/questions/21439239/github-latest-release

I'll do some investigating to see if I can work this in the installer (would mean no hosting required, as well as no manual labor to update)

**Comment by antonpup** [comment]
I already host updates on the site. So it won't be more work.

**Comment by HexaCubist** [comment]
Oh sweet, no worries then

**Comment by antonpup** [comment]
[http://aurora.lastbullet.net/download-latest.php](http://aurora.lastbullet.net/download-latest.php) will return the latest file.

**Comment by HexaCubist** [comment]
Alright, sweet. do you mind if I add myself to the list of awesome people? Also, is there anything else you want on the home screen?

**Comment by antonpup** [comment]
I will credit you on the repo, could add you as a collaborator too. If this works, I will compile my own with my own image for the background, as well as create a download page on the site. You will definitely not be forgotten. :+1:

**Comment by HexaCubist** [comment]
Alright :) I'm happy to help out wherever I can on here!

I can confirm that it's working fine on my pc with the download link set to your host. I've attached the files again with the updated exe and inno script. I recommend you run it through on your PC to confirm that it's working well on another system. The uninstall should also remove all files. An easy way of replacing that background would be to just replace the Aurora-wizard.bmp with your own and then recompiling. Keep in mind that it does have to be a BMP and the resolution needs to be 164 x 314 for the installer to accept it. Line 24 contains the welcome message displayed when you open it.

Image of new welcome screen:
![image](https://cloud.githubusercontent.com/assets/8563277/17758545/6aa1c6dc-6544-11e6-8fdf-db0805d5241b.png)

### [Aurora.zip](https://github.com/antonpup/Aurora/files/423934/Aurora.zip)

**Comment by antonpup** [comment]
Is it possible to have the installer automatically install C++ redistributables? Specifically C++ 2015 for 32 and 64 bit.

**Comment by HexaCubist** [comment]
Sure thing. I have two assessments due tomorrow but I should be able to figure this out when I have time later this week (hopefully!)

Cheers!

**Comment by antonpup** [comment]
Don't worry about it too much. Next version isn't ready yet, I'm aiming for a release by end of the month. I was just wondering if this can install redists, it would eliminate some issues with wrappers for users.

**Comment by HexaCubist** [comment]
Yes, it can do that. I don't know how right now but I have found some code online to test whether the c++ redis is already installed and if not install it. The trick will be to implement this and also find a way to either include the packages in the exe or host them online. I have also found a way to check whether the os is 32-bit or 64-bit but I haven't looked at combining that with the above.

**Comment by HexaCubist** [comment]
Alright, here's a version that will install c++ 2015 (latest version that I downloaded) if it finds either the x86 or x64 version of 14.0.24212 or 14.0.23026 (latest). If there is a version installed that it doesn't detect, then it will run the c++ installer and the installer will fail, so possibly a notice about that should be added, up to you. If you'd like to host the c++ files for keeping in line with the webinstall format, then I can add that as well with minimal effort.

Cheers!
### [Aurora.zip 😄](https://mega.nz/#!wo0XUATK!NiR3QHCLqVjnGIa38DXlZ5G6J3RrO6FAjZsOCydOpwA)
(psst! With all the new code, I can't upload it here, so I've placed the zip on mega)

**Comment by antonpup** [comment]
I've adjusted the installer to my liking. One problem, I am unable to set Aurora.exe to run as administrator. In some cases, Aurora will not run without Admin. So it would be nice to set up Aurora to run as administrator from the getgo.

I have committed the installer to the repo (in dev branch) in the "Web Installer" folder.
