### ISSUE TITLE
Cannot Import CUE Profile

### ISSUE THREAD

**Issue by lyktstolpe** [antonpup/Aurora#1020]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [x] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, (Failed to import)

### Expected behavior:
Import a CUE profile, to use as desktop profile

### Actual behavior:
Got a long-ass error message that tells me nothing

### How often does this problem occur?
Every time I try to import something

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Import profile (.cueprofile)
2. ???
3. Profit

### What is the version of Aurora you are experiencing this issue with?

The latest (Downloaded via latest stable build link minutes before posting this issue) 
v0.6.1 dev4

### Does the previous version of Aurora have this issue?
Haven't tried

### Please include any logs, screenshots, or files that are related to this issue:

https://imgur.com/qCwhcZN

**Comment by diogotr7** [comment]
As far as I know the importing isn't finished and isn't being worked on at the moment. You can find some cueprofile packs for older versions that work fine, but the more recent ones don't unfortunately :/

**Comment by simon-wh** [comment]
Hasn't been finished and likely won't be working on it for a bit as I'm focusing on other features.
See #429
