### ISSUE TITLE
Steelseries support

### ISSUE THREAD

**Issue by vicdilou** [antonpup/Aurora#1022]
Hello,

It's possible to add support of steelseries mouse and keyboard ?

Thank you. #

**Comment by brainbug89** [comment]
The dev version has support for Steelseries devices. You can download the latest version here: https://github.com/antonpup/Aurora/releases

**Comment by vicdilou** [comment]
This version doesn't support steelseries mouse

**Comment by FHeilmann** [comment]
just add any arbitrary mouse to your setup and it will work. whats important is that the LED count matches your mouse.

I have a Steelseries Sensei 310 and use one of the Logitech mice inside aurora. Works flawlessly

**Comment by vicdilou** [comment]
Yes it works !
thank you !
