### ISSUE TITLE
Adding a "percent effect" layer on a custom profile makes a fatal crash

### ISSUE THREAD

**Issue by Speedy-VonGofast** [antonpup/Aurora#1023]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [x] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [x] Other, (Percent Effect Layer)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, (Custom profile corruption)

### Expected behavior:
Adding a "percent effect layer" on a custom profile (Adobe Photoshop in my case) should be working like all other pre-existing profiles (Payday 2, CSGO, GTA V, Desktop, ...)

### Actual behavior:
Crash completely and corrupt the profile I was currently working on

### How often does this problem occur?

This problem occurs every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:
1. Create a custom profile for a custom executable
2. Add a "percent effect layer"
3. The crash occurs immediately

### What is the version of Aurora you are experiencing this issue with?

My version is beta v0.6.1-dev4

### Does the previous version of Aurora have this issue?
The previous version, 0.6.0b Beta, did not have this issue. (I think)

### Please include any logs, screenshots, or files that are related to this issue:
https://i.imgur.com/pEbJqz2.png
https://i.imgur.com/pFVoYEz.png

**Comment by simon-wh** [comment]
I've fixed the crash in the commit above, however, it isn't able to do anything as it doesn't have any variables to access. Would you like to be able to access the same variables that the Desktop "application" can?

**Comment by Speedy-VonGofast** [comment]
I don't quite understand which variable you are talking about. 

If you are talking about the "Current Value" and "Maximum Value" options of the Percent Effect Layer then yes I would like to have the same LocalPCInfo options.

**Comment by simon-wh** [comment]
Yes, that is what I'm referring to, I'll try and add support for that *hopefully* today/tomorrow

**Comment by Speedy-VonGofast** [comment]
Alright, thank you

**Comment by simon-wh** [comment]
I've made it work in the commit above, if you wish to use it then get the version from [here](https://ci.appveyor.com/project/antonpup/aurora/build/0.6.1-dev4-303/artifacts)
