### ISSUE TITLE
Aurora stop working with equalizer

### ISSUE THREAD

**Issue by vicdilou** [antonpup/Aurora#1024]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### How often does this problem occur?

Often when I use the equalizer with Spotify

### What is the version of Aurora you are experiencing this issue with?

My version is... Aurora 0.6.1-dev4

### Please include any logs, screenshots, or files that are related to this issue:

![bug aurora](https://user-images.githubusercontent.com/10620606/37429375-51c74c1e-27cf-11e8-82d4-0a6cdd36d2ef.png)

**Comment by simon-wh** [comment]
Do you have the AtmoOrb device enabled, try disabling that as I've had that issue happen before when it's enabled and running.

**Comment by vicdilou** [comment]
I disable it but at each start, he reactivates

**Comment by simon-wh** [comment]
Are you properly exiting Aurora? If it closes unexpectedly it might not have saved everything properly. Also, make sure you are disabling it, not just stopping it.

**Comment by vicdilou** [comment]
It close when I shut down the computer
and yes I disable it

**Comment by simon-wh** [comment]
Could you try disabling it and exiting Aurora normally to see if that works?

**Comment by vicdilou** [comment]
It works !
thank you
I will try with spotify now
