### ISSUE TITLE
Aurora freezes upon resuming from sleep/hibernation.  Have to kill process and restart it.

### ISSUE THREAD

**Issue by mmmboost** [antonpup/Aurora#1028]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [x] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Aurora works great if i start the program and adjust settings/profiles/etc.  It even senses game profiles more accurately than my SteelSteries mouse software.  The problem comes in when waking my computer up from sleep/hibernate.  None of the lighting profiles or changes seem to register.

### Actual behavior:
After waking my PC up, nothing from Aurora seems to register with my keyboard.  The profile is not restored and making any changes in the aurora software does nothing.  It seems like the computer sleeping has broken the link between the program and the keyboard.  In order to get keyboard lighting working again, I have to go into the task manager, kill the process, and then run it again in administrator mode. I believe the same thing happens when I restart my computer as well, but I would have to do some testing.

### How often does this problem occur?
Every time I wake my computer from sleep/hibernate. 
Also happening on first startup of windows.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Have Aurora running (minimized in taskbar if that matters)
2. Allow computer to go into sleep mode.
3. Wake computer from sleep mode.

1.  Start computer.
2.  Log into windows.
3.  Aurora starts up on it's own and is running.  Says its connected to keyboard, but no lighting profile is active.

### What is the version of Aurora you are experiencing this issue with?

v0.6.1

### Does the previous version of Aurora have this issue?
Not sure, this is the first version I have used.

### Please include any logs, screenshots, or files that are related to this issue:
The first log is the first one after waking my PC up.  It looks like it's not initializing properly.  The second log is from restarting Aurora after killing the process.  And just posted a new log of a fresh boot.

[2018-03-17 11.20.23.log](https://github.com/antonpup/Aurora/files/1821881/2018-03-17.11.20.23.log)
[2018-03-17 11.20.41.log](https://github.com/antonpup/Aurora/files/1821882/2018-03-17.11.20.41.log)
[2018-03-17 12.00.08.log](https://github.com/antonpup/Aurora/files/1821920/2018-03-17.12.00.08.log)

**Comment by KairuByte** [comment]
I'm not sure how on the radar this is, but I experience similar symptoms when I return from sleep/hibernation.

**Comment by simon-wh** [comment]
I've tested again on my laptop(which is a normal setup) with my Wooting One and still can't replicate the issue, I can sleep and hibernate and when it returns it works fine.

**Comment by simon-wh** [comment]
Has anyone still experienced this issue on v0.6.2b?

**Comment by simon-wh** [comment]
@gradius-v Do you have a log file for when that happened?

**Comment by gradius-v** [comment]
Yes, but it shows no errors. Aurora also doesn't crash, it makes LGS hang. Unplugging the Powerplay mat & restarting Aurora immediately restores funtionality.
[2018-09-02 18.06.39.log](https://github.com/antonpup/Aurora/files/2343539/2018-09-02.18.06.39.log)

**Comment by simon-wh** [comment]
@gradius-v you might be able to avoid restarting aurora by going into settings -> Device manager and stopping and starting the Logitech device

**Comment by simon-wh** [comment]
@gradius-v Actually, could you try [this build](https://ci.appveyor.com/project/antonpup/aurora/build/0.6.2b-467/artifacts), I've implemented what I mentioned above but I cannot test it properly in the vm I'm using.

**Comment by gradius-v** [comment]
Just tried it. G903/Powerplay lighting survives resume from sleep, but now I have to wait ~10sec at the login screen before the keyboard lets me type my password. Maybe make it configurable wich devices to disconnect before sleep?

**Comment by simon-wh** [comment]
@gradius-v The hook that I used for tracking sleeping/resuming seems to trigger when the lockscreen appears, I can see about getting it to trigger after unlocking if you run into the issue again

**Comment by simon-wh** [comment]
@mmmboost @ChickenJoe124 @KairuByte Could you try the build I linked above and see if it solves it for you as well?

**Comment by simon-wh** [comment]
Going to close this issue for now, if anyone runs into this issue again let me know!

**Comment by gradius-v** [comment]
I came back for me. If I let the PC sleep several hours and LGS is dead every single time i resume.

**Comment by simon-wh** [comment]
@gradius-v By any chance could you see if that is an LGS issue by not having Aurora open when sleeping it? With what I've setup to disconnect from the SDK when going to sleep it shouldn't be doing anything to LGS

**Comment by gradius-v** [comment]
Thanks, I will test the new build as soon as I'm home.

**Comment by gradius-v** [comment]
Works as it should ! LGS now survives a long sleep.

**Comment by simon-wh** [comment]
@gradius-v Awesome! Thanks for getting back to me!

**Comment by yiweitech** [comment]
@simon-wh hey, so I'm on 0.6.3 and I'm having this issue when I set windows to auto log in (sign in options > never require password). I think bypassing the lock screen also bypasses the trigger you implemented to start the device again. Thank you!

**Comment by simon-wh** [comment]
@yiweitech So it turns off but doesn't turn on again when you wake up? Could you make a new issue for it?

**Comment by stdedos** [comment]
@simon-wh still happens for me for `v0.6.4b-604`. New issue or bump this one?

I have a Wooting II / Logitech G502.

When resuming, devices have ther "original" lighting effects. Then, "after some time", Aurora adds one snapshot of the activated profile (`Ctrl`+`Alt`+`Shift`+`CPU %`+`Mem %`+`Audio Visualization`), and then freezes forever.

Aurora CPU usage is 2%~4%, the tray-right-click menu freezes forever open, and window (if I manage to open it) stays white forever and it is almost un-responsive (however, it responds with a huge delay to e.g. `WinKey+Shift+Left/Right` keys).

**Comment by Zarainia** [comment]
I also see a similar issue with a Razer keyboard. Often when waking from sleep, it'll take on the effect from Synapse, but kind of glitchy since some of the Aurora lighting seems to show through. Either restarting Aurora or turning Chroma Connect off and on again from Synapse fixes the problem.

**Comment by gradius-v** [comment]
After updating to GHUB because of a new G903 Hero this is back. Aurora is completely dead after sleep/resume..

**Comment by timdonovanuk** [comment]
@simon-wh Still an issues now, have to kill the process and restart aurora to get my keyboard to light up.

Keyboard is drevo blademaster pro. Not sure where the log file lives, can't see it in app directory.
