### ISSUE TITLE
Profile wont load with game

### ISSUE THREAD

**Issue by Julius971** [antonpup/Aurora#1029]
### What are you experiencing an issue with?

- [ x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [x ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [x ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
Aurora should load the Rainbow Six Siege Profile

### Actual behavior:
It doesn't

### How often does this problem occur?
Every Time

### Please describe the steps to reproduce this issue:
Create a new Profile for Rainbow six siege and test it

### What is the version of Aurora you are experiencing this issue with?
0.6.0b

### Does the previous version of Aurora have this issue?
i have no idea

**Comment by simon-wh** [comment]
Do you have the generic profile setup with the correct game exe?

**Comment by Julius971** [comment]
I setup a new profile and selected the wanted exe.

Julius

**Comment by simon-wh** [comment]
That doesn't help. I'm asking, have you definitely selected the exe which is running when the game is running? (I don't own rainbow six so I can't check myself, but a lot of games have a game launcher that launches that actual game exe which is the one you need to select, not the launcher). Also, if you reckon that is correct could you provide your log file?

**Comment by diogotr7** [comment]
I can confirm that aurora works with the game using "RainbowSix.exe" as the executable. 0.6.1-dev4

**Comment by Julius971** [comment]
Then the bug seems to occur out of another reasen for me🤔 i will try to figure it out

Julius

**Comment by simon-wh** [comment]
@Julius971 You said you're running v0.6.0b, have you tried updating and using v0.6.1-dev4?

**Comment by Julius971** [comment]
Did this zhis morning, now i cant even load a percentage layer to a custom profile😂

Julius

**Comment by Julius971** [comment]
My aurora says no😂 ill try a full reinstall.
Are there any more files excelt the files in appdata?

Julius

**Comment by simon-wh** [comment]
@Julius971 The only files are in %appdata%/Aurora and the directory that you're running aurora from
