### ISSUE TITLE
Praise, Comments, and Questions!

### ISSUE THREAD

**Issue by TBrozovich** [antonpup/Aurora#103]
Hey Anton, 
Thanks so much for the fantastic software. I just got my g910 spectrum last night and Aurora is working fantastically on it. 

I read through most of these comments and issues and found open ended answers to my questions but these were a month+ ago and was wondering if there was any change. 

1. Logitech G keys... I know the SDK does not support the G keys as of right now, I was just curious if you had any update or insight as to if they will be adding support for this or a time frame of when it may happen. 

2. Asus Aura... I have a MoBo with rgb headers and this could be amazing to sync the case with the keyboard and mouse. Just curious if this would at all be possible to integrate with Aurora.

3. Is there a link you could send giving a tutorial on how to tweak the Aurora profiles. For instance the Overwatch profile, if it would be possible to change the WASD default colors while in game. Hopefully this isn't a stupid question haha.

Thanks again for all of your work!

**Comment by antonpup** [comment]
Glad you're liking Aurora!

1. I will check in again with Logitech in a few weeks on the progress of the extra keys and other stuff.
2. It was suggested before, I don't have one. But if they have an SDK, I will gladly add support for it.
3. Umm for the most part, customization can be done within Aurora. In the case of Overwatch, the game itself controls which keys light up and what color. The only change that Aurora provides in terms of effects, is a brightness adjustment. With that said, I believe the game lights up keys based on the user key binds.

**Comment by TBrozovich** [comment]
Thanks for the reply! I look forward to updates and new features. Keep it up!
