### ISSUE TITLE
Aurora immediate crash after startup, no window showing up

### ISSUE THREAD

**Issue by Postknowledge** [antonpup/Aurora#1030]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Program window should startup and load

### Actual behavior:
After running the program, the RGB on my keyboard shuts off for a second, and then turns back on. Aurora fails to open. It seems to initialize with my corsair CUE software during that time, as shown in the log, and in the CUE it says a third party software is controlling it. However that stops and goes back to normal, after about a second.

### How often does this problem occur?
Every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1.  Running the program

### What is the version of Aurora you are experiencing this issue with?
0.6.1-dev4, tried on the other dev versions as well, same issue

### Does the previous version of Aurora have this issue?
The previous version, 0.6.1-dev3, did have this issue.

### Please include any logs, screenshots, or files that are related to this issue:
https://pastebin.com/qbSwRnEq

**Comment by simon-wh** [comment]
Could you try deleting %appdata%/Aurora to see if that changes anything?

**Comment by Postknowledge** [comment]
Just tried that, nothing changed.

**Comment by simon-wh** [comment]
@Postknowledge Can you double check that you have all the [prerequisites installed](https://github.com/antonpup/Aurora#how-to-install)?

**Comment by Postknowledge** [comment]
I have the C++ redist. installed, but it appears that 4.5 framework can't install because I already have 4.7

**Comment by Postknowledge** [comment]
@simon-wh figured it out. Aurora would not open while i had MSI Afterburner running, even in the background. After closing it, works fine now.
