### ISSUE TITLE
Keyboard lighting stuck when I start aurora

### ISSUE THREAD

**Issue by the27club** [antonpup/Aurora#1031]
### What are you experiencing an issue with?

- [x ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [x ] Performance problems
- [x ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Lighting to work with Aurora profiles

### Actual behavior:
Keyboard lighting is stuck.

### How often does this problem occur?

This problem occurs... every time I start Aurora

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Starting LGS
2. Starting Aurora
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... 0.6.1 d4

### Does the previous version of Aurora have this issue?
The previous version, 0.6.1 d3, did have this issue.

### Please include any logs, screenshots, or files that are related to this issue:
https://imgur.com/gallery/XhA4i

**Comment by simon-wh** [comment]
Do you have the Desktop Application and Keyboard lighting enabled? If you're not sure, try moving %appdata%/Aurora somewhere else (as it stores all the settings) and if that solves your issue then one of the settings you have on is causing the issue.

**Comment by the27club** [comment]
https://imgur.com/HaUeZOi this is what my settings look like. i will try to move the folder right now.

**Comment by the27club** [comment]
it does not solve the issue

**Comment by simon-wh** [comment]
In your settings you have the global brightness set to 0.
