### ISSUE TITLE
Request for marvo scorpion kg935 keyboard

### ISSUE THREAD

**Issue by SirDante345** [antonpup/Aurora#1034]
Hello there. Could you please add proper support for the Marvo scorpion kg935 keyboard? i hope you can do it 😄 because i want to use Aurora i love the program, keep the nice work !

**Comment by simon-wh** [comment]
I can't find any SDK available for that keyboard so there isn't much I can do to support it without physical access to the device to reverse engineer it. If someone else who has it could do that it could be supported, but otherwise not.
