### ISSUE TITLE
Aurora + Logitech G810 + Razer Synapse 3 with Philips Hue Integration

### ISSUE THREAD

**Issue by Schaekel** [antonpup/Aurora#1035]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [x] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [x] Enhancement suggestion
- [ ] Device issue
- [x] Other, (Fill in another type of issue here)

### Expected behavior:
Aurora Wrapper for Logitech functional while simultaniously Razer Synapse 3 allows Philips Hue integration for e.g. Overwatch.

### Actual behavior:
Maybe not a "bug" within Aurora, but maybe there is a way to handle this problem within the Aurora software:

While using the Aurora Wrapper for e.g. Overwatch (which works fine with my Logitech G810), Razer Synpase 3 is not able to find the Overwatch process. Thus the new Philips Hue lightning integration of the Razer Synpase 3 software does not work.

When I delete the Wrapper dlls in the Overwatch folder, the Razer software is able to find the Overwatch process and Philips Hue lightning works. 

Currently I have to decide to use Philips Hue with Synapse 3 or Logitech G810 Lightning within Aurora, both is not possible at the same time (or at least I did not find a way to enable this).

### How often does this problem occur?

Every time.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Patch Overwatch (create Razer Chroma SDK DLLs in Overwatch folder)
2. Start Synapse 3 with Philips Hue synchronisation working
3. Play Overwatch. 

### What is the version of Aurora you are experiencing this issue with?

beta v.0.6.1-dev4

### Does the previous version of Aurora have this issue?
Did not test it, I expect the same issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
This will be sorted once I add support for Philips HUE once I've finished reworking the device layout system (which is a bit delayed due to me having the flu.) See #358 for updates
