### ISSUE TITLE
Add support for the 5zig mod in minecraft

### ISSUE THREAD

**Issue by cinnamoneel** [antonpup/Aurora#1037]
### What are you experiencing an issue with?

- [ ] Aurora
- [x] Aurora supported game, (Fill in the game)
- [x] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [x] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### What to support:
add support for the 5zig mod in minecraft

### Actual behavior:
it has support for razer, logitech, and other devices, i am not in any way a devoloper in any way but i think that it would make it easy.

**Comment by diogotr7** [comment]
I just tested it and it works very inconsistently with the logitech patch. In the debig popup the keys showed so im pretty sure it didnt go straight to LGS. i have a g810

**Comment by simon-wh** [comment]
I think if I was going to add support for Minecraft I'd do it directly rather than doing it through a mod which seems to do quite a lot more (which not everyone may want), so I'm going to direct this to #334
