### ISSUE TITLE
Crashes on Startup 

### ISSUE THREAD

**Issue by rasl2002** [antonpup/Aurora#1039]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [x] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
The app would start up like normal.

### Actual behavior:
Explain here what happened instead.
It crashed. (Because I by accidentally hide the desktop profile.)

### How often does this problem occur?

This problem occurs... (Every time)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Hide the desktop profile 
2. Close the app
3. Open the app 

### What is the version of Aurora you are experiencing this issue with?

My version is... (v0.6.1.Dev4)

### Does the previous version of Aurora have this issue?
The previous version, ((v0.6.1.Dev3), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.
![screenshot 6](https://user-images.githubusercontent.com/33687071/37981288-904cadf8-31ed-11e8-9683-ad6d25f7e37f.png)

**Comment by estevanlandivar** [comment]
im with the same bug please help

**Comment by simon-wh** [comment]
Try deleting %appdata%/Aurora and if that doesn't do anything delete everything from the folder the Aurora exe is in and redownload & install it.

**Comment by estevanlandivar** [comment]
it worked thanks

**Comment by simon-wh** [comment]
Fixed with the above commit
