### ISSUE TITLE
G910 game profiles not working

### ISSUE THREAD

**Issue by Leweegibo** [antonpup/Aurora#104]
Hi, just landed myself the G910 Orion Spectrum (the newer 910 with normal keycaps...not the 810).
Loving Aurora so far, set up a great desktop lighting profile but cant get it to run in games. 
I have tried CS:GO, GTAV, Rocket League and Payday2.
I have followed and re-checked the "first time instructions for Logitech" and have run the wrapper patch as well as the individual patches for the games. Also set games to run as Admin.
I have both and all C++ Redists installed.

If i click the profile in Aurora it will change, however it won't change in game and stays as the desktop profile.

I've probably missed something simple but can't figure it out!
Thanks

**Comment by antonpup** [comment]
That is very strange. Can you post your latest log here? Should be located in the logs folder inside Aurora's directory.

CSGO and Rocket League should work without the wrappers. Try launching CSGO for example, when in main menu try to tab out and then tab back into CSGO. Aurora should be able to pick it up.

For GTA 5, I'm sure you patched logitech with the wrapper. It should be working, have you tried any Logitech or Razer demo apps? They should be working. [Add me on steam](http://steamcommunity.com/id/pupant/), so I can send you debug versions to figure out why wrappers aren't functioning.

**Comment by Leweegibo** [comment]
I have tried alt+tabbing no luck.

should i have physically installed some sort of logitech SDK? i just have the Gaming Software installed.

here are my logs
[2016_16_08.txt](https://github.com/antonpup/Aurora/files/424235/2016_16_08.txt)
[2016_17_08.txt](https://github.com/antonpup/Aurora/files/424236/2016_17_08.txt)
[2016_18_08.txt](https://github.com/antonpup/Aurora/files/424237/2016_18_08.txt)

**Comment by Leweegibo** [comment]
Hey i sorted it out, i wasn't running Aurora as administrator, DUH!
It is all working as intended now, thanks again for your time via steam!
