### ISSUE TITLE
DOOM support

### ISSUE THREAD

**Issue by S0und** [antonpup/Aurora#1042]
So yesterday chroma support was added for for Doom:

https://bethesda.net/community/topic/198659/doom-chroma-support-added

I copied the razer wrapper dll-s into the root of the .exe, but didn't worked. Interestingly, there is a "CChromaEditorLibrary.dll" dll in to root folder, and it's necessary, so removing it will hang the game. 

Could it be that ID is using the Chroma API through that dll, since it's part of the official Chroma effect editor?

**Comment by brainbug89** [comment]
Could be. Maybe we need a new wrapper. :thinking:

**Comment by diogotr7** [comment]
I got doom working in this branch. https://github.com/antonpup/Aurora/tree/chromawrapper-update

Video: https://streamable.com/jv9o1

**Comment by S0und** [comment]
@diogotr7 can confirm, it works fine with Doom and Quake Champions, meanwhile not affecting OW

Thanks!

**Comment by jigsaw345** [comment]
@S0und i am very new to this, but ive been trying to configure and get all the different profiles for the games working. so far only dying light has worked completely. but GTA and the rest either stays or one color or the keyboard goes black. i really want the doom profile to work, but i have no idea how to configure or install it in aurora. can you please help me
im running a corsair k95 Platinum

**Comment by Caleb10E** [comment]
@S0und It took me a minute to figure out as well, but I got it working with DOOM. I haven’t tried it with anything else besides Fortnite, which still doesn’t work.

Make sure you’re on the version of Aurora from Diogo’s branch (v0.6.2b-442). Now find your DOOM directory and delete the two patch files (RzChromaSDK.dll and RzChromaSDK64.dll). Open Aurora and make sure there’s no custom DOOM profile; if you made one, delete it. Now open the Overwatch profile, go to Overview, and use the Patch Overwatch button to patch your DOOM directory again. That should do the trick.

**Comment by jigsaw345** [comment]
@Caleb10E i downloading the top, the most recent
https://github.com/antonpup/Aurora/releases/tag/v0.6.2b

followed your instructions, but the keyboard goes black and stays black while running it

**Comment by Caleb10E** [comment]
@jigsaw345 There's your problem, that's not the version with the DOOM fix. This is the one you want:
https://ci.appveyor.com/project/antonpup/aurora/build/artifacts

Download either the exe or zip and do the steps I posted earlier with that version.

**Comment by jigsaw345** [comment]
alright ill give it a shot
thanks :)

**Comment by jigsaw345** [comment]
yes it worked! thank you so much @Caleb10E :)

you wouldnt happen to have a fix for gta as well??
or maybe this latest patch fixxed it
stays white when i go in game and doesnt change colour ever haha

**Comment by Caleb10E** [comment]
If that same method doesn't work for your GTA directory as well, then you'd just to wait for another update.

I'm pretty sure there's a branch off of an older version that has a GTA V profile. Problem is you'd lose the DOOM compatibility with that older version.

**Comment by diogotr7** [comment]
GTA is weird even if you have officially supported Logitech stuff. I was able to get it working by reinstalling Logitech gaming software, but it is still inconsistent.

**Comment by jigsaw345** [comment]
yeah true, anywhere to find the old gta support page?

**Comment by Caleb10E** [comment]
Hey @diogotr7 I use a color shift animation for my default profile, and that version with the DOOM fix is making the color transitions pretty choppy. Not sure what's causing it, but it wasn't happening on the last v0.6.2b.
