### ISSUE TITLE
Masterkeys Pro S Enter Key not working

### ISSUE THREAD

**Issue by Guacalaquerico** [antonpup/Aurora#1043]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [X] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [X] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Key should light up when selected

### Actual behavior:
Key never lights up

### How often does this problem occur?
Always

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1.  Selecting MasterKeys Pro S with United States Layout
2.  Applying any profile or effect to the enter key

### What is the version of Aurora you are experiencing this issue with?

My version is... v0.6.1-dev4

### Does the previous version of Aurora have this issue?
Yes

**Comment by AppleFM** [comment]
i can confirm.. same thing happened to me.. need a fix for this

**Comment by redvxns** [comment]
The same thing happened to me as well but i'm not sure if the devs gonna update the software anywhere soon.

**Comment by kentnek** [comment]
Same problem here! Got the bug after updating to the latest version.

**Comment by simon-wh** [comment]
See #1057, likely the same issue
