### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by RubiRubyx** [antonpup/Aurora#1045]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
The program should launch

### Actual behavior:
Explain here what happened instead.
Program crashes on start ("Program stops working" window comes up)

### How often does this problem occur?

This problem occurs... (Every time)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Launch the program (As admin or not, it happens with both)
2. Program launches
3. Program stops working ("Program stops working" window comes up)

### What is the version of Aurora you are experiencing this issue with?

My version is... (File version: 0.6.1.0 and the Product version: 0.6.1-dev4)

### Does the previous version of Aurora have this issue?
The previous version, (Not on 0.6.0b Beta, but after i followed the disabling csgo and dota 2 profiles from the logitech software the program did nothing else), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

No logs

**Comment by woloss** [comment]
I have no problems with launching Aurora itself, but I can't reach Aurora UI, it will crash. Using old versions won't help, deleting settings as  well.

**Comment by simon-wh** [comment]
@RubiRubyx @woloss Could you both post your log files?

**Comment by RubiRubyx** [comment]
@simon-wh Unfortunately i uninstalled aurora long ago, do i do not have those logs
