### ISSUE TITLE
With iCUE out, think we'll ever be able to configure fans and light strips, too?

### ISSUE THREAD

**Issue by BranWar** [antonpup/Aurora#1055]
I configure all my profiles on iCUE specifically with the way I have my fans and light strips on my case, and I absolutely love it! I was wondering if there are any plans to get Aurora to recognize strips and fans too.

**Comment by brainbug89** [comment]
@simon-wh said, that he is reworking the device layout system: https://github.com/antonpup/Aurora/issues/841#issuecomment-369259568

I don't know if that include fans and light strips. :thinking:

**Comment by S0und** [comment]
The question is, what type of light strips do you use. 

Personally i'm using this Wifi controller: https://ae01.alicdn.com/kf/HTB15eAuXU6FK1Jjy0Fpq6zFqVXaT/DC5-24V-Wireless-WIFI-LED-RGB-Controller-RGBW-Controller-IR-RF-Remote-Control-IOS-Android-for.jpg

If you also have this, you can use it with aurora, i wrote a device script for it:
https://gist.github.com/S0und/7f68ca0b156b8dd2f167ba1264e28fb8

Don't forget to change the device's ip.

**Comment by brainbug89** [comment]
@S0und nice script. Maybe I'll buy such a Wifi controller, too. Until now I thought about a raspi/arduino to connect a light strip but a Wifi controller looks like an easy solution.

But I think @BranWar wants to use the light nodes and fans of Corsair with iCUE. :wink:

**Comment by BranWar** [comment]
Sorry, I've been away from my computer for a bit... 

But, it was more just a random thought since iCUE now includes the light strips, fans, and RAM if it would be easier to include them in Aurora with its SDK. I'm also working on a bit of a hardware mod to get a PS4 controller to light up with CUE, so I figured if we get the light strip support though it,
 that would be a little added fun since I use my controller for Rocket League and GTA V.

 Those two comments you linked, @brainbug89, look pretty promising, though!

**Comment by S0und** [comment]
@vicdilou 
a) ...Aurora\Scripts\Devices\rgbcontroller.cs
After that it should show up in Aurora's device manager as 'RGB Strip Contoller'

b) I used my Router connected devices section to find out the device's IP.

**Comment by vicdilou** [comment]
@S0und 
Thank you it works
But how do you change light or add effect on it ?

**Comment by S0und** [comment]
> but when the esc key is off the LED strip is white instead of being off

Yeah that working as intended. The light strip is using the ESC key's color. Every frame Aurora sends it's color command to every key. If i'm not limit that behavior it would just spam the LED controller for no reason. I know this can be annoying, for example if you use Away Effects, and the Matrix effect does not hits the ESC key all the time, so the light strip is "flickering" between green and white. 

You can change that here: https://gist.github.com/S0und/7f68ca0b156b8dd2f167ba1264e28fb8#file-rgbcontroller-cs-L68

**Comment by vicdilou** [comment]
@S0und thank you
I find that earlier and add an "extra" key in keyboard and now the light strip is independent

**Comment by samwell1** [comment]
Hello! Does this script work on a digital RGB led strip (WS2812b)? And do leds make the same effects as raspberry pi? I was trying to find a way to work on Arduino, but I found this implementation interesting. Thank you.

**Comment by S0und** [comment]
@samwell1 Imo it's not gonna work, since the WS2812b is an individually addressed led strip, I'm pretty sure there is code out that you can use. This Wifi LED controller only sends a single color to the led strip.

**Comment by S0und** [comment]
@vicdilou 

https://gist.github.com/S0und/7f68ca0b156b8dd2f167ba1264e28fb8#file-rgbcontroller-cs-L83

Fixed the script, i changed the whole method! So if Aurora sends a absolute black color (255, 0, 0, 0) i will send that color to the device directly, without modifying it. 

The reason why black was actually whitish, because i process the color before i send it to device. I'm reducing color "brightness" so the LED-s will receive the target color at 30% brightness instead of 100%. I have a 5meter long led strip, and using a 5A power supply. If i run the device with full brightness i will fry it (I'm talking from experience 😀 ). Couple weeks ago i ordered a few 4x 25x25mm heat sinks. Hopefully they will help to cool the device, and i might be able to run it on a higher brightness setting. 

`hsv.V = 0.3; // <- Brightness settings`

You can change the brightness with this, default is 30%

**Comment by vicdilou** [comment]
Cool !
I have this Lightstrip ([https://fr.aliexpress.com/item/5m-LED-Strip-5050-RGB-Waterproof-60leds-m-IP65-tape-SMD-12V-flexible-light-24k-wifi/32704232184.html?spm=a2g0s.9042311.0.0.bffq5G](url))
I leave at 30% where I can increase ?

**Comment by S0und** [comment]
@vicdilou 

Looks like this is a 3A adapter, you can change the brightness. Imo the best way to test it, to gradually increase it. If the plastic enclosure is not hot to the touch, increase it, use it for an hour, if it's still not warm, go for 50%, and so on. But be careful because if it's overheats, the enclosure can melt.

**Comment by vicdilou** [comment]
@S0und 
Ok I will try it
thank you !

**Comment by S0und** [comment]
@vicdilou 

Unfortunately, even at 30% brightness the plastic case started to melt: https://i.imgur.com/vIFbOKi.jpg

so i went full YOLO: https://i.imgur.com/okjNnOg.jpg

**Comment by Turbolious** [comment]
@S0und 

I cannot for the life of me get this to appear under the device manager tab. 
Could you make a small write up on the install, it seems simple but i may be missing a small step.

Thanks in advance

**Comment by Turbolious** [comment]
@S0und 
That is what i presumed and have already done.
https://puu.sh/AlMmq/a7bb422724.png
I know the lights and controller work fine as i am currently using them through google home, but i would love to have them sync up with the keyboard, mouse and mouse pad. 
I have also set the IP to the correct address in the file.

**Comment by S0und** [comment]
@Turbolious Could you upload a log? 

1. Close Aurora!
2. Start Aurora (this will create a brand new, clean log file)
3. Go to Settings->Debug
4. Click on 'Show Logs Folder'
5. Find the latest log file, it should be like 2015-05-14 <few seconds earlier then your current time>.log
6. Open and paste the logs content to: https://pastebin.com/ then Create a paste

**Comment by Turbolious** [comment]
@S0und 
Here you are good sir

https://pastebin.com/EsHUt8Bg

**Comment by Turbolious** [comment]
Looks like i just needed a reinstall....however it is now connecting and i can start and stop the controller through aurora, but it doesn't change color at all with the ESC key.

Here is the log https://pastebin.com/w5Etk0sp

**Comment by Turbolious** [comment]
@S0und 
I got it to work, My google home and Magic home were taking control of the controller. Which makes me think, could we get a google home/alexa to control the controller which in turn would change the other peripheral colors? Some how the controller would just need to be set as the primary color feed device and all the others could sample off of it.

**Comment by Gurjot95** [comment]
Try this
https://github.com/antonpup/Aurora/pull/1421
