### ISSUE TITLE
Interactive effect on mouse

### ISSUE THREAD

**Issue by vicdilou** [antonpup/Aurora#1056]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (Fill in problematic devices)
- [x] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [x] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
When you press a key of the mouse their are an interactive effect like on the keyboard (key wave, key fade...)

Thank you

**Comment by simon-wh** [comment]
It'd be difficult to make some effects like the key fade as I'm not aware of any mouse having leds on the actual buttons. In theory I could make it have a key wave that originates at the location of the button, but all of this is a lot of work for something very minor, so I don't think it is going to be in the scope of this project currently, sorry.
