### ISSUE TITLE
Masterkeys Pro L ENTER Key not Lighting Up

### ISSUE THREAD

**Issue by ChickenJoe124** [antonpup/Aurora#1057]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x ] Aurora supported device, (CoolerMaster MasterKeys Pro L)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
I expect the ENTER key to light up

### Actual behavior:
The ENTER key does not light up

### How often does this problem occur?

This problem occurs... (Every time)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Plug in the device
2. Try to light up key
3. key will not light up

### What is the version of Aurora you are experiencing this issue with?

My version is... (v0.6.1-dev4)

**Comment by Thelgow** [comment]
Damn it, after last patch fixed the numpad, I hadn't noticed Enter not being lit.  
Same here.

**Comment by ryanmeblin** [comment]
Same exact problem on Masterkeys Pro M. After some digging, I confirmed that [build 0.6.1-dev4-286](https://ci.appveyor.com/project/antonpup/aurora/build/0.6.1-dev4-286/artifacts) does not have this issue. Some later build broke the Enter key on CM keyboards. I recommend reverting back to the older build until this issue is re-addressed.

**Comment by redvxns** [comment]
Thanks for the confirmation im gonna revert back to the old build.

**Comment by Thelgow** [comment]
Just a heads up, if I recall 6 on number pad didn't light up, hence the need for the beta build.  
I believe any changes you make for num6 apply to num5, any to num5 apply to num4.  
Or it was 4 didn't light up and it went the other way but you'll see.

**Comment by kentnek** [comment]
@ryanmeblin thanks for the confirmation, I just reverted back to this build and it worked.

**Comment by simon-wh** [comment]
Could someone with this issue test on the [latest build](https://ci.appveyor.com/project/antonpup/aurora/build/artifacts)? It's got changes for the MK750, not sure if it will work for the others. I don't know why builds after 286 would specifically break the enter key, if it was going to break anything I would have thought it'd be a lot more significant, as I haven't changed the code related to the enter key.

**Comment by Thelgow** [comment]
@simon-wh That 308 build seems to have fixed it. Enter is good, as is 4,5,6 and on numpad.  
I'm not seeing any blank keys.

**Comment by husseinfahmy** [comment]
@Thelgow Is this build in the latest release? I have the latest release but still hitting this on my pro S unfortunately

**Comment by simon-wh** [comment]
@husseinfahmy Try [this build](https://ci.appveyor.com/project/antonpup/aurora/build/0.6.1-dev4-325/artifacts) if you're still having issues. The builds mentioned are all after dev4.

**Comment by husseinfahmy** [comment]
@simon-wh Didn't fix it unfortunately

**Comment by simon-wh** [comment]
@husseinfahmy Could you try the [latest build](https://ci.appveyor.com/project/antonpup/aurora/build/0.6.1-dev4-337/artifacts)? There have been some more changes to CM stuff.

**Comment by husseinfahmy** [comment]
@simon-wh The new build didn't automatically fix it, but I realized that if I change my layout from automatic to US, it fixes it.

**Comment by husseinfahmy** [comment]
Aaaand now my right arrow key is dim...
