### ISSUE TITLE
LightFX Wrapper not working in Vermintide 2 after new Vermintide update

### ISSUE THREAD

**Issue by FTWOblivion** [antonpup/Aurora#1058]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [x ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Should launch game and start using Alien Lightfx

### Actual behavior:
Game doesnt launch when usingAurora wrapper, worked before the newest vermintide update. Now it says an unvalid file is in binaries. I think it  has to do with the latest anti cheat update

### How often does this problem occur?
<!-- Every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Replace LightFx.dll in Vermintide 2 with aurora wrapper
2. Crash
3. :(

**Comment by sausje** [comment]
Yep has to do with the new anti-cheat that does file integrity checking nonstop.

We could post and ask the devs to make an exception for the exact dll that we use for lighting, but otherwise I don't think we can do much about it.

**Comment by FTWOblivion** [comment]
Yeah I figured. It's just bummed me out because I literally just got the game and it was working great for a day before the new anticheat update lol. Darn timing of mine

**Comment by sausje** [comment]
Need to add an update to this, seems like the new patch did completely broke it for me.
It's suddenly not working anymore for me either now.

However, I did message their support asking if we could get an exception for our .dll file within the anti-cheat they got.

**Comment by Thelgow** [comment]
Yea, I just launched and got the error. I forgot to backup the original, so I just deleted the existing one and the game actually launched with it not present. Very sloppy.

**Comment by simon-wh** [comment]
There isn't much I can do if the Anti-Cheat is blocking the LightFX wrapper, maybe they'll make an exception, but I doubt it.
