### ISSUE TITLE
Razor Wrapper help

### ISSUE THREAD

**Issue by mrrioes** [antonpup/Aurora#1060]
### What are you experiencing an issue with?
- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?
- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issuex
- [x] Other, (Fill in another type of issue here)

I´m having trouble to apply the razer wrapper. I´m using a Logitech G410 btw.
as far as I understood I need to patch every razor supported game seperately.
so far so good. But i dont know where to apply the patch.  should the two dll files which the patch is creating already be anywhere? 
Tried with ruiner and KSP so far. 
Thanks

**Comment by simon-wh** [comment]
You need to make sure the game you're applying it to has support for Razer Chroma effects. The patch needs to be applied to the directory of the game containing the executable file
