### ISSUE TITLE
Aurora Chugging My RAM

### ISSUE THREAD

**Issue by DerkJerker** [antonpup/Aurora#1063]
### What are you experiencing an issue with?

- [X] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [X] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [X] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [X] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [X] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Operate without utilizing upwards of 6gb of RAM

### Actual behavior:
Continues amassing ram usage until programs on my PC begin to slowdown and eventually crash out.

### How often does this problem occur?

This problem occurs... (Every time the program is active for an extended period of time)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Downloading Aurora
2. Running Aurora with a g910 Spectrum
3. Running for an extended period of time

### What is the version of Aurora you are experiencing this issue with?

My version is... (v0.6.0b)

### Does the previous version of Aurora have this issue?
Unknown

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

Image to be provided later, when I can get a shot of the task manager and 6gb under use by Aurora

**Comment by simon-wh** [comment]
Could you please update to [v0.6.1-dev4](https://github.com/antonpup/Aurora/releases) and let me know if this is still occurring.
