### ISSUE TITLE
Cannot use FN Key as key bind to switch profiles

### ISSUE THREAD

**Issue by NeelAPatel** [antonpup/Aurora#1064]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [x] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [x] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
When pressing FN Key, the key should show up in the profile's keybind box

### Actual behavior:
FN Key doesn't show up

### How often does this problem occur?
100% of the time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Create a new profile
2. Assign key to 'Keybind to activate profile' 
3. Press FN Key. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (v0.6.1-dev4)

### Does the previous version of Aurora have this issue?
The previous version, (unsure), did/did not have this issue.

---------------------------------
I have a Corsair Strafe that I managed to set up so that pressing the media control's function keys work without pressing FN, using the CUE2 software. Now I wanted to use Aurora to light up those keys by switching profiles or even better, toggle a layer, within the profile, but currently is not possible.

**Comment by SnakePin** [comment]
Normally keyboards doesn't send FN key status to PC. So PC can not know if FN key is pressed or not.

**Comment by simon-wh** [comment]
What @SnakePin said.
