### ISSUE TITLE
Extremely Large log files (237.3 GB !)

### ISSUE THREAD

**Issue by ZedeN1** [antonpup/Aurora#1065]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [x] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, (Extra large logs)

### Expected behavior:
Logs should not be greater than a few hundred MB

### Actual behavior:
237.3 GB of log files!!!

### How often does this problem occur?

This problem occurs... (not sure, but based on number of logs it has happened 5 times, but for long periods of time)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. No idea
2. Important to note that the location reported in Log file below does not exist on my PC. (C:\projects\aurora\Project-Aurora\Project-Aurora\Utils\BitmapUtils.cs)
3. C:\projects does not exist on my system. Aurora is installed under C:\Program Files\Aurora

### What is the version of Aurora you are experiencing this issue with?

My version is... (Fill in here)
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\Windows\system32
Executing Directory: C:\Program Files\Aurora
Launch Directory: C:\Program Files\Aurora
Processor Count: 4
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.6.1-dev4-305

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.
Never had this issues before

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: https://pastebin.com/qYBcYmCh     contains only first 100 and last 100 lines, files impossible to open with Notepad++ due to size. Full files impossible to upload aswell due to size. I will keep the latest log but remove the rest.
For screenshots, you can use: https://imgur.com/a/1UgSb   WinDirStat of size
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by h4d3z** [comment]
Having the same problem

**Comment by ZedeN1** [comment]
I have updated to stable v0.6.1-dev4 and haven't had the issue yet (5days), but could I suggest creating a setting for max log file size to prevent the issue from resurfacing later on?

**Comment by diogotr7** [comment]
I'm using the latest commit build (Aurora-v0.6.1-dev4-306-rjohynqj) and got a 6GB file filled with this line 
`[ERROR] 20:39:21: Error encountered in the Equalizer layer. Exception: System.Runtime.InteropServices.COMException (0x80070490): Element not found. (Exception from HRESULT: 0x80070490)
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   at NAudio.CoreAudioApi.MMDeviceEnumerator.GetDefaultAudioEndpoint(DataFlow dataFlow, Role role) in C:\projects\aurora\NAudio\NAudio\CoreAudioApi\MMDeviceEnumerator.cs:line 74
   at Aurora.Settings.Layers.EqualizerLayerHandler.CheckForDeviceChange() in C:\projects\aurora\Project-Aurora\Project-Aurora\Settings\Layers\EqualizerLayerHandler.cs:line 188
   at Aurora.Settings.Layers.EqualizerLayerHandler.Render(IGameState gamestate) in C:\projects\aurora\Project-Aurora\Project-Aurora\Settings\Layers\EqualizerLayerHandler.cs:line 213`

**Comment by simon-wh** [comment]
I've tried to make changes in the past to prevent errors like this causing big log files. I'll try and make some attempts again to sort this out (as well as sorting out the errors that are present)

**Comment by simon-wh** [comment]
@ZedeN1 I've fixed the error that was spamming your log in the commit. However, I'm still going to try and implement something to catch repeated lines which may cause large log files

**Comment by diogotr7** [comment]
This has been fixed with #1920
