### ISSUE TITLE
Contributing 

### ISSUE THREAD

**Issue by kekkokk** [antonpup/Aurora#1067]
Hi guys,
I'm a developer but I'm totally new to visual studio / c++ projects.
My intention is to help to incorporate AURA SDK for Asus since I own a claymore core and I'd love to have these features in Aura.

Yesterday I spend an hour and I was able to make Aura Sdk works with the provided dlls in a simple project and change selectively the key colors.
I'd love to help making a wrapper and testing features but I don't know how to start.
Can you provide some basic info on how to import and compile the project?

I will really appreciate,
thanks!!

**Comment by kekkokk** [comment]
Nevermind, found a way

**Comment by simon-wh** [comment]
Have a look at how the other devices are implemented under the Devices
directory, might be best to find whatever device has the closest SDK design
to the Aura SDK, duplicate that and modify it as required. These have been
changed a bit under the dev-layout-rework branch but it isn't too hard to
convert them over. I'm planning at some point to move the Device
implementations into plugins, but that is likely to be a while off. I'm
currently taking a break from the project so I can focus on uni work for my
upcoming exams, so I might not be making changes for a few weeks.

**Comment by kekkokk** [comment]
I have successfully implemented everything to work with the asus claymore. 
I have to fix some stability issues but should not be a problem. 
I'll clean the code in the weekend and maybe do a PR.
Only problem is that AuraSDK works only in x86 :/
this could be an issue :D

**Comment by kekkokk** [comment]
Feel free to check out https://github.com/kekkokk/Aurora/tree/asus_integration

Api should works, tested with Asus Claymore Keyboard (layout IT).
I plan to add other features in the weekend (motherboard mouse and GPU).
Looking forward for your advices.

ps. it only compile in x86 as I said... :/

**Comment by brainbug89** [comment]
What happens when you compile it in x64?

**Comment by kekkokk** [comment]
that the aura sdks always return 0 or memory violation access :/

I'll work to make a wrapper that communicates via COM to the main x64 aurora project

**Comment by simon-wh** [comment]
@kekkokk You might want to mainly look at the Keyboards and Mice for now as implementing other devices will be difficult and won't work very well until I've finished the device layout system rework (which I've delayed until after I finish my exams).

**Comment by kekkokk** [comment]
Yeah, I think that atm is the only option. I'm quite busy this week, but from monday I think I'll start to implement a way to communicate with the x86 sdk so I can make a PR to integrate everything.
I'll also take a moment to look at the layout since I "brutally" implemented it and idk if it will work well with other layouts. Unfortunately there's no documentation and I only have the number of keys and leds from the sdk. no way to know wich one will light up in different layouts :/
My only option was to make a mapping from my IT layout and the default aurora key mapping
