### ISSUE TITLE
Percent Effect Layer Crash

### ISSUE THREAD

**Issue by BastiJava** [antonpup/Aurora#1069]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
Percent Effect Layer or Percent (Gradient) Effect Layer should work.
### Actual behavior:
Explain here what happened instead.
Aurora crashed
### How often does this problem occur?

This problem occurs every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Create New Custom Profile
2. Create new Layer with Percent or Percent (Gradient) Effect Layer
3. Aurora crash and deleted the profile

### What is the version of Aurora you are experiencing this issue with?

My version is beta v0.6.1-dev4

### Does the previous version of Aurora have this issue?
I don't know

### Please include any logs, screenshots, or files that are related to this issue:

https://imgur.com/a/OmW7STx The Crash Report

**Comment by simon-wh** [comment]
I believe this was fixed in the dev branch, if you want a build with this fixed look [here](https://ci.appveyor.com/project/antonpup/aurora/build/artifacts)
