### ISSUE TITLE
Permit LGS/CUE to handle desktop lighting

### ISSUE THREAD

**Issue by antonpup** [antonpup/Aurora#107]

**Comment by inheritanceXIV** [comment]
Desktop lighting? what does that entail?

**Comment by antonpup** [comment]
The desktop lighting means that brand utilities like Logitech Gaming Software or Corsair Utility Engine will be able to provide lighting effects when Aurora is on the desktop profile, allowing more customization and only provide gaming profiles.

The reason why there's no Corsair demo on [http://aurora.lastbullet.net/](http://aurora.lastbullet.net/) is because Razer and Logitech use a transparent image of a keyboard with changing colors behind them. So I could easily swap my own color effects behind the transparent keyboard images. But Corsair shows off their keyboard lighting via a gif, without transparency. So I decided not to spend time making my own transparent image, and focus on Aurora.

**Comment by TBrozovich** [comment]
So has this been implemented or is this a plan to incorporate? I think this option would be FANTASTIC for my set up and only let Aurora take over for game profiles. Thanks!

**Comment by antonpup** [comment]
@TBrozovich This is going to be a feature in the next version.

**Comment by Bluecat16475** [comment]
Is this feature coming soon? I love Aurora, but would really prefer to use the LGS lighting on my desktop, specifically for the star effect (unless it is already in and I am completely missing it). Keep up the great work!

**Comment by brainbug89** [comment]
See https://github.com/antonpup/Aurora/issues/241#issuecomment-265612108 https://github.com/antonpup/Aurora/issues/280#issuecomment-269521061 https://github.com/antonpup/Aurora/issues/226#issuecomment-264584363
