### ISSUE TITLE
Aurora doesn't start.

### ISSUE THREAD

**Issue by ASD2223** [antonpup/Aurora#1070]
### What are you experiencing an issue with?

- [x ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Aurora doesn't start.

### Actual behavior:
Aurora doesn't start. It crashes right away.

### How often does this problem occur?
Everytime. Tried reinstalling and it's still not working.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Aurora doesn't start.

### What is the version of Aurora you are experiencing this issue with?
Aurora 0.6.1-dev4

### Please include any logs, screenshots, or files that are related to this issue:
https://imgur.com/a/PZI7xTM

**Comment by simon-wh** [comment]
Could you try deleting %appdata%/Aurora?

**Comment by simon-wh** [comment]
@ASD2223 Any feedback?
