### ISSUE TITLE
Aurora not startup with Windows

### ISSUE THREAD

**Issue by Deskowicz** [antonpup/Aurora#1076]
### What are you experiencing an issue with?

- [x ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x ] Other, (Startup)

### Expected behavior:
Aurora should startup with Windows

### Actual behavior:
Aurora not start after Windows load. I checked in options "Start with Windows", but after close and open 
it uncheck. When i open it manually it ask me for permission.

### How often does this problem occur?

This problem occurs... (always)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. 
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (v0.6.1 dev4)

### Does the previous version of Aurora have this issue?
The previous version, (0.6.1 dev3), did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

https://pastebin.com/T3EdWQ4p

**Comment by simon-wh** [comment]
From your log it appears that the issue is a result of the Task Scheduler service not running. If you're still experiencing this issue, could you try the fixes mentioned [here](http://troubleshooter.xyz/wiki/fix-task-scheduler-service-is-not-available-error/)
