### ISSUE TITLE
Fast switching profiles

### ISSUE THREAD

**Issue by Deskowicz** [antonpup/Aurora#1077]
Is it possible to fast switch between Profiles? I want to make 2 profiles to Fortnite, one with building keys backlight, and second with shooting keys.

I bind "Q" as a key to both profiles, but it works randomly, or really slow, because sometimes it switch immediately, and sometimes i need to press key 2-3 times or more to switch them.

Regards

**Comment by simon-wh** [comment]
Hm, without looking at the code specifically I assume assigning both to the same key results in the first/last one it checks being the one loaded. I'll add a cycle/toggle option that'll allow you to swap between different profiles using a particular key.

**Comment by simon-wh** [comment]
Added thanks to @Wibble199 with #1143
