### ISSUE TITLE
Fortnite

### ISSUE THREAD

**Issue by Bastek100** [antonpup/Aurora#1079]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [x] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, (Fill in another type of issue here)

### Expected behavior:
Solve my problem

### Actual behavior:
Effects do not work with fortnite open. Is there any way to make them work and I'm guessing Aurora doesn't support Fortnite so when will it?

### How often does this problem occur?

This problem occurs... everytime

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Loading up fortnite with an aurora effect running 
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... Most recent 

### Does the previous version of Aurora have this issue?
The previous version may have not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by Bastek100** [comment]
It seems to be doing the same thing with CS:GO, which is supported by Aurora...

**Comment by Deskowicz** [comment]
Open Aurora, scroll the left side with profiles till the end, there you will find "+". Press it and find path to fortnite file. Something like Epic Games/Fortnite/FortniteGame/Binaries/Win64/FortniteClient-Win64-Shipping.exe . Select that file and press "Open". Now you have Fortnite profile, there you can add layers as you want.
