### ISSUE TITLE
UI Redesign

### ISSUE THREAD

**Issue by antonpup** [antonpup/Aurora#108]
Redesign the UI to allow for more advanced effects, while remaining easy to understand.
- [x] Include a layer manager, allowing users to reorganize layers, edit individual layers, and add/remove new ones. (This will replace the current "tabs" system)
- [x] Split every current tab into their own Layers.
- [x] Let the UI scale, up to a significant amount or full screen.
- [ ] ~~Include a "basic" and "advanced" modes. Basic will be similar to what Aurora offers right now. Advanced will allow users to add & edit layers.~~
- [ ] ~~[Not Sure] Split up the virtual keyboard into 3 sections: Keyboard, Mouse/Peripheral, Extra lights~~
- [ ] ~~[Not Sure] Add ability to overlay the debug image over the virtual keyboard. (Will allow for easier debug and a good visual alternative to current design)~~

**Comment by antonpup** [comment]
Here's a small demo of the layers. The CPU and RAM usages are their own "Percent Layers" with transparent background colors. There are two interactive layers, one is for Key Wave and other is Key Wave (filled) creating this "Circle with a boundary" effect.

![percent interactive_demo](https://cloud.githubusercontent.com/assets/3421963/18424965/f2961150-7869-11e6-8435-0188dffe63c5.gif)

![CPU layer](http://puu.sh/r8l5Q/12d8ece91b.png)
![RAM layer](http://puu.sh/r8l6p/6daa66457d.png)
![Interactive 1 layer](http://puu.sh/r8l6H/e3063ed3c7.png)
![Interactive 2 layer](http://puu.sh/r8l6Q/57974c2046.png)

These layers will work with all profiles.

**Comment by simon-wh** [comment]
Completed.
