### ISSUE TITLE
Crash loop when deleting only profile of a game

### ISSUE THREAD

**Issue by Xion4762** [antonpup/Aurora#1083]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [x] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Deleting aurora profile shouldn't cause a crash

### Actual behavior:
Crash and unable to reopen without crash

### How often does this problem occur?
Every time

### Please describe the steps to reproduce this issue:
1. Delete only profile for a game (I did CSGO in particular)
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?
Newest as of writing this (can't check since I can't open)

### Does the previous version of Aurora have this issue?
Unknown

### Please include any logs, screenshots, or files that are related to this issue:
https://pastebin.com/rCNM0Yk0

**Comment by simon-wh** [comment]
You shouldn't be able to delete the last profile as at least one needs to exist for stuff to work. Try deleting %appdata%/Aurora/Profiles/csgo, that should recreate everything for that and set it back to default. I'll make it so it doesn't allow you to delete the last profile, and if you delete it manually it will just recreate it.

**Comment by Xion4762** [comment]
Thanks for the temporary solution. The long term solution also sounds solid.

**Comment by simon-wh** [comment]
Fixed with above commit
