### ISSUE TITLE
Keyboard will flash in a "medium damage/in danger state" (orange/yellow) in ROTTR after first bear attack even after healing/out of danger

### ISSUE THREAD

**Issue by F0XTHREE** [antonpup/Aurora#1086]
### What are you experiencing an issue with?

- [ ] Aurora
- [ X] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [X ] Aurora supported device, (Logitec G910 +G502)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [X ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [X ] Visual/lighting bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [] Device issue 
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Keyboard should no longer flash as if the player damaged/ in danger after healing/ player is out of danger or major battle has ended.

### Actual behavior:
Keyboard continued to flash orange if the player is no longer in "in danger" state

### How often does this problem occur?
After first encounter with the bear very early game

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Using Aurora with logitec g910 + 502 mouse
2. Playing rise of the tomb raider until first bear encounter, the game will put you into a damaged state until you heal (scripted event in game) even after healing, the lighting will reflect as if the character is damaged. 
3.Will reset to normal after fast travel or /game/aurora/computer restart

### What is the version of Aurora you are experiencing this issue with?
Current release as of 5/7/18

### Does the previous version of Aurora have this issue?
did not test, first time using Aurora However after restarting my computer and re-entering the game after the fight, the keyboard lighting went back to normal. (UPDATE: also resets after fast travel after such event)

**Comment by F0XTHREE** [comment]
After continued game play you end up fighting the bear again, however the orange flashing started before the fight, indicating that the orange flashing means you are in potential danger maybe? Even after the fight is over the keyboard continues to flash, I will keep playing without a restart this time and see if it goes away as this may be intentional, but I am unsure.

**Comment by F0XTHREE** [comment]
UPDATE: so after being able to fast travel for the first time back to the first camp you are able to make, the "in danger orange" flashing stops, which may indicate a bug with the game profile after events like this occur.

**Comment by F0XTHREE** [comment]
Seems to have come back randomly while re-exploring the first area. Haven't been damaged yet as far as I can tell and there are no enemies around.

**Comment by F0XTHREE** [comment]
After fast traveling a second time it did go away again. I did record what happened via cell phone video.

**Comment by simon-wh** [comment]
The lighting effects shown for RoTTR is just whatever the game normally sends to the Razer devices, we have no control over what is shown and when. It's possible there is an issue with the wrapper causing it to light incorrectly, however, from your description it sounds like the lighting effects aren't being generated correctly by the game.
