### ISSUE TITLE
Question on overwatch: Does it gets health status?

### ISSUE THREAD

**Issue by Ricardonacif** [antonpup/Aurora#1091]
Hey man, thanks for doing this great tool! I would like to ask you, is there anyway of reading if your hero is with low health on the game for a special effect?

Thanks,

**Comment by diogotr7** [comment]
I dont think so, as far as i know the effects are native to the game and all the info is processed by it. we just get access to the colors and keys.

**Comment by simon-wh** [comment]
What @diogotr7 said.
