### ISSUE TITLE
MasterKeys Pro M not lighting up

### ISSUE THREAD

**Issue by hsalsdnas** [antonpup/Aurora#1092]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (CoolerMaster MasterKeys Pro M)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
I expect the keys to light up.

### Actual behavior:
None of the keys light up.

### How often does this problem occur?

This problem occurs... (Every time)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Start Aurora.
2. Try to light up any key.
3. None of the keys light up.

### What is the version of Aurora you are experiencing this issue with?

My version is... (v0.6.1-dev4-308)

### Does the previous version of Aurora have this issue?
The previous version, (v0.6.1-dev4), did not have this issue.

**Comment by simon-wh** [comment]
Could you try on the [latest build](https://ci.appveyor.com/project/antonpup/aurora/build/artifacts) and let me know if it still occurs?

**Comment by hsalsdnas** [comment]
It's still not lighting up.
[Latest log](https://pastebin.com/bmjzCFPi)

**Comment by simon-wh** [comment]
@hsalsdnas Can you try [this build](https://ci.appveyor.com/project/antonpup/aurora/build/0.6.1-dev4-322)? The build you ended up using was from a PR that isn't fully up to date with the latest changes on the dev branch.

**Comment by simon-wh** [comment]
Okay, could you try out [this build](https://ci.appveyor.com/project/antonpup/aurora/build/0.6.1-dev4-323/artifacts) for the commit above?

**Comment by hsalsdnas** [comment]
Build 323 fixed it, thanks.

**Comment by simon-wh** [comment]
Awesome! Sorry for the confusion
