### ISSUE TITLE
logitech g502 gaming mouse

### ISSUE THREAD

**Issue by iamruthle55** [antonpup/Aurora#1095]
the g 502 gaming mouse from Logitech kinda works but keeps resetting the colour profile and constantly wants to open a new aurora window on my pc

**Comment by moogathicc** [comment]
yeah is there a fix for this? Starting to annoy me now

**Comment by simon-wh** [comment]
I don't think I quite understand exactly what is happening with your issue, could you give me a more detailed description or a video of what you're describing?
