### ISSUE TITLE
Overwatch character theme persists after match starts

### ISSUE THREAD

**Issue by Thoth2020** [antonpup/Aurora#11]
If I pick Hanzo, for example, at the start of a match, the theme of the keyboard is a subdued, earthy tone. However, once the match starts, if I switch to a different character, the theme of the keyboard does not change.

Using Logitech G910.

**Comment by antonpup** [comment]
Lighting for Overwatch is entirely controlled by the game. If it was able to set lighting in the beginning, I don't see why it can't set lighting mid-game. I'll see if I can reproduce this bug.

**Comment by Thoth2020** [comment]
Also Soldier 76's theme is all black. That is, no lights. Not sure if this is a bug or not, I get the feeling this is by design.

**Comment by antonpup** [comment]
If you're on Logitech, enable enhanced color for Logitech in devices tab. From observation, Logitech is much darker than Corsair and Razer in terms of color. It's possible that Soldier has a background color that is very dim, which wouldn't show that well on Logitech keyboards.

**Comment by antonpup** [comment]
Just played a game of Overwatch, was not able to reproduce this bug.
