### ISSUE TITLE
Shared mode and/or disable profiles

### ISSUE THREAD

**Issue by MaitreDede** [antonpup/Aurora#110]
Hi,

I have a Cosrair K95. Is it possible either to work as shared mode, or disable game profiles (either via GUI or keyboard shortcut) so I can have CUE effects in combination of Aurora ? Sample : on desktop, I would like to have CUE effects shared with memory/processor indications...

Thanks.

**Comment by antonpup** [comment]
I don't think it's possible to do that, either Aurora applies effects to the keyboard or CUE does. If you do both, the keyboard will start flickering.

**Comment by MaitreDede** [comment]
I have made a simple test : putting CueSDK in shared mode with CueSDK.Initialize(exclusiveAccess = false), a custom application profile. And no flicker : only keys that seams not to be defined in your layout (multimedia keys) does not seams to remain "dark". So I think that with a shared profile mode, there can be a set of keys that remains "untouched", by Aurora, so other applications can set them.

I think this would be usefull for example if you have an Outlook plugin that lights up G18 when you receive a spam during gaming sessions, or a Teamspeak plugin driving other key lights.

:)

**Comment by antonpup** [comment]
I played around with this a bit more. My corsair mouse ended up being wonky with lighting, at times it would just stay completely black.

Another problem with this, is that Logitech and Razer don't offer such options. So it would be a "Corsair exclusive feature", which I don't really want to do.
