### ISSUE TITLE
Aurora crashed after added new layer

### ISSUE THREAD

**Issue by aui14th** [antonpup/Aurora#1107]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
New layer added

### Actual behavior:
Aurora crashed.

### How often does this problem occur?

This problem occurs... (everytime I try to add new Percentage (Gradient) Effect Layer )

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Run Aurora
2. Add Percentage (Gradient) Effect Layer 
3. Aurora crashed

### What is the version of Aurora you are experiencing this issue with?

My version is... (beta v0.6.1-dev-4)

### Does the previous version of Aurora have this issue?
Never done this before.

### Please include any logs, screenshots, or files that are related to this issue:

https://pastebin.com/WfVUmFkT

**Comment by simon-wh** [comment]
Were you adding it to a generic profile? (One created from selecting an application) If so, that's been fixed in the dev branch and will be in the next release

**Comment by aui14th** [comment]
No, I added from new Lighting Profile. I just tried the new version and i guess it kinda works but Aurora crashed first time i tried to add new layer (so I run Aurora again and i can add new layer now)
