### ISSUE TITLE
Warframe Razer Effects not supported

### ISSUE THREAD

**Issue by LightShaft** [antonpup/Aurora#1108]
Hello,
Just reporting that Warframe doesn't work with Aurora, I have tried with another software (RETC, this one https://github.com/MartB/RETC) and it works like it should, but I would like Aurora to support the game so I can light up not only my Corsair keyboard but also my logitech mouse and headset
To install the wrappers, I used the "Overwatch profile" and directed the installation in Warframe directory, I also tried the option "Install Aurora Wrapper Patch for Razer" in the settings
After that I have seen that when launching the Warframe launcher, the launcher actually "clean" the directory and delete the wrappers, ticking "read only" in the properties of the wrappers work and the files are not deleted.
This way, RETC work, not Aurora, and I find this a bit strange cuz the wrappers are different but I though they were both supposed to "emulate" Razer effects.
Voilà, hope it will be fixed, I'll keep in touch if I made it work by myself

**Comment by simon-wh** [comment]
Hm, I had tried to get the wrapper to work on Warframe before with no luck, I'll try and see if I can figure out what the problem is. There is an issue already open for this #663, so direct any continuation to that
