### ISSUE TITLE
Aurora Fatally Crashed. No resources folder?

### ISSUE THREAD

**Issue by Mikhaiilov** [antonpup/Aurora#1109]
### What are you experiencing an issue with?

- [x ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
When i first installed it, everything was fine. Opened it no problems. 

### Actual behavior:
Today though, when i open it, it gives me a fatally crashed error saying:

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files\Aurora\Resources\desktop_icon.png'.

### How often does this problem occur?
Every time now. 

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. No idea  what happened. It just broke
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is...       0.6.1-dev4

### Does the previous version of Aurora have this issue?
Have not tried previous versions

### Please include any logs, screenshots, or files that are related to this issue:

https://pastebin.com/DaRbEbA6

**Comment by simon-wh** [comment]
Have a look at #1039
