### ISSUE TITLE
"Generic Application" zone keyboard layout

### ISSUE THREAD

**Issue by MaitreDede** [antonpup/Aurora#111]
I am trying this "generic application" mode, but it seams that there is a problem with the keyboard layout.
I have a K95 Azerty/

I have created a new "Color Zone", and assigned keys "AZE" (first letter row) but the highlighted keys are "QWE" on the keyboard.

**Comment by antonpup** [comment]
It's an issue with the layout. I'll fix it for next version. For now, just assign the QWE keys for AZE lighting
