### ISSUE TITLE
Aurora doesn't hook into the Corsair Utility Engine SDK

### ISSUE THREAD

**Issue by GreenGhost21** [antonpup/Aurora#1112]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
Aurora should use the CUE SDK to display lighting effects

### Actual behavior:
Explain here what happened instead.
Aurora fails to hook, preventing lighting effects from being displayed.

### How often does this problem occur?

This problem occurs... (Every time)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Starting Aurora
2. Going to Device Manager under Settings
3. Clicking Start on the Corsair devices section

### What is the version of Aurora you are experiencing this issue with?

My version is... (beta v0.6.1-dev4-314)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

Admittedly, have not tried other versions, but other versions had other issues (such as producing mouse lag in Overwatch, if I remember correctly).

### Please include any logs, screenshots, or files that are related to this issue:

https://pastebin.com/VGgt65YD

And yes, I made sure CUE SDK was enabled in the Corsair Utility Engine.

**Comment by simon-wh** [comment]
Which version of CUE are you running? According to the latest changelog of CUE.NET, CUE 1 is no longer supported with the version of the SDK that is included.

**Comment by GreenGhost21** [comment]
I'm on CUE 2, but I tried CUE 3 as well. Neither worked. 

Tried the latest build, still not working, unfortunately.

**Comment by GreenGhost21** [comment]
Any updates to speak of?

**Comment by simon-wh** [comment]
@GreenGhost21 I don't know what's wrong, do you have anything potentially helpful in your log? Also, what exact version of CUE are you using? It's working perfectly for me with [this build](https://ci.appveyor.com/project/antonpup/aurora/build/0.6.1-dev4-320) and CUE 3.2.87

**Comment by GreenGhost21** [comment]
Huh. Now it works for some weird reason. How odd. 

I do have an issue with the Clevo Keyboard flickering (and possibly an issue with Overwatch + Aurora lagging the mouse), but I'll worry about those issues another time.
