### ISSUE TITLE
Key Assigning

### ISSUE THREAD

**Issue by BaumeistervonOsk** [antonpup/Aurora#1113]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [x ] Other, Key Assigning

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x ] Other, A Key is no abled to be assigned

### Expected behavior:
Explain here what should happen.
The FN Key should be added to the Lightened Keys
### Actual behavior:
Explain here what happened instead.
Aurora does not recognise it, if i press "FN"
### How often does this problem occur?

This problem occurs... Everytime

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Create a new Layer
2. Add an Effect
3. Try to add the FN Key

### What is the version of Aurora you are experiencing this issue with?

My version is... beta v0.6.1.-dev4

### Does the previous version of Aurora have this issue?
This is the first version of Aurora i use

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
When you're assigning keys to a layer you select them on the virtual keyboard, you don't press the keys to add them. If you're trying to use a keybind or something, the FN key won't work because it isn't an actual key, it is never sent to your OS

**Comment by BaumeistervonOsk** [comment]
It worked, Thank you.
