### ISSUE TITLE
"Device Manager" settings don't work after disabling a device

### ISSUE THREAD

**Issue by luolimao** [antonpup/Aurora#1116]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [x] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:

Clicking "Enable" on the "Device Manager" settings page should re-enable that device.

### Actual behavior:

Going to the "Device Manager" page causes the entire Aurora app to start flickering and lagging _heavily_. None of the buttons work on that page, including "Refresh All" and "Restart" which seem to do nothing.

### How often does this problem occur?

Aurora worked fine before I disabled several devices using the Device Manager settings. I wanted to re-enable them later on, and ran into this issue.

This problem occurs anytime I navigate to the Device Manager page. Uninstalling/reinstalling did not fix the problem, because I believe the app stores the Aurora settings in a user directory, and it doesn't get deleted on uninstall.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Disable all devices from Aurora's Device Manager.
2.  Close Aurora.
3. Attempt to re-enable any device.

### What is the version of Aurora you are experiencing this issue with?

My version is...  0.6.1-dev4

### Does the previous version of Aurora have this issue?
I have no idea, I just started using this app.

### Please include any logs, screenshots, or files that are related to this issue:

It seems like there's nothing suspicious in the logfile that would indicate an issue, but I'm attaching it anyway for thoroughness.

https://gist.github.com/luolimao/dfe8a133ec2c4fb39e5afe611124df79

**Comment by luolimao** [comment]
I dug through and figured out that deleting `%appdata%/aurora` seems to fix the issue. But this folder should really be removed in the uninstaller (and there should be a way to reset the app without having to find this folder manually).

**Comment by simon-wh** [comment]
I haven't been able to replicate your issue on the current dev branch, but I believe that is due to changes I made to how the Devices refresh which must have fixed the issue.
