### ISSUE TITLE
[Request] Destiny 2 support for the included Razor Profile/Custom Profile

### ISSUE THREAD

**Issue by F0XTHREE** [antonpup/Aurora#1117]
There is a custom profile out there for Destiny 2 for Logitech G910 users that another Aurora user had created, however it doesn't seem to work. (did manage to get it working one time, however it has since stopped for an unknown reason)

Found here: https://modworkshop.net/mydownloads.php?action=view_down&did=21126
(if anyone out there can seem to get this to work please let me know how you did it)

However I have noticed Destiny 2 comes with its own Razor profile, so in theory a patch may allow its use with Aurora maybe?

**Comment by F0XTHREE** [comment]
I have also reached out to the OG creator of that profile to see if he could help the community out with the issues many have been having with the profile as well. 

For the savy profile creators out there, if anyone can find the issues as to why the profile may not be showing up with the G910, here is the original link he gave to his profile on gitlab:

https://gitlab.com/apinto/aurora-profile-destiny2

**Comment by apintocr** [comment]
Greetings @F0XTHREE 

I am not the creator of the first profile, just the second one (https://gitlab.com/apinto/aurora-profile-destiny2)

I've updated the profile today to match the Aurora  new profiles (I haven't noticed it was changed).

At this moment I'm using the _bleeding edge_ builds, specifically this one: https://ci.appveyor.com/project/antonpup/aurora/build/0.6.1-dev4-323/artifacts

Please check if it works for you.

**Comment by F0XTHREE** [comment]
Thank you very much to getting back! I will try it out today and see what happens, will report back.

**Comment by F0XTHREE** [comment]
Just tested it and it is now showing in preview/in game now, thank you very much @apintocr.  I did notice you got rid of the class specific binds and everything seems to be onto one, is that because the game changed and it is all universal now? I am new to Destiny and am not sure if that is the case which is why I ask regardless it works so thank you for coming back and making that change. I'm sure a lot of players will appreciate it.

**Comment by F0XTHREE** [comment]
well it was good, then the profile went dark after about 20 mins into a session. I will restart it and see if I can replicate the issue

**Comment by F0XTHREE** [comment]
well it was working =/. After about 20 min in the game the profile went dark, it is now dark in preview as well.

**Comment by F0XTHREE** [comment]
I also Uninstalled my current version of Aurora and got the latest build and still the same results.

**Comment by apintocr** [comment]
I honestly have no idea about what the issue can be.
Does that happen if you create your own profile?
If it works with your own profile, just copy my settings, it's easy.

This is probably unrelated to the profile itself.

**Comment by simon-wh** [comment]
You might have accidentally disabled the profile or set the global brightness (or keyboard) brightness to 0%. Can you check those in the settings? If it's not working for you, try deleting %appdata%/Aurora/Config.json, as it will reset all the core settings of Aurora.
