### ISSUE TITLE
Razer devices not changing with Aurora since shortly after last Synapse 3 update

### ISSUE THREAD

**Issue by jackjack86** [antonpup/Aurora#1119]
### What are you experiencing an issue with?

- [x ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [? ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
Layers and effects to be applied when checked in Aurora.

### Actual behavior:
Explain here what happened instead.
no changes on device(s) (Razer Lancehead TE and Blackwidow V2 TE) or in Aurora (cannot see any changes in Aurora's UI, no debug, layout remains static....)

### How often does this problem occur?

This problem occurs... (Fill in here)
Just started today after Synapse 3 update and Windows restart.  Tried restarting Aurora and Synapse 3.  Disabling/Stopping devices in Aurora's Device Manager.  Reinstalling Ayrora....

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. 
2. 
3. 

As I have no idea how it got to this state and no changes can be made in logs or UI, I cannot give a clear answer here.  Attaching logs to verify.  Nothing can be changed on my end, will need further guidance to see where the problem lies,  new user. less than a day of use

### What is the version of Aurora you are experiencing this issue with?

My version is... (6.1dev4)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.
 have not tried any previous version (working straight from 6.1dev4)
[2018-05-30 14.37.12.log](https://github.com/antonpup/Aurora/files/2061411/2018-05-30.14.37.12.log)
[2018-05-31 17.55.13.log](https://github.com/antonpup/Aurora/files/2061412/2018-05-31.17.55.13.log)
[2018-05-31 22.50.53.log](https://github.com/antonpup/Aurora/files/2061413/2018-05-31.22.50.53.log)
[2018-05-31 23.02.22.log](https://github.com/antonpup/Aurora/files/2061414/2018-05-31.23.02.22.log)
[2018-05-31 23.04.48.log](https://github.com/antonpup/Aurora/files/2061415/2018-05-31.23.04.48.log)
[2018-05-31 23.24.43.log](https://github.com/antonpup/Aurora/files/2061416/2018-05-31.23.24.43.log)

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
Hm, I'm not sure why that is happening, the logs aren't showing anything, it appears to be initialising correctly. You could try [this build](https://ci.appveyor.com/project/antonpup/aurora/build/0.6.1-dev4-324/artifacts) which has an updated version of the .net wrapper we use for the Razer sdk which might make a difference.

**Comment by jackjack86** [comment]
Inexplicably, everything seems to be working fine now.  No restart of OS or any applicable apps (Aurora or Synapse 3).  The effect layers for cpu and ram usage were a little buggy (only showing gradient up to current percentage and no other coloring past that) but this was easily remedied by selecting all keys in my background layer.  Will attach most recent log and DL the Razer sdk build just in case things go awry.
[2018-05-31 23.24.43.log](https://github.com/antonpup/Aurora/files/2064574/2018-05-31.23.24.43.log)

**Comment by jackjack86** [comment]
I seem to have reproduced the bug.

1) start aurora
2) mess with effect layer(s) (this was done by changing blink threshold on cpu/ram usage and/or changing alpha on primary/secondary in interactive layer [not entirely sure which but changing alphas was last change i made before Aurora stopped responding to changes])
3) Aurora locks up and reverts back to default synapse lighting (however no changes happen when using chroma apps so this may be a synapse 3 bug)

Also, I was using the Razer build (6.1-dev4-324) you suggested when I reproduced this bug.  Furthermore, Synapse 3 reverts back to turning off chroma apps when restarting.  Will post to the Razer forums to see if this is ultimately the issue.

**Comment by simon-wh** [comment]
@jackjack86 When you say "Aurora locks up", do you mean it freezes? If so, is there any error in the log file that may be associated with the lock up?

**Comment by jackjack86** [comment]
The UI will lock up.  I can still navigate but any LED indication is missing and I cannot select keys nor make any changes after this has occurred.  The debug bitmap window is also missing.

Synapse 3 just had an update that fixed the Chroma Apps toggle, and seems to have fixed my issue as well.

**Comment by simon-wh** [comment]
@jackjack86 Are you saying with that last part that your issue is sorted? I'm not sure which part you mean has been fixed.
