### ISSUE TITLE
Key wave and Ambilight slow

### ISSUE THREAD

**Issue by Wolfieeewolf** [antonpup/Aurora#1122]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [x] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior;
on key press key wave with sliders all the way up should be super fast

with ambilight turned on should map what is on the screen in time with keys

### Actual behavior:
Key wave is very slow. have both slider turned up and still moving at 1 key per second.

Ambilight is very slow takes 5 to 10 seconds to update keys from what is on the screen 

### How often does this problem occur?

This problem occurs... (Everytime)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Select key wave turn it up and press keys
2. Select ambilight and it should duplicate the screen

### What is the version of Aurora you are experiencing this issue with?

My version is... (0.6.1-dev4-326-bjcgyhcx)

### Does the previous version of Aurora have this issue?

Yes, all versions did this

Believe this could be a CPU problem. I have a very old computer. A dinosaur if you will - it's an i7 860 with 16 GB ram. I'm thinking this could be the issue as it takes a bit of computing power to do some of the effects but all the Razer Chroma effects work ok with nil slow down so maybe not. I'll report it as an issue just in case others are having problems with this on faster computers.

I'm not home right now so can't attach log files but will try and upload them when I can if needed

**Comment by simon-wh** [comment]
Is the lagging the same on the Debug view (Settings -> Debug) and on your keyboard? What cpu usage does it show for Aurora in Task Manager?

**Comment by Wolfieeewolf** [comment]
Not at home right now so can't test. Away for the next few days so will let you know when I get back to my computer

**Comment by Wolfieeewolf** [comment]
I deleted everything and reinstalled the latest dev copy. key wave now seems to work but the ambilight layer is still slow. I'm thinking it has to be the cpu. it's now getting up to 88% and still lagging a lot. If no one else is having issues with this I'm thinking it's my dinosaur computer.

**Comment by simon-wh** [comment]
@Wolfieeewolf It could be, the Ambilight will cause performance issues as it has to constantly take screenshots of your screen, so it isn't that surprising that it would result in high CPU usage. If the key wave is fine now, then I think I'll close this, as that is something that shouldn't be lagging, and if it is fine now then it should be fine.
