### ISSUE TITLE
Aurora fatally crashed

### ISSUE THREAD

**Issue by NiightWiing** [antonpup/Aurora#1124]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
The program is supposed to get launched and open without crashing.

### Actual behavior:
I'm not able to launch the program as it crashes : there's a message explaining the issue, which I don't understand, the only thing I understand is that the crash is about a PNG file named desktop_icon. Then when I close this window, my only option is to exit Aurora.

### How often does this problem occur?

Every time.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Launch Aurora
2. An error window explains the issue.

### What is the version of Aurora you are experiencing this issue with?

I just downloaded the last version that I found on the official website at the time I'm writing my message.

### Does the previous version of Aurora have this issue?
This is the only version I have ever used.

### Please include any logs, screenshots, or files that are related to this issue:
https://pastebin.com/C4G8Svss
https://imgur.com/a/I9Y33nN

**Comment by simon-wh** [comment]
Try deleting %appdata%/Aurora

**Comment by NiightWiing** [comment]
I already tried to uninstall (+ deleting the files) and download again but it doen't fix it ...

**Comment by simon-wh** [comment]
Did you definitely delete all the files in %appdata%/Aurora? It has been known to fix that issue on multiple occasions.

**Comment by simon-wh** [comment]
Just copy-paste the folder before you delete it. Ensure you are deleting the correct thing, it should have stuff like Config.json, Profiles, etc in it

**Comment by NiightWiing** [comment]
Ooohh ok I got you, I deleted it and then launched Aurora and it worked ! Last time I tried to delete this file was when I uninstalled Aurora ... Thank you for your help dude, have a good day/night !
