### ISSUE TITLE
Aurora isn't overwriting my SSE3 settings

### ISSUE THREAD

**Issue by Blakcbird** [antonpup/Aurora#1128]
So, I'm using a Steelseries Apex M750 Fullsize, and the SSE3 engine doesn't have enough options to do what I want it to do, but Aurora does, so I enable Aurora in the SSE3 engine apps, but aurora doesn't want to override my SSE3 settings
https://cdn.discordapp.com/attachments/316643315741097986/455023379070844950/unknown.png
https://cdn.discordapp.com/attachments/316643315741097986/455023550445649940/unknown.png
If there is any other information you would need, tell me in response to this, or add me or discord
Blakcbird#2981

**Comment by simon-wh** [comment]
@Blakcbird Is Steelseries enabled in the Device Manager? Using my Rival 300 I'm not getting any issues

**Comment by SnakePin** [comment]
Dude why "Disable Keyboard Lighting" is enabled, is this a joke or the screenshot is wrong.

**Comment by simon-wh** [comment]
@SnakePin Haha, hadn't even noticed that. Closing this
