### ISSUE TITLE
Corsair K70 RGB layout missing keys

### ISSUE THREAD

**Issue by brainbug89** [antonpup/Aurora#113]
The layout for the K70 missing the multimedia keys:
![k70layout](https://cloud.githubusercontent.com/assets/21130949/17837269/ca6459e2-67ae-11e6-9ad6-d5932e6696f1.PNG)

Also there is no Logo-LED or G1-G18 keys but that doesn't hurt. ;-)

**Comment by antonpup** [comment]
I will be reworking the virtual keyboard system to allow for dynamic addition of keys, so I don't have to make a layout for each keyboard.

**Comment by antonpup** [comment]
This will be addressed with #119.

**Comment by antonpup** [comment]
Resolved. Here's a small demo.

![K95 demo](https://dl.dropboxusercontent.com/u/30675690/Aurora/k95_demo.gif)

**Comment by brainbug89** [comment]
nice :+1:
