### ISSUE TITLE
DPI Keys not lighting up after Aurora wraps over Corsair Framework

### ISSUE THREAD

**Issue by brunodmjr** [antonpup/Aurora#1130]
Corsair Sabre's (mouse) DPI Keys not lighting up after Aurora wraps over Corsair Framework. Changing the mouse response time on Corsair CUE makes the dpi lights to turn on and function normally. Aurora keeps working as expected and without issues after this.

**Comment by simon-wh** [comment]
I assume it's not working because there is no mouse layout that covers the light? Do the other lights on the mouse work with aurora with whatever mouse you've chosen?

**Comment by brunodmjr** [comment]
Yup, it works. Had it tested with wife's g203. There is a layout for the Corsair Sabre, it just ignores the DPI lights. It seems even on purpose, since it makes sense that the DPI lights works independently to show de DPI steps.

**Comment by simon-wh** [comment]
@brunodmjr Wait, so does it work properly with it ignoring the DPI light so that it is lit normally? I haven't looked into it, but if the DPI light works independently with the rest of the lights working, then most likely it's the case that we can't control the DPI light, as when the CUE SDK is connected it normally overrides all lights that are controllable.

**Comment by brunodmjr** [comment]
After Aurora's initialization, the two DPI lights goes completely dark, not responding to DPI changes. The DPI lights only starts to work if I change a major setting in CUE software, like pooling rate. Scroll Wheel and Logo Light works as expected, controlled by Aurora, before and after the pooling rate change.

**Comment by simon-wh** [comment]
I just remembered that I've come across this before, from this issue: https://github.com/DarthAffe/CUE.NET/issues/43 it isn't possible to control the DPI light through the CUE SDK, so there isn't anything I can do

**Comment by brunodmjr** [comment]
It is possible to ignore DPI lights then? Instead of aurora shutting them down, that they continue to work as intended, changing colors when DPI changes with Aurora controlling the rest of the led zones? That would be the ideal solution to me.

**Comment by simon-wh** [comment]
If there is no control of the DPI light through the CUE SDK I can't have any affect on how it acts
