### ISSUE TITLE
Can't get Network bandwidth counter to work

### ISSUE THREAD

**Issue by ginx2666** [antonpup/Aurora#1131]
I'm trying to make a layer that makes certain keys light up as network bandwidth reaches certain values. I'm using Voron scripts, but their use Aurora Internal counters, so might as well post it here.

### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [x] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [x] Other, (Aurora Internal counters)

### What kind of an issue is it?

- [ ] Crash
- [x] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Keys should light up in accordance to bandwidth.

### Actual behavior:
Nothing happens. If I use literally any Aurora Internal counter, everything works fine. I don't know what Aurora considers as "Default Network", and trying to put in any aliases from Get-NetIPInterface aplet to Value source field results in invalid operation exception.

### How often does this problem occur?

This problem occurs only if using Aurora Internal | Default Network.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Add Script layer
2. Pick Voron script
3. Assign keys
4. Put "Aurora Internal | Default Network | Bytes Received/sec" or any of 5 network meters in Value source
5. Watch as the keys don't light up in Aurora window or on keyboard.

### What is the version of Aurora you are experiencing this issue with?

My version is 0.6.1-dev4

### Does the previous version of Aurora have this issue?
No idea.

### Please include any logs, screenshots, or files that are related to this issue:

https://i.imgur.com/GgNylCx.png

**Comment by simon-wh** [comment]
Issues with 3rd party scripts are not issues with Aurora. It gives the impression of it being an Aurora issue, but the "Aurora Internal" stuff, is part of the script, not Aurora.
