### ISSUE TITLE
G910 Orion isnt working straight out after wrapper and instructions

### ISSUE THREAD

**Issue by InvertTails** [antonpup/Aurora#1134]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [x] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Effects should be woiking

### Actual behavior:
G910 seems static although changes slightly when I launch Aurora. Mouse seems to not be affected so it is localized to the keyboard, additionally Aurora acts weirdly and does not show the labels for keys even after reinstall/fresh program. In short, none of the effects I have on my profile are working for the desktop and games as well.

### How often does this problem occur?
It happens every time even after reinstalling drivers and restarting several times

### What is the version of Aurora you are experiencing this issue with?

v0.61-dev4

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

http://puu.sh/AG9RW.png
http://puu.sh/AG9TU.png

**Comment by sausje** [comment]
It looks like you didn't patch the Logitech software, because not even Aurora is showing up in your app list: https://i.imgur.com/ZrFTvWT.png

**Comment by simon-wh** [comment]
@InvertTails Is Logitech initialised in Device Manager? Could you post your log files as well?
