### ISSUE TITLE
BF4, R6S, ETS2 and Fallout 4 profiles

### ISSUE THREAD

**Issue by KILLTROOP** [antonpup/Aurora#1135]
If someone have some profiles for these games i would love to get my hands on those.

**Comment by Ansler** [comment]
I've been trying to come up with something neat for Fallout 4 but 1) I'm still learning the aurora software and everything I can do with it, and b) There is only so much I can do with shades of green. If I do come up with something and it turns out alright I'll share it with you.

**Comment by Ansler** [comment]
Ok, I have an admittedly simple Fallout 4 lighting profile that highlights the default keys and includes a couple of subtle effects. I doubt its the most efficient implementation and there are things I wanted to do but couldn't as I don't know the ins and outs of scripting for Aurora yet but if you want a starting point I hope this is alright. 

[Fallout Green.zip](https://github.com/antonpup/Aurora/files/2109434/Fallout.Green.zip)

**Comment by Wibble199** [comment]
Euro Truck Simulator 2 profile (with game-state integration) has been added to the dev branch (#1105) recently and will be available in the next release.

**Comment by simon-wh** [comment]
This isn't exactly something that should be open as an issue. If you want to discuss profiles then please join the discord: https://discord.gg/YAuBmg9
