### ISSUE TITLE
Help Corsair Strafe "No keyboard detected, please ensure that you have SDK enabled for your keyboard"

### ISSUE THREAD

**Issue by LordZony** [antonpup/Aurora#114]
Anton, thanks for making this great software! I am reallly keen to try it but i cant seem to have it detect my Corsair Strafe RGB keyboard. 

I have Enable SDK checked in CUE but  I keep getting the error of "No keyboard detected please ensure that you have SDK enabled for your keyboard"

I have installed and uninstalled, and countless reboots but it doesnt work. 
error log: http://pastebin.com/tAwKw28S

If anyone could guide me or point me in the right direction, I would be most grateful! Thank you!

**Comment by antonpup** [comment]
Seems CUE isn't initializing sdk. Reinstall CUE.

**Comment by LordZony** [comment]
Hi Anton, i uninstalled, rebooted then reinstalled and rebooted.

then i tried to boot aurora and i got an error message stating that there is missing dll MSCVP120.dll

Aurora loaded anyhow after this message but no luck, still cant detect keyboard :( any other steps I can try?

**Comment by brainbug89** [comment]
MSVCP120.dll is a missing file from Microsoft Visual C++ 2013 (reinstall Visual C++)

**Comment by LordZony** [comment]
Hi brainbug89, yea I did a repair of my Visual C++ redistributable 2015 and that error went away. Unofortunately, I am still stuck with keyboard not detected :( 

I tried changing versions of CUE and also the new beta but couldnt get it to work

**Comment by antonpup** [comment]
You need to repair/install the 2013 version.

Can you also provide your latest log, to see if CUE sdk isn't initializing for a different reason now.

**Comment by LordZony** [comment]
Ah, sorry I thought the latest version 2015 would suffice, pardon my ignorance. I hope this is the problem causing all my issues!

I will install the 2013 version once I reach home and report back with the results! Hopefully it works!

**Comment by LordZony** [comment]
hey Anton and brainbug89, thanks for your help! i installed/repaired my visual 2013 and now it works! silly me

thanks a lot!!

**Comment by antonpup** [comment]
Glad you resolved it. Enjoy Aurora! :D
