### ISSUE TITLE
[Suggestion] Windows lock for lock colour layer

### ISSUE THREAD

**Issue by TheFacelessOne** [antonpup/Aurora#1140]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [x] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Desired behavior:
I have a button to lock my windows key, I would like to be able to use it similar to the lock colour layer

### Actual behavior:
Current options for lock colour are:
Capital, Numlock, Scroll

### How often does this problem occur?
N/A

### Please describe the steps to reproduce this issue:
N/A

### What is the version of Aurora you are experiencing this issue with?

My version is... beta v0.6.1-dev4

### Does the previous version of Aurora have this issue?
N/A

### Please include any logs, screenshots, or files that are related to this issue:

N/A

**Comment by simon-wh** [comment]
Are you referring to a button on your keyboard that disables the windows key? If so, there is no way for us to find out whether it is toggled or not, so it isn't possible for us to do.
