### ISSUE TITLE
Coolermaster CK550 Support.

### ISSUE THREAD

**Issue by Junneh** [antonpup/Aurora#1144]
Hello,

Just want to let u know, CM has a new board out with SDK available. (http://www.coolermaster.com/peripheral/keyboards/ck550/)

Is this already supported via one of the other coolermaster board options? Led options/chip seems similar to previous models :)

Dont have it yet but plan on ordering soon, gateron>cherry :)

**Comment by simon-wh** [comment]
I've already updated the SDK used in Aurora to that version, so CK550 should be supported on the [latest buld](https://ci.appveyor.com/project/antonpup/aurora/build/artifacts)
