### ISSUE TITLE
Crashing when trying to do a percentage effect on Wizard of Legend and Enter the Gungeon

### ISSUE THREAD

**Issue by evocablecrab** [antonpup/Aurora#1145]
### What are you experiencing an issue with?

- [x ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [x ] Aurora Wrapper
- [x ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
I should be able to select percentage values from the game I added for lighting effects.
### Actual behavior:
Explain here what happened instead.
It crashes on selection of the lighting option
### How often does this problem occur?

This problem occurs... (Fill in here) Everytime I try to do that.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1.  Add a game, two Itried were Enter the GUngeon and Wizard of Legend
2.  GO to lighting
3.  Attempt to add a percentage gradient or color.

### What is the version of Aurora you are experiencing this issue with?

My version is beta v0.6.1

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue. I have not used the previous version

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.
![image](https://user-images.githubusercontent.com/10471940/41673226-dd06ba36-7481-11e8-89e8-bb159a7267c5.png)

**Comment by simon-wh** [comment]
This has been fixed in the dev branch, try [this build](https://ci.appveyor.com/project/antonpup/aurora/build/0.6.1-dev4-343/artifacts) if you want a fixed version
