### ISSUE TITLE
Lighting across devices

### ISSUE THREAD

**Issue by dankar3** [antonpup/Aurora#115]
Possibilities for adding support for shared lighting between keyboard/mouse/gpu/rgb case light (ROG gpu/mb/strips light etc etc)

**Comment by brainbug89** [comment]
Shared lighting between keyboard and mouse is already possible with Aurora.

Answer from Antonpup for ROG Aura: "I do not know if they have an SDK. But if they do, I will definitely add support for it."
source: https://www.reddit.com/r/pcmasterrace/comments/4mohjq/aurora_unified_lighting_effects/d3x7r1e

And README.md says: "Planned Features/Support: SteelSeries devices, LightFX devices, LightPack"

**Comment by antonpup** [comment]
My general stance on adding support for devices, as @brainbug89 stated is, "If it has an SDK, I can add support for it".
