### ISSUE TITLE
roccat talk fx (kone pure)

### ISSUE THREAD

**Issue by gitmacer** [antonpup/Aurora#1153]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [X] Aurora supported device, (roccat kone pure)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [X] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
The light color should change.

### Actual behavior:
Nothing happens.
I know that you can control the led. Because I could change the color by using this repository (by using its test file):
[https://github.com/CosminLazar/roccat-talk-csharp](https://github.com/CosminLazar/roccat-talk-csharp)

I don't know why but the key effect is not working. (no breathing, blinking...)
### What is the version of Aurora you are experiencing this issue with?

My version is... (dev4-349)

**Comment by simon-wh** [comment]
I don't think the current implementation of the SDK supports the Roccat mice, I'll try and have a look into this and get it working for you.
