### ISSUE TITLE
Add disk information to LocalPCInfo

### ISSUE THREAD

**Issue by OverDodo** [antonpup/Aurora#1158]

**Comment by simon-wh** [comment]
Um, in LocalPCInfo Memory refers to RAM, not your drive

**Comment by OverDodo** [comment]
Is there a way to get the info from the drive?

**Comment by simon-wh** [comment]
Yes, I can add it, but I doubt I'll add it to this version, I'll add it in the rewrite, if someone wants to make a PR with it they can go ahead.
