### ISSUE TITLE
Animation freezes.

### ISSUE THREAD

**Issue by donaldkieu** [antonpup/Aurora#1159]
### What are you experiencing an issue with?

- [X] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [X ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [X ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Keyboard lighting should be animated (gradient rainbow wave) as well as be able to use Ctr, Win, and Alt shortcut layers

### Actual behavior:
Keyboard will follow animation for a few minutes and then freeze. Animation still moves in application.
Aurora device manage displays "8096 ms" next to MasterKeys Pro S Connected message
Restarting application will not fix issue. Must reboot system to fix.
Reinstalling via redownloading and deleting folder in %appdata% also does not fix.
### How often does this problem occur?

This problem occurs about half the time after computer startup.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Windows Login
2. Aurora Autostart
3.  Wait

### What is the version of Aurora you are experiencing this issue with?
My version is... Beta v0.6.1-dev4

### Does the previous version of Aurora have this issue?
Yes

### Please include any logs, screenshots, or files that are related to this issue:
https://pastebin.com/jS9vG8Rg

**Comment by simon-wh** [comment]
The latency you're having with the device might be an issue with the device/sdk from Cooler Master. The animation is lagging on your device as the sdk is taking a long time to update the lighting from the information we give it, so I don't think there's anything we can do. I think you'll just need to do general troubleshooting

**Comment by donaldkieu** [comment]
I see. Sometimes it would work flawlessly for 1-2hr sessions and other times it would freeze up within a few minutes
