### ISSUE TITLE
Fatal Crash

### ISSUE THREAD

**Issue by denali1** [antonpup/Aurora#1164]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
It shouldn't crash.

### Actual behavior:
Explain here what happened instead.
![image](https://user-images.githubusercontent.com/6053366/42404560-1c694fc6-8158-11e8-8cd0-e3039c3a31c5.png)

### How often does this problem occur?

First time today.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Load Aurora
2.  Play Warframe
3.  Exit Warframe after playing for 8 hours.

### What is the version of Aurora you are experiencing this issue with?

My version is 0.6.1-dev4

### Does the previous version of Aurora have this issue?
No clue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
This has been fixed in the Dev branch, if you keep running into this issue please download one of the "bleeding edge builds" you can find in the readme
