### ISSUE TITLE
Is there anyway to convert this corsair profile for use with Aurora with StarCraft 2?(Logitech G910)

### ISSUE THREAD

**Issue by F0XTHREE** [antonpup/Aurora#1166]
I know the integration of events is not possible, but it looks like this contractor for corsair made a custom lighting profile for corsair keyboards so in theory it may work with Aurora since the platform is universal? The Profile can be found on the creators website (below) or I have attached the zip file from said site containing the profile. Currently using a Logitech G910 Orion Spectrum.

Site: http://lewisgerschwitz.com/corsair.html

Video showing the profile: https://www.youtube.com/watch?v=F0B_ceWscVw

[StarcraftII.zip](https://github.com/antonpup/Aurora/files/2178637/StarcraftII.zip)

**Comment by simon-wh** [comment]
Have you tried importing it on the latest version?
