### ISSUE TITLE
Does not work for non-RGB Razer Blackwidow

### ISSUE THREAD

**Issue by Simple2Sample** [antonpup/Aurora#1175]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (Razer Blackwidow Ultimate Stealth 2016)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Option to choose a non-RGB mode where it works the same way as normal just without the colours.

### Actual behavior:
The keyboard's light stays the same. Aurora shows in the preview what actually should happen. My reacts as expected.

### How often does this problem occur?

This problem occurs... every time.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Have Razer Blackwidow Ultimate Stealth 2016
2. Apply a fitting wrapper
3. Enter a patched game.

### What is the version of Aurora you are experiencing this issue with?

My version is... newest stable version

**Comment by simon-wh** [comment]
It should work somewhat by default as I have a Corsair Strafe (non-rgb) which worked just fine, just everything was a single colour.
