### ISSUE TITLE
Aurora Crashes Logitech Gaming Framework and is generally unusable.

### ISSUE THREAD

**Issue by jjbrunton** [antonpup/Aurora#1180]
### What are you experiencing an issue with?

- [ x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x ] Device issue
- [ x] Other, (Fill in another type of issue here)

### Expected behavior:
Aurora should not crash Logitech Gaming Framework

### Actual behavior:
Running Aurora appears to crash Logitech Gaming Framework which then means I need to restart my PC to get the gaming framework to recognize the keyboard again.

I am using the Logitech 910 Orion Spectrum.

### How often does this problem occur?
100% of the time of running this software.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Use a Logitech Orion Spectrum
2. Start Aurora
3. Gaming framework will eventually become unresponsive then crash

### What is the version of Aurora you are experiencing this issue with?

My version is... (Fill in here)

Latest 0.6.1dev4

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by diogotr7** [comment]
I clean installed lgs a couple of weeks ago and I haven't had any problems. Is yours updated?

**Comment by jjbrunton** [comment]
Yes it is. I received the keyboard today and everything is new (9.42 I believe for Logitech).

**Comment by jjbrunton** [comment]
I've just LGS and now I can't even get Aurora to connect.

Logs:

[INFO] 12:52:53: Loading Configuration
[INFO] 12:52:53: Loading Plugins
[INFO] 12:52:53: Loading KB Layouts
[INFO] 12:52:53: Loading Input Hooking
[INFO] 12:52:53: Loading Applications
[INFO] 12:52:54: Loading Device Manager
[INFO] 12:52:54: Device, Logitech, was initialized
[INFO] 12:52:54: Starting GameStateListener
[INFO] 12:52:54: Listening for game integration calls...
[INFO] 12:52:54: Loading ResourceDictionaries...
[INFO] 12:52:54: [IPCServer] Pipe created 39086322
[INFO] 12:52:54: [AuroraCommandsServerIPC] Pipe created 20974680
[INFO] 12:52:54: Loaded ResourceDictionaries
[INFO] 12:52:54: Loading ConfigUI...
[INFO] 12:52:54: Device, Logitech, was shutdown
[INFO] 12:52:59: Show Window called
[INFO] 12:53:05: Device, Logitech, was shutdown

**Comment by diogotr7** [comment]
Has it worked at all even once? Or it just straight up crashes everytime? I'd tell you to reset Aurora settings but it seems that's not the problem. Is Aurora asking for administrator? If not, start it as admin manually

**Comment by jjbrunton** [comment]
It connected once before I reinstalled LGS. Now it is completely broken.

I have always been launching Aurora as Administrator.

**Comment by jjbrunton** [comment]
Managed to get it working for about 20 seconds of CS:GO, Aurora didn't show it as connected to Logitech but it did appear to change the keyboard. Could see ammo keys being changed...

Then it crashed LGS.

**Comment by simon-wh** [comment]
I'm pretty sure this issue is on LGS's side as we don't send anything to LGS that it isn't expecting. However, it is something that we can try and get sorted. Have you tried any of the "bleeding edge builds" if I remember correctly there was an update to the Logitech sdk that hasn't been pushed to the releases yet which might help.

**Comment by jjbrunton** [comment]
Cheers for the notification reminder with the closure. It turns out this was down to the keyboard being plugged into a USB hub for anyone that comes across this in the future.

**Comment by simon-wh** [comment]
@jjbrunton Ah! Thanks for letting us know!
