### ISSUE TITLE
[Suggestion] Disable Volume key for lock colour layer

### ISSUE THREAD

**Issue by iLeoLion** [antonpup/Aurora#1181]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [x] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [x] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Desired behavior:
I have a button to mute my volume (On a k95 platinum), I would like to be able to use it similar to the lock colour layer
I was reading that it's impossible for the Windows Lock Key, is it too for this?
Thanks!
### Actual behavior:
Current options for lock colour are:
Capital, Numlock, Scroll

**Comment by simon-wh** [comment]
You cannot use the Windows Lock key as the input of that key is never sent to the computer. The dev builds have a layer which allows you to achieve the same thing as the Lock Colour layer with any key, which you can check out with [this](https://ci.appveyor.com/project/antonpup/aurora/build/0.6.1-dev4-376/artifacts)
