### ISSUE TITLE
Aurora crashing randomly

### ISSUE THREAD

**Issue by seamlessatomica** [antonpup/Aurora#1184]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Not crashing randomly.

### Actual behavior:
Every so often when I have Aurora open for a random amount of minutes (completely random, sometimes 30 mins, sometimes 10) it pops up with a crash report, but the program keeps running perfectly fine until I hit ok, where it then freezes for a minute and proceeds to crash. The problem is that it opens up another crash report every couple of minutes. So I cant just leave it open cause my computer would slow down pretty badly. I only have a Steelseries Rival 110 connected in case that helps.

### How often does this problem occur?
This problem occurs every time I have aurora open for a random amount of time.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Opening Aurora.
2. Leaving it open for 10 mins or so.

### What is the version of Aurora you are experiencing this issue with?
My version is beta v0.6.1-dev4.

### Does the previous version of Aurora have this issue?
Never used another version.

### Please include any logs, screenshots, or files that are related to this issue:
I don't seem to have a logs folder but I have a snapshot of the crash report popup.
Snapshot:
[](https://imgur.com/a/ambRyqq)

**Comment by simon-wh** [comment]
This issue has come up multiple times before, I thought it had been fixed in the dev branch (which you can get running through the bleeding edge builds in the readme) but according to #1129 it's not fully fixed, please look there
