### ISSUE TITLE
Any way to add support for Cooler master MK750 & ASUS AURA? SDK's in comments

### ISSUE THREAD

**Issue by aceofpilots** [antonpup/Aurora#1185]
http://www.coolermaster.com/peripheral/keyboards/masterkeys-mk750/

Mk750 SDK: http://www.coolermaster.com/xresserver01-DLFILE-P17111700011edb-F18061300016ef6.html

ASUS AURA SDK: https://www.asus.com/campaign/aura/download/AuraSDK.ZIP

Anyway to add support for these?

**Comment by simon-wh** [comment]
Um, the MK750 has been supported for a while, see: #1014 
As for the Asus Aura SDK, it has come up multiple times before: #546
