### ISSUE TITLE
On startup, MK750 is showing different colors in the wrong spots.

### ISSUE THREAD

**Issue by Caleb10E** [antonpup/Aurora#1186]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [x] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (CM MK750)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
When Aurora starts up, it should be displaying two colors in two different zones on my keyboard: The light bar should be blue, while every other LED should be red.

### Actual behavior:
Almost every time I start up,  a couple keys near Insert, Home, and Delete are blue while the light bar LEDs are red. Random buttons like Print Screen and Play/Pause will also not be illuminated at all. In Aurora, the software thinks that the correct keys are illuminated. The only way I've found to snap it back to normal is by opening Cooler Master's software, letting that set the LEDs, and then restarting Aurora.

### How often does this problem occur?

This problem occurs almost every time. I've had a couple times where it sorts itself out, but it pretty much always happens for at least a couple seconds even when it does sort itself out. Most of the time, it just gets stuck with the keys illuminated in the wrong spots.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Setting a Solid Fill Color layer to one color (like red).
2. Setting a Solid Color layer to another color (like blue) and assigning the additional LEDs for the color bar.
3. Shutting down, then starting back up. Restarting hasn't reproduced the issue, where shutting down typically causes the issue.

### What is the version of Aurora you are experiencing this issue with?

My version is 0.6.1-dev4-377-aqytjgwr.

### Does the previous version of Aurora have this issue?
The previous version, 0.6.1-dev4-342, has this issue too.

### Please include any logs, screenshots, or files that are related to this issue:

I can post screenshots of what the keyboard is displaying and what it should be displaying later today.

**Comment by diogotr7** [comment]
I'm sorry, I didn't mean to edit your post. 

I'm not sure if any changes were made to coolermaster, but the build you're using is from a pull request which added roccat support, which might've messed something up. Builds from the dev branch don't have letters after the numbers, so I'd say try a more recent one, like this https://ci.appveyor.com/project/antonpup/aurora/build/0.6.1-dev4-376 .

**Comment by simon-wh** [comment]
I believe this is an issue with the CM SDK, from the testing I did when I was getting it working most of the time it'd work fine but sometimes it'd do what you describe where it looks corrupted

**Comment by Caleb10E** [comment]
@simon-wh So I'm guessing because it's probably the SDK acting up, there's not much you can do on your end? I suppose I'll just have to figure out if there's some way to make it more reliable. Does Aurora need Cooler Master's software installed to work with the MK750? Or can it work without it?

**Comment by simon-wh** [comment]
@Caleb10E Yeah, there isn't much we can do about it, if you look at the original cm mk750 issue you'll see how much bother we had with it working at all for the MK750 and how it still doesn't even work properly when it does light correctly. The SDK communicates directly with the device and doesn't go through the software, so you don't need it. Also, I don't have access to my MK750 right now and am about to go to a festival so if you see any firmware updates or SDK updates it'd be a great help if you could post it on the original issue (so it's all in one place) and if there is an update to the SDK I'll try and get a build going with it asap

**Comment by Caleb10E** [comment]
@simon-wh Can do. Current firmware version is v1.05.02, current SDK version is v22.

**Comment by simon-wh** [comment]
@Caleb10E As far as I can tell the SDK version hasn't changed, so there isn't anything to do currently on our end to try and sort it out

**Comment by Caleb10E** [comment]
For anyone else that sees this and can't get their MK750 to play nice, I found a way to snap it back into shape:

Go into Aurora's Device Manager and select Stop next to the Cooler Master device. Then go to the taskbar, find Aurora in the icons at the bottom-right, right-click and Quit. Now once you start Aurora back up, it should automatically restart the Cooler Master device and fix any keys that weren't working before.

**Comment by Zazama** [comment]
Hi, after inserting the new SDK version 24 dll, I don't get this bug anymore. Updating should fix the issue. Can anyone else confirm?

**Comment by Caleb10E** [comment]
@Zazama I got it to bug out once, but I'm gonna see how it does this week. It's seems much improved from before.

**Comment by Caleb10E** [comment]
Since the SDK update, I've had no issues with it on a day-to-day basis. Looks like it's fixed.
