### ISSUE TITLE
Aurora crashing when opened

### ISSUE THREAD

**Issue by BurningIce323** [antonpup/Aurora#1189]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Aurora should start normally with no crashes.

### Actual behavior:
I get this error message: https://puu.sh/B0lnQ/efb443c22a.png
When I close out of it, Aurora crashes.

### How often does this problem occur?

This problem occurs... Everytime

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:
1.  Running the application

### What is the version of Aurora you are experiencing this issue with?

My version is... 0.6.1

### Does the previous version of Aurora have this issue?
I never used any other version. This error only started happening recently.

### Please include any logs, screenshots, or files that are related to this issue:

[2018-07-20 22.59.36.log](https://github.com/antonpup/Aurora/files/2215837/2018-07-20.22.59.36.log)
[2018-07-20 23.03.41.log](https://github.com/antonpup/Aurora/files/2215838/2018-07-20.23.03.41.log)
[2018-07-20 23.19.37.log](https://github.com/antonpup/Aurora/files/2215839/2018-07-20.23.19.37.log)
[2018-07-20 22.32.55.log](https://github.com/antonpup/Aurora/files/2215840/2018-07-20.22.32.55.log)
[2018-07-20 22.48.23.log](https://github.com/antonpup/Aurora/files/2215841/2018-07-20.22.48.23.log)
[2018-07-20 22.51.01.log](https://github.com/antonpup/Aurora/files/2215842/2018-07-20.22.51.01.log)

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
The puush you posted doesn't work anymore, but from the logs it looks like an error that has come up before, which I believe has been fixed in the dev builds but you should be able to sort it out by deleting %appdata%/Aurora
