### ISSUE TITLE
Aurora will not start at all.

### ISSUE THREAD

**Issue by FunkyFlame** [antonpup/Aurora#1190]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, (Aurora not starting at all)

### Expected behavior:
Aurora should start up when the exe is run

### Actual behavior:
nothing. Aurora can been seen as open in background processes

### How often does this problem occur?

This problem occurs... (Every time)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Run Aurora.exe
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (0.6.1)

### Does the previous version of Aurora have this issue?
Did not use the Previous version

**Comment by DarkNachtara** [comment]
Did Aurora give you an Error Massage??

**Comment by ComradeNixco** [comment]
Had the same problem with clean and fresh install (v0.6.2) but starting Aurora.exe with Admin permissions let it started 'normally'

**Comment by ComradeNixco** [comment]
Like you said, I checked the permission of the folder in which Aurora is and managed security from there. Now it works without UAC.

**Comment by simon-wh** [comment]
@FunkyFlame Have you tried what was mentioned above? 

@ComradeNixco Is it working correctly for you now then?

**Comment by DarkNachtara** [comment]
@simon-wh it seems the solution for @ComradeNixco are working

**Comment by ComradeNixco** [comment]
Yes, @simon-wh, the problem in my case was that aurora didn't had enough permission because the install drive had it's permissions settings not what it should be

**Comment by simon-wh** [comment]
Thanks for getting back to me @ComradeNixco! @FunkyFlame have you tried what has been suggested here?

**Comment by DarkNachtara** [comment]
I think he is already gone...

**Comment by simon-wh** [comment]
@DarkNachtara Yeah, I'll close this as it seems to be all sorted
