### ISSUE TITLE
Games that support Chroma that aren't Overwatch do not work

### ISSUE THREAD

**Issue by Caleb10E** [antonpup/Aurora#1191]
### What are you experiencing an issue with?

- [ ] Aurora
- [x] Aurora supported game, (DOOM, Fortnite)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, (Wrapper-related?)

### Expected behavior:
The Overview menu of the Overwatch profile says "P.S. You can actually apply this patch to any Razer Chroma supported game, and Aurora will work with it." So applying the patch to the .exe's for DOOM and Fortnite should both work, since they have Chroma support.

### Actual behavior:
Neither game displays anything using the Wrapper Lighting layer. I believe I'm setting it up correctly, so you can verify the steps I took below to see if I'm doing it right.

### How often does this problem occur?

This problem occurs every time.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Go to the Overwatch profile in Aurora and go to Overview.
2. Use the Patch Overwatch button to apply the patch to the directory where DOOMx64.exe or FortniteClient-Win64-Shipping.exe are.
3. Create a game profile in Aurora for either DOOM or Fortnite, add a Wrapper Lighting layer.
4. Start the game you applied the patch to. I'm assuming it should function like Overwatch where the keyboard works once the game is started, but the keyboard stays black.

### What is the version of Aurora you are experiencing this issue with?

My version is v0.6.1-dev4-376.

**Comment by Caleb10E** [comment]
Are there any non-Overwatch Chroma games that do work with this patch?

**Comment by diogotr7** [comment]
Deus ex MD and Rise of the Tomb Raider work. I could not get factorio and quake champions to work either.

**Comment by gitmacer** [comment]
Move or die also work.

**Comment by simon-wh** [comment]
See #1042 for DOOM and I believe that for Fortnite the anti-cheat kills it so there's nothing we can do about that.

**Comment by diogotr7** [comment]
I got doom working in this branch. https://github.com/antonpup/Aurora/tree/chromawrapper-update

Video: https://streamable.com/jv9o1

**Comment by Caleb10E** [comment]
@diogotr7 I must be missing a step for getting this to work. I'm downloading the ZIP from your branch and running Aurora, then applying the Overwatch patch to my DOOM directory. I use a custom application profile for my DOOM exe and add a Wrapper Lighting Layer to it. Am I doing something wrong here?

**Comment by diogotr7** [comment]
Try without adding a profile for it. Just straight patching and opening the game.

**Comment by Caleb10E** [comment]
That didn't work either, it just uses the default desktop profile.

**Comment by Caleb10E** [comment]
@diogotr7 I finally figured it out and DOOM's Chroma profile is now working. I made sure there was no DOOM profile and repatched my DOOM directory.
