### ISSUE TITLE
Crash on startup, latest Appveyor build

### ISSUE THREAD

**Issue by Khurune** [antonpup/Aurora#1197]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Launching app

### Actual behavior:
Crashes every time.

### How often does this problem occur?

This problem occurs... Everytime

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Launching App
2. Relaunching app

### What is the version of Aurora you are experiencing this issue with?

My version is... 0.6.1-dev4-379

### Does the previous version of Aurora have this issue?
The previous version, 0.6.1-dev4, did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

https://pastebin.com/6ue6djmU

**Comment by lucasvanhalst** [comment]
@Khurune  You can use this build in the meantime which fixes this https://ci.appveyor.com/project/antonpup/aurora/build/0.6.1-dev4-380-fhswdibu/artifacts

**Comment by Khurune** [comment]
Cheers @lucasvanhalst Will install that for now, fell back to 378 for now.
