### ISSUE TITLE
Game Request: TF2

### ISSUE THREAD

**Issue by Kisco** [antonpup/Aurora#120]
I'm pretty sure you play TF2 a lot, so I am going to guess the only reason you haven't done this yet is because it is too big of a project...

**Comment by antonpup** [comment]
TF2 Doesn't have Game State Integration. Thus no real way to get information out of the game.

**Comment by Kisco** [comment]
that is too bad :l

**Comment by antonpup** [comment]
Hey! I found something really old, but I might be able to use it to get information from TF2.

[http://www.tf2newbs.com/newbs_blog/2010/01/14/tf2_g-series/](http://www.tf2newbs.com/newbs_blog/2010/01/14/tf2_g-series/)

I'll be looking into it next week.

**Comment by Kisco** [comment]
Yeet!

**Comment by antonpup** [comment]
There is quite a bit of information presented though this implementation.

![lcdscreen_0902_224904](https://cloud.githubusercontent.com/assets/3421963/18223064/12b3cdc6-7160-11e6-9299-0e0c74f7162a.png)
![lcdscreen_0902_225121](https://cloud.githubusercontent.com/assets/3421963/18223065/1879ea60-7160-11e6-953b-6f01d8be9ae3.png)
![lcdscreen_0902_225210](https://cloud.githubusercontent.com/assets/3421963/18223066/1c1f6f6e-7160-11e6-8324-1ef255bde2e0.png)
![lcdscreen_0902_225250](https://cloud.githubusercontent.com/assets/3421963/18223067/20a700a6-7160-11e6-8d9c-f547fb86485c.png)
![lcdscreen_0902_225219](https://cloud.githubusercontent.com/assets/3421963/18223071/244a82aa-7160-11e6-9460-e917b1593638.png)
![lcdscreen_0902_225225](https://cloud.githubusercontent.com/assets/3421963/18223072/256a3630-7160-11e6-9cea-4ee5f49a7f83.png)
![lcdscreen_0902_225234](https://cloud.githubusercontent.com/assets/3421963/18223073/26c05672-7160-11e6-862b-e466c1dee666.png)

**Comment by Kisco** [comment]
yeah, looks like you can do health, team color, ammo, all that jazz!

**Comment by antonpup** [comment]
The problem is, that information is on different "pages" of the LCD display. User would have to go to the page they wanted for information. I could simulate user going to those pages, but I don't think that's an efficient way to go.

**Comment by Kisco** [comment]
I really think it would be cool if you could get cloak, uber, sandman ball,
recharge meter on the keyboard. That is what I want the most tbh :^)

**Comment by antonpup** [comment]
If it doesn't disclose that information, I will not reach in to get it. Last thing I want is a VAC.

**Comment by Kisco** [comment]
good point

**Comment by antonpup** [comment]
It is also using a very old sdk, which I had to dig a little bit to find. So I might be able to get this going, but I am not sure.

**Comment by antonpup** [comment]
Unfortunately I will not be going the LgLCDApi route. I would have to try to convert text of an image to real text, then evaluate if it's what I need. Plus there's multiple pages that a user can go to, which I would have to invoke manually. All of this would result in too much resource usage.
