### ISSUE TITLE
Coolermaster Masterkeys Pro S Enter key not lighting up

### ISSUE THREAD

**Issue by Remitar** [antonpup/Aurora#1200]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [x] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
Enter key and "|\' should light up when the corresponding key is modified.

### Actual behavior:
Explain here what happened instead.
The lighting options for the Enter key modifies the lighting on the "|\" key, and modifying the lighting for the "|\" key does nothing.

### How often does this problem occur?

This problem occurs every time, all the time.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Set a color for the "|\" key (Nothing happens.)
2. Set a color for the Enter key ("|\" key lights up)
3. Happens for any mode (Single key or fill.)

### What is the version of Aurora you are experiencing this issue with?

My version is beta v0.6.1-dev4.

### Does the previous version of Aurora have this issue?
The previous version that I used, which was around v0.6.0, did not have this issue.

**Comment by simon-wh** [comment]
This has come up multiple times before and has been fixed in the dev builds, please try one of the bleeding edge builds or wait for the next release
