### ISSUE TITLE
Another issue with brightness modifier

### ISSUE THREAD

**Issue by gitmacer** [antonpup/Aurora#1202]
- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Only the Keyboard should dim with the option "Keyboard brightness modifier" like the Peripherial option.

### Actual behavior:
Every light dim.

### How often does this problem occur?

This problem occurs... (Every time)

### What is the version of Aurora you are experiencing this issue with?

My version is... (Aurora-v0.6.1-dev4-382)

### Does the previous version of Aurora have this issue?
The previous version, (Aurora-v0.6.1-dev4), did have this issue.

### Please include any logs, screenshots, or files that are related to this issue:
[https://imgur.com/a/bzX8YrF](https://imgur.com/a/bzX8YrF)

**Comment by simon-wh** [comment]
Fixed with the above commit, thanks again
