### ISSUE TITLE
Fatal Error (System.IO.DirectoryNotFoundException)

### ISSUE THREAD

**Issue by Endolite** [antonpup/Aurora#1205]
Opening Aurora, I expected everything to be normal, as it had been before.
It instead decided to crash upon startup.
This problem occurs every time.
I don't know how this issue can be reproduced.
I am using Aurora-v0.6.1-dev4
This is the only version of Aurora that I have ever used.
Logs: https://pastebin.com/5iJi4MTf
Screenshot: https://imgur.com/a/diWPVOk

**Comment by simon-wh** [comment]
This has been fixed with v0.6.2, please update
