### ISSUE TITLE
Game support: Endless Space 2

### ISSUE THREAD

**Issue by numbernegative** [antonpup/Aurora#1207]
I would like to request support for the game Endless Space 2, it has chroma support with the expected effects listed here: https://www2.razer.com/chroma-workshop/integrations-endless-space-2
Unfortunately dropping the RzChromaSDK files into the directory does not patch it and when launching Aurora keeps it's desktop profile.

Aurora v0.6.2b

**Comment by Gurjot95** [comment]
I and Dr Meteor are working on updating the Razer wrapper and it seemes new games should work now. Doom and Quake Champions are confirmed to be working now which earlier had issues. You can download the update from mine or Dr. Meteor repo and try out if it works now.

**Comment by Gurjot95** [comment]
Download the build folder and extract it somewhere and run aurora from there and reapply the wrapper patch.

**Comment by diogotr7** [comment]
Don't overcomplicate things.@numbernegative, here is the build https://ci.appveyor.com/project/antonpup/aurora/build/0.6.2b-442

**Comment by Gurjot95** [comment]
Sorry I didn't had acess to PC right now thats why couldn't build it myself!

**Comment by numbernegative** [comment]
I tested out that build and it does not appear to have fixed the Chroma in ES2, I also tried other games in my library with known issues with Aurora, namely Aven Colony and Factorio, with no change as well.

**Comment by diogotr7** [comment]
@numbernegative I would appreciate it if you would try this build for me: https://ci.appveyor.com/project/antonpup/aurora/build/0.6.2b-448 .

Keep in mind that you will need to delete the dll's and re-patch, as they have been updated. Factorio works with this build.

**Comment by numbernegative** [comment]
@diogotr7 Can confirm that factorio is working in this build but ES2 still does not, I did delete the .dll's and replaced them with the same ones that were being used to patch factorio, they were placed in the same folder as the application .exe and when launched aurora kept the desktop lighting.
I also tested making a profile for ES2 in aurora with the only layer being wrapper lighting, in which case the keyboard went blank upon launching the game with no lighting effects.
Also did confirm that effects are enabled in ES2 settings.
Did the same with Aven Colony with identical results.

![image](https://user-images.githubusercontent.com/11063321/44950720-c99eb300-ae14-11e8-8d7c-347025315c8f.png)

**Comment by diogotr7** [comment]
@numbernegative can you contact me on discord please? DrMeteor#8631

**Comment by Gurjot95** [comment]
I heard issues regarding ES2 doesn't even work on Razer devices anymore so unless they fixed that bug, I am going to assume this is game issue.

**Comment by Gurjot95** [comment]
Update: I tried running it on Razer Emulator which emulates Razer Keyboard, while all other games ran successfully on it, this one didn't. Most likely the issue is within game when even Razer emulator failed to load it. You can try contacting anyone who owns Razer keyboard and this game and let me know if chroma effects works. Maybe some latest patch broke Chroma integration on all Razer devices.
