### ISSUE TITLE
Wrong or incomplete keyboard layout used by aurora for G910 UK layout

### ISSUE THREAD

**Issue by Doldol** [antonpup/Aurora#121]
Aurora doesn't detect the # and \ key, note pressing the # key lights up the ' key when effects are used.

Undetected keys marked red:
![untitled-1](https://cloud.githubusercontent.com/assets/4009352/18022724/8e8ab2b2-6bf1-11e6-8c65-985ca47aeb85.jpg)

**Comment by brainbug89** [comment]
notice to add: this is an UK layout

**Comment by Doldol** [comment]
Also just noticed pressing ' lights up ` (top leftmost key in the above image).

@brainbug89 That's in the title btw.

**Comment by antonpup** [comment]
So this is what is happening:
# -> '
' -> '
\ -> what does this light?

If you set a color zone for each of those keys, which key on the keyboard lights up instead? Or is the issue only input related?

**Comment by Doldol** [comment]
@antonpup
no
```
# -> '
# -> ` (topleft key, also printed with ¬ and ¦)
\ -> lights nothing.
```

Aurora doesn't display the correct layout (I'm guessing it's identifying my keyboard as a qwerty US layout.), so I can't actually select those (marked red) keys.

I will try to get a comparative image what lights up in LGS vs Aurora today or tomorrow.

**Comment by brainbug89** [comment]
Did you select the UK layout at Aurora setting tab?

**Comment by Doldol** [comment]
@brainbug89 Urh, no, it was on auto-detect. Thanks, this fixed the basic lighting issue, but effect issue is still there (as mentioned in my previous post.)

**Comment by antonpup** [comment]
Keep both open. I will close them when I resolve them for each layout.

**Comment by Doldol** [comment]
I updated the list of wrong-key lighting effects for UK in my post above (I went over every key, so it should be complete now).
