### ISSUE TITLE
Aurora suggest

### ISSUE THREAD

**Issue by klemanjar0** [antonpup/Aurora#1210]
Please. I've asked this few months ago, but I still want an aurora's programme support for HyperX things like Alloy RGB or Pulsefire Surge. You recently added Roccat, so please make something with HyperX, I supplicate you, I will donate as much as I can, please! Thank you!

**Comment by bigode1997** [comment]
the hyperx has a software called GENESIS if you look in the files of the program will find the SDK

**Comment by simon-wh** [comment]
@bigode1997 Are you sure? I can't find a single mention of an SDK for HyperX anywhere and as far as I can tell HyperX seemed to have moved to their NGenuity software. I'm not on windows to be able to have a look at it, Could you upload the files you think are part of an SDK?

**Comment by bigode1997** [comment]
https://mega.nz/#F!tuo3gDLa

here are the Genesis program files for the HYPERX MARS keyboard

**Comment by bigode1997** [comment]
key 
!_Q1EHnFAwlh2Cx-fs_GBBA

**Comment by simon-wh** [comment]
@bigode1997 Looking through that I don't see anything that is explicitly an SDK, there are some DLL's which might have stuff available to use but as far as I can tell none of it is documented so there's no guarantee there is anything usable there.
