### ISSUE TITLE
Aurora stopped working on my cooler master masterkey pro s

### ISSUE THREAD

**Issue by husseinfahmy** [antonpup/Aurora#1211]
### Expected behavior:
The profile selected should show on my kb

### Actual behavior:
no behaviour. As if the program wasn't running at all. The on screen keyboard shows the profile and effects that are supposed to happen, but instead i just see the CM profile set in my software. And I can confirm that I have checked off "allow Aurora wrappers to take priority over desktop profiles while active"

### How often does this problem occur?
Every time

### Please describe the steps to reproduce this issue:
This happens every time i launch the program, It's as if it isn't running, despite not showing any errors

### What is the version of Aurora you are experiencing this issue with?
0.6.2b

### Does the previous version of Aurora have this issue?
Yes i first started seeing this on the build i was on before this. I don't think it was a new build that broke it.

### Please include any logs, screenshots, or files that are related to this issue:
[2018-08-02 00.35.26.log](https://github.com/antonpup/Aurora/files/2252125/2018-08-02.00.35.26.log)

##Update
It now turns off the keyboard's lights all together. Exiting the program resumes my CM profile.

**Comment by KWall24** [comment]
I can also confirm I have this issue. It worked the first time I connected my keyboard, but now when I try to click the reconnect button, it just shows "Masterkeys Pro SMasterkeys Pro SMasterkeys Pro S" repeating, before changing back to Not Connected.

I tried running Aurora as admin, and tried having the Cooler Master software open as well. No dice. Happy to help test things if needed.

**Comment by simon-wh** [comment]
Has there been a firmware update for the Pro S? Also, have you tested on v0.6.1-dev4 to see if it has the issue as well?

**Comment by husseinfahmy** [comment]
Now that you mention it, it failed after I had launched the native CM software for the first time in a while. So it's very likely a firmware update caused this. Yes I've tried many previous versions and none of them fix it

**Comment by husseinfahmy** [comment]
Sounds good I'll look into that. 

If it helps: 

SW version: 1.01

FW Version: 1.2.1

**Comment by husseinfahmy** [comment]
@simon-wh testing SDK worked, so I backed up and deleted the `appdata/roaming/aurora` directory and that fixed things. Then migrated my profiles to the new aurora dir. I still have the old `appdata/roaming/aurora` dir if you'd like it for debugging reasons.

**Comment by simon-wh** [comment]
@husseinfahmy That'd be super helpful! There seems to be lots of issues that get fixed by deleting appdata and it'd be nice to finally figure out why

**Comment by diogotr7** [comment]
Ctrl C and Ctrl V work on layers @husseinfahmy

**Comment by simon-wh** [comment]
Just had a look at the old Aurora folder, worked fine for me, no clue why it wasn't working.
