### ISSUE TITLE
Custom-made profiles for other games not working after alt-tabbing out and back in

### ISSUE THREAD

**Issue by Elcheer** [antonpup/Aurora#1217]
### Expected behavior:
Aurora switches from desktop profile to profile for respective game after tabbing out and back in.

### Actual behavior:
Aurora stays on desktop profile as if the game isn't active anymore.

### How often does this problem occur?
This problem occurs every time you alt-tab out and back in after launching it.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Install game (in my case it was osu!)
2. Create profile for game in Aurora (My profile was just static colors for certain keys)
3. Launch game
4. Alt-tab out of the game
5. Alt-tab back into the game.

### What is the version of Aurora you are experiencing this issue with?
My version is v0.6.2b

### Does the previous version of Aurora have this issue?
The previous version, v0.6.1-dev4, doesn't support my keyboard so I probably wouldn't be able to test it.

### Please include any logs, screenshots, or files that are related to this issue:
Profile: https://i.imgur.com/iCZ0SHU.png
Profile showing on keyboard: https://i.imgur.com/oV3jQK0.jpg
Game showing profile: https://i.imgur.com/30vWDl7.jpg
Game after tabbing out and back in: https://i.imgur.com/NJlmPHG.jpg

**Comment by diogotr7** [comment]
Try going into aurora settings and switching the detection method from Windows events to the other one. I had that problem at first but foreground app scan seems to be more reliable.

**Comment by Elcheer** [comment]
Thanks! It works perfectly now.
