### ISSUE TITLE
Add RGB support for the Logitech G502 Proteus Spectrum Mouse

### ISSUE THREAD

**Issue by Doldol** [antonpup/Aurora#122]
Aurora seems to not detect this mouse (Afaik it should be bundled for rgb effects with my G933 headset, but it only follows the Logitech utility.).

**Comment by antonpup** [comment]
This might be an issue with Logitech SDK. The mouse should work, as it's treated as an RGB device. And I already update those. I'll check it out in the dev branch.

**Comment by SilentZen** [comment]
Doldol do you have a rgb logitech keyboard? those devices are linked to a sdk enabled device rather than been sdk controlled directly.

**Comment by Doldol** [comment]
@SilentZen Yes G910. Like I explained, there is definitely an issue as my G933 headset gets controlled by Aurora, while the mouse is not.

**Comment by ItsYairo** [comment]
I have the same issue

**Comment by antonpup** [comment]
Try this.  Close Aurora, and replace the "LogitechLed.dll" file with the one I provided. The file is located in Aurora's directory. This might fix the issue, it's one of the latest LED SDK files, I haven't updated the one used in Aurora for quite some time now.

Let me know if this helps.

[LogitechLed_8_85_215_x64.zip](https://github.com/antonpup/Aurora/files/452858/LogitechLed_8_85_215_x64.zip)

**Comment by SilentZen** [comment]
Hi

Just tested and it fixed issue
(G502 Mouse working with this dll)

Thanks and much appreciated

Brad
