### ISSUE TITLE
Request: Corsair K68 Support

### ISSUE THREAD

**Issue by michaelsegreti95** [antonpup/Aurora#1221]
Can I get help with adding the K68 to the supported devices? I am using the K70 layout because it is almost identical except for one issue, the K68 has 2 buttons instead of the scroll wheel for volume. So I believe it just needs to have the layout from the K70 copied, renamed, and add volume down/vol up on the right side of the mute button. Sorry I don't know python very well, I am trying to figure this out and will upload any code I get to work but i'm sure someone that actually knows what they're doing could do a better job in a small fraction of the time.

**Comment by diogotr7** [comment]
let me know if that fixed it and ill close the issue

**Comment by michaelsegreti95** [comment]
How do I get the dev branch with the changes to run? I tried replacing the files in my current directory with the new ones but I'm pretty sure that's wrong. Seems like I need to get the installer to use the dev branch but I can't seem to find any installation executables besides the current stable release.

**Comment by simon-wh** [comment]
https://ci.appveyor.com/project/antonpup/aurora/build/0.6.2b-440/artifacts this is the build for that commit, on there you can download an installer or a zip with the files

**Comment by michaelsegreti95** [comment]
Thank you so much! Just tried that download, the K68 is on the list and all the buttons work perfectly so far. I really appreciate all the help, you guys are great
