### ISSUE TITLE
Can't write CTRL+ALT+. (dot) when Aurora is running

### ISSUE THREAD

**Issue by Mavi222** [antonpup/Aurora#1222]
### Expected behavior:
If I press CTRL+ALT+. (dot) it should write ">" (more than) symbol on Czech keyboard layout (QWERTZ).

### Actual behavior:
It doesn't make the ">" symbol, it does nothing. 

### How often does this problem occur?
This problem occurs every time.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. press CTRL+ALT+. (dot)
2. observe that nothing happened.

### What is the version of Aurora you are experiencing this issue with?

My version is beta v0.6.2b

### Does the previous version of Aurora have this issue?
The version v0.5.1 (I think I had that one before, I made a huge version jump), did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

I have no idea how do I show you just the log that is needed. And screenshots or files won't help I guess. I can provide you the logs if they are needed.

**Comment by Mavi222** [comment]
The key combination for ">" (CTRL+ALT+. (dot)) actually acts as Global Brightness modifier, it lowers the global brightness. It wasn't doing that before.

**Comment by simon-wh** [comment]
Why do you need to press CTRL+ALT+. to write the >?

**Comment by simon-wh** [comment]
I'm going to implement an option to choose the keybind that is used in the options so you can change it to something that would suit better for your setup.

**Comment by simon-wh** [comment]
Wait, I've just looked at the code and it is setup for Alt + Volume buttons, not for Ctrl+Alt+., is that a bind or something? Also, does disabling "Use ALT+Volume Controls for global brightness" change anything?

**Comment by Mavi222** [comment]
If I disable the "Use ALT+Volume Controls for global brightness" it works as intended. It's probably something with Czech keyboard layout (QWERTZ)

**Comment by simon-wh** [comment]
I'm not sure, I'm able to replicate it on the UK layout and it doesn't work with the intended keys, trying to debug it now. But I am in a VM so it's not an exact testing environment

**Comment by simon-wh** [comment]
I've fixed it with the above commit, you can either continue to keep the option disabled or [download the commit version](https://ci.appveyor.com/project/antonpup/aurora/build/0.6.2b-454/artifacts). Thank you very much for reporting this issue and replying quickly!
