### ISSUE TITLE
Aurora settings won't save, keyboard won't work for some time, and requires a restart to launch.

### ISSUE THREAD

**Issue by Endolite** [antonpup/Aurora#1228]
### Expected behavior:

Aurora should launch normally with all of my settings intact and my keyboard (G Pro) working.
### Actual behavior:

Aurora says that it is already running the first time that I boot it up, so I have to close it in task manager. My settings reset, so I have to select everything again, including the option to start with Windows, despite the fact that it just did. I also have to reinstall the Wrapper Patch for Logitech, reselect the G Pro, select the Desktop Profile (which I prefer to leave hidden), follow the first time instructions for Logitech, restart my devices, and finally restart Aurora. Even doing that sometimes doesn't work, in which case I just repeat it until it eventually does.
### How often does this problem occur?

This problem occurs every time that I reboot my PC.

### Please describe the steps to reproduce this issue:
I'm not sure how this issue can be reproduced.

### What is the version of Aurora you are experiencing this issue with?

My version is 0.6.2b

### Does the previous version of Aurora have this issue?
Version 0.6.1-dev4 lacked this issue but crashed upon startup no matter what I did.

### Please include any logs, screenshots, or files that are related to this issue:

https://pastebin.com/0dJYiPpy 
https://pastebin.com/wLB1F0T0 
https:// pastebin.com/uX4qSmbe 
https:// pastebin.com/q8EAFHYA 
https://pastebin.com/9GBeJbq6

I don't think that screenshots would be helpful.

https://www.dropbox.com/sh/r5j51604uqqdoa8/AAC_q90dB94XFpzb_TC25Otpa?dl=0

**Comment by diogotr7** [comment]
Do you have an "Aurora" folder in %appdata%?

**Comment by Endolite** [comment]
https://www.dropbox.com/sh/r5j51604uqqdoa8/AAC_q90dB94XFpzb_TC25Otpa?dl=0

**Comment by Endolite** [comment]
I called it Logs in Dropbox. Sorry about the missing link for files. I just fixed it.

**Comment by diogotr7** [comment]
Try deleting config.json from appdata and starting again.

**Comment by Endolite** [comment]
It worked for a bit with the keyboard of my Razer Blade, but not the G-Pro. It promptly went back to how it was earlier

**Comment by simon-wh** [comment]
@Endolite  Do you have it set to startup minimized in settings? On startup Aurora will generally run in the background and you can open it by click on the taskbar icon. The settings shouldn't be resetting at all, you definitely will not need to reapply the logitech wrapper unless you are using a system restore point or something which returns files back to older versions. Also, when you set the settings you can try closing it properly by clicking the X and saying yes to close aurora to re-open it. That should force the settings to save.
