### ISSUE TITLE
Wrong keyboard layout for german (DE) layout

### ISSUE THREAD

**Issue by brainbug89** [antonpup/Aurora#123]
After seeing #121 
I just notcied similar problems with german layout for interactive effects. Like I said here: https://github.com/antonpup/Aurora/issues/23#issuecomment-241103150 the X and Z key are switched.
But also these keys:

```
y -> z
z -> y
# -> -
- -> ß
ß -> ü
ü -> ö
ö -> ^
^ key no effect at all!
+ -> ´
´ -> +
Alt Gr -> Alt Gr AND Strg (left Ctrl)
right Ctrl (Strg) no effect
```

Color zone for each of those keys works fine, only the interactive effect is wrong.

**Comment by antonpup** [comment]
Corsair keyboard?

**Comment by brainbug89** [comment]
Corsair K70 RGB Rapidfire

**Comment by Xantha123** [comment]
Having a similar issue with the k70 rapidfire in germany. when i select afk mode with rainbow the y and z are swapped. everything else works fine. ( i changed to the german layout mode)

**Comment by brainbug89** [comment]
Update for version 0.6.0:
#, -, ß, +, ´ and right Ctrl work fine. But y, z, ü, ö, ^ and Alt Gr are still messed up.
```
y -> z
z -> y
ü -> ö
ö -> ^
^ -> nothing (no key)
Alt Gr -> Alt Gr AND Strg (left Ctrl)
```

Also, not only for Interactive effects, but Solid Color Layer, too.

**Comment by antonpup** [comment]
@brainbug89 Already fixed on dev. :)
