### ISSUE TITLE
Game support: Moster hunter world

### ISSUE THREAD

**Issue by LimticRage** [antonpup/Aurora#1234]
will be possible to have MHW support?

I was thinking about status, health, weapon sharpness, mounting the monster... maybe bow coatings or special attacks 

for Corsair K95 RGB Platinum, thanks!

**Comment by simon-wh** [comment]
MHW doesn't appear to have any existing RGB integration and it uses Denovu so it's unlikely we'll be able to do anything to support it. Sorry!
