### ISSUE TITLE
Support For Warframe!

### ISSUE THREAD

**Issue by uzaybahaberk** [antonpup/Aurora#1236]
First Hello I need to explain one something my English not so good I'm from Turkey and im new with aurora i try to figure out how it's works i look on the left panel ready profile's and i can't see Warframe or Dirt rally like theese game's can you add this games for dirt rally maybe keyboard left a RPM Dashboard like audio visualizer Thank you Good day's

**Comment by simon-wh** [comment]
Warframe is a duplicate of #663 and Dirt Rally is a duplicate of #976
