### ISSUE TITLE
Key press effect 

### ISSUE THREAD

**Issue by felixeng** [antonpup/Aurora#124]
Suggestion: Add key press effect to the available effects for color zones. If it gets selected there should be two options for color: background and keypress color. Also, if you do add this, it would be nice if the keypress color could be random. So for example a white background with random color keypress for that "rainbow" effect but with keypresses. 

Not sure if this is the right way to use github, just couldn't find anywhere else to give feedback so I thought why not?

**Comment by antonpup** [comment]
Sorry for the late response. Next version will basically break down each profile into their own "layers", so people can select an Interactive layer and set what they want for each profile. Another cool thing that you can do is combine multiple interaction layers to create various effects.

Demo:
![percent interactive_demo](https://cloud.githubusercontent.com/assets/3421963/18424965/f2961150-7869-11e6-8435-0188dffe63c5.gif)
