### ISSUE TITLE
Keyboard g910 not connecting (?) to aurora

### ISSUE THREAD

**Issue by radujr** [antonpup/Aurora#1244]
I recently got a Logitech g910 keyboard and really wanted to do a key press ripple effect, so i found Aurora after some internet searches. I set up the software with the installer, did all the settings i was told to in the setup info on the Logitech software and aurora wouldn't light up my keyboard. i uninstalled both the Logitech software and aurora and then reinstalled just aurora again using the setup download (not the zip) and the software seems to work fine and when i press keys the software reacts by my lighting on the keyboard always remains the same light blue i set it as when i got it. Any ideas? under device manager in settings it doesn't recognize the keyboard i think.
### What is the version of Aurora you are experiencing this issue with?
most recent
### Does the previous version of Aurora have this issue?
I didn't have previous version

**Comment by diogotr7** [comment]
You need both LGS and Aurora running for it to work.

Also, in LGS's settings, enable "Allow Games to control illumination"

**Comment by radujr** [comment]
Re-downloaded, and enabled, still no luck.

**Comment by diogotr7** [comment]
Can you send me a log? Aurora settings > debug > show logs foler

**Comment by radujr** [comment]
did that work?

**Comment by diogotr7** [comment]
Try restarting your computer. If you have LGS open and the option enabled, there's no reason it wouldnt work.

**Comment by radujr** [comment]
already have restarted a few times, with no luck. It may be worth mentioning that im using this keyboard with a laptop that has its own rgb keyboard built in? also nothing is recognized in the device manager tab.

**Comment by simon-wh** [comment]
@radujr Do you have Logitech GHub or Logitech Gaming Software installed?

**Comment by olliff** [comment]
I have the same problem, G910 not working at all.. already tried the fixed dll.
This is the error from the debug log.
[ERROR] 19:00:48: Logitech LED SDK could not be initialized.
[INFO] 19:00:48: Device, Logitech, was not initialized

**Comment by olliff** [comment]
You're right, official release works fine. Thanks! Awesome project!
