### ISSUE TITLE
Using Layer as "Away Effect"

### ISSUE THREAD

**Issue by rojnwa** [antonpup/Aurora#1248]
Hey there,

is there a way to use layer (e.g. "Ambient Layer") as Away Effect?

Kind regards

**Comment by Soulshake1** [comment]
Nice ! With Layers possible in Away Effect, I could finnaly add audio layer with a deylay of 5 mins to sync it with plane9 my screensaver that also supports audio in its effects, GREAT !! cant await THX

**Comment by xQwexx** [comment]
Duplicate of #768

**Comment by diogotr7** [comment]
This is now doable with overrides.
