### ISSUE TITLE
Support for Cooler Master Masterkeys Pro S & L

### ISSUE THREAD

**Issue by Atreyu333** [antonpup/Aurora#125]
Will you be considering adding support for the masterkeys lineup of keyboards?

**Comment by antonpup** [comment]
I see that they have an SDK. I will see what I can do. Thank you for your suggestion.

**Comment by antonpup** [comment]
I looked at their SDK, it was only for 32 bit processes. Aurora is a 64 bit application, so there's an issue with that. I will try to create a 32-bit server for the sdk to use with Aurora. I also do not have the keyboard to test with, their SDK is straightforward enough, but if I am going to write a server with a C# wrapper, it would be nice to be able to test.

**Comment by Atreyu333** [comment]
It's okay if it's going to be too much of hassle, but I could help you test it possibly if I don't have to do anything too technical.

**Comment by antonpup** [comment]
I will do some work on it and give you a testing version after the profile tabs have been converted into layers, so there's something to test with. Thanks for your input.

**Comment by ATGH15102AFMLD** [comment]
Now Cooler Master have 64-bit SDK ([link](http://www.coolermaster.com/service/support/masterkeys-pro-l/)).

**Comment by InfiniteBored** [comment]
Any news on this? Just got a Masterkeys Pro S and would love to use Aurora on it :)

**Comment by mm615657** [comment]
Masterkeys Pro L user (not RGB version though)here,looking forward to new progress

**Comment by antonpup** [comment]
I have been busy with school work as well as talking with companies about potential collaborations/jobs.

The support isn't off the table, I will see about adding it and then posting a test version for users to try.

**Comment by mm615657** [comment]
OMG it is done !!!
Gonna test it tomorrow.
Thanks :D

**Comment by cjbeames** [comment]
Just started using it, very good, although the keys don't all light up. Specifically the enter key, tilda key and the backslash key. UK version of the S RGB.

**Comment by Firedrops** [comment]
@cjbeames  @mm615657 

Sorry, I'm not sure this is the right place to ask, but may I know how you two got it working? My Aurora shows the keyboard as "connected", but it's exerting no control at all, it still follows CM's portal software. Are there other things I need to do?

**Comment by mm615657** [comment]
@Firedrops It is not working on my MasterKeys L White,check https://github.com/antonpup/Aurora/issues/802

**Comment by cjbeames** [comment]
Disable the Cooler master software.

**Comment by mm615657** [comment]
uninstalled the CM's portal software, doesn't help

**Comment by cjbeames** [comment]
Have you selected your keyboard in the setting of aurora?

**Comment by mm615657** [comment]
Yes, I do selected my keyboard in the Devices&Wrappers. i even manually set a new layer to make all keyboard showing white,but nothing happened except my keyboard not lighting up anymore.

**Comment by cjbeames** [comment]
There is a layer that highlights things like copy and paste when you hold down ctrl. Does that work?

**Comment by mm615657** [comment]
no，the preview and debug map shows that all keyboard should be white but my physial keyboard is dark.
i know how this software works,it was once worked in my self-modified version,but in official dev version it doesn't work at all

**Comment by Firedrops** [comment]
Pretty much in a same situation as @mm615657, except I've never had "my own" versions to play with before.
