### ISSUE TITLE
Device request: Patriot RGB keyboards

### ISSUE THREAD

**Issue by schwizzled** [antonpup/Aurora#1253]
Greetings,

Would it be possible to add support for Patriot Viper RGB keyboards, V760 and V770?

Thank you for an amazing program.  I love all the possibilities.

**Comment by simon-wh** [comment]
I can't find any SDK available for those keyboards, so, unfortunately, there isn't anything I can do to support the device. It may be possible to reverse engineer it, but I can't do that without access to a device.

**Comment by schwizzled** [comment]
Thank you.  I'm contacting Patriot just in case they can provide a SDK.  If I can ever get a v760 on the cheap, I'll send it your way ;-).
