### ISSUE TITLE
Feature request: Allow Logitech G910 Macro profile buttons to be trigger keys for toggle layer

### ISSUE THREAD

**Issue by schwizzled** [antonpup/Aurora#1255]
### Actual behavior:  Will not work because when assigning Trigger Keys for the Toggle layer, the M1-M3 keys are not recognized.

Greetings again.  I've been playing with the Toggle Layer, and I found that I could set up a toggle so that when I press the Mute button, the three keys to the right of Num Lock turn red.

I was hoping that I could create a toggle layer for the Macro keys, so that when I would press M1, M2, or M3, the colors for the macro keys would change.  However, the M1-M3 keys are not recognized as Trigger Keys when I am assigning. 

May not be possible, but thought I would throw it out there.

**Comment by SnakePin** [comment]
It is not possible for Aurora to read state of those buttons.
