### ISSUE TITLE
Corsair Media Keys

### ISSUE THREAD

**Issue by MikeUNtested** [antonpup/Aurora#126]
At the current time there is no way to edit the light from the media keys.
(Corsair K70)

**Comment by antonpup** [comment]
This was resolved a few days ago on the dev branch. It will be in the next version.

![demo](https://camo.githubusercontent.com/5614acc560075bffe6b81b24804909c996f74bd2/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f752f33303637353639302f4175726f72612f6b39355f64656d6f2e676966)
