### ISSUE TITLE
Overwatch wrapper not lighting up all the keys

### ISSUE THREAD

**Issue by luwifupo123** [antonpup/Aurora#1262]
### Expected behavior:
 The Corsair K95 keyboard LEDs should all be lit up.

### Actual behavior:
 Wrapper works as intended but some keys don't light up, specifically G6 -> G18 (weird because G1 -> G5 work fine). Also all media keys and lights/lock are not working, but I'm not sure those were working before.

### How often does this problem occur?

This problem started occuring today, no idea why, after the wrapper worked flawlessly for many months.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Patch Overwatch
2. Start the game
3. Wrapper kicks in as expected, only not fully

### What is the version of Aurora you are experiencing this issue with?

My version is beta v0.6.2b

### Does the previous version of Aurora have this issue?
The previous version, did not have this issue, however i just downloaded it and tested and it happens again, same thing. Also tried reinstalling the most recent version to no avail

**Comment by simon-wh** [comment]
The lighting from Overwatch is generated on that side and afaik no Razer keyboards have more than 5 G-keys so that's why the rest aren't lighting. For the rewrite I can try and get it working better as some effects (not all) could just be copied from the rest of the G keys

**Comment by luwifupo123** [comment]
You're right, I just checked and there are no Razers with more than 5 G-keys, and those aren't even being made anymore. It's really odd though, because I could have sworn that those keys were working before...

Do you know what effects can't be copied?

Anyway, thanks a lot for the help so far!

**Comment by SilentZen** [comment]
Possibly could you look into creating layer to clone keys, opened request #1269

**Comment by simon-wh** [comment]
Fixed thanks to #1341!
