### ISSUE TITLE
Logitech led SDK not longer working with Aurora 0.6.3 

### ISSUE THREAD

**Issue by Speedy-VonGofast** [antonpup/Aurora#1265]
### Expected behavior:
Logitech LED SDK starting with no issue and keyboard receiving Aurora's lighting

### Actual behavior:
Logitech LED SDK not starting and keyboard not receiving Aurora's lighting (still taking Logitech Assistant's lighting instead)

### How often does this problem occur?
This problem occurs every time.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1.  Updating Aurora from 0.6.2b to 0.6.3
2.  Start Aurora

### What is the version of Aurora you are experiencing this issue with?

My version is 0.6.3

### Does the previous version of Aurora have this issue?
The previous version, 0.6.2b did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:
https://pastebin.com/7wcKCL3b
https://imgur.com/a/HOy40Zy

**Comment by simon-wh** [comment]
Are you using Logitech GHub? If so, see #1264

**Comment by Speedy-VonGofast** [comment]
No, I was not using it. I Just installed GHub to try if it would not fix my issue but it's still not initializing

**Comment by simon-wh** [comment]
Did you use the G Hub build of Aurora after you installed it?

**Comment by JMZ10** [comment]
@simon-wh I have this issue as well after getting 0.6.3 and not using G Hub. Reinstalling fixes the issue, but is concerning updating broke it in the first place.

**Comment by simon-wh** [comment]
@JMZ10 Hm, that's really strange, updating shouldn't have broke it

**Comment by Speedy-VonGofast** [comment]
I confirm that uninstalling and re-installing fixed my issue as well.

**Comment by simon-wh** [comment]
Turned out that the updater was downloading the G-Hub version that was added in the assets of the release. If anyone experiences this issue then reinstall, should be sorted now

**Comment by YaLaMu939** [comment]
So hey I'm having the same issue here. After I have updated from 0.6.0 to 0.6.3. I have uninstalled both (the Logitech & Aurora) and reinstalled both. Multiple times and does not seem to work for me. And I'm not using G-Hub at all.  Not sure how to upload a log file, but here hopefully this works.
[2018-09-27 18.34.45.log](https://github.com/antonpup/Aurora/files/2426403/2018-09-27.18.34.45.log)

**Comment by diogotr7** [comment]
@YaLaMu939 you have the g huh version of Aurora. Reinstall Aurora.

**Comment by YaLaMu939** [comment]
> @YaLaMu939 you have the g huh version of Aurora. Reinstall Aurora.

Wow thank you! I have know idea how you knew that, but it worked. Didn't know there where two different installs.

**Comment by diogotr7** [comment]
@YaLaMu939 i got the version from the log. glad you got it working.
