### ISSUE TITLE
New update 0.6.3 problem

### ISSUE THREAD

**Issue by Doperr** [antonpup/Aurora#1266]
My G810 rgb not showing after version 0.6.3 update.
In bitmap and in app preview works fine but my keyboard not showing any light.

[2018-09-19 17.57.44.log](https://github.com/antonpup/Aurora/files/2396823/2018-09-19.17.57.44.log)

**Comment by simon-wh** [comment]
Your issue is due to a temporary problem with the updater downloading the ghub version of aurora. It is now fixed, you just need to reinstall Aurora with the lgs version. https://github.com/antonpup/Aurora/releases/tag/v0.6.3
