### ISSUE TITLE
Blizzard unauthorized third-party applications warning received.

### ISSUE THREAD

**Issue by stephenej** [antonpup/Aurora#1267]
### Expected behavior:
Aurora is working fine, Overwatch is talking to my keyboard correctly.

### Actual behavior:
Just got an warning email from Blizzard about third-party software while using Aurora. (I am not running anything else that possibly could be flagged)

### How often does this problem occur?
This problem occurs possibly every time playing Overwatch?

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Install Aurora
2. Run Aurora and Patch Overwatch
3. Play Overwatch and get a warning email.

### What is the version of Aurora you are experiencing this issue with?
My version is the current version Aurora v0.6.3 which I just installed today.

### Does the previous version of Aurora have this issue?
The previous version, Aurora v0.6.2b, did not have this issue the last time I used it.
I am not willing to risk downgrading, running it and getting my account locked.

### Please include any logs, screenshots, or files that are related to this issue:
![image](https://user-images.githubusercontent.com/5493213/45796369-2d770780-bc6e-11e8-8f05-2ac8dceef93a.png)

I have contacted Blizzard directly (Message I sent them as follows):

"Hello, I just received an email about using a third-party plugin while playing Overwatch.
The third-party program in question is Aurora (http://www.project-aurora.com/), which provides the ability for Overwatch to talk to my Logitech keyboard's RGB back-lighting like it does for Razer keyboards.

I really enjoy the game and enjoy it even more when my expensive keyboard has its features used. Is there anyway to white-list this program or could you provide me with information I could share with the developer of Aurora so it doesn't get flagged in the future? I would greatly appreciate any help on this matter."

I will post any replies they give as soon as I receive them.

**Comment by SilentZen** [comment]
No warnings for me yet and I used aurora with overwatch, could be delayed.
Probably best to see if there are other warnings.

**Comment by Gurjot95** [comment]
Blizzard have been sending messages to those who are using Visior or Pursuit with Overwatch. If you used any of those softwares even once then that could be reason as I really don't think Aurora should have any issues with Overwatch but I will confirm nevertheless.

**Comment by simon-wh** [comment]
@stephenej Have you use Visior or Pursuit as @Gurjot95 has mentioned?

**Comment by diogotr7** [comment]
I got the email and I used both visor and pursuit for a short while.
