### ISSUE TITLE
Cannot run as a standard user on Windows 10

### ISSUE THREAD

**Issue by Bloodcloak** [antonpup/Aurora#1268]
### Expected behavior:

Aurora should be able to run without having to go through the UAC prompt to run as an administrator
### Actual behavior:

Prompts to run as administrator and then uses the admin's config instead of the standard user's config
### How often does this problem occur?

This problem occurs... Every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Create a standard user on Windows 10
2. Install through that user
3. Prompts for admin and then runs with the admin config profile

### What is the version of Aurora you are experiencing this issue with?

My version is... beta v0.6.3

### Does the previous version of Aurora have this issue?
The previous version, beta v0.6.0b , did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

I can post if needed. The key thing is that before the desktop shortcut did not have the windows admin shield in the bottom right hand corner but now it does.

**Comment by simon-wh** [comment]
iirc we need to run as admin for consistently getting the process of the foreground application
