### ISSUE TITLE
Game Request:Warframe

### ISSUE THREAD

**Issue by X-Madar** [antonpup/Aurora#127]
Warframe is my favourite game and it's actually played by a lot of people.
I would like to see this game added in this project if it's possible

**Comment by ZephyrusFS** [comment]
I'd love to see a Warframe profile.

**Comment by WannabeLynx** [comment]
Isn't a Custom profile for warframe working?

**Comment by brainbug89** [comment]
FYI https://forums.warframe.com/topic/750293-rgb-keyboard-support/?do=findComment&comment=8350091 It seems like Warframe devs doesn't want to support RGB keyboards.

**Comment by simon-wh** [comment]
There doesn't appear to be any realistic way to get information from the game. Closing until plausible

**Comment by mmalyska** [comment]
They are now supporting Razer Chroma
http://warframe.wikia.com/wiki/Update_21

> Razer Chroma Compatibility
If you find joy in neon colors flashing to the beat of killing Grineer, plug in that Razer Chroma and enjoy the show! Please note that Razer Chroma and Warframe compatibility is a work-in-progress and more compatibility will be added as we continue to develop it.
