### ISSUE TITLE
Request: Extra cutomisable device

### ISSUE THREAD

**Issue by SilentZen** [antonpup/Aurora#1271]
Could extra device be added to device list that is generic and modifiable so updates will not remove it.
zip shows how to do currently, but would like to have seperate extra device to right of mouse.
Screenshot showing example

Thanks

[ExtraDevG502.zip](https://github.com/antonpup/Aurora/files/2400328/ExtraDevG502.zip)
![g504 hack](https://user-images.githubusercontent.com/16260816/45804508-37bbf480-bcb4-11e8-8ca1-842379abce1c.PNG)

**Comment by simon-wh** [comment]
I've got this planned for the rewrite

**Comment by SilentZen** [comment]
Awesome, thanks for your great work.

**Comment by Gurjot95** [comment]
Make sure to remind me to re-open if Simon doesn't do his planned Rewrite™ in few months :P
