### ISSUE TITLE
Corsair K95 Platinum overlay missing profile button

### ISSUE THREAD

**Issue by RKirkpatrick** [antonpup/Aurora#1273]
### Expected behavior:

Profile button should light up like the rest of the keyboard.

### Actual behavior:

Profile button is just black.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Go to Aurora Settings
2. Go to Devices & Wrappers
3. Select 'Corsair - K95 Platinum' for the Preferred Keyboard

### What is the version of Aurora you are experiencing this issue with?

My version is v0.6.3

### Please include any logs, screenshots, or files that are related to this issue:

Corsair ICue
<a href="https://imgur.com/PQGZzV6"><img src="https://i.imgur.com/PQGZzV6.jpg" title="source: imgur.com" /></a>
Aurora
<a href="https://imgur.com/wP610Dz"><img src="https://i.imgur.com/wP610Dz.jpg" title="source: imgur.com" /></a>

**Comment by Gurjot95** [comment]
I am sure Profile button is not programmable through SDK. It is designed that way. Profile button is meant to switch between iCue profiles but it's useless when it is controlled by third party app through SDK.

**Comment by Gurjot95** [comment]
@diogotr7 can be closed as it's not possible by SDK?
