### ISSUE TITLE
Could we get support for the GMMK TKL?

### ISSUE THREAD

**Issue by Endolite** [antonpup/Aurora#1274]
I've had a G Pro for a few months now and have been loving it's Aurora integration. It recently got an issue that requires me to send it back to be either replaced or refunded, and now that I know more about keyboards than I did back then, I'm considering picking up a GMMK TKL (mainly for switch and keycap customization). My only gripe with the product is the fact that it isn't supported by Aurora. If possible, could support for the board be added? Now, I know that the GGMK TKL is for a niche within a niche, but (if it doesn't take too much time away from more significant additions or fixes) could it be attempted?

**Comment by diogotr7** [comment]
Unfortunately they don't provide an SDK for us to work with, you can try emailing them and ask for one. As for a tkl keyboard with customizable switches and keycaps, the wooting one fits those requirements and is Aurora compatible :).

**Comment by diogotr7** [comment]
Also, someone on the discord has one and we're looking into possibly reverse engineering it, but it's a long shot.

**Comment by simon-wh** [comment]
Gonna close this for now
