### ISSUE TITLE
My keyboard does not respond to aurora (Recoil II)

### ISSUE THREAD

**Issue by XxAssebasxX** [antonpup/Aurora#1275]
I recently bought a new laptop, Recoil II of pcspecialist.co.uk (https://www.pcspecialist.co.uk/notebooks/recoil-II-15/), I think my laptop uses a clevo keyboard, but I'm not sure. I'm also new to aurora, so did I do something wrong? Or is my device just not compatible with aurora.
### Expected behavior:
Light on my keyboard

### Actual behavior:
Darkness still remains

### How often does this problem occur?
Every time

### What is the version of Aurora you are experiencing this issue with?
0.6.3

### Does the previous version of Aurora have this issue?
The previous version, did have this issue

### Please include any logs, screenshots, or files that are related to this issue:
https://pastebin.com/raw/WVhWdjNH

**Comment by simon-wh** [comment]
I can't find any details regarding how the keyboard in that laptop is set up. What did you see which made you think it is Clevo?

**Comment by XxAssebasxX** [comment]
> I can't find any details regarding how the keyboard in that laptop is set up. What did you see which made you think it is Clevo?

Because most the most laptops of this kind are from Clevo. If mine's not, I don't get support of Aurora, right?

**Comment by simon-wh** [comment]
Clevo is supported, so if it doesn't work for you it's probably not clevo. Without any SDK to interact with the lighting there isn't much I can do
