### ISSUE TITLE
Add support for Worms WMD

### ISSUE THREAD

**Issue by benjibrew** [antonpup/Aurora#128]
Hi. :)

Maybe it´s possible to add a Profile with Patch for Worms WMD?
The game supports the Razer Chroma Workshop. Wish it would work with my G810 too. :)

And let me say, I love your tool. Overwatch never felt this good. <3

Greetz BenjiBrew

**Comment by GreatBigBushyBeard** [comment]
I own Worms WMD, so once I have some time I'll look into supporting this.

**Comment by benjibrew** [comment]
Coolio thanks. :)

**Comment by antonpup** [comment]
I fit already support Razer Chroma. Then it should work with the Razer Wrapper just fine.

**Comment by GreatBigBushyBeard** [comment]
^^ Yeah, I just came to mention that you can temporarily patch Worms W.M.D. through the Overwatch patcher and it will show the lighting effects on your keyboard. Full support will come in the next version.

**Comment by benjibrew** [comment]
I love u guys. <3
