### ISSUE TITLE
Audio visualizer only works for left sound channel

### ISSUE THREAD

**Issue by mm615657** [antonpup/Aurora#1281]
### Expected behavior:
Audio visualizer supposed be responding for all sound channels

### Actual behavior:
Only left channel triggers visualizer,sounds from other channel was not reflected

### How often does this problem occur?
This problem occurs every time

### What is the version of Aurora you are experiencing this issue with?
My version is beta0.6.3-488

### Does the previous version of Aurora have this issue?
No idea

**Comment by simon-wh** [comment]
Fixed thanks to #1282
