### ISSUE TITLE
FFXV's Wrapper Lighting doesn't work

### ISSUE THREAD

**Issue by aaronhowser1** [antonpup/Aurora#1285]
### Expected behavior:
FFXV has a bunch of Chroma compatibility. [Here](https://www.youtube.com/watch?v=MV9Rt7bwxQE)'s an example. I made a profile pointed at the ffxv_s.exe and made a Wrapper Lighting Layer, but it didn't work.
This is using a Blackwidow Chroma V2 btw.

### Actual behavior:
The entire keyboard stays dark no matter what.

### How often does this problem occur?
All the time.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Make a new profile pointed to here:
![image](https://user-images.githubusercontent.com/15698722/46275491-cafdf100-c522-11e8-8682-082235a28d38.png)

2.  Set the settings like this:
![image](https://user-images.githubusercontent.com/15698722/46275496-d2bd9580-c522-11e8-8cc4-a636fe9b2d41.png)

3.  Make sure Chroma apps are enabled in Synapse: 
![image](https://user-images.githubusercontent.com/15698722/46275546-06002480-c523-11e8-9a14-1c629feb7faa.png)

4. Try playing the game: 
![image](https://user-images.githubusercontent.com/15698722/46275676-63947100-c523-11e8-9652-97a9b4bed54c.png) It should be glowing blue here.

### What is the version of Aurora you are experiencing this issue with?

My version is beta v0.6.3

### Does the previous version of Aurora have this issue?
I don't know, I haven't used it.

### Please include any logs, screenshots, or files that are related to this issue:
https://pastebin.com/du8ZN8RK

**Comment by diogotr7** [comment]
Try applying the chroma wrapper patch to that games folder.

**Comment by aaronhowser1** [comment]
Sorry, what is that? Where do I find that? I don't think I've heard of that before.

**Comment by diogotr7** [comment]
Click [this](https://i.imgur.com/jSmrdMk.png) button and then select the folder that games's exe is in

**Comment by aaronhowser1** [comment]
That worked perfectly, thanks! Is that safe to use in multiplayer games, or would I get banned? Has anyone gotten banned for it yet?
