### ISSUE TITLE
Keyboard lights not updating for some seconds after keypresses

### ISSUE THREAD

**Issue by Zazama** [antonpup/Aurora#1291]
Hey, I have a CoolerMaster MK750 and I'm experiencing some issues where the LEDs don't change their colors anymore for some seconds after some keypresses (see video). I'm not using an USB Hub or anything and the delay stays at 30 ms the whole time.

### Expected behavior:
Key lighting should work no matter what key is pressed.

### Actual behavior:
After some key presses, the lighting delays/lags and there's no change for 1-2 seconds on the keyboard. It can be triggered by any key on the keyboard.

### How often does this problem occur?
This problem occurs about every 10th keypress.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Setup some kind of animation like interactive layer or audio visualizer
2. Write or press keys

### What is the version of Aurora you are experiencing this issue with?
My version is v0.6.3

### Please include any logs, screenshots, or files that are related to this issue:
Logfile: https://pastebin.com/XJcZBYxf
Video: https://imgur.com/qGQIENd (please keep in mind that this happens with any key and it's not about pressing one key repeatedly but the issue also happens while writing normally + not only with the audio visualizer)

**Comment by Leomelonseeds** [comment]
Same issue. Please find a fix soon :P

**Comment by simon-wh** [comment]
There's been an update to the Cooler master SDK, could you try the [latest build](https://ci.appveyor.com/project/antonpup/aurora/build/artifacts) which includes the updated SDK to see if it helps?

**Comment by Zazama** [comment]
New build fixed it for me, big thank you :)

**Comment by ghost** [comment]
https://user-images.githubusercontent.com/44059860/103705141-8589c300-4f78-11eb-8610-bb7086e7f710.mp4

Hi, not sure if I should be reopening this issue or submitting a new one but it appears that the same issue is occurring with the SK650. The bitmap itself stutters as well. Keyboard is on the latest firmware (1.01.05) and Aurora is on build beta v0.81 +902-repwtfxv. Have tried it with and without installing the CM software, issue persists.
