### ISSUE TITLE
Support for Lioncast LK300

### ISSUE THREAD

**Issue by darkman1984** [antonpup/Aurora#1292]
First, congratulations for the project! It's very nice to see a software for nearly all RGB keyboards out there. But, unfortunaly i bought a Lioncast LK300 Keyboard and it's sadly not supported by Aurora.

I wrote the Lioncast Support that it would be very great if there is an ability to wrap up with chroma devices. A SDK would also be great, but it take a very long time :/

Can you eventually take contact up with lioncast to get the SDK that it can be supported in the near future?

Greetings
Chris

**Comment by qweqwertz** [comment]
Is there still no Support for Lioncast?

**Comment by darkman1984** [comment]
No and Lioncast has answered me that they has nothing planned to release a SDK -_- sadly. if i know that before i never bought a keyboard from them.
