### ISSUE TITLE
Logitech G910 Interactive Layer 

### ISSUE THREAD

**Issue by adamane** [antonpup/Aurora#1294]
### Expected behavior:
After I create a new interactive Layer and select a Effect type, Keys should Light up according to the selected Effect.

### Actual behavior:
The Keyboard stays compleatley dark.

### How often does this problem occur?
This problem occurs every time.

### What is the version of Aurora you are experiencing this issue with?
My version is beta v0.6.3

### Does the previous version of Aurora have this issue?
don´t know, just installed it.

### Please include any logs, screenshots, or files that are related to this issue:
https://pastebin.com/ZiaSBS1C
Recorded the error : https://youtu.be/_CV8Gax3neo

**Comment by adamane** [comment]
Edit: All the Layers that require a Keypress to Trigger aren´t working.

**Comment by simon-wh** [comment]
That's pretty strange, the system for getting the keypresses must be breaking on your system. Also, it's important to note that the keyboard in Aurora's ui only updates when the application is in focus, if you want to see the keyboard updates while you're tabbed into something else you need to go into settings and look at the debug bitmap

**Comment by adamane** [comment]
I just remembered this software, and the Bug on my end still exists. Where could i search for something that breaks the integration?
