### ISSUE TITLE
Request: Shadow Warrior 2 support

### ISSUE THREAD

**Issue by TimmehTheMeme** [antonpup/Aurora#1297]
It would be awesome to be able to have info from this game displayed on the KB seeing as it's so damn fast paced.

**Comment by TimmehTheMeme** [comment]
Yah, but I don't use razer.

Coolermaster is my preferred choice.

**Comment by diogotr7** [comment]
If you apply the Razer latch to the games folder, Aurora can capture the lights and send them to all other peripherals. Razer wrapper is needed because the game has Razer chroma effects, not because of your hardware. I have tested and the game works this way with my Logitech gear.

**Comment by Gurjot95** [comment]
SW2 should work now. Please update if it doesn't. I will open issue again.
