### ISSUE TITLE
[Request]League of legends

### ISSUE THREAD

**Issue by OldMartin** [antonpup/Aurora#1299]
the actual support  feel boring should be cool something like overwolf logitech spark effect for champions and some custom color for the logitech logo when you using a champion for example ashe the G turn blue and the mice full blue color in those feactures the spark its more better but the problem its outdated

**Comment by simon-wh** [comment]
The lighting for LoL is sent from the game itself, we don't actually have the details of what's going on in the game so we can't really achieve what you're looking for.
