### ISSUE TITLE
Problems with the layouts. / Add an option to manually change the keyboard layout?

### ISSUE THREAD

**Issue by NuclearMeltdown** [antonpup/Aurora#13]
Hello there,

I am currently using a Logitech g910. My problem is, that I'm using the US Region setting and the English language setting with a German keyboard. I am German, and I do live in Germany, I just like the English language better, which is why I decided to do this. Now, to my actual problem. Some of the keys are misplaced in the software and some of them don't light up. With some of them, also the interactive lighting effects don't work, or they originate from a completely different key from the one that is being pressed. I've tried to circumvent this problem by deleting the US layout and renaming the German one to be the US one. All keys light up, but the "ö" key for example originates from the US "~" one, that should be the "^" one on a German keyboard. But instead, the "^" key is still doing nothing. Also, the "z" and "y" keys are still swapped in the German layout, not on the displayed layout itself, but the interactive lighting effects still use the opposite keys (I have not tested, if there are any additional keys that have this problem). Also, on the displayed German layout within Aurora itself, there are a few minor mistakes still, which would be nice to be fixed.
 
And finally, I would very much like to thank you for making this program. I've waited a long time to get my g910 to be customized more than the Logitech Gaming Software allows me to, and I very much appreciate your work with Aurora so far. Keep up the awesome work.

Cheers, Alex

**Comment by antonpup** [comment]
I will be looking into adding and fixing layouts sometime this week.

As for the Y/Z swap, make sure you're running latest version of LGS. I know they fixed that internally in the later versions, as I had to swap the two keys.

You mentioned that there were a few mistakes on the layouts. Can you point them out to me in greater detail? As I only have a US keyboard to look at for an example, other layouts I have to look at pictures online and Wikipedia, which sometimes don't even have the same layouts.

As for the "Preferred Layout" I will see about adding that option. Probably will require a software restart to take effect though.

**Comment by NuclearMeltdown** [comment]
Hey there,
Thanks for the very quick response. I am running the latest version of LGS right now, so there should be no issue on my end, as my software updater states, that my software is up to date.

For the mistakes in the layout, as I said, the "~" key on the top left should be the "^" key. Furthermore, the "/" key on the top right should be the "´" key. I suppose US keyboards don't have the accent buttons at all (but I'm not sure). Additionally, on the numpad, instead of the "." should be a ",". Other than that, I don't seem to find any other issues with the keyboard layout. But as I mentioned, the "ö" key is still triggering interactive lighting effects originating from the (right now) "~" key and that key is triggering no effect when being pressed.

I hope this helps.

Cheers, Alex

**Comment by antonpup** [comment]
I added option to select a preferred keyboard brand and a preferred keyboard layout. Swapped the Y/Z and fixed the visual errors you pointed out. Those will be included in the next update.

I was not able to test the invalid key locations though, could you add me on steam so I can send you a version with more logging. Comment on my profile prior to adding me, as I have a pile of friend invites. [http://steamcommunity.com/id/pupant/](http://steamcommunity.com/id/pupant/)

Thank you for your help.
