### ISSUE TITLE
Battlefield 1 Lighting

### ISSUE THREAD

**Issue by antonpup** [antonpup/Aurora#130]
It should work out of the box. But official support would be ideal.

**Comment by Blizzardfall** [comment]
BF1 lighting also changes G keys and logo color on Logitech G910 keyboard.
Maybe Logitech updated the SDK?

**Comment by antonpup** [comment]
G keys and logo support is coming soon. But from my experience with BF1, I don't think they use anything special. The lighting implementation for BF1 seems to be just a "You're in menu, You're alive on X team, You're dead". I didn't see any more lighting. Plus, when you're in a menu, the menu effect doesn't trigger sometimes.

It's weird, it's a beta, I will add full support for it later, but users can still get lighting effects by patching their Logitech LED SDK from the devices tab in settings.

**Comment by antonpup** [comment]
Played around a bit more with Battlefield 1's light effects. And it seems to be done fairly well. They use `SetLighting`and `SetLightingForKeyWithScanCode` to set the entire keyboard to a specific color and then light up specific keys based on a scan code. I haven't implemented the scan code functionality, so Aurora users will only get the background lighting. I will add it for next version, but overall I take back what I said about the lighting implementation, it's pretty solid once I implement the scan codes.

**Comment by brainbug89** [comment]
Do I need to have any Logitech Software installed and running or where do I find the Logitech SDK dll?

**Comment by antonpup** [comment]
Aurora can patch/create the Logitech LED SDK files. You can go into devices tab and press "Patch Logitech LED SDK".

But keep in mind that the currently public version only has the background lighting, not per-key lighting effects.

**Comment by brainbug89** [comment]
hmm I patched Logitech LED SDK and still no background lighting at BF1... do I missing a setting?

**Comment by mnl1121** [comment]
I just found Aurora and am very interested. Two questions, has scan codes been implemented yet? Also does BF1 work with Corsair keyboards?

**Comment by antonpup** [comment]
@mnl1121 As far as I know, I never removed scan codes from the dev build. So they should be part of next update. And yes, if it works with Aurora, it will work. But natively BF1 works with Logitech devices.

**Comment by FrozenBeard** [comment]
K70 RGB Lux calling in here, how can I get support?

**Comment by simon-wh** [comment]
@FrozenBeard You should be able to get it to work through Patching the Logitech Wrapper in Settings as mentioned above.

**Comment by HighKo** [comment]
Tested BF1 today with v0.6 dev4. Just selected "The Devision" in Aurora and applied the Logitech patch. Worked for background lighting and single keys. Ironically, "The Division" does not work.

**Comment by diogotr7** [comment]
Proper bf1 support has been added.
