### ISSUE TITLE
Aurora stops working after sleep and auto log-in

### ISSUE THREAD

**Issue by yiweitech** [antonpup/Aurora#1301]
### Expected behavior:

Aurora should resume upon Windows resuming from sleep

### Actual behavior:

Aurora stops working after waking the machine up from sleep with the (Accounts > Sign-in options > Require sign-in set to "Never"). Under the "Device Manager" tab in Aurora all devices are stopped, pressing "start" on the desired devices (only logitech using LGS for me) does resume all functions again, as does a restart of Aurora. Basically what happened here, but while logging in normally works, auto-login doesn't. https://github.com/antonpup/Aurora/issues/1028#issuecomment-430584521

### How often does this problem occur?

This problem occurs every time the computer is waken from sleep.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Set Require sign-in to never
2. Put PC to sleep
3. Wake up PC

### What is the version of Aurora you are experiencing this issue with?

My version is 0.6.3

### Does the previous version of Aurora have this issue?
Yes, tried with 0.6.2b with the initial fix.

**Comment by charmarkk** [comment]
Came here to post just this; +1.

**Comment by Snafu7** [comment]
Same issue here, version 0.6.3, however my setup requires typing a password after sleep.
issue is fixed by killing aurora from task manager and launching again.

**Comment by gtr0y** [comment]
Having this as well, 0.6.3

**Comment by gradius-v** [comment]
Same issue.

**Comment by charmarkk** [comment]
Of note: one of the alpha releases one of the devs suggested fixes this. I’ll try and find that and link it back-I thought it was a general announcement at the time.

**Comment by noodlon** [comment]
I also have this issue. Been killing and re-opening Aurora every time I wake the pc up. I am using 0.6.3 with a Corsair Strafe RGB keyboard and a Logitech G502 mouse.

**Comment by Snafu7** [comment]
i do not get this issue anymore, nothing changed in my setup, just the issue stopped happening after some reboot.

**Comment by playnasc** [comment]
I still have this problem as of 1/13/19. I tried with 0.6.2b with the initial fix and it worked for a day or so but as of right now after 2 reboots I have to kill Aurora and start it up again. This is with my Logitech G810.

**Comment by simon-wh** [comment]
Could everyone who's experiencing this issue on v0.6.3 post their log file please? Also, it may help if you disable all the devices you don't have in Device Manager

**Comment by Snafu7** [comment]
[2019-01-19 17.24.57.log](https://github.com/antonpup/Aurora/files/2783798/2019-01-19.17.24.57.log)

**Comment by gobba** [comment]
Happens to me every day. My computer doesnt go to sleep. Leaving it on over the night i have to kill aurora when i come back to it. The keyboard lights looks ok, but the animations doesnt work. When i try to open aurora from the notification field down by the clock, nothing happens. 

[2019-01-20 22.55.45.log](https://github.com/antonpup/Aurora/files/2783981/2019-01-20.22.55.45.log)
[2019-01-22 18.47.11.log](https://github.com/antonpup/Aurora/files/2783983/2019-01-22.18.47.11.log)

**Comment by simon-wh** [comment]
Hey, could anyone experiencing this issue try [this build](https://ci.appveyor.com/project/antonpup/aurora/builds/21812338/artifacts) from the above commit. I've tested waking from sleep with & without auto-login and using Corsair, Cooler Master and Wooting. Works perfectly for Corsair and Wooting, but my CM MK750 didn't want to play nice with the sdk after waking up each time, so with CM ymmv.

**Comment by noodlon** [comment]
Seems to be working better now. Normally would need to kill it when I get on the computer in the morning, but working fine now. Thanks!

**Comment by simon-wh** [comment]
@noodlon Awesome!

I'm going to leave this issue open for a bit to get more feedback, hopefully it's finally sorted!

**Comment by gorch** [comment]
works fine for me as well.
Resuming from hibernation without required credentials and G910 light effects are active again.

**Comment by charmarkk** [comment]
Late to the party @simon-wh but it's working fine and stable with Logitech's G810. Thanks for the work!
