### ISSUE TITLE
[G810] Battlefield 1 Patch LED SDK crash

### ISSUE THREAD

**Issue by Doperr** [antonpup/Aurora#1303]
### How often does this problem occur?
Always

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Open Aurora
2. Click patch logitech led sdk in BF1
3. Aurora Crash

### What is the version of Aurora you are experiencing this issue with?
beta0.6.3
### Does the previous version of Aurora have this issue?
idk

### Please include any logs, screenshots, or files that are related to this issue:
Crash logs [ https://pastebin.com/kuJSQjNy ]

**Comment by diogotr7** [comment]
Did you click the button with bf1 open?

**Comment by diogotr7** [comment]
And you get the same exact error in both cases? That log looks like you probably had it open. Do it with it closed and send me a log of it still fails.

**Comment by Doperr** [comment]
> 
> 
> And you get the same exact error in both cases? That log looks like you probably had it open. Do it with it closed and send me a log of it still fails.

here is the latest crash logs
Open BF1 : https://pastebin.com/L64XXUZj
Close BF1 : https://pastebin.com/Yj8HxPi5

**Comment by Doperr** [comment]
Seems like I know the problem that LogitechLed.dll used by LGS. When I close LGS I can patch led sdk but keyboard no light while in BF1 so I open LGS again but also no light too. so I patch again and then it crash again. Maybe LGS cause this?

**Comment by diogotr7** [comment]
When you patch it should send lights to aurora, but it wont send them to LGS anymore. Have you restarted your system after patching? 

Also, if you want lgs to get the lights again, go into `C:\Program Files\Logitech Gaming Software\SDK\LED\x64` , delete `LogitechLed.dll` and rename `LogitechLed.dll.aurora_backup`, deleting the aurora_backup part. Repeat this for `C:\Program Files\Logitech Gaming Software\SDK\LED\x86` .

Again, as the wrapper makes light go to aurora, it shouldnt be needed.

**Comment by Doperr** [comment]
> 
> 
> When you patch it should send lights to aurora, but it wont send them to LGS anymore. Have you restarted your system after patching?
> 
> Also, if you want lgs to get the lights again, go into `C:\Program Files\Logitech Gaming Software\SDK\LED\x64` , delete `LogitechLed.dll` and rename `LogitechLed.dll.aurora_backup`, deleting the aurora_backup part. Repeat this for `C:\Program Files\Logitech Gaming Software\SDK\LED\x86` .
> 
> Again, as the wrapper makes light go to aurora, it shouldnt be needed.

WOW man it works. After follow your instructions it's work like charm. Thank you very much man!!

**Comment by Doperr** [comment]
**I'll close topic now**
