### ISSUE TITLE
G910 Orion Spectrum - Don't work on Overwatch

### ISSUE THREAD

**Issue by TheStarTaK** [antonpup/Aurora#1308]
### Expected behavior:
Profile Should load after I launch into the game.

### Actual behavior:
Keyboard goes dark and nothing happend when i'm on qp or training.

### How often does this problem occur?

This problem occurs... (Every time)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Aurora Loads
2. Check Overwatch Profile
3. Open Overwatch

### What is the version of Aurora you are experiencing this issue with?

My version is... (beta0.6.3)

### Does the previous version of Aurora have this issue?
didn't have aurora before.

**Comment by kurim** [comment]
If you use Logitech GHub instead of Logitech Gaming Center:

Please use the version mentioned in this post https://github.com/antonpup/Aurora/issues/1288#issuecomment-429633276 this works fine with latest Ghub and Overwatch.

**Comment by simon-wh** [comment]
Closing due to lack of follow up

**Comment by kurim** [comment]
@simon-wh,
with the 0.6.3-508 and still doing the manual copy way from the sdk_legacy_led_x64.dll to LogitechLed.dll it still works, but I need to re-apply the Overwatch patch.

Now you can close it as solved I think.
