### ISSUE TITLE
Away effect: Turn lighting off

### ISSUE THREAD

**Issue by Acharnite** [antonpup/Aurora#131]
It would be wonderful, as an addition to the "dim" option in the away effects, to have one that completely turns off the lighting.

Perhaps even an option to apply the away effects, when the screen turns off, like the razer synapse 2.0 software can do :)

**Comment by brainbug89** [comment]
> Perhaps even an option to apply the away effects, when the screen turns off, like the razer synapse 2.0 software can do :)

Just set the same time for screen off and away effect

**Comment by antonpup** [comment]
Will look into. Thanks for the suggestion.
