### ISSUE TITLE
Aurora does not respond th what is happening in-game

### ISSUE THREAD

**Issue by TheKingofChicken** [antonpup/Aurora#1312]
### How often does this problem occur?

This problem occurs... (Fill in here)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Download aurora
2. open a game
3. get base lighting pattern
4.expect light to change

### What is the version of Aurora you are experiencing this issue with?

My version is... (Fill in here)
The latest version
### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.
none, I had installed for about a week without touching it, telling myself I would fix the issue later

**Comment by diogotr7** [comment]
Which game did you try and how did you expect the lights to change?

**Comment by Therrk** [comment]
Wow I don't think I could've been more unhelpful if I tried, sorry about that
