### ISSUE TITLE
Interactive layer does not respond to keypresses if focus is changed to another machine via Mouse Without Borders

### ISSUE THREAD

**Issue by Snafu7** [antonpup/Aurora#1313]
Hi, i'd just report this behaviour here in case you werent aware of it. This is not in any way a big issue and to be honest i do not have any expectation to see a fix for it, specially that this is probably quite a niche use. Anyways, Aurora is fantastic, thank you very much for all the time you invested in creating it.

### Expected behavior:

Interactive effects should be trigerred as usual
### Actual behavior:

When mouse/kb focus is on another machine via Mouse Without Borders the interactive layer does not  trigger
### How often does this problem occur?

Every time.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. grab mouse without borders from https://www.microsoft.com/en-us/download/details.aspx?id=35460
2. install on multiple PC's and configure the connection.
3. switch the input to another machine.

### What is the version of Aurora you are experiencing this issue with?

My version is Beta V0.6.3

**Comment by simon-wh** [comment]
I doubt there's much we can do about this, as I would assume when you switch to the other machine it is taking all key presses and blocking them from software on your main machine.
