### ISSUE TITLE
Logitech Wrapper Not Patching

### ISSUE THREAD

**Issue by Endolite** [antonpup/Aurora#1314]
### Expected behavior:

LGS should be patched.
### Actual behavior:

Instead, I get an error message saying the DLL can't be used because it's being used by another process.
### How often does this problem occur?

This problem occurs every time.
### Please describe the steps to reproduce this issue:
I don't know how this issue can be reproduced.
### What is the version of Aurora you are experiencing this issue with?

My version is beta v0.6.3.

### Does the previous version of Aurora have this issue?
The previous versions did not have this issue.
### Please include any logs, screenshots, or files that are related to this issue:
 Logs: https://pastebin.com/FzGvKX67

**Comment by simon-wh** [comment]
You likely need to make sure that you do not have anything open which connects to Logitech, so games. It might also help to close LGS, but that shouldn't be needed.

**Comment by Endolite** [comment]
Sorry about the wait! Everything's working now. Thanks!
