### ISSUE TITLE
EQ doesn't work when switching output devices

### ISSUE THREAD

**Issue by Jappachino** [antonpup/Aurora#1315]
Hi, I thought I'd just let you know about this issue that I noticed. It's nothing major, but would be nice if you can look into it. Aurora is great though, keep up the amazing work!!

### Expected behavior:
When default output device is switched, Equalizer (Audio Visualizer layer) will pull audio information from the new device output.

### Actual behavior:
The Equalizer monitors only the first device connected, so it stops working when switched. Operates normally once switched back to the initial device. Aurora itself is still running fine, just the EQ layer is not doing anything.

### How often does this problem occur?
All the time.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Have two (or more) audio output devices plugged in. USB, 3.5mm Jack, HDMI etc.
2. Start playing some audio, check if equalizer is picking up information
3. Switch output to one of the other devices, and it will stop receiving signal. 

### What is the version of Aurora you are experiencing this issue with?

My version is Aurora beta 0.6.3

### Does the previous version of Aurora have this issue?
Always had issues, as far as I remember.

**Comment by simon-wh** [comment]
Hm, that's pretty strange, I thought I had set it up to work properly in that case, I'll try and have a look into it

**Comment by simon-wh** [comment]
Having looked at the code it should switch over if the Audio device ID changes, I'm not sure why it's not switching for you. Right now I don't have the environment to be able to try and replicate your issue, so I'll try and look into it later

**Comment by Jappachino** [comment]
I just noticed that, if I have my Vive's audio output switched to have it go through the USB device, Aurora will have no problems switching over between my DAC and the VR Headset which are both USB output devices. However, switching to my speakers (3.5mm port) will make the EQ layer freeze. It will un-freeze after I switch it back to one of my USB output devices, though.

**Comment by BowsetteLewdsPls** [comment]
I found a way to fix it. I had the same problem. I have msi mobo. Within your sound configuration app. Open it up. Make sure its on 7.1 speakers. That worked for me. Anything else does not want to work with the eq audio.

**Comment by Jappachino** [comment]
@BowsetteLewdsPls Thanks so much!! It worked!
