### ISSUE TITLE
League Of Legends lightning effects not working

### ISSUE THREAD

**Issue by TheGamer14** [antonpup/Aurora#1316]
### Expected behavior:

I have patched League and enabled lightning in the config so it should have responsive lightning.
### Actual behavior:

Keyboard goes completely dark when starting league
### How often does this problem occur?

This problem occurs... every time i start league

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1.  Patching league
2. Enabling LightFx
3. Starting League

### What is the version of Aurora you are experiencing this issue with?

My version is... beta v0.6.3

### Does the previous version of Aurora have this issue?
The previous version, 0,6,1 ), did have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

Logs show nothing interesting

**Comment by diogotr7** [comment]
Double check you have the dll in the correct place. The problem with league is every patch the path to the game executable changes as well, so you need to patch again every update. League is working on my system on this patch.

**Comment by TheGamer14** [comment]
have already checked that i have patched the correct version and done it several times

**Comment by TheGamer14** [comment]
Don't know what i did but i created a new profile reset it to default and then it started working.
