### ISSUE TITLE
Game support for Middle Earth: Shadow of War

### ISSUE THREAD

**Issue by Ricostyle21Dev** [antonpup/Aurora#1318]
Could you add support for Middle Earth: Shadow of War just like you added support for Shadow of Mordor? Thanks for the app!

**Comment by diogotr7** [comment]
I don't think that game has LightFX support so we can't add support the same way. You can try applying the patch and see if it works though.

**Comment by Ricostyle21Dev** [comment]
Sorry, what patch?

**Comment by diogotr7** [comment]
Aurora settings > devices and wrappers > apply patch for lightfx (either 64 or 32 bits depending on the game).  I'm not expecting it to work but you can give it a try

**Comment by Ricostyle21Dev** [comment]
Then I assume make a new lighting profile for it?

**Comment by diogotr7** [comment]
If the game has any support for it you shouldnt need to. just make sure to apply the patch to the same folder the game's .exe is in

**Comment by Ricostyle21Dev** [comment]
K, will try this tomorrow, quick other question, how do I stop the desktop layer from activating in for example Spotify if I have made a profile for Spotify?

**Comment by simon-wh** [comment]
@Ricostyle21Dev Any follow up on this?

**Comment by Ricostyle21Dev** [comment]
My problem is that I don't know how to apply the patch in a specific folder...

**Comment by simon-wh** [comment]
You click apply and go to the folder

**Comment by Ricostyle21Dev** [comment]
When I click apply in the settings it just says Applied Patch

**Comment by diogotr7** [comment]
You probably tried applying the Logitech Patch.
Try applying the Lightfx(64-bit) patch, as that's the most likely one to work.
The button for that is in Settings > Devices & Wrappers

**Comment by Ricostyle21Dev** [comment]
Nope nothing…

**Comment by simon-wh** [comment]
@Ricostyle21Dev The support for Shadow of Mordor in Aurora is Middle-earth: Shadow of Mordor. Could you click on the profile, click the "Overview" button and follow the setup instructions

**Comment by simon-wh** [comment]
Ignore that last comment, I misread the title. It doesn't see like Shadow of War has LightFX support like Shadow of Mordor does, so we can't really support it right now
