### ISSUE TITLE
Aurora crashes Hunt Showdown if left open during gameplay.

### ISSUE THREAD

**Issue by mawatkinson** [antonpup/Aurora#1327]
> ### What are you experiencing an issue with?
> * [x]  Aurora
> * [ ] Aurora supported game, (Fill in the game)
> * [ ]  Aurora Wrapper
> * [ ]  Aurora Profile
> * [ ]  Aurora supported device, (Fill in problematic devices)
> * [ ]  Aurora Scripts
> * [ ]  Aurora Updater
> * [ ]  Aurora Lighting issue
> * [x]  Other, (Crashes unsupported game - Hunt Showdown)
> 
> ### What kind of an issue is it?
> * [x]  Crash
> * [ ]  Performance problems
> * [ ]  Visual bug
> * [ ]  Localization issue
> * [ ]  Enhancement suggestion
> * [ ]  Device issue
> * [ ] Other
> 
> ### Expected behavior:
> Desktop profile should be used during unsupported game being played
> 
> ### Actual behavior:
> When playing Hunt Showdown, desktop profile is shown but within 5-10 minutes the game crashes to desktop
> 
> ### How often does this problem occur?
> Almost every game played, shutting down Aurora before starting the game causes the issue to go away.
> 
> ### Please describe the steps to reproduce this issue:
> Open Logitech Gaming Software, Open Aurora, Configure a desktop profile, launch Hunt showdown and start a game.
> 
> 
> ### What is the version of Aurora you are experiencing this issue with?
> My version is... Latest
> 
> ### Does the previous version of Aurora have this issue?
> Not tested.
> 
> ### Please include any logs, screenshots, or files that are related to this issue:
> For logs, you can use: http://pastebin.com/
> For screenshots, you can use: http://imgur.com/
> For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
That's pretty strange that that would happen, Aurora shouldn't be doing anything to cause that.
Have a look at [this reddit post](https://www.reddit.com/r/HuntShowdown/comments/8ybkhm/game_wont_stop_crashing_right_at_the_start_of_the/). Seems like it may be on the game's side
