### ISSUE TITLE
Master layer request

### ISSUE THREAD

**Issue by TheKingofChicken** [antonpup/Aurora#1328]
Would it be possible to have a master layer(s), so that an effect on a specific key wouldn't change even when a new gawe is opened? Essentially like a layer that overwrites everything. I have no idea if this even could be done, and if it is, how easy it could be.

**Comment by Gurjot95** [comment]
You can just add layer over the top of wrapper layer. As long as layer remains on top, it will overwrite all the effects.

**Comment by diogotr7** [comment]
This is now possible with overlays.
