### ISSUE TITLE
Still Assigning to non existent Color Zone

### ISSUE THREAD

**Issue by thlawton** [antonpup/Aurora#133]
Small bug that is minor inconvenience. If there is one Color Zone, and the 'Assign Keys' button is pressed, and then the Color Zone is deleted via the 'Remove Zone' button. The 'Stop Assigning' button is greyed out, but acts as if you are still assigning keys to a non-existent zone. This prevents you from assigning keys anywhere else, as the error 'You are recording a key sequence for Color Zone Keys' displays.

**Comment by antonpup** [comment]
Thank you for your report. I'll look into it.

**Comment by simon-wh** [comment]
Colour Zones are no longer being developed.
