### ISSUE TITLE
Request for Battlefield V game support

### ISSUE THREAD

**Issue by MrLinford** [antonpup/Aurora#1332]
As a user, I would like to have support for Battlefield V.

I would like to have the same behaviour as the natively support Logitech (REF: [Logitech Demo Page](https://www.logitechg.com/en-us/battlefield-v-gaming-gear.htm))

**Comment by Ricostyle21Dev** [comment]
You could try to patch the Logitech SDK as it should work with Logitech out of the box, meaning Aurora should work with it as well.

**Comment by MrLinford** [comment]
even with corsair gear?


> You could try to patch the Logitech SDK as it should work with Logitech out of the box, meaning Aurora should work with it as well.

**Comment by Ricostyle21Dev** [comment]
Yep

**Comment by diogotr7** [comment]
The patch likely won't work as the game needs g hub for the lighting which uses a different way of communicating with the game.

**Comment by MrLinford** [comment]
I tried the Logitech Patching and it indeed did not work.

**Comment by Cocotteseb** [comment]
Yep already tried the patch and doesn't work, that's why my vote +1 to this feature request.
I've also installed the G-hub software with no success

I haven't find in the code why there is a special version of the dll and what changes have been made to it, as we are doing unmanaged calls...

**Comment by Ricostyle21Dev** [comment]
I could send you my install folder but I doubt that’ll help XD

**Comment by Gurjot95** [comment]
You can try the dll I posted above.

**Comment by MrLinford** [comment]
I have done the below:

- Install LGHUB
- Close LGHUB
- Back up DLLs
- Copied your DLLs to LGHUB install DIR
- Install Aurora 0.6.3
- Setup Corsair SDK
- Installed Wrapper Patch for Logitech
- Launched LGHUB
- Disabled BF V Corsair profile in iCUE
- Launched Game

This failed, desktop lighting profile remained active

**Comment by Gurjot95** [comment]
Can you DM me on discord?

**Comment by Gurjot95** [comment]
I spent some time on this and it seems BF V uses signature/hash check or something before it loads DLL. Therefore it doesn't load wrapper and can only load logitech signed DLL. But good news is BF V works with LGS also so it doesn't require GHUB or use new SDK (There is no new sdk). Future Logitech games should work with old wrapper as it is unless as long as it doesn't verify DLL.

I think we can close this issue now.
