### ISSUE TITLE
ALT + Tab shortcuts stay lit after performing the shortcut

### ISSUE THREAD

**Issue by Xantha123** [antonpup/Aurora#134]
Hi,
after using the ALT+Tab shortcut on my Corsair K70 Rapidfire RGB the shortcuts assigned to the ALT key stay lit. When pressing ALT again it resets.

Cheers

**Comment by antonpup** [comment]
Yes, it's a known issue. You can also press CTRL+ALT+DELETE and it will stick with CTRL. As I understand, it is a permissions issue. When Aurora is ran as a standard user, it cannot receive a "key up" command when you're in a process ran by an admin. So, Aurora thinks that CTRL was never released.

**Comment by Xantha123** [comment]
Thanks for the info. Running Aurora with admin permissions seems to solve the porblem.

**Comment by brainbug89** [comment]
I always running the app as admin, because the Aurora-Updater.exe ask for admin rights at every start :-/
