### ISSUE TITLE
RazerFirefly

### ISSUE THREAD

**Issue by notcarksss** [antonpup/Aurora#1343]
No support for razer firefly

**Comment by Gurjot95** [comment]
The support is available in latest Bleeding Edge build.

**Comment by notcarksss** [comment]
Thank you

**Comment by notcarksss** [comment]
Where could I find this build

**Comment by notcarksss** [comment]
So, I downloaded the Bleeding Edge build and I still can't find the option for Razer Firefly. Have I missed anything or?

**Comment by diogotr7** [comment]
In the mouse picker there should be an option for mousepad. It doesn't specifically say Firefly because that layout is the same as the Corsair mousepad.

**Comment by notcarksss** [comment]
Ohhh, I see it now, thank you very much.

**Comment by Gurjot95** [comment]
We should close this issue now

**Comment by simon-wh** [comment]
Fixed thanks to #1331!
