### ISSUE TITLE
Aurora crashes on startup with any GHUB

### ISSUE THREAD

**Issue by karabin1000pl** [antonpup/Aurora#1348]
### Expected behavior:

Aurora should start

### Actual behavior:

Aurora crashes on startup

### How often does this problem occur?

This problem occurs every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Start Aurora
2. Wait
3. Aurora crashes after 1 second or doesnt start

### What is the version of Aurora you are experiencing this issue with?

My version is 0.6.3-488

### Does the previous version of Aurora have this issue?
The previous version, (0.6.3), have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

Log: https://pastebin.com/8bWuHd83

**Comment by diogotr7** [comment]
[this](https://ci.appveyor.com/project/antonpup/aurora/builds/19486678/artifacts) version fixes this issue

**Comment by karabin1000pl** [comment]
Thank you very much it worked! But i'm curious why in download page corrupted version is available. This makes a lot of trouble for new users.
