### ISSUE TITLE
Spotify Equalizer

### ISSUE THREAD

**Issue by Xantha123** [antonpup/Aurora#135]
Hi, 
is there an option to use the keyboard (K70 RGB Rapidfire) in an Equalizer mode when Spotify is playing (with different color settings)?

Cheers

**Comment by brainbug89** [comment]
Duplicate of #34 

It's planned for a later version.

**Comment by antonpup** [comment]
Like @brainbug89 said, this is a duplicate. I will be including a general visualizer for both microphone and speakers audio. I will close this issue, but please continue the discussion on issue #34 .

Thank you.

**Comment by apkright360** [comment]
Try[ Spotify modified apk](https://thespotify.com/spotify-premium-apk/) for high-quality audio experience with that you do not need to any Equalizer
