### ISSUE TITLE
Device Request: Roccat Vulcan

### ISSUE THREAD

**Issue by grant-m-s** [antonpup/Aurora#1350]
Following a conversation on the Discord Support channel, The Vulcan series doesn't seem to work and so I would love to have this implemented.

**Comment by simon-wh** [comment]
I can't find anything saying that the Roccat Vulcan is supported through TalkFX, so I don't think there's much we can do at this time.

**Comment by TomberWolf** [comment]
+1 for Roccat Vulcan / Swarm Drivers

**Comment by Ranek99** [comment]
+1 for this :( i wish i have sync RGB on those :C

**Comment by SnakePin** [comment]
Can anyone here test this to see if this changes colors and if it does, then help with mapping keys https://github.com/SnakePin/Roccat-Vulcan-Aurora-KeyMapper-Study/releases/download/0.2/Release.zip

**Comment by SnakePin** [comment]
@TomberWolf You have to run the program inside the zip and see if colors change on your kb, if they do then press on the lit up keys until all keys are done to help with key mapping.

**Comment by TomberWolf** [comment]
![09-05-_2019_12-50-53](https://user-images.githubusercontent.com/9993839/57448248-30545600-7259-11e9-9b1c-4c457cd46ea5.png)

**Comment by SnakePin** [comment]
@TomberWolf Can you try this one https://github.com/SnakePin/Roccat-Vulcan-Aurora-KeyMapper-Study/releases/download/0.3/Release.zip also if you have a Discord account that would be helpful for easier communication.

**Comment by Ranek99** [comment]
Hello! I Tried it, i get something like this : 

![image](https://user-images.githubusercontent.com/50290357/57481570-b1840b00-72a2-11e9-9dbe-388ddbe7d26e.png)

**Comment by SnakePin** [comment]
@Ranek99 okay this one should work https://github.com/SnakePin/Roccat-Vulcan-Aurora-KeyMapper-Study/releases/download/0.4/Release.zip

**Comment by Ranek99** [comment]
Hello ! Thanks for fast answer.

**
![image](https://user-images.githubusercontent.com/50290357/57482312-9dd9a400-72a4-11e9-83be-9914295274a5.png)
**

Still same. Tell me 1 thing. I need to have Roccat Talk FX. But is roccat swarm won't do any problems ?

**Comment by TomberWolf** [comment]
The keyboard is reacting as soon as I start the RCT_TEXT.exe.
It flickers for a short time.

![10-05-_2019_00-11-37](https://user-images.githubusercontent.com/9993839/57490114-78569580-72b8-11e9-952c-6e96cf7e48d2.png)

Do you need infos about my Swarm settings?

**Comment by SnakePin** [comment]
I'm sorry ppl, I just found out the error, the `index` was -4 when `i` was 0 in line 280, now it shouldn't happen anymore. Try this build https://github.com/SnakePin/Roccat-Vulcan-Aurora-KeyMapper-Study/releases/download/0.5/Release.zip

**Comment by TomberWolf** [comment]
Seems to work
![11-05-_2019_01-09-49](https://user-images.githubusercontent.com/9993839/57560994-a7890780-7389-11e9-88c8-e6f0e3c6a46e.png)

**Comment by SnakePin** [comment]
@TomberWolf Can you do the key mapping process and send the output file, it shows output file's location at the end of process, btw if any unrecognized key is lit up then just press ESC on those, I forgot to ask user to press the key

**Comment by TomberWolf** [comment]
Uhm... that's the only screen I got.
No keymapping process.

**Comment by SnakePin** [comment]
Don't you have any lit up keys on the keyboard @TomberWolf ?

**Comment by TomberWolf** [comment]
Oh, okay. When I turn off the SWARM Software and start the RCT_TEST, ESC turns red.
But nothing happens if I press it.
There's not other key lit-up.

**Comment by diogotr7** [comment]
Discord would be a much easier way to communicate all of this, if that's possible

**Comment by TomberWolf** [comment]
> 
> 
> Discord would be a much easier way to communicate all of this, if that's possible

I know. I'm at work so that's not an option for me now, sorry.

**Comment by SnakePin** [comment]
Oh I'm again sorry @TomberWolf cause I noticed key detection process isn't working well, I'm trying to find out the reason.

**Comment by SnakePin** [comment]
@TomberWolf Can you try this: https://github.com/SnakePin/Roccat-Vulcan-Aurora-KeyMapper-Study/releases/download/0.6/Release.zip

**Comment by TomberWolf** [comment]
Sure.

ESC was lit-up but no other key.
So I pressed ESC.

Please take a look at the screenshot for the results:

![11-05-_2019_02-58-30](https://user-images.githubusercontent.com/9993839/57563028-02762b00-7399-11e9-81de-6735b10ece82.png)

**Comment by SnakePin** [comment]
If no key is lit up after the `Press the lit up key.` message then press ESC too, it will still up the index

**Comment by TomberWolf** [comment]
Oh, okay. I got it. Sorry.
Please notice: I had two times with lit up keys. Both times, two keys were lit-up simultaneously. The "2" and the "Y" (German layout. English layout it would be the "Z" key).
At the first time I pressed "2" the second time I pressed "Y".
[ROCCAT_KBMAP_OUTPUT.txt](https://github.com/antonpup/Aurora/files/3168472/ROCCAT_KBMAP_OUTPUT.txt)

**Comment by SnakePin** [comment]
Strange, all indexes show ESC key's VK code in the output file, can't reproduce on my computer though.

**Comment by grant-m-s** [comment]
I ran the same test. Apart from the initial ESC key lighting up, no keys lit up so just ended up pressing ESC the whole time

**Comment by Ranek99** [comment]
Tested - Same as grant-m-s only esc lit up.

If u want to make live-tests- pm me on Discord - Name's Trigger :)

**Comment by SnakePin** [comment]
Can you ppl test this build of Aurora https://github.com/SnakePin/Aurora/releases/download/vulcan-test-0.1/Roccat-Vulcan-Test-Release.zip , tell me if it doesn't work or if some keys are at wrong position. Btw make sure Roccat Swarm is fully closed and do not run Roccat Swarm while testing this, this skips Roccat Swarm and directly communicates with keyboard.

**Comment by TomberWolf** [comment]
Seems to work as soons as the SWARM software is closed.
Roccat Vulcan was detected and the right keys lit up if I select the Roccat Ryos as Preferred Keyboard.
Now we have to find a way to run it beside the SWARM software. If I keep it active the keyboard is flickering like it has epilepsy. ;-)

**Comment by SnakePin** [comment]
@TomberWolf Sadly Roccat Swarm software doesn't allow other programs to control this keyboard, that's why it is flickering. There is no way to prevent this.

**Comment by embrion44** [comment]
> 
> 
> @TomberWolf Sadly Roccat Swarm software doesn't allow other programs to control this keyboard, that's why it is flickering. There is no way to prevent this. Roccat SWARM must be closed.

Hi @SnakePin . How to worka round the fact that without SWAM running media keys (FN + F9-F12) do not work rubber mute button doesn't blink on muted? I've tried to keep SWARM running with "black" color backlight but it still generates a conflict.

**Comment by diogotr7** [comment]
Support for the vulcan has now been separated from unified HID and will be ready to use in the next version of aurora (probably v0.7.2)
