### ISSUE TITLE
in Source Keys when selected "visualName": "", in device configs ignored for Additional Light 1-19

### ISSUE THREAD

**Issue by SilentZen** [antonpup/Aurora#1355]
### Expected behavior:
Should show entry in "visualName": "", 

### Actual behavior:
shows Additional Light 1 - Additional Light 19

### How often does this problem occur?

every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Create layout using additional keys 1-19
2. Select keys in source keys
3. label should be defined ones in "visualName": "", 

### What is the version of Aurora you are experiencing this issue with?

My version is... 0.6.3-522

### Does the previous version of Aurora have this issue?
Yes

**Comment by Gurjot95** [comment]
This isn't issue. Additional Keys names are intentionally ignored in layout file so we can create small size LED without printing its name all over it as it won't fit the whole name. Check for keyboardlayoutmanager.cs, there is code which tells the Aurora to ignore visualname tag for Additional keys.

**Comment by SilentZen** [comment]
Thanks for quick response.
As there are now 32 Additional keys could the extra ones above 19  be added to keyboardlayoutmanager.cs so that the behaviour of Additional Keys is the same.

**Comment by simon-wh** [comment]
@SilentZen Sorted
