### ISSUE TITLE
Witcher 3: no realtime reaction

### ISSUE THREAD

**Issue by wlanowski** [antonpup/Aurora#1358]
Aurora detects when I play Witcher 3, but unfortunately it does not react on ingame-actions like changing the active sign. Is there something to set?

**Comment by diogotr7** [comment]
Have you installed the mod?

**Comment by wlanowski** [comment]
which mod I have to install?

**Comment by wlanowski** [comment]
Ah! I see in the overview settings. Sorry for this spam Issue!

**Comment by diogotr7** [comment]
It works in my testing but the method is not perfect. If you need any help the discord would be a better to not spam notifications :)
