### ISSUE TITLE
Game Support: Eurotruck Simulator 2

### ISSUE THREAD

**Issue by Shadow091995** [antonpup/Aurora#136]
Hey,

it would be nice to have the turn signals on the keyboard, or like the backlight of the insturment panel on the keys. As well as keys that are used to turn on/off stuff (light, indicators or rotating warn lights) Such stuff would be nice, if possible :D

**Comment by brainbug89** [comment]
Should be possible: https://www.reddit.com/r/trucksim/comments/45nnm0/logitech_g910_light_enabler_for_ats_and_ets2/?st=isndd6lx&sh=a61b236d

Euro Truck Simulator 2 / American Truck Simulator have a SDK wich provide such information

**Comment by antonpup** [comment]
It is possible to do, I think it was suggested before. But I don't own the game, so I cannot make an implementation for it.

**Comment by MaitreDede** [comment]
Game integration is made using the telemetry API : https://github.com/nlhans/ets2-sdk-plugin

There is a sample C# : https://github.com/nlhans/ets2-sdk-plugin/tree/master/ets2-client/C%23

This game support may be tagged as "beta", so users can try it themselves. Also players that own the game can give it a try. (I own it)

**Comment by simon-wh** [comment]
Support has been added with #1105

**Comment by littlepaddy** [comment]
hi you I have the Logitech G920 Driving Force Racing Wheel for the pc but I cannot get this to work in euro truck simulator 2 it picks up in the game but will not set up in the game I no this will work for this game as I have seen videos on youtube people playing the game can you help me please
