### ISSUE TITLE
League of Legends Profile Does Not Work

### ISSUE THREAD

**Issue by comander5** [antonpup/Aurora#1360]
I've already patched the game and enabled the LightFX. But, when I'm actually in League, for the most part, the lights stay static. The QWER keys are lit blue, and everything else is green. But, when I do certain things, like but an item, the green keys will dim slightly, but that's about it.

I HAVE looked at the other topics about this issue, but I don't see a solution that's worked for me.
### Expected behavior:

It should detect  HP etc., like it says it's supposed to.
### Actual behavior:

All keys are a static color
### How often does this problem occur?
This problem occurs... Every time

### What is the version of Aurora you are experiencing this issue with?

My version is... beta 0.6.3

### Does the previous version of Aurora have this issue?
Not tested

**Comment by diogotr7** [comment]
The colors I know of are:

Grey when dead
Blue when someone on your team pings
Red when you take damage or are low up
Green otherwise.

I don't know if your effects are actually different because they usually either work on don't at all. If the logs have any useful info that would help.

**Comment by QuentinMcCarthy** [comment]
I have this same problem, I'm not entirely sure what the keys are supposed to do due to being a first-time user, but all the keys except QWER are green until low hp, then they're red, dimming slightly on buying an item, no other changes.

**Comment by diogotr7** [comment]
This is all intended behaviour.
