### ISSUE TITLE
Aurora stops working after waking from sleep. App needs reboot and sometimes keyboard reconnected

### ISSUE THREAD

**Issue by Thelgow** [antonpup/Aurora#1361]
### Expected behavior:

Wake up and still work. 
### Actual behavior:

I brought my CM Master Keys Pro L in to work for the holidays and have it set to Glitch mode to just flicker. When it goes to sleep the colors stop blinking and freeze with the random colors. When I wake it, it doesn't come back up.
I went into Device Manager and see the ms on the CM section report 8000+. One instance I hit stop, start and back to 8k. Last time I hit start and nothing would happen. I restart Aurora, no difference. I have to sometimes disconnect the Keyboard entirely, then when I plug it back in, it will let me hit start and then the lights start up again. 

### How often does this problem occur?

This problem occurs at least the last 3 times I've paid attention to it. 

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Wait for machine to sleep.
2. Wake it up.

### What is the version of Aurora you are experiencing this issue with?

My version is beta v0.6.3

### Does the previous version of Aurora have this issue?
Unknown.

### Please include any logs, screenshots, or files that are related to this issue:

Oddly I had no logs folder. Hitting Show logs directory gave me an error, so I just created this folder. Again, at work so might be some restrictions or policies in place causing some of these issues.

**Comment by Thelgow** [comment]
It just froze again, and not after my PC was asleep from what I can gather. Time/latency again was 8000. I tried to reconnect keyboard and that didnt do it until aurora was restarted. Which also didnt show in the system tray and was in task manager, so I had to end process there, then launch it again. Then when I hit Start, the colors began to process again.
I forgot I also have a Razer trinity and that appears to still be flickering the colors as opposed to the keyboard.

**Comment by mschol** [comment]
hi,
Got the same issue here;
using version 0.6.3, a logitech G910 and a Corsair K95 RGB Platinum
Everything works until sleep, after sleep the keyboard stays "off" (as setup in iCue).
in settings -> device manager Corsair is stopped apparently, hitting start (or restarting the program) works to get it working again until next sleep.

Using windows 10 x64 pro build 1709

**Comment by simon-wh** [comment]
Appears to be related to #1301

**Comment by simon-wh** [comment]
Hey, could anyone experiencing this issue try [this build](https://ci.appveyor.com/project/antonpup/aurora/builds/21812338/artifacts) from the above commit. I've tested waking from sleep with & without auto-login and using Corsair, Cooler Master and Wooting. Works perfectly for Corsair and Wooting, but my CM MK750 didn't want to play nice with the sdk after waking up each time, so with CM ymmv.

**Comment by mschol** [comment]
Installed it and for me now it seems to be working: the lights on my corsair K95 light up when waking up from sleep, not using auto login.

**Comment by charmarkk** [comment]
Late to the party @simon-wh but it's working fine and stable with Logitech G810. Thanks for the work!

**Comment by gradius-v** [comment]
My G910 still happily stops working every time

**Comment by schwizzled** [comment]
This happens to both my G910 and my G815.  Every time the computer goes to sleep and comes out of it, I have to kill Aurora and restart.  This didn't use to happen, but I'm not sure if it is a problem with GHUB or Aurora.....

**Comment by RaulMarq** [comment]
I'm having the same issue on my G403, it stops working whenever my PC comes out of sleep mode. Looking at the device manager, it seems like the Logitech service gets stopped, for some reason, and it can't be restarted until I close and re-open Aurora.

**Comment by ThePizzaMuncher** [comment]
I’m still experiencing this on the latest version of Aurora, with a Corsair K95 RGB Platinum. iCUE seems to address it just fine, but while I can stop and start the service in Aurora to my heart’s content, it doesn’t seem to have any bearing on the device; sometimes when I set it to request full control it’ll turn the lights off instead of controlling them like how I’ve set them up.

**Comment by Aytackydln** [comment]
This bug is resolved in this repository:
https://github.com/Aurora-RGB/Aurora

Issue still persists on logitech sdk tho
