### ISSUE TITLE
Logitech G903 mice and powerplay mousepad

### ISSUE THREAD

**Issue by Karandras82** [antonpup/Aurora#1363]
Is it possible to get support for the new G903 mice from logitech. And for the powerplay mouspad. Has also a RGB LED.

https://www.logitechg.com/en-us/products/gaming-mouse-pads/powerplay-wireless-charging.html

https://www.logitechg.com/en-us/products/gaming-mice/g903-wireless-gaming-mouse.html

Thanks!

**Comment by Gurjot95** [comment]
Do you own both these devices? You can help in testing it.

**Comment by gobba** [comment]
I do and can help.

In devices and wrappers I set the mouse to g900 and it seems to work, with the powermat as well. The desktop ripple effect continues to the powermat and mouse.

**Comment by kathampy** [comment]
The PowerPlay mouse pad is not in sync with the mouse and keyboard when using Rainbow.
