### ISSUE TITLE
Dota 2 Profile not detecting heroes

### ISSUE THREAD

**Issue by sydeffekt** [antonpup/Aurora#1367]
I'm not sure if this has something to do with the latest update? I've demoed Zeus and spammed his spells but the lighting doesn't react. Its got an orange for the health and mana bars and white for the rest of the keys. If I return to the main menu, i get the default blue/green/white profile. If i alt tab while demoing a hero, the keys go blank (no lighting).

### Expected behavior:
The profile should detect the hero I'm playing and load the health and mana bars as it used to. It should also react to certain spells that I'm using like Zeus' lightning.

### Actual behavior:
The profile loads up the default layer on startup of the game and after loading into a match, it loads up and orange and white profile no matter what hero is chosen. No reaction from the lighting when spells are cast.

### How often does this problem occur?
This problem occurs everytime

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Start dota 2
2. Either find a match or
3. Click the heroes tab and select a hero -> demo hero

### What is the version of Aurora you are experiencing this issue with?
My version is v0.6.3

### Does the previous version of Aurora have this issue?
Not sure, but v0.6.3 was working fine until the frostivus patch on the 19/12/2018

### Please include any logs, screenshots, or files that are related to this issue:
[2018-12-21 11.45.57.txt](https://github.com/antonpup/Aurora/files/2702381/2018-12-21.11.45.57.txt)

**Comment by diogotr7** [comment]
This happens due to the game sending extra "seasonal" abilities aurora does not handle. I'm not sure how to fix this because I don't know if these seasonal abilities will stay or will be removed until next year (I don't play the game). Also different heroes having different number of abilities does not help.

**Comment by sydeffekt** [comment]
> This happens due to the game sending extra "seasonal" abilities aurora does not handle. I'm not sure how to fix this because I don't know if these seasonal abilities will stay or will be removed until next year (I don't play the game). Also different heroes having different number of abilities does not help.

Thanks for the reply! I'm sure they will remove the seasonal stuff in the next few weeks. hopefully its all back to normal after that.

**Comment by diogotr7** [comment]
@mihanemail  https://ci.appveyor.com/project/antonpup/aurora/builds/21409271/artifacts

**Comment by mihanemail** [comment]
@diogotr7 i already have the  aurora app and i copied this file in layer folder in dota 2 profile but nothing will change

**Comment by diogotr7** [comment]
You need the different Aurora build i linked. This cannot be fixed with profiles or layers.

**Comment by mihanemail** [comment]
@diogotr7 oh ty so much.solved <3 and 1 more question can i use this layers ??
https://github.com/antonpup/Aurora/tree/master/Project-Aurora/Project-Aurora/Profiles/Dota%202

or i dont need any of this and the program will use this files automaticly ?

**Comment by diogotr7** [comment]
You linked the source code. You don't need any of it to use aurora.

**Comment by mihanemail** [comment]
diogotr7 tnx a lot for the replays <3
