### ISSUE TITLE
Can they make it so amazon alexa can display the colored light if possible

### ISSUE THREAD

**Issue by CosmicTDW** [antonpup/Aurora#1368]
### How often does this problem occur?

This problem occurs... (Fill in here)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. 
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (Fill in here)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

**Comment by simon-wh** [comment]
I don't think this is possible
