### ISSUE TITLE
Support for Acer PredatorSense RGB keyboards. (laptop)

### ISSUE THREAD

**Issue by LatavernediRi** [antonpup/Aurora#1369]
Greetings !

Will the Acer laptop Keyboards be supported in the future ? I mean those who are powered by PredatorSense.
I Own an _Acer Predator 15 G9-593-77VQ_ and am willing to provide informations about my hardware and software, if it is useful and can help.

- [Acer Predator 15 G9-593](https://www.acer.com/ac/en/SG/content/predator-model/NH.Q1ZSG.001)
- [predatorSense Software](https://au.answers.acer.com/app/answers/detail/a_id/41886/~/predatorsense-software)

I wish you all a happy holiday season.

**Comment by Gurjot95** [comment]
1. Does it support zone lightning or per key RGB? (I think it's zone)
2. Do they have SDK for their RGB? which is important for us to integrate support for Aurora.

**Comment by LatavernediRi** [comment]
You're right, it has 4 colorful zones that can be configured independently. 
However, I did not find any information about the SDK, either official or within the Internet communities.
It is either a lack of competence/knowledge on my part or just bad news.

**Comment by Gurjot95** [comment]
From what I know, I would go with bad news. Best bet would be to try to communicate with them and see if SDK is in works.

**Comment by simon-wh** [comment]
Closing for now

**Comment by JafarAkhondali** [comment]
I know it's closed, but I hope this helps future users:
https://github.com/JafarAkhondali/acer-predator-turbo-and-rgb-keyboard-linux-module
