### ISSUE TITLE
Left 4 Dead 2 Support

### ISSUE THREAD

**Issue by antonpup** [antonpup/Aurora#137]
Through wrapping the LgLCDAPI, Aurora can get access to some L4D2 information without GSI.

![lcdscreen_0903_095726](https://cloud.githubusercontent.com/assets/3421963/18226366/e5c7c972-71bc-11e6-8c79-16319cac9a0e.png)
![lcdscreen_0903_095737](https://cloud.githubusercontent.com/assets/3421963/18226367/e662d1b0-71bc-11e6-87ef-7ba311d8d59b.png)
![lcdscreen_0903_095744](https://cloud.githubusercontent.com/assets/3421963/18226368/e7361ac0-71bc-11e6-9915-7d33c838d8c8.png)

**Comment by brainbug89** [comment]
> LgLCDAPI
So all these games could be possible added: https://en.wikipedia.org/wiki/Logitech_G19#Game_and_application_support when manual map this information to key lighting?

**Comment by antonpup** [comment]
It should be possible, yeah. If those games give user any valuable information, like HP or ammo, then I can use that. I also notice that your list has a few already supported games, which means that I will either switch to lglcdapi wrapper or continue using existing wrappers for those games.

**Comment by antonpup** [comment]
This cannot be accomplished in an elegant way, look at close reason of #120.
