### ISSUE TITLE
[Bug] Script layers don't behave correctly

### ISSUE THREAD

**Issue by snappyapple632** [antonpup/Aurora#1371]
### Expected behavior:
A new script layer should be independent of any other layer.

### Actual behavior:
Creating a second script layer after creating the first script layer will reflect the assigned key of the first. If you change the assigned key(s) on the second layer, those changes will be reflected onto the first, and vice versa, when it shouldn't be.

### How often does this problem occur?
The problem occurs every time Aurora is started up.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Start Aurora
2. Create a script layer and assign a key.
3. Create a second script layer. The assigned key of the first script layer should be reflected onto the second instead of the default keys.

### What is the version of Aurora you are experiencing this issue with?
beta v0.6.3 

### Does the previous version of Aurora have this issue?
N/A

**Comment by simon-wh** [comment]
I've fixed it with the above commit, [here is the build with the fix](https://ci.appveyor.com/project/antonpup/aurora/builds/21813187/artifacts). Thanks for reporting this!
