### ISSUE TITLE
CS GO Api

### ISSUE THREAD

**Issue by andreas-git** [antonpup/Aurora#1374]
Hallo,

sorry for Posting this as an Issue, but have not found a better Place for.
Im searching for Information how to get Game events to External App, because im trying to get the same Features under Linux, with something Like this https://github.com/MatMoul/g810-led .
Can you give few Hints where i can start to understand how you grab from Games, for Example the Placed Bomb in CS.GO.

Best Regards
Andreas

**Comment by diogotr7** [comment]
This page has some useful information for csgo: https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Game_State_Integration.

Dota 2 works in a similar way.
