### ISSUE TITLE
Add lighting support for the Corsair logo on newer keyboards

### ISSUE THREAD

**Issue by iCeCoCaCoLa64** [antonpup/Aurora#1375]
Newer Corsair keyboards, such as the K70 Mk2 and K95 Platinum, have an RGB logo at the top. Aurora doesn't seem to recognize this, and lighting for the logo is disabled.

It's a very small thing, but it seems like a waste to have an RGB logo and not be able to utilize it. Please add lighting support for this in the next Aurora update.

**K70 Mk1 (no RGB logo):**
![K70 Mk1](https://user-images.githubusercontent.com/25655781/50543556-89c0c000-0ba9-11e9-8ce5-9617ad0f1203.jpg)

**K70 Mk2 (w/ RGB logo):**
![K70 Mk2](https://user-images.githubusercontent.com/25655781/50543557-8b8a8380-0ba9-11e9-969f-ce795eaf9bdd.jpg)

**Comment by Gurjot95** [comment]
I have same keyboard. Logo is not yet supported by the SDK unfortunately.
