### ISSUE TITLE
Add support for Razer Goliathus Extended Chroma

### ISSUE THREAD

**Issue by sayig18** [antonpup/Aurora#1377]
https://www.razer.com/gaming-mouse-mats/razer-goliathus-chroma

Would be great if it had the same type of support the RGB Corsair mouse pad has. It only has 1 lighting zone so only simple animations would work but that's fine imo.

**Comment by diogotr7** [comment]
It should follow the mouse color in the current version. More device types are planned for the next versions.

**Comment by Gurjot95** [comment]
Correct me if I am wrong but I don't think Goliathus is supported by SDK?

**Comment by sayig18** [comment]
> It should follow the mouse color in the current version. More device types are planned for the next versions.

So far it doesn't do anything. I'm using a g903 if that helps and I have it set to blue. The pad just does not sync

**Comment by sayig18** [comment]
> Correct me if I am wrong but I don't think Goliathus is supported by SDK?

In synapse, I have the aurora app enabled. Still does not do anything. Not sure if supported by SDK

**Comment by diogotr7** [comment]
Do you have any other working Razer hardware?

**Comment by sayig18** [comment]
> Do you have any other working Razer hardware?

No sadly, I only have other corsair products

**Comment by sayig18** [comment]
I cant get the mousepad to respond to aurora at all. Not even static colors

**Comment by simon-wh** [comment]
Doesn't appear to be supported by the SDK so there doesn't seem to be much we can do

**Comment by Gurjot95** [comment]
It should be working now with latest update.

**Comment by sayig18** [comment]
New update works great. Thank you
