### ISSUE TITLE
The backlight of the case of Asus Aura as on the video.

### ISSUE THREAD

**Issue by HDGluk** [antonpup/Aurora#1379]
Hello. I wanted to know. I have an Asus Aura backlight in my computer case. I downloaded the latest version of the Aurora program, but I didn’t find how to enable Asus Aura support in it so that the backlight of the case works like a video. Tell me please.

https://www.youtube.com/watch?v=x-y0u19HmKI

**Comment by diogotr7** [comment]
The support is still experimental. You can use the version in development if you ask in the discord [here](https://discord.gg/YAuBmg9).
