### ISSUE TITLE
Feature request: keyboard program switching

### ISSUE THREAD

**Issue by TrikkyPlayz** [antonpup/Aurora#1382]
So I have some profile folders in icue that are used in certain games e.g rainbow six siege however i cannot replicate these in aurora. The problem is that i like the CS:GO profile and the GTA V profile in aurora along with the desktop one but i cant use them at the same time as the rainbow six one without exiting aurora. My suggestion is that aurora uses its own profiles for specified games but for other specified games it switches to using icue.

**Comment by diogotr7** [comment]
You can use the "exclude" feature in the settings. That causes Aurora to drop control of the keyboard if an excluded application is in the foreground iirc.

**Comment by TrikkyPlayz** [comment]
ok thanks for that, i only just got into the program.
