### ISSUE TITLE
Added Prismatik Lightpack support

### ISSUE THREAD

**Issue by Rumon** [antonpup/Aurora#1384]
Hi,

I have made a device for Aurora to support Prismatik Lichtpack An Ambilight Device.
I did not know how to fork it but I wanted to Share it 

Here is the lik to the CS in one drive for more updated version in the future
https://1drv.ms/u/s!AiVqVnWrLobRhZJOuS-VaVaksar4Vg
I also attached the file

Installation:
- Make a folders if it does not exist:
 aurorainInstallDir
[Prismatik.zip](https://github.com/antonpup/Aurora/files/2730597/Prismatik.zip)
\Scripts\Devices\
 Example c:\program files(x86)\Aurora\Scripts\Devices\
- copy Prismatik.cs in the folder
  or Unzip Prismatik.cs in the folder
- Restart Aurora
- Device will set al lets to color value 1
- If it pops up in devices and is connected it should work
- Keyboard keys F1-F10 are mapped to Led number 1-10

Device Settings:
- Install Prismatik (unofficial fork) 5.11.2.17  (https://github.com/psieg/Lightpack)
- Device / Software settings:
 Enable Experimental mode and then go to TAB Experimental and enable the api server 
 check for port 3636
 Leave API key Empty (Not used yes)

Aurora Game Profiles settings:
- Open a game Profile (Dota)
 Go in to Layers
 Select Health
 Set to Percentage (Gradiant Effect Layer..)
 set current value to hero Health
 set max to here/maxheath
 Effectype to All at once
 Map Keys F1 till F10
 Test the effect in preview

Info about the lightpack https://github.com/woodenshark/Lightpack
Tested with Prismatik (unofficial fork) 5.11.2.17  (https://github.com/psieg/Lightpack)

Kind Regards
Rumon lagendijk

**Comment by Rumon** [comment]
Use the onedrive version, I was spamming the log, https://1drv.ms/u/s!AiVqVnWrLobRhZJOuS-VaVaksar4Vg

**Comment by Gurjot95** [comment]
Hey, can you make a PR instead since its not an issue?
