### ISSUE TITLE
League of Legends Color zones aren't working

### ISSUE THREAD

**Issue by nickeeey** [antonpup/Aurora#139]
Hello,
my overwatch layout is good so far ( but i don't know why my Keyboard light up all unused  Buttons orange). Unfortunatly my lol setup is working until i click play game at the lol launcher. Ingame my keyboard isn't showing my custom color zones. Do you have a solution? I use a g910

**Comment by antonpup** [comment]
I'll look into it. I think it's an issue with the recently changed program detection method.
