### ISSUE TITLE
Ducky Shine 7 support?

### ISSUE THREAD

**Issue by ocp15k** [antonpup/Aurora#1391]
Newly released Ducky Shine 7 has Razer Chroma compatibility. The keyboard is detected in the razer synapse program. Ducky has also released a new version of their own RGB software too. Any chance of taking a look at it?

**Comment by JKinch** [comment]
+1. about to buy a shine 7 and would love to have Aurora Support

**Comment by lawlcrackers** [comment]
I would very much like to see this happen.

**Comment by thingamajig0** [comment]
https://ci.appveyor.com/project/antonpup/aurora/builds/30612391/artifacts
Here is a current dev build with Support for Ducky Shine 7. This build is a bleeding-edge build so expect some odd bugs.

**Comment by diogotr7** [comment]
Added with #1892
