### ISSUE TITLE
Aurora doesn't wok with my Steelseries Apex m 750 keyboard.

### ISSUE THREAD

**Issue by koksajz** [antonpup/Aurora#1393]
I am having issues with Aurora. It doesn't show any of it's lighting when I play dota. Can someone help me pls. I think I did everything according the the instructions.

![2](https://user-images.githubusercontent.com/46627101/51074493-2db56b80-1680-11e9-838b-17512ea1283d.jpg)
![3](https://user-images.githubusercontent.com/46627101/51074494-2e4e0200-1680-11e9-8873-9eef5eab8782.jpg)
![4](https://user-images.githubusercontent.com/46627101/51074495-2e4e0200-1680-11e9-955b-63bc3aa249d4.jpg)
![5](https://user-images.githubusercontent.com/46627101/51074496-2e4e0200-1680-11e9-8e70-94aeb6be2575.jpg)
![bez nazvu](https://user-images.githubusercontent.com/46627101/51074497-2e4e0200-1680-11e9-8932-39c63a18f73c.jpg)

**Comment by koksajz** [comment]
Now Aurora works but when I load the game it doesn't show any of the effect that are happening in the game and after like 30 seconds in changes back to my ussual steelseries windows effects.

**Comment by simon-wh** [comment]
@koksajz Could you post your log file?

**Comment by simon-wh** [comment]
Hm, those log files show no issues, but I would assume to large files contain lots of errors which could give more insight on the issue you're having. Could you open them with Notepad++ or something and find some of the errors in there and post them?

Also, is Steelseries showing up as connected in Device Manager? If so, is Aurora showing up in SSE3?

**Comment by koksajz** [comment]
Sure Steelseries is connected and I don't understand what do you mean by SSE3, sorry.
Here I copied one of the errors, hope it helps. Thank you.

Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Aurora.Profiles.Dota_2.Layers.Dota2AbilityLayerHandler.Render(IGameState state) in C:\projects\aurora\Project-Aurora\Project-Aurora\Profiles\Dota 2\Layers\Dota2AbilityLayerHandler.cs:line 63
   at Aurora.Settings.Layers.Layer.Render(IGameState gs) in C:\projects\aurora\Project-Aurora\Project-Aurora\Settings\Layers\Layer.cs:line 281
   at Aurora.Profiles.GameEvent_Generic.UpdateLights(EffectFrame frame) in C:\projects\aurora\Project-Aurora\Project-Aurora\Profiles\Generic\GameEvent_Generic.cs:line 31
   at Aurora.Profiles.LightingStateManager.Update() in C:\projects\aurora\Project-Aurora\Project-Aurora\Profiles\LightingStateManager.cs:line 588
   at Aurora.Profiles.LightingStateManager.<InitUpdate>b__74_0(Object g) in C:\projects\aurora\Project-Aurora\Project-Aurora\Profiles\LightingStateManager.cs:line 494
[ERROR] 17:34:56: ProfilesManager.Update() Exception, System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

**Comment by simon-wh** [comment]
@koksajz Ohhhh, I see, so desktop effects are working fine then? Is it only Dota that has the issue or do you experience it with any other games?

**Comment by koksajz** [comment]
No it doesn't work even with cs.go. At fisrst the keyboard lighting is as in aurora (ingame mode) but after like 15 second in the game it changes to my regular SS settings. When I switch back to windows it sets my keyboard back to aurora windows settings. But even during the 15 seconds in game, it doesn't show any gaming sense.

**Comment by simon-wh** [comment]
Hmm, it sounds like SS is overwriting Aurora's lighting. From the screenshot it looks like you have all the games disabled, does it return to stock SS lighting or lighting specific for the game? Once it stops working in game is Aurora still running? and what does it say in Device Manager in that case?

**Comment by koksajz** [comment]
It returns to the SS lighting which I selected for windows. Aurora still runs, but the device manager doesn't show any changes.

**Comment by koksajz** [comment]
[2019-01-22 20.27.31.log](https://github.com/antonpup/Aurora/files/2784304/2019-01-22.20.27.31.log)
This should be it.

**Comment by simon-wh** [comment]
@koksajz I've been told that the errors you're getting have been fixed in the dev branch, could you try out [this build](https://ci.appveyor.com/project/antonpup/aurora/builds/21812338) and let me know if it helps?

**Comment by koksajz** [comment]
How should I use it?

**Comment by koksajz** [comment]
It looks to be working fine, only tested for 2 minutes but the gaming sense
is working. Thank you very much for your time.

ut 22. 1. 2019 o 23:27 Simon W <notifications@github.com> napísal(a):

**Comment by simon-wh** [comment]
@koksajz Glad it's sorted!
