### ISSUE TITLE
aurora not taking over from LGS

### ISSUE THREAD

**Issue by numinis** [antonpup/Aurora#140]
it was working yesterday but after a reboot, things just stopped. it keeps the lighting effect lgs is assigning to the keyboard.

g910, both redist installed and running as admin

http://pastebin.com/2JkUPEC9

**Comment by vydax** [comment]
i have the same problem here but mine whas being weird yesterday aswell it just like disabled kind of it was working half like one colour only the one i set originally in lgs before using thisand then certain effects didnt work anymore, and now its not taking over either.

**Comment by vydax** [comment]
oh i just found something out if u go to general options then enable ALT+volume and use it it started working for me :/

**Comment by vydax** [comment]
for the global lightning

**Comment by numinis** [comment]
i am an idiot. it appears that my logitech updated itself or something like that, it disabeled the allow games to control ilumination setting.
