### ISSUE TITLE
Masterkeys pro M numpad does not light with numlock off

### ISSUE THREAD

**Issue by Oldcustard** [antonpup/Aurora#1401]
### Expected behavior:

With numlock off, the numpad keys should still respond to keypresses with lighting effects.

### Actual behavior:

The keys do not respond lighting effects with numlock turned off.

### How often does this problem occur?

This problem occurs all the time.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Set up an interactive effect.
2. Turn numlock off
3. Press numpad keys 

### What is the version of Aurora you are experiencing this issue with?

My version is beta v0.6.3-537

### Does the previous version of Aurora have this issue?
The previous version, v0.6.3 had this issue.

### Please include any logs, screenshots, or files that are related to this issue:

https://pastebin.com/tsvS2nTh

**Comment by Oldcustard** [comment]
I just tested the above and yes, the normal middle block of keys light up in aurora.

**Comment by simon-wh** [comment]
Okay, I think I may be able to pull up a hacky fix for your problem

**Comment by simon-wh** [comment]
@Oldcustard Could you tell me exactly all the keys that this happens to and which keys they end up being?

**Comment by Oldcustard** [comment]
Seems to have fixed mopst of the keys. 1 and 3 still do not light, I suppose since they do not have a function when numlock is off. One possibly related issue is that when numlock is ON, presses of the 00 key light up the 0 key instead.

**Comment by Oldcustard** [comment]
It probably does just send two presses of 0. Thanks for your help 👍
