### ISSUE TITLE
Game Support World of Tanks with CoreEngine

### ISSUE THREAD

**Issue by jigglyDiggly** [antonpup/Aurora#1402]
Profile request for Razer Chroma 

(I#m using Razer Chroma Ornata keyboard in combination with Roccat Kone Aimo. Is it possible to combine those two for effects?)
### Expected behavior:
-show health bar(F1-F12)
-highlight 1-3 for Ammo-types
-highlight 4-6 for Consumables
-highlight F5 and F7 for "OKAY" and "HELP"
-highlight 'X' and 'G' for "switching fire mode"
-highlight 'C' for "Reload Clip"
-highlight 'SPACE' for "Hand brake"
-flash/off/flash/off... num-keys when gun is ready to fire
  or maybe turn off mouse while reloading and light it up when gun is ready to fire

**Comment by simon-wh** [comment]
Duplicate of #210
