### ISSUE TITLE
Device won't start

### ISSUE THREAD

**Issue by vicdilou** [antonpup/Aurora#1407]
### Actual behavior:

I can't start the device in the device manager

### How often does this problem occur?

This problem occurs everytime since I install the update 0.6.3-532-cnttkfsy

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Try to start anything in the device manager

### What is the version of Aurora you are experiencing this issue with?

My version is 0.6.3-547

### Does the previous version of Aurora have this issue?
The previous version, 0.6.3-532-cnttkfsy, did have this issue. And if I downgrade I still have the issue.

### Please include any logs, screenshots, or files that are related to this issue:

I don't have logs, the folder is empty

**Comment by simon-wh** [comment]
You're going to have logs. Either go to Settings -> Debug -> Show Logs Folder or %appdata%/Aurora/Logs to find them

**Comment by vicdilou** [comment]
It's the latest logs
[2019-01-24 12.34.59.log](https://github.com/antonpup/Aurora/files/2791882/2019-01-24.12.34.59.log)

**Comment by simon-wh** [comment]
Have you got GHub installed? If so you need to get the GHub version of Aurora, if you've got LGS ensure you download the main build from [here](https://github.com/antonpup/Aurora/releases/tag/v0.6.3)

**Comment by vicdilou** [comment]
I don't have GHub. And I have the same issue with the version in your link

**Comment by vicdilou** [comment]
I try with the 0.6.4 and it doesn't work too @simon-wh
