### ISSUE TITLE
Drevo Blademaster "y" key not lighting up (iso layout)

### ISSUE THREAD

**Issue by Taloslx** [antonpup/Aurora#1411]
### Expected behavior:
all lights should be on

### Actual behavior:
all the lights except 'Y'  turn on

### How often does this problem occur?
Every time
### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. have blademaster plugged in
2. open up aurora 
3. 

### What is the version of Aurora you are experiencing this issue with?
My version is... (beta v0.6.3-552)

### Does the previous version of Aurora have this issue?
The previous version did not have support for this keyboard

### Please include any logs, screenshots, or files that are related to this issue:

Log: https://pastebin.com/6XDpsJHF
Screenshots: https://imgur.com/a/6aojYDg

**Comment by diogotr7** [comment]
@meng0609 any idea why this would happen? Another user reported the same in our Discord.

**Comment by Taloslx** [comment]
When trying to light up the "y" key the "t" key is lit up
and when trying to light up the "t" key none of the keys are lit up

**Comment by Taloslx** [comment]
Also, when using drevo power console and lighting up "y" and "t" keys the lights match to their corresponding key

**Comment by meng0609** [comment]
Updated DrevoRadi.dll, fix for Drevo Blademaster "y" key not lighting up @Taloslx

**Comment by instantlemming** [comment]
Version 0.6.4b fixed the 'y' key, but the backspace/pipe key (above the enter and below the backspace) does not light up at all.

**Comment by meng0609** [comment]
@instantlemming What is the layout of your keyboard?

**Comment by meng0609** [comment]
@instantlemming General Settings -> Devices & Wrappers -> Preferred Keyboard Layout

**Comment by instantlemming** [comment]
> 
> 
> @instantlemming General Settings -> Devices & Wrappers -> Preferred Keyboard Layout

I had it on 'automatic detection', changing it to 'United states' fixed it. (and changed the keyboard preview image to match my keyboard).
Sorry to have bothered you.

**Comment by diogotr7** [comment]
Glad this is fixed now.
