### ISSUE TITLE
Corsair K68 is not working!

### ISSUE THREAD

**Issue by Kalbi1** [antonpup/Aurora#1418]
### Expected behavior:
Corsair K68 is not working!

### Actual behavior:
With the newest update, the Corsair K68 is not working (no light)

### How often does this problem occur?

This problem occurs... (everytime)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. connect keyboard 
2. lightning does not work
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (0.6.4)

### Does the previous version of Aurora have this issue?
The previous version, (0.6.3), did not have this issue.

**Comment by simon-wh** [comment]
I believe this has been fixed in some of the latest dev changes which will soon be released as v0.6.4b. Could you try [this build](https://ci.appveyor.com/project/antonpup/aurora/builds/21976016/artifacts) please?

**Comment by Kalbi1** [comment]
I reported this problem for my friend! I will tell him that he has to try this new Version :).
