### ISSUE TITLE
Overwatch Lighting Effects not working on Corsair K70 RGB

### ISSUE THREAD

**Issue by kinecty** [antonpup/Aurora#142]
So I downloaded Aurora and it works great for Payday 2 and Battlefield 3 but when you click on the Overwatch settings tab there is no lighting effects and no way to add any. I tried patching Overwatch even  though I do not have a Razer keyboard and still nothing.
![snapshot](https://cloud.githubusercontent.com/assets/18298946/18492020/3497c878-79d7-11e6-9b70-8964a9e315d1.JPG)

**Comment by brainbug89** [comment]
There are no Overwatch settings for lighting effects because Overwatch controlls the lighting effects itself.

**Comment by kinecty** [comment]
Okay but it doesn't work my keyboard is just black when i play the game

**Comment by antonpup** [comment]
Try running game as admin.

**Comment by kinecty** [comment]
I have but still nothing :/

**Comment by brainbug89** [comment]
Did you successfully patched Overwatch? Check if the new RzChromaSDK.dll and RzChromaSDK64.dll at Overwatch directory are existing.

**Comment by kinecty** [comment]
As far as I know it successfully patched yes, and those files are in my Overwatch directory

**Comment by antonpup** [comment]
What is your OS? Try restarting Aurora as administrator. I don't have access to Overwatch right now to test.

**Comment by kinecty** [comment]
I have Windows 10 64x, I already tried restarting Aurora a few times using administrator and I've tried re-downloading it to no avail

**Comment by Xantha123** [comment]
Hi, i have the K70 RGB Rapidfire and no issues with Overwatch after patching the files. Running Win10 x64

**Comment by sym5** [comment]
Hi, just started using aurora, been working great with overwatch until today, now I have the same problem as o/p only I'm using a g910, tried running as admin & re-patching no go , as soon as I run the game my keyboard lights go out, strange how it was working fine, any suggestions? I'm on win 10 x64

**Comment by antonpup** [comment]
@sym5 I actually do not know why this is happening. Have you tried restarting your computer? I would try removing the two wrapper files from Overwatch directory, restarting PC, repatching Aurora.

**Comment by sym5** [comment]
Will try today, when you say patch aurora how exactly? Don't you mean patch Logitech gaming software with aurora? Thanks...

**Comment by sym5** [comment]
@antonpup, problem solved for me , I had a while ago copied my overwatch installation to another ssd, updated the path in battlenet so the game ran off of my other ssd, so I patched the directory on the ssd. For some reason battlenet had put the path of the game installation to my old drive which of course wasn't patched so the lighting wasn't working...Now it is thankyou so much for this great piece of software, why cant Logitech produce this in their drivers, Well done and many thanks.

**Comment by brainbug89** [comment]
> why cant Logitech produce this in their drivers, Well done and many thanks.

Because the devs of Overwatch have an agreement with Razer for the lighting effects. The game devs need to built in support for RGB keyboards into their games. The keyboard manufacturers can only ask for it.

**Comment by sym5** [comment]
Yes I understand that, however this aurora software allows you to control your lighting effects in everyway possible ,unlike the Logitech gaming software. The aurora makes the g910 keyboard worth owning now...

**Comment by brainbug89** [comment]
Yes because Aurora is "routing" the lighting effects from Razer, Alienware, ... to Logitech. Logitech couldn't  do that without getting trouble with Razer. We need more game devs to generic support RGB keyboards like Valve is doing with CS:GO and Dota2 ;-)
