### ISSUE TITLE
Drevo Blademaster RGB light side bars. Is there any way to turn them on?

### ISSUE THREAD

**Issue by marcktorius** [antonpup/Aurora#1423]
### Expected behavior:
The four-side RGB light bars of the keyboard should work.

### Actual behavior:
The four-side RGB light bars of the keyboard don't work (they remain off).  

### How often does this problem occur?
Every time.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Keyboard connected
2. Aurora opened (instead of Drevo Power Console)

### What is the version of Aurora you are experiencing this issue with?

My version is... (beta v0.6.4).

### Does the previous version of Aurora have this issue?
The previous version did not have support for this keyboard.

**Comment by meng0609** [comment]
Currently, Aurora does not support the Drevo Blademaster RGB light side bars, which will be developed in the future. @marcktorius

**Comment by marcktorius** [comment]
Ok, thanks!

**Comment by sephrat** [comment]
Any ETA on this feature? Does it take time because the Drevo SDK is tricky to implement or is it about Aurora not having a concept of a side bar implemented?
As a workaround, isn't there a way to let Drevo software handle the side bars rather than having Aurora turn them off?
