### ISSUE TITLE
Rocket League Profile Help Needed

### ISSUE THREAD

**Issue by Staibdude** [antonpup/Aurora#143]
Hello, I'm new to using this program. I love how it works for Overwatch! It's beautiful!

I'm having issues with the overlay for Rocket League, though. I know there was a Rocket League patch just released yesterday (0.5.1a), which I have downloaded, but I am having this issue anyway.
For starters, I'm using a G810 Orion, so that may be a root cause right there. But when I start my computer and first use Aurora, the Rocket League preview works totally fine (the boost meter fills and the keyboard splits for the scores). However, when I start up Rocket League, the keyboard goes blue and only stays blue while I am in the Rocket League game.

Another issue that I've found is that whenever I play a game that has Aurora enabled on it, but I change programs or minimize the game, my keyboard SHOULD revert back to its standard colors that I gave it through the Logitech Gaming app. Instead, my keyboard displays no lights, and I need to manually open the Logitech Gaming app for the lights to come back on. Does anyone have any suggestions for this?

Thanks! I would submit a log, but I am not sure where to find it.

**Comment by antonpup** [comment]
:)

Regarding Rocket League, It's not updated. It's using memory reading, which requires me to update aurora everytime Rocket League releases an update. So I decided not to keep working on Aurora overall than keep chasing every RL update.

Regarding the second issue, I am not exactly sure what is causing the issue. Could you provide me with a more detailed example so I could attempt to reproduce it on my end?

**Comment by brainbug89** [comment]
Second issue:
> but I change programs or minimize the game, my keyboard SHOULD revert back to its standard colors that I gave it through the Logitech Gaming app

No it should change to the colors of the desktop mode of Aurora.


btw logs are inside of Aurora directory: \Aurora\logs
