### ISSUE TITLE
Add Italian keyboard layout.

### ISSUE THREAD

**Issue by Manfre98** [antonpup/Aurora#1431]
Hello, I created the Italian version of the keyboard, can someone add it with a PR?
I am still a beginner with git.
[layout.it.txt](https://github.com/antonpup/Aurora/files/2830425/layout.it.txt)

**Comment by diogotr7** [comment]
![image](https://user-images.githubusercontent.com/29486064/52456015-e5884c80-2b4a-11e9-8037-49c67eca5fdf.png)
Does this look right? @Manfre98

**Comment by Manfre98** [comment]
Yes, that is perfect
