### ISSUE TITLE
Aurora Crashing when patching Overwatch

### ISSUE THREAD

**Issue by ProfessoRJ13** [antonpup/Aurora#1436]
Hi all, every time I try to patch Overwatch Aurora crashes. Any help would be appreciated!

This problem occurs every time

My version is 0.6.4b

Here is the crash report.
![image](https://user-images.githubusercontent.com/47466126/52514078-ef04d800-2c62-11e9-9281-ad3a584e7769.png)

Thanks!

**Comment by diogotr7** [comment]
You need to close overwatch first to patch it. Regardless it looks like you've already patched it no?

**Comment by ProfessoRJ13** [comment]
I was trying it with overwatch open, I just did it with it closed and it successfully patched.
However, if it was already patched, it wasn't working. I will try to test it again (probs wont have time tonight) and let you know what happens.

Thanks for the response! I'm an idiot XD

**Comment by ProfessoRJ13** [comment]
Ok, so I have booted overwatch, and the aurora worked in the app but not on the keyboard (it froze). i restarted aurora and iCue and unplugged/replugged keyboard, and now they keyboard just goes black.
halp plz

**Comment by ProfessoRJ13** [comment]
To clarify, all other effects work, but when I alt tab into Overwatch, the keyboard/mouse/mousepad just goes black where it should have the in-game effects. When i alt tab out, the other effects come back.

**Comment by ProfessoRJ13** [comment]
Nervermind, it just started working...?
Thanks for the help!
