### ISSUE TITLE
Gta 5 White lights only

### ISSUE THREAD

**Issue by scott0702** [antonpup/Aurora#1443]
### How often does this problem occur?

This problem occurs... All the time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. open aurora
2.  select blackwidow x
3. patch gta5 

### What is the version of Aurora you are experiencing this issue with?

My version is... V0.6.4b

### Please include any logs, screenshots, or files that are related to this issue:

https://pastebin.com/y7jVYzuW

**Comment by Gurjot95** [comment]
White Color only in GTA V generally means Logitech Wrapper is not working as White Color is provided by Aurora as a background layer, not by wrapper. Please make sure you have installed Logitech wrapper patch.

**Comment by scott0702** [comment]
I have installed the patch and it still doesn't work

**Comment by karabin1000pl** [comment]
I have exactly the same problem

**Comment by MorkMikael** [comment]
same problem for open Logitech G HUB, and logitech g810.


    Start G hub
    open aurora
    select logitech g 810
    patch gta5
    
My version is... V0.6.4b

**Comment by SmittysSmellyAss** [comment]
Had the same issue, downloading Logitech Gaming Software https://support.logitech.com/en_us/software/lgs 
Fixed it for me

**Comment by scott0702** [comment]
Installed Logitech Gaming Software and now works fine
