### ISSUE TITLE
Pressing Alt Gr illuminates keys of Ctrl shortcuts

### ISSUE THREAD

**Issue by brainbug89** [antonpup/Aurora#145]
Pressing the Alt Gr (right Alt) key illuminates keys of the Ctrl shortcuts:
![aurora_altgr_shortcut_bug](https://cloud.githubusercontent.com/assets/21130949/18555116/e68764fe-7b66-11e6-8e8f-e42506c9352f.PNG)

Keyboard: K70 RGB Rapidfire (DE layout)

**Comment by simon-wh** [comment]
This is no longer an issue due to the Shortcut Assistant redesign and changes made in PR #693
