### ISSUE TITLE
MemoryReader crashes when trying to open handle on exited process

### ISSUE THREAD

**Issue by srodriguez1850** [antonpup/Aurora#1456]
In any GameEvent_[GAME].cs UpdateLights method, Process.GetProcessesByName(string) **can** return a process that has exited. Testing with Resident Evil 2:

`Process[] process_search = Process.GetProcessesByName("re2");`

Returns an array of one element with re2.exe, with the `HasExited` property set to true. Because the following lines usually are:

`if (process_search.Length != 0)`: returns true, and
`using (MemoryReader memread = new MemoryReader(process_search[0]))`: tries to open a handle on an exited process,

the MemoryReader constructor at MemoryReader.cs line 17 throws an unhandled exception and kills Aurora.

This can cause Aurora to crash in games that rely on memory reading.

**Comment by JoeyBallentine** [comment]
Already fixed in my clone hero & memory reader PR

**Comment by srodriguez1850** [comment]
So on more investigation this seems to be an edge case where the process list is not cleared after a particular process has exited, creating a duplicate where one is active and the other has exited. I haven't been able to replicate but it just might be a .NET quirk. Keep closed but refer to if this ever surfaces again.
