### ISSUE TITLE
Aurora doen't work

### ISSUE THREAD

**Issue by Rolekko** [antonpup/Aurora#1464]
### Actual behavior:
Aurora start but don't work

### How often does this problem occur?

Always

### What is the version of Aurora you are experiencing this issue with?

v0.6.4b

### Does the previous version of Aurora have this issue?
I have a problem similar to this: https://github.com/antonpup/Aurora/issues/1334

I have a logitech g910 and I have already tried to uninstall GHUB but nothing has changed

**Comment by diogotr7** [comment]
By similar to #1334 do you mean it doesnt start on boot but once you restart aurora it works fine? Perhaps it would be better to debug this in our discord here https://discord.gg/YAuBmg9

**Comment by Rolekko** [comment]
> By similar to #1334 do you mean it doesnt start on boot but once you restart aurora it works fine? Perhaps it would be better to debug this in our discord here https://discord.gg/YAuBmg9

tell me what I have to do exactly

**Comment by Rolekko** [comment]
I do not understand, now for some strange reason it works.
