### ISSUE TITLE
Game Support: Ark Survival Evolved

### ISSUE THREAD

**Issue by paul-hansen** [antonpup/Aurora#147]
### Possible features:
- Durability of items shown as brightness on respective number keys.
- Flash keys when extremely hot/cold/hungry/thirsty. Respective colors could be red/blue/green/light blue?
- Pulse the E key when something usable is in reach. Basically whenever "Press E to use/ride" is showing.
- Have certain keys/lights able to be assigned color based on the current temperature (Probably a red>yellow>blue gradient). The Logitech G logo would be perfect to assign this.

Will gift you the game on Steam if needed.

**Comment by antonpup** [comment]
I can look into it, a quick google search yields nothing useful. I will look around later, but I don't think there will be an "easy way" to have a working profile for this game. Maybe reading game logs? Could you provide a sample log file (if there is any) from a game session?

P.S. Thanks for the gift offer, but I would rather not take it unless I know that Aurora users can benefit from it. Maybe if the logs contain useful information.

**Comment by stbatuhan** [comment]
Can be a great and that game uses Unreal Enginer 4. Also full modding support it has.

**Comment by audenga** [comment]
+1, didnt feel like making a new post for the same game

**Comment by ersan** [comment]
The Logitech site advertises support for ARK - perhaps you can hook into that: http://gaming.logitech.com/en-us/microsite/rgb-illumination

**Comment by audenga** [comment]
thats the thing, ive spent ages trying to get that to work and its not working, also theres no absolutly help from logitech with getting it to help

**Comment by paul-hansen** [comment]
@audenga same thing here. Pretty sure Logitech flat out lied in their advertising about integration with Ark.

**Comment by antonpup** [comment]
Afaik there are several versions of Ark. One of which has RGB illumination support, while the current "main" one does not.

**Comment by paul-hansen** [comment]
Going through and cleaning up my open issues across github. I no longer have an individually addressable rgb keyboard that supports this type of integration. If anyone still wants Aurora to support Ark or has any information on what the next steps would be, it might be best to open a new issue.
