### ISSUE TITLE
Skyrim Support

### ISSUE THREAD

**Issue by Edi-Gaming** [antonpup/Aurora#1482]
Adding the skyrim games would be awesome Features i would like Heath, Stamina, Magika, Compass Direction And That is about it 
Thank you

**Comment by drhead** [comment]
This should be possible with an SKSE plugin.  All of the functions to get player actor values should be there. Compass direction could be derived from (the SKSE C++ function equivalent of) the in-game console command player.getangle(z).

**Comment by simon-wh** [comment]
Duplicate of #999
