### ISSUE TITLE
Fortnite not working with logitech/aurora

### ISSUE THREAD

**Issue by LeasyBenjamin** [antonpup/Aurora#1485]
### Expected behavior:

Fortnite's built in RGB profile should show up on my steelseries keyboard

### Actual behavior:
The keyboard is black.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. 
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (Fill in here)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:
https://pastebin.com/9eDkfPp2

So basically fortnite has it's own in game reactive SDK/Profile/Whatever which changes color based on emotes/storm/etc that works with Logitech and Razer peripherals only. Unfortunately I own a steelseries keyboard and an ROG mouse, but I got this program in hopes that it could mitigate this issue. I have linked steelseries engine to aurora, but im not sure how to get this fortnite thing to work. I went into the logitech gaming software and turned on the virtual keyboard, and everything was showing up there just fine. So, I tried making fortnite an app on aurora and making an aurora wrapper layer, then linking that with the Logitech software. So in a nutshell, I need Fortnite->Logitech->Aurora->Steelseries or ROG to be connected. Right now I'm struggling with Logitech->Aurora

**Comment by diogotr7** [comment]
You had the right idea. The problem, as far as we know, is that fortnite doesn't load Aurora's modified dll due to anti-cheat, so unfortunately there's nothing we can really do.

**Comment by LeasyBenjamin** [comment]
Big F in chat. Well I hope that fortnite adds support for more peripherals so I dont have to deal with this crap
