### ISSUE TITLE
issues with shortcut assistant (Layout issue)

### ISSUE THREAD

**Issue by gitmacer** [antonpup/Aurora#1489]
### Expected behavior:

Alt Gr should not trigger Alt shortcuts and the other way arround.
### Actual behavior:

Alt and Alt Gr triggers each other
### How often does this problem occur?

This problem occurs... (everytime)
### What is the version of Aurora you are experiencing this issue with?

My version is... (0.6.4b-630)

### Please include any logs, screenshots, or files that are related to this issue:

![shortcut layer Alt Gr bug + demo](https://user-images.githubusercontent.com/37345589/68506573-378d0880-026a-11ea-8c3a-de60ac24ff9b.gif)

**Comment by diogotr7** [comment]
Fixed with #1882
