### ISSUE TITLE
Wooting Two support

### ISSUE THREAD

**Issue by volkete** [antonpup/Aurora#1491]
### Expected behavior:

Aurora should be able to manage Wooting two RGB lightning. 

### Actual behavior:

The device can't be activated on device manager . 

### How often does this problem occur?

This problem occurs... every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Plug and install a Wooting Two keyboard
2. Open Aurora
3. Go to Device Manager
4. Try to start the Wooting device

### What is the version of Aurora you are experiencing this issue with?

My version is... 0.6.4b

### Does the previous version of Aurora have this issue?
First version I try

### Please include any logs, screenshots, or files that are related to this issue:
https://pastebin.com/Cqi1M3Ay
https://pastebin.com/L6i7iiQX
https://imgur.com/a/TKqsuwV

**Comment by diogotr7** [comment]
The current release version doesn't have wooting two support yet as the official sdk hasn't been updated yet. You'll need a development version. [This](https://ci.appveyor.com/project/antonpup/aurora/builds/22844969) is the latest one.

**Comment by volkete** [comment]
Thanks, this version works wright
