### ISSUE TITLE
Hitman 2 support

### ISSUE THREAD

**Issue by DorsalAxe** [antonpup/Aurora#1493]
Hitman 2 has integration with Razer Chroma, although I haven't been able to find any information about specifics. Would be nice to have this for other brands of keyboards, if it's possible.

**Comment by simon-wh** [comment]
Try patching the Razer wrapper (by looking in Settings) to the game directory and let us know if that allows for the lighting to start working through Aurora.

**Comment by DorsalAxe** [comment]
Ah, yep. Got it working, thanks.

**Comment by greenfrogs** [comment]
@DorsalAxe I was wondering how you set it up?  I have installed the wrapper to both the main directory / and to the dx12Retail/ (using dx12) and can select it in the options menu.  However on the main menu the keyboard is completely black (I also cannot seem to find any output files from the wrapper, version: beta 0.6.4b).

Thank you for any help you can provide
