### ISSUE TITLE
Profiles lost after changing user type

### ISSUE THREAD

**Issue by adomm420** [antonpup/Aurora#1494]
### Expected behavior:

redundand.
### Actual behavior:

I've changed my user account type from administrator to a regular user and lost all my setup profiles.

### How often does this problem occur?

This problem occurs always.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. set youruser account as regular user.
2. logout + login
3. start aurora

### What is the version of Aurora you are experiencing this issue with?

My version is 0.6.4b

### Does the previous version of Aurora have this issue?
Yes, I've updated because of this.

**Comment by simon-wh** [comment]
My guess would be that due to the Aurora settings being stored in the %Appdata% that the change in user type messed with that somehow. You can try looking through your user directory to see if you can find your profiles, but other than that I don't think that this is an issue with an Aurora
