### ISSUE TITLE
Support for Diablo 1 and 2

### ISSUE THREAD

**Issue by KaHonu** [antonpup/Aurora#1499]
Support similar to what Diablo III provides would be nice to have.

**Comment by simon-wh** [comment]
Does anyone actually play Diablo 1 & 2? They're very old games and I can't see it being worthwhile to try supporting them

**Comment by KaHonu** [comment]
I do but I can see why this would be a (very) low priority item. There are certainly more popular games out there that deserve attention before old Diablo.
