### ISSUE TITLE
Overwatch lightning profile does not start.

### ISSUE THREAD

**Issue by Relaf** [antonpup/Aurora#15]
Hi, I have installed Aurora yesterday and it works great with most of the games supported on my g810. But when i try with overwatch the program (and the keyboard) keep the default profile. I have installed the program following the istructions (even if the logitech program has changed a bit) and i have runned it in administrator mode but nothing!
What do i have to do?

**Comment by Blizzardfall** [comment]
![2016-06-08_20-39-28](https://cloud.githubusercontent.com/assets/19769002/15893217/4b26227a-2db9-11e6-9be4-3b22ec0231ea.png)
Since you did not mention about it in the post...
There's 'Patch Overwatch' button in the settings.

**Comment by Relaf** [comment]
Yes, i have forgot to mention. I already did, even if the install directory is different from the default one.

**Comment by antonpup** [comment]
Make sure you have the [Visual C++ Redistributable Packages for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145) installed.

**Comment by Relaf** [comment]
I had it already, I also re-installed it but nothing changed.

**Comment by antonpup** [comment]
Make sure Overwatch isn't run as Admin. If that still does not trigger it, please pastebin your latest log file, located in "*Aurora's location*/logs/*today's date*.log".

**Comment by Relaf** [comment]
I do start overwatch from the battle.net launcher so I THINK that it's not running as admin. 
However there is the log: http://pastebin.com/dFXux5Qb

**Comment by eezmac** [comment]
I am having the same issue with my Logitech G910. Could it possibly be due to the fact that the game is not housed in my C: drive as that I have a SSD for OS and HDD for games?

**Comment by Relaf** [comment]
I was thinking the same thing but then I thought about the fact that there was a "patch" button for this reason....

**Comment by antonpup** [comment]
I have League installed on a G: drive, and I am able to patch it for LightFX testing. The patching process doesn't discriminate against drives. It takes the given path and copies files into it.

From looking over Relaf's logs, it appears that Game does not make the initial connection with Aurora. Which leads me to believe that the DLL isn't being loaded. Someone else had this issue with similar symptoms, they were running Windows 8. See if you need to unblock the dll files, I know that can prevent applications from loading dlls. You should be able to right click on dll, go to properties, and there should be a "Unblock" button or a checkbox. Press it. Do this for both dlls. Another thing you can try is running Aurora as admin and then patching and running Overwatch, but I don't see how that will be much different.

**Comment by eezmac** [comment]
I got mine working. Turns out it was actually in my C: drive :p my b. I then just found it in the patch and ran it from there. Seems to work great.

**Comment by antonpup** [comment]
Great to hear that!

**Comment by garrettbutton** [comment]
I had this issue. I moved the folder I unzipped to from downloads to program files. Don't know if that helps, but if fixed the problem.

**Comment by Relaf** [comment]
I tried unblocking dlls, moving the aurora's folder to program files and running Aurora as administrator. Nothing changed :(

**Comment by ItsYairo** [comment]
@theresamouseinmyhouse This method worked for me! I've spend hours trying to fix it, Thanks!

**Comment by antonpup** [comment]
@theresamouseinmyhouse Windows might not allow programs to make changes to the system from the Downloads folder. Which is reasonable. An installer would fix this issue.

**Comment by Relaf** [comment]
Today i'm gonna try this methods another time. Hopefully i missed something...

**Comment by Relaf** [comment]
Notice that, as I wrote in the first post, the logitech program as changed a bit from Aurora's istructions screenshots...

**Comment by Relaf** [comment]
I have tried again all the suggestions... Nothing.
The only thing that i haven't tried yet it's eezmac's suggestion, because of my terrible english skills i did not understand.

**Comment by Relaf** [comment]
YES! I finally did it! 
I thinked about the fact that the game must use the dll libraries so, after 1000 attempts, I runned the game from it's folder as administrator and it works! Anyway thanks to antonpup for doing Aurora!
