### ISSUE TITLE
A couple of suggestions & questions.

### ISSUE THREAD

**Issue by OttoWerse** [antonpup/Aurora#150]
Hi, I recently found this and when searching for a better, less buggy way to control the lighting on my G910 and G502 RGB and while I do very much like the experience and stability so far, especially compared to the original LGS control software, I have a few suggestions for features that would further enhance the experience.

First of all, migrating. I have about 40 Profiles for various games in LGS and copying all of them over seems, while totally doable, a bit tedious. Do you think there could be a way of converting LGS standard .XML Profiles into Aurora's .JSON format? I think it should be possible, although LGS stores colour information for each key, at least in per-key mode, while Aurora only works with zones, but a clever script should be able to figure out keys that belong to the same group just by looking for matching colours.

Secondly, I noticed that key combination settings look quite a bit different in custom profiles than in the desktop profile. There is no setting for Win-Key combinations, which makes sense I guess and, more importantly, there is no setting for dimming other keys when holding down CTRL or ALT, which you can do in the desktop profile. I would greatly appreciate this feature being added to custom profiles as well, or even better, the ability to use "modules" aka the different settings tabs, from other profiles in any custom profile, at least the ones that are not entirely game dependent and specific.

I also noticed there is no option to set a zone to cycle colours, like in LGS. I know there is colour wave in various directions, but no cycle effect that just changes the colour on all zoned keys simultaneously. I think it shouldn't be hard to add that in too, since its just the same as the wave effect, but without the X or Y modifier.

I have read a little bit about 3rd party apps for Logitech G devices now, and most, if not all, mention that control over G-Keys is not possible outside of LGS, since there is no SDK or API for them. But on Logitechs developer site, they offer an SDK called "GkeySDK" which I'd assume is an SDK for controlling G-Keys on various devices. Shouldn't it be possible to control colour or even macros for the G keys as well, or am I misinterpreting this SDK?

Last but not leas, I'd like to see some more interactive effects based on system states, for example, the ability to have the Caps-, Scroll- and Numlock keys light up in a different colour based on their active state, Zones lighting based on the mute state in addition to the volume state, the abilty to turn off the timeout of the volume effect, Windows keys colour based on Win-Lock state (which I don't even know if possible) and of course, a music visualiser (which has been mentioned a lot already)

I do also have one qestion, and that is, how does the exclusion of processes work? I wanted to exclude LGS, since it also displays Aurora's effects, making it hard to "copy" profiles between the two. I have already tried:
C:\Program Files\Logitech Gaming Software\LCore.exe
C:/Program Files/Logitech Gaming Software/LCore.exe
C:\Program Files\Logitech Gaming Software\LCore.exe
LCore.exe
but none of these formats seem to work. I looked into the FAQ and Googled it, but all I found was another project called Aurora on GitHub, which was about Apache Mesos clusters and obviously didn't help much, besides making me want a Computing Cluster for... research.

Again, thanks for the awesome job so far, I'd love to help, but I really don't know enough about coding yet, so I'll have to stick to feedback and suggestions. Also, sorry for the novel, but typing feels way too cool with the key press effect not to wirte one.

**Comment by simon-wh** [comment]
A lot of what you've talked about is either added now in Aurora or isn't relevant anymore to the current version. If you still care you can have a look at the current version and open a new issue
