### ISSUE TITLE
Support for StarCraft 1 and 2

### ISSUE THREAD

**Issue by KaHonu** [antonpup/Aurora#1501]
Lots of people still play StarCraft 1 and 2. Some helpful functionality would be a nice enhancement to this series.

**Comment by simon-wh** [comment]
See #50 for Starcraft 2
For Starcraft 1, I don't really see the point

**Comment by KaHonu** [comment]
@simon-wh Starcraft 1 has a remastered edition (updated for modern systems) that was recently released and is still played by lots of people. I'm not sure if you'd run into the same problems with StarCraft 2 (i.e. no way to address game state) but it might be worth a look.
