### ISSUE TITLE
Ambilight Layer Does Not Capture Full Screen OpenGL

### ISSUE THREAD

**Issue by KaHonu** [antonpup/Aurora#1504]
Actual behavior:
OpenGL games do not appear to be compatible with the Ambilight layer when in full screen mode. Any changes in the currently displayed image do not appear on the RGB device. Window modes do function as expected.

How often does this problem occur?
Always.

The issue can be reproduced by doing following steps:

1. Set up the Ambilight layer and make sure it is functioning correctly. (In this case I have it set up to work in desktop mode with no other profiles active -- most games do work as expected with the layer)

2. Load and play an OpenGL rendered game in full screen mode.

3. Observe that the RGB device doesn't change color to match on screen activity. Colors 'freeze' on what was displayed just prior to the OpenGL renderer loading.

Games Tested: Current Steam versions of the Half-Life series (GoldSrc engine - Half-Life, Opposing Force, Blue Shift); RAGE; DOOM 3 BFG Edition; The issue occurred with all of these games.

I also tried setting up a profile for the game(s) in question with only the Ambilight layer. Same result.

Devices Tested: Corsair Strafe RGB (v1); Corsair Dark Core SE

What is the version of Aurora you are experiencing this issue with?
v0.6.4b

Does the previous version of Aurora have this issue?
I have seen the same issue with prior versions of Aurora but I'm not sure if this occurs with all versions.

Please include any logs, screenshots, or files that are related to this issue:
See #251 . I'm not sure if it will help but there is mention of OpenGL and a driver that seems to provide Ambilight features.

**Comment by diogotr7** [comment]
Please test again with the updated layer in v0.7.0

**Comment by KaHonu** [comment]
Tested and worked with Half-Life. Can't test RAGE and DOOM 3 at the moment. Feel free to close if you're confident it's fixed.
