### ISSUE TITLE
The Division 2 Corsair Lighting

### ISSUE THREAD

**Issue by sausje** [antonpup/Aurora#1506]
### Expected behavior:
Dynamic keyboard lighting from Corsair on my Logitech G910

### Actual behavior:
Keys stay dark with the wrapper layer applied.

### How often does this problem occur?
All the time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Make TD2 profile
2. Apply wrapper layer
3. Launch game

### What is the version of Aurora you are experiencing this issue with?
v0.6.4b-631

### Does the previous version of Aurora have this issue?
Yep

### Please include any logs, screenshots, or files that are related to this issue:
Note, my fans and RGB strip (from Corsair) do work, but I'm trying to get the keyboard to have the same effects as shown in this video (from someone else): https://www.youtube.com/watch?v=4gIBcSttaXM

Idk if this even shows up in logs, if so, let me know which one you need.

**Comment by VeraxonHD** [comment]
Which executable are you selecting the profile to run on?

I'm encountering the same issue (using TheDivisionGame.exe)

**Comment by sausje** [comment]
> Which executable are you selecting the profile to run on?
> 
> I'm encountering the same issue (using thedivision2.exe)
> 
> My guess is there's no support for it yet?

Same exe yes.
There should be support for it, since you should be able to apply the wrapper to the keyboard and let the Corsair software take over. But I guess for that to work, we have to tell ICUE that there is a Corsair keyboard connected to it by spoofing it?

**Comment by VeraxonHD** [comment]
I suppose so.

**Comment by Wibble199** [comment]
There's been a few conversations on this Discord, but here are two of the contributor's messages:

> TD2 uses EAC and while there is already corsair wrapper which will work on TD2, it will clash with Anti Cheat unless we can find a workaround without getting flagged by anti cheat or bypassing it.

and

> You're forgetting the main thing, Anti Cheat won't allow the wrapper to work.
> And I am sure Div 2 comes with EAC

So unfortunately there's probably not a great deal we'll be able to do to get Division 2 support :disappointed:

**Comment by VeraxonHD** [comment]
Can't you just spoof a corsair keyboard "signature" and just get Aurora to "translate" it back? I'm not gonna pretend I know how all this stuff works but still that sounds like the path through it, and idk how that would trigger EAC.

**Comment by Wibble199** [comment]
DLL signing works on public-private key cryptography. Without the private key (which obviously we don't have because it's private), there's no way of making the signature of the Aurora DLL match the one that it knows to load. The whole reason for signing DLLs is so that it _can't_ be spoofed and so that the program loading it is able to verify that the original DLL hasn't been tampered with or replaced. Plus even if we could somehow sign the DLL, there's no guarantee it would work. EAC may use checksums as well as signature checking,

**Comment by VeraxonHD** [comment]
Yeah thats a shame really, but it makes sense to me. Unless we can get the game to try and accept different DLLs there's no way short of a 100 million year bruteforce of getting it to work.
Or, y'know, buying a corsair keyboard 😅

**Comment by sausje** [comment]
> Or, y'know, buying a corsair keyboard 😅

Yeah that's not gonna happen. Bought the G910 especially for TD1, and now those ffers suddenly switch to Corsair lighting for their sequel.. I hate such deals..

**Comment by KillTheSandman** [comment]
rip... feel like crying man

**Comment by sausje** [comment]
Honestly, has anyone tried to contact EAC and get them to clear the wrapper as safe? As long as you can show them the source etc, there shouldn't be any reason for them to decline the request.

**Comment by diogotr7** [comment]
We've contacted them and the only way they'd even consider looking at it is if we signed the dll, which is really expensive to do.

**Comment by sausje** [comment]
How much? Is it something that could be feasible with crowdfunding?
