### ISSUE TITLE
support for custom keyboards

### ISSUE THREAD

**Issue by Abstruse-AK47** [antonpup/Aurora#1507]
Can you guys add support for custom keyboards? I have a keyboard name circle squadron MX and I am not able to find any software for adding custom lighting effects and this is the closest software I have got, so I want you guys to add support for this keyboards.

keyboard link 
https://www.amazon.in/dp/B07DHRVNX9/ref=twister_B07FF39QPS?_encoding=UTF8&psc=1\

Thanks

**Comment by AK2427** [comment]
so nothing can be done about it I guess. if there is even a slight chance please tell me. I don't much about keyboard customization but if there's  a chance I will do it myself

**Comment by Wibble199** [comment]
Without an SDK it's very difficult to communicate with the keyboard. Theoretially the only other option would be to monitor the packets being sent to keyboard from the vendor's own software to try and replicate it but this is **exceptionally** difficult, takes many hours, and usually results in nothing anyways.

So unfortunately, yes, you're probably out of luck I'm afaid. :disappointed:

**Comment by diogotr7** [comment]
Best case scenario, if it supports the qmk firmware follow issue #1344.

**Comment by AK2427** [comment]
How can I identify that it supports qmk firmware? I have been searching for it a lot but not able to find anything about it on the net. Your help would be appreciated. 
Thanks
