### ISSUE TITLE
Backlights not working for any game

### ISSUE THREAD

**Issue by snickers568** [antonpup/Aurora#1509]
### Expected behavior:

Backlights should work as intended in games
### Actual behavior:

Backlight's dont work as intended in games
### How often does this problem occur?

This problem occurs... every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Starting a game 
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... beta v0.6.4b

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue. <--the previous version didn't support my keyboard (logitech g213)

### Please include any logs, screenshots, or files that are related to this issue:

https://pastebin.com/NCnXwHwS

**Comment by diogotr7** [comment]
More information would be useful. What does "not working" mean? The lights dont look like they should, look black, don't change at all? Do desktop effects work?

**Comment by snickers568** [comment]
I bought another keyboard and it worked. The reason it didn't work for the g213 is because it can only be customized in groups, not a specific key. You can close the thread since there isn't any problem anymore.
