### ISSUE TITLE
Apex Legends support

### ISSUE THREAD

**Issue by imvudude** [antonpup/Aurora#1511]
Apex legends was just updated with Razer Chroma support. Adding a wrapper for Aurora would be fantastic.

**Comment by Knaber** [comment]
You should label this room for "game support" so that the devs can easily find this room :)

**Comment by Wibble199** [comment]
We've had this discussion on Discord and unfortunately the user reported that the wrapper was blocked by Easy Anti-Cheat (EAC) and wasn't allowed to be loaded. There's unfortunately nothing we can do about this.

You can easily prove this for yourself by adding Apex into Aurora using the plus button on the left menu and selecting the exe and add a wrapper layer to the new profile. Then go to settings, 'Devices & Wrappers' and 'Install Aurora Wrapper Patch for Razer'.

**Comment by imvudude** [comment]
> You should label this room for "game support" so that the devs can easily find this room :)

whoops, didn't know how to label

**Comment by theshorterbus** [comment]
damn easy cheat blocks everything but the cheaters I guess.

**Comment by EthanZammit** [comment]
this seems to be working now since i tried it and it's enabled + success on r5apex.exe

**Comment by Arcanum417** [comment]
Confirmed that just now, but the chroma and wrapper layer are not doing anything.

**Comment by shinayser** [comment]
Hello, may I ask how to make Apex Legends work with Aurora? I installed Aurora on my pc but there is no Apex Legends on it.

**Comment by ijtan** [comment]
> Hello, may I ask how to make Apex Legends work with Aurora? I installed Aurora on my pc but there is no Apex Legends on it.

Hi, it has been quite a while and I have not tested it since. 
Yet it did work, I think I had to add it manually and use the Razer wrapper. Don't know if it is still possible though. 
from what I can remember I added the r5apex.exe to aurora.
