### ISSUE TITLE
Support for Cooler master CK530

### ISSUE THREAD

**Issue by OneB1t** [antonpup/Aurora#1512]
Is there someone working on support for this keyboard? I expected it to be supported as CK550 is supported but it looks like this keyboard is not included inside public SDK (but there is working cooler master application which allows to modify keyboard behaviour)

Did someone tryed to reverse engineer this new type of cooler master keyboards?

**Comment by diogotr7** [comment]
The sdk is included in the download section of the keyboard's web site, so it may still be supported. If we could get someone to test and feedback that would be great

**Comment by OneB1t** [comment]
i allready tested that and its not working i have visual studio and everything prepared and i can see that 
isDevicePlug never returns true for all devices which are inside this enum

        public enum DEVICE_INDEX
        {
            [Description("None")]
            None = -1,
            [Description("MasterKeys Pro L")]
            DEV_MKeys_L = 0,
            [Description("MasterKeys Pro S")]
            DEV_MKeys_S = 1,
            [Description("MasterKeys Pro L White")]
            DEV_MKeys_L_White = 2,
            [Description("MasterKeys Pro M White")]
            DEV_MKeys_M_White = 3,
            [Description("MasterMouse Pro L")]
            DEV_MMouse_L = 4,
            [Description("MasterMouse Pro S")]
            DEV_MMouse_S = 5,
            [Description("MasterKeys Pro M")]
            DEV_MKeys_M = 6,
            [Description("MasterKeys Pro S White")]
            DEV_MKeys_S_White = 7,
            [Description("MasterMouse MM520")]
            DEV_MM520 = 8,
            [Description("MasterMouse MM530")]
            DEV_MM530 = 9,
            [Description("MasterKeys MK750")]
            DEV_MK750 = 10,
            [Description("CK372")]
            DEV_CK372 = 11,
            [Description("CK552")]
            DEV_CK550_552 = 12,
            [Description("CK551")]
            DEV_CK551 = 13,
            [Description("Default")]
            DEV_DEFAULT = 0xFFFF
        }

i also allready writen to cooler master tech support in order to try to get new SDK which will support this type of keyboard :)

**Comment by OneB1t** [comment]
i also allready tested Cooler Master C# Wrapper which should alow me to run all options of SDK and i just cant connect to my keyboard with any selected device


![sdkv24](https://user-images.githubusercontent.com/320479/54785082-99d6c180-4c25-11e9-9a73-7b42972c2b12.jpg)

**Comment by LeasyBenjamin** [comment]
It's kind of dumb, they should make the SDK support the ck530. The included rainbow effect is awful, I want to sync it up to Aurora.

**Comment by OneB1t** [comment]
i contacted their tech support about this issue and they promised to ask development to create new build.. so we will see if there is new version of SDK with CK530 support included

**Comment by OneB1t** [comment]
new sdk is out and contains CK530!!!

//Enumeration of device list
enum DEVICE_INDEX { DEV_MKeys_L = 0, DEV_MKeys_S = 1, DEV_MKeys_L_White = 2, DEV_MKeys_M_White = 3, 
					DEV_MMouse_L = 4, DEV_MMouse_S = 5, DEV_MKeys_M = 6, DEV_MKeys_S_White = 7, 
					DEV_MM520 = 8, DEV_MM530 = 9, DEV_MK750 = 10, DEV_CK372 = 11, 
					DEV_CK550_552 = 12, DEV_CK551 = 13, DEV_MM830 = 14, DEV_CK530 = 15,
					DEV_MK850 = 16,
					DEV_DEFAULT = 0xFFFF};
