### ISSUE TITLE
Rocket League Not Working

### ISSUE THREAD

**Issue by sjhenley** [antonpup/Aurora#1521]
Aurora v0.6.4b on Logitech G910 through Logitech Gaming Software

### Expected behavior:
After Aurora is initialized, opening Rocket League switches Aurora from desktop overlay to RL-specific overlay and provides game information through keyboard lights such as boost amount and game score. After closing Rocket League, Aurora returns to desktop overlay.

### Actual behavior:
opening Rocket Leauge causes Aurora to display solid blue lighting across all keys on keyboard. No events in the game affect the wrapper lighting. After closing Rocket League, Aurora returns to desktop overlay.

### How often does this problem occur?
This problem occurs every time.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Running Logitech Gaming Software
2. Running Aurora
3. Running Rocket League

### What is the version of Aurora you are experiencing this issue with?
My version is... v0.6.4b

### Does the previous version of Aurora have this issue?
unsure

### Please include any logs, screenshots, or files that are related to this issue:
https://pastebin.com/YWweHNt2

**Comment by Wibble199** [comment]
This is because the pointers haven't been updated for the latest version of RL.

It's a time consuming task and each time there is a new update, the pointers change and it has to be done again, so often people just don't have the time to do it.

**Comment by stuntguy3000** [comment]
Should be addressed by #1714
