### ISSUE TITLE
Support Marvo KG938

### ISSUE THREAD

**Issue by Pescu123** [antonpup/Aurora#1523]
Hello, I am looking for a way to customize my keyboard better, if there is any chance of getting support for my keyboard please tell me.

Thanks!

**Comment by Wibble199** [comment]
From a preliminary look there doesn't appear to be an SDK for the keyboard, which means is very difficult to make Aurora communicate with the keyboard. It might be possible to reverse engineer or watch the data the software sends, but that's an _enormous_ amount of effort.

**Comment by Pescu123** [comment]
if you want to reverse engenieer the keyboard I can help, I am not an expert, but if you need something I can help
