### ISSUE TITLE
Not recignizing Corsair MM800

### ISSUE THREAD

**Issue by noisyboi** [antonpup/Aurora#154]
Today I received my new mouse mat "Corsair MM800 RGB" and sadly Aurora don't seem to detect it :(
However it does detect my Logitech G900, G910, G933 and my Razer Firefly mousemat.
Am I doing something wrong? or is my issue related to this: https://github.com/antonpup/Aurora/issues/148

**Comment by antonpup** [comment]
Your issue  might be related to #148.  If you are using CUE 2, then #148 will fix your problem. If you are not using CUE 2, make sure that "Enable SDK" is checked in CUE. With either outcome, try going into Aurora's settings, "Devices & Wrappers" tab, then press "Retry for connected devices".

**Comment by noisyboi** [comment]
I am indeed using the latest build on CUE 2, SDK is enabled. CUE 2 give me this http://puu.sh/rkvQb/a7bee64ada.jpg So it can tell that something is trying to controll it. Aurora howver still fails after "Retry for connected devices" I have unplugged all other RGB peripherals and it still fail... I'm clueless

**Comment by antonpup** [comment]
I have pushed a small update that fixes issues with CUE 2.
[Version 0.5.1b](https://github.com/antonpup/Aurora/releases/tag/v0.5.1b)
