### ISSUE TITLE
League of Legends LightFX no longer work after new patch

### ISSUE THREAD

**Issue by giganizer** [antonpup/Aurora#1540]
A few days ago I was notified by the game launcher, that the developer (Riot Games) was moving some game files around. Since then, the LoL wrapper lighting has not worked. I've been using it for about a month and a half now with no problems, I've had it working in this current game patch, but after that notification, it hasn't worked once. Automatic patching in Aurora no longer seems to work. When I click "Patch League of Legends" nothing happens (this is also new since the launcher notification). I manually patched both releases in my game folder, but to no effect. I checked both directories manually and the LightFX.dll file is located in the "deploy" folder in both. Other than patching manually instead of automatically, I changed nothing else. Later I also tried creating a new LoL profile and kept it default and it didn't work either.
I have a Wooting Two keyboard.

### Expected behavior:
When in-game in League of Legends, the LoL Aurora profile should change the keyboard lighting in the wrapper layer depending on the in-game HP.

### Actual behavior:
The wrapper layer stays dark (off) as if I wasn't in-game or the game wasn't properly patched, etc. It doesn't turn on.

### How often does this problem occur?
This problem occurs every time. 

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Patching League of Legends (with LightFX enabled in the config)
2. Starting the game

### What is the version of Aurora you are experiencing this issue with?
My version is... beta 0.6.4b-624-lkowurnn
This problem did not exist in this same version until recently.

### Does the previous version of Aurora have this issue?
I don't know, I haven't used any other version.

### Please include any logs, screenshots, or files that are related to this issue:
Logs:
[2019-04-14 19.49.56.log](https://pastebin.com/4RJGsrSm)
[2019-04-11 19.55.18.log](https://pastebin.com/fEbWH5ED)

Screenshot:
[game directories for patching](https://i.imgur.com/r1fbvvB.png)

**Comment by diogotr7** [comment]
That "league_client_sln" folder is the folder for the launcher, not the actual game. If you could go into a training match and find out where the actual game executable is that would be helpful. It used to be in "lol_game_client_sln" but it's not there in your screenshot.

**Comment by giganizer** [comment]
The "league_client_sln" folder and the folders shown in the screenshot are what Aurora directed me to in the Overview section for League of Legends. I located the game executable in "C:\Riot Games\League of Legends\Game" through task manager and patched that folder. The lighting now works. 
The new patched location looks like [this](https://i.imgur.com/mS1Pspw.png).
As far as new game patches go, I guess we'll see. Maybe now that the LightFX is in this location, we won't have to patch the files after every game patch...?

**Comment by diogotr7** [comment]
That looks a lot easier for us actually. Not having to patch every single update is awesome. I'll change the button to reflect those changes when I can. Thanks for your help!

**Comment by giganizer** [comment]
So, here's an update. I tested the previously mentioned method in practice tool and the lighting worked at the time. I went on with my day without playing. Soon after tho, the lighting stopped working. I attributed this to the new game patch, thought I just needed to re-patch the the game files like previously and it would be good. Turns out this is not the case. Patching the LightFX in this new location requires the game files to be re-patched every time the launcher is opened. When the launcher opens, the LightFX dll disappears. 
Looks like I was too quick to jump to conclusions. With this new location, the lighting effects do work, which is an improvement over the old location, where there was no effect, but having to patch the game every time after opening it is not a great fix.

**Comment by diogotr7** [comment]
It's an improvement nonetheless. Try going into the properties of the dll after patching and set it to read only. That might prevent the launcher from deleting it.

**Comment by giganizer** [comment]
I tried it. Checking the "Read-only" check mark in the properties did nothing, so I moved on to permission editing. After some trial and error it seems that the game launcher only cares about permissions from "Authenticated users". It needs some permissions like read and execute (not exactly sure which ones exactly, didn't bother) and it requires the delete permission ([see image](https://i.imgur.com/OkkNhIj.jpg)). If it doesn't have this permission, the launcher will attempt to [repair the files](https://i.imgur.com/nKXNuBk.jpg) after starting and [fail](https://i.imgur.com/13Xg0Im.jpg). The game files will not be verified/game-ready if the game doesn't have the delete permission over the LightFX dll when starting the launcher and it's impossible to launch a game. Patching the game files and/or editing permissions to the dll still only works while the launcher is already opened and only until the next launcher restart. When starting the launcher, it will either delete the dll or try to repair the files and fail.

**Comment by diogotr7** [comment]
That's really shitty from Riot.... I'm not sure what we can do to get over this issue unfortunately.

**Comment by diogotr7** [comment]
I tested this again and the old fix i commited seems to work just fine.

**Comment by diogotr7** [comment]
I just merged this old fix and it seems to work correctly on my machine. Closing the issue. Reopen if needed
