### ISSUE TITLE
Solution (Fix) for G-Sync UI Stutter

### ISSUE THREAD

**Issue by gitmacer** [antonpup/Aurora#1542]
### Why is this issue happening?
If G-Sync is Enabled for **windowed and full screen mode** your GPU/Monitor will try to sync to Aurora's frame rate. Because Aurora does not render at 60hz or more you will feel and see stuttering.
This is a general WPF issue and not really related to Aurora.

![grafik](https://user-images.githubusercontent.com/37345589/56161316-7c4d0b80-5fc9-11e9-865c-bf5430ffe6cb.png)

### How can I fix it?
There are 2 possible solutions to this problem:

Set G-Sync to **Enable for full screen mode** (Suggested because Aurora is not the only programm with this issue)
G-Sync will no longer work with Games in windowed or borderless mode.
![grafik](https://user-images.githubusercontent.com/37345589/56163900-d650cf80-5fcf-11e9-8969-969a3eb715ad.png)

Or disable G-Sync just for Aurora:
![G-Sync](https://user-images.githubusercontent.com/37345589/56163385-786fb800-5fce-11e9-9f25-d9f6059f5aa9.gif)

Demonstation Video:
https://www.youtube.com/watch?v=YsznF1pe5Gg
You can find more information about this issue here:
https://github.com/digimezzo/Dopamine/issues/895

Related issue:
https://github.com/antonpup/Aurora/issues/1403

**Comment by S0und** [comment]
Is this solution should work with AMD? Because i tried the equivalent of "disable G-Sync just for Aurora", so i added as a "Game" to the Radeon Software and disabled freesync for it, but a frame drops are there. If i just close Aurora, everything is fine.
