### ISSUE TITLE
Crash at Startup

### ISSUE THREAD

**Issue by Willy-JL** [antonpup/Aurora#1546]
### Expected behavior:

Should load up without crashing.
### Actual behavior:

Crashed fatally.
### How often does this problem occur?

First time I have seen this occur.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Turn on PC
2. Log into Windows
3. PC shuts down by itself (idk if this is related to Aurora)
4. PC reboots by itself without pressing any button (again idk if related to Aurora)
5. Log into Windows
6. All startup programs load
7. Aurora pops up with fatal crash
8. Click OK
9. Another fatal crash popup
10. Yet another crash popup
11. Guess what, last crash popup
12. Aurora shuts down
13. Open Aurora and it works fine.

### What is the version of Aurora you are experiencing this issue with?

My version is v0.6.4b

### Does the previous version of Aurora have this issue?
No clue, happened for the first time today
### Please include any logs, screenshots, or files that are related to this issue:

Logs:
1. https://pastebin.com/krziwNvx
2. https://pastebin.com/J5W6Kr3B
3. https://pastebin.com/NjYZ7XbU

Screenshots:
1. https://imgur.com/a/nZnGn86
2. Didn't save it as it looked identical to the previous
3. https://imgur.com/a/GeIttbq
4. https://imgur.com/a/vKizWNB

**Comment by Wibble199** [comment]
Seems like the settings for one of more of the games is perhaps corrupt or missing. Strange.

I would suggest deleting the Aurora appdata at `%appdata%\Aurora`. This will be re-created when Aurora runs next. If you have any customised profiles that have been changed (if you've ever managed to get the program to work before), you will need to back them up else they will be lost. Each profile is stored as a JSON file in `%appdata%\Aurora\Profiles\<gamename>`.

**Comment by andrixbooom** [comment]
Was going to open a thread about this, I have almost the same issue, except my computer doesn't reboot immediately.
I launch Aurora, and it immediately crashes. Doesn't matter how many times I launch it, it never starts properly.
I tried uninstalling it and reinstalling the latest version without success.
As soon as it starts, it crashes.
Here's the screen I made.
https://i.imgur.com/jyGtUBk.png
