### ISSUE TITLE
Request: A4Tech Bloody B820R / B975

### ISSUE THREAD

**Issue by lottery248** [antonpup/Aurora#1547]
### Expected behavior:
I want my own Bloody B820R / B975 able to use the aurora

### Actual behavior:
This is not yet working with so.

### How often does this problem occur?
the such keyboard is the first time  to appear here.

I am hoping for the ability that A4Tech keyboard will be compatible with this software.

**Comment by Wibble199** [comment]
Unforunately there is no SDK available for the Bloody hardware which makes adding support for it exceptionally difficult.

**Comment by lottery248** [comment]
oof
