### ISSUE TITLE
Star Ctizen support 

### ISSUE THREAD

**Issue by alanpoux** [antonpup/Aurora#1549]
Hey, like said a long time in #190, Did they plan to integrate Star Citizen ? that can be really cool

**Comment by Wibble199** [comment]
It's unlikely Star Citizen support will be coming, atleast any time soon. To get values from the game with either need (in order of preference):
1. The game to provide us with these values (e.g. CS:GO, Dota 2)
2. The ability to mod the game and add our own code (e.g. Minecraft, Subnautica)
3. The ability to read values from the game using a memory reader (e.g. Borderlands, Dishonoured).
Given that Star Citizen does not support mods or have any native game state integration, that leaves us with having to rely on memory reading. This a very time consuming task and to do justice for a huge game such as Star Citizen it would be a monumental job. In addition, it will likely break as soon as any game update or patch is released, meaning someone would have to go through the entire process again. Typically we also don't do memory reading for online games (which, correct me if I'm wrong, SC is?) as this could easily trigger anti-cheat or something similar.

**Comment by Wibble199** [comment]
Duplicate of #190

**Comment by diogotr7** [comment]
The best way i could see this maybe being supported is by reading the keybind files (like @drhead is doing for cataclysm dda in his fork) but given that it hasn't been released yet, they could change.
