### ISSUE TITLE
Aurora not working with coolermaster mk730

### ISSUE THREAD

**Issue by ThiccRice** [antonpup/Aurora#1550]
### Expected behavior:
i just got a coolermaster mk730, tkl mk750, and i expected it to work since i have used a wooting one before with aurora that was fine

### Actual behavior:
it didnt detect the keyboard at all

### How often does this problem occur?

This problem occurs... all the time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. plug in my mk730
2.  open aurora
3.  aurora doesnt notice mk730

### What is the version of Aurora you are experiencing this issue with?

My version is... (beta v0.6.4b)

### Does the previous version of Aurora have this issue?
The previous version, i didnt have a previous version, did/did not have this issue.

**Comment by inthedeepthought** [comment]
Same here. Is there any plan to add support?

**Comment by diogotr7** [comment]
Added with #1933
