### ISSUE TITLE
Add support for ETS2 and ATS new built-in RGB support

### ISSUE THREAD

**Issue by rookieoneqc** [antonpup/Aurora#1556]
ETS2 and ATS will add support of Razer Chroma in form of upcoming update 1.35 (already available for those that applied the experimental beta through steam).

Seen in this : https://blog.scssoft.com/2019/05/razer.html

**Comment by diogotr7** [comment]
With Aurora's integrated support for these games I don't see the appeal of using this integration, it seems less flexible to me.

**Comment by simon-wh** [comment]
I agree with @diogotr7, I don't know why we'd bother setting up Razer effects when you can have full customization with the existing integration?

**Comment by diogotr7** [comment]
Adding to this, if you really want the razer effects just apply the razer wrapper to it.

**Comment by Wibble199** [comment]
There's a few things the Razer integration can do that ETS2 Telemetry can't (or doesn't), such as the police lights, or the flashing enter key when it's relevant. But yeah, if people really want those effects they could use the wrapper.

**Comment by rookieoneqc** [comment]
The problem is that I tried to apply the razer wrapper, just don't seem to work for some reason
