### ISSUE TITLE
New issue Between Aurora And Corsair MM800

### ISSUE THREAD

**Issue by noisyboi** [antonpup/Aurora#156]
So, after the update of Aurora to 0.5.1b it still reports Corsair as uninitialized. I have done a clean install of aurora when updating it and I did the same to CUE 2 v2.4.66, as before CUE2 reports it being controlled by third party software but Aurora dont initalize it. my previus issue is: #154 Is there any additional information I can provide to help fixing this?

Edit, Including the logfile:

http://puu.sh/rmAOA/b59bed543e.txt

Looking at the logfile Aurora seems unable to even Identify the MM800

**Comment by antonpup** [comment]
Oh... your issue was due to the mouse mat not being supported. My apologies, I thought it was related to the fact that other users had issues with CUE 2.

Umm.. well, unfortunately, full MM support won't come until next big version. If I need to release a 0.5.1c, then I will include a solid color based on the single peripheral light.

**Comment by noisyboi** [comment]
How far off are we-isch to the next big update? currently the only features I was planning on using was slow breathing from bright to dark red and the Interactive flow effect, I can patiently wait and use CUE2 for the breathing effect in the meantime so you do not need to rush in a hotfix if you don't want to.

**Comment by antonpup** [comment]
I cannot tell you an exact date, we still have to convert all game profiles to the new layers system, finish up different keyboard/mouse virtual configurations, and resolve issues with foreign keyboard layouts. So.. It's a bit of work. Plus we have some people contributing to this project, so it would be nice to sync up completion dates.

**Comment by noisyboi** [comment]
I hear it WILL be WORTH the wait :)

**Comment by antonpup** [comment]
I added support for it in the 0.5.1c version as well as the dev branch.
