### ISSUE TITLE
Possibility to recieve RBG-Actions from Razer Synapse, Logi G Lighthub and replay on Aurora Supported Hardware

### ISSUE THREAD

**Issue by gammelobst1** [antonpup/Aurora#1563]
Hi,

would it be possible to recvieve events generated from Razer Synapse, Logitech G Lighthub and other Controller software and replay it in Aurora?
So it would be possible to use the "Full Spectrum Browsing"-Feature between Synapse and Vivaldi-Browser with another RBG-Keyboard.

cya

**Comment by KaHonu** [comment]
I have a Corsair Strafe RGB and was able to get Vivaldi to display various colors on my keyboard by installing the Razer wrapper into the folder that contains vivaldi.exe. In Vivaldi the feature is called "Razer Chroma Theme Integration". Is that what you are looking for?

There is also a Logitech wrapper and I have had success in using it for apps that support Logitech RGB lighting.

**Comment by gammelobst1** [comment]
yeah, that was it.
"Full Spectrum Browsing" is working well, thanks.
