### ISSUE TITLE
Tesoro brand keyboard support

### ISSUE THREAD

**Issue by ShibeTemple** [antonpup/Aurora#1564]
Would there be any way of manually adding support for Tesoro keyboards with third-party SDKs? 

Here are some examples of such SDKs that have been made:

https://github.com/maciek134/tesoro Python
https://github.com/rolopogo/TesoroRGB C#

If this cannot be officially supported, how would I go about adding support by myself via a fork?

**Comment by diogotr7** [comment]
The 2nd repository you linked looks to be relatively easy to add into aurora. If you look at a pull request adding a new device that could get you started.

I've looked at that repo before but I didn't know of anyone with a tesoro keyboard So i didn't bother.

**Comment by diogotr7** [comment]
Me and @GrandTeki tested with his Gram Spectrum SE on discord and although it initializes fine, none of the commands take any effect.
I think it would work with the non-SE version of it though, so if you could test that out @ShibeTemple that would be very helpful.

**Comment by ShibeTemple** [comment]
@diogotr7 Could you send me or reference the fork that has the support? I will gladly test.

**Comment by diogotr7** [comment]
I remember someone in the discord reporting that setting colors takes way too long for it to work properly. Please make another issue if you discover this is not the case.
