### ISSUE TITLE
Add Win+X and Win+; Shortcut to default desktop profile

### ISSUE THREAD

**Issue by Krutonium** [antonpup/Aurora#1565]
### Expected behavior:
When I press the Left Windows Key, it should light up the X and ; keys as well

(Win+X is a menu that appears over the start button, Win+Semicolon opens an Emoji menu)

### Actual behavior:
It highlights many other keys, but not these two.

### How often does this problem occur?

This problem occurs every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Enable Default Desktop Lighting Profile
2. Press Windows Key

### What is the version of Aurora you are experiencing this issue with?

My version is 0.6.4b

### Does the previous version of Aurora have this issue?
Yes.

**Comment by Wibble199** [comment]
The layers are fully customisable.

1. Assuming you are using the default desktop profile, on the layers list select "Win shortcuts" layer.
2. Scroll to the bottom of the shortcut list and press "New shortcut". A new item will appear at the bottom of the list.
3. Press the "Assign" button next to the new item, and press the buttons on the keyboard you want to show up. In this case press the windows key and the X key at the same time.
4. Press the stop button (same place as the assign button).
5. Repeat for each additional shortcut you want to show up.

**Comment by Krutonium** [comment]
Would love to do so, but pressing the shortcut activates said shortcut, and Aurora doesn't actually get the input.

**Comment by Wibble199** [comment]
Ah okay. I guess it could be added to the default profile, but there's nothing we can do about the shortcut not being recieved.

In the mean time if you want them to show up you can edit the JSON data for the profile. Add two new shortcuts like specified above, then close Aurora (though you may have to make a new layer and then delete it to trigger a save - this is another issue we're looking into). After this, go to `%appdata%\Aurora\Profiles\desktop` and open the relevant JSON file (probably called `default.json` or `Profile 1.json` or similar) in a text editor.  Find the line that says `"Name": "Win Shortcuts"`, and below there there will be a list of `"$type": "Aurora.Settings.Keybind, Aurora"` objects. On the last two *replace* the `"$values"` array with `"$values": [ 91, 88 ]` for <kbd>Win</kbd> + <kbd>X</kbd> and  `"$values": [ 91, 186 ]` for <kbd>Win</kbd> + <kbd>;</kbd>. When you restart Aurora it will load this file and, if done correctly, will have <kbd>Win</kbd> + <kbd>X</kbd> and <kbd>Win</kbd> + <kbd>;</kbd> in the list.
