### ISSUE TITLE
Tesoro Gram SE Spectrum (all layouts) support

### ISSUE THREAD

**Issue by GrandTeki** [antonpup/Aurora#1567]
I would like to request support for my keyboard, a Tesoro Gram SE Spectrum keyboard with a Hungarian layout.
diogotr7 (DrMeteor on Discord) told me to post an issue with the following screenshots:
![image](https://user-images.githubusercontent.com/50800712/57984491-919bd680-7a5c-11e9-9796-6d2f2dfe052f.png)
![image](https://user-images.githubusercontent.com/50800712/57984463-441f6980-7a5c-11e9-9fb9-188934236d93.png)

**Comment by diogotr7** [comment]
This was meant to be posted on another repo, oops.
