### ISSUE TITLE
Overwatch wrapper no longer works since Anniversary update 5/21/19

### ISSUE THREAD

**Issue by Caleb10E** [antonpup/Aurora#1570]
### Expected behavior:

Wrapper layer for Overwatch should work as it does on Razer keyboards after patching Overwatch directory.

### Actual behavior:

After today's update (5/21), the wrapper layer no longer works. It's just solid black.

### How often does this problem occur?

This problem occurs every time.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Patch Overwatch directory.
2. Open Overwatch and start a game or go to the practice range. None of the keyboard LEDs will light up.

### What is the version of Aurora you are experiencing this issue with?

My version is 0.6.4b.

### Please include any logs, screenshots, or files that are related to this issue:

[Screenshot of Aurora displaying Overwatch wrapper with game open in the training range](https://i.imgur.com/2KBUI85.png)

**Comment by Ocaeldan** [comment]
Hello,
Exact same issue for me (910), event if i delete the 2 files when we patch OW, delete the 2 microsoft Visual C++, take another version of Aurora and delete the Appdata file of Aurora.

Hope my case can help you too !

**Comment by diogotr7** [comment]
I suspect blizzard implemented signature checks on third party dlls as per razers guidelines, so it's very likely that auroras way of interfacing with the game will no longer work :(

**Comment by torda385** [comment]
Is there any way to get the signed dlls from the Razer app? Or maybe just point Aurora to those dlls?

**Comment by Wibble199** [comment]
No, it's not possible to sign a DLL as someone else. Even if it was possible, the signature itself is a checksum of the DLL meaning that if the DLL is different (like ours is) then the signature would be different even if you used the same private key to sign it.

**Comment by Ange17** [comment]
Hello,
This exact issue also happened to me. I tried reinstalling both the Microsoft Visual C + + and the aurora itself also, tried repatching overwatch several times and still did not work. 
Other games works perfectly and it just does it on Overwatch.

Just a question, how can I get the logs for Overwatch? So other people can see it and check what's wrong.

**Comment by Wibble199** [comment]
We know what's wrong with it. It's just not something wrong with Aurora or the wrapper.

Normally, OW ships with the Razer DLL which is a library of code authored by Razer themselves. OW tells this DLL file which keys should be what colour and the DLL then passes this information to the Razer Synapse software which then converts that information into data that can be understood by the keyboard.

What Aurora did was replace this DLL with our own "wrapper" DLL (what we call "patching") that would send the lighting information from Overwatch to Aurora instead of OW to Synapse.

The most recent update has made it so that before OW will check the signature or the checksum of the DLL and make sure it makes the official Razer one before loading it. Since the Aurora DLL is obviously different, the signature and checksums _are not the same as the Razer one_, so OW refuses to load it.

There is no way to fake the signature or checksum for our wrapper, and so there is no way to make OW load our custom DLL.

There have been ideas floating around on the Discord server about what we _can_ do, but it's very limited and will be very difficult (read: it will take a long time before Aurora supports OW again if it ever does).

**Comment by gecastan** [comment]
What about signing an aurora dll by blizzard

**Comment by Wibble199** [comment]
No doubt Razer and Blizzard will have some kind of agreement for exclusive RGB and for either party to sign our DLL would be breaking the agreement. Razer invests a huge amount of time and money in setting up RGB for games so it makes sense as to why they keep exclusivity.

**Comment by mordhau5** [comment]
This is such a sad day. Just switched teams from Rz to Logitech because I loathe their Synapse software, and was very happy to start using my G513, but I took for granted that the RGB rights would be exclusive to Razer. Understand the situation, just very sad.

**Comment by danimas** [comment]
Same Issue over here. I have a Logitech PRO Keyboard. After the Aniversary update the "Wrapper Lighting" does not work.

**Comment by ShizCalev** [comment]
Looks like they also turned on verification for Diablo 3, since that's now broken as well.

**Comment by DarkyShadoW** [comment]
Maybe could be a way to attack razer/chroma  insted of OW?

Just an idea I dont know the Chroma ecosystem

**Comment by QuiNz0r** [comment]
how exactly do they verify the razor.dll CRC?
The next step would be to intercept from razor synapse software, any ideas?

**Comment by MartB** [comment]
It is theoretically possible to replace the razer sdk server, as in provide the endpoints the official razer dll expects and take the effect data out of the binary stream that is written to these endpoints. I wandered off into this for my RETC project but nothing remotely feature complete or presentable came out of it.

**Comment by QuiNz0r** [comment]
Thanks for the insight @MartB what was the issue with your approach? Interpreting the binary stream?

**Comment by MartB** [comment]
@QuiNz0r the first issue one needs to tackle is getting the razer dll to work with your faked sdk service.
Rz. seems to use a mix of Create/Open/Pulse Event calls to signal changes and Global "worldreadable" named files. However the dll seems to expect certain environment conditions and i failed to get it to send me events and initialize correctly.

**Comment by diogotr7** [comment]
There's a working prototype being tested in the aurora discord.

**Comment by QuiNz0r** [comment]
@diogotr7 thanks for letting me know, so I talked to MoshiMoshi on discord who developed a smart workaround in record time and it looks very promising that all razer chroma games (including Overwatch) will be supported in the near future

**Comment by Gurjot95** [comment]
Please test the new build posted in Aurora's discord development channel. It should work with all chroma games.

**Comment by funkyp56** [comment]
So....will this be resolved?

**Comment by MoshiMoshi0** [comment]
Try the build in #1632

**Comment by Caleb10E** [comment]
@MoshiMoshi0 Is there an HSV toggle where I could set it to Linear like with the old wrapper layer? I think it's enabled because it seems to turn the WASD keys orange in Overwatch when they're usually yellow with the Linear setting and on actual Razer keyboards.

Also as a side note, I think the old interface for key cloning was easier to use than this one. I have to assign all 30 additional lights on my Cooler Master MK750 one-by-one, so this one's a little tedious to use.

**Comment by MoshiMoshi0** [comment]
>Is there an HSV toggle where I could set it to Linear like with the old wrapper layer? I think it's enabled because it seems to turn the WASD keys orange in Overwatch when they're usually yellow with the Linear setting and on actual Razer keyboards.

There is no linear setting since it distorts colors. The orange is the correct color from overwatch.
You can hue shift of about 20 and that will be yellow, but it will shift all colors.

>Also as a side note, I think the old interface for key cloning was easier to use than this one. I have to assign all 30 additional lights on my Cooler Master MK750 one-by-one, so this one's a little tedious to use.

Yes it might have been easier but it only allowed for one source key, so it was cloning one key to many. My method allows many source keys to many destination keys, so you have better control on how they are cloned.

**Comment by diogotr7** [comment]
The Linear color correcting didn't work correctly for zarya and Dva, for example, so using HSV looked better anyway. The current key cloning UI does allow for multiple origin keys and can be faster if you're trying to choose a large number of keys at once. This UI is easier to understand but I'm not sure which one i prefer.

**Comment by MoshiMoshi0** [comment]
Oh I thought you can have only one source key.

My reasoning is that you wouldn't really want to use one to many cloning, only in rare cases i guess. For best effect you would want to clone the color from the closest key only. I dont see the point in cloning 1 key to for ex. 10 keys. Those 10 keys would light up at the same time and that would look weird.

I could understand having multiple source keys, so it blends multiple source keys to one destination key.

**Comment by Gurjot95** [comment]
Closing now that it's resolved
