### ISSUE TITLE
Shortcut assistant - dim background keys without 'disabling' effects

### ISSUE THREAD

**Issue by AlsterDev** [antonpup/Aurora#1571]
Would it be possible to have an option within the shortcut assistant effect to not force a color and instead _just_ dim the background keys? e.g if I have a gradient layer that is translating x to y on another layer, keep that gradient applied to the keys that have a shortcut, if that makes sense?

see example I did with photoshop: https://imgur.com/a/QYqsbbc

**Comment by diogotr7** [comment]
Added with #1882
