### ISSUE TITLE
Aurora has started to grab microphone in bleeding edge builds

### ISSUE THREAD

**Issue by priitohlo** [antonpup/Aurora#1578]
At one point in the bleeding edge builds, Aurora started to grab access to the microphone. Looking through options, I could not find any reason why and for what purpose it would be doing this.

### Expected behavior:

Aurora should not access microphone without any obvious reason.

### Actual behavior:

On Windows 10, upon startup, Aurora starts accessing microphone.

### How often does this problem occur?

This problem occurs every time.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1.  Start Aurora
2.  Look at system tray or Settings - Privacy - Microphone

### What is the version of Aurora you are experiencing this issue with?

My version is 0.6.4b-642-gdohotno

### Does the previous version of Aurora have this issue?
The previous version, 0.6.4b-642-arctdgue, did have this issue.

### Please include any logs, screenshots, or files that are related to this issue:
ss: https://i.imgur.com/8UlRRG8.png

**Comment by diogotr7** [comment]
Aurora grabs the microphone to get the gamestate variable mic volume.

**Comment by gitmacer** [comment]
Aurora is using the microphone to get the Mic input volume. If we find the time we can try to ungrab the microphone if no such layer is used.
Btw: This Icon was added in the last Windows Update to 1903. That is why it started to appear.
