### ISSUE TITLE
How do i add my icue fans?

### ISSUE THREAD

**Issue by BenjaminHoegh** [antonpup/Aurora#1586]
I have a Lenovo Legion Y740 15" it has 2 fans with icue light, how do i use them in Aurora?

**Comment by Wibble199** [comment]
Currently there are a few devs on Discord who are attempting to add iCue support, but it's currently not incorporated into the main build yet.

**Comment by Wibble199** [comment]
Currently there is an experimental Corsair and Asus build in the pull requests: #1580. If you try those builds, it may be able to detect your fans. AFAIK it doesn't pick up all possible peripherals (I'm not part of that feature, so I don't know entirely what state it's in).

**Comment by Gurjot95** [comment]
That build should work with all compatible Asus and Corsair peripherals. Please use the PR to report any issues. I am closing this for now.
