### ISSUE TITLE
Help to edit keyboard

### ISSUE THREAD

**Issue by BenjaminHoegh** [antonpup/Aurora#1589]
I tryed to add it myself but i can't make any sens out of those keyboard layout files so, can you help me add this to the program?

![Keyboard Layout Editor – Google Chrome 04-06-2019 00_35_37 (2)](https://user-images.githubusercontent.com/22152591/59142875-01024780-89c5-11e9-94ef-ab755223e440.png)

**Comment by Wibble199** [comment]
Duplicate of #1587
