### ISSUE TITLE
Add Mouse: Logitech G Pro Mouse

### ISSUE THREAD

**Issue by shinji257** [antonpup/Aurora#1590]
### Expected behavior:

Logitech G Pro Mouse isn't listed in the available and supported mice.
### Actual behavior:

Eh... I guess have it listed?
### How often does this problem occur?

This problem occurs... (Fill in here)
It's a feature/enhancement request
### Please describe the steps to reproduce this issue:
N/A

### What is the version of Aurora you are experiencing this issue with?

v0.6.4b

### Does the previous version of Aurora have this issue?
N/A

### Please include any logs, screenshots, or files that are related to this issue:
N/A but if one of the listed Logitech mice will work let me know which one will map properly.  I don't know if the G900 or the G502 will actually map properly.

EDIT: Looks like it is "working" but I have no way to verify if it is working properly.  If you can advise me on which supported games that Aurora can map over supported mouse -> mouse lighting for let me know and I'll try to check it.  I actually set it on Generic for now.

**Comment by diogotr7** [comment]
If it works as generic it should work the same for everything. If it doesn't light up on games then the problem might be aurora connecting to that game, and not aurora connecting to the mouse.
