### ISSUE TITLE
Key Light Not Working On Logitech g910 Orion Spark

### ISSUE THREAD

**Issue by Rymazon** [antonpup/Aurora#1594]
### Expected behavior:
All keys light up normally on Logitech g910 Orion spark

### Actual behavior:
[ \ ] key doesn't light up

### How often does this problem occur?
Every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Use a profile on aurora

### What is the version of Aurora you are experiencing this issue with?

My version is... (### Does the previous version of Aurora have this issue?
The previous version, 0.6.4b

![image](https://user-images.githubusercontent.com/51682972/59232699-821f3180-8bb3-11e9-96aa-dda788729f52.png)

![image](https://user-images.githubusercontent.com/51682972/59232743-aa0e9500-8bb3-11e9-8085-02596e640894.png)

**Comment by diogotr7** [comment]
You have the wrong alayout selected in Settings > Devices & Wrappers > Preferred Keyboard Layout
