### ISSUE TITLE
Asus Gladius 2 hardware support?

### ISSUE THREAD

**Issue by markkbfan** [antonpup/Aurora#1596]
### Expected behavior:

Hi, I see that the Asus Pugio mouse is supported, but not the Gladius 2. Both have very similar hardware characteristics.

### How often does this problem occur?

This problem occurs... (Fill in here)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. 
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (Fill in here)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

**Comment by Gurjot95** [comment]
There is Asus build already present. Please discuss it in #1580.
