### ISSUE TITLE
League of Legends Effects

### ISSUE THREAD

**Issue by andersdigital** [antonpup/Aurora#160]
Hi,
I'm not sure if this is technically an "issue" per se, but I am not seeing any League of Legends effects. I have got the color zones working, but in the documentation it mentions "League of Legends reacts to player HP, when damaged, healed, or killed." I haven't seen any of this working (basically my Q, W, E and R keys are static blue). I've googled and looked through the software and can't find anything. I have patched it in the correct directory. Am I being a doofus?

**Comment by brainbug89** [comment]
Do you have an custom color zones for the mentioned keys? I think color zones overwrite the lighting effects of LoL.

**Comment by antonpup** [comment]
Did you enable LightFX or AlienFX in LoL settings? I think I forgot to include that as part of the instructions.

**Comment by antonpup** [comment]
Follow these instructions to enable LightFX: http://forums.na.leagueoflegends.com/board/showthread.php?t=2758307

Then make sure that you have the AuroraLightFX wrapper installed correctly.

**Comment by andersdigital** [comment]
Perfect, thank you. It was in the in-game menu under "interface." Thank you very much all :)
