### ISSUE TITLE
Cherry Mx8.0 support

### ISSUE THREAD

**Issue by gnolkaheel** [antonpup/Aurora#1605]
Hi sir, is there anyway to supprot Cherry MX 6.0/8.0. There is no response even i select "generic laptop" in the "Preferred keyboard". please help Thanks^^

**Comment by Mikowmer** [comment]
From the Cherry Americas Website for the Cherry MX 6.0:
* Bi-color status keys (blue backlight when activated)
* Red LED key backlight with adjustable brightness (dimmer)

This is not an RGB Keyboard, and so this keyboard is unlikely to work whatsoever with Aurora. If you want to try a workaround, possibly selecting pure Blue (0,0,255,255) or White (255,255,255,255) colours for effects may work, similar to how it does for the Logitech g300s mouse. It's not ideal, but it _may_ work.

For the Cherry MX 8.0:
* Adjustable white key backlight

No indication that it would be adjustable from software.


And finally, Aurora currently doesn't have wrappers from Cherry Keyboards, and I can't find an SDK for them, although it was only a very basic search. So everything above is a non-starter without that SDK.

**Comment by gnolkaheel** [comment]
Thanks for the reply, first of all the cherry MX8.0 is a RGB Keyboard, but I think there is no SDK for cherry. Anyway, thank you for the help sir!

**Comment by diogotr7** [comment]
Closing due to no sdk
