### ISSUE TITLE
Binary Counter Effect layer type

### ISSUE THREAD

**Issue by Somoto711** [antonpup/Aurora#1617]
When I let my laptop go idle for x amount of time, I fancy the idea that I could be greeted by a Binary clock. This could be used as a new layer type through a base converter, and a designation for where bits should illuminate. 
This would make use for a few things that I wish to accomplish.

Display larger values (Such as Levels, Kills and Headshots) in a compact, yet readable way
Allows clocks to be used as custom away layers triggered with the conditional layer.
More ways that I can't think of off the top of my head.

The Bits could be assigned to keys in an array. The more keys, the more bits can be displayed.

If I assign a value to keys Q W E R T & Y It would count up to 64 With Q being the 32 bit and Y being the 1 bit.

The order and number of keys signifying the highest bit to use for the counter , and location of each bit. 

What do you think?

**Comment by Wibble199** [comment]
In the dev version of Aurora there is an overrides system which is similar to the conditional layers but allows you to enable/disable ANY type of layer on a condition. In a future version (that's I'm currently working on now), I have added an idle 'evaluatable' for the overrides system which basically outputs true if the mouse hasn't been clicked or a keyboard button pressed in a configurable amount of time.

A binary-like counter layer should be easy to make, and then with this future update it could easily be used as an idle clock. I like this idea 👍
