### ISSUE TITLE
Steelseries 

### ISSUE THREAD

**Issue by robomrburns** [antonpup/Aurora#162]
Hi I have a MSI GE72 Laptop. I would love to see Steelseries support.
sdk is here:
https://github.com/SteelSeries/gamesense-sdk
Any chance of having your awesome software working here?

**Comment by antonpup** [comment]
I want to do SteelSeries support, but unfortunately, I do not have an access to a device to develop/debug with. So I decided to put it off until I had access to a SteelSeries keyboard.

**Comment by brainbug89** [comment]
I would love Steelseries support for my Rival mouse and Siberia V3 Prism headset. :+1: 

Unfortunately I haven't enough money to buy you a Steelseries keyboard. :-/

**Comment by antonpup** [comment]
If steel series had a way to display a keyboard without owning one, like Logitech emulated keyboard or CUE 2. It would be easy to make then.

I can try to make it blindly, but I don't expect it to work properly. I will try though.

**Comment by robomrburns** [comment]
the steelseries device in my case just seems to be a HID device with VID 1770 and PID FF00.
It should be relatively easy to get it working. I've found this: https://github.com/stevelacy/msi-keyboard/blob/master/lib/findKeyboard.js which might be very interesting.

**Comment by robomrburns** [comment]
I made software in C# to communicate with the keyboard:

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using HidLibrary;

namespace MSI_Keyboard
{
    public partial class Form1 : Form
    {

        HidDevice device;
        public Dictionary<Regions, Tuple<Colors, Levels>> CurrentConfig;
        public Modes CurrentMode;
    
        


        public Form1()
        {
            InitializeComponent();
            CurrentConfig = new Dictionary<Regions, Tuple<Colors, Levels>>();
        }

      
           

        public void button1_Click(object sender, EventArgs e)
        {
           device = HidDevices.Enumerate(0x1770, 0xFF00).First();
            device.OpenDevice();
            if (device.IsConnected){

                button1.Text = "OK";
                SetColor(Regions.right, Colors.White, Levels.High);
                SetMode(Modes.Normal);

            }

           

            device.CloseDevice();
        }



        public bool SetColor(Regions region, Colors color, Levels intensity)
        {
            if (device.WriteFeatureData(new byte[] { 1, 2, 66, (byte)region, (byte)color, (byte)intensity, 0, 236 }))
            {
                CurrentConfig[region] = new Tuple<Colors, Levels>(color, intensity);
                return true;
            }
            return false;
        }

        public bool SetMode(Modes mode)
        {
            if (device.WriteFeatureData(new byte[] { 1, 2, 65, (byte)mode, 0, 0, 0, 236 }))
            {
                CurrentMode = mode;
                return true;
            }
            return false;
        }




        public enum Regions
        {
            left = 1,
            middle = 2,
            right = 3
        }

        public enum Colors
        {
            Off = 0,
            Red = 1,
            Orange = 2,
            Yellow = 3,
            Green = 4,
            Sky = 5,
            Blue = 6,
            Purple = 7,
            White = 8,
            DarkOrange = 9,
            DarkGreen = 10,
            MidnightBlue = 11,
            Rose = 30,
            Teal = 50,
            Custom = 99
        }

        public enum Levels
        {
            Light = 3,
            Low = 2,
            Medium = 1,
            High = 0
        }

        public enum Modes
        {
            Normal = 1,
            Gaming = 2,
            Breathe = 3,
            Demo = 4,
            Wave = 5
        }
    }

 

}

**Comment by justinghawk** [comment]
So is this being added? Would love to have steelseries integration with my keyboard.

**Comment by antonpup** [comment]
I have no steel series keyboard to test with. So I can't really add support for it.

**Comment by justinghawk** [comment]
Well this guy made a code so you can maybe try it out

**Comment by antonpup** [comment]
How can I try it out without having a steel series keyboard to try with?

**Comment by CalcProgrammer1** [comment]
Look at the code that @saltybot committed to my keyboard visualizer.  He implements the Apex M800 using USB HID interface.  I ported a similar implementation for MSI SteelSeries laptops (3 keyboard zones and up to 4 additional zones depending on laptop model) from @bparker06.

Apex M800:  https://github.com/CalcProgrammer1/KeyboardVisualizer/blob/master/KeyboardVisualizerCommon/SteelSeriesGameSense.cpp

MSI SteelSeries Laptop:  https://github.com/CalcProgrammer1/KeyboardVisualizer/blob/master/KeyboardVisualizerCommon/MSIKeyboard.cpp

**Comment by ersan** [comment]
Any progress on this at all?  I have Arctis 5 headphones and would very much like support in Aurora for them as I haven't found any other RGB headset that is nearly as good.  Would a hardware donation help?

**Comment by brainbug89** [comment]
> I can come up with code that can change the headset light colors but I'm afraid Aurora is a bit more complex than I've dealt with before so I don't think I'm knowledgeable enough to do a pull request.

Are you using the Gamesense SDK? Which programming languages did you used?

**Comment by th3an7** [comment]
Hi,
Is this still in progress or it's already dropped? I've just bought Rival 300 and I could test something if anybody could tell me, what should be done to make Aurora support Steelseries products.

Thanks :)

**Comment by brainbug89** [comment]
If someone owns a SteelSeries Apex M800, please reply to #644 :wink:
