### ISSUE TITLE
not all K95 Platinum macro keys illuminating after iCue update

### ISSUE THREAD

**Issue by ShizCalev** [antonpup/Aurora#1620]
### Expected Behaviour
G1, G2, G4, and G5 keys light up

### Actual Behaviour
The described macro keys don't light up.

### Reproduction steps
Set up a fill layer on desktop.
Update iCue to latest version, 3.17.94
G1, G2, G4, and G5 keys no longer light up.
Close aurora and they turn back on.

### Frequency

100%
### Aurora Version:

V0.6.4B-129

### Previously an Issue?

Unknown. Didn't occur until today's icue update.

**Comment by Gurjot95** [comment]
This seems like iCue only issue as reported by other members in discord as well. I suggest you to wait for Corsair to release update. If it works with iCue but only have issues with Aurora then let me know and I will reopen this.

**Comment by BrunoBettini** [comment]
I have exactly the same setup as ShizCalev (Corsair K95 RGB Platinum, iCUE v3.17.94, Aurora v0.6.4b), and exatcly the same problem, and as he said ("Close aurora and they turn back on"), those 4 keys work normally if managed by iCUE itself, but don't light up at all if managed by Aurora.
In fact the very moment you close the Aurora exe, they light up immediately, and can be managed normally through iCUE.
Also for me the problem started when I updated iCUE to the latest version, never experienced that before.

**Comment by Gurjot95** [comment]
Seems like issue with SDK. Reopening it.

**Comment by WhiteSockedDancer** [comment]
got exactly the same issue.

**Comment by Nitzowsky** [comment]
Same issue here, Only G3 and G6 lights up in Aurora, in icue it's all normal

**Comment by RicalNL** [comment]
It seems to be a remapping issue. (Aurora V0.6.4b)
M1 refers to M3 in the ICUE software V3.18.77
and M2 to M6

**Comment by WhiteSockedDancer** [comment]
Any News on this? Can we help somehow?

**Comment by SlothBro101** [comment]
I have the exact same issue except only G3 and G6 light up. The other macro keys stay turned off but as soon as I exit Aurora, the rest of the lights turned on to work fine with iCue.

**Comment by diogotr7** [comment]
For everyone that has this problem, does iCue v3.17.94 have this issue, or is it limited to v3.18.77?

**Comment by RicalNL** [comment]
> For everyone that has this problem, does iCue v3.17.94 have this issue, or is it limited to v3.18.77?

Just installed ICUE v3.17.94 and has the same issue for me atleast. I set M1 to a colour and M3 lighted up. Got the same with M2 to M6.

K95 RGB Platinum (US North America), Firmware v3.21.7168. ICUE v3.17.94. Aurora v0.6.4b (Key layout, United States) = Bug Present
K95 RGB Platinum (US North America), Firmware v3.21.7168. ICUE v3.18.77. Aurora v0.6.4b (Key layout, United States) = Bug Present

When you need more info, I'll be glade to help.

**Comment by Gurjot95** [comment]
Please test #1670 and let me know if it works

**Comment by RicalNL** [comment]
> Please test #1670 and let me know if it works

Thx for the easy FIX. It works great again!
