### ISSUE TITLE
Support for Minecraft 1.13.2

### ISSUE THREAD

**Issue by Somoto711** [antonpup/Aurora#1626]
Please add support for the following game:

**Game Name: Minecraft Version 1.13.2** 
**Methods:Already has support for versions around it, and there is a Forge version for 1.13.2 now.
https://github.com/antonpup/Aurora/pull/1213 can be updated** 

The new forge can be found here: https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.13.2.html

**Comment by diogotr7** [comment]
I have a working 1.13 version working. I'll try and push it to the gitlab soon.
Please keep these issues asking for the mod to that repo, please. You can find a link to it in the Minecraft overview tab in Aurora.

**Comment by diogotr7** [comment]
I just uploaded the mod here https://gitlab.com/aurora-gsi-minecraft/mc1.13.2/-/tags
