### ISSUE TITLE
Overwatch plugin notworking with Logitech G910 and razer goliathus connected

### ISSUE THREAD

**Issue by PedroCavaleiro** [antonpup/Aurora#1637]
Hi,

I tryed to use Aurora with both my Logitech G910 (connected through Aurora) and Razer Goliathus Chroma (not connected through Aurora) but even though Aurora switches to the Overwatch profile the keyboard remains black but the Razer Goliathus works just fine and in accordance with the game, when I return to the desktop Aurora returns to the default profile that works fine. Yes, I did patch the game

Aurora Version: beta 0.6.4b
Logitech Gaming Framework Version: 9.02.65
Razer Synapse Version: 3.4.630.62510
Overwatch Version: 1.38.0.2.60038

**Comment by diogotr7** [comment]
Please follow issue #1570
