### ISSUE TITLE
Logitech G-Key & Logo lighting

### ISSUE THREAD

**Issue by dangerskew** [antonpup/Aurora#164]
Version 8.87 of Logitech's LED Illumination SDK now allows for this.
http://gaming.logitech.com/en-us/developers
"Added the ability to set G-Keys and the G Badge’s color with LogiLedSetLightingForKeyWithKeyName."

**Comment by antonpup** [comment]
Thank you! I will take a look at it. Might put up another small update with this enabled.

**Comment by antonpup** [comment]
I looked at it. And I implemented it in the dev build. I will push another small update that will enable the functionality tomorrow.

**Comment by antonpup** [comment]
Did the update a bit earlier.
