### ISSUE TITLE
Problem with Corsair Strafe Mk.2

### ISSUE THREAD

**Issue by igorz7** [antonpup/Aurora#1643]
[INFO] 20:20:34: CaptureState is Starting
[ERROR] 20:20:34: Error encountered in the Equalizer layer. Exception: System.Runtime.InteropServices.COMException (0x88890008): Exceção de HRESULT: 0x88890008
   em System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)
   em NAudio.CoreAudioApi.WasapiCapture.InitializeCaptureDevice()
   em NAudio.CoreAudioApi.WasapiCapture.StartRecording()
   em Aurora.Settings.Layers.EqualizerLayerHandler.UpdateAudioCapture(MMDevice defaultDevice) na C:\projects\aurora\Project-Aurora\Project-Aurora\Settings\Layers\EqualizerLayerHandler.cs:linha 182

### Expected Behaviour
Keyboard lights responding correctly in Audio Visualizer function and in game interactive effects.

### Actual Behaviour
I'm having a problem with my new keyboard in Aurora. It don't work. Some effects works fine setting manually, but i have intrested in Audio Visualizer and in game effects, and both don't works. Audio Visualizer are not responding. And in game effects, the keyboard change color for the game, but is not working any interactive effect.
In Audio Visualizer, i've tried other softwares, like Corsair Effects Engine (I can't set my keyboard in dropbox, that have only "None" option), and also Keyboard Audio-Visualizer, and I get this error: "An error occurred while starting the Keyboard Audio-Visualizer. Please double check if SDK-support for your devices is enabled."
In iCue (version 3.18.77, the most recent) is enabled "enable SDK", and when I open Aurora, iCue inform that lights are be controled by third softwares itself. 
In Aurora settings, my device is recognized in Device Manager showing 1-2 ms started.

### Frequency
 Every time, since I bought.

### Aurora Version:
v0.6.4b

### Previously an Issue?
 Yes

**Comment by diogotr7** [comment]
For the visualizer, refer to #1487 . 
For the games not working, that depends on the game, so please specify.

**Comment by igorz7** [comment]
> For the visualizer, refer to #1487 .
> For the games not working, that depends on the game, so please specify.

About #1487, i didn't find any process or service with "Nahimic" name. But my motherboad is ASUS with Sonic Studio installed.
In games, all i've tried i had problems. Examples: CSGO, Rocket League, GTA V and The Division. When I select the window of Aurora, the keyboard lights on, and when i change to other window, lights out. In Rocket League the Keyboard stays in blue all the time in game, for example. 

I dont know what do anymore. I hope someone can help me.

**Comment by diogotr7** [comment]
If you disable sonic studio the vizualiser will work.

Rocket league support is broken, CSGO might need patching ( you can do that from aurora), the other two games are logitech supported and should work, but there are some known issues that are fixed and will probably be released in the next version. For further help please join our discord: https://discord.gg/YAuBmg9

**Comment by igorz7** [comment]
OMG man, tried change output in Windows and for the fist time i'm seeing my keyboard lights with the music! I'm using Razer Surround Audio Controller now, but i don't know how i will disable Sonic Studio and still working on Windows.

About games, Rocket League I didn't know about it. Thanks fort the information!
I'm very grateful for your help! Thank you so much!
I'll test games again, and if I found some error I go to Discord. Thanks!!!
