### ISSUE TITLE
aurora with arduino 

### ISSUE THREAD

**Issue by RSTK13** [antonpup/Aurora#1645]
Hi , first of all , thanks for all ur awesome work here,
I've started to trying to setting up this program : https://github.com/Wulkop/Aurora/tree/pi-lighting
But since this folder doesn't exist , i wonder where i have to install this script for aurora , tried to install it in my desktop script folder but it didn't work and aurora says it maybe need an update.
Is it possible to update this for the aurora's version 0.6.4b ?

Here's what's the logs says about that: https://pastebin.com/AQZmKzM1

here's the link where i download the script : https://github.com/Wulkop/Aurora/tree/pi-lighting

Looking forward for ur answers , Thomas.

**Comment by diogotr7** [comment]
There's instructions on that page: 
`On your PC, copy file "Scripts/Devices/rpi_script.cs" to "Aurora install location/Scripts/Devices/rpi_script.cs"`

Which on most installations would be : `C:/Program Files/Aurora/Scripts/Devices/rpi_script.cs`

**Comment by RSTK13** [comment]
Hi diogotr7 , here's my aurora install location looks like : 
https://imgur.com/a/LsItTfc
I don't have this "Scripts" folder , and i think that was with an older version of aurora

**Comment by diogotr7** [comment]
You need to create that folder structure

**Comment by RSTK13** [comment]
owh , in fact , the script is now rcognized and maybe works , since i have to wait monday to test it with my esp 8266 , thanks for the help here <3 much appreciated
