### ISSUE TITLE
G810 Media buttons and indicators not lighting

### ISSUE THREAD

**Issue by medifin** [antonpup/Aurora#165]
Logo light is working, but flickering a bit though

**Comment by antonpup** [comment]
Media keys are not available as far as I know.

Can you describe the flickering? When does it happen? What settings do you have in Aurora that flicker?

**Comment by medifin** [comment]
I have set the logo in red-white color breathing mode and the animation feels laggy. I have other keys set in color breathing mode as well and they dont flicker at all

**Comment by antonpup** [comment]
Yeah, I think I know what you are experiencing. It's a hardware issue. Basically, the Logo and badge both operate differently than the keycap LEDs. If a color isn't 100% red/green/blue, then it will try to quickly mix variations of the three to produce the color. This happens with both LGS and Aurora. It can be clearly seen with high fps cameras. Here are two demo videos I took with my phone:
LGS Demo:
[![LGS Demo](http://img.youtube.com/vi/8DuvfWiI8Ik/0.jpg)](https://www.youtube.com/watch?v=8DuvfWiI8Ik)

Aurora Demo (Note: Aurora currently does not control the "G910" badge, its color is static):
[![LGS Demo](http://img.youtube.com/vi/0xypVFLya7E/0.jpg)](https://www.youtube.com/watch?v=0xypVFLya7E)

In the Aurora demo, when the logo color is 100% red, there is no flicker, but as soon as it starts shifting to white, it starts mixing colors and producing flickering.

**Comment by medifin** [comment]
Alright, thanks for the explanation
