### ISSUE TITLE
need a bit of help to install this properly

### ISSUE THREAD

**Issue by RSTK13** [antonpup/Aurora#1650]
#1454 
Hi guys , so i've managed to install this to make my 5 meters of ws 2812b working with aurora
So, i've bought an esp 8266 followed up all the tutorial and when i try to upload the code i end with some errors during the compiling and i can't figure why.
here's the pastebin of the error report : 
https://pastebin.com/f5TvXtSt

Thx in advance

**Comment by RSTK13** [comment]
i've found why is it buggy so for the next persons , here's a link where i solved my problem :3 
https://github.com/FastLED/FastLED/issues/733

**Comment by diogotr7** [comment]
Thanks for following up on the issue!
