### ISSUE TITLE
Gta v issue 

### ISSUE THREAD

**Issue by Reppzz** [antonpup/Aurora#166]
Hey You really done some amazing work with this program :) 
But for some reason the police effect on my g910 doesn't work in game.
It just stays red and blue and doesn't flash, it does work in the aurora preview though.

**Comment by antonpup** [comment]
This was addressed in the dev version. I really need to get a solid deadline for it.

Anyways, GTA 5 changed the way their lighting works. Before they would pass an additional "police indicator" value to the Logitech SDK, with which LGS would change colors to mimic the siren. They do not do that anymore. Instead, they actually set the entire keyboard color and actually set the function key lights with the siren effect.

**Comment by antonpup** [comment]
This will be addressed in 0.5.1d.
