### ISSUE TITLE
K95 G Keys lightning problem

### ISSUE THREAD

**Issue by toxicgl** [antonpup/Aurora#1668]
### Expected Behaviour

All G keys must be work.

### Actual Behaviour

Only G3 and G6 works for lightning.

### Reproduction steps

I updated my CUE and lights went out. On aurora app i can see them they have light on them.
Must be CUE integration problem.

### Frequency

Every time

### Aurora Version:

0.6.4b-663

### Previously an Issue?

Yes

**Comment by diogotr7** [comment]
Duplicate of #1620
