### ISSUE TITLE
One button light in other color

### ISSUE THREAD

**Issue by Tehakla** [antonpup/Aurora#167]
Hi one of my button at my G910 lights with another color and i cant change it. 
When i disable tthe lights the button still light.

**Comment by antonpup** [comment]
Did you select your keyboard localization in the settings? What localization is your keyboard for?

**Comment by Tehakla** [comment]
Germany my button is the Ü 
I have choose logitech and germany

**Comment by Tehakla** [comment]
can close i've downloaded me the layout and replace it

**Comment by brainbug89** [comment]
Hi @Tehakla, try change color of "ß" ... maybe it's a similar issues like #123

**Comment by antonpup** [comment]
The issue is that when I updated the Logitech SDK, I just copied the Logitech integration from dev branch. On which I was doing changes for how foreign keyboards function. So as a result, foreign keyboard layouts on Logitech are broken with 0.5.1c

**Comment by antonpup** [comment]
This is addressed in 0.5.1d.
