### ISSUE TITLE
[Question] Microphone in use?

### ISSUE THREAD

**Issue by QuentinMcCarthy** [antonpup/Aurora#1672]
This isn't really an issue, I just had no clue where to post such a question. Recently, my Windows updated, and I noticed a new feature in my tray that was telling me how many applications were currently using my microphone. Naturally, I was curious, so I clicked into it. I noticed the expected game I was playing for voice chat, but I also noticed Aurora was using my microphone.

Why does Aurora need to use my microphone? The only audio-based capability I've ever seen on the application is the ability to react to audio playing on the computer, but that has nothing to do with the microphone?

**Comment by dessmith** [comment]
Likewise, same thing, updated windows recently and an icon on the task bar status area states "Aurora is using your microphone"

**Comment by diogotr7** [comment]
This is used for the game state variable microphone volume. You'll be able to disable it in the next version

**Comment by diogotr7** [comment]
Also, our discord is a pretty good place for questions like this: https://discord.gg/YAuBmg9
