### ISSUE TITLE
Aurora crashes after v0.7.0rc1 update

### ISSUE THREAD

**Issue by steris123** [antonpup/Aurora#1678]
### Expected Behaviour

Aurora should start normally
### Actual Behaviour

It crashes after ~10-15 secs and starts to spawn that error message several times
### Reproduction steps

does it every time for me
### Frequency

every time
### Aurora Version:

v0.7.0rc1
### Previously an Issue?

worked fine

**Comment by steris123** [comment]
if I keep that error message open, aurora works fine

**Comment by Gaerisson** [comment]
same for me :/ 
![image](https://user-images.githubusercontent.com/25458928/64056793-336fab00-cb96-11e9-85ae-85a040d3a1f2.png)

**Comment by diogotr7** [comment]
Could you post a log here? you can find them in %appdata%\Aurora\Logs

**Comment by Gaerisson** [comment]
[2019-08-31 02.21.20.log](https://github.com/antonpup/Aurora/files/3561923/2019-08-31.02.21.20.log)
This error came after the update of the Chroma version : 
![image](https://user-images.githubusercontent.com/25458928/64057092-2d2efe00-cb99-11e9-8d66-ce0ac18075a6.png)

**Comment by diogotr7** [comment]
Do you have any nzxt devices?

**Comment by steris123** [comment]
I though at I posted logs allready :D
and no nzxt devices, only logitech 
[2019-08-30 21.44.03.log](https://github.com/antonpup/Aurora/files/3562263/2019-08-30.21.44.03.log)

**Comment by Gaerisson** [comment]
@diogotr7 for me I only have Razer and Logitech, Razer worked before updating the chrome in Aurora, but now, It won't sync and crash.

**Comment by simon-wh** [comment]
Can those with issues please try [v0.7.0-rc2](https://github.com/antonpup/Aurora/releases/tag/v0.7.0rc2)?

**Comment by steris123** [comment]
works fine, thank you
