### ISSUE TITLE
support Cooler Master CK372

### ISSUE THREAD

**Issue by LynkLin** [antonpup/Aurora#1691]
Please add support for the following device:

**Device Name:**  Cooler Master CK372

**Device Website:** https://www.coolermaster.com

I select other device, like pro L, but the num lock and other 3 light (C, S, G) did't work. which device should I choose.

**Comment by diogotr7** [comment]
I looked at the coolermaster integration and sdk docs and it seems that the key mappings of that keyboard dont have anything special in particular. Those 4 keys you mentioned don't light up at all?

**Comment by LynkLin** [comment]
Not 4 keys, just num lock led, caps lock led, scroll lock led and game mode led. The 4 led

**Comment by diogotr7** [comment]
Ah you mean the indicator lights? The sdk doesn't mention them at all so i don't think tey can be controlled.

**Comment by LynkLin** [comment]
I'm sad, cooler master's sdk is so so weak.
