### ISSUE TITLE
G keys assigned as F keys

### ISSUE THREAD

**Issue by Greenblud** [antonpup/Aurora#1694]
### Summary
In "Solid Color Layer", "Toolbar Layer" and other layers, the G keys, when assigned, are seen as F keys (G1 = F1, G2 = F2, [...]). Even in the "Affected Keys" box, F1 appears instead of G1.

If selected with the UI (instead of being pressed), only the color of the (G) keys can be changed, they won't behave as intended with the Toolbar Layer.

Keyboard: G910

### Aurora Version:
v0.6.4b

### Previously an Issue?
Don't know.

**Comment by diogotr7** [comment]
Aurora can't detect the G keys (or any macro keys) being pressed. It only detects whatever you set them to (which in your case seems to be the F keys).

**Comment by Greenblud** [comment]
Thanks
