### ISSUE TITLE
FN shortcut assistant layer

### ISSUE THREAD

**Issue by Foohy2502** [antonpup/Aurora#1700]
Hey there! I was wondering on my Logitech G513 why Aurora doesn't know the "FN" button. As soon as I try to use the Layer type "Shortcut Assistant Layer" and wanted to add a new shortcut, it doesnt work with the FN. Would be great if you could fix that, as its more useful than using the other presets, which are given.

Greetings!

**Comment by diogotr7** [comment]
Unfortunately the fn key on most keyboards doesn't even get to the computer, it just modifies the keys on the hardware. We can't really do anything to fix this unfortunately.
