### ISSUE TITLE
How does Aurora get access to the csgo game state?

### ISSUE THREAD

**Issue by LegendaryB** [antonpup/Aurora#1702]
Hey,

wanted to know how aurora gets the informations from the game like bomb ticking etc. Is it reading RAM? I'm asking cause of VAC.

And how does I get the Roccat Mouse to work? I have installed Roccat FX Talk but its always using the default colors

**Comment by diogotr7** [comment]
Aurora uses this to get access: https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Game_State_Integration

**Comment by LegendaryB** [comment]
Thank you! :)
Can you also provide the information about roccat?
