### ISSUE TITLE
Aurora crashes on startup every time

### ISSUE THREAD

**Issue by senkus** [antonpup/Aurora#1704]
### Bad Behaviour
Aurora will crash every time for me. No real idea why. Sometimes at least the tray icon will show, but you can can't open the right-click menu even.

Things I've tried:
- Reinstall Aurora and wipe AppData
- Remove and uninstall all Logitech USB devices/drivers via USBDeview
- Reinstall LGS
- Uninstall Synapse (I'm not using any Razer devices rn)
- Launch Aurora without any LED peripherals connected (using Remote App on phone)

### Frequency
Always. 

### Aurora Version:
Aurora-v0.7.0rc2
Aurora-v0.6.4b

### Previously an Issue?
Aurora-v0.7.0rc2 was running fine just a few days ago, actually.

### Logs
[2019-09-08 22.11.47.log](https://github.com/antonpup/Aurora/files/3587996/2019-09-08.22.11.47.log)
[2019-09-08 22.02.34.log](https://github.com/antonpup/Aurora/files/3587998/2019-09-08.22.02.34.log)
[2019-09-08 22.01.05.log](https://github.com/antonpup/Aurora/files/3587999/2019-09-08.22.01.05.log)

**Comment by senkus** [comment]
I remembered that the Event Viewer is a thing:
```
Faulting application name: Aurora.exe, version: 0.7.0.0, time stamp: 0x5d6ad465
Faulting module name: d3d9.dll, version: 10.0.18362.329, time stamp: 0x1ac9a115
Exception code: 0xc0000005
Fault offset: 0x00000000000ac44e
Faulting process id: 0x95c
Faulting application start time: 0x01d5668b8b50266c
Faulting application path: C:\Portable\Aurora\Aurora.exe
Faulting module path: C:\WINDOWS\SYSTEM32\d3d9.dll
Report Id: 74c65f5c-657a-4729-8550-3c2fcc69e2f1
Faulting package full name: 
Faulting package-relative application ID: 
```

**Comment by senkus** [comment]
If I shut down both HWiNFO and RTSS (Afterburner not installed), Aurora launches again.
(In the past I've never had to close HWiNFO when dealing with RTSS woes.)

**Comment by MigRic** [comment]
hmm just a wild guess... Have you tried clearing cache from RTSS?

**Comment by senkus** [comment]
> hmm just a wild guess... Have you tried clearing cache from RTSS?
I didn't even know that existed. I cleared the injection cache just now.
Now it seems that I can launch all programs in any order.

**Comment by MigRic** [comment]
> > hmm just a wild guess... Have you tried clearing cache from RTSS?
> 
> I didn't even know that existed. I cleared the injection cache just now.
> Now it seems that I can launch all programs in any order.

So, it really worked?? I wasn't expecting it =P
