### ISSUE TITLE
Empty effect_type by LightFX

### ISSUE THREAD

**Issue by drdrjojo** [antonpup/Aurora#171]
Caused by `effect_type = GetString("effect_config");`

Maybe a workaround?

**Comment by antonpup** [comment]
Can you explain exactly to me what is the problem? What is the workaround for?

**Comment by drdrjojo** [comment]
The problem is after Command_Wrapper received an ActionFx command, the effect_type is not set.
And this happens with this part of the code:
`effect_type = GetString("effect_type");
effect_type = GetString("effect_config");`

Looks like `effect_config = GetString("effect_config");` will fix this, but i haven't tested it with all games.

**Comment by antonpup** [comment]
I see what you mean. I fixed it in the dev. Thank you, nice catch!
