### ISSUE TITLE
Desktop Layer

### ISSUE THREAD

**Issue by Mikowmer** [antonpup/Aurora#1710]
With the introduction of the Overlay Layers in 0.7, I've noticed something: When I'm using the software that I have an overlay layer for, it doesn't include the default desktop lighting, even when there are no layers provided.

Would it be possible to either:
1. Add a layer that would default to the desktop profile? So whatever the desktop profile would do, it will do. Or,
2. Add a button that would allow for the overlay lighting effects to be provided by Aurora, but not the main layers?

**Comment by Wibble199** [comment]
A solution for this has been implemented as of PR #1707, allowing users to disable the regular layers independently from the overlay layers. So in this case you would disable the regular layers for whichever program you have added the overlay layers for and Aurora will then fallback to using the desktop layer. It is in the current dev build and will be in the next release.
