### ISSUE TITLE
Random 383 GB Log

### ISSUE THREAD

**Issue by Unkn0wnTh2nd3r** [antonpup/Aurora#1716]
I awoke this morning to find that my computer's SSD had randomly filled up to max capacity. Upon inspection i was able to narrow down the culprit of the massive change in storage has been a result of a _**383 GB**_ log in Aurora's log folder. Too large to open in any word processing program.

**Comment by diogotr7** [comment]
Oh man that is BAD. Could you try opening it in chrome and find out what exactly is spamming it?

Usually that works for big logs but your example is a bit too extreme.

**Comment by Snafu7** [comment]
Aurora beta v0.7.0rc2 - 500+mb log file. and its growing fast...

the log file is totally spammed by the following entries:

`[ERROR] 11:29:19: Error encountered in the Equalizer layer. Exception: System.DivideByZeroException: Nastąpiła próba podzielenia przez zero.
   w Aurora.Settings.Layers.EqualizerLayerHandler.Render(IGameState gamestate) w C:\projects\aurora\Project-Aurora\Project-Aurora\Settings\Layers\EqualizerLayerHandler.cs:wiersz 274
[ERROR] 11:29:19: Error encountered in the Equalizer layer. Exception: System.DivideByZeroException: Nastąpiła próba podzielenia przez zero.
   w Aurora.Settings.Layers.EqualizerLayerHandler.Render(IGameState gamestate) w C:\projects\aurora\Project-Aurora\Project-Aurora\Settings\Layers\EqualizerLayerHandler.cs:wiersz 274
[ERROR] 11:29:19: Error encountered in the Equalizer layer. Exception: System.DivideByZeroException: Nastąpiła próba podzielenia przez zero.
   w Aurora.Settings.Layers.EqualizerLayerHandler.Render(IGameState gamestate) w C:\projects\aurora\Project-Aurora\Project-Aurora\Settings\Layers\EqualizerLayerHandler.cs:wiersz 274
[ERROR] 11:29:19: Error encountered in the Equalizer layer. Exception: System.DivideByZeroException: Nastąpiła próba podzielenia przez zero.
   w Aurora.Settings.Layers.EqualizerLayerHandler.Render(IGameState gamestate) w C:\projects\aurora\Project-Aurora\Project-Aurora\Settings\Layers\EqualizerLayerHandler.cs:wiersz 274
[ERROR] 11:29:19: Error encountered in the Equalizer layer. Exception: System.DivideByZeroException: Nastąpiła próba podzielenia przez zero.
   w Aurora.Settings.Layers.EqualizerLayerHandler.Render(IGameState gamestate) w C:\projects\aurora\Project-Aurora\Project-Aurora\Settings\Layers\EqualizerLayerHandler.cs:wiersz 274
[ERROR] 11:29:19: Error encountered in the Equalizer layer. Exception: System.DivideByZeroException: Nastąpiła próba podzielenia przez zero.`

send help, i've got 2TB on that drive :(

**Comment by diogotr7** [comment]
@snafu7 that bug has been fixed in the release/v0.7 branch and will be available in the official v0.7 release.

**Comment by Snafu7** [comment]
Oh, sorry, i tought im on the bleeding edge, totally misread the links. Thanks for your reply.

**Comment by diogotr7** [comment]
This bug has been fixed with #1920
