### ISSUE TITLE
Logitech G-Key Question

### ISSUE THREAD

**Issue by TBrozovich** [antonpup/Aurora#172]
Hi thank you for the continual support.

I saw there was now support for the Logitech SDK that is now including the G-keys in your latest version. You mention that this does not include the wrapper. So do we need to wait for an updated wrapper to get the G-keys to function properly or am I doing something wrong. 

Thanks for your time!

**Comment by antonpup** [comment]
The wrapper not being updated simply means that other applications that use Logitech LED sdk will not be able to set the g-keys, logo, and badge.

Overall, Aurora will work just fine with the g-keys. It's just the other applications.

**Comment by antonpup** [comment]
I will close this, as it's not really an issue to be resolved. Feel free to continue commenting if you have any further questions.

**Comment by TBrozovich** [comment]
Sorry I am getting back to this late but when I change the keys on Aurora the colors change but it does not change the keyboard. So the colors are stuck to whatever was last loaded on the Logitech software just as it was before the SDK support. Do you have any suggestions to get the G-keys working? Thanks for everything!
