### ISSUE TITLE
Can't get Warframe Chroma effects with Logitech keyboard G513

### ISSUE THREAD

**Issue by TheWyvern13** [antonpup/Aurora#1731]
### Expected Behaviour
Warframe Chroma Effects

### Actual Behaviour
No effects

### Reproduction steps
Install Aurora v0.7.0-rc2
Activate Logitech and Razer support
Test Logitech support works (in my case it works for Diablo 3, The Witcher 3 for example)
Launch Warframe
No Chroma effects :(

### Frequency
Every time

### Aurora Version:
v0.7.0-rc2

### Previously an Issue?
Don't know

**Comment by Wibble199** [comment]
Are you using the new Razer Chroma Layer for this? I'm not certain how Warframe loads and verifies the lighting code library, however if it is like the recent Overwatch changes, we are no longer able to replace the DLL without our own "wrapper" because it detects that it is not an official one and refuses to load. Not all Razer Chroma-supported games validate the DLL.

Please try the following instructions to use the new method of getting the Razer lighting which does not use the wrapper DLL, as this may be the issue with the lighting.

> 1. Make sure you're running build v0.7.0 or above
> 2. Open settings, go to the Devices and wrappers tab
> 3. Click the sub-tab Razer
> 4. Check if the supported version of the chroma sdk is installed and connected successfully
>     4a: If it is, the text should be green and you can proceed,
>     4b: If it's not, click the Install button, wait for it to finish and then restart Aurora
>     4c: When Aurora starts up again, the Connection text should now say Success and turn Green.
> 5. Click the profile of the game you want chroma lighting to be visible on (icons on the left side of the window)
> 6. Add a "Razer Chroma Layer" to the top of the layer list
> 7. Open the game, and make sure it's working!
> 
> Troubleshooting:
> 1. Aurora shows the sdk as being Connected (in devices and settings) and the razer layer still doesn't work!
>     A: If you've patched the game using aurora's "Apply wrapper patch" button, you need to delete the two dll's Aurora places in the game directory:
>         - RzChromaSDK.dll and RzChromaSDK64.dll
> 2. The colors are too dim
>     A: Open the Razer Chroma Layer of the profile you want to change, then tick the "Enable Color Post Process" checkbox and adjust the sliders as you want.
> 3. I can't find some of the options or menus mentioned
>     A: You most likely don't have the correct build from step 1.

**Comment by TheWyvern13** [comment]
Ok thanx I'll try! However I can't find Warframe profile... can I create a custom profile, referencing Warframe .exe file? Thanx!

**Comment by Wibble199** [comment]
Yes that should work.

**Comment by LightShaft** [comment]
Works perfectly, thanks for the mini tutorial

**Comment by TheWyvern13** [comment]
Ok it works!!!
