### ISSUE TITLE
I would like to be helping with the profiles

### ISSUE THREAD

**Issue by RBalconi** [antonpup/Aurora#1738]
Hey,
How can I integrate with other games? It's possible? I would like to be helping with profile for other games, because I am a programmer I think I can contribute.

Thanks.

**Comment by Wibble199** [comment]
The best way of contributing is to look at past pull requests that add support for games to see what was changed.

Please also read the following to understand what sort of games can be supported.

> To be able to add game state support for a particular game there needs to be a way of reading the values from the game. This can be done in one of several ways:
> 
>   1. Sometimes the game itself makes the relevant variables available (e.g. CSGO, Dota 2). This is quite uncommon and your requested game probably won't do this.
>   2. Another option is mod support. Depending on the level of support, we may be able to make a custom mod that gets useful variables and sends them (via HTTP request) to Aurora (e.g. Minecraft, Subnautica).
>   3. We may be able to read values from the game itself using memory reading. This SHOULD NOT BE DONE FOR MULTIPLAYER GAMES or games with anti-cheat as memory reading can be used by cheats to give players an advantage, and so many anti-cheat systems will flag you if memory reading is detected.
>   4. If the game already has support for lighting (e.g. it natively supports Razer Chroma) you may be able to patch the game and use the wrapper layer on Aurora to get the values from the existing system. This does not always work as sometimes games will not load modified DLLs. For this to work, we do not need to add anything special and you do not need to make an issue.
