### ISSUE TITLE
Aurora 0.5.1d can't connect Corsair keyboard

### ISSUE THREAD

**Issue by brainbug89** [antonpup/Aurora#174]
Aurora can't connect Corsair K70 RGB Rapidfire device after updating Aurora  from 0.5.1a to 0.5.1d.

SDK at CUE2 is enabled and still working for other third party applications.

Part of the log:
`[ERROR] 08.10.2016 19:38:04: Logitech LED SDK could not be initialized. (LogiLedSetTargetDevice or LogiLedSaveCurrentLighting failed)
[INFO] 08.10.2016 19:38:04: Device, Logitech, was not initialized
[ERROR] 08.10.2016 19:38:04: Corsair device, Exception! Message:System.TypeInitializationException: Der Typeninitialisierer für "CUE.NET.Native._CUESDK" hat eine Ausnahme verursacht. ---> System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: ptr
   bei System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
   bei CUE.NET.Native._CUESDK.LoadCUESDK()
   bei CUE.NET.Native._CUESDK..cctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei CUE.NET.Native._CUESDK.CorsairPerformProtocolHandshake()
   bei CUE.NET.CueSDK.Initialize(Boolean exclusiveAccess)
   bei Aurora.Devices.Corsair.CorsairDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Corsair\CorsairDevice.cs:Zeile 67.
[INFO] 08.10.2016 19:38:04: Device, Corsair, was not initialized
[INFO] 08.10.2016 19:38:04: No Chroma SDK available
[ERROR] 08.10.2016 19:38:04: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   bei Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:Zeile 50.
[INFO] 08.10.2016 19:38:04: Device, Razer, was not initialized`

**Comment by Exokao** [comment]
No problem on my side, with a similar configuration :
- Corsair K65 RGB RapidFire (Azerty/French version)
- CUE2 v2.4.66
- Aurora 0.5.1a -> 0.5.1D

Try to update CU2, maybe ?

**Comment by brainbug89** [comment]
CUE 2.5.63 installed

**Comment by brainbug89** [comment]
MSVCP140.dll was missing so I reinstalled Visual C++ Redistributable Packages for Visual Studio 2015 and everything works fine.
