### ISSUE TITLE
Support for Corsair Strafe MK.2

### ISSUE THREAD

**Issue by Jordonbc** [antonpup/Aurora#1744]
Please add support for the following device:

**Device Name:** Corsair STRAFE MK.2

**Device Website:** https://www.corsair.com/us/en/Categories/Products/Gaming-Keyboards/RGB-Mechanical-Gaming-Keyboards/STRAFE-RGB-MK-2/p/CH-9104110-NA

The "Corsair - STRAFE" keyboard that's already in Aurora works but there's no support for the logo, media and the right Win keys.

![Annotation 2019-10-04 201101](https://user-images.githubusercontent.com/16258926/66233387-25f09800-e6e3-11e9-9e92-86c2216a5670.jpg)

**Comment by Gurjot95** [comment]
Corsair SDK doesn't support these keys therefore there is nothing we can do as of now.
