### ISSUE TITLE
Ambilight coordinates not remembered

### ISSUE THREAD

**Issue by Marte2007** [antonpup/Aurora#1745]
### Expected Behaviour
When using an ambilight layer in coordinates mode, coordinates get remembered.

### Actual Behaviour
Coordinates Y, W and H reset after each restart. X is loaded correctly.

### Reproduction steps
- Create an ambilight layer, set it to coordinates mode.
- Set X, Y, W, H.
![before](https://user-images.githubusercontent.com/1051155/66255540-ebd7d280-e784-11e9-8796-9c3b719682d3.png)
- Close the program. At this point, the coordinates are stored in the profile .ini correctly.
![profile](https://user-images.githubusercontent.com/1051155/66255542-fa25ee80-e784-11e9-8788-2d370bd4274b.png)
- Reopen the program. The ambilight layer is still working.
- Click on the layer: the coordinates Y, W and H reset to 0, and you can see in the keyboard preview that the layer stops working.
![after](https://user-images.githubusercontent.com/1051155/66255555-20e42500-e785-11e9-8fde-fd4a69cc5a67.png)

### Frequency
Always occurring, according to my tests.

### Aurora Version:
v0.7.0-725 from Appveyor

### Previously an Issue?
AFAIK, the bug is present since the introduction of the coordinate mode.

### Notes
My Windows locale has "," as decimal separator and ";" as field delimiter. Maybe this is related?
I also checked the logs, nothing related to this problem.

**Comment by diogotr7** [comment]
Thanks for reporting, just fixed it. :)
