### ISSUE TITLE
Patch Logitec LED sdk problem

### ISSUE THREAD

**Issue by Myrthrac** [antonpup/Aurora#175]
![error](https://cloud.githubusercontent.com/assets/22716532/19215608/d95a2020-8da2-11e6-8f1e-e547bcdaca14.PNG)

Operation System: Windows 7 Ultimate
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.1.7601 Service Pack 1
System Directory: G:\Windows\system32
Processor Count: 8
User DomainName: -
User Name: -
SystemPageSize: 4096
Version: 4.0.30319.42000

I assume that the problem has to do with the fact that my main drive is G: not C:
Is there anyway to change the path Aurora searches for the Logitec SDK ?

**Comment by antonpup** [comment]
Umm.. I am assuming you do not own a Logitech device. Create "C:\Program Files\Logitech Gaming Software\SDK\LED\x86" and "C:\Program Files\Logitech Gaming Software\SDK\LED\x64" paths. And then try patching again.

**Comment by Myrthrac** [comment]
I do own a Logitech Device but the Path to the SDK would be:  G:\Program Files\Logitech Gaming Software\SDK\LED\x64

**Comment by antonpup** [comment]
Yeah. Aurora is hardcoded to C:/ I will adjust this so it looks for the windows-installed drive. But creating the directories for those paths on C should work.

**Comment by Myrthrac** [comment]
This Worked thank you for your swift response
