### ISSUE TITLE
HP Omen dc0051nr Keyboard Support 

### ISSUE THREAD

**Issue by Colton-Morrill** [antonpup/Aurora#1751]
Is it possible to get the HP Omen DC0051NR Keyboard supported in this program?

**Comment by diogotr7** [comment]
Which software do you use to change its lights?

**Comment by Colton-Morrill** [comment]
It is normally controlled through the OMEN Command Center

**Comment by diogotr7** [comment]
I couldn't find any way of interfacing with the lights on that keyboard as HP doesnt offer an SDK for use to use, so i'm afraid we can't support it.
