### ISSUE TITLE
Corsair K95 - Platinum. G6 - G3 keys are not controlled by Aurora, but ICUE instead

### ISSUE THREAD

**Issue by DenisPodberiozkin** [antonpup/Aurora#1762]
### Expected Behaviour
When I user Aurora, original Corsair ICUE software shall not affect light effects in any way, but G keys from 6 to 3 are controlled by ICUE rather than Aurora

### Actual Behaviour
Basically, when I assign any colour to any of the G6 - G3 keys using Aurora, it's overlapped by colour set up in the Corsair ICUE software. If no colour is set up in the ICUE, then no colour, applied in Aurora, appears at all.

### Reproduction steps

1. Set up any colour on G keys Using ICUE
2. Launch Aurora and setup another colour on the same G keys
3. You can see that colour set up in the ICUE is over the colour set up in the Aurora

### Frequency
Every time

### Aurora Version:
beta v0.7.0

### Previously an Issue?
No

![ICUE_No_Colour](https://user-images.githubusercontent.com/32970818/67117611-0a08ee00-f1db-11e9-8540-c4040e943785.png)
![Aurora_Orange](https://user-images.githubusercontent.com/32970818/67117612-0a08ee00-f1db-11e9-88d6-174ceffb5725.png)
![K95_Orange](https://user-images.githubusercontent.com/32970818/67117627-12f9bf80-f1db-11e9-9569-e98f8f733b01.jpg)
![ICUE_Red](https://user-images.githubusercontent.com/32970818/67117613-0a08ee00-f1db-11e9-8f2b-0d7b9d012c2c.png)
![K95_Orange_And_Red](https://user-images.githubusercontent.com/32970818/67117628-13925600-f1db-11e9-813d-7ac40aa15c30.jpg)

**Comment by diogotr7** [comment]
You might have an outdated version of iCUE, that bug was fixed on aurora's side a while ago. please check that iCUE is up to date

**Comment by DenisPodberiozkin** [comment]
Thanks, that was the case!
