### ISSUE TITLE
Backlash key on corsair strafe missing from layout, causing it to stay the default colour from icue software

### ISSUE THREAD

**Issue by Ryan-Arends** [antonpup/Aurora#1763]
### Expected Behaviour
Should be able to program the colour of the backslah key

### Actual Behaviour
No way to pragram the backslah key as it is missing from the layout

### Aurora Version:
v7

### Previously an Issue?
no

**Comment by diogotr7** [comment]
Check that you have the correct layout selected in the settings (us, uk, etc) . If it is set to automatic try choosing it manually

**Comment by Ryan-Arends** [comment]
> Check that you have the correct layout selected in the settings (us, uk, etc) . If it is set to automatic try choosing it manually

Thank you! that worked! changed to manual!
