### ISSUE TITLE
Support for online profiles

### ISSUE THREAD

**Issue by jdubnz** [antonpup/Aurora#178]
Not an issue, just a possible enhancement. (or I'm just incompetent) 

Is there any way to provide support for a profile found online? SO we can download Razer, Corsair, logitech profiles etc...

Eg. If I found a corsair profile for Witcher 3, is there a way of making that work with Aurora on a Logitech keyboard? That would greatly increase the number of games that the keyboard can respond to in-game events.

**Comment by antonpup** [comment]
At the moment, no. It is planned to convert proprietary profiles to Aurora profile. But it isn't a priority at the moment.

**Comment by jdubnz** [comment]
Awesome, cheers for the quick feedback. Keep up the good work. And let me know if you need help with RL pointers again :)

**Comment by brainbug89** [comment]
> That would greatly increase the number of games that the keyboard can respond to in-game events.

How that?

**Comment by the27club** [comment]
i second this!

**Comment by Pandry** [comment]
A server should be used, so...
It would cost some money, at least if the server is not gifted...

**Comment by simon-wh** [comment]
Duplicate of #429
