### ISSUE TITLE
G903 RGB goes out of sync with keyboard/mousepad after a while

### ISSUE THREAD

**Issue by elie195** [antonpup/Aurora#1786]
### Expected Behaviour
Profile shouldn't crash/stop working after a certain amount of time. RGB of mouse/keyboard/mousepad should stay in sync

### Actual Behaviour
After some time (~~maybe 1 hour~~ just happened in 25 minutes or less), the RGB on the mouse (G903) goes out of sync with the keyboard/mousepad RGB (which are using an Aurora profile). **After restarting "Logitech" in the device manager tab, the mouse gets in sync with the keyboard/mousepad again.**

### Reproduction steps
- Recently replaced mouse (G903) that pairs to mousepad (POWERPLAY)
- Replacement mouse wasn't recognized by Logitech Gaming Software (tried reinstalling LGS as a troubleshooting step), so I installed G HUB, which sees the mouse and I see that Aurora is using the G HUB DLL now, according to the logs.
- Everything works, except the mouse starts its own flashing pattern instead of being in sync with the mousepad/keyboard
- It just takes some time (~~probably around an hour~~ 25 minutes or less)
- State stays the same until "Logitech" in device manager in Aurora is restarted (stop/start). It is _not_ stopped when the mouse goes into this out-of-sync state, and the keyboard and mousepad RGBs are still in sync and using the chosen Aurora profile

### Frequency
Every time

### Aurora Version:
0.7.0

### Previously an Issue?
No, mouse would never go out of sync with the other two devices.
[2019-11-08 12.45.08.log](https://github.com/antonpup/Aurora/files/3826923/2019-11-08.12.45.08.log)

EDIT: takes 25 minutes or less until the sync stops working, not 1 hour+ like initially mentioned.

**Comment by kathampy** [comment]
For me the PowerPlay mouse pad goes out of sync, while the G815 and G903 remain in sync.

**Comment by elie195** [comment]
This is looking more and more like an issue with G HUB. I'm pretty sure I saw a notification that said "Device DPI now set to 1600" right around when the mouse RGB went out of sync. 

The notification pops up normally when G HUB starts, so it looks like some G HUB related service crashed, which then affects Aurora. G HUB in general seems pretty buggy.

**Comment by diogotr7** [comment]
I suspect this is a g hub issue as well. I keep the led on my g900 off anyway because of battery, so it doesn't affect me.
