### ISSUE TITLE
Logitech G502 Proteus Spectrum RGB Lighting issue

### ISSUE THREAD

**Issue by Ve1orum** [antonpup/Aurora#1787]
After using Aurora app RGB backlight on my Logitech g502 stop working right. Shades of colors on DPI and LOGO have differences when i choose one basic color in LGS.
I try to explain how this is actually looks and take a photo: 
https://drive.google.com/open?id=1o1P7Ky181MU5ALr14tFBR17fwQiCPzbG
https://drive.google.com/open?id=17y3C86rD1mLMfaRVmcTsLLoJutnioYqR
Screenshot of Logitech game software:
https://drive.google.com/open?id=1sry6CZqHywnGQ0XO0GEgHNpsvo914RQr
https://drive.google.com/open?id=1GhYRmEa1fbIAV1Jy96fVE_F9a8pEaQnM
Any ideas what can i do with it? Maybe hard reset of g502 hardware or something?

**Comment by diogotr7** [comment]
It seems like your blue led is failing. Try setting the color to blue (0,0,255) and see what lights up

**Comment by Ve1orum** [comment]
> 
> 
> It seems like your blue led is failing. Try setting the color to blue (0,0,255) and see what lights up
Dpi and logo colors looks the same but Dpi is brighter 
https://drive.google.com/open?id=1wNVJ3BK0dd978JConzAX6Ro2kD312EgT

**Comment by diogotr7** [comment]
It seems like your blue led on the G logo is less bright somehow? If you set it to red or green do they look the same?

**Comment by Ve1orum** [comment]
>If you set it to red or green do they look the same?
Yes, look the same

**Comment by diogotr7** [comment]
yeah, then it's a hardware problem with the blue led i think. if it's still under warranty try that :/
