### ISSUE TITLE
Add a blacklist to desktop profile

### ISSUE THREAD

**Issue by TomW1605** [antonpup/Aurora#1788]
Would it be posable to add a program blacklist to the desktop profile? This would automatically turn off the profile when a blacklisted program is active. This would allow for games that are not supported by Aurora but that have lighting configured in the standard apps without having to manually turn it off.

Sorry if this has already been requested

**Comment by Bluscream** [comment]
Just add a new profile for those apps and keep it empty

**Comment by diogotr7** [comment]
This is what excluded processses in general settings does.

**Comment by TomW1605** [comment]
unfortunatly an empty profile just resaults in all the lights being off not what i have set in LGS.

the excluded processes settings is exactaley what i need however there is a problem where LGS link isent restarted when i leave the excluded process. the only way to get the desktop process working again is to go to the settings and manualey press start on logitech under the device wrappers tab.

i think it is somthing i shuld make another issue about but just wanted to say it here as well.
