### ISSUE TITLE
Rise of the Tomb Raider support

### ISSUE THREAD

**Issue by medifin** [antonpup/Aurora#179]
It has lighting effects for Razer devices, would it be possible to make them work on logitech devices as well?

**Comment by brainbug89** [comment]
Maybe try the Razer Wrapper Patch :wink:

**Comment by sym5** [comment]
I tried this, It didn't work :-(

**Comment by avaplaya13** [comment]
How do you download the razer patch? I'm really wanting to use the H1Z1 and RotTR effects

**Comment by antonpup** [comment]
It doesn't work with H1Z1 due to their anti-cheat. The game simply doesn't load the wrapper.

**Comment by avaplaya13** [comment]
Damn. Well then how do I install it anyways for the RotTR?

**Comment by antonpup** [comment]
Go into settings, then open the "Devices & Wrappers" tab, in there you will find "Install Aurora Patch for Razer", and all other ones. Like so:
![]((https://puu.sh/rSpkJ/d27f6db88e.png))

**Comment by medifin** [comment]
I installed the patch and tried to enable it from the settings ingame but nothing happens.

**Comment by Dagda52** [comment]
it worked for me

**Comment by diogotr7** [comment]
@Dagda52 how did you get it to work? Are you on the dev version?

**Comment by Dagda52** [comment]
nope, i'm currently using the official 0.6.0b, i just installed the wrappers dll's near the executable, other thing you can try i founf this dll's works if you put them in windows/system32 and windows/syswow64, doing that you can patch them globally, and no need to put them in every game.

**Comment by Dagda52** [comment]
dont forget to enable effects in game http://steamcommunity.com/sharedfiles/filedetails/?id=1093395217

**Comment by diogotr7** [comment]
I just solved the problem. I added a profile for the .exe and that made it not work, once I deleted it it started working as it should.

**Comment by diogotr7** [comment]
I tested this again with v0.6.1-dev3 and the game crashes right before the main screen if I leave the dlls on the folder. If I remove them it works fine.

The game seems to recognize the devices but crashes right after.

Aurora logs: https://pastebin.com/Cn0UDnmu

RotTR log: https://pastebin.com/EFVn81SD

I have not created a profile for the game and am using the g810 and  g502.

**Comment by sym5** [comment]
Same as diogotr7, the dev3 breaks ROTTR & lighting effects for said game, mine totally locks up & I have to restart my pc in order to get back to desktop.
I once got the game to load but the keyboard animation was stuck with just a column of keys lit.

**Comment by diogotr7** [comment]
I don't have to restart my PC, I can call task manager but the keyboard stuck with one colunn of keys lit happens here too

**Comment by simon-wh** [comment]
Could you try the recent developer version and see which is the first version that introduces the issue?

**Comment by diogotr7** [comment]
I tried and the first version that seems to introduce the game crash/hang  is 0.6.1-dev. Earlier versions didn't display lightning at all and the game worked. This version Makes the screen go black.

Log: https://pastebin.com/h9pFy8yL

**Comment by simon-wh** [comment]
@diogotr7 Could you try [this build] and tell me how it goes? I've made it so it'll log the gamestate it received which caused it to error out in your previous dev3 build so make sure to include the log file as well.

**Comment by diogotr7** [comment]
I deleted the %appdata% Aurora folder and ran the exe. The Logitech first time intro appears and then I get this 
http://i.imgur.com/6xeuIBx.jpg
I ran it from my desktop, is that a problem?

**Comment by simon-wh** [comment]
@diogotr7 Try [this build](https://www.dropbox.com/s/zhnf1uarc1o54uk/v0.6.1-dev3%20tr%20test2.zip?dl=0) (it should be uploaded in a few mins)

**Comment by diogotr7** [comment]
@simon-wh  I jkust tried it and

**Comment by diogotr7** [comment]
@simon-wh I just tried it and it seemed to work without any problems, as long as I don't create a profile for it. Orange wave across keyboard while loading, movement keys orange and turn white while pressed, whole keyboard flashes red when low hp and damage taken.
Log without profile: https://pastebin.com/wXvXjrQp

Log with profile: https://pastebin.com/JC2BxGTk  (that error keeps appearing for ~2500 lines across 15 seconds)

**Comment by simon-wh** [comment]
@diogotr7 Is there nothing after the Pipe Created line on the log without the profile? Before the log you had with v0.6.1-dev3 showed an error which caused it to stop working and I was hoping to be able to catch to try and narrow it down.

**Comment by diogotr7** [comment]
I just did it again and the log looks just like that one : 
v0.6.1-dev3 tr test2 : https://pastebin.com/4NBpjKwi

I tested again with the most recent version and I found that it doesn't make the game crash every time. Sometimes it just stops updating the lightning and just lights up the G logo on both the keyboard and mouse.
Here's a Log (I opened and closed the game twice and it didn't crash.) https://pastebin.com/a0AayKUL

**Comment by simon-wh** [comment]
Can you try and get the error from dev3 to occur when using dev3 tr test2?

**Comment by diogotr7** [comment]
@simon-wh I tried running the game as admin, without the launcher, restarted my computer and unfortunately i wasn't able to get the error using the test2 version. It always just worked straight away.

The one thing I noticed is that the older version crashes/freezes/stops updating lightning when it gets to the main menu. In the working version, this is when the game displays the following keys as orange:

WASD, ESC, LSHIFT, Space, Enter, PGUP and PGDOWN, and the arrow keys. The G logos both turn off at this point. 

Once the gameplay starts it lights up a couple more keys like QERFV, and turns off the arrow and pgup and pgdown keys. Again, I don't think this makes a difference, but might as well say it.

**Comment by simon-wh** [comment]
With the log from dev3 it seems like it errors due to it erroring out on a malformed payload and it doesn't close the connection with the game causing it to freeze. Maybe there was a change since dev3 that stopped that issue from happening.

**Comment by simon-wh** [comment]
@diogotr7 What's the name of the rotr exe? I'm planning to add a profile for it so you can customize it better.

**Comment by diogotr7** [comment]
@simon-wh I just tried it and it worked very well  I can apply new layers and the display as they should, without affecting the game's lightning. 

I applied the razer patch( both dll's) from the aurora settings to the same directory as ROTTR.exe is in, and I didn't delete/replace/reapply the patch at any point. 

Also, I do not have the files in system32 or syswow64, as was referred earlier in the issue.

Other thing I noticed is that the Overview tab says "Worms W.M.D." where it should say rottr.

The color enhancing didn't seem to have any effect, but I believe it's not needed anyways,

**Comment by simon-wh** [comment]
@diogotr7 I've corrected the Overview text to have the right game title (I just copy paste similar applications). Seeing as you've got it working by putting it in the standard location for wrappers for a game then I don't need to make any changes. I'll close this issue as it seems like it has been sorted. Thanks for all the help! Could you see if your log has the error that was coming up in a few of them? I made some changes that hopefully fixed it.

**Comment by diogotr7** [comment]
@simon-wh The log does not have that error. Glad to help!
