### ISSUE TITLE
Timer Reset not stopping Timer

### ISSUE THREAD

**Issue by fluorescentb** [antonpup/Aurora#1798]
### Actual Behaviour
When the repeat action is set to `Reset` on the timer layer effect, the timer resets to 0, but doesn't actually stop counting. This means to cancel a timer you have to remove and copy back in the layer.

### Reproduction steps
Create a timer layer and set the Repeat action to Reset.

### Frequency
Every time the timer is run.

### Aurora Version:
0.7.1

### Previously an Issue?
Don't Know

**Comment by Wibble199** [comment]
This is not a bug, it is the intentional behaviour for the reset mode.

A new option that cancels the timer when the trigger has been pressed has been PRed.
