### ISSUE TITLE
Add support for Blade and Soul

### ISSUE THREAD

**Issue by brainbug89** [antonpup/Aurora#180]
Seems like Blade and Soul has Razer Chroma support: https://youtu.be/kqytjCyUoVs

Should be working with Razer Wrapper Patch...

**Comment by brainbug89** [comment]
All these games: http://www.razerzone.com/chroma-workshop/#chroma-games should be supported by Aurora, right?

**Comment by antonpup** [comment]
Theoretically, yes.

**Comment by brainbug89** [comment]
@DeathAngel thanks for adding support for Blade and Soul. :+1:
