### ISSUE TITLE
RGB NET integrations don't handle alpha correctly

### ISSUE THREAD

**Issue by Rechinan** [antonpup/Aurora#1813]
### Expected Behaviour

Global brightness level changes.
### Actual Behaviour

Slider in Aurora adjusts but no change on devices
### Reproduction steps

Adjust slider or hold ALT and move volume wheel. No change in visible brightness
### Frequency

All the time
### Aurora Version:

beta 0.7.1
### Previously an Issue?

No, this is recent. I'd like to add this is on corsair and asus devices

**Comment by Rechinan** [comment]
[2019-11-24 13.52.08.log](https://github.com/antonpup/Aurora/files/3883684/2019-11-24.13.52.08.log)

**Comment by diogotr7** [comment]
Fixed with #1815
