### ISSUE TITLE
bleeding edge failed vulcan aimo 120

### ISSUE THREAD

**Issue by thecichos** [antonpup/Aurora#1817]
i pressed start (by the vulcan) and then disable (by the vulcan) and it gave me this message

![billede](https://user-images.githubusercontent.com/15047629/69645799-09c80200-1067-11ea-8377-59a72d6b0815.png)

**Comment by diogotr7** [comment]
I fixed this bug in PR #1800 , it should be merged soon

**Comment by diogotr7** [comment]
Please test the newest dev build here: https://ci.appveyor.com/project/antonpup/aurora/branch/dev/artifacts

**Comment by thecichos** [comment]
Working like a treat 😃
