### ISSUE TITLE
Aurora GUI and tray application no longer working

### ISSUE THREAD

**Issue by OttoWerse** [antonpup/Aurora#1819]
### Expected Behaviour
Aurora should open when clicking on the app icon.

### Actual Behaviour
Aurora.exe shows up in task manager, but the window does not open and there is no tray application running. (the tray icon shows up for a split second but vanishes as soon as I hover over it)

### Reproduction steps
Double click on aurora.exe

### Frequency
Every time I try to run Aurora, even after multiple reboots (soft and hard) and restarts of the program (I haven't tried uninstalling yet)

### Aurora Version:
I don't know for sure, as I can't look it up in the GUI, the EXE-File is version 0.7.1.0.
When I run AuroraUpdater.exe, it just tells me I am on the latest version.

### Previously an Issue?
No, this only started happening today

### Recent changes to my system:
Updated Logitech G Hub to the latest version (forced by Logitech)
Updated Razer Synapse to the latest version (because the old version stopped working with Aurora)
Installed the Elgato StreamDeck Application

### Used SDKs:
Logitech G Hub
Razer Synapse/Chroma Studio
Corsair iCUE
SteelSeries Engine 3
Asus Aura

I already tried quitting all of my SDK integration programs, but that didn't change the observable behaviour for me.

**Comment by diogotr7** [comment]
This was caused by the latest G HUB update and can be solved by copying `sdk_legacy_led_x64.dll` from GHUB's executing directory and placing it in Aurora_executing_directory/Logi/LGHUB, renaming it LogitechLed.dll, replacing the one already there. I've updated it in a pull request and should be released soon.

**Comment by le0dime** [comment]
The answer provided by @diogotr7 actually works

> This was caused by the latest G HUB update and can be solved by copying sdk_legacy_led_x64.dll from GHUB's executing directory and placing it in Aurora_executing_directory/Logi/LGHUB, renaming it LogitechLed.dll, replacing the one already there. I've updated it in a pull request and should be released soon.

But, the directory inside aurora is `Aurora_executing_directory/Logi/GHUB`, not `LGHUB` (it should exist already).

**Comment by diogotr7** [comment]
That is correct, the directory should be GHUB.

**Comment by diogotr7** [comment]
This issue was fixed witn  v0.7.2
