### ISSUE TITLE
Can't patch CSGO

### ISSUE THREAD

**Issue by Carlolmg** [antonpup/Aurora#182]
Can't patch CSGO because it says the game is not installed so I cant install the GSI config file

**Comment by simon-wh** [comment]
Are you sure you have CS:GO installed? If so, where do you have it installed relative to your steam library? Additionally, do you have a non-standard Steam install? If Steam is not installed correctly it could cause issues with the Steam game detection we have.

**Comment by Carlolmg** [comment]
I do have CS:GO installed and it is downloaded from steam

**Comment by antonpup** [comment]
Any updates on this issue?
