### ISSUE TITLE
Aurora Working Only While on Foreground (Logitech G Hub)

### ISSUE THREAD

**Issue by Bennzon** [antonpup/Aurora#1821]
### Expected Behaviour
Aurora should continue working when minimized

### Actual Behaviour
Aurora will stop working and Logitech G Hub will take control of the RGB Lights

### Reproduction steps
1.Boot
2.Open G Hub (Auto Start ON)
3.Open Aurora (Auto Start Off)
4. Minimize Aurora Window 

### Frequency
Every time I minimize the Aurora window or even If I click outside of it's window

### Aurora Version:
beta 0.7.1
Logitech G Hub Version: 2019.11.29288

### Previously an Issue?
Don't Know

Before this issue Aurora didn't open unless I turned off G Hub. This past issue was solved by following @diogotr7 advice in #1819 After `sdk_legacy_led_x64.dll ` was replaced, I can't use Aurora Profiles unless it is the foreground application. 
Thank You

**Comment by diogotr7** [comment]
Please check if G HUB has a profile for Aurora. This should not be the case for it to work properly. On my system, I have the desktop G HUB profile set as persistent and it seems to work.

**Comment by Bennzon** [comment]
I've managed to fix it. I reinstalled Logitech G Hub and now it works even without an Aurora Profile.
