### ISSUE TITLE
Project aurora doesn't work

### ISSUE THREAD

**Issue by Henriquim** [antonpup/Aurora#1824]
Hey, 
i use project aurora to control my rgb lights from my mouse and keyboard.
I use for a few months, but now, it didn't start, it show up at my task manager and don't open a window to control.
Please help me.

**Comment by Wibble199** [comment]
Do you use GHUB? If so, please read #1819

**Comment by Wibble199** [comment]
Do you use GHUB? If so, please read #1819

**Comment by diogotr7** [comment]
Fixed with v0.7.2
