### ISSUE TITLE
Improving CSGO Bomb Timer

### ISSUE THREAD

**Issue by trxraptor** [antonpup/Aurora#1850]
It would be great if there was a way to indicate how much time does the bomb have.
It takes 10 seconds to defuse a bomb without a defuser and 5 seconds with one.

There should be a layer that starts timing 40 seconds when the bomb is planted (turns to a certain color).
Turns to another certain color after 30 seconds (10 seconds left) so you know that you can't defuse it without a kit.
And turns to another certain color after 35 seconds (5 seconds left) so you know that you can't defuse and need to run.
After 40 seconds (the bomb goes boom), there can be the same effects as the current bomb layer for bomb primed and round winner.

Also, this layer shouldn't blink (at least it should have the option to not the blink) unlike the current Bomb layer.

I don't exactly know how the current Bomb Layer works, but you can do this by starting a 40 sec timer when Round/Bomb value switches to 1. or  starting a 30 sec timer, 35 sec timer and 40 sec timer when Round/Bomb value switches to 1 and make it so the color for each milestone is customizable etc...

WHAT I WANT IS:

(t = time in seconds) 
The bomb is planted (t = 0):
10 second left (t = 30)
5 seconds left (t = 35)
BOOM (t = 40)

for t < 0: OFF
for 0 < t < 30 --- Defusable w/o kit color
for 30 < t < 35 --- Defusable w/ kit color
for 35 < t < 40 --- Can't be defused color
for 40 < t < 41 --- Bomb primed color   //same logic as the current bomb layer
for 41 < t < (endOfRound) --- Round winner color   //same logic as the current bomb layer
(NOTE: for 40 =< t, this can be the same as the current bomb layer)

**Comment by stuntguy3000** [comment]
I'm working on improving the CS:GO layer to make it more better.

That being said, accurate bomb timers are **impossible**. Why? Valve introduced a random delay of a few seconds or so to fix cheats like this:
![image](https://user-images.githubusercontent.com/1522389/71452246-faa5b280-27d2-11ea-9f2b-996a8bd156f0.png)

This can't be done.

**Comment by trxraptor** [comment]
Do you know how much the delay is approximately? Is it greater than 1 sec? I mean if it is less than 1 second, this feature can still be helpful to some extent i think.

**Comment by stuntguy3000** [comment]
It is randomly up to 3 seconds in delay I believe, so implementing a feature which will **always** be incorrect isn't a good idea in my opinion.

**Comment by diogotr7** [comment]
Marking as Cant fix as the delay sent by the game isnt accurate.
