### ISSUE TITLE
Enum override does not work while using Dynamic value

### ISSUE THREAD

**Issue by gitmacer** [antonpup/Aurora#1853]
### Expected Behaviour

It should remember the selection
### Actual Behaviour

It is forgetting the sellection
![enum bug](https://user-images.githubusercontent.com/37345589/71450897-1f663f80-276b-11ea-88b5-27a19c0c0db9.gif)

You can use the lookup table as a Workaround.

### Reproduction steps

Sellect Dynamic value as override mode and add an enum state variable.
Switch between Overrides and value sellection is gone.

### Frequency
Every time

### Aurora Version:
0.7.2

### Previously an Issue?
Don't know

@Wibble199 maybe you can say something about it.

**Comment by stuntguy3000** [comment]
Can confirm same bug, was about to report it...

**Comment by gitmacer** [comment]
Fixed with #1972
