### ISSUE TITLE
Corsair K57 wireless Keyboard only works wired

### ISSUE THREAD

**Issue by UniCizin** [antonpup/Aurora#1856]
Latest stable version of Aurora
Latest stable version of icue (and drivers)

as long as i keep the keyboard plugged in, the lightning works as it should.
but as soon as i remove the cable and go to wireless mode
the lightning stops functioning  (not in icue, just aurora).

**Comment by diogotr7** [comment]
I think it would make sense for icue to handle that, but maybe Aurora needs to re establish the connection once you disconnect it... I'm working on an alternative method of integrating with icue so once that's done we'll see if it helps or not.

**Comment by UniCizin** [comment]
i guess Aurora cant establish a connection at all. 
when i start the app with the keyboard in wireless mode, i get no functionality. 
In the log i saw something like this
[INFO] 13:42:20: Device, Corsair, was shutdown

**Comment by UniCizin** [comment]
any news here? do you need more information?

**Comment by UniCizin** [comment]
short update ..
i saw that iCue updates the colors in the preview, but does not send it to the keyboard.
So i guess it's an icue error?

i attached the icue log (the part at the end is important.. because i fiddeld around in icue before)

![icueTest](https://user-images.githubusercontent.com/41308043/75658240-3728db00-5c68-11ea-8fe4-a655732a1d33.png)
[2020-03-02T08-57-53.log](https://github.com/antonpup/Aurora/files/4274226/2020-03-02T08-57-53.log)

**Comment by UniCizin** [comment]
can be closed. 
it's an issue with corsair sdk

![image](https://user-images.githubusercontent.com/41308043/79863184-963cdd80-83d7-11ea-9170-d24d77e4a33c.png)

**Comment by diogotr7** [comment]
Thanks for the information :)
