### ISSUE TITLE
Aurora.exe

### ISSUE THREAD

**Issue by cafk11** [antonpup/Aurora#186]
Nothing in that package called aurora.exe! so not easy to install!!!

**Comment by brainbug89** [comment]
Where do you found it?!

See here for download: https://github.com/antonpup/Aurora/releases

**Comment by cafk11** [comment]
I don't have it downloaded yet just found it right now and the instructions says that i should run aurora.exe but it aint in any if the files https://github.com/antonpup/Aurora

**Comment by antonpup** [comment]
Please download the latest release from here: https://github.com/antonpup/Aurora/releases/latest

**Comment by cafk11** [comment]
Works now thank you ;D
