### ISSUE TITLE
Aurora not letting iCue control desktop colors at all

### ISSUE THREAD

**Issue by leopupin** [antonpup/Aurora#1876]
### Expected Behaviour
When disabling Aurora to provide lighting to my K95 Plat, the keyboard assumes the colors patterns on the iCue profile that it's selected.

### Actual Behaviour
The keyborad simply goes dark and don't let iCue Control it's lighting on desktop or any unsuported (by Aurora) application at all

### Reproduction steps
Set any color profile for general at iCue, and start using
Open Aurora and uncheck "Enable Aurora to provide lighting effects to desktop"
Done!

### Frequency
Always

### Aurora Version:
Aurora 0.7.2 (latest stable)
iCue 3.23.66 (latest stable)

### Previously an Issue?
I don't know, since I had a try it always occured, so I would assume Yes

**Comment by diogotr7** [comment]
This is a bug with RGB.NET, not aurora. I've rewritten the corsair implementation in another branch without the use of RGB net and it works properly. A fix for this will come soon, not sure when as the dev team is currently busy with other things :S

**Comment by leopupin** [comment]
Really glad to hear it's fixable.
Is there any way I can get this branch before they release, I mean, if I compile this branch you're talking about I can fix it? Is it any of the ones on your profile?

**Comment by diogotr7** [comment]
That branch does a few things differently and does not support all of the devices that the current release version does. I would recommend you wait, but if you want to try it out, it's [here](https://ci.appveyor.com/project/diogotr7/aurora/builds/29898086/artifacts). Backup your settings from `%appdata%\Aurora` first!

**Comment by leopupin** [comment]
Oh cool, will give a try, thank you for patience and time =)

**Comment by Chase-san** [comment]
@diogotr7 Is there any news on this? I am having the same issue with the latest version of Aurora.

**Comment by kathampy** [comment]
Please reopen this issue.

**Comment by diogotr7** [comment]
This has been fixed in the development versions
