### ISSUE TITLE
Cannot start Aurora

### ISSUE THREAD

**Issue by NomisIV** [antonpup/Aurora#1877]
### Expected Behaviour

Aurora launches after installation

### Actual Behaviour

After launching the latest Aurora, the program shows up as a background processes in task manager for about five seconds, then it disappears. I have tried starting it as an administrator, but it too did not work.

### Reproduction steps

Install and Launch Aurora (v0.7.2)

### Frequency

Always

### Aurora Version:

Latest (v0.7.2)

### Previously an Issue?

I tried to install an earlier version (v0.7.0), and it started updating to the latest version. After updating, it once again did not start.

**EDIT:** [Latest log file](https://pastebin.com/JmNZ0SNv)

**Comment by diogotr7** [comment]
Do you have asus hardware and asus aura installed?

**Comment by NomisIV** [comment]
Indeed I do. I have an ASUS motherboard, and installed AURA to control the RGB. I have also got iCUE installed for my RAM modules.

**Comment by diogotr7** [comment]
Try adding this: 
`"Aurora.Devices.Asus.AsusDevice, Aurora, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"`
to the config file at `%appdata%\Aurora\Config.json` under `devices_disabled`.

**Comment by NomisIV** [comment]
That just worked! Thank you!
