### ISSUE TITLE
Logitech G910, Aurora won't control G keys, logo and 910 badge

### ISSUE THREAD

**Issue by DannyRoman86** [antonpup/Aurora#1878]
Hello, everyone. As the title says, Aurora cannot seem to override the colors of the G-keys, the logo and the 910 badge. Maybe there's a setting I am missing, I don't know. It used to work and I think it's related to the last  LGS update, not entirely sure. Any help will be appreciated, thank you!

### Expected Behaviour
Aurora should control G-keys, logo and badge aswell.

### Actual Behaviour
Aurora doesn't control G-keys, logo and badge.

### Frequency
All the time.

### Aurora Version:
v0.7.2 (latest)

### Logitech Gaming Software Version:
v8.82.151 (latest)

### Previously an Issue?
No

**Comment by diogotr7** [comment]
the latest version of lgs is 9.02 from here: https://download01.logi.com/web/ftp/pub/techsupport/gaming/LGS_9.02.65_x64_Logitech.exe

**Comment by DannyRoman86** [comment]
> the latest version of lgs is 9.02 from here: https://download01.logi.com/web/ftp/pub/techsupport/gaming/LGS_9.02.65_x64_Logitech.exe

I didn't even notice LGS had an update. This was a two weeks old problem which I just remembered and said i'd try solving in here, checked for a Aurora update but didn't check for a LGS update, my bad. Thank you very much, the update solved my problem. Have a great day!

**Comment by diogotr7** [comment]
That link is pretty buried in logitechs support page... glad it fixed it

**Comment by DannyRoman86** [comment]
Well, I just updated through LGS itself and I got the same version, so it is easier to find updates. Glad it fiexd it too, I LOVE Aurora, it is way better than LGS. Once again, thank you for the help.
