### ISSUE TITLE
Aurora Start but Not Work, but Work after Close & Restart the .exe

### ISSUE THREAD

**Issue by WhiteWidowFR** [antonpup/Aurora#1879]
\Aurora\Logs Folder Not finded in the Directory.

### Expected Behaviour
Aurora Start but Not Work, but Work after Close & Restart the .exe

### Actual Behaviour
Aurora Start but Not Work, but Work after Close & Restart the .exe

### Reproduction steps
Launch the computer, see the Aurora launching & seems working... but no ^^"
After the closing & restarting the Aurora's launcher it's ok :)

### Frequency
Every time

### Aurora Version:
0.7.2

### Previously an Issue?
i don't remember if i had this problem on 0.7.1

### My Software & System
Logitech GHub 2019.11.29288
Windows 10 last update

**Comment by PixelHir** [comment]
in my case it happens randomly, the app sometimes just hangs in background

**Comment by diogotr7** [comment]
Do you have Asus Aura or NZXT hardware?

**Comment by WhiteWidowFR** [comment]
> Do you have Asus Aura or NZXT hardware?

I dont have any NZXT Hardware, i seen all topics about it but im not concerned

& Now, i think Aurora doesnt Start (Before it Start but don't work properly)

But again, work perfectly after a Start/Restart

& For information, i'm not the only one, my best friend have the same Keyboard (Logitech G910) & have exactly the same probably.

We already made a quick macro to launch the software to don't loose time, not a big problem,
but if it will be resolved it can be really nice ;)

Thx all for your reply

**Comment by diogotr7** [comment]
Ah I see what you mean. G hub takes a while to start so you need to delay aurora by around 15 seconds at startup. You can increase the delay in the general settings.

**Comment by WhiteWidowFR** [comment]
Oh thank you! I will try!!
