### ISSUE TITLE
Razer logo not lighting up

### ISSUE THREAD

**Issue by MGThePro** [antonpup/Aurora#188]
Is there really no option to make the logo (in my case the razer logo) light up?

**Comment by antonpup** [comment]
Not with the current public version, no. I didn't include it because I was not able to find Razer users to test with. I've got a bunch of Logitech and Corsair users.

**Comment by exidez** [comment]
This is a small cosmetic issue I noticed as well. Any way I can help resolve this? If you point me where to look I can try and resolve it..?
