### ISSUE TITLE
Non-US Backslash and # doesn't lit up on German Keyboard Layout

### ISSUE THREAD

**Issue by SomaKhaos** [antonpup/Aurora#1888]
Hey, there so i have a German Keyboard Layout, and there is this <>| Key on my keyboard (see screenshot to see what i mean) right between the left shift and my Y-Key, which your Program referrs to as "Non-US Backslash". And this key won't lit no matter what i do. Not with assigning the key, and not with freestyle.

![Non-US Backslash](https://user-images.githubusercontent.com/5221216/72513958-1f2f0080-384e-11ea-9d08-09be2b664800.png)

### Expected Behaviour
"Non-US Backslash" should lit up

### Actual Behaviour
Nothing Happens
11ea-9ff1-8089c88ece9f.png)

### Frequency
Every Time, on every Profile

### Aurora Version:
beta v0.7.2

### Previously an Issue?
Don't Know

Log-Files:
[2020-01-15 00.39.33.log](https://github.com/antonpup/Aurora/files/4070436/2020-01-15.00.39.33.log)
[2020-01-15 00.46.46.log](https://github.com/antonpup/Aurora/files/4070437/2020-01-15.00.46.46.log)
[2020-01-15 00.49.41.log](https://github.com/antonpup/Aurora/files/4070438/2020-01-15.00.49.41.log)
[2020-01-15 09.13.09.log](https://github.com/antonpup/Aurora/files/4070439/2020-01-15.09.13.09.log)
[2020-01-16 09.52.11.log](https://github.com/antonpup/Aurora/files/4070440/2020-01-16.09.52.11.log)

**Comment by SomaKhaos** [comment]
Just saw the #-Key isn't working as well

**Comment by diogotr7** [comment]
Which model of keyboard is this?

**Comment by SomaKhaos** [comment]
i'm using a Roccat Vulcan. and in aurora i chose Roccat Ryos as Preferred Keyboard, because it's the closest to the Vulcan of the looks. Everything works fine with the Vulcan besides these two keys i mentioned

**Comment by diogotr7** [comment]
That makes sense. When I wrote the library to control that keyboard I couldn't find anyone with that model. Later today I'll make some changes and would appreciate it if you could test them.

**Comment by SomaKhaos** [comment]
So here you have someone now using that model :) 

Of course i can test them for you

**Comment by diogotr7** [comment]
[vulcan-iso-test.zip](https://github.com/antonpup/Aurora/files/4074276/vulcan-iso-test.zip)
Please test this program with aurora closed. It's supposed to set the keyboard to red, and the keys that do not light up currently to blue.

**Comment by SomaKhaos** [comment]
Ok so, your test program is working like you said.

And I'm on the Discord, whats your name there? same as here? Or where should i talk to you?
My Name on Discord is Same as here

**Comment by auratum** [comment]
Hey there,
i have the same issue with the german Vulcan.
The testfile works well, but i am not on Discord, so is there any solution so far?
Thank you

**Comment by diogotr7** [comment]
@auratum please test this build: https://ci.appveyor.com/project/antonpup/aurora/builds/30220733

**Comment by auratum** [comment]
@diogotr7 it works perfect!
Tank you 👍
