### ISSUE TITLE
Visualizer not working after recent Realtek driver update

### ISSUE THREAD

**Issue by SavageBruh** [antonpup/Aurora#1890]
### Expected Behaviour

Visualizer layer should work
### Actual Behaviour

Visualizer layer does not work
### Reproduction steps

Windows update installed the new Realtek audio drivers, and now the visualizer does not work at all. I tried rolling back the drivers to fix it but then I just get no sound.
### Frequency

Every time
### Aurora Version:

beta v0.7.2
### Previously an Issue?

Don't know

**Comment by diogotr7** [comment]
Please upload a log from %appdata%\Aurora\Logs

**Comment by SavageBruh** [comment]
@diogotr7 
[2020-01-19 17.25.09.log](https://github.com/antonpup/Aurora/files/4084084/2020-01-19.17.25.09.log)

**Comment by diogotr7** [comment]
Duplicate of #1487
