### ISSUE TITLE
 G-Hub Integration with Aurora Work-Around.

### ISSUE THREAD

**Issue by incryptx** [antonpup/Aurora#1894]
V0.7.2

A Nuclear Option:

Frankly, I just don't know how to describe this bug, but there seems to be no DIRECT WAY to get Aurora to integrate with G-HUB, except to man handle it in. Aurora does not have a button that says, "Integrate with G-Hub" and G-Hub does not have any way to choose Aurora as an application  for G-Hub to be added to "Integration".

So, I found a stupid workaround to get Aurora to work with G-Hub. I'll let the developer figure out why it works.

You will need the following files.

1) Aurora-v0.7.2+19.zip (contains the Elite profile)
2) Aurora-setup-v0.7.2.exe (Does not have the Elite Profile for some reason, Windows Installer)
3) G-Hub Installer

Now,

1) Uninstall the G-Hub install completely.
2) Uninstall Aurora and delete the directory at C:\Program Flies\Aurora

Reboot your PC.

1) Install Aurora-Setup-v0.7.2.exe, which will create the Aurora directory at C:\Program Files\Aurora without the "Elite Profile", but we will fix that in just a second.
2) Install G-Hub from the installer, then close it without configuring anything.
3) Now, unzip Aurora-v0.7.2+19.zip somewhere, then go into the directory and "copy and paste" all the files directly on top of the directory at C:\Program Files\Aurora.

Now open Aurora first, then G-Hub and boom, your Elite Profile will work. You can go into G-Hub and enable integration, but Aurora should be already working.

As a side note, all of the game profiles I had in G-Hub were still there and all the settings I had for Aurora were still there, so I did not need to reconfigure either G-Hub or Aurora.

I don't know why this works, nor do I care. I uninstalled everything, reinstalled G-Hub after a reboot, used the Aurora-Setup-v0.7.2.exe to create the directory rather than unzip files and put it back there, then overwrote the Aurora directory with the zip file for the Elite Profile.

I have done this three times, it works every time.

It's completely stupid, but it works.

**Comment by Bluscream** [comment]
I got GHUB to work without any shenanigans

**Comment by akakroes** [comment]
> I got GHUB to work without any shenanigans

Could you tell us if you did anything different or what versions you got?

**Comment by Liniuta** [comment]
Where i can find  Aurora-v0.7.2+19.zip?

**Comment by diogotr7** [comment]
This is generally unnecessary. The issue you had with g hub was probably due to the elite version of aurora not having the updated ghub dll. It has now been merged into dev so you can use that instead.

The most common issue with g hub is aurora starting up before g hub has time to. This can be fixed by adding a delay to the startup task of aurora in general settings.
