### ISSUE TITLE
French keyboard trouble with light

### ISSUE THREAD

**Issue by JeremyD357** [antonpup/Aurora#19]
Hi, as I say in the title I have a french keyboard and when i press Q it's illuminate A and when i press Z it's illuminate W (Sorry for my bad english i try to do my best :D ) So can you do something to fix it please it's would be cool :) Thank you.

**Comment by antonpup** [comment]
I have fixed the Q/A and W/Z issue. But I would like to know if some of the other keys function properly. Can you tell me if any of the circled keys are not working or not illuminating correct keys?

![http://puu.sh/pnSzb/ad7d8d04c5.png](http://puu.sh/pnSzb/ad7d8d04c5.png)

**Comment by JeremyD357** [comment]
I hope you will understand what i mean :D
![sans titre](https://cloud.githubusercontent.com/assets/18364472/15973452/cb80e6f4-2f43-11e6-88e4-760f7624b9ca.png)

**Comment by JeremyD357** [comment]
I hope you will understand what i mean :D
![sans titre](https://cloud.githubusercontent.com/assets/18364472/15973494/0463e12e-2f44-11e6-8155-46c057df217a.png)

**Comment by JeremyD357** [comment]
And for league of legends i don't know why but it's don't work maybe should i open another topic for this?

**Comment by antonpup** [comment]
Oh, for LoL, you need to enable LightFX in config. "Riot Games\League of Legends\Config\game.cfg" and set "EnableLightFx=0" to "EnableLightFx=1"

**Comment by JeremyD357** [comment]
Oh thank you :)

**Comment by antonpup** [comment]
Can you add me on steam, I would like to get the key information from French input. [http://steamcommunity.com/id/pupant/](http://steamcommunity.com/id/pupant/)

**Comment by JeremyD357** [comment]
Added tell me how can i help you

**Comment by JeremyD357** [comment]
[INFO] 10/06/2016 21:11:14: Key pressed: Escape.
[INFO] 10/06/2016 21:11:15: Key pressed: F1.
[INFO] 10/06/2016 21:11:15: Key pressed: F2.
[INFO] 10/06/2016 21:11:16: Key pressed: F3.
[INFO] 10/06/2016 21:11:16: Key pressed: F4.
[INFO] 10/06/2016 21:11:17: Key pressed: F5.
[INFO] 10/06/2016 21:11:17: Key pressed: F6.
[INFO] 10/06/2016 21:11:17: Key pressed: F7.
[INFO] 10/06/2016 21:11:18: Key pressed: F8.
[INFO] 10/06/2016 21:11:18: Key pressed: F9.
[INFO] 10/06/2016 21:11:19: Key pressed: F10.
[INFO] 10/06/2016 21:11:19: Key pressed: F11.
[INFO] 10/06/2016 21:11:19: Key pressed: F12.
[INFO] 10/06/2016 21:11:20: Key pressed: PrintScreen.
[INFO] 10/06/2016 21:11:20: Key pressed: Scroll.
[INFO] 10/06/2016 21:11:20: Key pressed: Pause.
[INFO] 10/06/2016 21:11:22: Key pressed: Oem7.
[INFO] 10/06/2016 21:11:22: Key pressed: D1.
[INFO] 10/06/2016 21:11:23: Key pressed: D2.
[INFO] 10/06/2016 21:11:23: Key pressed: D3.
[INFO] 10/06/2016 21:11:24: Key pressed: D4.
[INFO] 10/06/2016 21:11:24: Key pressed: D5.
[INFO] 10/06/2016 21:11:25: Key pressed: D6.
[INFO] 10/06/2016 21:11:25: Key pressed: D7.
[INFO] 10/06/2016 21:11:25: Key pressed: D8.
[INFO] 10/06/2016 21:11:26: Key pressed: D9.
[INFO] 10/06/2016 21:11:26: Key pressed: D0.
[INFO] 10/06/2016 21:11:26: Key pressed: OemOpenBrackets.
[INFO] 10/06/2016 21:11:27: Key pressed: Oemplus.
[INFO] 10/06/2016 21:11:27: Key pressed: Back.
[INFO] 10/06/2016 21:11:27: Key pressed: Insert.
[INFO] 10/06/2016 21:11:28: Key pressed: Home.
[INFO] 10/06/2016 21:11:28: Key pressed: PageUp.
[INFO] 10/06/2016 21:11:28: Key pressed: NumLock.
[INFO] 10/06/2016 21:11:29: Key pressed: Divide.
[INFO] 10/06/2016 21:11:29: Key pressed: Multiply.
[INFO] 10/06/2016 21:11:29: Key pressed: Subtract.
[INFO] 10/06/2016 21:11:30: Key pressed: Tab.
[INFO] 10/06/2016 21:11:31: Key pressed: A.
[INFO] 10/06/2016 21:11:31: Key pressed: Z.
[INFO] 10/06/2016 21:11:32: Key pressed: E.
[INFO] 10/06/2016 21:11:32: Key pressed: R.
[INFO] 10/06/2016 21:11:32: Key pressed: T.
[INFO] 10/06/2016 21:11:33: Key pressed: Y.
[INFO] 10/06/2016 21:11:33: Key pressed: U.
[INFO] 10/06/2016 21:11:33: Key pressed: I.
[INFO] 10/06/2016 21:11:34: Key pressed: O.
[INFO] 10/06/2016 21:11:34: Key pressed: P.
[INFO] 10/06/2016 21:11:34: Key pressed: Oem6.
[INFO] 10/06/2016 21:11:35: Key pressed: Oem1.
[INFO] 10/06/2016 21:11:35: Key pressed: Return.
[INFO] 10/06/2016 21:11:36: Key pressed: Delete.
[INFO] 10/06/2016 21:11:36: Key pressed: End.
[INFO] 10/06/2016 21:11:36: Key pressed: Next.
[INFO] 10/06/2016 21:11:37: Key pressed: Home.
[INFO] 10/06/2016 21:11:37: Key pressed: Up.
[INFO] 10/06/2016 21:11:37: Key pressed: PageUp.
[INFO] 10/06/2016 21:11:38: Key pressed: Add.
[INFO] 10/06/2016 21:11:39: Key pressed: Capital.
[INFO] 10/06/2016 21:11:39: Key pressed: Q.
[INFO] 10/06/2016 21:11:39: Key pressed: S.
[INFO] 10/06/2016 21:11:40: Key pressed: D.
[INFO] 10/06/2016 21:11:40: Key pressed: F.
[INFO] 10/06/2016 21:11:40: Key pressed: G.
[INFO] 10/06/2016 21:11:41: Key pressed: H.
[INFO] 10/06/2016 21:11:41: Key pressed: J.
[INFO] 10/06/2016 21:11:41: Key pressed: K.
[INFO] 10/06/2016 21:11:42: Key pressed: L.
[INFO] 10/06/2016 21:11:42: Key pressed: M.
[INFO] 10/06/2016 21:11:42: Key pressed: Oemtilde.
[INFO] 10/06/2016 21:11:43: Key pressed: Oem5.
[INFO] 10/06/2016 21:11:43: Key pressed: Return.
[INFO] 10/06/2016 21:11:44: Key pressed: Left.
[INFO] 10/06/2016 21:11:44: Key pressed: Clear.
[INFO] 10/06/2016 21:11:45: Key pressed: Right.
[INFO] 10/06/2016 21:11:45: Key pressed: Add.
[INFO] 10/06/2016 21:12:07: Key pressed: LShiftKey.
[INFO] 10/06/2016 21:12:07: Key pressed: OemBackslash.
[INFO] 10/06/2016 21:12:08: Key pressed: W.
[INFO] 10/06/2016 21:12:08: Key pressed: X.
[INFO] 10/06/2016 21:12:09: Key pressed: C.
[INFO] 10/06/2016 21:12:09: Key pressed: V.
[INFO] 10/06/2016 21:12:09: Key pressed: B.
[INFO] 10/06/2016 21:12:10: Key pressed: N.
[INFO] 10/06/2016 21:12:10: Key pressed: Oemcomma.
[INFO] 10/06/2016 21:12:10: Key pressed: OemPeriod.
[INFO] 10/06/2016 21:12:11: Key pressed: OemQuestion.
[INFO] 10/06/2016 21:12:11: Key pressed: Oem8.
[INFO] 10/06/2016 21:12:12: Key pressed: RShiftKey.
[INFO] 10/06/2016 21:12:12: Key pressed: Up.
[INFO] 10/06/2016 21:12:13: Key pressed: End.
[INFO] 10/06/2016 21:12:13: Key pressed: Down.
[INFO] 10/06/2016 21:12:13: Key pressed: Next.
[INFO] 10/06/2016 21:12:14: Key pressed: Return.
[INFO] 10/06/2016 21:12:17: Key pressed: LControlKey.
[INFO] 10/06/2016 21:12:17: Key pressed: LWin.
[INFO] 10/06/2016 21:12:18: Key pressed: LMenu.
[INFO] 10/06/2016 21:12:18: Key pressed: Space.
[INFO] 10/06/2016 21:12:19: Key pressed: LControlKey.
[INFO] 10/06/2016 21:12:19: Key pressed: RMenu.
[INFO] 10/06/2016 21:12:19: Key pressed: RWin.
[INFO] 10/06/2016 21:12:20: Key pressed: Apps.
[INFO] 10/06/2016 21:12:20: Key pressed: RControlKey.
[INFO] 10/06/2016 21:12:20: Key pressed: Left.
[INFO] 10/06/2016 21:12:21: Key pressed: Down.
[INFO] 10/06/2016 21:12:21: Key pressed: Right.
[INFO] 10/06/2016 21:12:21: Key pressed: Insert.
[INFO] 10/06/2016 21:12:22: Key pressed: Delete.
[INFO] 10/06/2016 21:12:22: Key pressed: Return.

**Comment by antonpup** [comment]
Resolved.
