### ISSUE TITLE
Can't Install Chroma supported version

### ISSUE THREAD

**Issue by Macsh** [antonpup/Aurora#1901]
Hello Everyone,

I hope this was not an issue that's been asked before but whenever I try to install the new Chroma ver to get OW Chroma Support I get this error:

![image](https://user-images.githubusercontent.com/60581130/73613321-9c02fe00-45f4-11ea-82ea-041e83b48160.png)

Do you know what I should do?

Thanks!

**Comment by Macsh** [comment]
Okay I actually managed to fix the issue on my end.
If that happens to somebody else here's what I did : 
Closed Synapse
Uninstalled Razer Chroma SDK
Pressed Install in Aurora
That installed the newer version prompted me to reboot and voilà!
Now it works :)

![image](https://user-images.githubusercontent.com/60581130/73613726-b212bd80-45f8-11ea-8d23-d30374509de7.png)

**Comment by diogotr7** [comment]
Thank you for following up with the fix!
