### ISSUE TITLE
Some keys aren't affected by Aurora anymore. (Vanguard K08)

### ISSUE THREAD

**Issue by BmontYo** [antonpup/Aurora#1907]
So I've used Aurora for about a year now and absolutely love it.  The Soundblaster software is AWFUL so Aurora is so nice to have.

Unfortunately, very recently Aurora stopped working on my numpad, arrow keys, and right alt/ctrl/fn.  It's VERY strange to me because if I use the Soundblaster software I can change those key colors with no problem at all, but Aurora won't affect them in any way.  If I set my keyboard to be blue in Soundblaster then they will stay blue NO MATTER WHAT I do in Aurora.  

I've tried uninstalling my keyboard drivers and reinstalling, I've uninstalled and reinstalled Aurora, I've tried with and without the Soundblaster software installed, and I've tried telling Aurora that it's a different keyboard but to no avail.  The only thing I haven't tried is a different PC because I don't have another one to test with.

Has anyone had this issue before?  I'm starting to think I just can't use Aurora with this keyboard anymore, and that's a huge bummer.  Any help is greatly appreciated!!!

**Comment by BmontYo** [comment]
I just solved the issue.  I saw someone else say you can do a hardware reset on this keyboard by holding Ctrl+alt+f2 while plugging it into the USB port.  Worked great!

**Comment by diogotr7** [comment]
Thanks for posting the solution!
