### ISSUE TITLE
G815/G915

### ISSUE THREAD

**Issue by snak31** [antonpup/Aurora#1912]
Hello, I am using your application for my G815 keyboard. However there is no profile for this keyboard. I use that of the G910 but it does not have the buttons to manage the music. Is it possible to add them? Thank you

**Device Name:** Logitech G815

**Device Website:** https://www.logitechg.fr/fr-fr/products/gaming-keyboards/g815-low-profile-rgb-mechanical-gaming-keyboard.html

**Comment by diogotr7** [comment]
Logitech's SDK doesn't allow for individual addressing of the media keys.
