### ISSUE TITLE
Drevo Blademaster TE: No lighting on pipe/backslash key

### ISSUE THREAD

**Issue by taario** [antonpup/Aurora#1913]
### Expected Behaviour
The pipe/backslash key should be lit

### Actual Behaviour
The pipe/backslash key button is not lit

### Reproduction steps
Select pipe/backslash key in any scenario for lighting, key does not light up 

### Frequency
Always

### Aurora Version:
0.7.2

### Previously an Issue?
Don't know

**Comment by diogotr7** [comment]
Try manually setting the layout in the settings to United States or other ANSI layout. It's probably set to Automatic now

**Comment by taario** [comment]
> Try manually setting the layout in the settings to United States or other ANSI layout. It's probably set to Automatic now

You're correct, this resolved the issue. Thank you.
