### ISSUE TITLE
Req: Hide games not detected

### ISSUE THREAD

**Issue by Sokonomi** [antonpup/Aurora#192]
I only have 3 or 4 of the standard included games, so theres a buttload of icons taking up unnecessary space.

Maybe have a tick in the settings that hides any games it couldn't detect on initial startup? Then if you unhide them and point them to the location of the exe manually, they will show up when you tick hide again.

**Comment by antonpup** [comment]
There are some games that I cannot detect, like Battlefield, DRM-free HM, Guild Wars.
