### ISSUE TITLE
Aurora will not start

### ISSUE THREAD

**Issue by Mehammers** [antonpup/Aurora#1922]
### Expected Behaviour
the program will start

### Actual Behaviour
when i start the program i see it start in the task manager, but after a few seconds it gets shutdown

### Frequency
this happends every time i start the program

### Aurora Version:
v0.7.2

### Previously an Issue?
i dont think so, it did work some time ago, but it has not worked for a long time

**Comment by diogotr7** [comment]
Do you have asus aura?

**Comment by Mehammers** [comment]
yes

**Comment by diogotr7** [comment]
Duplicate of #1895
