### ISSUE TITLE
Keyboard Bitmap View

### ISSUE THREAD

**Issue by stdedos** [antonpup/Aurora#1931]
* Add a more direct button to open it (instead of going all the way down to debug)
(could be toggle-able)

* Could this look _less_ like I need to wear glasses? (could be toggle-able)
![image](https://user-images.githubusercontent.com/133706/76496269-56cabb00-6441-11ea-93b8-f89241c83c49.png)

  I understand it needs to "immitate" what is shown on the devices (hence I am not expecting crisp QHD), but at _some_ improvement.

**Comment by diogotr7** [comment]
You can increase the quality of the bitmap in the settings but I wouldn't recommend it. Some of the layers don't render exactly the same for different quality values.

**Comment by stdedos** [comment]
Oh, okay, now I see what are you talking about.

I don't know how internals work; I was hoping that _bitmap view_ itself would be "finely rendered" (or: _great and above_), without "affecting anything else".

I understand your point, but it is always not easy to track it continuously. I don't want to close this, but I don't see how could this be fixed (maybe "lock" rendering / window in a reasonable size, and then apply "beautification" above it?)

**Comment by gitmacer** [comment]
About direct button. I am working on auto open of the debug window + remember position... Will be greate if you want to test changes that require a restart.

**Comment by stdedos** [comment]
![image](https://user-images.githubusercontent.com/133706/77477198-a7202080-6e24-11ea-988c-98c19749b60c.png)

I am _most definite_ you could render a 48x48px topmost Mario-QuestionMark button on the lower right corner of the window that would open debug view immediately. Default off (if you have to); user configurable.

**Comment by gitmacer** [comment]
If we add a more direct button I would prefer right clicking the settings icon and be able to choose which one. Opinions?

**Comment by stdedos** [comment]
Right-clicking the cog wheel _at the bottom right_ with a quick-access menu doesn't sound half-bad either

**Comment by gitmacer** [comment]
@stdedos Is that what you wanted?

**Comment by stdedos** [comment]
Sounds like it 👍

**Comment by gitmacer** [comment]
Feel free to test/use it. If your profiles are important to you please back up them under %appdata% 
https://ci.appveyor.com/project/antonpup/aurora/builds/31773909/artifacts

**Comment by stdedos** [comment]
I have already reported enough bugs 😛 

https://github.com/antonpup/Aurora/issues/stdedos

And to quote myself: https://github.com/antonpup/Aurora/issues/1897#issuecomment-580370515

> Program crashes a lot for me, it leaks _a lot_ of memory, and I need to restart it daily, to get "half" the features.
> 
> So, no, not out of the blue, but I cannot really tell what did I do, what is to blame, or how to reproduce it. I was actually thinking that it had crashed silently, and I didn't bother to restart it; however, it crashed.

**Comment by diogotr7** [comment]
Just merged #1943 

As for the antialiasing on the bitmap window, i dont think applying effects to the bitmap window and not to the keyboard makes sense, as it would defeat the purpose of it being a preview.
