### ISSUE TITLE
Logitech G910 - Bottom logo not responding.

### ISSUE THREAD

**Issue by Sokonomi** [antonpup/Aurora#194]
For some odd reason the bottom logo in the wrist rest of my G910 does not want to play along. I cant assign it to anything as it is not a button, though it does have its own address, same as the "G" logo next to the ESC button. Yet it remains 'stuck' on obnoxious cyan blue.

Is there a way to include this logo in anything?

**Comment by antonpup** [comment]
That is because that led is not included in the layout. It should be resolved next major version.

**Comment by antonpup** [comment]
That is because that led is not included in the layout. It should be resolved next major version.

**Comment by antonpup** [comment]
I got the badge in for G910

![](https://puu.sh/soLyE/a05c429929.png)
