### ISSUE TITLE
Logitech G815 Media key RGB Support?

### ISSUE THREAD

**Issue by Jappachino** [antonpup/Aurora#1954]
I Just got my Logitech G815 today,and most of the RGB keys are addressable, but I noticed that the media keys and the brightness button is not lit up nor is addressable in Aurora. These keys definitely light up and is RGB, I checked in the Logitech GHUB software. Did I set up something wrong in aurora, or is this something that needs to be implemented in a future update?

Thanks!

**Comment by diogotr7** [comment]
This is not possible with the Logitech G SDK unfortunately as these keys are not individually addressable. Sorry!
