### ISSUE TITLE
MOAR Cores

### ISSUE THREAD

**Issue by stdedos** [antonpup/Aurora#1955]
![image](https://user-images.githubusercontent.com/133706/78981417-8fd17a80-7b28-11ea-8d60-e0b53601a3fd.png)

At least now Aurora _just_ crashed ...

**Comment by diogotr7** [comment]
I think this was fixed with #1880 but I'm not 100% sure. Did you try to delete e custom profile just before it crashed?

**Comment by stdedos** [comment]
> I think this was fixed with #1880 but I'm not 100% sure. Did you try to delete e custom profile just before it crashed?

Indeed

**Comment by diogotr7** [comment]
I have to finish up a few pull requests and I'll make a new pre release soon with a bunch of fixes. In any case, this issue has been fixed with the mentioned PR.
