### ISSUE TITLE
Windows Service

### ISSUE THREAD

**Issue by Pandry** [antonpup/Aurora#196]
I was thinking about making a windows service for aurora...
I think it could be useful...

Maybe [that](https://msdn.microsoft.com/en-us/library/zt39148a%28v=vs.110%29.aspx) could be a valid example

Would it be useful?

**Comment by brainbug89** [comment]
Useful for what? :thinking:

**Comment by Pandry** [comment]
Windows services are a special type of application that is configured to launch and run in the background, in some cases before the user has even logged in. They can be configured to run as the local system account. Services are designed to run continuously in the background and perform system tasks, like backing up your computer or running a server process that listens on a network port.

So for example save a config file and make a service instead of start Aurora with the Admin permission at every startup...

**Comment by rkkoszewski** [comment]
I was about to post the same request. It seems like Aurora's configuration interface is always in RAM and is just hidden but still taking up computer resources. It would be awesome to split the whole Aurora logic as a UI-less background service optimized for low RAM and CPU usage, and a configuration interface in a complete separate process which is freed/closed once the configuration window is closed. The service could show a Tray icon (To allow easy killing of the service or run it as standalone service without having to install it explicitly as a windows service), and from the tray icon it could just launch the main configuration executable.

This could be a possible new feature for the next iteration of Aurora.

**Comment by antonpup** [comment]
If you guys want todo this, by all means go for it. I wouldn't know how to accomplish this. So, take a looker the dev branch and make changes to that. As it has a few fixes and improvements over the public version.

**Comment by Pandry** [comment]
I was thinking to do that after the installer...
Being more precise I was thinking about make aurora save a file that contains the lighting settings, so the service read it and make the keyboard lights up...
And it would work even before to do the login...

**Comment by VoronFX** [comment]
There is a problem. LGS is not a service, so it will not work before login even if aurora will be a service.

**Comment by Pandry** [comment]
Yeah, I figured out about it...
Maybe Logitech could do something to have a service that manages these kinds of things...
I though it could be useful anyway one a user log-in...

**Comment by brainbug89** [comment]
> There is a problem. LGS is not a service, so it will not work before login even if aurora will be a service.

Same problem with CUE. :thinking:
