### ISSUE TITLE
Ducky One 2 TKL RGB ISO mapping messed up

### ISSUE THREAD

**Issue by mikk150** [antonpup/Aurora#1965]
### Expected Behaviour
When using Interactive layer (Key fade) pressing a button, should fade corresponding button pressed

### Actual Behaviour
Some buttons fade different button

### Reproduction steps
1. Get your Ducky One 2 TKL RGB ISO keyboard
2. Make interactive layer
3. Start typing

### Frequency
Every time

### Aurora Version:
B 0.7.2 + 802

### Previously an Issue?

https://youtu.be/09GAr6Kxlu4

https://github.com/antonpup/Aurora/pull/1892#issuecomment-581101246 99%is possibly not enough :)

**Comment by mikk150** [comment]
I have looked at it bunch more, and investigated it... and it turns out, it is not Ducky mapping issue(even thou you still have one issue, as capslock for some bizarre reasion has 2 RGB leds, and both are addressed, I guess ducky wanted capslock key LED to be on the key itself, even having cutout on the keycap itself, but never actually implemented it as capslock LED is plain old boring white led on top of Insert key)

**Comment by diogotr7** [comment]
I assume this was caused by the layout being incorrect in the settings?

Thanks for reporting your findings.

**Comment by mikk150** [comment]
@diogotr7 yes, none of layouts even match Estonian layout
