### ISSUE TITLE
Roccat Vulcan light only flickering!

### ISSUE THREAD

**Issue by Kalbi1** [antonpup/Aurora#1970]
### Expected Behaviour
Light should work as expected

### Actual Behaviour
light flickers very fast! Looks like it changes between the commands from aurora and the roccat swarm software very fast!

### Reproduction steps
Active Vulcan API in Device Manager

### Frequency
Every time!

### Aurora Version:
beta 0.7.2

### Previously an Issue?
Dont know. I just got my new keyboard

**Comment by diogotr7** [comment]
Please close the roccat swarm software when you use aurora.

**Comment by Kalbi1** [comment]
thank you

**Comment by Bluscream** [comment]
vulkan is a keyboard not a graphics api in aurora?

**Comment by diogotr7** [comment]
vulkan != vulcan. I didn't name the keyboard, roccat did

**Comment by Kalbi1** [comment]
Its a german brand :D

**Comment by Bluscream** [comment]
What a disappointment. I always had the vulkan wrapper emabled in hopes it would allow ambient lighting in vulkan games

**Comment by OHGODNO162534** [comment]
when i press exit on swarm it starts to flicker more than it does when the app is open
