### ISSUE TITLE
Vertical Perdent (Gradient) Effect Layer

### ISSUE THREAD

**Issue by Cheerpipe** [antonpup/Aurora#1986]
Would be nice to have a vertical oriented gradient option in the Vertical Perdent (Gradient) Effect Layer.

Thanks in advance.

**Comment by gitmacer** [comment]
You can Rotate the Freestyle selection.
![freestyle rotating](https://user-images.githubusercontent.com/37345589/80583409-75e0d480-8a10-11ea-8fb8-f4676158dcdb.gif)

**Comment by Cheerpipe** [comment]
Didn't know about this. Thanks!
