### ISSUE TITLE
Corsair Dark Core not working

### ISSUE THREAD

**Issue by JPCadarn** [antonpup/Aurora#1994]
### Expected Behaviour
The mouse lights should be lighting up

### Actual Behaviour
The lights are off

### Reproduction steps
Configured the mouse as Corsair M65 and created a light profile. Corsair iCue shows the lights changing the same way Aurora shows, but the actual mouse lights don't turn on.

### Frequency
All the time

### Aurora Version:
0.7.2

### Previously an Issue?
Never used previous versions

**Comment by diogotr7** [comment]
Can't fix as per 
https://github.com/CorsairOfficial/cue-sdk/issues/8
