### ISSUE TITLE
Shift Key modifier?

### ISSUE THREAD

**Issue by hmschreck** [antonpup/Aurora#2]
I see that you can allow the CTRL and ALT keys to be used to modify layouts on the fly (hold down CTRL/ALT, etc).  Could this functionality be added for L-Shift as well?  Or, perhaps even better, a way for the software to allow user-defined keys to exhibit this behavior?

**Comment by antonpup** [comment]
There are two reasons why I did not include Shift key in the Shortcuts Assistant.

1. When you type, you use the shift key on a regular basis. As a result, it would be distracting and annoying for the user to have keys light up every time they want to type something.
2. There's not much space on the interface to include more than 3 shortcut selections. I might redesign it to allow users to select which keys activate the shortcuts assistant, besides the hardcoded CTRL, WIN, and ALT.

**Comment by hmschreck** [comment]
Regarding the first one, having the option would still be pretty nice for
my use case, though I can definitely get your drift.  Regarding the second,
that seems pretty reasonable! :)
