### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by BREgATRON** [antonpup/Aurora#20]
Hi, I installed everything which was needed and it keeps crashing on launch. The buttons on my g810 do random shiny things but after that I have to stop the programm. Here's the log:

[INFO] 10.06.2016 15:36:05: Device, Logitech, was initialized.
[ERROR] 10.06.2016 15:36:05: Corsair device, CUE Exception! ErrorCode: ServerNotFound.
[INFO] 10.06.2016 15:36:05: Device, Corsair, was not initialized.
[INFO] 10.06.2016 15:36:05: No Chroma SDK available.
[ERROR] 10.06.2016 15:36:05: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   bei Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:Zeile 52..
[INFO] 10.06.2016 15:36:05: Device, Razer, was not initialized.
10.06.2016 15:36:05: Listening for game integration calls....
[ERROR] 10.06.2016 15:36:05: Fatal Exception caught : System.Collections.Generic.KeyNotFoundException: Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
   bei System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   bei Aurora.Utils.SteamUtils.GetGamePath(Int32 gameId) in d:\Repositories\Git\Aurora\Project-Aurora\Utils\SteamUtils.cs:Zeile 135.
   bei Aurora.Profiles.Dota_2.Control_Dota2.InstallGSI() in d:\Repositories\Git\Aurora\Project-Aurora\Profiles\Dota 2\Control_Dota2.xaml.cs:Zeile 1079.
   bei Aurora.Profiles.Dota_2.Control_Dota2..ctor() in d:\Repositories\Git\Aurora\Project-Aurora\Profiles\Dota 2\Control_Dota2.xaml.cs:Zeile 119.
   bei Aurora.ConfigUI..ctor() in d:\Repositories\Git\Aurora\Project-Aurora\ConfigUI.xaml.cs:Zeile 35.
   bei Aurora.Program.Main(String[] args) in d:\Repositories\Git\Aurora\Project-Aurora\Program.cs:Zeile 208..
[ERROR] 10.06.2016 15:36:05: Runtime terminating: True.
[INFO] 10.06.2016 15:36:24: Device, Logitech, was initialized.
[ERROR] 10.06.2016 15:36:24: Corsair device, CUE Exception! ErrorCode: ServerNotFound.
[INFO] 10.06.2016 15:36:24: Device, Corsair, was not initialized.
[INFO] 10.06.2016 15:36:24: No Chroma SDK available.
[ERROR] 10.06.2016 15:36:24: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   bei Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:Zeile 52..
[INFO] 10.06.2016 15:36:24: Device, Razer, was not initialized.
10.06.2016 15:36:24: Listening for game integration calls....
[ERROR] 10.06.2016 15:36:25: Fatal Exception caught : System.Collections.Generic.KeyNotFoundException: Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
   bei System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   bei Aurora.Utils.SteamUtils.GetGamePath(Int32 gameId) in d:\Repositories\Git\Aurora\Project-Aurora\Utils\SteamUtils.cs:Zeile 135.
   bei Aurora.Profiles.Dota_2.Control_Dota2.InstallGSI() in d:\Repositories\Git\Aurora\Project-Aurora\Profiles\Dota 2\Control_Dota2.xaml.cs:Zeile 1079.
   bei Aurora.Profiles.Dota_2.Control_Dota2..ctor() in d:\Repositories\Git\Aurora\Project-Aurora\Profiles\Dota 2\Control_Dota2.xaml.cs:Zeile 119.
   bei Aurora.ConfigUI..ctor() in d:\Repositories\Git\Aurora\Project-Aurora\ConfigUI.xaml.cs:Zeile 35.
   bei Aurora.Program.Main(String[] args) in d:\Repositories\Git\Aurora\Project-Aurora\Program.cs:Zeile 208..
[ERROR] 10.06.2016 15:36:25: Runtime terminating: True.
[INFO] 10.06.2016 15:37:31: Device, Logitech, was initialized.
[ERROR] 10.06.2016 15:37:31: Corsair device, CUE Exception! ErrorCode: ServerNotFound.
[INFO] 10.06.2016 15:37:31: Device, Corsair, was not initialized.
[INFO] 10.06.2016 15:37:31: No Chroma SDK available.
[ERROR] 10.06.2016 15:37:31: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   bei Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:Zeile 52..
[INFO] 10.06.2016 15:37:31: Device, Razer, was not initialized.
10.06.2016 15:37:31: Listening for game integration calls....
[ERROR] 10.06.2016 15:37:31: Fatal Exception caught : System.Collections.Generic.KeyNotFoundException: Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
   bei System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   bei Aurora.Utils.SteamUtils.GetGamePath(Int32 gameId) in d:\Repositories\Git\Aurora\Project-Aurora\Utils\SteamUtils.cs:Zeile 135.
   bei Aurora.Profiles.Dota_2.Control_Dota2.InstallGSI() in d:\Repositories\Git\Aurora\Project-Aurora\Profiles\Dota 2\Control_Dota2.xaml.cs:Zeile 1079.
   bei Aurora.Profiles.Dota_2.Control_Dota2..ctor() in d:\Repositories\Git\Aurora\Project-Aurora\Profiles\Dota 2\Control_Dota2.xaml.cs:Zeile 119.
   bei Aurora.ConfigUI..ctor() in d:\Repositories\Git\Aurora\Project-Aurora\ConfigUI.xaml.cs:Zeile 35.
   bei Aurora.Program.Main(String[] args) in d:\Repositories\Git\Aurora\Project-Aurora\Program.cs:Zeile 208..
[ERROR] 10.06.2016 15:37:31: Runtime terminating: True.
[INFO] 10.06.2016 15:42:50: Device, Logitech, was initialized.
[ERROR] 10.06.2016 15:42:50: Corsair device, CUE Exception! ErrorCode: ServerNotFound.
[INFO] 10.06.2016 15:42:50: Device, Corsair, was not initialized.
[INFO] 10.06.2016 15:42:50: No Chroma SDK available.
[ERROR] 10.06.2016 15:42:50: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   bei Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:Zeile 52..
[INFO] 10.06.2016 15:42:50: Device, Razer, was not initialized.
10.06.2016 15:42:51: Listening for game integration calls....
[ERROR] 10.06.2016 15:42:51: Fatal Exception caught : System.Collections.Generic.KeyNotFoundException: Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
   bei System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   bei Aurora.Utils.SteamUtils.GetGamePath(Int32 gameId) in d:\Repositories\Git\Aurora\Project-Aurora\Utils\SteamUtils.cs:Zeile 135.
   bei Aurora.Profiles.Dota_2.Control_Dota2.InstallGSI() in d:\Repositories\Git\Aurora\Project-Aurora\Profiles\Dota 2\Control_Dota2.xaml.cs:Zeile 1079.
   bei Aurora.Profiles.Dota_2.Control_Dota2..ctor() in d:\Repositories\Git\Aurora\Project-Aurora\Profiles\Dota 2\Control_Dota2.xaml.cs:Zeile 119.
   bei Aurora.ConfigUI..ctor() in d:\Repositories\Git\Aurora\Project-Aurora\ConfigUI.xaml.cs:Zeile 35.
   bei Aurora.Program.Main(String[] args) in d:\Repositories\Git\Aurora\Project-Aurora\Program.cs:Zeile 208..
[ERROR] 10.06.2016 15:42:51: Runtime terminating: True.

**Comment by antonpup** [comment]
I've applied a small fix on my local version. But I do wonder why it's only starting to happen now. Do you perhaps not have Dota 2 installed? Even then, if it worked in the previous version, it should still be working now.

**Comment by BREgATRON** [comment]
I have CS:Go and Dota 2 installed

**Comment by antonpup** [comment]
Strange, because it's crashing when it attempts to get steam install path from registry.  Are you running Aurora from within the Downloads folder by any chance? What OS are you on?

**Comment by BREgATRON** [comment]
Well, some weeks ago I changed to w10 but only cleaned the harddrive where windows is located. The other two harddrives with Steam on it were not touched at all. Aurora is launching from the same device Steam is located on.

**Comment by antonpup** [comment]
Add me on steam, [http://steamcommunity.com/id/pupant/](http://steamcommunity.com/id/pupant/) I would like to debug this issue.

**Comment by antonpup** [comment]
Resolved.
