### ISSUE TITLE
Profile Switcher

### ISSUE THREAD

**Issue by the27club** [antonpup/Aurora#200]
Is there a way to make multiple profiles for one application and use the Pause/Break key to change the profiles? 

Say I want to make multiple profiles for the Star Wars Battlefront and mid-game, i decide i would like a different profile. Instead of leaving the window to go change the profile, I just tap pause/break to switch the profile.

**Comment by antonpup** [comment]
I suppose I could add that as a feature. So essentially pressing Pause/Break will go to next profile.

**Comment by the27club** [comment]
Yes! Pressing the Pause/Break (or any desired key) could change the profile inside of a single applications profiles

**Comment by the27club** [comment]
any chance that this as been worked on??

**Comment by antonpup** [comment]
Not last two days, but it is still on the table.

**Comment by simon-wh** [comment]
Feature is available in recent releases
