### ISSUE TITLE
Overlays layers not working since v0.7.2+822

### ISSUE THREAD

**Issue by Cheerpipe** [antonpup/Aurora#2010]
Overlays layers are not working since v0.7.2+822. 

Away effects are not working too since the same build.

https://youtu.be/57gmJuta7vA

### Expected Behaviour
 * Overlay layers should be showed if an application with overlays in their profile is running.

### Actual Behaviour
Overlay layers are not showed or are ignored.

### Reproduction steps

* Create new profile.
* Create an overlay layer.
* Open the application.
* Overlay should be showed, instead, overlay layers are ignored.

### Frequency
Always

### Aurora Version:
clean v0.7.2+822 downloaded from appveyor.

### Previously an Issue?
Working fine until  v0.7.2+821

**Comment by diogotr7** [comment]
This is indeed an issue, i did not notice since the built-in profiles display overlays correctly. Caused by #1997 , will investigate.

**Comment by xQwexx** [comment]
It happening because the sequence was deleted, where the overlays are applied, 
but for some reason in the desktop case the overlay applied in the regular layer applying function.

**Comment by Cheerpipe** [comment]
The following is working as expected now: 

Overlays
Away effect
Process running gamestate conditional

Thanks for your amazing work.
