### ISSUE TITLE
Terraria GSI becomes obsolete with 1.4 release

### ISSUE THREAD

**Issue by PixelHir** [antonpup/Aurora#2013]
**Game Name:** Terraria

**Methods:** The 1.4 promises to bring the razer chroma support, so that means the current tmodloader solution which isn't too flexible and isn't working on multiplayer can be replaced with a Razer Chroma Layer
Source: Terraria 1.4 Changelogs
 https://forums.terraria.org/index.php?threads/there-back-again-a-summary-of-journeys-end.87997/
![image](https://user-images.githubusercontent.com/7670940/82073650-d68f3300-96d9-11ea-8ce7-2bfaf3c06f64.png)

**Comment by diogotr7** [comment]
I know this, but the wrapper solutions are not as reliable as the GSI ones. We'll see what happens when 1.4 actually releases.

**Comment by Bluscream** [comment]
If this becomes implemented i would suggest to pack the legacy lighting into a plugin and provide that for people that want to continue using that

**Comment by ToastedToast128** [comment]
legacy lighting could target tmodloader's new renamed executable and a new wrapper lighting profile could be used for terraria 1.4

**Comment by diogotr7** [comment]
This i didn't know about. I just installed Tmodloader on steam and the exe name is indeed different. I will be renaming this profile to TModloader, along wioth a new icon. If regular terraria players want to use the chroma lighting, they're free to create a new profile with a razer chroma layer / use a chroma layer on the desktop profile.
