### ISSUE TITLE
Light indicator

### ISSUE THREAD

**Issue by Pandry** [antonpup/Aurora#202]
i was thinking about a Apple-like function when the caps lock.
I mean for example that when the caps lock is enabled, it's color change, for example, from being part of the gradient, it stay of a specific color, or change the color gradually ti be the opposite of the actual color (so for example if the actual color is green and the caps lock is enable, the backlight color will be red (I was thinking about a second gradient with a offset))

**Comment by antonpup** [comment]
Will look into, good suggestion! Might even add this for Num lock and Scroll lock.
