### ISSUE TITLE
Confirmation of Vulcan Aimo functionality

### ISSUE THREAD

**Issue by schwizzled** [antonpup/Aurora#2026]
Greetings.  This isn’t an issue as much a confirmation.  If I want to use Aurora with a Roccat Vulcan 120, can I still run Roccat Swarm alongside Aurora for the mouse side of things? Or will Aurora function with the Vulcan only if Swarm is shut down?

Thank you!

**Comment by diogotr7** [comment]
We will be adding documentation about this sort of thing to the wiki soon hopefully. Meanwhile, you need any other programs closed when you use aurora with a Vulcan
