### ISSUE TITLE
Cant get new Razer mouse to work with Aurora and Logitech headset/keyboard.

### ISSUE THREAD

**Issue by avaplaya13** [antonpup/Aurora#204]
I am kind of noobish at this, so i may be missing something obvious. My old logitech mouse did not have chroma effects, so it did not really matter. But now, not only will Razer Synapse not recognize Aurora, it also will glitch out my desktop profile (which i particularly like). The color cycling keeps on going on my Naga, but the headset and keyboard just totally freeze somewhere in the rainbow, and with a bunch of keys going dark.

I have no idea where to begin to fix this, so I really need help. Thanks for the program, though! I have loved it 100% up until this point.

**Comment by avaplaya13** [comment]
Actually, i just returned my mouse (didnt like how it felt), and I still am having issues with my desktop profile. Every other profile works, but the desktop one now is broken totally. Not even resetting it and trying again works

**Comment by antonpup** [comment]
Can you explain in greater detail what is "broken"?

**Comment by antonpup** [comment]
Any updates on this problem? Does it happen on latest version?
