### ISSUE TITLE
Logitech G213 Support (Zone based keyboard support)

### ISSUE THREAD

**Issue by CrossCroissant** [antonpup/Aurora#205]
Hey,
I already used to play games with my Orion Spark and Aurora. Now i got a G213 and game implementation isnt working at all. 
Aurora seems to fail to activate certain keys. It can change colour and brightness of the wohle keyboard (like Changing Teams in CS Go, Flash, Burn) but cant adress single keys.

A Bomb Timer for example will be flashing red over the whole keyboard :( Kills, Health Ammo etc. are not shown in general...

EDIT: https://www.youtube.com/watch?v=ptjTAdyskSQ&feature=youtu.be It only responds to the "Mouse/Headset" Field when configuring a profile :(

EDIT: Since one cant light up single keys in the Logitech Gaming Software, im getting the feeling that the G213 is not a real "RGB" Keyboard... (only rainbow effect :/)

**Comment by antonpup** [comment]
On the site, it says that it's a zone rgb keyboard. Not per key. Which leads me to believe that you can either set entire keyboard one color, or per region. Afaik, the SDK does not have a "per region" color set. So... I don't know. I will take a look at it though.

**Comment by CrossCroissant** [comment]
Yeah,

I found not a single methode to adress one single key :/. I think the rainbow effect is some bad marketing strategy, to think its a full rgb membran keyboard... Just got a Cooler Master for a good price and now working on getting the sdk working [😊]


Anyway thanks for the help!!!


________________________________
Von: Anton Pupkov <notifications@github.com>
Gesendet: Mittwoch, 16. November 2016 07:57:13
An: antonpup/Aurora
Cc: CrossCroissant; Author
Betreff: Re: [antonpup/Aurora] Logitech G213 Support (#205)


On the site, it says that it's a zone rgb keyboard. Not per key. Which leads me to believe that you can either set entire keyboard one color, or per region. Afaik, the SDK does not have a "per region" color set. So... I don't know. I will take a look at it though.

**Comment by antonpup** [comment]
Wait for the weekend, I will be accepting this pr #208

**Comment by davidanger** [comment]
https://community.logitech.com/s/feed/0D531000068wAbKCAU
G213 seems like only have 5 zone color LED. can not set single KEY's LED. :(

**Comment by davidanger** [comment]
https://community.logitech.com/s/feed/0D531000068wAbKCAU
G213 seems like only have 5 zone color LED. can not set single KEY's LED. :(

**Comment by assasing123** [comment]
is there any chance this can be done per zone then? even if its way more limited ? I have one of this keyboards and on my country they are quite damn expensive to buy another one... although its true they dont work per zone I have noticed that certain apps that dont quite recognize the model will send it per key commands and the keyboard will react zone wise or whole keyboard color wise.

**Comment by simon-wh** [comment]
@assasing123 I can probably try and get keyboards with 'zones' working with the device layout redesign I'm in progress of.

**Comment by t0mb3r** [comment]
How can I set the g213 to work with aurora?

**Comment by JonnoN** [comment]
you should update your website to say the G213 isn't supported, so people don't waste their time downloading and installing.

**Comment by diogotr7** [comment]
there's rough support for that keyboard in @SnakePin 's branch here https://github.com/SnakePin/Aurora/tree/g213

**Comment by Gurjot95** [comment]
Fixed #1420

**Comment by Bluscream** [comment]
I wish aurora had a layout option for zoned keyboards in the preview and in the "use these keys" listview. so it looks nicer when setting something up.
