### ISSUE TITLE
Please add support to both the Corsair K57 Wireless RGB keyboard and the Corsair Ironclaw RGB wireless mouse

### ISSUE THREAD

**Issue by megabytesme** [antonpup/Aurora#2058]
Please add support for the following device:

**Device Name:** Corsair K57 RGB Wireless keyboard, Corsair Ironclaw RGB wireless mouse

**Device Website:** www.corsair.com

**Comment by diogotr7** [comment]
Can't fix as per https://github.com/CorsairOfficial/cue-sdk/issues/8

**Comment by megabytesme** [comment]
I see now, thanks. Would it be possible to add these devices, however in USB mode only instead? I usually keep my mouse and keyboard plugged in through USB anyway.

**Comment by diogotr7** [comment]
I see no reason why they wouldnt work right now apart from layout inconsistencies. You can choose a similar layout and it should work fine ( apart from the icue issues with wireless stuff).

**Comment by megabytesme** [comment]
Ok. How would I go about making a profile so the layout is correct? Thanks
