### ISSUE TITLE
How to compile dev version

### ISSUE THREAD

**Issue by ZedeN1** [antonpup/Aurora#206]
First I would like to thank you for a great product, I have been using it for a number of months now and only had a few issues. I have searched through github and found that the issues I have been having (such as Corsair Media Keys) have been fixed in the Dev version of aurora. 

I have non existential knowledge of C# (or other programming languages) and have been trying to compile the dev code using Visual Studio 2015. The issue I am having is that even after compiling the code, my version of Aurora seemded identical to the master release and did not have the issues fixed (it even said that there is a new update available after first launch). 

I am pretty sure that it's and issue with my lack of knowledge, could you please provide instruction on how to compile the dev branch of your awesome program or send a link to any instructions that could help?

Best regards,
Pavel

**Comment by brainbug89** [comment]
Did you downloaded the dev branch?

**Comment by antonpup** [comment]
It sounds like you did not clone or download the dev branch.

You can download the dev branch as a zip from here: https://github.com/antonpup/Aurora/archive/dev.zip
