### ISSUE TITLE
"High" cpu usage when using certain numeric gamestate in overrides

### ISSUE THREAD

**Issue by Cheerpipe** [antonpup/Aurora#2060]
### Expected Behaviour
Aurora CPU usage should be low, or at leaste below 1%

### Actual Behaviour
CPU usage goes above 1%, even above 2% or 3% when using certain numeric values in overrides logics like system volume.  Don't happen when using lightweight 

https://studio.youtube.com/video/btXtJRWBmQI/edit

### Reproduction steps
- Create any layer.
- Create any override logic using numeric values like mem/cpu usage or system volume

### Frequency
Always

### Aurora Version:
0.8.0+854

### Previously an Issue?
Yes, but just figure it out today what whas the source of the problem.

**Comment by diogotr7** [comment]
Does this only happen when you use the values in overrides? does the same thing happen in a percent effect layer? which values lag?

**Comment by Cheerpipe** [comment]
It is strange. CPU usage is not getting down with overlays disabled after i restart Aurora. Let me do some more test to get more conclusive results.

**Comment by Cheerpipe** [comment]
Reportin back after a clean boot.

I have a nice 0%-0.5% without any percent layer or localPcInfo gamestate. I am running a lot of layers, some of them animated and with a lot of leds and still below 0.5%.

![image](https://user-images.githubusercontent.com/972765/83413303-9b834400-a3e9-11ea-901a-e2541cfbbfc4.png)

**Comment by Cheerpipe** [comment]
There is some strange going on. Sometimes Aurora will use over 2% or % of CPU without a reason, even without layers using LocalPcInfo.

I compiled a build without LibreHardwareMonitorLib (complete removed) and there is no more high cpu usage anymore so there is something happening in background that is using LibreHardwareMonitorLib.

Hope this helps.

**Comment by diogotr7** [comment]
I would use the Visual studio profiler ( Debug -> Performance Profiler) to try and figure out what's eating up CPU time

**Comment by Cheerpipe** [comment]
My PC is getting some weird CPU usage readings while using virtual machines with Windows 10 2004 what make my tests unreliable.
