### ISSUE TITLE
equalizer

### ISSUE THREAD

**Issue by cyrok** [antonpup/Aurora#2068]
I know its a quite banal, but some sort of vu meter.
i use a equalizer tool that has it, but it looks it wont work with aurora, so i try to replicate it in aurora. the k95 platinum has a lightbar wich i wanted to use for this, like the tool did.
color changing and setting for it would be great

**Comment by gitmacer** [comment]
Have a look at the audio layer https://wibble199.github.io/Aurora-Docs/reference-layers/audio-visualizer/

**Comment by cyrok** [comment]
jeah, but its mostly vertical. the lightbar is horizonticaly. aaaand i think im to stupid to configure it corectly without a gui... lol

**Comment by gitmacer** [comment]
Oh now I get what you want. You can display the speaker level. By using the Percent Effect Layer.
