### ISSUE TITLE
Aurora not opening

### ISSUE THREAD

**Issue by ilkiwer** [antonpup/Aurora#2069]
### Expected Behaviour
Upon clicking on the icon, Aurora should start up.

### Actual Behaviour
Aurora doesn't show up not in the desktop nor in the tray nor in the task manager.

### Reproduction steps
Download Aurora and install it, then try to open it by clicking in the icon.

### Frequency
Always happens.

### Aurora Version:
Latest one (v0.7.2).

### Previously an Issue?
No. (I never used Aurora before.)

**Comment by gitmacer** [comment]
Can you try the latest version (v0.8.0) https://github.com/antonpup/Aurora/releases

**Comment by devdev999** [comment]
I had this similar issue, and found that the app was running in task manager but nothing appeared. I ended the task and ran it again, only then would it open.

**Comment by ilkiwer** [comment]
> Can you try the latest version (v0.8.0) https://github.com/antonpup/Aurora/releases

Tried it, it's working! Idk why, but it showed me that the 0.7.1 was the latest one... thanks!
