### ISSUE TITLE
Implement to show Cpu ? Gpu Tems

### ISSUE THREAD

**Issue by NicTanghe** [antonpup/Aurora#2070]
Hello i ws wondering if its possible to implement a way to show ur Cpu and Gpu Temps?

I mean if core temps can grab my cpu temps so could u no ?
Also a feature that whould change the color of all affected keys to a given color on 100 % whould be nice.
or does blinking already do that ?

**Comment by gitmacer** [comment]
Do you use the latest version (v0.8.0)? https://github.com/antonpup/Aurora/releases CPU/GPU Temps are already available. For changing color depending on data you should use the override system. https://wibble199.github.io/Aurora-Docs/advanced-topics/overrides-system/

**Comment by NicTanghe** [comment]
check for updates tells me i have the latest version installed but it`s 7.2 (installed with winget)

**Comment by NicTanghe** [comment]
Downloading binary this time.
