### ISSUE TITLE
Make discord not blank out all the lights

### ISSUE THREAD

**Issue by hax4dazy** [antonpup/Aurora#2099]
Every time i now click on discord my desktop profile will turn off and it'll switch to the discord one, witch at that point (because i have no ping's/i'm not muted) will turn off all my lights. This is not as annoying in the day as it is in the night.

**Comment by diogotr7** [comment]
The discord profile is supposed to come disabled by default, but in case it's not you can always disable it manually by right clicking the BetterDiscord icon in aurora's app list. Disabling the profile means it will remain on your desktop profile when you have discord open on the foreground
