### ISSUE TITLE
Skype and Steam message notification?

### ISSUE THREAD

**Issue by medifin** [antonpup/Aurora#21]
Would it be possible that when I get a new message in steam or skype, my G810's logo or a key would light up? Sometimes I forget if I got messages and this would help a lot.

**Comment by antonpup** [comment]
Yes! I will add it as an overlay to show if you have missing messages, when you're getting called, I might allow it to light up two buttons, one green and one red, to allow user to answer the call without tabbing out.

**Comment by medifin** [comment]
Great! When can we expect this update?

**Comment by antonpup** [comment]
Today I am resolving issues with yesterday's update. But I would say 0.4.5 is a good estimate.

**Comment by antonpup** [comment]
I made a first attempt at the Skype Integration in the Skype-support branch. It works, but I haven't added any settings or added any effects for it. So, expect Skype support in the next version.

As for Steam support, I would have to have the user sign into steam through Aurora, and I don't want to do that. So, steam support might not be possible at the moment.

**Comment by antonpup** [comment]
Skype supported added. It will be available in the next version.

**Comment by medifin** [comment]
Awesome.
