### ISSUE TITLE
Differing Keyboard/Mouse brands not working

### ISSUE THREAD

**Issue by nomadhook** [antonpup/Aurora#211]
I have a Razer Blackwidow Chroma and a Logitech G502 Proteus Spectrum, however the program does not pick up the mouse as a Logitech mouse (rather it says it is a Razer mouse), this leads to the lighting effects not working on the mouse. 
![image](https://cloud.githubusercontent.com/assets/7195972/20309185/a5680e1a-ab4f-11e6-92b0-f1837b0b64c7.png)

**Comment by antonpup** [comment]
Aurora is designed in such a way that even if you had an RGB mouse plugged in from every single supported brand, they would all work. Each device does not interfere with others. So, I think that there's an issue with the Logitech SDK. I will see if there are any problems though.

**Comment by simon-wh** [comment]
Could you see if this is still an issue in the [latest pre-release](https://github.com/antonpup/Aurora/releases)
