### ISSUE TITLE
ONN Mechanical Keyboard Support

### ISSUE THREAD

**Issue by WilliamKappler** [antonpup/Aurora#2118]
I recently bought an ONN mechanical keyboard (Walmart store brand). The keyboard was good for the price but the software is as may be expected pretty bad. It would be nice if there was an alternative.

As far as I can tell there is no SDK (there's not even a driver download site that I can find, just the CD that came with it) and of course this is not a huge product line, so I fully understand it's not a priority. I make no guarantees, but I would be willing to take a look at sniffing the driver's interactions if someone can point me in the right direction for how to do that.

Also, I suspect this may be a rebrand of a Redragon keyboard.

**Device Name:** ONN 100004357

**Device Website:** No real website, closest https://www.walmart.com/ip/onn-Gaming-Mechanical-Keyboard/660379246

**Comment by diogotr7** [comment]
Please tell me what the VID and PID of the keyboard are. If it is a redragon rebrand, aurora support is not possible. I've tried this on a keyboard i own and the firmware does not support direct lighting, only writing custom lighting patterns to flash.

**Comment by WilliamKappler** [comment]
Looks like the VID is 3938 and PID is 1205.

**Comment by bolerro** [comment]
I just got one of these keyboards and would like to try Aurora. I will keep an eye on updates and hopefully y'all find a way to get it working.

**Comment by diogotr7** [comment]
Forgot about this issue, sorry. The best way to potentially get this supported would be to reverse engineer it and write a controller for OpenRGB. You can find more info on their gitlab and discord: https://gitlab.com/CalcProgrammer1/OpenRGB . Although if it is indeed a redragon rebrand it is not possible to integrate into aurora as those boards don't support real time lighting.

**Comment by torradactyl** [comment]
I'm having an issue with this keyboard.  Seems Shift+W doesn't work.  Some other keys act as function keys.  Anyone else experiencing this with the Onn. Mechanical keyboard?

**Comment by aleksandr1592** [comment]
**DO NOT INSTALL OPENRGB UNLESS YOU KNOW WHAT YOU DOING!**
Openrgb killed my redragon k621 keyboard with no way to repair it. So double-check if your keyboard is compatible with openrgb.

**Comment by madpanic** [comment]
Try Fn + CtrL + W    to reset back to regular mode.....no need to unplug it as some others have said

**Comment by torradactyl** [comment]
> Try Fn + CtrL + W to reset back to regular mode.....no need to unplug it as some others have said

oh my god that worked!  you're amazing - thank you soooo much!

**Comment by kieths** [comment]
This reset, FN + CTRL + W, works on the Onn Mechanical keyboard, p/n 100004357, as (was?) sold at Walmart. 

One day the keyboard stopped accepting regular keypresses (password failed repeatedly), as I presume it was in Gamers/ Gaming Mode. The above reset put it back into "normal" mode, working as expected. I suspect an accidental bump/ combination of keys turns on gamers mode. I'm adding a FN + CTRL + W label at the top of my keyboard!

**Comment by DavidPayneII** [comment]
I’m having an issue with my onn keyboard my A,S,D buttons on my keyboard moved to the shift left, right, up, down, button and I’m wanting to change them back how can I do that

**Comment by madscientist42** [comment]
> **DO NOT INSTALL OPENRGB UNLESS YOU KNOW WHAT YOU DOING!** Openrgb killed my redragon k621 keyboard with no way to repair it. So double-check if your keyboard is compatible with openrgb.

Uhm...how the F did it do that?  It didn't update firmware- and if sending it RGB commands bricked the thing, you probably DIDN'T want the thing in the first place...  ;)

**Comment by HAK3R4LIFE** [comment]
Ok then. when will this keyboard get support on openrgb?

**Comment by Leif-W** [comment]
I've had this kb (& mouse) 7 months.  Adequate.  But the recent OEM driver uses 100% CPU on one of my cores.  Luckily, I have an older driver from 7+ months ago that didn't do this.  Unfortunately, it auto-updates if I accidentally look on the app version info panel.  It also reverts to default colors every time the app loads or system reboots, and forgets it was configured to sync to both devices, requiring multiple clicks to reconfigure.  All this to say, there exist many pain points, to which basic functionality would be a huge relief.

It'd be lovely to simply set some colors (or turn them off), apply to all Onn devices, click a button, forget about it, or have a profile set via command line, triggered by events (sleep/wake) or hotkey combos.  Will look at the dev/reverse engineer path, but idk if I have the skill for that.  Just commenting for posterity.
