### ISSUE TITLE
Corsair VOID RGB Headset nolonger works.

### ISSUE THREAD

**Issue by Sokonomi** [antonpup/Aurora#212]
I get no response from my headset.

It used to work on my windows 7 machine, but on windows 10 it seems to not function anymore.
I followed SDK instructions, all apps running in admin mode.

Any suggestions?

**Comment by brainbug89** [comment]
Does other SDK apps work?

**Comment by Sokonomi** [comment]
I got it to respond again, by setting "always run as admin" in the compatibility tab.
Apparently rightclicking and choosing "run as admin" doesn't work.

**Comment by antonpup** [comment]
I have the same issue, I will look into it.
