### ISSUE TITLE
Layer Visibility Conditions

### ISSUE THREAD

**Issue by GaleGit** [antonpup/Aurora#2122]
I'm sorry, this in not a bug report, but a question. (Couldn't find a place to send my question)

When I'm trying to set up a new conditional layer, it encourages me to use Layer Visibility Conditions. I can guess what it does from its name, but where are these conditions tweaked, I can't find. Can someone help?

Thank you and again, sorry.

**Comment by gitmacer** [comment]
Have a look at the guide https://aurora-rgb.github.io/Docs/advanced-topics/overrides-system/

**Comment by GaleGit** [comment]
Thanks
