### ISSUE TITLE
Aurora not detecting games.

### ISSUE THREAD

**Issue by Sokonomi** [antonpup/Aurora#213]
For some reason I cant get aurora to trigger when I launch a game, even ones that ive created myself.
The normal desktop mode does seem to work, which makes this weird.

Windows 10 64bit ultimate. App running in admin mode,
followed setup instructions, did the wrapper patches.

**Comment by antonpup** [comment]
It's an issue with process detection. I will see about adding a toggle between two detection methods in the dev build and releasing a test version of it to public this weekend.
