### ISSUE TITLE
Aurora blocking mouse lighting

### ISSUE THREAD

**Issue by Morfildor** [antonpup/Aurora#214]
Hello there;
I'm happily using Aurora for my G910. But when aurora is installed and starts up with windows automatically, my g502 proteus spectrum mouse's lighting turns off. It starts up as lights down. I have to open up logitech gaming software from tray at least one time to make it light up again.

Tested it out. When I disable Aurora from starting with windows, mouse starts up all lit.

**Comment by antonpup** [comment]
What about G910? Does that function properly on startup? Because those two go together, and both should work fine. If G910 just works while the mouse doesn't, then I suspect it's an issue with LGS.

**Comment by Morfildor** [comment]
Yes. G910 works flawlessly.

**Comment by Morfildor** [comment]
I tested it out with reinstalling both softwares. Final conclusion; When PC starts mouse lighting enables, it lights up until Aurora starts with windows start-up. I have to manually open up logitech gaming software to make it light up again.

Is there a way to exclude mouse lighting from Aurora?

**Comment by brainbug89** [comment]
> Is there a way to exclude mouse lighting from Aurora?

Can you deactivate SDK support for the mouse at the logitech gaming software?

**Comment by Morfildor** [comment]
> Can you deactivate SDK support for the mouse only at the logitech gaming software?

I couldn't find anything regarding of disabling SDK for mouse :/

**Comment by brainbug89** [comment]
Same problem like #218 I don't know if there is a way to fix it. :frowning_face:

**Comment by haleksander** [comment]
my logitech g600 mouse resets to on-board memory upon each startup of Windows along with resetting the lighting configurations i've made for each profile in the Logitech Gaming Software

**Comment by Morfildor** [comment]
Yeah my g502 does that too. Except the opposite way. I insistly set it to on-board memory but it keep changing back to software based settings.

**Comment by antonpup** [comment]
Resetting of LGS profiles should not be related to Aurora. Aurora only interacts with LGS via the official SDK. I think LGS is having some technical difficulties.

**Comment by Morfildor** [comment]
That may be LGS related but mouse lighting is definitely aurora based. I just realized it shuts down mouse lighting when Idle effects are prompted for the keyboard. I have to open up LGS again to fix it.

**Comment by IrealiTY** [comment]
Bumping this with a similar issue:
Got a Naga Chroma and it's not listed in the mice list inside Aurora and the default lighting is also disabled while Aurora is running.

**Comment by antonpup** [comment]
@IrealiTY you can select any other mouse, and lighting will work just fine.

**Comment by IrealiTY** [comment]
Indeed, thanks :)

**Comment by simon-wh** [comment]
Try on v0.6.2b if you're still experiencing this. Closing for now.
