### ISSUE TITLE
"\" (backslash) is not correctly mapped or lighting up on the Logitech G815 Keyboard

### ISSUE THREAD

**Issue by JimmeeMan** [antonpup/Aurora#2147]
### Expected Behaviour
The backslash "\\" is in the wrong location on the key mapping of the G815 keyboard layout. It is not lighting up.
Currently the keyboard profile image/mapping is showing the backslash to the left of the enter key instead of above the enter key where it is. The enter key is incorrectly showing as a vertical key instead of horizontal.

(On a side note, the audio/multimedia and brightness button/keys aren't mapped either. They also have RGB)

### Actual Behaviour
The backslash should be lighting up.

### Reproduction steps
Use any lighting profile for the Logitech G815

### Frequency
Constant

### Aurora Version:
0.8.1

### Previously an Issue?
Don't Know

Product Page: https://www.logitechg.com/en-us/products/gaming-keyboards/g815-low-profile-rgb-mechanical-gaming-keyboard.html

**Comment by TCourage** [comment]
Can you change your Preferred Keyboard Layout to United States? Sounds like you have a US keyboard and the international layout was automatically detected somehow.

**Comment by JimmeeMan** [comment]
> Can you change your Preferred Keyboard Layout to United States? Sounds like you have a US keyboard and the international layout was automatically detected somehow.

Yeah...that would be it. Whoops, not a bug. It was set on Auto Detect. Thanks for letting me know.
