### ISSUE TITLE
I can`t find the settings for LogitechGamingSoftware,

### ISSUE THREAD

**Issue by 4realRedX** [antonpup/Aurora#215]
I pluged Keyboard out and in again and now Aurora doesn`t work anymore. Maybe it`s the settings please help.

**Comment by antonpup** [comment]
Restart computer? Aurora doesn't handle devices directly. It's the SDK of each device that does. So, make sure that whatever your device's utility software is running.

**Comment by 4realRedX** [comment]
Thy for helping me but I fixed the problem. When I restart my computer it changes the settings of LGS so i need to change it everytime.

**Comment by antonpup** [comment]
It shouldn't change LGS settings. What kind of settings are you talking about?
