### ISSUE TITLE
Aurora CPU and RAM Overlay's background colors not set

### ISSUE THREAD

**Issue by selmansavas** [antonpup/Aurora#2167]
I am using Corsair K95 Platinum keyboard with aurora. When i lock my computer, aurora's and icue softwares connection to the keyboard disconnects. After i log back in to desktop, aurora and icue lights up the keyboard, but background color of CPU Usage and RAM Usage layers not set correctly. If the CPU or RAM CurrentValue gets to the uncorrectly lit key, or aurora uses afk mode to make whole keyboard black, the keys uses icue's colors.

**Comment by gitmacer** [comment]
icue isn't allowing us to control the device when the pc is locked. But a new way to control Corsair devices is implemented in the dev builds which should fix wrong colors when unlocked. Please give feedback if it works as expected. https://ci.appveyor.com/project/antonpup/aurora/branch/dev/artifacts

**Comment by selmansavas** [comment]
Just tried the link you provided. Works flawlesly, thank you so much! I will switch back to Aurora from now on!
