### ISSUE TITLE
Possibility to separate mouse and headset lighting settings

### ISSUE THREAD

**Issue by Clessiah** [antonpup/Aurora#218]
Some RGB headsets are wireless. I am wondering whether it is possible to keep the LED on the headset off when using Aurora to prolong battery life.

**Comment by brainbug89** [comment]
Maybe there is a setting at your device setting to deactive the SDK support for your headset?

**Comment by Clessiah** [comment]
The headset is Logitech G933. There is one setting to allow/disallow all Logitech devices to be controlled by third party application, but no setting for individual devices.

**Comment by antonpup** [comment]
I can add 3 options: "Disable Mouse Lighting", "Disable Headset Lighting", and "Disable Keyboard Lighting"

Each function is self explanatory. It will work out for Corsair and Razer SDKs, but for Logitech headsets and mice are bundled together in one command. So disabling mouse and/or headset lighting will result in both Logitech mouse and headset being turned off.

**Comment by Clessiah** [comment]
Not bad. At least it'll work with Logitech headset + Logitech keyboard + some other brand mouse setup.

**Comment by Morfildor** [comment]
If logitech keyboard and mouse are not bundled together in one command, I could benefit from that. My mouse lighting is not working at the moment.
