### ISSUE TITLE
Aurora Defaulting Ducky One 2 to profile one

### ISSUE THREAD

**Issue by 28lachie** [antonpup/Aurora#2188]
Hi, Auroras great and I love the fact that the ducky one 2 has full support but there is just one thing that does not seem to be working but I could be missing something.

If I have missed the answer I'm sorry but I couldn't find any issues or posts about it.

Basically macro support doesn't work on the ducky because aurora seems to be forcing profile 1 on the keyboard and only profile 2-5 works for macros so I was wondering if macro functionality is still possible? Like it makes sense that it would if you could change to profile 2. Anyway thanks if I'm missing something I'm sorry

**Comment by Lexevolution** [comment]
Unfortunately when any Ducky keyboard is being controlled by the PC, macros are disabled. This was by Ducky's design, however, I have recently made a [Pull Request](https://github.com/antonpup/Aurora/pull/2263) which makes it so whenever you turn Aurora off or stop the lighting, it will go back to the profile you set it to.
