### ISSUE TITLE
Add support for Redragon keyboards

### ISSUE THREAD

**Issue by rjindael** [antonpup/Aurora#2193]
Please add support for the following device:

**Device Name:** Redragon devices (specifically keyboards)

**Device Website:** https://www.redragonzone.com/

Redragon devices account for a vast majority of quality full-RGB keyboards at a budget. It would be imperative to add them considering the following factors:
- Most people do not want to shell out $60 or more for a RGB keyboard.
- Redragon's RGB protocol works over HID, with no SDK needed
- Many, many people use Redragon keyboards (including myself)

I have found documentation for the K556 Devajaras HID protocol. I wouldn't doubt that this documentation extends to Redragons full line of keyboard products, as taking a look at most of it it seems to be the same for my keyboard (K582 Surara.) The documentation is available here: https://gitlab.com/CalcProgrammer1/OpenRGB/-/wikis/Redragon-K556-Devarajas

**Comment by diogotr7** [comment]
Unfortunately this is impossible. The firmware on the keyboards does not support real-time lighting. This means any lighting updates are written which is slow and uses up write cycles on the flash of the device. Some work has been done on the firmware of these devices on the OpenRGB discord, but on stock configureation this cannot be done.

**Comment by aleksandr1592** [comment]
**DO NOT INSTALL OPENRGB UNLESS YOU KNOW WHAT YOU DOING!**
Openrgb killed my redragon k621 keyboard with no way to repair it. So double-check if your keyboard is compatible with openrgb.
