### ISSUE TITLE
Uniwill not initializing on Intel Whitebook qc7

### ISSUE THREAD

**Issue by Djerii** [antonpup/Aurora#2194]
### Expected Behaviour
Keyboard lighting should work as shown in Aurora. Uniwill should be renamed to Komplett/XMG/etc as in version 7.2 beta posted here:
https://www.notebookchat.com/index.php?topic=105082.0

### Actual Behaviour
I can select Uniwill 550 (ISO) and nordic layout and it shows as my keyboard. when typing the colors change in Aurora but not on the actual keyboard. Uniwill doesn't get Initialized. It should?
I've got a PS4 controller working but not the keyboard.

### Reproduction steps
I have the latest Control Center 2.2.0.18, latest Aurora Build and drivers installed. I choose my keyboard in Devices and Wrappers. Tried reinstalling Windows.

### Frequency
Every time. I have never got it to work.

### Aurora Version:
I've tried several different versions. Now running 0.8.1

### Previously an Issue?
Don't know.

### Log
[INFO] 19:50:19: 

Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Executing Directory: C:\Program Files\Aurora
Launch Directory: C:\Program Files\Aurora
Processor Count: 12
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.8.1

[INFO] 19:50:20: [ASUS] Could not find Asus Aura SDK, please install version v1.07.71
[INFO] 19:50:20: Loading Configuration
[INFO] 19:50:20: Loading Plugins
[INFO] 19:50:20: Loading KB Layouts
[INFO] 19:50:21: Loading Input Hooking
[INFO] 19:50:21: Loading RazerSdkManager
[INFO] 19:50:21: RazerSdkManager loaded successfully!
[INFO] 19:50:21: Loading Applications
[INFO] 19:50:24: Fetching latest pointers
[INFO] 19:50:24: Loading Device Manager
[INFO] 19:50:24: Loading LGS DLL
[ERROR] 19:50:24: Logitech LED SDK could not be initialized. (LogiLedSetTargetDevice or LogiLedSaveCurrentLighting failed)
[INFO] 19:50:24: Device, Logitech, was not initialized
[ERROR] 19:50:24: RGB.NET device (Corsair), Exception! Message: Error in the application.
[INFO] 19:50:24: Device, Corsair, was not initialized
[INFO] 19:50:24: Razer device, Initialized
[INFO] 19:50:30: Device, Razer, was initialized
[ERROR] 19:50:30: Roccat device, Exception! Message:System.Exception: No devices connected
   at Aurora.Devices.Roccat.RoccatDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Roccat\RoccatDevice.cs:line 213
[INFO] 19:50:30: Device, Roccat, was not initialized
[ERROR] 19:50:30: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 71
[INFO] 19:50:30: Device, Clevo Keyboard, was not initialized
[INFO] 19:50:30: No Cooler Master devices successfully Initialized!
[INFO] 19:50:30: Device, Cooler Master, was not initialized
[ERROR] 19:50:30: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 58
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 55
[INFO] 19:50:30: Device, SteelSeries, was not initialized
[INFO] 19:50:30: No Wooting devices successfully Initialized!
[INFO] 19:50:30: Device, Wooting, was not initialized
[INFO] 19:50:30: Device, SoundBlasterX, was not initialized
[INFO] 19:50:30: Device, LightFX, was not initialized
[ERROR] 19:50:30: Drevo Radi SDK could not be initialized.
[INFO] 19:50:30: Device, Drevo, was not initialized
[ERROR] 19:50:30: Device YeeLight encountered an error while connecting. Exception: System.Net.Sockets.SocketException (0x80004005): The requested address is not valid in its context 0.0.0.0:55443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Socket.Connect(IPAddress address, Int32 port)
   at Aurora.Devices.YeeLight.YeeLightDevice.Connect(IPAddress lightIP, DoWorkEventArgs token) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\YeeLight\YeeLightDevice.cs:line 157
   at Aurora.Devices.YeeLight.YeeLightDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\YeeLight\YeeLightDevice.cs:line 48
[INFO] 19:50:30: Device, YeeLight, was not initialized
[INFO] 19:50:30: Device, Asus, was not initialized
[INFO] 19:50:30: Vulcan device not initialized
[INFO] 19:50:30: Device, Vulcan, was not initialized
[INFO] 19:50:32: Device, Uniwill, was not initialized
[INFO] 19:50:32: Device, Ducky, was not initialized
[INFO] 19:50:32: Starting GameStateListener
[INFO] 19:50:32: Retrying Device Initialization
[INFO] 19:50:32: Listening for game integration calls...
[INFO] 19:50:32: Loading ResourceDictionaries...
[INFO] 19:50:32: [IPCServer] Pipe created 34739275
[INFO] 19:50:32: [AuroraCommandsServerIPC] Pipe created 44644735
[INFO] 19:50:32: Loaded ResourceDictionaries
[INFO] 19:50:32: Loading ConfigUI...
[DEBUG] 19:50:33: Trying to get game path for: 209870
[DEBUG] 19:50:33: Trying to get game path for: 730
[DEBUG] 19:50:33: Trying to get game path for: 570
[DEBUG] 19:50:33: Trying to get game path for: 239140
[DEBUG] 19:50:33: Trying to get game path for: 219150
[DEBUG] 19:50:33: Trying to get game path for: 232090
[DEBUG] 19:50:33: Trying to get game path for: 49470
[DEBUG] 19:50:33: Trying to get game path for: 43160
[DEBUG] 19:50:33: Trying to get game path for: 241930
[DEBUG] 19:50:33: Trying to get game path for: 200010
[DEBUG] 19:50:33: Trying to get game path for: 270450
[WARN] 19:50:33: Could not find an AutoNode getter method for field '_ParsedData' of type 'JObject'. It will not be automatically populated.
[DEBUG] 19:50:33: Trying to get game path for: 41070
[DEBUG] 19:50:33: Trying to get game path for: 257510
[DEBUG] 19:50:33: Trying to get game path for: 200510
[ERROR] 19:50:55: Logitech LED SDK could not be initialized. (LogiLedSetTargetDevice or LogiLedSaveCurrentLighting failed)
[INFO] 19:50:55: Device, Logitech, was not initialized
[ERROR] 19:50:55: RGB.NET device (Corsair), Exception! Message: Error in the application.
[INFO] 19:50:55: Device, Corsair, was not initialized
[INFO] 19:50:55: [ASUS] Could not find Asus Aura SDK, please install version v1.07.71
[INFO] 19:51:06: Retrying Device Initialization
[ERROR] 19:51:06: Roccat device, Exception! Message:System.Exception: No devices connected
   at Aurora.Devices.Roccat.RoccatDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Roccat\RoccatDevice.cs:line 213
[INFO] 19:51:06: Device, Roccat, was not initialized
[ERROR] 19:51:06: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 71
[INFO] 19:51:06: Device, Clevo Keyboard, was not initialized
[INFO] 19:51:06: No Cooler Master devices successfully Initialized!
[INFO] 19:51:06: Device, Cooler Master, was not initialized
[ERROR] 19:51:06: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 58
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 55
[INFO] 19:51:06: Device, SteelSeries, was not initialized
[INFO] 19:51:06: No Wooting devices successfully Initialized!
[INFO] 19:51:06: Device, Wooting, was not initialized
[INFO] 19:51:06: Device, SoundBlasterX, was not initialized
[INFO] 19:51:06: Device, LightFX, was not initialized
[ERROR] 19:51:06: Drevo Radi SDK could not be initialized.
[INFO] 19:51:06: Device, Drevo, was not initialized
[ERROR] 19:51:06: Device YeeLight encountered an error while connecting. Exception: System.Net.Sockets.SocketException (0x80004005): The requested address is not valid in its context 0.0.0.0:55443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.Socket.Connect(IPAddress address, Int32 port)
   at Aurora.Devices.YeeLight.YeeLightDevice.Connect(IPAddress lightIP, DoWorkEventArgs token) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\YeeLight\YeeLightDevice.cs:line 157
   at Aurora.Devices.YeeLight.YeeLightDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\YeeLight\YeeLightDevice.cs:line 48
[INFO] 19:51:06: Device, YeeLight, was not initialized
[INFO] 19:51:06: Device, Asus, was not initialized
[INFO] 19:51:06: Vulcan device not initialized
[INFO] 19:51:06: Device, Vulcan, was not initialized

**Comment by Djerii** [comment]
Nvm. Found the fix in your discord! 👍

**Comment by malcom2073** [comment]
@Djerii how did you fix this?

**Comment by Djerii** [comment]
> @Djerii how did you fix this?

Check their discord and search for tongfang. You will need a .dll to get it working.

My rgb's glitches and haven't found a fix for it. So let me know if you get the same result and resolve it :)

**Comment by malcom2073** [comment]
Thanks! I found, it, and also talked to DrMeteor who wrote that plugin. They pushed the source code up and I've been playing with it, I think I've found the bug that causes the flickering! I'll let you know if I can get it polished up and working smooth

**Comment by Djerii** [comment]
Np.
Nice! Thanks! Would really appreciate it!
Merry Christmas 🎅
