### ISSUE TITLE
Keyboard layout automatic detection is not working correctly

### ISSUE THREAD

**Issue by Clessiah** [antonpup/Aurora#22]
My keyboard is US layout. Automatic detection gives me [this layout](http://i.imgur.com/6ija3W3.png) instead.

Also, it seems I have to restart Aurora when I change the layout for it to come into effect, which is fine but I didn't see any related instruction.

**Comment by antonpup** [comment]
The automatic detection looks at your computer localization and loads up that keyboard layout. It's assuming that if you're in UK, then you gotta be using a UK keyboard.

But right below both preference selections, it states that you need to restart Aurora for changes to take effect. I'll see about making it a bit more visible.

**Comment by Clessiah** [comment]
You are right. I am blind. I was looking under the checkbox and did not realize there is a line above it.

My computer's region is Canada, which uses UK spellings but we only use US keyboard layout.

**Comment by antonpup** [comment]
Repositioned the notice above the two selections and made it bold. Will be available in the next version.

Thank you for the report.
