### ISSUE TITLE
Ambilight flashes with certain applications

### ISSUE THREAD

**Issue by gyorokpeter** [antonpup/Aurora#2200]
### Expected Behaviour

Ambilight should be steady and reflect what is on the screen.

### Actual Behaviour

When running certain full-screen apps like Starcraft II, the ambilight will rapidly flicker on and off.

### Reproduction steps

Set up the desktop profile with Ambilight in either "entire monitor" or "foreground application" mode, such that the light changes from Ambilight are clearly visible when the screen content changes. Then start StarCraft II.

### Frequency

Always.

### Aurora Version:

beta v0.8.1

### Previously an Issue?

Don't know

**Comment by diogotr7** [comment]
Do the logs say anything useful? Please upload one. I'm not sure what this could be caused by. 
Do you have HW Acceleration turned on in the layer? 
Do you have multiple Ambilight layers running? 
Does setting different ambilight qualities and update rates change the fllickering?

**Comment by gyorokpeter** [comment]
@diogotr7 Looks like enabling HW Acceleration solves it. I had no idea it would to that, and it's still not clear what the impact of using it will have on other programs.

**Comment by diogotr7** [comment]
HW Acceleration, when it works is better in general. It uses the desktop duplication API which gives better performance and works in fullscreen games. The issue with it is it might not work for everyone, and can only be used in one layer at a time. You should also see decreased CPU load if you have the option enabled.
