### ISSUE TITLE
Interactive effects on all profiles?

### ISSUE THREAD

**Issue by the27club** [antonpup/Aurora#221]
Is there any way to have an option to apply interactive effects on all profiles?

**Comment by caw1** [comment]
yeah this would be very nice.

**Comment by antonpup** [comment]
There will be an option to add an interactive effect to any profile you want. But it's not a "global interactive effect", you will have to configure each one.

**Comment by caw1** [comment]
will this implemented in the next update or do i have to do something with the actual version?

**Comment by antonpup** [comment]
If you compile the dev version, you can add an interactive effect to any profile now. It's not "global interactive effect" like I said before, but it works.

**Comment by caw1** [comment]
i´ve tried several thing but no results for me.. :( is there anywhere a step by step introduction how to compile and edit the dev version? sorry :(
