### ISSUE TITLE
Aurora & Keyboard crash / hang every 5-15 seconds

### ISSUE THREAD

**Issue by henpenben** [antonpup/Aurora#2210]
### Expected Behaviour
it don't be broken lol

### Actual Behaviour
Every 5-15 seconds, all lights on the keyboard blink off (even ones like the capslock  or numlock lights). If try to type when this happens, the keyboard does not respond (and it does not buffer my inputs). If I was already typing when it happens, whatever letter I last pressed is repeated until it comes back.

### Reproduction steps
Do anything at all? I tried reinstalling, I tried making a new profile with _no_ effects. I tried changing bitmap settings. The only thing that stopped it from happening was checking "disable keyboard lighting" in the settings.

I checked the logs. After initializing devices, there is nothing logged.

I am using a Cooler Master Master Keys Pro M RGB

### Frequency
Always

### Aurora Version:
0.8.1

### Previously an Issue?
it used to not be... I'm not sure if I had auto-update installed. I first installed the program at 0.7.1 and it was not an issue.

**Comment by diogotr7** [comment]
Mayube try updating the firmware? I changed how that specific device works in the development versions, so also give that a try and tell me if anything changed
https://ci.appveyor.com/project/antonpup/aurora/branch/dev/artifacts

**Comment by henpenben** [comment]
I was not able to find a firmware update anywhere (at least on CM's website, although I didn't look that hard)

however, the development version (0.8.1+897) seems to have fixed the problem! Thank you!
