### ISSUE TITLE
Kraken X61/Asetek 690lc coolers

### ISSUE THREAD

**Issue by Firehawke** [antonpup/Aurora#2212]
Please add support for the following device:

**Device Name:** NZXT Kraken X61 (Uses ASETEK 690lc)

**Device Website:** https://www.nzxt.com/products/kraken-x61

Liquidctl supports the device via the ``--legacy-690lc`` option.
Details at https://github.com/jonasmalacofilho/liquidctl/blob/master/docs/asetek-690lc-guide.md
Not expecting you to support the cooling side of things, but it'd be nice if you could allow the color to be controlled so I can monitor temperature that way. Maybe add a LocalPCInfo section to poll the liquid temperature?

**Comment by diogotr7** [comment]
Best way to get this supported would be touse the developemnt builds along with OpenRGB. I think adding all of the reverse engineered devices directly into aurora doesnt make much sense, supporting OpenRGB instead allows for more flexibility (and for more devices to be added without nedding to change aurora).

You'll need the aurora development builds ( or wait for the next stable release): https://ci.appveyor.com/project/antonpup/aurora/branch/dev/artifacts

And also OpenRGB: 
https://gitlab.com/CalcProgrammer1/OpenRGB

**Comment by Firehawke** [comment]
I opened issue 684 at Gitlab for OpenRGB on this subject.

We'll see if anyone's interested in tackling it!

I guess this can now be closed if you wish.
