### ISSUE TITLE
Logitech G102/G203 Lightsync not working at all?

### ISSUE THREAD

**Issue by PacuFTW** [antonpup/Aurora#2219]
I really want to use my G102 Lightsync with Aurora, but the leds don't turn on at all. I tried with OpenRGB too but to no avail. Can you please fix this if I may ask?

**Comment by DvoraNoob** [comment]
Same here.

**Comment by romulolassoares** [comment]
I have same problem here

**Comment by PacuFTW** [comment]
> I have same problem here

It will never get fixed because it's not included in the Logitech SDK, unless Logitech includes it which is unlikely.
