### ISSUE TITLE
Display CPU Usage very slow to respond to decreasing usage

### ISSUE THREAD

**Issue by write-only-memory** [antonpup/Aurora#222]
I have the "display CPU usage on keyboard" option enabled, and while it detects increasing CPU usage pretty well, it doesn't seem to want to come back down. For example, I run a CPU benchmark program, all the F-keys light up as they should with a short delay. However, when I stop the benchmark program (idle CPU now), it takes a very long time for the F-key lights to return from 100% usage to 0%. The last three F-keys (10-12) change colour immediately, but the rest take a very long time to update (multiple minutes). I hope this makes sense. I can upload a video of it if required.

Thanks in advance

EDIT: The feature seems to be kinda hit and miss currently. Sometimes its quick to respond to CPU usage changes, other times it'll completely miss/ignore spikes.

**Comment by antonpup** [comment]
I'll see if I can make it more accurate. But I originally made it update every once in a while, and made it change gradually based on how big the difference between two samples was. It was a performance fix.

**Comment by write-only-memory** [comment]
>change gradually based on how big the difference between two samples was

Ah yep, that makes perfect sense then. Explains why it takes so long to go from 100 to 0. Thanks for looking into it.

**Comment by antonpup** [comment]
I just tested with Prim95, and the CPU usage goes up quickly and then comes back down quickly as well... So I guess I resolved this issue a while back and didn't realize it.

![Prime95 test](https://puu.sh/t0u7i/1aba2e3d1f.gif)
