### ISSUE TITLE
Missing Light Input G910 Orion Spectrum

### ISSUE THREAD

**Issue by JarTheHead** [antonpup/Aurora#224]
When I try to set all of my keys to a different color on Aurora, everything changes color except the G910 logo on the bottom. Will this be fixed in the future? I know it is a minor problem, so I understand if it is disregarded.
![capture](https://cloud.githubusercontent.com/assets/24198002/20645550/99bf1dd6-b416-11e6-8c25-a519c20de5bd.PNG)
![img_1239 1](https://cloud.githubusercontent.com/assets/24198002/20645551/9cafb0f0-b416-11e6-8381-bd5783da0f4d.JPG)

**Comment by antonpup** [comment]
Fixed in dev
