### ISSUE TITLE
Aurora opens multiple crash windows.

### ISSUE THREAD

**Issue by ghost** [antonpup/Aurora#2256]
I created a layer with custom mouse layout but it was very slow so i tried to remove it. By doing so, aurora opened a lot of fatal error windows (i cant even read them) and then crashed. ![Capture d’écran 2021-01-12 130604](https://user-images.githubusercontent.com/65017947/104312474-f419d400-54d6-11eb-9ade-d622fe17bc0f.png)The layer is still there and i can't create a new one. I can still edit the older ones but if i create a new one i get fatal error windows and aurora crashes. How could i remove this layer without loosing my profile?

I have aurora beta v0.8.1+65.

**Comment by gitmacer** [comment]
I don't know what you mean with **custom mouse layout** but you can find the save data under %Appdata%\Aurora

**Comment by ghost** [comment]
Thanks for the answer. I have already copied the layers and overlays one by one in an other profile and it works (sorry i should have closed the topic). **custom mouse layout** is in **devices & wrappers** on preferred mouse (see picture). I think it wasn't compatible with my devices so it broke everything.
![Capture d’écran 2021-02-22 174323](https://user-images.githubusercontent.com/65017947/108739987-79ac8d00-7535-11eb-81b7-d55ecd5fca90.png)
