### ISSUE TITLE
Can I use normal lighting in CUE along with just synchronized game lighting?

### ISSUE THREAD

**Issue by lolrepeatlol** [antonpup/Aurora#226]
I know this isn't an issue... but I would like to know before I buy my peripherals- can I use CUE normally on the desktop and then use Aurora for game lighting?

**Comment by brainbug89** [comment]
Not at the current version. But I asked the same and IIRC antonpup built in this feature.

**Comment by antonpup** [comment]
In dev build I added an option for desktop profile to turn off all lighting SDKs, so their respectable utilities can take over lighting. And once a game or app that is supported by Aurora is launched, it would reestablish the connection to the SDKs.

This works with all peripherals. Logitech, Corsair, Razer, Cooler Master, and Clevo.

**Comment by lolrepeatlol** [comment]
Thanks! I also would like to know- what lighting effects are built into Aurora? I was thinkng maybe instead of the M65 Pro and K70 I'll just grab a K70 and a g900 to sync that together instead.

**Comment by antonpup** [comment]
You're asking me to describe the entirely of Aurora. It will work regardless of which RGB keyboard you have, as long as it's supported. Effects don't change from brand to brand, they're all universal.

With that said, you can find a list of some effects on the [main page](https://github.com/antonpup/Aurora) of this repo, as well as a few demo videos.
