### ISSUE TITLE
Keyboard goes blank on left side after joining Dota match

### ISSUE THREAD

**Issue by vulture1162** [antonpup/Aurora#228]
Just installed this a few days ago and it's been great on my brand new Logitech G910. Except when I'm playing Dota 2 the keyboard seems to go blank from the Escape - F3 all the way down the keyboard on the left side. Even once I exit Aurora + Logitech Gaming Software it still stays this way. Need to force a restart to get the keyboard working again. 

![img_20161203_003147330](https://cloud.githubusercontent.com/assets/4745128/20857103/40ed3100-b8f0-11e6-8ad2-bd8fc461cc8e.jpg)

**Comment by antonpup** [comment]
Sounds like a Logitech issue. Try reinstalling LGS, updating your keyboard firmware.
