### ISSUE TITLE
Crashing after install

### ISSUE THREAD

**Issue by flustix** [antonpup/Aurora#2291]
### Expected Behaviour

Aurora starts after install

### Actual Behaviour

it crashes instantly

### Reproduction steps

install latest version, open in the start menu

### Frequency

every time

### Aurora Version:

0.8.1

### Previously an Issue?

Don't know

**Comment by HumbleDeer** [comment]
Have you uninstalled it to verify it's not just a one time fluke? That'd be important to know as there's no crash log provided.

**Comment by flustix** [comment]
yeah i reinstalled it 4 times

**Comment by flustix** [comment]
But the .zip version works fine
