### ISSUE TITLE
Need people with foreign layouts

### ISSUE THREAD

**Issue by antonpup** [antonpup/Aurora#23]
I will need to find someone who has one of the following keyboards to test and fix foreign keyboard layouts.
- [ ] Logitech - Japanese layout
- [ ] Corsair - French layout
- [ ] Corsair - Deutsch layout
- [ ] Razer - French layout
- [ ] Razer - Deutsch layout

I will add more to this list as I add more keyboard layouts.

**Comment by silphnaberrie** [comment]
This is Screenshots of Logitech Japanese layout(G810) on LGS.
Aurora can't controls 5keys and logo on G810 JP layout.
Screenshot_1:
This is Graphic of G810 Japanese layout on LGS.

Screenshot_2:
Aurora can't controles those 5keys and logo dimmer. (red color on Screenshot_2)
I added keycode(DEC) of those.

Im glad if it help.
![screenshot_1](https://cloud.githubusercontent.com/assets/19863253/15988401/30719486-308a-11e6-9c6b-873981d5bf26.JPG)
![screenshot_2](https://cloud.githubusercontent.com/assets/19863253/15988402/3513fd58-308a-11e6-9a73-6a3cd8bf52af.JPG)

**Comment by antonpup** [comment]
@silphnaberrie I will see about adding support for those keys. But at a quick glace, I had issues with making 220 and 226 light. The Logo cannot be controlled as it's not part of the SDK. When it's updated in the SDK, I will add support for it.

Thank you for the screenshots.

**Comment by silphnaberrie** [comment]
@antonpup I Understood it. I'll test after Aurora support. ;)

**Comment by silphnaberrie** [comment]
@antonpup Thanks for Update. I've checked JP layout of G810. it need to fix some points. pls see screenshot.

'Half/Full width"(Keycode 229) is uncontrollable on Aurora. but Dimmer is lighting when selected Keycode 220. I think this dimmer controller of Kyecode 229 is 220's. (checked by Rainbow Shift mode)

![screenshot_1_fix](https://cloud.githubusercontent.com/assets/19863253/16000238/170a576a-3186-11e6-8bdc-40587482c130.jpg)

**Comment by dankar3** [comment]
i'll try to send you Logitech g910 nordic info later today if im not working too late, if needed/wanted that is :)

**Comment by antonpup** [comment]
@silphnaberrie I did the changes you listed there. 0.4.5 will have this.

**Comment by silphnaberrie** [comment]
@antonpup Thanks for great works. text labels are perfectly now :)

2 issues:

'Half/Full width' key still wrong lighting when I checked '\' key(Aurora said, it's 'OEM 5' key. and Aurora uncontrollable OEM 5's light now). can swap light to 'OEM 5' key from 'Half/Full width' key?

Can you put on Half/Full width' key from Tilde key of International layout? (it can control 'Half/Full width' key's light.)

and thank you again. Im very enjoying Aurora with Overwatch. please keep great works :)

**Comment by brainbug89** [comment]
I have a K70 RGB Rapidfire with german layout (Corsair - Deutsch layout).

Everything seems fine, but Z and Y are inverted. (correct layout at Aurora GUI, but maybe inverted keycodes)

**Comment by antonpup** [comment]
I will swap the two keys. Thank you.

**Comment by Mensiys** [comment]
i have a Logitech japanese layout G910.
that can't light up two keys.　please check my screenshot.

![screenshot](https://i.gyazo.com/8df5415831d94b88829efbef1d9f1a88.png)

**Comment by brainbug89** [comment]
> I will swap the two keys. Thank you.
Still inverted at version 0.6.0 :wink:

**Comment by Mensiys** [comment]
i have a Logitech G910 japanese layout keybord.
Aurora can not control 2 keys. please check my screen shot.
![g910_03](https://cloud.githubusercontent.com/assets/24567684/21841823/555887f6-d827-11e6-850a-818f140a1cf9.jpg)
