### ISSUE TITLE
GTA5 not working

### ISSUE THREAD

**Issue by rakosi2** [antonpup/Aurora#230]
Aurora detects that I started gta5 and my keyboard goes all white. Aurora is showing what I have on the preview while i play gta5 like I preview chomp(all red) with police and that is what I see constantly. I tried clicking patch logitech several times. I tried 5.1d and dev version on windows 10 with same results. I then tried bf3 but got a static colors and then tried rocket league but I think that goes with issue#227.  The skype works as pause button flashes brown. I am running a corsair k95.

**Comment by antonpup** [comment]
I am confused about your report. So, GTA 5 isn't functioning properly? Is BF1 not functioning properly? Or is Skype integration not working properly?

For BF1, you need to use the dev build and patch Logitech with it for lighting to work properly.
GTA 5 should function fine, I will check if Rockstar changed something.
Skype should also function properly.

**Comment by rakosi2** [comment]
I was trying to say that Aurora can detect Skype's unread messages and flash brown but Aurora is not working with bf3, gta5, and rocket league as I am seeing what I set in the preview tab. For an example, in gta5 I turn on wanted level in the preview and it flashes the whole time in game.

**Comment by antonpup** [comment]
Try this fix #42 .

As for the GTA 5 preview, if you set the police wanted level and leave it on, it will play in the game. So before playing GTA 5, make sure that the previews are all off.

**Comment by rakosi2** [comment]
I have visual C++ 2015 14.0.24215 x64 and x86 installed if that is what you mean by fix #42. As for the preview, how do you turn it off? I don't see any checkbox or anything to enable/disable preview.

**Comment by rakosi2** [comment]
Both steam and Aurora is ran as an administrator and gta5 launched from steam's menu. In task manager, UAC Virtualization is grayed out for both Aurora, GTA5, and GTA5Launcher so I am assuming that they are running as an administrator. Once GTA5 in started up, even when I switch characters, my K95 is still all white. I try to add a wanted level in the preview tab and now it is all white with f-keys flashing. 

For the logitech LED SDK patch, do I need logitech's suite installed even though I don't have a logitech keyboard?

**Comment by rakosi2** [comment]
YES, YES You do need to install the Logitech suite for the patch to work. I also tried gta5 without logitech opened and did not work. So can you please change the requirements to include the Logitech suite if it is needed for the rgb to be passed through to Aurora.

**Comment by antonpup** [comment]
You shouldn't need to install Logitech Gaming Software... I'll check it out.

**Comment by rakosi2** [comment]
So now it sometimes works and sometime it doesn't. Right now when I play GTA Online it is all white but when I am chased by police then my F keys are alternating red/blue while all other keys are still white. Also I have noticed that in Devices and Wrappers tab, every time I click retry for connected device, it sometimes says K95 and sometimes says Not Initialized.

**Comment by rakosi2** [comment]
Ok so if I go from story mode to online so let's say trevor to online then in online my keyboard stays brown while I am in online so Aurora is not detecting that I am in Online mode. Also I just needed to install Logitech Gaming Software to get the LogitechLed.dll without it I get a large error.

**Comment by antonpup** [comment]
@simon-wh Can you debug GTA 5 not properly detecting game states? Perhaps for GTA 5, we could use a range of colors to detect game states. For example: R [100,105] G [0,5] B [35. 40] is some state. So if Rockstar decides to slightly change the color of Online or Trevor state, then Aurora hopefully could still detect correct states.

**Comment by rakosi2** [comment]
I would like to help debug, I am currently playing GTA Online and I have built Aurora from the Dev branch, I just don't know how I can see the values and the debug output just says a bunch of keyboards "was not initialized"

**Comment by antonpup** [comment]
@rakosi2 For GTA 5, the following code is responsible for detecting the Game State. It's detected based on the reported background color. https://github.com/antonpup/Aurora/blob/dev/Project-Aurora/Profiles/GTA5/GSI/GameState_GTA5.cs#L193

And this code is responsible for actually setting the color that will be drawn to the keyboard from a previously determined Game State. https://github.com/antonpup/Aurora/blob/dev/Project-Aurora/Profiles/GTA5/GameEvent_GTA5.cs#L53

It's just not triggering the correct Game State, thus returning a PlayerState.Undefined. That does not get drawn. Rockstar has done this in the past, where they changed the color values by one. So Aurora wasn't detecting states properly. That is why I suggested that we try detecting ranges instead.

If you fix it, feel free to send a pull request.

**Comment by rakosi2** [comment]
I modified Aurora to output the color to the console and when I go into GTA Online, the GameState_GTA5 function is not being called so it's something other than a color difference.

**Comment by rakosi2** [comment]
In NetworkListener.cs, the StreamReader reading the game state does not read anything when I switch to gtaonline so Aurora maintains what color it was last including anything I set in the preview tab. I have no clue how the IPCServer works so I will leave the rest to you guys.

**Comment by simon-wh** [comment]
I've just done some testing with GTA 5 and I got it working after I ran both Aurora and both GTA5 exes as admin, installed Logitech Gaming Software and patch the Logitech SDK. After that, it worked as normal, except for the background colour of multiplayer not being detected as it was drastically different than before.

I've changed it now for the state detection that it'll round all the values to the closest 5 to prevent issues with slightly changed values of each state. @rakosi2 I'm not sure why it isn't getting anything when you're in online, but if you get cops, if it is receiving game states properly it'll refresh and should show the correct colour if it wasn't before.

**Comment by rakosi2** [comment]
OK thanks for the update, Single player works with correct colors but when I switch to Multiplayer, it switches back to white. In the logs I get "12/27/2016 12:23:11 PM: Undefined color - Color [A=255, R=255, G=0, B=255]" after adding the values to GameState_GTA5.cs it started working.

**Comment by simon-wh** [comment]
@rakosi2 Is this with or without the commit that referenced this issue?

**Comment by rakosi2** [comment]
I haven't tried all of the colors yet but the main characters in single player, multiplayer and police works

**Comment by rakosi2** [comment]
So I have added a checkbox to Aurora to Bypass the cases and just display what gta5 gives and I think that in online, you are displayed your Crew's color because my crew color is pink and that is what I see while I play online.

**Comment by rakosi2** [comment]
Ya after I left my Crew, it started doing the issue again with it maintaining single-player colors after switching to multiplayer, so the color during multiplayer is up to your crew color. I would recommend just passing any unknown colors as the fill background because different crews are going to have different colors.

**Comment by simon-wh** [comment]
@rakosi2 I've just made a commit that'll use the background colour from the game if it cannot be detected

**Comment by rakosi2** [comment]
Ok thanks, the only thing with this update is that as you start GTA5 the keyboard led is off unlike the all white as it was (well, it maintains the last color so if you close gta and start it again then it will show last color, so there needs to be a default color when GTA starts). And other then there is no color change if I am not in a crew(nothing you can do about this) this is good thank you.

**Comment by simon-wh** [comment]
What colour does it give when you're not in a crew? I can set it to use white by default for GTA, but the issue with it using the previous colour on restart is something we can only really deal with if we track the process exiting or starting.

**Comment by rakosi2** [comment]
None, it just maintains the last color as no update gets sent

**Comment by simon-wh** [comment]
@rakosi2 The commit above resolves the issue with it keeping the previous game state colour on game restart. I've also brought back the Ambient Colour option which will be used as the startup colour for the game. Do you know if Online without a crew is actually sending out an update or not?

**Comment by antonpup** [comment]
I am marking this as resolved. If it still persists, feel free to carry the discussion on.
