### ISSUE TITLE
Backslash key not reacting to interactive effects on G810

### ISSUE THREAD

**Issue by eVanasse** [antonpup/Aurora#231]
My software versions are
Aurora: 0.5.1d
LGS: 8.88.28 (Firmware: 102.3.27)

**Comment by antonpup** [comment]
What is your keyboard layout?

**Comment by eVanasse** [comment]
I don't know. How can I find out?

**Comment by eVanasse** [comment]
It's US layout.

**Comment by BronsonLe** [comment]
Do you have the source code, as I want to fix the backslash myself and enable RGB on the media buttons. Since I have C++ background.

**Comment by antonpup** [comment]
Does this still happen on latest version?

**Comment by eVanasse** [comment]
No! Last update fixed it. Thank you!
