### ISSUE TITLE
Corsair Wrapper. question

### ISSUE THREAD

**Issue by DiaoticHaze** [antonpup/Aurora#232]
Is there anyway using aurora that could allow a orion g910 to simulate a corsair, so you can do fun keyboard effects like these.
https://www.youtube.com/watch?v=GQi7uexxYjs

**Comment by antonpup** [comment]
Those are profiles for CUE. Writing a wrapper for Corsair will not enable you to use those profiles. Likewise for Razer or Logitech. The utility is communicating with hardware directly.

The only reason to write a wrapper is for games or apps that use their lighting sdk to send lighting information to Aurora instead of their designed utility.

In terms of Corsair, I have only seen one game with lighting support. So writing a wrapper for it isn't of high priority.

**Comment by DiaoticHaze** [comment]
Thank you for the reaponse! Is it possible to use CUE RGB profiles on my
logitech?

On Dec 3, 2016 5:22 PM, "Anton Pupkov" <notifications@github.com> wrote:

Those are profiles for CUE. Writing a wrapper for Corsair will not enable
you to use those profiles. Likewise for Razer or Logitech. The utility is
communicating with hardware directly.

The only reason to write a wrapper is for games or apps that use their
lighting sdk to send lighting information to Aurora instead of their
designed utility.

In terms of Corsair, I have only seen one game with lighting support. So
writing a wrapper for it isn't of high priority.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/antonpup/Aurora/issues/232#issuecomment-264677551>, or mute
the thread

**Comment by antonpup** [comment]
At the moment, no. It was planned to reverse engineer profiles from CUE and Razer to work with Aurora. I ,unfortunately, will not be able to do that. I will try to provide a similar set of tools/effects that CUE has so people can either recreate those profiles in Aurora, or another programmer can create a utility to convert from CUE to Aurora profile.

I want Aurora to be as close to commercial software as I can make it. And I also am hoping that other people will join in to help this project grow.

**Comment by DiaoticHaze** [comment]
Awesome! If you could get this to work similar to the CUE, I would put money down for it. I'll make sure to spread this forum and product to other logitech G910 users.
