### ISSUE TITLE
G810 layout US - key without light

### ISSUE THREAD

**Issue by DeniSmooth** [antonpup/Aurora#235]
I have a G810 and everything works very well. The only problem is that a key is not recognized by the software, causing that key to be erased. I have tested all available layouts in the software and it still does not work. Using standard Logitech software works normally. The key is the backslash, which is under the backspace and upon enter.

Thank You.

**Comment by antonpup** [comment]
I will test with G810, I got one sent to me recently. But on my G910, \ works fine.

**Comment by DeniSmooth** [comment]
Thanks!

**Comment by DeniSmooth** [comment]
![15322366_1213072418777571_1492926933_o](https://cloud.githubusercontent.com/assets/24403934/20914735/c965752c-bb68-11e6-9d6b-bbdeca70624d.jpg)

**Comment by antonpup** [comment]
That is odd. It should become apparent when I test it. But as far as LGS is concerned, everything is correct in terms of lighting. Which is odd.

**Comment by antonpup** [comment]
![https://puu.sh/sFPi0/41ce5d683f.png](https://puu.sh/sFPi0/41ce5d683f.png)

**Comment by DeniSmooth** [comment]
![capturar](https://cloud.githubusercontent.com/assets/24403934/20927054/d43888c0-bba6-11e6-87d7-72886e3f58e0.JPG)

**Comment by DeniSmooth** [comment]
I think I got it sorted out. It was not a bug, I believe it was my mistake. I believe that the time I selected a zone previously, this key that was deleted was not listed in the selected options ... I have refitted and now it is working. Thank you for your help!
I will reboot the computer to make sure.
