### ISSUE TITLE
Integration of AtmoOrb support

### ISSUE THREAD

**Issue by RickDB** [antonpup/Aurora#237]
Hi,

Recently started playing around with Aurora and patched in our AtmoOrb protocol which are Philips Hue like devices but open source / DIY, early test video here:

https://www.youtube.com/watch?v=YImIF7XOUpQ

Code not neatly integrated yet but wondering if you would like me to add it first, full overview of project here:

http://forum.team-mediaportal.com/threads/diy-atmoorb-a-hue-like-mood-lamp-based-on-particle-photon-with-neopixel-tutorial-added.131901/

https://github.com/ambilight-4-mediaportal/AtmoOrb

Hyperion ambilight support is on my list after this depending on if you approve :)

**Comment by antonpup** [comment]
Looks nice. If you want to send a PR, I can approve. I don't own any of these, so I cannot implement them myself.

**Comment by RickDB** [comment]
Awesome :)

Hopefully can finish up this week and will create PR for it.

**Comment by antonpup** [comment]
If you have any other RGB devices that you would like to include, feel free to PR them as well. Just make sure you're working on the dev branch and not main.

**Comment by RickDB** [comment]
PR #244 created
