### ISSUE TITLE
 Unable to Launch Aurora

### ISSUE THREAD

**Issue by Jsian1** [antonpup/Aurora#2377]
### Expected Behaviour

Aurora should be able to launch 
### Actual Behaviour

unable to launch the program
### Reproduction steps

i had tried reinstalled the program and also edit the Config.json 
### Frequency

Starting from today(23/1/22). yesterday was fine
### Aurora Version:

Aurora v0.8.1+906
### Previously an Issue?

Bo

[2022-01-23 20.51.59.log](https://github.com/antonpup/Aurora/files/7920516/2022-01-23.20.51.59.log)

**Comment by asgraf** [comment]
I currently have similar issue.
The problem started right after the last automatic update of Razer Synapse

**Comment by Jsian1** [comment]
> I currently have similar issue. The problem started right after the last automatic update of Razer Synapse

sorry for late reply.
i had fix it. as you said, the problem start after razer synapse update.
i checked the Program report and it show that aurora unable to launch due to razer.
so i jus uninstall and reinstall my razer synapse and its work

**Comment by melesiv** [comment]
I'm getting a similar issue now. I don't know when it started but as of today I cannot open the actual software window. (it starts and effects my keyboard in the background, however.)

I've tried uninstalling Razer Synapse, it didn't work.

I don't know how to submit logs or anything, apologies.

(Also, sorry for posting on a closed report, but I thought it'd be easier than making a new one.)

**Comment by Masamune3210** [comment]
Please next time, just make a new issue report, it helps avoid false correlation and just keeps everything cleaner and easier to track
