### ISSUE TITLE
Can I get a ban?

### ISSUE THREAD

**Issue by aronj134** [antonpup/Aurora#238]
If I use this would I get a ban in overwatch?

**Comment by antonpup** [comment]
From [F.A.Q.](https://github.com/antonpup/Aurora#faq)

> Q: Can this give me a ban in a video game?
> 
> A: Support for all included games is tested to be sure not to trigger any anti-cheats or produce any suspicious behavior. With that said, the software is to be used at your own risk. We cannot prevent game developers from adding anti-cheats or blocking ways Aurora retrieves information from the game.

Also take a look at a comment I made about this same question: https://github.com/antonpup/Aurora/issues/105#issuecomment-265490763

**Comment by RickDB** [comment]
Thanks, played competitive after reading up here as well and for the short period I played here no issues as well.
