### ISSUE TITLE
System.OutOfMemoryException: Insufficient memory to continue the execution of the program.

### ISSUE THREAD

**Issue by yeroc3103** [antonpup/Aurora#24]
I am unable to launch the application. Looks like some sort of memory leak. The mouse pointer skips across the screen for about 30 seconds and the keyboard is unresponsive. After that, the system works fine but Aurora.exe has high CPU usage and it keeps using more and more memory until the 1.5GB mark then crashes. The Aurora UI never appears, aside from the instructions on how to configure LGS. 

I have a Logitech G810. I am using the latest 64 bit version of LGS - 8.83.85, but older versions had the same behavior. I am also on Windows 10 Pro x64 with all of the prerequisite software installed. I attached the logs, so you can see all of the errors. 
[2016_10_06.zip](https://github.com/antonpup/Aurora/files/310242/2016_10_06.zip)

**Comment by antonpup** [comment]
Is Dota 2 installed? Can I get a few files from your steam folders?
appmanifest_570.acf (This is your Dota 2 manifest file, located in steamapps folder)

**Comment by antonpup** [comment]
Issue has been located, it will be fixed in the next version.

**Comment by yeroc3103** [comment]
Hey. Just letting you know reinstalling Dota 2 fixed this. This is an awesome app. I love it! Keep it up!. I'll let you know if I find any other bugs.
