### ISSUE TITLE
Aurora Color Cycle effect

### ISSUE THREAD

**Issue by Nedo93** [antonpup/Aurora#240]
I'm sorry for I posted a question just half an hour ago, but I would like to know how (if possible) can I set up the effects to simply cycle through colors. I saw there is a color breathing effect that should do the trick, but it will cycle only between 2 colors.

Thank you in advance for answers.

**Comment by DiaoticHaze** [comment]
There is a gradient feature, once selected, click the 3 dots, click on the
color canvas and add and adjust colors there

**Comment by Nedo93** [comment]
But it will just let me create a gradient to shift throgh the keyboard, it won't make me create a cycle effect that will cycle through all colors on all keys like this:
https://www.youtube.com/watch?v=g_PdFBMQ4rw&ab_channel=FemaleFightersId

**Comment by antonpup** [comment]
Will add.

**Comment by Nedo93** [comment]
Thank you bro, you are the man.

**Comment by Nedo93** [comment]
Hi, i'ts me again. I would like to know when you will release this effect color cycle (not to hurry you, just to know if there is a date).

**Comment by antonpup** [comment]
Your request will be bundled along with gradient layers. I am currently aiming to release an update (or at least a test version) before Christmas.

**Comment by Nedo93** [comment]
Thank you for your work man, if there is a site where you are taking some donation, let me offer you a beer.

**Comment by brainbug89** [comment]
> Thank you for your work man, if there is a site where you are taking some donation, let me offer you a beer.

See README.md for donation link: https://github.com/antonpup/Aurora#donations

**Comment by antonpup** [comment]
Update:
![](http://i.imgur.com/ekMUjKV.png)

**Comment by Pandry** [comment]
Love you! <3

**Comment by Nedo93** [comment]
Will this be implemented in a software update or do I have to recompile the code with new additions?

**Comment by antonpup** [comment]
Next update.
