### ISSUE TITLE
Aurora won't start at all

### ISSUE THREAD

**Issue by WyntrHeart** [antonpup/Aurora#2413]
### Expected Behaviour
The program should start when executed

### Actual Behaviour
Nothing happens. Aurora does not open. The Aurora.exe process is not visible in Task Manager

### Reproduction steps
Install Aurora. Double click Aurora.exe or a shortcut to it

### Frequency
Every time

### Aurora Version:
v0.8.1

### Previously an Issue?
Don't know. This is a fresh first time install

**Comment by xrnss** [comment]
Did you figure this one out? I can't seem to get it to open either

**Comment by WyntrHeart** [comment]
Nope. I had to go back to G Hub to control my lighting unfortunately

**Comment by Aytackydln** [comment]
hey, new fork is available and gets updated:
https://github.com/Aurora-RGB/Aurora
