### ISSUE TITLE
Swiss Logitech keyboard layout

### ISSUE THREAD

**Issue by LukasACH** [antonpup/Aurora#242]
I would like to add a swiss keyboard layout for Logitech, and possible for other brands too. I could test it with my G910. But I can't find the necessary documentation to do so, especially where I need to write additional code in.

**Comment by fldeton** [comment]
Sadly there is no possibility to control g-keys and logitech-logo, if you have a swiss layout keyboard. Would it be difficult to program an own layout for aurora? I'm also using a G910. G-Keys stay light blue instead of another colour...

**Comment by LukasACH** [comment]
If you select the German G910 Layout, the keyboard specific keys should work.

**Comment by fldeton** [comment]
Sadly it is not working... The g-buttons and the logo stays light blue and it should be dark blue.

**Comment by antonpup** [comment]
Try the 0.6.0 pre-release #287

**Comment by simon-wh** [comment]
I'm going to use #463 as the main issue for this
