### ISSUE TITLE
Razer Ornata and Logitech G102 Prodigy

### ISSUE THREAD

**Issue by IvanFernan** [antonpup/Aurora#245]
I manage to control the RGB in Razer Ornata Keyboard but the mouse (Logitech G102 Prodigy) not syncing. Using Aurora v0.5.1d.

**Comment by antonpup** [comment]
Will look into.

**Comment by IvanFernan** [comment]
thanks anton for fast response.

**Comment by IvanFernan** [comment]
its working now. I just shutdown my computer and its working perfectly!

**Comment by brainbug89** [comment]
> its working now. I just shutdown my computer and its working perfectly!

Then close this issue :wink:
