### ISSUE TITLE
Key Wave Color Breathing Option

### ISSUE THREAD

**Issue by Running-Banana** [antonpup/Aurora#246]
For the Key Wave under the Interactive Effects (also please add support for any profile to have Interactive Effects) there should be a Rainbow/Color Breathing option. Please add this!!!

**Comment by Running-Banana** [comment]
did u do it?

**Comment by antonpup** [comment]
Check latest version. It allows you to add interactive layer to any profile. And there are breathing/blinking effects.

**Comment by Running-Banana** [comment]
okay thanks :))))))))

**Comment by Running-Banana** [comment]
can you also later add support for the g502 mouse cuz like I have that but
Idk what I should select.

**Comment by antonpup** [comment]
G900 (or any of them will work really)

**Comment by Running-Banana** [comment]
Okay thanks and what is that eye at the bottom of the list do????

**Comment by antonpup** [comment]
You can hide profiles that you don't want to see.

**Comment by Running-Banana** [comment]
Ah okay thanks :))))

**Comment by Running-Banana** [comment]
Also is there like an easy way to do this
https://www.youtube.com/watch?v=u17D7dZKMLk
I know there is like layers and all but like I don't know how to set up the
timings but I got this to work on LGS but like I wanna know how to do it
with aurora cuz u know aurora is better and like has better support :)))

**Comment by Running-Banana** [comment]
Also like I just started playing csgo and like my mouse is getting major
stutters and when i turn off aurora its fine... please fix
