### ISSUE TITLE
ETS2 & ATS Support?

### ISSUE THREAD

**Issue by stbatuhan** [antonpup/Aurora#25]
Would you like to add support for these beautiful games like in asetta corsa? There is already a modding tools and also a mod for the dashboard part. Lighting effects would be awesome.

**Comment by antonpup** [comment]
I can add lighting support to almost any game, but if I don't own the game, then I cannot test it. I will certainly look into it.

**Comment by stbatuhan** [comment]
Ok then i may help about testing as much as i can :) Also about dashboard you can look:
https://github.com/Funbit/ets2-telemetry-server

**Comment by stbatuhan** [comment]
Is there any news about this?

**Comment by antonpup** [comment]
No news about this specifically. I've been improving Razer and LightFX wrappers. Next version of Aurora will support scripting with C# and Python, so people can create their own game integrations.

**Comment by stbatuhan** [comment]
Hmm nice addition but when we will get a new version? Thanks for your reply

**Comment by antonpup** [comment]
After I complete most of this: #87 and when I properly add profiles for most of these: #18 

It's close. I can't say exactly when. But not this week.

**Comment by antonpup** [comment]
A small update. As you can see from #87, I have excluded most of the items listed from next version. So, all I need to do for that is write documentation and include transition effects between profiles. For #18, I will be working on those tomorrow. Will be adding about 4 more profiles (at least that will cover all games I own). So, expect an update next week if all goes according to plan.

**Comment by stbatuhan** [comment]
Perfect, waiting with excitedly :)

**Comment by antonpup** [comment]
Purchased ETS2, going to see about adding support for it.

**Comment by simon-wh** [comment]
ETS2 support has been added with #1105

**Comment by stbatuhan** [comment]
Thanks for the heads-up 👍

**Comment by simon-wh** [comment]
ATS has also been added #1136
