### ISSUE TITLE
Media keys support and g810 extra backslash not lighting up

### ISSUE THREAD

**Issue by Mike43110** [antonpup/Aurora#250]
just received a g810 and after setting up my desktop and gaming profiles to my liking I noticed that the media keys were still dark.

The g810 also allows for the numlock/scrolllock/capslock indicator lights to have custom lighting.

Unsure as to what information would be needed to assist.

**Comment by antonpup** [comment]
Logitech LED SDK does not allow for lighting customization for media or the lock keys.

Nothing I can do about it. Once they are added to the SDK, I will include them.

**Comment by Mike43110** [comment]
That's unfortunate! But, as stated, nothing can be done for now.
Thanks
