### ISSUE TITLE
Integrate with RGB LED strip

### ISSUE THREAD

**Issue by latworx** [antonpup/Aurora#252]
Hi. Is aurora limit to mouse, keyboard only? Im planning to attach some RGB led strip to my gaming station, and i would like to have the led interract as the keyboard do. Is there any rgb led strip controller that have support with aurora? Can u suggest me the model if any?

**Comment by brainbug89** [comment]
Any RGB controller with SDK support works. For example the [AC farbwerk](https://shop.aquacomputer.de/product_info.php?language=en&products_id=3232).
But you need to wrote your own script: https://github.com/antonpup/Aurora/wiki/Device-Scripting

**Comment by antonpup** [comment]
I will hopefully complete my project for [TV lighting setup](https://github.com/antonpup/Aurora/projects/1) and other people can use that as a base for their own strip or RGB bulb implementations.

But overall, Aurora is very flexible in terms of adding new devices. Take a look at the Device Scripting wiki page (linked above), as well as some current and previous pull requests related to devices. It should give you a pretty good understanding of how to add your own.

**Comment by RickDB** [comment]
Hyperion will do just this once integrated into Aurora which is pretty easy and will do this very soon, it allows for numerous led setups or Hue if you want to keep it simple :)

**Comment by latworx** [comment]
@antonpup i'm looking for it. still not familiar with the mechanism.

@RickDB I'm might asking too much, can u provide detail how u do that? based on the YouTube, that's exactly what i need. I'm planning using Hyperion, as I can find Rpi stock nearby.

**Comment by RickDB** [comment]
Basically you need an AtmoOrb device, we have some instructions and complete DIY here:

https://hyperion-project.org/wiki/AtmoOrb-Device
http://forum.team-mediaportal.com/threads/diy-atmoorb-a-hue-like-mood-lamp-based-on-particle-photon-with-neopixel-tutorial-added.131901/

You can control the AtmoOrb devices even without Hyperion btw as every Orb is standalone (has its own receiver).

And full hyperion guide (bit dated but valid):

http://forum.team-mediaportal.com/threads/diy-amblight-project-guide-hyperion-ws2801-ws2812b-apa102.128526/

Now for Hyperion support in Aurora I have made some sample code and will integrated early next week :)

**Comment by latworx** [comment]
@RickDB wow thats a very good info. I'll waiting for how to integrate aurora with hyperion. I'm really new with coding, still not seeing how they can integrate -  when i see the Device Scripting pages, I manage to understand it a bit, but I didnt have any idea how exactly it communicate with hyperion. I hope u got what i mean :) I think i might fall into the category "guys that need a graphical tutorial" haha

**Comment by antonpup** [comment]
I am finally doing my [TV lighting setup](https://github.com/antonpup/Aurora/projects/1) project. My progress will be available on the [pi-lighting](https://github.com/antonpup/Aurora/tree/pi-lighting) branch. I don't intend on discouraging @RickDB or anyone else from doing their own implementations. I want to simply provide a project that implements [Device Scripting](https://github.com/antonpup/Aurora/wiki/Device-Scripting) and a Raspberry PI with Aurora, so people have a functional project to try out before developing.

**Comment by antonpup** [comment]
I wrote a functional script for Aurora with C#, and for the PI I used Java. I mapped ESC - F12 keys to represent 2 lights on a 32 led strip, and it ended up working quite nicely. I am optimizing the code a bit, and then I will push it to the pi-lighting branch. Raspberry pi is a pretty cool little piece of tech. :+1:

**Comment by antonpup** [comment]
I committed my scripts I used for Raspberry Pi with instructions.

https://github.com/antonpup/Aurora/tree/pi-lighting

**Comment by latworx** [comment]
im afraid to said this. But, i really dont understand how to do it from the start. sorry, but really hope i can imagine how to do it. 

Btw, @antonpup, under the Projects, i saw your post, but I didnt have any idea how to look into each completed task.

**Comment by antonpup** [comment]
I got my [NeoPixels](https://www.adafruit.com/products/1461) working today. Gonna write a python portion to handle NeoPixels on a Pi. I don't think it will require any changes to the original [RPi Device Script](https://github.com/antonpup/Aurora/blob/pi-lighting/Scripts/Devices/rpi_script.cs). So... same interface, just in python and working on NeoPixels :)

**Comment by antonpup** [comment]
Done. https://www.youtube.com/watch?v=p0WiaQwmSYQ

NeoPixel python portion is on the [pi-lighting](https://github.com/antonpup/Aurora/tree/pi-lighting) branch.

**Comment by latworx** [comment]
Hi @antonpup . Thats a very good guide!!

BTW, before i try it, i would like to install the hyperion to try it out. Everything is working when im using OSMC. But then, when im using raspbian as OS, im encounter a prob. The installing of Hyperion into rpi is successful. But seems like its not working. I cant start the service. I check into /etc/init.d and /etc/init folder, there is no hyperion related files. Is it the culprit?


Another things, based on my little knowledge about codes, I'd go through the [https://github.com/antonpup/Aurora/blob/pi-lighting/Scripts/Devices/rpi_script.cs](url) link, is it the basic codes? I means, the script will turn on LED based on which key is pressed? How to implement the DOTA games to interact with the LED? I read the DOTA2 Namespace, but I dont know how to apply it into script. Can I have some example (i.e. led go GREEN when health full but turn RED when low health).

Thanks all

**Comment by antonpup** [comment]
I can't help you with Hyperion, I don't have it.

But with my rpi scripts, you simply specify which key will light up which led in your connected strip.

For the demo video on that branch, I set it up with Left Ctrl, Left Shift, Caps lock, Tab, ~, ESC, F1 - F12, Backspace, |\, Enter, Right shift, Right Ctrl.

So it works with most game configurations, as I set Function keys to be HP and what not, so the top of my monitor lights up with HP.

**Comment by latworx** [comment]
Oh!  I got the wrong idea before. Thanks for the tips! Will try to install it. Hope I know how to install all the dependencies. Less knowledge on command line and linux os

**Comment by latworx** [comment]
Hi. I successfully install all the dependencies, and run the mvn command. Then i ssh "java -jar AuroraPiLighting-full.jar" and command send me "SPI initialization SUCCEEDED" but then i cant send any command in the same ssh windows. Normal?
However, when i run Aurora, nothing happen to the led strip. Double check the IP and port set in script is match with the java file in the src folder. Am I doing any wrong?

**Comment by antonpup** [comment]
Is your LED Strip a NeoPixel or is it LPD8806? Have you properly connected your LED Strip?

**Comment by latworx** [comment]
oh. forgot to mention. mine is APA102. Same connection with LDP8806. Is the color code not match?

**Comment by antonpup** [comment]
Make sure that the data is connected to pin 18.

**Comment by latworx** [comment]
oh?sorry, why 18? mine RPI 3 MOSI/GPIO10 is on pin19. pin 18 is GPIO24. Or i really need to connect to pin 18 for RPI3?

**Comment by antonpup** [comment]
That's the pin I set it up for on the Pi end. So... you'd have to adjust that.

**Comment by latworx** [comment]
still no. The led only light up when i connect DI to pin19/MOSI. But not integrate with aurora. do i need to change the library used? how?

**Comment by antonpup** [comment]
That I cannot help you with. I never used those leds. So... you'll have to look around yourself.

**Comment by latworx** [comment]
oh ok. by the way, i say that now the raspberry pi script is not initialized. (before is connected). How to fix it?

**Comment by latworx** [comment]
I'm sorry for opened this again. Just remembered that u ask me to connect data pin to pin 18. What i need is pin 19. Can i know where can i alter the code so that it'll match with my case?

**Comment by antonpup** [comment]
@latworx connect as explained here: https://learn.adafruit.com/assets/1589 this is for RPi 1, you will need to find pin layout for your Pi, but connection points are the same.
