### ISSUE TITLE
New effect ideas?

### ISSUE THREAD

**Issue by KensonN** [antonpup/Aurora#253]
Something like this? http://i.imgur.com/FIlknbj.gifv
Also maybe a way to set the effect speed past 5?
Thanks!

**Comment by Nopraz** [comment]
Yes that would be so cool !

**Comment by antonpup** [comment]
Here are a few options that I can do:

1. Provide users with necessary tools to create effects like this (and perhaps other ones) [Easy to do, already possible,  but users have to create it]
2. Add these as new "rainbow" effects. [Each effect will have a duplicate rainbow one, tedious to maintain]
3. Add a "gradient" and "solid color" modes. Users will be able to define their own gradients for each supported effect. [Most difficult to do, easy for users to setup, may not work with all effects]

**Comment by antonpup** [comment]
Added. Speed and width are adjustable.
Preview:
![](https://dl.dropboxusercontent.com/u/30675690/Aurora/keywave_rainbow.gif)
