### ISSUE TITLE
[FeatureRequest] Change color of userdefined Keys/Area while Caps-/Num-/Scrollock is activated

### ISSUE THREAD

**Issue by Phelagor** [antonpup/Aurora#255]
I was searching for a way to change the color of any key / Area on Keyboard by activating any of the -lock keys (Caps-/Num-/Scroll-).
A feature like the Shortcut Assistant, where you may define keys or areas to light up or change Color while one of the lock-keys is activated.

**Comment by Phelagor** [comment]
Thanks for the great work.

I had a look at the dev branch before the pre-release, and there I was able to realize this feature by adding a layer for it.
Will have a look at 0.6.0, cause last time I checked there was a bigger delay after altering the lock-state continously for some seconds.

**Comment by antonpup** [comment]
I checked it out and yes, it happens once in a while. I'll look into it.
