### ISSUE TITLE
Razer Ornata Not Detected

### ISSUE THREAD

**Issue by amathystbumps** [antonpup/Aurora#256]
After multiple configuration changes in an attempt to troubleshoot this, I'm still left with Aurora not detecting the keyboard. I know it's newer KB, but I've seen that other users are running Aurora on the Ornata as well.

If anyone can point me in the right direction I'd appreciate it, because I'm feeling a bit lost at this point.

Edit: It worked once, but after a restart, it continued to not recognize the KB.

**Comment by antonpup** [comment]
Have you selected Razer as your keyboard brand? Look at #239

**Comment by amathystbumps** [comment]
Ah, interesting. It WAS previously selected, but is now set to automatic. Likely something I've done to mess that up.

Solved.

**Comment by antonpup** [comment]
:) Enjoy!
