### ISSUE TITLE
How general / universal is Chroma's patching?

### ISSUE THREAD

**Issue by WryZed** [antonpup/Aurora#257]
Meaning, is it possible to use Overwatch's Chroma patching with other Chroma supported games (in the same vain as Logitech's wrapper), ie: Kerbal Space Program for example, or is it unique to each title?

Thanks in advance!
-WryZed

**Comment by antonpup** [comment]
Universal, should work with most chroma games.

**Comment by WryZed** [comment]
Thank you for the quick response, and the fantastic software! For Chroma related games, is it the binaries directory that needs to be patched? (As a general rule, I realise some may be specific)

**Comment by antonpup** [comment]
Usually it's the folder with the game's exe. There are some rare cases where you have to place those in another directory. But for the most part, next to exe.

**Comment by WryZed** [comment]
Lovely jubbly! Cheers for that!

-WryZed
