### ISSUE TITLE
DotA2 Ping lightning

### ISSUE THREAD

**Issue by caw1** [antonpup/Aurora#261]
Hi,

i´ve seen thats for DotA2 some lightning effects if someone is pinging - is it possible to get that Feature for the g910 too?

**Comment by antonpup** [comment]
I don't think GSI exposes such information. You said you've seen it somewhere, can you provide a link?

**Comment by caw1** [comment]
hey,

i´ve talked to the person who told me.... but it was a coincidence with some other lightings... sorry about that
