### ISSUE TITLE
CSGO?

### ISSUE THREAD

**Issue by CDNBreadCats** [antonpup/Aurora#263]
New to Aurora not sure if im doing something wrong, i set up my configs for desktop and csgo desktop seems to work fine yet when i open CS it changes profiles but then nothing updates

Corsair strafe RGB

Thanks

**Comment by antonpup** [comment]
What do you mean by "nothing updates"? Does it switch to the csgo profile and then it does not show hp/ammo, ect? Does it return back to the desktop profile after tabbing out?

It's possible that GSI did not get installed. On the overview of CSGO, press "Patch Aurora GSI".

**Comment by CDNBreadCats** [comment]
Sorry i realized i had a different  program interfering with it got it to work 
Thanks anyway and good work
