### ISSUE TITLE
[Keyboard Request] Roccat / AlienFX

### ISSUE THREAD

**Issue by DanielMckibbin** [antonpup/Aurora#264]
Roccat now have AlienFX enabled on their keyboards (notably Ryos MK FX). Can we get it enabled on this device? Tried starting the software but it says 'No Keyboard Detected'. 

- Just noticed this issue was asked back in July, have you made any progress on LightFX hardware support?

**Comment by antonpup** [comment]
No progress was made because I don't have access to an AlienFX keyboard, nor has anyone else made support for AlienFX. I can look into it and attempt to write support blindly, but I wouldn't expect it to work 100%

**Comment by antonpup** [comment]
Looked into Ryos FX. And it seems like you cannot set the individual color of keys. The SDK allows you to set a color to ALL TalkFX devices and with Ryos you can select which keys are turned on or off.

As a result, I don't think Ryos or any TalkFX device will have decent lighting effects. It would be more ambient than specific.

I will add it, but like I said before, don't expect it to be 100% functional nor to be eye candy.

**Comment by DanielMckibbin** [comment]
As far as I know anything made for light fx should just work for ryos too. If you make a test build with light fx I'll be happy to test and report my findings for you.

**Comment by antonpup** [comment]
Add me on steam, will send over a build.

http://steamcommunity.com/id/pupant/

**Comment by DanielMckibbin** [comment]
Added you (Vyrus)

**Comment by Arcanum417** [comment]
I have an Roccat Kone + and I am confused how to make it work....
