### ISSUE TITLE
Bug in ColorSpectrum, fix attached

### ISSUE THREAD

**Issue by VoronFX** [antonpup/Aurora#267]
Hi! I've just found bug that still present even in dev branch.
Aurora.EffectsEngine.ColorSpectrum.GetColorAt(float position, float max_position = 1.0f) 
calculates wrong colors if max position is not 1.0f
Here is code with fix;
```csharp
       public Color GetColorAt(float position, float max_position = 1.0f)
        {
            position = CorrectPosition((position / max_position) + shift);

	    max_position = 1.0f; // Add this line here to fix the bug

			float closest_lower = 0.0f;
            float closest_higher = 1.0f;

            foreach (KeyValuePair<float, Color> kvp in colors)
            {
                if((kvp.Key * max_position) == position)
                {
                    return kvp.Value;
                }

                if((kvp.Key * max_position) > position && kvp.Key < closest_higher)
                {
                    closest_higher = kvp.Key;
                }

                if ((kvp.Key * max_position) < position && kvp.Key > closest_lower)
                {
                    closest_lower = kvp.Key;
                }
            }

            return Utils.ColorUtils.BlendColors(colors[closest_lower], colors[closest_higher], ((double)( (position / max_position) - closest_lower ) / (double)(closest_higher - closest_lower)));
        }
```

**Comment by antonpup** [comment]
I don't understand what this fix is for? The color spectrum is designed so it has at least two points (0.0f and 1.0f). The parameters refer to "current position" out of "maximum position". The spectrum itself can be considered a line of different colors from 0% to 100%. So if the position is 0.4 and max_position is 2.0, then it will return a color from spectrum at 0.2 or 20%.

I guess I need to throw more exceptions :P

**Comment by VoronFX** [comment]
bugged version it will work correctly only if you use normalized points (0.0-1.0) like you do almost every where. but if you try to use for example `GetColorAt(56, 100)` it will return wrong color. 

look here:
` if((kvp.Key * max_position) > position && kvp.Key < closest_higher)`
you are comparing already normalized `position ` with key multiplied on not normalized `max_position`.
here you normalizing position:
`position = CorrectPosition((position / max_position) + shift);`
but you forgot to set `max_position` to 1f after that.
 That's why I added this line:
 `max_position = 1.0f;`
Hope now it's more clearly.

**Comment by antonpup** [comment]
I see where you're coming from now... Yeah... I will look into it. Thanks for bringing this up!

**Comment by VoronFX** [comment]
Np!) I've discovered when my script was not working correctly. Anyway, thanks for you amazing program!
