### ISSUE TITLE
Aurora 0.4.2/0.4.3 keeps crashing.

### ISSUE THREAD

**Issue by silphnaberrie** [antonpup/Aurora#27]
Hi.
(my english is too bad.)

Aurora 0.4.2 and 0.4.3 keeps crashing on launch. it's similar issue #20. but 0.4.1 can work on same system.
Im using:
 Logitech G810(JP layout)
 Win10 x64
 LGS x64 8.83.85

should I wait next release for fix? :)
[2016_12_06.zip](https://github.com/antonpup/Aurora/files/310520/2016_12_06.zip)

**Comment by antonpup** [comment]
Your issue isn't related. I will add a catch for this error in the next version. But for now, can you please run this in command prompt as admin: `lodctr /R`

It will reset the performance counters used by CPU and RAM indicators.

**Comment by silphnaberrie** [comment]
Thanks for response :)
I tried 'lodctr /R' and restart. but 0.4.3 still crashing on launch.
New log here.
[2016_12_06.zip](https://github.com/antonpup/Aurora/files/310557/2016_12_06.zip)

**Comment by antonpup** [comment]
Previous error is resolved, this one is related to Hotline Miami. Do you have Hotline Miami installed? Can you send me your appmanifest_219150.acf file, located in steamapps folder.

**Comment by silphnaberrie** [comment]
Yes, I installed Hotoline Miami.
here it is. :)
[appmanifest_219150.zip](https://github.com/antonpup/Aurora/files/310578/appmanifest_219150.zip)

**Comment by antonpup** [comment]
Change 
`	"InstallDir"		"hotline_miami"`
to
`	"installdir"		"hotline_miami"`

lowercase, this issue will be fixed in the next version.

**Comment by silphnaberrie** [comment]
Yes !
0.4.3 working perfectly now :D
(got same error log by Talos Principle. but it can fix in same way as Hotline Miami.)
Thanks for helping and great wrapper.

Maybe, I can test JP layout of Logitech G810, if you still need tester.

**Comment by antonpup** [comment]
Glad I could help. :)

Fixed in the next version.
