### ISSUE TITLE
Choosable direction on Freestyle option?

### ISSUE THREAD

**Issue by cvb941** [antonpup/Aurora#271]
Particular example would be healthbar on CS:GO, I would personally like it going progressively vertically from top to bottom.

**Comment by antonpup** [comment]
Turn freestyle 90 degrees, and stretch. The bar will now fill up or down.

**Comment by cvb941** [comment]
Thank you very much! Sorry for not noticing this, I thought it would be simple enough to be already implemented. I'm usually a do-research-before-asking guy but this was an exception. Sorry again.
