### ISSUE TITLE
Overwatch remapping keys?

### ISSUE THREAD

**Issue by Olliechu** [antonpup/Aurora#272]
Is there any way to remap the keys that show up on the overwatch part? asking for a friend as they are left handed.

**Comment by antonpup** [comment]
So, for example you would remap WASD to arrow keys? As far as I know, Overwatch lights up keys based on what keys you selected in settings.

**Comment by Olliechu** [comment]
Just tried that for myself to see if it works, Changing to arrow keys myself works. but the Hero select I have set to = instead of H and that doesn't work.

**Comment by antonpup** [comment]
Leave spawn and come back, it will change.

**Comment by antonpup** [comment]
Any updates on this?
