### ISSUE TITLE
[FeatureRequest] ColorWave from LGS

### ISSUE THREAD

**Issue by Nightcro** [antonpup/Aurora#273]
I didn't see this option or maybe i wasn't looking too well. Is there a ColorWave with the direction Center Out ?

One more question can i change  the badge at the bottom ? (i have a logitech g910), i haven't found the option to change its color.

And one more question: How hard will it be to implement an audio visualization like this one (https://www.youtube.com/watch?v=kaj8hjpg01U), but to attach to the sound output of a process like winamp ?

Thanks for your work !! :)

**Comment by brainbug89** [comment]
Logitech logo was added in dev version: https://github.com/antonpup/Aurora/issues/164#issuecomment-251291658

Audio equalizer will be added later: https://github.com/antonpup/Aurora/issues/34#issuecomment-269068220

**Comment by Nightcro** [comment]
I know about the one at the top near the "esc" key
I'm talking about the one at the bottom:
![rgblogo](https://cloud.githubusercontent.com/assets/24304655/21482051/926d809a-cb77-11e6-93f2-d8a90fb8dc0f.png)
I can't seem to find the setting to change its color.

Thanks for  the audio equalizer :)

**Comment by antonpup** [comment]
Part of dev, #194

**Comment by antonpup** [comment]
As for color wave coming out from center, will look into later.

**Comment by Nightcro** [comment]
Sweet :D
Thanks for the quick reply.
