### ISSUE TITLE
Request: New Profile for GTA V Wanted stars , Ammo Health

### ISSUE THREAD

**Issue by Solilord** [antonpup/Aurora#274]
Dear anton,

Please add Wanted Stars blinkin as macro keys(G1-G5) depending on how many Stars:
1 star -> only G1 blinks and so on. 

And please add Health/ Vest and/or ammo bar linke in CS GO if possible. 

Thx :)

EDIT: And WASD ond so an :))

**Comment by antonpup** [comment]
The way Aurora interacts with GTA 5, you cannot get "how many stars you have" or "how much HP you have". The game simply does not expose this information,

On "WASD" however, in the current version (0.5.1) you can set a color zone for those keys, in the next version (0.6.0) you can set a layer for those keys.
