### ISSUE TITLE
Mouse movement feels jerky and unresponsive

### ISSUE THREAD

**Issue by MegisMake** [antonpup/Aurora#276]
Aurora sees my Logitech G402, and does _something._

It feels like the mouse is rapidly getting disconnected, then connected back in. I didn't really notice it at first, but it when playing CS:GO, it got so bad that I thought my mouse broke.

I then closed Aurora, which solved the problem and my mouse feels right again, but whenever I open it back up I can notice it getting slightly unresponsive again, and probably would get worse if I started playing again.

I looked trough the settings but I couldn't find a way to disable aurora for my mouse. 
In the Devices & Wrappers settings, it just says "Logitech: Connected" with no way to stop aurora from messing with my mouse. 

Feels really great otherwise, but at it's current state I just cannot use the program right now.

Edit: oh, and my keyboard is Corsair K70 LUX RGB, if that makes a difference.

**Comment by antonpup** [comment]
What is your CPU? If you're running a dual core, you won't be able to use it with CSGO.

**Comment by MegisMake** [comment]
I have AMD Athlon X4 760K, Quad core.

There's nothing wrong with the lightning on my keyboard, but it does something to my mouse and there's no way to disable it.

**Comment by brainbug89** [comment]
Maybe disable lighting SDK at LGS for mouse?

**Comment by antonpup** [comment]
If he's having input issues, it's likely not related to lighting. It's more likely an issue with overall Aurora performance. Perhaps your anti-virus is being very active on Aurora and slows down its performance? Send over some logs (preferably ones where you had input issues).

**Comment by MegisMake** [comment]
I already tried disabling the lightning SDK, but that didn't help.
I also never have an anti-virus running in the background so that's not the case either.

I can't access my main computer now but I'll send logs later.

**Comment by antonpup** [comment]
Any updates on this issue?
