### ISSUE TITLE
CS GO Profile for Aurora

### ISSUE THREAD

**Issue by Leonmeister** [antonpup/Aurora#278]
Hello, i tried Aurora for a few games now, and the most worked well. But in cs:go, there are some "profiles" like flashbang or burning events default, and in preview they seem to work. coincident to this, i wanted to make my own color zones for it. Still in preview it seems to work, but as i go ingame, my keyboard is completly white. If i join a matchmake, there work some defaults like, bomb explosion event or health/ammo indicators. But the kill indicator, the flash and burning events and my own color zones arent working at all. Ingame i got some different colors than i made in Aurora. Can someone help me out here? It seems to work, but as i go ingame in cs:go, there are just other settings for my keyboard.

**Comment by antonpup** [comment]
If you have a Logitech device, then LGS may be running effects over Aurora. Please go to Aurora's settings -> Devices & Wrappers -> Press "View first-time instructions for Logitech" and follow those instructions to disable CSGO and Dota 2 effects in LGS.

**Comment by Leonmeister** [comment]
Hey thank you man, this works <3
