### ISSUE TITLE
Overwatch not working

### ISSUE THREAD

**Issue by McRiot** [antonpup/Aurora#281]
running Aurora beta v0.5.1d with my Logitech G910 and nothing happens when I load Overwatch, just a black keyboard no lights. Keep up the good work.

**Comment by antonpup** [comment]
Take a look at #42

**Comment by McRiot** [comment]
thanks, installing  Visual Studio C++ 2015 Redistributable x64 seemed to fix it. I assume rocket League will be fixed in next patch? I just get a blue keyboard, unless I missed something for that as well?

**Comment by antonpup** [comment]
Rocket League is a can of worms that I refuse to touch nowadays. It will most likely not be fixed up, due to the painful process of finding correct pointers for it. I am waiting until a better alternative is available.
