### ISSUE TITLE
I dont really know where to start

### ISSUE THREAD

**Issue by PedMar0625** [antonpup/Aurora#282]
I have a G810 Logitech Keyboard.

When using aurora I cant have ALL keys to have the wave effect (that includes lights, mute and play buttons)

Also my mouse turns off when using it and I cant select it unless I freestyle it.

**Comment by antonpup** [comment]
Media keys aren't available for color changes in Logitech LED SDK.

I am not sure about the mouse issue. Once 0.6.0 is out, let me know here if it still happens. I don't have any issues with my Logitech G900 and Corsair Sabre.

**Comment by PedMar0625** [comment]
I also told the software to run when windows start and it didnt. and when I minimize it goes to my task bar, I suggest it should minimize to tray better

**Comment by VoronFX** [comment]
Minimize is minimizing. To put Aurora in tray you have to press "close" and answer that you don't want to actually close. 
If you don't want to answer every time, there is a setting in general "What to do when Aurora window is closed". You can choose desired behavior.

**Comment by antonpup** [comment]
Any updates about this?
