### ISSUE TITLE
Feature Request - Audio Spectrogram Integration

### ISSUE THREAD

**Issue by McRiot** [antonpup/Aurora#283]
Would like to know if it's possible to integrate this guys work.

> winner of the logitech challenge contest
> 
> Dhyan Yahampath
> Description: This program displays an audio spectrogram on your Logitech RGB Keyboard based on the audio currently playing on your computer. The ARX app is used to control the spectrogram or to display its on-screen output.

It's pretty fun to play with but it doesn't seem to play nice with Aurora. You can only have one or the other running his Spectrogram software overrides Aurora.

Sadly I'm not much of a coder and this is beyond my capabilities or I would try to figure it out myself. Would love to see the two programs play nice so I can more easily watch my keyboard beat to the music and change on load up to a game.

*crosses fingers*

**Comment by antonpup** [comment]
So this? #34 

Also, patching Logitech LED SDK with Aurora's wrapper will make it go through Aurora.

**Comment by McRiot** [comment]
Hah yes exactly :) Sorry I'll look harder before posting, I'm new to all of
this. Just got the G910 keyboard for Christmas and was kind of disappointed
by the lack of Logitech software/plugins so I went searching elsewhere and
found Aurora. Used to have a G15 and some pretty cool display features for
it like seeing who is talking on Ventrilo, What song I have playing and
more. As cool as the ARX app could be it's really lacking. I hope things
improve with Logitech but in the meantime Aurora seems to add a lot more.
