### ISSUE TITLE
Pre-release feedback [Version 0.6.0]

### ISSUE THREAD

**Issue by antonpup** [antonpup/Aurora#287]
While I am waiting for technical issues to clear up with updates server. I have posted a pre-release version of 0.6.0 for you guys to play around with.

https://github.com/antonpup/Aurora/releases/tag/v0.6.0-pre

It's a pretty hefty update. Alot has changed compared to the latest public version. Some things to test out:
* Give Layers a spin, see if they are easy to use
* If you have a foreign keyboard layout, see if it's working properly
* If you have a Razer or a Corsair keyboard, see if they are working properly
* Profile hiding
* Equalizer
* Overall stability and performance
* Spelling mistakes

Thank you for your time. I am hoping to release a proper 0.6.0 update next week.

**Comment by TheRebelWizard** [comment]
Have a G910 and G900. Will test it out! Everything looks good so far, no hiccups installing or loading profiles. 

App seems to run smoother, but lags really badly when selecting keycap type. That's the only thing I've noticed so far really, aside from the interactive effects tab being gone. :( (RIP?)

**Comment by antonpup** [comment]
@TheRebelWizard Interactive effects are now a layer, and can be applied per-profile.

**Comment by TheRebelWizard** [comment]
Edited, just found them. Messing with the layers now and will update with anything I run into! :D

**Comment by antonpup** [comment]
@TheRebelWizard You can already copy/paste and delete layers with CTRL-C CTRL-V and DELETE keys. Copy/paste works across profiles.

**Comment by TheRebelWizard** [comment]
First error report, when saving a new Profile and choosing to overwrite an existing one Aurora crashes before it saves. This happens 100% of the time for me.

Also, clicking the Aurora icon from the taskbar no longer gives that old error, but states "Aurora is already running" rather than bringing the app up from being minimized in the toolbar.

**Comment by simon-wh** [comment]
@TheRebelWizard I've fixed two of the issues you've mentioned as you can see from the commits above. I was unable to replicate the issue you mentioned from bringing the app up from the taskbar, is it consistent? If so, how exactly are you replicating it?

**Comment by TheRebelWizard** [comment]
Yeah sorry, my description was kinda bad because I kept mixing up tray and taskbar. But to clarify either way, the taskbar shortcut will not open the Aurora window while it is minimized to the tray.

**Comment by bardyspoon** [comment]
Logitech G900 is the only Logitech mouse in the device settings. I have a Logitech G Pro, which has logo and side lights. Selecting G900 for the mouse and setting the Peripheral Logo to be used in a layer **does** result in the logo and side lights being used on the G Pro. This is the behavior I'd expect and the way it was working on the release beta with automatic device detection.

Just not very intuitive. Perhaps there can be generic or automatic options added back to device selection? Or maybe there are plans to add more layouts for mice?

**Comment by antonpup** [comment]
@TheRebelWizard I will see about fixing automatic source detection. But I am not sure how to implement the key sequence for the EQ. I could probably do an option for a freestyle, but not key sequence.

@bardyspoon The automatic detection options are hard to do when several device SDKs do not report a connected keyboard. For example, the Razer SDK initializes even if you do not have a Razer keyboard plugged in. So as long as you have Razer Chroma enabled on your computer, Aurora would always detect your keyboard as Razer. And then there's Cooler Master, Roccat, and hopefully in the future SteelSeries. They simply don't report if a keyboard is physically connected.

As for the mouse layouts, you can technically use any of them for Logitech. Because Logitech RGB mice only have 1 color zone. But there are plans to add more mice, I just didn't feel like doing it for the reason stated above. #119

**Comment by McRiot** [comment]
Very impressive Aurora build. 

LOVE the EQ took me a bit of time to find where you stashed it though. After realizing I can click to add new layers and change the function of each layer everything made sense. For those less intuitive that layers have functions built into them these amazing features could go unnoticed. 

One thing I found a bit annoying with the layer functionality is drag and drop or just overall moving the order of layers is not very refined. Maybe theirs key shortcuts for this function? However, Up and Down arrows next to each layer at the very least but even better when you drag a layer have it underline the layer it will be moved beneath.

While playing with the EQ colors I did manage to freeze up the color drop menu. I removed the layer and added a new layer and it was fixed. If I replicate the problem I'll let you know.

Overall this project is so good and I just want to help see this grow 👍 

As long as you guys don't mind I'll keep posting ideas, areas I can see improvement in and of course bugs/crashes/typos ;). I am enjoying watching how this project continues to evolve, keep up the excellent work

**Comment by antonpup** [comment]
@McRiot I am not sure how to emphasize to users that Layers have options. They just gotta explore I guess? I really don't know.

But for layer dragging, I added "buns" to the left of a layer. When moused over, it will change the cursor to up-down arrows, hopefully indicating to the user that this can be dragged.

![](https://puu.sh/t6vX3/7d5fe7c0bf.png)

As for EQ, not sure how you froze it. But if you can recreate it, let me know. It probably affects all ColorBoxes.

**Comment by McRiot** [comment]
Love the buns that looks great. 

Maybe just making the "add" and "remove" buttons more appealing to press. Took me a bit before it occurred to me I should press "add" (colorize and enlarge it slightly?) Make me want to push the button :)

**Comment by antonpup** [comment]
@McRiot So, if I understand correctly. Make the "add" button red, and make it uniquely stand out. Subconsciously making you want to press the button.

Like so:
![](http://www.gamegrin.com/assets/games/please-dont-touch-anything/screenshots/please-dont-touch-anything-screenshot-4.jpg)

:)

**Comment by McRiot** [comment]
I love this guy ^^ 👍

**Comment by McRiot** [comment]
If you make red and green circular buttons for this build I'll buy you a drink ;)

**Comment by antonpup** [comment]
@McRiot I added icons to the buttons. Hopefully, that will make them stand out more than before. I also added tooltips for those

![](https://puu.sh/t6x4h/0e0ca64f04.png)

**Comment by McRiot** [comment]
Well it doesn't make me believe I'm about to launch those missiles but it does look much better :) :1st_place_medal: 

this is what is currently bothering me more right now:

> Added VLC as a new Lighting Profile, Added EQ options. Works great as long as VLC is running in the foreground but the second I switch to another window it defaults back to Desktop Settings. Would like to have the option for my audio programs to continue the light show no matter what window I'm in. Only switch off when I close the media application.

Probably a little more complicated then my cosmetic gripes. Maybe an option that can prioritize certain applications when running in the background or minimized.

**Comment by antonpup** [comment]
It's possible to do. But it will come later as "overlays" feature. It will let you select profiles to act as overlays or underlays. So, current Skype and Volume overlays will go there.

I would also like to point out, that EQ on a specific application (like VLC) does not exclusively restrict audio analysis for that process. It takes overall PC sound.

**Comment by McRiot** [comment]
Fantastic, I look forward to those changes 👍 

I was really excited about getting this keyboard but I'm even more excited for this Aurora project. 

Keep it up guys! I'll be checking in frequently :)

**Comment by gradius-v** [comment]
Can you make the background keys dimmable in the EQ layer ?

**Comment by antonpup** [comment]
@gradius-v So, dim background when there is music playing?

**Comment by TheRebelWizard** [comment]
Thanks for all the fixes, that solves every technical problem I've encountered so far.

Any chance of lowering the lowest speed effect setting for layers? 

I'm using the gradient layer, at 1 effect speed, and it's quite a bit faster than the lowest setting on the old Rainbow Shift Zone Effect. I really liked that speed setting at the lowest because it was pretty subtle in comparison.

**Comment by antonpup** [comment]
@gradius-v I added the background dimming on sound to EQ Layer.

I also fixed a bug in EQ Layers that caused incorrect values to be displayed.

@TheRebelWizard I'll look into it, but as far as I remember, I just copy-pasted the effects to layers. Is it too fast for any animated effect? Or just the gradient?

**Comment by TheRebelWizard** [comment]
I think it's just the effect animation speed in general. It seems faster overall for most settings.

**Comment by antonpup** [comment]
I added an Image layer with gif support. So users can now create their own little animations, save them as gifs, and use with Aurora.

Here's Aurora Inception
![](https://puu.sh/t7TEy/1e0839d4e6.gif)

**Comment by gradius-v** [comment]
Thanks for adding the dimming to the EQ layer.

**Comment by antonpup** [comment]
It seems that those profiles got corrupted. They won't be loaded. Your best bet is to delete them. I am not sure how they got corrupted.

**Comment by gradius-v** [comment]
Just deleted the corrupt profiles. I got another feature request, can you add an exclusion list to the key fade effect ?

**Comment by brainbug89** [comment]
I really like the new version! :+1: 
For foreign keyboard layout feedback, see: https://github.com/antonpup/Aurora/issues/123#issuecomment-269993488 and #310
Lighting for Corsair media keys work fine.
Profile hiding seems fine.
I like the new Equalizer layer. Maybe at a few more options like [CEE](http://forum.corsair.com/v3/showthread.php?t=139027).
I'll test the Ambilight layer a little bit more. At first try, it looked to bright.

Thanks for this awesome software and everyone who participated. :+1:

**Comment by VoronFX** [comment]
Layers are great and it is a big step. But I have some more propositions for future.
1. I feel like scripts should be as layers too, somethings like Script layer type.
2. One more nice to have feature is ability to overlap profiles or maybe make layer across several profiles. 
I have my default colors/scripts in desktop profile and I want some game profile to add functionality when game running instead of replacing it. In addition it will allow to have one script instance across profiles, if scripts will be as layers.
Of course this I can do now by copy/pasting things in every profile, but it feels like it's not as it should be. It's a workaround.
3. Controls for scripts. Don't know in which way but will be nice.

**Comment by antonpup** [comment]
@bardyspoon I added some instructions for the "No keyboard selected" screen.
![](https://puu.sh/t8Vq0/4b9f58420e.png)

@gradius-v That will come later for all layers as a Layer Mask.

@brainbug89 What options exactly do you want to see from CEE?

@VoronFX Script layer was considered, but not added because originally it was going to just run all scripts in one layer. Now that I think about it, we could add a script layer that runs only one script. So users can choose where they go. But first I would like to see how general public likes the layers. If they don't, then it won't work out. For profile over/underlays see: https://github.com/antonpup/Aurora/issues/287#issuecomment-269852531 As for settings for layers, will have to see what we can come up with.

**Comment by brainbug89** [comment]
> @brainbug89 What options exactly do you want to see from CEE?

More color effects like Rainbow (with direction) and Defined Rows and maybe Db and frequencies settings.

**Comment by antonpup** [comment]
@brainbug89 Took me a bit of time. But here you have it!

The bar width is automatically scaled based on the number of frequencies. The frequencies are automatically sorted from lowest to highest (to avoid broken power bars).

![](https://puu.sh/t9vLD/580c0e6c56.png)
![](https://puu.sh/t9vNq/4e58b04252.png)
![](https://puu.sh/t9vOM/3c4a31284a.png)

And the default for comparison
![](https://puu.sh/t9vW1/d7d12b41f5.png)

Also, the way I set up EQ power bars is to sample between each defined frequency. So with default, 1st bar is between 60 - 170 Hz, 2nd is 170 - 310 Hz, etc... So instead of looking at information at a specific frequency, I also take a look around to get a bit more "vibrant" values.

**Comment by brainbug89** [comment]
@antonpup wow you're awesome! :smile:  Now I only want more color options.
I could recreate the Defined Rows with Gradient (Vertical)
![eq_definedrows](https://cloud.githubusercontent.com/assets/21130949/21608879/842ce932-d1bf-11e6-9938-f4fda11904a7.png)

What I would like to see now is the moving Rainbow. So please add the animation options (Translate X and Y) from the Gradient Layer to the View Type: Gradient (Horizontal).

**Comment by antonpup** [comment]
@brainbug89 
> What I would like to see now is the moving Rainbow. So please add the animation options (Translate X and Y) from the Gradient Layer to the View Type: Gradient (Horizontal).

If I am adding options like these to several layers, I might as well make them into a universal control that I can stick everywhere without repeating code. I will do that at a later point.

**Comment by snichola** [comment]
I'm not sure if this is an issue with cooler master keyboards implementation or overwatch.  Keys like the change hero button are flickering rather than pulsing.  I'll try and figure out if it broke with my code at some point as I know it used worked but I'll be unavailable for the next few days.

**Comment by antonpup** [comment]
@snichola It's probably flickering because of Color Enhancement.

**Comment by gradius-v** [comment]
I've found a bug in the key fade feature. Pressing the Enter key in the numbers block results in the main Enter key lighting up instead. I have a G910 Orion Spectrum, German QWERTZ layout.

**Comment by brainbug89** [comment]
[Anton said](https://github.com/antonpup/Aurora/issues/268#issuecomment-268688116):
> Windows doesn't differentiate between Numpad_Enter and Enter

**Comment by gradius-v** [comment]
Didn't see that. Logitechs LGS itself can light them up individually with their key fade implementation though.

**Comment by brainbug89** [comment]
Because the Logitech driver tells LGS exactly which key was pressed. Aurora however using information from Windows to detect the pressed key and Windows doesn't differentiate between numpad Enter and normal Enter.

**Comment by antonpup** [comment]
Thank you, everyone, for your reports, suggestions, and support! Closing this now. :)
