### ISSUE TITLE
Corsair RGB k70 rapidfire french layout

### ISSUE THREAD

**Issue by Kaarsen** [antonpup/Aurora#288]
Hi,
On my Corsair keyboard french layout, the "A" key seems to be inverted with "Q" and "W" key witch "Z".
The Aurora GUI layout is ok.

**Comment by antonpup** [comment]
Are you on 0.6.0 pre-release? #287 
If not, please see if your issue persists on that version.

**Comment by Kaarsen** [comment]
I wasn't on the 0.6.0 pre-release.
Now i'm on it and still have this issue

**Comment by antonpup** [comment]
Is it the lighting that is inverted? Or is it also the interaction effect?

**Comment by km972** [comment]
Hello anton, first of all thx for your great job, then im a user of french layout and light are still inverted ( W > Z ; A > Q ... ) for all games, using ver0.6.0.

So interaction are inverted too.. it's quite disturbing. Hope this helps

**Comment by antonpup** [comment]
@km972 What keyboard do you have? What localization? Have you set your localization in Aurora settings?

**Comment by km972** [comment]
Have a K70 RapidFire RGB , lmocalization is set on French on Aurora settings. screen below

![fr2](https://cloud.githubusercontent.com/assets/25014888/21779366/a75e580e-d6a7-11e6-990c-642033db8f01.PNG)

**Comment by km972** [comment]
Issue still not resolved, any news ?

**Comment by antonpup** [comment]
Which keys are inverted again? Is it just the lighting? Are interactive effects firing on correct keys in Aurora?

**Comment by km972** [comment]
The keys inverted are : 
w for z
q for a
as on the previous screen, by the way whatever the game i play, the lights and interaction works like i have an Qwerty layout instead of an Azerty.
Basically Aurora act like Azerty french layout doesnt exist.
