### ISSUE TITLE
Overlapping UpdateLights events

### ISSUE THREAD

**Issue by VoronFX** [antonpup/Aurora#289]
Hi, again! 
When I begin to write scripts I've stumbled with that UpdateLights event can overlap. I rewrote scripts in safe way so that is not a problem anymore. But I think it's a weak place that can produce hidden problems in program and in user scripts especially, although it can happen too rare, it still can. Instead of always keeping in mind this edge case I decided to make some research if this behavior can be excluded in it's root. Here is some results:

Everything begins from `update_timer` that fires `update_timer_Tick` no matter what happens. It even eating exceptions that may occur in `update_timer_Tick`. The first idea is to make timer one-shot and reactivate it in the end of  'update_timer_Tick'. But then if `update_timer_Tick` fails it will not reactivate timer. The most straightforward fix is `try{ } finally { }` block. I've done some test that showed about 5% performance penalty for wrapping in `try{ } finally { }`. As alternative way we can run another timer with long interval, for example 1 or 5 secs, that checks if  'update_timer_Tick' occurred in recent time, and if not (probably cause of exception) trigger the timer. 

Or we can leave everything as it is and consider this rare edge case as too rare and hope that it will not cause any problems even if happens.  =)

Tell me what you think about it.

**Comment by simon-wh** [comment]
Theoretically, if the Timers.Timer is 'eating' the exception, wouldn't it be running in a try block anyway, resulting in that performance reduction? I doubt the try-catch block would have a noticeable effect on effect response, the Threading.Timer also runs on a different thread so the slowdown would only really be on the keyboard effect responsiveness. I'm going to do some testing with the performance overhead of the try-catch to see what it is like.

**Comment by VoronFX** [comment]
Yeah, I was thinking the same. Now I've checked and yes, Timers.Timer is using try-catch while Threading.Timer is not.

Here is decompiled Timer.Timer
```CSharp
    private void MyTimerCallback(object state)
    {
      if (state != this.cookie)
        return;
      if (!this.autoReset)
        this.enabled = false;
      Timer.FILE_TIME lpSystemTimeAsFileTime = new Timer.FILE_TIME();
      Timer.GetSystemTimeAsFileTime(ref lpSystemTimeAsFileTime);
      ElapsedEventArgs e = new ElapsedEventArgs(lpSystemTimeAsFileTime.ftTimeLow, lpSystemTimeAsFileTime.ftTimeHigh);
      try
      {
        ElapsedEventHandler onIntervalElapsed = this.onIntervalElapsed;
        if (onIntervalElapsed == null)
          return;
        if (this.SynchronizingObject != null && this.SynchronizingObject.InvokeRequired)
          this.SynchronizingObject.BeginInvoke((Delegate) onIntervalElapsed, new object[2]
          {
            (object) this,
            (object) e
          });
        else
          onIntervalElapsed((object) this, e);
      }
      catch
      {
      }
    }
```
and Threading.Timer
```CSharp
    [SecuritySafeCritical]
    internal void CallCallback()
    {
      if (FrameworkEventSource.IsInitialized && FrameworkEventSource.Log.IsEnabled(EventLevel.Informational, (EventKeywords) 16))
        FrameworkEventSource.Log.ThreadTransferReceiveObj((object) this, 1, string.Empty);
      if (this.m_executionContext == null)
      {
        this.m_timerCallback(this.m_state);
      }
      else
      {
        using (ExecutionContext executionContext = this.m_executionContext.IsPreAllocatedDefault ? this.m_executionContext : this.m_executionContext.CreateCopy())
        {
          ContextCallback callback = TimerQueueTimer.s_callCallbackInContext;
          if (callback == null)
            TimerQueueTimer.s_callCallbackInContext = callback = new ContextCallback(TimerQueueTimer.CallCallbackInContext);
          ExecutionContext.Run(executionContext, callback, (object) this, true);
        }
      }
    }
```

So the best will using Threading.Timer with try-catch manually. 
Still wonder how we come to this problem simultaneously =).

**Comment by simon-wh** [comment]
It's pretty weird. I kept running into an exception with StringProperty when it was initializing Dota 2 items, discovered that this was the root issue. I'll make a commit that throws in the try-catch to the update call.

**Comment by VoronFX** [comment]
Cool, now I've nothing to worry about!
