### ISSUE TITLE
Aurora 0.4.3 crashes on startup

### ISSUE THREAD

**Issue by neamtua** [antonpup/Aurora#29]
Hi. I've just downloaded it for the first time and did the whole setup but it crashes every time i start it up.

Error is
`Fatal Exception caught : System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
`
I've attached the log. I have a logitech G810 keyboard, if that helps at all.

[2016_12_06.zip](https://github.com/antonpup/Aurora/files/310954/2016_12_06.zip)

**Comment by antonpup** [comment]
It's an issue that's been resolved on my local version. I will see about releasing an update today.
