### ISSUE TITLE
Masterkeys Pro S FPS drops in Overwatch Version 0.6.0

### ISSUE THREAD

**Issue by InfiniteBored** [antonpup/Aurora#290]
Hi (hope i posted this in the right thingy :D )

Well first off thanks for adding support for the Masterkeys.

But it seems there is a problem with the Framerate when Auroa is running.

If you are in spawn and the H Key is blinking the frames just go under 50FPS after you leave the spawn it goes up again.

Same for all the other keys that indicate a cooldown oder ultimate. Like the left shift of Mei if used than it blinks red indicating that it is on a cooldown and so the fps goes down.

I made a little video that shows the problem.
https://youtu.be/Ix6TdLTeZNg

Also the "Ü" ( "[ {" on ANSI), "#" ("\ :" on ANSI) and the "<>" (the extra key right of left shift) aren't lit
German Layout BTW

Cheers ;)

**Comment by antonpup** [comment]
I'll see if I can squeeze out extra performance.

**Comment by antonpup** [comment]
The computer that I have access to right now handles Overwatch at 40-60 fps. Which makes no difference whether any keys are blinking. Maybe your anti-cheat is messing with Aurora's wrapper? If not, I can try to really squeeze out last drops of performance.

**Comment by antonpup** [comment]
I'm working on a small patch that I hope will improve performance. Give me a few minutes.

**Comment by antonpup** [comment]
I obviously was wrong in my previous performance improvement assumptions. I will rewrite the wrapper a bit to see if I can get it to be more optimal.

**Comment by antonpup** [comment]
I rewrote the wrappers a bit, and I was able to squeeze out a few frames out of my system. See if this will improve your performance. (Make sure to reapply the wrappers)

https://puu.sh/t5zbt/9425b2900a.zip

**Comment by InfiniteBored** [comment]
Thanks.

Yeah got a few frames more but still far from beeing playable (my opinon. Went from 39FPS to like 45FPS. Tested also a few other Games like CS and GTA5 and there i have 0 issues. 

Guess i am not gonna use Auroa for OW than.

**Comment by antonpup** [comment]
Can you send me your log files? I encountered a similar issue where FPS would go down to 30 fps when the log was spammed.

**Comment by InfiniteBored** [comment]
Sure here you go http://pastebin.com/N8gv1Gvi

**Comment by antonpup** [comment]
Let me give you another version to try. https://puu.sh/t656F/948153848e.zip

**Comment by InfiniteBored** [comment]
Oh my it's like witchcraft :D
Now it is playable still some drops here and there but at least most of the time it is 150FPS wich is good cause of my 144hz Monitor.

BIG THANKS
