### ISSUE TITLE
Overwatch and League of Legends not functional in Aurora

### ISSUE THREAD

**Issue by Zwepo** [antonpup/Aurora#291]
Aurora recognizes that the games are installed, but it does not provide any sort of customization for them. The keyboard is blank and lacks the tabs that usually allow one's self to modify the keys. Example:
![image](https://cloud.githubusercontent.com/assets/24834516/21558505/aeb339c6-ce00-11e6-8c3c-f7fdf657cafe.png)
![image](https://cloud.githubusercontent.com/assets/24834516/21558506/b83c0388-ce00-11e6-936f-dd09125c5fda.png)

Other games function normally, appearing as such:
![image](https://cloud.githubusercontent.com/assets/24834516/21558547/610cf56c-ce01-11e6-8668-a66d8c804c0d.png)

I'm using a g810 and have enabled lightfx in League of Legends, but nothing changed. Ironically, these are the two games I play the most. Please advise.

**Comment by antonpup** [comment]
Take a look at fixes here #42 also they don't have much customization in 0.5.1, try 0.6.0 pre-release #287

**Comment by Zwepo** [comment]
Thanks, turns out I had multiple 2015 c++ redistributables. Deleted older versions and set Overwatch to open as administrator. Everything is working fine!
