### ISSUE TITLE
Unable to use the Pre-Release. 

### ISSUE THREAD

**Issue by the27club** [antonpup/Aurora#293]
Before using the pre-release, I went into the beta 0.5.1d window and hit update and it just said i was up to date. I'm not sure if i have missed a step or something, but ive downloaded the pre-release from the webpage and it still says i am using Beta0.5.1d. The updater ran and everything and restarted.

Im not sure if im just overlooking anything or if im just plain stupid haha. Help?

**Comment by antonpup** [comment]
When you download the pre-release, it will say that there's a new version available. That is in fact the previous version. So when it asks you to "update" cancel it.

**Comment by the27club** [comment]
Okay, so pretty much, open the 0.5.1d beta, then download the pre-release from your page. Then do I go into the pre-release folder and open the Aurora Application while having the Beta open?

**Comment by antonpup** [comment]
1. Download pre-release and extract it somewhere
2. Close all instances of Aurora
3. Run the extracted pre-release
4. ???
5. Profit!

**Comment by the27club** [comment]
So after following those steps, the "about" section does not say it is the newer release and I have looked through and saw none of the things in the change log for the pre-release. not too sure what I could be doing wrong.

**Comment by antonpup** [comment]
Well... You just have to download the release files from [here](https://github.com/antonpup/Aurora/releases/tag/v0.6.0-pre), extract them, and run them.

**Comment by the27club** [comment]
i had to extract that bout 3 times to work, but now it is fine. thank you for your patience!
