### ISSUE TITLE
Problems with the german keyboard Layout (Razer Blackwidow Chroma)

### ISSUE THREAD

**Issue by dfg260** [antonpup/Aurora#294]
When the german layout is selected there are following lighting problems:
"Ü" activates "Ö"
"Ö" activates "^"
"^" doesent light up when pressed
The numpad enter key activates the normal enter key
"alt gr" activates "alt gr" & "left strg" 
The Ü key is completely unresponsive (Doesent light up when using  a solid fill color layer)

**Comment by antonpup** [comment]
Are you using the 0.6.0 pre-release version? #287

**Comment by dfg260** [comment]
yes.

**Comment by antonpup** [comment]
@dfg260 Try this version: https://puu.sh/t5fqe/d58be7d9d0.zip

It's the one I used to fix French layout on Corsair keyboards, but I also did changes for Razer there.

**Comment by dfg260** [comment]
This fix doesent work

**Comment by antonpup** [comment]
Is this a problem with the interactive layer? Or is this a problem with incorrect key lighting?

**Comment by dfg260** [comment]
I tested the keys with the interactive layer. But the Ü key is always off.

**Comment by antonpup** [comment]
What keyboard layout are you using? The one I have up on my On-Screen Keyboard seems to work fine. The interactive effects light up correct keys on the Aurora keyboard. Are the keys on the Aurora virtual keyboard lighting up properly for you?

![](https://puu.sh/t64Gc/fe75b1f424.png)

**Comment by dfg260** [comment]
![unbenannt-1](https://cloud.githubusercontent.com/assets/1705723/21572665/fbf2d86e-cedb-11e6-8019-6d9a05561c34.png)
The virtual layout is right but it lights up the wrong keys

**Comment by antonpup** [comment]
Ok. Here's a version that should hopefully fix everything except Ü and Alt gr. (In terms of lighting)

https://puu.sh/t67Gb/aa991536af.zip

Let me know if my assumptions are correct.

**Comment by dfg260** [comment]
Result:
![screenshot_4](https://cloud.githubusercontent.com/assets/1705723/21573889/70453f32-ceea-11e6-8aae-804d624996fc.png)

**Comment by antonpup** [comment]
Hey! At least the logo works now!

Try this version: https://puu.sh/t6c0X/399c4741a9.zip

**Comment by dfg260** [comment]
^ is now off, Ü works fine and Ö is flickering pink/green. i guess its trying to dispaly ^and ö on the same key.

**Comment by antonpup** [comment]
With which version? The first one or second one?

**Comment by dfg260** [comment]
the last one.

**Comment by antonpup** [comment]
Are you sure you ran the last one? Because I added it in because I saw that those keys were overlapped.

https://puu.sh/t6cvl/02adcb8ea2.zip

**Comment by dfg260** [comment]
oh, i didnt refresh the page therefore i didnt see the edit. it works now :)

**Comment by antonpup** [comment]
:) Thank you for your help. Enjoy!

**Comment by dfg260** [comment]
I just noticed that Y and Z are exchanged too

**Comment by antonpup** [comment]
Try this version. Should have Y-Z reverted.

https://puu.sh/t7izX/75c45b5dd1.zip
