### ISSUE TITLE
Game support request: Paragon - The best upcoming MOBA - Using many existing features

### ISSUE THREAD

**Issue by Starkiller1113** [antonpup/Aurora#296]
Just saying Paragon is an amazing up and coming moba and I'm looking for somewhat of a copy of the Dota profile. I will be working on my own scripts soon to achieve this hopefully I'll update on any progress. But the features would include:
- Custom per ability key and lighting for each of the 5 abilities and would have two states that it could fade between based on its status of cooldown. (i.e the "R" key for the ult could glow with a breathing effect while ready, but as soon as it it starting it's cooldown not just pressed as some have confirmation it would be off or white). May not need them for the mouse buttons but could be nice to have a G key light up when these are ready.
- A HP and mana bar with custom colour and placement
- A feature that had a custom background or effect like CSGO for each hero would be awesome but not a must have
- There are times or abilities that can cause a hero to become invisible an overlayed lighting effect whilst this is active would be nice (could be a simple on off no counter)
- There are also up to 6 usable item cards such as a hp potion or a ward when these are ready to be used (not on cooldown) maybe based on their usage number could do the same as abilities in lighting up a custom colour when available and off when not (fading in between based on cooldown)

Many of these features already exist but right now I'm unsure on how to retrieve info from the game to the scripts. Thanks and I'm very excited to see this happen. The game is Paragon by Epic Games and is an amazing game with a huge audience. I would be more than willing to do this myself if someone could help lead me in the right direction as far as retrieving cooldown data from paragon etc.

**Comment by Soulflare3** [comment]
This one can probably be closed, Paragon is shutting down on April 26, 2018
News post here: https://www.epicgames.com/paragon/en-US/news/paragon-to-close-on-april-26
