### ISSUE TITLE
Feature Request: Discord

### ISSUE THREAD

**Issue by McRiot** [antonpup/Aurora#297]
Would it be possible to see something similar to your Skype integration but for Discord? In my opinion Discord is the new hotness for gamers with a lot of new features on the way: 

https://blog.discordapp.com/year-end-teaser-search-screen-share-video-chat-audit-logs-and-channel-organization/

Would love to see this app in a future Aurora update!

Keep up the great work! if you need anything tested on a G910 hit me up. More then happy to help!

**Comment by simon-wh** [comment]
I'll have a look into this, but it if it does come it probably won't come until after the next release.

**Comment by McRiot** [comment]
Any progress? 
Discord is becoming more and more popular in my gaming circles. Would love to see some support for the new App :)

**Comment by Rocket-Scientist2** [comment]
Some possible effects could include being muted/deafened, being called, being in a voice channel, having unread messages, etc.

**Comment by antonpup** [comment]
With [Discord.Net](https://github.com/RogueException/Discord.Net), it seems that you can get notified when you've received a message, also voice states, and itt even allows you to see your "role color" so you can do a few things with that alone. Not sure if it supports "unread messages".

@simon-wh dig in? No need for a separate client (like skype), it should work fine inside Aurora main.

**Comment by simon-wh** [comment]
Having dug into the Discord API a lot more I've concluded that the best option available would be to use the local RPC that is present. However, currently, the local RPC is locked down alongside the GameBridge SDK currently making it not possible for us to use. The other alternative I've found would be doing something similar to how [BetterDiscord](https://github.com/Jiiks/BetterDiscordApp) achieves 'modding' Discord or using a plugin under that. However, these methods are against Discord's ToS and don't appear to be a very viable solution. 

I'm going to close this issue for now until a viable alternative to the locked down RPC appears or the RPC becomes publicly usable.

**Comment by thu2468** [comment]
Is it possible to make it so that it wont pause aurora applet when the discord applet goes and does it thing. 
https://surl.im/i/h30qf b,c i just found out discord got it own applet

**Comment by simon-wh** [comment]
@thu2468 I don't think there is any way to know when the Discord applet is doing its thing so we wouldn't know when to disable the Logitech SDK connection so that it can be shown. Additionally, it would only allow Discord support for people with Logitech devices which isn't very helpful for a lot of people who use Aurora.

**Comment by thu2468** [comment]
Ah ok @simon-wh do you know if the local RPC and the GameBridge still lock?
https://discordapp.com/developers/docs/topics/rpc
https://discordapp.com/gamebridge

**Comment by simon-wh** [comment]
Yeah, @thu2468 it's locked into a private beta and requires you to sign up as a developer of a game to get access to it. I might try another field of contact to see if I can get access to it for Aurora.

**Comment by thu2468** [comment]
@simon-wh lol yeah b.c aurora not a game xD haha

**Comment by simon-wh** [comment]
I've looked into how Steelseries has implemented their support for Discord as mentioned in #742. It appears that they are using the RPC which is still locked under gamebridge so we're not closer to adding support for it.

**Comment by JakeCover** [comment]
Any update on this? Would really love get this working!

**Comment by diogotr7** [comment]
Support for better discord has been merged into the dev branch. You might want to join auroras discord for help with setting it up.
