### ISSUE TITLE
Assign Keys Won't Work

### ISSUE THREAD

**Issue by McRiot** [antonpup/Aurora#299]
One more (not so minor) issue I am having, I assume it must just be me? "Assign Keys" does not seem to work at all for me. I assume it's supposed to let me select all the keys that I want to be a specific color or used for a specific effect. Keystrokes do not seem to be showing in the "Affected Keys" box.

I noticed this issue in the official release too but didn't think much of it as I was still learning the program. Still won't work in 0.6.0
![notassigning](https://cloud.githubusercontent.com/assets/24819387/21579375/cdbb0bb2-cf60-11e6-882f-67a4fe3f4688.jpg)

**Comment by antonpup** [comment]
The way assigning keys works is, you have to press on keys on the virtual keyboard. There's even a message in top left about it.

I'll see about getting key presses as well.

**Comment by McRiot** [comment]
ahh thank you. That was not obvious to me. I did see the message top right "Please select key(s) you want to assign" I just thought it meant press the keys on the keyboard.

> I'll see about getting key presses as well.

That would be far better imo 👍

**Comment by antonpup** [comment]
Added.
