### ISSUE TITLE
Huge CPU overhead and not working

### ISSUE THREAD

**Issue by werdna87** [antonpup/Aurora#30]
After installing, i am getting a huge CPU usage and it is not picking up any games. Aurora is using about 40% of my processor, and close to 2GB of RAM. the only thing it seems to do is light up the top 2 rows of the keyboard. (i am using a logitech g910)

**Comment by antonpup** [comment]
Did the UI show up? Can you send me your latest logs?

**Comment by werdna87** [comment]
No, the UI never showed up and im not sure how to get the logs (where are they located)?

**Comment by werdna87** [comment]
just kidding, found them (i might be blind) here is the log:
[2016_12_06.txt](https://github.com/antonpup/Aurora/files/310973/2016_12_06.txt)

**Comment by antonpup** [comment]
Can you add me on steam, I would like to debug this issue further, as it's quite a serious problem. [http://steamcommunity.com/id/pupant/](http://steamcommunity.com/id/pupant/)

Write on my profile before adding, so I know who to add.

**Comment by antonpup** [comment]
Issue has been located, it will be fixed in the next version.

**Comment by jdubnz** [comment]
This issue just happened to me after the latest update. Using 83% of my CPU causing 1 fps in Rocket League! And on a side note, they keyboard went blue for rocket league, but no boost effects or score.

**Comment by antonpup** [comment]
Can you post your log file at the time of the incident?

**Comment by jdubnz** [comment]
It didn't seem to save sorry. I had to end process in task manager to fix it as the entire computer was struggling. It happened around 1am. The log ends at 10.30pm the day before, and starts at 2pm when I relaunched it. Nothing at the time it happened. I will try to recreate the issue

________________________________

**Comment by jdubnz** [comment]
It didn't seem to save sorry. I had to end process in task manager to fix it as the entire computer was struggling. It happened around 1am. The log ends at 10.30pm the day before, and the next one starts at 2pm when I relaunched it. Nothing at the time it happened. I will try to recreate the issue.

**Comment by jdubnz** [comment]
Log file before. the 80% CPU usage.
========================================
Operation System: Windows 10 Home
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 4
User DomainName: DESKTOP-RR8N683
User Name: Jack
SystemPageSize: 4096
Version: 4.0.30319.42000
========================================

[INFO] 1/07/2016 3:14:02 PM: Device, Logitech, was initialized
[ERROR] 1/07/2016 3:14:02 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 1/07/2016 3:14:02 PM: Device, Corsair, was not initialized
[INFO] 1/07/2016 3:14:02 PM: No Chroma SDK available
[ERROR] 1/07/2016 3:14:02 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 1/07/2016 3:14:02 PM: Device, Razer, was not initialized
[INFO] 1/07/2016 3:14:02 PM: Loading KB Layouts
[INFO] 1/07/2016 3:14:02 PM: Retrying Device Initialization
[ERROR] 1/07/2016 3:14:02 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 1/07/2016 3:14:02 PM: Device, Corsair, was not initialized
[INFO] 1/07/2016 3:14:02 PM: No Chroma SDK available
[ERROR] 1/07/2016 3:14:02 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 1/07/2016 3:14:02 PM: Device, Razer, was not initialized
[INFO] 1/07/2016 3:14:02 PM: Input Hooking
[INFO] 1/07/2016 3:14:02 PM: Starting GameEventHandler
[INFO] 1/07/2016 3:14:02 PM: Starting GameStateListener
1/07/2016 3:14:02 PM: Listening for game integration calls...
[INFO] Baseline X = 44
[INFO] Baseline Y = 37
[INFO] 1/07/2016 3:14:07 PM: Retrying Device Initialization
[ERROR] 1/07/2016 3:14:07 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 1/07/2016 3:14:07 PM: Device, Corsair, was not initialized
[INFO] 1/07/2016 3:14:07 PM: No Chroma SDK available
[ERROR] 1/07/2016 3:14:07 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 1/07/2016 3:14:07 PM: Device, Razer, was not initialized
[INFO] 1/07/2016 3:14:12 PM: Retrying Device Initialization
[ERROR] 1/07/2016 3:14:12 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 1/07/2016 3:14:12 PM: Device, Corsair, was not initialized
[INFO] 1/07/2016 3:14:12 PM: No Chroma SDK available
[ERROR] 1/07/2016 3:14:12 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 1/07/2016 3:14:12 PM: Device, Razer, was not initialized
[INFO] 1/07/2016 3:14:17 PM: Retrying Device Initialization
[ERROR] 1/07/2016 3:14:17 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 1/07/2016 3:14:17 PM: Device, Corsair, was not initialized
[INFO] 1/07/2016 3:14:17 PM: No Chroma SDK available
[ERROR] 1/07/2016 3:14:17 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 1/07/2016 3:14:17 PM: Device, Razer, was not initialized
[INFO] 1/07/2016 3:14:22 PM: Retrying Device Initialization
[ERROR] 1/07/2016 3:14:22 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 1/07/2016 3:14:22 PM: Device, Corsair, was not initialized
[INFO] 1/07/2016 3:14:22 PM: No Chroma SDK available
[ERROR] 1/07/2016 3:14:22 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 1/07/2016 3:14:22 PM: Device, Razer, was not initialized
[INFO] 1/07/2016 3:14:27 PM: Retrying Device Initialization
[ERROR] 1/07/2016 3:14:27 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 1/07/2016 3:14:27 PM: Device, Corsair, was not initialized
[INFO] 1/07/2016 3:14:27 PM: No Chroma SDK available
[ERROR] 1/07/2016 3:14:27 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 1/07/2016 3:14:27 PM: Device, Razer, was not initialized
[INFO] 1/07/2016 3:14:32 PM: Retrying Device Initialization
[ERROR] 1/07/2016 3:14:32 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 1/07/2016 3:14:32 PM: Device, Corsair, was not initialized
[INFO] 1/07/2016 3:14:32 PM: No Chroma SDK available
[ERROR] 1/07/2016 3:14:32 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 1/07/2016 3:14:32 PM: Device, Razer, was not initialized
[INFO] 1/07/2016 3:14:37 PM: Retrying Device Initialization
[ERROR] 1/07/2016 3:14:37 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 1/07/2016 3:14:37 PM: Device, Corsair, was not initialized
[INFO] 1/07/2016 3:14:37 PM: No Chroma SDK available
[ERROR] 1/07/2016 3:14:37 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 1/07/2016 3:14:37 PM: Device, Razer, was not initialized
[INFO] 1/07/2016 3:14:42 PM: Retrying Device Initialization
[ERROR] 1/07/2016 3:14:42 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 1/07/2016 3:14:42 PM: Device, Corsair, was not initialized
[INFO] 1/07/2016 3:14:42 PM: No Chroma SDK available
[ERROR] 1/07/2016 3:14:42 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 1/07/2016 3:14:42 PM: Device, Razer, was not initialized
[INFO] 1/07/2016 3:14:47 PM: Retrying Device Initialization
[ERROR] 1/07/2016 3:14:47 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 1/07/2016 3:14:47 PM: Device, Corsair, was not initialized
[INFO] 1/07/2016 3:14:47 PM: No Chroma SDK available
[ERROR] 1/07/2016 3:14:47 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 1/07/2016 3:14:47 PM: Device, Razer, was not initialized
1/07/2016 4:09:56 PM: [Server] Pipe connection established
1/07/2016 5:17:45 PM: Connection lost
1/07/2016 6:04:03 PM: [Server] Pipe connection established
1/07/2016 7:25:53 PM: Connection lost
1/07/2016 8:57:29 PM: [Server] Pipe connection established
1/07/2016 10:11:11 PM: Connection lost
------------------------------------------------------------------------------------------------------------------------------
Log File after restarting system. ~60% usage

[INFO] 2/07/2016 1:12:34 AM: Device, Logitech, was shutdown
========================================
Operation System: Windows 10 Home
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 4
User DomainName: DESKTOP-RR8N683
User Name: Jack
SystemPageSize: 4096
Version: 4.0.30319.42000
========================================

[INFO] 2/07/2016 1:54:05 PM: Device, Logitech, was initialized
[ERROR] 2/07/2016 1:54:05 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 2/07/2016 1:54:05 PM: Device, Corsair, was not initialized
[INFO] 2/07/2016 1:54:05 PM: No Chroma SDK available
[ERROR] 2/07/2016 1:54:05 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 2/07/2016 1:54:05 PM: Device, Razer, was not initialized
[INFO] 2/07/2016 1:54:05 PM: Loading KB Layouts
[INFO] 2/07/2016 1:54:05 PM: Retrying Device Initialization
[ERROR] 2/07/2016 1:54:05 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 2/07/2016 1:54:05 PM: Device, Corsair, was not initialized
[INFO] 2/07/2016 1:54:05 PM: No Chroma SDK available
[ERROR] 2/07/2016 1:54:05 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 2/07/2016 1:54:05 PM: Device, Razer, was not initialized
[INFO] 2/07/2016 1:54:05 PM: Input Hooking
[INFO] 2/07/2016 1:54:05 PM: Starting GameEventHandler
[INFO] 2/07/2016 1:54:05 PM: Starting GameStateListener
2/07/2016 1:54:05 PM: Listening for game integration calls...
[INFO] Baseline X = 44
[INFO] Baseline Y = 37
[INFO] 2/07/2016 1:54:10 PM: Retrying Device Initialization
[ERROR] 2/07/2016 1:54:10 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 2/07/2016 1:54:10 PM: Device, Corsair, was not initialized
[INFO] 2/07/2016 1:54:10 PM: No Chroma SDK available
[ERROR] 2/07/2016 1:54:10 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 2/07/2016 1:54:10 PM: Device, Razer, was not initialized
[INFO] 2/07/2016 1:54:15 PM: Retrying Device Initialization
[ERROR] 2/07/2016 1:54:15 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 2/07/2016 1:54:15 PM: Device, Corsair, was not initialized
[INFO] 2/07/2016 1:54:15 PM: No Chroma SDK available
[ERROR] 2/07/2016 1:54:15 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 2/07/2016 1:54:15 PM: Device, Razer, was not initialized
[INFO] 2/07/2016 1:54:20 PM: Retrying Device Initialization
[ERROR] 2/07/2016 1:54:20 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 2/07/2016 1:54:20 PM: Device, Corsair, was not initialized
[INFO] 2/07/2016 1:54:20 PM: No Chroma SDK available
[ERROR] 2/07/2016 1:54:20 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 2/07/2016 1:54:20 PM: Device, Razer, was not initialized
[INFO] 2/07/2016 1:54:25 PM: Retrying Device Initialization
[ERROR] 2/07/2016 1:54:25 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 2/07/2016 1:54:25 PM: Device, Corsair, was not initialized
[INFO] 2/07/2016 1:54:25 PM: No Chroma SDK available
[ERROR] 2/07/2016 1:54:25 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 2/07/2016 1:54:25 PM: Device, Razer, was not initialized
[INFO] 2/07/2016 1:54:30 PM: Retrying Device Initialization
[ERROR] 2/07/2016 1:54:30 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 2/07/2016 1:54:30 PM: Device, Corsair, was not initialized
[INFO] 2/07/2016 1:54:30 PM: No Chroma SDK available
[ERROR] 2/07/2016 1:54:30 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 2/07/2016 1:54:30 PM: Device, Razer, was not initialized
[INFO] 2/07/2016 1:54:35 PM: Retrying Device Initialization
[ERROR] 2/07/2016 1:54:35 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 2/07/2016 1:54:35 PM: Device, Corsair, was not initialized
[INFO] 2/07/2016 1:54:35 PM: No Chroma SDK available
[ERROR] 2/07/2016 1:54:35 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 2/07/2016 1:54:35 PM: Device, Razer, was not initialized
[INFO] 2/07/2016 1:54:40 PM: Retrying Device Initialization
[ERROR] 2/07/2016 1:54:40 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 2/07/2016 1:54:40 PM: Device, Corsair, was not initialized
[INFO] 2/07/2016 1:54:40 PM: No Chroma SDK available
[ERROR] 2/07/2016 1:54:40 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 2/07/2016 1:54:40 PM: Device, Razer, was not initialized
[INFO] 2/07/2016 1:54:45 PM: Retrying Device Initialization
[ERROR] 2/07/2016 1:54:45 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 2/07/2016 1:54:45 PM: Device, Corsair, was not initialized
[INFO] 2/07/2016 1:54:45 PM: No Chroma SDK available
[ERROR] 2/07/2016 1:54:45 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 2/07/2016 1:54:45 PM: Device, Razer, was not initialized
[INFO] 2/07/2016 1:54:50 PM: Retrying Device Initialization
[ERROR] 2/07/2016 1:54:50 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 2/07/2016 1:54:50 PM: Device, Corsair, was not initialized
[INFO] 2/07/2016 1:54:50 PM: No Chroma SDK available
[ERROR] 2/07/2016 1:54:50 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 2/07/2016 1:54:50 PM: Device, Razer, was not initialized
2/07/2016 1:55:41 PM: [Server] Pipe connection established
2/07/2016 1:56:20 PM: Connection lost
2/07/2016 1:56:51 PM: [Server] Pipe connection established
2/07/2016 2:53:45 PM: Connection lost
[INFO] 2/07/2016 4:10:00 PM: Device, Logitech, was shutdown
========================================
Operation System: Windows 10 Home
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 4
User DomainName: DESKTOP-RR8N683
User Name: Jack
SystemPageSize: 4096
Version: 4.0.30319.42000
========================================

[INFO] 2/07/2016 4:10:04 PM: Device, Logitech, was initialized
[ERROR] 2/07/2016 4:10:04 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 2/07/2016 4:10:04 PM: Device, Corsair, was not initialized
[INFO] 2/07/2016 4:10:04 PM: No Chroma SDK available
[ERROR] 2/07/2016 4:10:04 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 2/07/2016 4:10:04 PM: Device, Razer, was not initialized
[INFO] 2/07/2016 4:10:04 PM: Retrying Device Initialization
[ERROR] 2/07/2016 4:10:04 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 2/07/2016 4:10:04 PM: Loading KB Layouts
[INFO] 2/07/2016 4:10:04 PM: Device, Corsair, was not initialized
[INFO] 2/07/2016 4:10:04 PM: No Chroma SDK available
[ERROR] 2/07/2016 4:10:04 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 2/07/2016 4:10:04 PM: Device, Razer, was not initialized
[INFO] 2/07/2016 4:10:04 PM: Input Hooking
[INFO] 2/07/2016 4:10:04 PM: Starting GameEventHandler
[INFO] 2/07/2016 4:10:04 PM: Starting GameStateListener
2/07/2016 4:10:04 PM: Listening for game integration calls...
[INFO] Baseline X = 44
[INFO] Baseline Y = 37
[INFO] 2/07/2016 4:10:09 PM: Retrying Device Initialization
[ERROR] 2/07/2016 4:10:09 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 2/07/2016 4:10:09 PM: Device, Corsair, was not initialized
[INFO] 2/07/2016 4:10:09 PM: No Chroma SDK available
[ERROR] 2/07/2016 4:10:09 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 2/07/2016 4:10:09 PM: Device, Razer, was not initialized
[INFO] 2/07/2016 4:10:14 PM: Retrying Device Initialization
[ERROR] 2/07/2016 4:10:14 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 2/07/2016 4:10:14 PM: Device, Corsair, was not initialized
[INFO] 2/07/2016 4:10:14 PM: No Chroma SDK available
[ERROR] 2/07/2016 4:10:14 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 2/07/2016 4:10:14 PM: Device, Razer, was not initialized
[INFO] 2/07/2016 4:10:19 PM: Retrying Device Initialization
[ERROR] 2/07/2016 4:10:19 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 2/07/2016 4:10:19 PM: Device, Corsair, was not initialized
[INFO] 2/07/2016 4:10:19 PM: No Chroma SDK available
[ERROR] 2/07/2016 4:10:19 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 2/07/2016 4:10:19 PM: Device, Razer, was not initialized
[INFO] 2/07/2016 4:10:24 PM: Retrying Device Initialization
[ERROR] 2/07/2016 4:10:24 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 2/07/2016 4:10:24 PM: Device, Corsair, was not initialized
[INFO] 2/07/2016 4:10:24 PM: No Chroma SDK available
[ERROR] 2/07/2016 4:10:24 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 2/07/2016 4:10:24 PM: Device, Razer, was not initialized
[INFO] 2/07/2016 4:10:29 PM: Retrying Device Initialization
[ERROR] 2/07/2016 4:10:29 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 2/07/2016 4:10:29 PM: Device, Corsair, was not initialized
[INFO] 2/07/2016 4:10:29 PM: No Chroma SDK available
[ERROR] 2/07/2016 4:10:29 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 2/07/2016 4:10:29 PM: Device, Razer, was not initialized
[INFO] 2/07/2016 4:10:34 PM: Retrying Device Initialization
[ERROR] 2/07/2016 4:10:34 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 2/07/2016 4:10:34 PM: Device, Corsair, was not initialized
[INFO] 2/07/2016 4:10:34 PM: No Chroma SDK available
[ERROR] 2/07/2016 4:10:34 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 2/07/2016 4:10:34 PM: Device, Razer, was not initialized
[INFO] 2/07/2016 4:10:39 PM: Retrying Device Initialization
[ERROR] 2/07/2016 4:10:39 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 2/07/2016 4:10:39 PM: Device, Corsair, was not initialized
[INFO] 2/07/2016 4:10:39 PM: No Chroma SDK available
[ERROR] 2/07/2016 4:10:39 PM: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 2/07/2016 4:10:39 PM: Device, Razer, was not initialized
[INFO] 2/07/2016 4:10:44 PM: Retrying Device Initialization
[ERROR] 2/07/2016 4:10:44 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
----------------------------------------------------------------------------------------------------------------------
After rebooting Aurora whilst still in Rocket League the CPU usage was low, but no RL lighting effects  were running

**Comment by antonpup** [comment]
Hmm... Does Rocket League profile still work? It might be an issue strictly related to Rocket League.

**Comment by SoupOrJuice** [comment]
Rocket League profile for me doesn't work as well, and I have the same issue - after a while of playing Rocket League, the CPU Usage for Aurora shoots upwards of 80+% and my framerate drops to below 20.
[Here's my log file, as a text file - hope that's okay.](https://github.com/antonpup/Aurora/files/345469/2016_03_07.log.txt)

**Comment by antonpup** [comment]
Looks like I will have to play some Rocket League. Alright, I'll look into it. Most likely a memory leak somewhere.

Thank you for your report.

**Comment by antonpup** [comment]
Issue recreated. Looking into it.

**Comment by antonpup** [comment]
CPU problem with Rocket League fixed. Will be working normal next update, but for now, it is recommended to disable Rocket League profile.
