### ISSUE TITLE
Issues with Logitech Gaming Software

### ISSUE THREAD

**Issue by yucaipawarrior** [antonpup/Aurora#300]
Whenever Aurora is running, even if I disable the game in Aurora itself, LGS gets really choppy and all macros become very laggy. They will be delayed by about a second and will run several times as opposed to the one press. Not just the macros lag but also the UI itself. The entire LGS window gets really laggy to where it is almost impossible to work with. The program works normal as soon as Aurora is closed.

Devices - Logitech G502, Logitech G930, Logitech G910 Orion Spark

System - i7 4790k, 16gb RAM, Asus Z97s Krait, GTX 1070

Any way to fix this?

**Comment by antonpup** [comment]
I had this when I downgraded LGS from 8.89. Try reinstalling latest LGS and restart. I'm sure isn't an issue within LGS.

**Comment by antonpup** [comment]
Stupid phone >.< "I am sure it's an issue within LGS, not Aurora"

**Comment by yucaipawarrior** [comment]
I'm on the most current version of LGS

**Comment by antonpup** [comment]
Reinstall LGS and restart. It worked for me.

**Comment by antonpup** [comment]
Any updates on this?
