### ISSUE TITLE
Overwatch Profile: Lighting is very dim on Logitech G810

### ISSUE THREAD

**Issue by MRiGGz** [antonpup/Aurora#301]
Just as the title says. Don't get me wrong I love this profile for overwatch, and really prefer it over Logitech's Profile. I just wish that the lights weren't dim on it. Some characters like Bastion and McCree you can't even really see the lights. If anyone could help me figure this out it would be much appreciated.

**Comment by antonpup** [comment]
It's not an issue exclusive to G810. Some Razer keyboards also suffer from this. You can use the Color Enhancing. But unfortunately trying to adjust colors past that results in other colors being overexposed.

**Comment by MRiGGz** [comment]
Yeah I seen that enhancing the color helps a little, but is there anything I can change in the files to help aswell?

**Comment by antonpup** [comment]
Settings for the color enhancing can be found here: https://github.com/antonpup/Aurora/issues/234#issuecomment-265023604

**Comment by antonpup** [comment]
There is another potential solution, to use [HSL](https://en.wikipedia.org/wiki/HSL_and_HSV) to boost the brightness of each dark color. But I am afraid of implementing this because it might lead to characters that have very dark colors (like near black) to be displayed as a gray color.

**Comment by MRiGGz** [comment]
How exactly would I go about doing this? I'm willing to try this.

**Comment by LukasACH** [comment]
I've played around with some algorithms, especially with image gamma correction, but am currently unable to test it myself. I have no idea of how strong the effect is visible on already bright Colors or how it interacts with pusing colors like the ability cooldowns.

`newColorRedPart = (byte)Math.Min(255, (int)((255.0 * Math.Pow(color.R / 255.0, 1.0 / gammaCorrection)) + 0.5));`
I've tested it on plain Colors, where values of `gammaCorrection` between `1.5f` and `3.0f` resulting in pretty good colors.

**Comment by kasyx09** [comment]
Does it mean it will be corrected in new version of Aurora ?

**Comment by LukasACH** [comment]
I'm not sure if the solution above result in better colors. It might also make the experience worse. At the beginning of next week, I will try to implement and test it. If it works, I will make a PR as soon as possible.

**Comment by LukasACH** [comment]
I've created a Pull Request #335 with a new method to calculate the color. It does better with dark colors like McCree or Bastion, but worse with already bright colors.

**Comment by antonpup** [comment]
@LukasACH use `Utils.ColorUtils.IsColorDark(color);` to determine if a color needs adjustment?

**Comment by LukasACH** [comment]
The problem is that I affect every channel on it's own on the whole 0-255. If I would simply don't touch it beyond that threshold, the brighness would make a jump down again. (darker -> brighter -> darker again)
And the Implementation you mentioned is special weighted on the different color channels.

**Comment by LukasACH** [comment]
I have finally got it to work without any compromises. It does a better job with very dark colors and provieds more user customability.

**Comment by kasyx09** [comment]
ok. so should I wait for a new version of Aurora where it is fixed or what to do with that ? :)

**Comment by antonpup** [comment]
I'll be looking over his pull request sometime this weekend, so I would say next version will include it.

**Comment by kasyx09** [comment]
ok nice :) thx :)

**Comment by MRiGGz** [comment]
Good job guys, looking forward to seeing this change in a new update. :)

**Comment by antonpup** [comment]
The solution provided by @LukasACH works very well! Next update will include it.

**Comment by kasyx09** [comment]
When is it ? I can`t wait ! :]
