### ISSUE TITLE
Feature Request: Ping Pulse / CPU Cores / GPU Load

### ISSUE THREAD

**Issue by McRiot** [antonpup/Aurora#303]
I was using this guys script in the official build before the pre-release 0.6.0

http://modworkshop.net/mydownloads.php?action=view_down&did=18852

I know you have some similar features under "Percent Effect Layer" but this guy has some really neat effects like keyboard dimming out when CPU is under load with a cool num pad color circle going. Theirs a video on his post.

The ping pulse is very cool too.

I really liked it, sadly it no longer functions in the new 0.6.0 pre-release. Maybe these are ideas/features you can expand on in future builds and just make them a part of Auroras core functions :)

**Comment by antonpup** [comment]
You're looking for @VoronFX and I would like to leave it up to him to implement those in.

**Comment by McRiot** [comment]
Here is hoping he updates his scripts for the new build :) It was a favorite for me.

**Comment by VoronFX** [comment]
Yeah! I've just made an update with new scripts and support for version 0.6.0. Check it out!
