### ISSUE TITLE
Start with Windows not working..

### ISSUE THREAD

**Issue by McRiot** [antonpup/Aurora#304]
Selecting the box "Start with Windows" does not seem to be working. Tried with Aurora with and without admin mode. 

running Windows 10 64bit
Aurora 0.6.0

Selecting "Start Aurora in a minimized state" this works when I manually open Aurora

** Checked my Startup tab after rebooting, Aurora is there, Status Enabled, Startup impact Not measured
It's defiantly is not starting up on reboot.

**Comment by antonpup** [comment]
Can you open properties of Aurora.exe, if there's a button for "unblock" or "this file came from another computer". Unblock it and try again.

**Comment by McRiot** [comment]
you talking about right clicking the Aurora.exe / Properties ?

theirs no options like those.

Aurora also shows to be in my regedit>windows>currentversion>run

"C:\Program Files\**\Aurora.exe" -silent -delay 5000

**Comment by McRiot** [comment]
I don't even have skype installed :)

I just changed the regedit file to "C:\Program Files\Logitech Gaming Software\Mods\Aurora\Aurora.exe" /autostart /tray -silent

that fixed it.

probably don't need the /tray (going to remove that and reboot again. I think just /autostart is probably what fixed it.

**Comment by antonpup** [comment]
That's not possible? I don't have those options implemented.

**Comment by McRiot** [comment]
I just altered the registry Run file.

This is what it was: "C:\Program Files**\Aurora.exe" -silent -delay 5000

This is what it is now: "C:\Program Files**\Aurora.exe" /autostart -silent

Seems to have fixed it. Maybe you can use this info to fix the select box.

As far as Aurora I have only ever run the official setup exe and then replaced those files with 0.6.0 later on.

**Comment by antonpup** [comment]
Try just with "-silent". /autostart should have no effect on Aurora.

**Comment by McRiot** [comment]
sure I'll try it. give me a minute
