### ISSUE TITLE
Aurora Crash - Saving over an existing profile.

### ISSUE THREAD

**Issue by McRiot** [antonpup/Aurora#305]
I created  and Saved a new profile, made some changes and selected my existing profile, hit save. 

"Aurora has stopped working" 
close program

seems to do this every time I try to save over an existing profile.

** just made a whole new profile. added a new layer, selected the new profile and tried to save. I get asked if I want to overwrite, I say yes. Aurora crash

**Comment by antonpup** [comment]
It's been fixed. https://github.com/antonpup/Aurora/commit/2c358054d8e194b7a68107614c0ba7d1038dbcad
