### ISSUE TITLE
Windows 10 Login Screen Lag

### ISSUE THREAD

**Issue by WilliamFong** [antonpup/Aurora#307]
When I have Aurora running, I noticed that in the Windows 10 Login Screen, it is extremely laggy. Like when I want to lock my computer, it makes my mouse extremely laggy to move and also to click.

**Comment by antonpup** [comment]
What version of Aurora are you using?

Can you provide the log file for the time when you experienced this issue?

**Comment by WilliamFong** [comment]
I am using beta 0.5.1d. 

And here is the log file. 

http://puu.sh/t8bEO/b6a44ce1e8.log

**Comment by WilliamFong** [comment]
I tested it, and it seems to have that problem when I have the mouse set as a color zone for it to change colors when it's not in a game. 
It happens when I lock my computer, and it goes to the account selection/login screen.


![ss 2017-01-01 at 10 27 21](https://cloud.githubusercontent.com/assets/23246277/21585240/801e2fc6-d071-11e6-97b6-c7fa5c39a6ca.png)

**Comment by WilliamFong** [comment]
LGS does not lag. I am using the latest version. It might be, because I am on Windows 10.

**Comment by antonpup** [comment]
I don't think so. My main computer at home is running Windows 10 Pro. So, it must be something else.

Does it lag forever? Or does the lag go away after a while? It could be slowing down to attempt to initialize devices. When you start Aurora, go into Settings, then Devices & Wrappers tab. 
![](https://puu.sh/t8pw0/01a4be897e.png)
Does Aurora still lag after the "Retries" reaches zero?

**Comment by WilliamFong** [comment]
I don't think that it is the system that is slowing down but rather just the mouse itself. As long as I am on the login screen, the mouse cursor/clicking is lagging. (and yes, there was no retries on Aurora)

**Comment by antonpup** [comment]
I was unable to re-create the issue on my Windows 10 or 7 machines. I can say that when you lock the computer, the mouse lags for a few seconds and then returns back to normal operation.

**Comment by simon-wh** [comment]
Try v0.6.2b if you're still experiencing this
