### ISSUE TITLE
Logitech G910: No Key Lighting in Overwatch

### ISSUE THREAD

**Issue by Gulugumi** [antonpup/Aurora#312]
I have pressed the "Patch Overwatch" and pointed it to where I have installed it. But When i run the game all keys go black and nothing happens.
i'm guessing it has something to do with the "Game Listener".

Thanks in advance. :)

**Comment by brainbug89** [comment]
Do you get an error message telling you Game Listener couldn't get started when starting Aurora?

Try to run Aurora with Admin rights. (This is what I need to do.)

**Comment by Gulugumi** [comment]
I don't get an error. Nothing happens, it just goes black.
I am running it as admin otherwise it won't start at all.

**Comment by antonpup** [comment]
Take a look over solutions for #42

**Comment by Gulugumi** [comment]
I have just tried that. It's not working.
I installed both x86 and x64 of vc_redist, and i am runnning everything as admin.

**Comment by antonpup** [comment]
Can you attach the Aurora log during which you tried playing Overwatch?

**Comment by Gulugumi** [comment]
[2017_02_01.txt](https://github.com/antonpup/Aurora/files/682695/2017_02_01.txt)
here.

**Comment by antonpup** [comment]
I see what is going on here.

Run Command Prompt as administrator and execute the following command: lodctr /R

**Comment by Gulugumi** [comment]
I have done that now.
Not fixed yet.
[2017_03_01.txt](https://github.com/antonpup/Aurora/files/682913/2017_03_01.txt)

**Comment by antonpup** [comment]
Well, if you're running Overwatch. Then the wrapper isn't making a connection with Aurora. Are you sure you installed the wrapper in the correct location? (There should be two files next to Overwatch.exe: "RzChromaSDK64.dll" and "RzChromaSDK.dll")

![](https://puu.sh/t9Vqv/49728b8266.png)

**Comment by Gulugumi** [comment]
I already have those.

**Comment by antonpup** [comment]
I just tested with current Overwatch update (to make sure that Blizzard didn't block Aurora's wrapper), and it worked fine.

So, I believe that your PC isn't allowing wrapper to communicate with Aurora. Do you have any antiviruses or firewalls that could be blocking the wrapper?

**Comment by Tearhead** [comment]
Having this same issue. I tried turning off my antivirus and firewall, but still having the same issue.

**Comment by simon-wh** [comment]
Any updates on this? And, could @Tearhead and @Gulugumi try the [latest development release](https://github.com/antonpup/Aurora/releases) if you're still having issues.

**Comment by Tearhead** [comment]
@simon-wh Yep. working for me now.

**Comment by MightyWalrusss** [comment]
@simon-wh I have all the things i need but it still doesn't work. I don't understand why
