### ISSUE TITLE
Integration Voron Scripts into Aurora

### ISSUE THREAD

**Issue by VoronFX** [antonpup/Aurora#313]
With a new release of Aurora 0.6.0 lot's of functionality of my scripts can be achieved by Aurora itself. Other can be achieved by few modifications. Maybe it's time to become part of Aurora and extend it? I can merge it and make a pull request. 
Features I am planning to do:
- Extend LocalPCInfo with GPU values and other stuff like we was talking [here](https://github.com/VoronFX/Aurora/commit/377d607b0098a3f22eb3b8aeba7a8ad7c59b30d4).
- Add to Percent Effect Layer minimum value, blinking speed, update interval, turn on/off easing/smoothing and ability to take value from custom PerformanceCounter by CategoryName, CounterName, InstanceName.
- PingPulser make as another layer type and provide gui also.

What you think about it? Want you me to work on it?

**Comment by antonpup** [comment]
That would allow for more user control. :)

Yeah, go for it. Maybe also add per-core cpu information to LocalPCInfo, so people can recreate per-core usage.
