### ISSUE TITLE
Import profiles from LGS to Aurora

### ISSUE THREAD

**Issue by kasyx09** [antonpup/Aurora#316]
Hello everyone. I have a keyboard Logitech G810 and I love Overwatch profile in Aurora program. Can you help me how can I set one of the defaults profiles from Logitech Gaming Software to Aurora ? For example rainbow waving or ocean wave when I am out of the game and working on the desktop ? Is it possible ?

**Comment by brainbug89** [comment]
There are two possible options:

1. Recreate the Rainbow wave with Aurora: add Gradient Layer, Set to Rainbow, animation type: Translate X and Y.

2. You can disable the Desktop mode and use LGS for desktop/ Aurora for supported games: goto Desktop Settings and uncheck the box _Enable Aurora to provide lighting effects for desktop_

**Comment by kasyx09** [comment]
Hello. I can`t find option "Enable Aurora to provide lighting effects for dekstop". I`ve looked for every option here before.... :/

**Comment by brainbug89** [comment]
Make sure you're using the version 0.6.0
Desktop Settings > Show Profile Overview/Options >uncheck _Enable Aurora to provide lighting effects for desktop_

![disabledesktopmode](https://cloud.githubusercontent.com/assets/21130949/21644044/d08a3632-d28b-11e6-8c05-3032845d0b88.PNG)

**Comment by kasyx09** [comment]
ok i see the problem. My version is 0.5.1d downloaded from this site. You recommend me to have the v ersion 0.6.0 which is not avaliable on the site... only 0.5.1d...

**Comment by antonpup** [comment]
@kasyx09 0.6.0 is available as a pre-release. It will hopefully be released fully next week.

**Comment by simon-wh** [comment]
Moved LGS import to #429
