### ISSUE TITLE
Shift key for Shortcut Assistant

### ISSUE THREAD

**Issue by Wolfen420** [antonpup/Aurora#318]
Maybe I am just doing this wrong. But for example. I took the default profile of the desktop, renamed it, then modified it how I wanted to using notepad++.  I then move that profile to a new location (in to the custom profiles or in this case the "additional profiles" section and under the application folder there.

Upon launching Aurora though, it will just overwrite my saved changes with the previous version of the file. Basically reverting it to the original. 

But maybe there is some simpler solution to what I want to do. When I create a new app profile I want to have under the shortcuts Assistant a section for Ctrl, Alt, and Shift. However it only defualts with Ctrl and Alt. Hence what I was doing was either copying one of these sections in the .json and then renaming ctrl_ to shift_, etc. But that reverting happens.

**Comment by antonpup** [comment]
That happens because "shift_*" isn't an option. Thus it isn't read from file, and when profile is saved, it isn't saved.

**Comment by Wolfen420** [comment]
Hi, thanks for the reply. Is there a way to use a shift key? left_shift? Something?

**Comment by antonpup** [comment]
No, those aren't defined. I will be reworking the Shortcut Assistant to include a wider range of keys, maybe even 3+ combinations.

But for now, you cannot define anything beyond CTRL, ALT, or WIN.

**Comment by Wolfen420** [comment]
Ahh. Well that explains that haha. Look forward to it. Hope you add shift as an option as well in the future. Thanks for your replies. =)

**Comment by brainbug89** [comment]
> I will be reworking the Shortcut Assistant to include a wider range of keys, maybe even 3+ combinations.

Would be nice to use for Corsair K70 Lock key or Mute key etc. :wink:

**Comment by Wolfen420** [comment]
Cool. Proper title change hehe. Any ETA on this? Got the latest with layer stuff. Great stuff man!

**Comment by simon-wh** [comment]
This is now possible through the Shortcut Assistant rework that'll be available in the next release (or you can get it now through the latest prerelease)
