### ISSUE TITLE
Diablo 3 recently got Corsair/Razer support, hoping to see that get added into Aurora.

### ISSUE THREAD

**Issue by Omniphantasm** [antonpup/Aurora#320]
Any chance to get that working on Logitech keyboards like Overwatch?

> Support has been added for the Corsair Utility Engine (CUE) SDK and Razer peripherals

>Supported backlit keyboards will respond to certain in-game situations like Legendary and Set item drops, characters leveling up, and more

>Players will need to update their firmware for supported devices to use this feature

**Comment by brainbug89** [comment]
Try to apply the Razer wrapper to Diablo 3. It should work... please report back.

**Comment by Omniphantasm** [comment]
Ah, I might have been unclear my bad.

Meant I was hoping to see Aurora get it working on Logitech keyboards like Overwatch does.  

If I'm misunderstanding you let me know how to do it exactly and I'll let you know if it works.

**Comment by brainbug89** [comment]
You need to apply the Razer wrapper to the Diablo 3 folder. There should be two files inside the Diablo 3 folder: RzChromaSDK.dll and RzChromaSDK64.dll

Click Aurora > General Settings > Devices & Wrapper > Install Aurora Wrapper Patch for Razer

Aurora should now be able to receive the RGB information from Diablo 3 and send them to LGS, wich will send them to your Logitech keyboard.

But maybe it doesn't  work.
> Players will need to update their firmware for supported devices to use this feature

Maybe the Aurora wrapper needs to be updated. So please feel free to test it. :wink:

**Comment by Omniphantasm** [comment]
Looks like they only have the CUESDK_2015.dll for Corsair

Not seeing any of the usual Razer ones.

**Comment by antonpup** [comment]
@Omniphantasm So Aurora works with Diablo via Razer wrapper?

**Comment by Omniphantasm** [comment]
Yup, worked perfectly after I rebooted. 

Just point it at the root directory for D3 and if it doesn't start working try rebooting I guess.

**Comment by RancidHyena** [comment]
I can't seem to get it to work, but it's probably because I don't understand how to use the wrapper. Do I add Diablo III using "Add a new lighting profile", and then use the Razer wrapper in general settings and select the Diablo III folder? My Naga V2 responds to the game because of Synapse, but my keyboard stays dark.

**Comment by Omniphantasm** [comment]
Delete the lighting profile for Diablo 3 if you made one and then just do the Razer wrapper in general settings to the base Diablo III folder.

Wound up working for me doing that.

**Comment by RancidHyena** [comment]
I deleted any profiles related to Diablo III in Aurora, then ran the Razer wrapper in the base Diablo III folder. Now, the keyboard stays default whenever I load Diablo III. It changes when I load Overwatch and other games, though.

**Comment by Omniphantasm** [comment]
Weird, is it possible you don't have the latest Logitech update and thats dicking with it? If that's not the case you might as well open up an issue and see if they can help you with it cuz I'm not sure what it could be.

**Comment by RancidHyena** [comment]
I think it may be with either Synapse or the installation itself, because my mouse isn't returning to normal coloring after closing out of Diablo unless I disable the Diablo III Chroma app and unplug my mouse and plug it back in.

**Comment by brainbug89** [comment]
Are you using the Diablo III PTR version?

**Comment by RancidHyena** [comment]
Just the standard Diablo III. I'm not sure how it relates, but I opened Diablo III just now with Aurora and Diablo III enabled in Synapse, and my mouse changed, but stayed red after Diablo III was closed. I disabled Diablo III, and it remained red. Only after disabling Aurora in Synapse did the mouse go back to normal.

**Comment by dump66** [comment]
Sorry to open this again, but is it still working for someone out there?
I've got a G910 and the only thing working for me are the 1,2,3,4 and Q buttons (shining white). But there is no red light or any other buttons shining. Followed the instructions here.

**Comment by simon-wh** [comment]
@dump66 See issue: #539

**Comment by dump66** [comment]
My bad. I knew I saw this bug somewhere in the webs, but could't find it anymore. Thx for the link, though. Hope you get it working and thx for your huge efforts. As a programmer myself I really appreciate your work.

**Comment by Eps77** [comment]
I cant get this to work for me for anything ive tried everything above

**Comment by Eps77** [comment]
Were you guys using the diablo 3 launcher only thing i can think of i just have a darkened keyboard

**Comment by Jaobonz** [comment]
Its not working for me either. I'm using a G810 Logitech. Did the wrapper, tried to reboot everything and still do not apply to the game. =/

**Comment by jdfosterarmy** [comment]
Any updates yet? I can't get diablo 3 to do any effects on my g910 at all. It does work on other games like star trek online so i know aurora does work. and yes i've put the wrapper in both 32bit & 64 bit locations. I followed the instructions to the letter without success
