### ISSUE TITLE
Datafall like in LGS

### ISSUE THREAD

**Issue by nyan257** [antonpup/Aurora#322]
is it possible to add the datafall effect from LGS into an away effect for aurora

**Comment by antonpup** [comment]
I can add it as a "Matrix Effect".

**Comment by antonpup** [comment]
Here's a demo:
![](https://puu.sh/tf8hW/b016f46bd3.gif)

**Comment by nyan257** [comment]
When is this gonna be added?

**Comment by nyan257** [comment]
Sorry

**Comment by antonpup** [comment]
Next version, 0.6.0.

**Comment by nyan257** [comment]
When is it coming out?

**Comment by antonpup** [comment]
Impatient are we? :P Hopefully next week.

**Comment by nyan257** [comment]
Yay

**Comment by PlsHelpmeSenpai** [comment]
For some reason im having a major issue with aurora and LGS today.  For starters, the overwatch profile didnt work, so I reinstalled everything.  Now, it says aurora is in control of everything, but even the desktop profile wont show up.  I really need help.
