### ISSUE TITLE
Aurora dont work with my logitech

### ISSUE THREAD

**Issue by Esitek05** [antonpup/Aurora#323]
Aurora does not work with my logitech keyboard and mouse. I have a Logitech G213 prodigy keyboard and Logitech G302 mouse. What will make the program work properly?

Currently, the program switched on the keyboard lights only when you select a headset / mouse point, but when you select the keyboard, nothing happens.

**Comment by antonpup** [comment]
G213 is a "zone-based RGB". And in the Logitech LED SDK, there is no such thing as a zone. So... There is no way to support that keyboard.

**Comment by vergilet** [comment]
I've asked dev team of Logitech SDK about zones and they answered the next:

> We currently do not have the functionality for this in our release version of LGS and LED SDK. However I would like you to know that your requested functionality is already implemented and will be included in our next release. Be on the lookout for that!
