### ISSUE TITLE
REQUEST: Black Ops 3 (Zombie mode) game state integration :)

### ISSUE THREAD

**Issue by g-uru** [antonpup/Aurora#327]
would love to see this ++

**Comment by antonpup** [comment]
Black Ops should have Razer support. Try the Razer Wrapper.

**Comment by g-uru** [comment]
i use corsair keyboard, does razer software work for it?

**Comment by antonpup** [comment]
... It will work through Aurora.

**Comment by g-uru** [comment]
So i have to download the razor sdk or rather install the latest synapse along with the sdk and then point the wrapper to its install directory?

**Comment by antonpup** [comment]
...

Aurora -> Settings -> Devices & Wrappers -> "Install Aurora Wrapper for Razer", then point it to the folder where Blops 3 zombies exe is.

**Comment by g-uru** [comment]
applied accordingly, now which profile do i use when i start bo3?

**Comment by antonpup** [comment]
It will automatically switch.

**Comment by g-uru** [comment]
it does switch to something else when entering the game. after starting a game in zombie mode there is no game state integration whatsoever though. the whole board just stays brownish static.

**Comment by g-uru** [comment]
to be clear i dont have to install synapse or its sdk?

**Comment by antonpup** [comment]
Aurora switches to the Razer Wrapper and displays the Razer Integration that was done for the game.

**Comment by g-uru** [comment]
i guess then razer didnt write any game state integration 🗡

**Comment by g-uru** [comment]
anything else i can try?

**Comment by antonpup** [comment]
Nothing else comes to mind.
