### ISSUE TITLE
Support for Aura, NZXT, Prismtik

### ISSUE THREAD

**Issue by nyan257** [antonpup/Aurora#329]
1. Asus Aura
2. NZXT Hue+
3. Prismatik for Lightpack
4. Steelseries Engine

**Comment by brainbug89** [comment]
1. Asus Aura doesn't have an API/SDK
2. NZXT Hue+ doesn't have an API/SDK
3. Prismatik could be possible. I don't know if there is an API/SDK
4. Steelseries is already on the [list](https://github.com/antonpup/Aurora#planned-featuressupport)

For Asus Aura and NZXT Hue+ you need to ask the manufacturers for API/SDK support.

**Comment by SpencerCornish** [comment]
@brainbug89 Correct me if I'm wrong, but I believe that AURA does now have a public SDK. Link: https://www.asus.com/campaign/aura/us/SDK.html

**Comment by brainbug89** [comment]
You're right. There is a newer issue for Asus Aura: #546

**Comment by simon-wh** [comment]
@arch-master Yes, these will be dealt with in time. I've currently got exams so I can't do much and I've got some big changes that need to take place before I try to work on these myself.

**Comment by Gurjot95** [comment]
Both Aura and NZXT are WIP. Also closing because of duplicate.

**Comment by tirrorex** [comment]
@Gurjot95 hello, any ETA on this ?
I might be able to help with the programming if you give me some pointers on what needs to be done
(Would need to refresh my c++ skills though as i mostly do swift those days)
