### ISSUE TITLE
Two questions/requests; profile and shortcut assistant

### ISSUE THREAD

**Issue by MrJWalk** [antonpup/Aurora#33]
I'm loving the software.  I was making some requests on reddit with Star Citizen and now that I've had a chance to use Aurora, I've had some thoughts.

Is it possible to have multiple profiles per game?  I think it could be beneficial with macros and such for MMOs.  Also, it could be used for games with multiple roles (like Planetside 2's cloaker and Max suit) or different types of vehicles (land and air).  We could bind a series of keys to swap between profiles and use the logo to indicate which profile we're on (Alt+Shift 1 for bleh / Alt+shift 2 for blah).

The second is with shortcut assistant.  Could it be set up so left ctrl and alt light up differently than right ctrl and alt?  With Star Citizen's latest update, they've really hammered in the left alt is separate from right alt.  Here's an example of what I mean http://i.imgur.com/NfujyYR.jpg.

Also, not sure if it's been reported but in shrotcut assistant both key zone boxes are labeled as "Shortcut Assistant Ctrl Keys".

**Comment by antonpup** [comment]
1. I don't think that sub-profiles fit very well into the nature of Aurora. I want Aurora to be "set it and forget it" type of thing. When a user has to keep switching lighting profiles, I think it would be too tedious for them to do. I suppose I could add this for the "Generic Profiles", but I cannot see this be a thing with already supported profiles.

2. I want to redesign the Shortcuts Assistant. I want to allow the user to select which keys will trigger the assistant as well as define the shortcuts for those keys. So, it should be possible to set Left and Right Controls to be different. But that's on the back burner for now.

**Comment by antonpup** [comment]
Next version of Aurora will have profile import/export as well as profile switching. So that should appeal to your first request.

Still haven't done anything with Shortcuts Assistant. Will probably be a part of following update. Or this one if I can fit it.

**Comment by simon-wh** [comment]
Both features mentioned are available in the current pre-release (v0.6.0-dev2) and will be in the next public release.
