### ISSUE TITLE
Start on Boot

### ISSUE THREAD

**Issue by TechnoPeter** [antonpup/Aurora#331]
Aurora actually boots with Windows, but the lighting effects don't show up on the keyboard. I have to close and reopen it to work.

**Comment by antonpup** [comment]
Next time this happens, try this and let me know if it fixes the issue for you.

Disable the CPU and RAM layers. Upon disabling them, the lighting should start working again, but if you re-enable them, it should break again. Can you verify that is the case?

**Comment by simon-wh** [comment]
Any updates on this?
