### ISSUE TITLE
Corsair strafe rgb not detected

### ISSUE THREAD

**Issue by anzabanza** [antonpup/Aurora#333]
I tried reinstalling cue 2 and nothing works. Cue works ok by itself, but aurora says that there is no corsair device initialized:( Anybody have an idea what could be wrong? I did try with multiple versions of aurora

The log:
[2017_08_01.txt](https://github.com/antonpup/Aurora/files/692355/2017_08_01.txt)

**Comment by antonpup** [comment]
It probably doesn't work with CUE 2 because the SDK hasn't been updated. It's not an issue with Aurora, if Corsair decides to break their own SDK.

_Also, I don't need to know your username, but it does show up in the file paths for configs and what not. It's still visible, But neat edit nonetheless._

**Comment by anzabanza** [comment]
LOL, it was a joke. Anyway I had it working with cue 2 on my previous windows installation.

**Comment by antonpup** [comment]
Enable SDK?

**Comment by anzabanza** [comment]
It is enabled I checked everything, read a bit through the logs and couldn't find out why it doesn't work.

**Comment by brainbug89** [comment]
Does other third party apps with SDK support work?

**Comment by antonpup** [comment]
I plugged in my Strafe RGB, using latest CUE 2. And everything is working properly. Even the "demo K95" was showing proper colors.

So.. I have no idea why it's not functioning. Reinstall CUE?

**Comment by anzabanza** [comment]
I did reinstall it 2 times. In aurora it just says "not initialized". I don't know any other software that's using cue sdk.

**Comment by brainbug89** [comment]
You could try [CEE](http://forum.corsair.com/v3/showthread.php?t=139027)

**Comment by anzabanza** [comment]
I tried CEE and it works ok with the cue sdk. Although it does some funky things sometimes, like flash until you get a seizure and light up random key although it's set as reactive lightning, but that's a problem with the cee itself. Also are there any "hidden" registry settings or something for aurora as when I tried reinstalling it I only removed the files in "C:/Program Files/Aurora" or wherever I placed it.

**Comment by anzabanza** [comment]
I tried using Aurora with cue 1.16 but same result, "Corsair: Not initialized"

**Comment by anzabanza** [comment]
@antonpup Looks like there is a problem with aurora loading the sdk:
`[ERROR] 14. 01. 2017 10:13:37: Corsair device, Exception! Message:System.TypeInitializationException: The type initializer for 'CUE.NET.Native._CUESDK' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: ptr
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
   at CUE.NET.Native._CUESDK.LoadCUESDK()
   at CUE.NET.Native._CUESDK..cctor()
   --- End of inner exception stack trace ---
   at CUE.NET.Native._CUESDK.CorsairPerformProtocolHandshake()
   at CUE.NET.CueSDK.Initialize(Boolean exclusiveAccess)
   at Aurora.Devices.Corsair.CorsairDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Corsair\CorsairDevice.cs:line 67`

**Comment by antonpup** [comment]
Do you have [Visual C++ Redistributable Packages for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145) installed? Also  [Visual C++ Redistributable Packages for Visual Studio 2013](https://www.microsoft.com/en-us/download/details.aspx?id=40784) You need both of x86 and x64.

**Comment by DarthAffe** [comment]
I'll join this conversation to prevent the long way :)
This seems like an installation-problem. CUE.NET isn't able to load the SDK-dll that's why the pointer is null. I don't know how aurora is distributed, but could you check if your aurora installation-folder (or the execution folder if you changed that) contains an x64 and x86 folder, both with an CUESDK_2015.dll inside?

**Comment by antonpup** [comment]
The files are included, you can verify this by downloading the latest release. I use the same zip for automatic updates as well. Is it possible that the dlls get blocked on some PCs?

**Comment by DarthAffe** [comment]
Well I trust you that the installer itself is correct, it seems more like a problem with @anzabanza environment so it would be good if he could check that for his installation.
If they are missing we'd at least know why it doesn't work (and it's the only way I could reproduce this error).
I haven't heard that someone had problems with blocked SDK-dlls but I can not rule it out.

**Comment by anzabanza** [comment]
I reinstalled aurora multiple times, verified the files and everything. I don't know why it would block the dll files as other cue.net programs work just fine.

**Comment by DarthAffe** [comment]
I can't find any other reason for this error. Could you try to take the attached exe, copy it in the aurora execution directory and run it? If it works things get really weird, if the same error occurs there's definitely a installation issue.
[CUE.NET_Test.exe.zip](https://github.com/antonpup/Aurora/files/706721/CUE.NET_Test.exe.zip)

**Comment by anzabanza** [comment]
Yes this worked, finally, thank you so much :D

**Comment by antonpup** [comment]
@anzabanza  Aurora now functions properly?

**Comment by anzabanza** [comment]
Yes as it should. But now I can't get my headset and mouse from Logitech working with build 0.6.0, but it works with 0.5.1b. Probably because I can't figure out how to configure them. Will have to fiddle around with new version of Aurora bit more :)

**Comment by anzabanza** [comment]
Also, are you planning on adding a function that would allow you to also control led strips with help of arduino or raspberry pi through aurora, because that that would be just extremely awesome!

**Comment by antonpup** [comment]
@anzabanza Take a look at https://github.com/antonpup/Aurora/issues/252#issuecomment-272498399 and https://www.youtube.com/watch?v=p0WiaQwmSYQ and here's a branch for it https://github.com/antonpup/Aurora/tree/pi-lighting

**Comment by anzabanza** [comment]
Ok, I just saw the branch and didn't really look into it that much. Still thank you for this awesome software and for your help.

**Comment by anzabanza** [comment]
Well I'm just dumb. Anyway thanks for this awesome software and for your help.

**Comment by Tenns** [comment]
I have the same problem that @anzabanza was having, it says "corsair: not initialized", I tried as @DarthAffe suggested to run the .exe that he gave in the aurora directory but it crashes every time I launch it even as an administrator.

**Comment by anzabanza** [comment]
@Tenns You need to put the file (CUE.NET_Test.exe) in the aurora directory then just run the aurora as normal. This script doesn't do anything by itself. Also could you post the log? I'm not a C++ dev but I still know some stuff about it and might be able to help.

**Comment by Tenns** [comment]
Even after puting the .exe in, and launching aurora, it still says not initialized. Here is the log: http://pastebin.com/ULR9HN2B

**Comment by DarthAffe** [comment]
what happens if you run the exe?

**Comment by Tenns** [comment]
@DarthAffe well it crashes but it says something http://imgur.com/a/g2Eu2 (sorry, it's in french)

**Comment by DarthAffe** [comment]
Ah, the Version of CUE.NET is quite old - the test-exe is using features from a newer version :(
I linked a new one that should be compatible with that version (github doesn't accept it as attachement ...)
[http://uploads.wyrez.org/CueNetTestOld.zip](http://uploads.wyrez.org/CueNetTestOld.zip)

**Comment by Tenns** [comment]
It's ok i found out why, CUE needs to be running whith a blank profile ...

**Comment by DarthAffe** [comment]
Oo this sounds like a bug in CUE then - i can't see any reason why you'd need to use a blank profile to access the SDK.

**Comment by brainbug89** [comment]
See https://github.com/antonpup/Aurora/issues/453#issuecomment-280123138 He didn't run CUE at all.

btw @Tenns you don't need a blank profile. Every profile works fine with SDK apps.
