### ISSUE TITLE
Minecraft support

### ISSUE THREAD

**Issue by Kalbi1** [antonpup/Aurora#334]
Whats about Minecraft? Its a Game everybody has, why not? For PVP I could be nice :D

**Comment by antonpup** [comment]
It's been a while since I've made a Minecraft mod. I can look into it, but I don't know if it will work very well.

**Comment by brainbug89** [comment]
Just use the Razer Minecraft mod with the Aurora Razer wrapper? (There is also a mod for Steelseries Gamesense.)

I don't know if Razer ChromaSync works with the Razer wrapper.

**Comment by santosch** [comment]
I would love this.
I think of displaying health, hunger, and perhaps the keyboard background color adapting to the current time of the day (fading from blue to bright yellow e.g.)

**Comment by AKBoy14** [comment]
that would be awesome, I tried to find a way to use the chromacraft mod with aurora but since my experience with code is nonexistent I got no luck

**Comment by diogotr7** [comment]
Support has been added with PR #1213
