### ISSUE TITLE
Ambilight uses entire desktop?

### ISSUE THREAD

**Issue by Sokonomi** [antonpup/Aurora#336]
Ambilight seems to use the entire desktop, so it looks a little off when im watching a movie in the middle screen with the rest turned off. Can a future update perhaps allow me to specify which area it should scan?

Telling it to stick to the specified application only would make it even better.

**Comment by antonpup** [comment]
Watch a movie in full screen? :P

I'll see what I can do.

**Comment by Sokonomi** [comment]
Its fullscreen on my center monitor. :P Cant watch movies with bezels in the way.
Everything else youve done is working wonderfully though! G910 bottom logo, hell yeah!

**Comment by antonpup** [comment]
Capturing foreground window:
![](https://puu.sh/tg6rl/306518adde.png)

Capturing specific process (in this case VLC):
![](https://puu.sh/tg6vL/e1fc134f09.png)

Also added capture for main monitor only.
