### ISSUE TITLE
Support for Cooler Master Masterkeys Pro L White & Masterkeys Pro M White

### ISSUE THREAD

**Issue by mm615657** [antonpup/Aurora#339]
FYI: I just tested the SDK provided by Cooler Master,they use the R(red) to determine the brightness of white LEDs

**Comment by mm615657** [comment]
And I don't know if it is a bug or not .Aurora can't detect my Masterkeys Pro L White,it writes Not Initialized at config page.
My keyboard LEDs can respond the Example provided by Cooler Master SDK,but not in Aurora

**Comment by antonpup** [comment]
@snichola Can you help?

Do you have 64 bit sdk installed? Aurora uses 64 bit.

**Comment by mm615657** [comment]
I'm working on it,will done soon

**Comment by simon-wh** [comment]
I believe they are working in any of the recent versions
