### ISSUE TITLE
Equalizer Effect

### ISSUE THREAD

**Issue by ItsYairo** [antonpup/Aurora#34]
Is it possible to have different kinds of equalizer effect that displays the audio via the LED's?

What I mean with "different kinds" is: 
![soundwave](https://cloud.githubusercontent.com/assets/19850486/16024682/777d4412-31c3-11e6-9c2a-caf322098a2a.jpg)

![xla6jn](https://cloud.githubusercontent.com/assets/19850486/16024686/7d680fa6-31c3-11e6-9936-87299872c2d4.gif)

Let us know what you think of this idea!

**Comment by antonpup** [comment]
It's possible to do. But it's on the back burner for now. As I think optimized wrappers, good user experience, and lots of game support takes more priority.

**Comment by antonpup** [comment]
As I have standardized the keyboard layouts, it should be easier to implement this. I will look into it for next version. Are there any specific styles you want for the equalizer? Or just those two listed.

**Comment by ItsYairo** [comment]
Yes!
![29b911ec0c725aa66d2d3db775fd9cbb](https://cloud.githubusercontent.com/assets/19850486/16350914/143a9b96-3a62-11e6-8823-95801f018a19.gif)

This one is also one I had in mind. Basically the other GIF but mirrored from the center. 

- What I had in mind for these two, is being able to set it to: vertical, horizontal and being able to select wich area you want it.
- Also I think it would be nice is being able to change the color of the levels. This is very similair to the volume feature.
- The Heartbeat-like effect has one solid color.

I hope these ideas are helpful!

**Comment by antonpup** [comment]
Equalizer won't make it into the upcoming version. I would like to see how people react to custom gradients and profiles.

But I will look into it for the version after.

**Comment by brainbug89** [comment]
Maybe this is usefull: https://github.com/AterialDawn/CUEAudioVisualizer (Visualizer for Corsair SDK)

**Comment by antonpup** [comment]
That will help. However, I would like to redesign the UI to allow for easier addition of these things to profiles. So, version 0.5.2 should have this and more.

**Comment by antonpup** [comment]
This upcoming version will have a general equalizer. I can include various styles and options. What would you envision the equalizer layer having in terms of options? @ItsYairo @brainbug89 

My main concern about this layer is whether or not the user can define custom keys or freeform region for this effect. Would this layer always just display a visualizer in the background, IE you cannot select which keys are defined for the equalizer. Or would this layer allow for key selection, and it would only display the equalizer within the selected keys/freeform region.

Also what kind of effects would you like? Here's a few that I could find and can implement:
![](http://i.dowload.vn/Data/image/2012/Thang11/12/Windows-Media-Player-11.jpg)
![](http://www.khimhoe.net/wp-content/uploads/2008/07/wmp11.jpg)
![](https://i.ytimg.com/vi/rKASqSlHksg/hqdefault.jpg)
![](http://2.bp.blogspot.com/-X4xb25AUDxA/VWsyuzv8TAI/AAAAAAAADyk/Sf3IN7c9biA/s1600/unnamed%252B%2525281%252529.png)
![](https://lh4.ggpht.com/1oPaMjEwfwrfaDlxo6cuP9o1UX2x6opgfHtOgVRzWSm_UGARx54NWmx8imz2rBTMkUI=h900)
![](http://burwenaudio.com/sitebuilder/images/BURWEN_OUTPUT-670x508.jpg)

**Comment by brainbug89** [comment]
At the moment I'm using [CEE](http://forum.corsair.com/v3/showthread.php?t=139027) from Elestriel with an effect like picture 4 (dub music player) but I would love something like picture 5, too. ;-)

**Comment by antonpup** [comment]
Equalizer layer will not be a part of the next version. I couldn't get it to a nicely functional state, so I don't want to include it.

**Comment by antonpup** [comment]
I am taking my previous statement back. Due to the technical difficulties with pushing an update, I have fixed up the Equalizer layer. It will be part of the next update.
