### ISSUE TITLE
Constant Upload

### ISSUE THREAD

**Issue by selmansavas** [antonpup/Aurora#342]
Aurora contantly uploading with 3-4kb/s, what is it for?

**Comment by antonpup** [comment]
That appears to be the AtmoOrb device. It's constantly trying to maintain Orb lights. I will see about fixing it.

Here's the definition of the IP address that you're probably seeing. https://github.com/antonpup/Aurora/blob/master/Project-Aurora/Devices/AtmoOrb/AtmoOrbDevice.cs#L110

Also note, Aurora's Wrappers and GSI implementations may also show up in the networking, as it's trying to communicate to other apps via IPC (for wrappers) or http requests (for GSI).

**Comment by selmansavas** [comment]
Thanks for fast reply, Great work with Aurora. Do you have a patreon or another type of tip method?

**Comment by antonpup** [comment]
There are options to donate at the [bottom of github project page](https://github.com/antonpup/Aurora#donations).
