### ISSUE TITLE
Percent Effect Layer missing options

### ISSUE THREAD

**Issue by TechnoPeter** [antonpup/Aurora#343]
As seen on the screenshot, there only is the option CPUUsage. Without some kind of "Max CPUUsage" Option, there is no way to show the usage of the CPU.
![screenshot_8](https://cloud.githubusercontent.com/assets/19509228/21777841/0038cdd0-d6a1-11e6-8562-03b41eb97528.png)

**Comment by antonpup** [comment]
Type 100 for max value.
