### ISSUE TITLE
Mouse Support

### ISSUE THREAD

**Issue by selmansavas** [antonpup/Aurora#347]
A minor issue, but before the last update, aurora could see and change colors of my logitech g502 mouse, but now i cant seem to find where to activate the mouse control, or only found the g900 one.

**Comment by antonpup** [comment]
G900 will work. (Technically any of them will work)

**Comment by LawAbidingEnt** [comment]
Thank you so much, just tried the g900 from the preferred mouse list (on 0.6.0b) and the lighting seems to be working properly.
