### ISSUE TITLE
Wrappers require admin permissions to load

### ISSUE THREAD

**Issue by antonpup** [antonpup/Aurora#35]
Users have reported that wrappers do not work unless the game is run as admin. This was not the case in the previous versions.

I need reports from users who are able to run the Overwatch wrapper. Do you run the game as Admin? What OS are you using? What RGB devices do you have?

**Comment by LukasACH** [comment]
I've patched Overwatch with the newest version of Aurora and the wrapper works perfectly. I tested it with running Overwatch.exe in the gamefolder with normal rights.
OS: Windows 10 Pro
Device: Logitech G910

**Comment by IrealiTY** [comment]
OS: Windows 10 Pro
Device: Logitech G910

Game and wrapper work normally without Admin mode
