### ISSUE TITLE
Cannot assign keys for "Dota 2 Respawn" lighting

### ISSUE THREAD

**Issue by 44shades44** [antonpup/Aurora#351]
"Assign Keys" button changes to "Stop Assign", but no assigning can occur. "Stop Assign" also does nothing.
Can remove and move up/down normally, just can't assign different keys (or re-assign once removed except by creating a new respawn layer).

Loving the program, thanks heaps for your work, keep it up! 👍 

Edit: Freestyle doesn't work either 😢

**Comment by antonpup** [comment]
Fixed. The issue will automatically close when it's released in a new update.
