### ISSUE TITLE
Running Game not detected

### ISSUE THREAD

**Issue by TechnoPeter** [antonpup/Aurora#352]
When setting up a profile for a specific game/program, Aurora doesn't seem to detect if its running or not. (Tested in Battlefield 1 and Garrys Mod)

**Comment by antonpup** [comment]
Switch the application detection method to Foreground App scan.
![](https://puu.sh/thGWU/0928bb8576.png)

**Comment by TechnoPeter** [comment]
Already tried, no difference. Switching the game to windowed mode didn't help either.

**Comment by antonpup** [comment]
Hm... could it be that you need to run Aurora as admin?

**Comment by TechnoPeter** [comment]
Just tried, no effect.

**Comment by TechnoPeter** [comment]
Well, it seems like the "Excluded Processes" Window was bugged. There was nothing in there, but I started spamming the "Remove Process" button and suddenly all of my last used programs appeared there. It seems to work now, weird.

**Comment by antonpup** [comment]
Ok. I'll look into it. Thanks.

**Comment by antonpup** [comment]
Yes, I can confirm that the list isn't being populated on launch. I will fix it. Thank you for the find.
