### ISSUE TITLE
Dota 2 shows Health/Mana when in menus.

### ISSUE THREAD

**Issue by cgr1988** [antonpup/Aurora#353]
Dota 2 Health/Mana information (always 100%) is being displayed when the game is in menus and spectating.

Before I updated to 0.6.0 Aurora would always display the background colour on the entire keyboard while in menus and only load the health/mana info when a game started.

![image1](https://cloud.githubusercontent.com/assets/25040993/21823793/99273ce2-d774-11e6-967f-5852f025dffb.JPG)

**Comment by antonpup** [comment]
It doesn't bother me. But a fix that can be done is to create a new Dota 2 Background layer, replace the Radiant and Dire team colors with a transparent color, and then place it above the HP/Mana layers.

![](https://puu.sh/thSfm/5c3e2020c8.png)

**Comment by cgr1988** [comment]
I'll do that! Thanks for the response! Really like this program. Keep up the good work!
