### ISSUE TITLE
Aurora beta v.0.6.0b not picking up razer chroma

### ISSUE THREAD

**Issue by secto15** [antonpup/Aurora#355]
program not detecting it please help, razer synapse shows enabled aurora

![aurora_2017-01-10_17-30-54](https://cloud.githubusercontent.com/assets/25043213/21827749/f7b1ef06-d75a-11e6-91b5-97ca86b76ff5.png)

**Comment by antonpup** [comment]
If you're talking about the mice, I didn't add any Razer mouse layouts. So, you can use any setting.

If you're talking about Keyboard not working, then I don't know.
