### ISSUE TITLE
Overwatch More Custom Support and CSGO Mouse Stutters

### ISSUE THREAD

**Issue by Running-Banana** [antonpup/Aurora#356]
For the overwatch I  think there should be more like customization cuz you cant really do anything outside of the defaults and also for CSGO I get major mouse stutters and its not that my comp/mouse is trash lol, whenever i quit aurora its fine,,,, please fix!!

**Comment by antonpup** [comment]
Overwatch does a decent job of LED illumination. There's nothing really to add.

As for CSGO, what processor are you using? A dual core?

**Comment by Running-Banana** [comment]
No but like for overwatch I wanna be able to customize it cuz like i dont
like how hanzos green looks and some other heroes and also its not my
computer because without Aurora no problems.. heres my specs anyways
https://pcpartpicker.com/list/4fPYm8

**Comment by antonpup** [comment]
Was the CSGO issue happening on the previous version?

**Comment by Running-Banana** [comment]
No Dx

**Comment by Running-Banana** [comment]
Oh and now my overwatch lighting wont work either..

**Comment by antonpup** [comment]
Make sure to repatch it with the new wrapper.

**Comment by Running-Banana** [comment]
Ok thanks but yeah the thing with csgo really needs to get fixed... i know
its not my computer also

**Comment by antonpup** [comment]
Can you please try the following version?

https://puu.sh/tibOZ/c0dcd5935c.zip

**Comment by Running-Banana** [comment]
Will do tomorrow!

**Comment by Running-Banana** [comment]
That fixed it!!!

**Comment by Running-Banana** [comment]
Well there feels like minimal stuttering but its a lot more playable but
that could just be me

**Comment by Running-Banana** [comment]
Well after some more playing it seems like the stuttering is still there
but its getting better... I guess playing against real players helps figure
it out XD
