### ISSUE TITLE
Is Philips Hue Support planned?

### ISSUE THREAD

**Issue by jomojomo95** [antonpup/Aurora#358]
If you don't know Philips Hue is the most popular LED smart/wireless lighting.
Including lightstrips, bulbs, whole lamps, ...
I have multiple hue lights around my gaming setup and think that a synchronization with Aurora would be really nice.
So my question is if any philips hue support is planned?

**Comment by antonpup** [comment]
I don't have any HUE lights, so no, I do not have HUE support planned. Others are free to make support for them and make a pull request.

**Comment by JoniSykes** [comment]
I intend to work on this. Part of the reason I was searching the interwebnet for any Chroma + GSI examples was to expand them to work with my Hue bulbs.
Before I do that though I'll be working on some game specific effects for Dota (hopefully).

**Comment by jomojomo95** [comment]
Cool, I would also like to work on a Hue integration. I only have to work myself into C # again, which I have not used for a long time. Maybe we can team up for this project.

**Comment by JoniSykes** [comment]
@jomojomo95 Sounds like a plan Batman. I'm learning C# for this too.
#blindleadingtheblind

**Comment by jomojomo95** [comment]
@JoniSykes Yea lets do our best ;D.[I forked the project. ](https://github.com/jomojomo95/Aurora/tree/dev) and added a [C# Hue API](https://github.com/Q42/Q42.HueApi) Most of the work is to understand the project structure. But I think its doable. For the start I would recomment to take a look at the [Hue dev doc](https://developers.meethue.com/) and the mentioned [Q42 API](https://github.com/Q42/Q42.HueApi).

> Let me get this straight. You think that your client, one of the wealthiest, most powerful men in the world, is secretly a vigilante who spends his nights beating criminals to a pulp with his bare hands; and your plan, is to blackmail this person? Good luck. -Lucius Fox

**Comment by JoniSykes** [comment]
Nice quote! Gotta love Morgan Freeman.
Well I'm still busy working on the Dota 2 Effects layer currently. I've spent a lot of time refactoring if/else blocks into dictionaries for performance. Now I have to actually create a whole bunch of effects. After that I'll be adding an Item Layer to complement the ability layer, creating item effects, then finally I will join you on the Hue API. Please do go ahead (obviously) without me for the time being. Good luck!

**Comment by rikkuness** [comment]
+1 Found this while looking for the same support, got a bunch of different Hue lights if you need me to pull and test build

**Comment by cadnce** [comment]
Hey, this sounds awesome. @jomojomo95 looking forward to seeing how you get on!

**Comment by jomojomo95** [comment]
@rikkuness 🙋 thanks, I just implemented the core Bridge connection mechanics, I will get back to you when I need a tester.

**Comment by Nitzowsky** [comment]
I can test if needed

**Comment by juleztb** [comment]
Anyone still working on this idea?
Just tried to integrate my Hue within Razer Synapse and this is just amazing.
Doesn't work with Aurora though. Therefore I sadly have to make the choice of leaving my Corsair Keyboard out or leaving the Hue lights out.

**Comment by simon-wh** [comment]
@juleztb I'm currently reworking the device layout system which will allow for devices outside of Keyboards + Mice, once I've got it setup I'll be adding support for this.

**Comment by jomojomo95** [comment]
@juleztb I stopped working on it as Philips announced the Entertainment setup. I didn't watched into is since then cause it was a pain to get it working in the current device environment. @simon-wh Im happy to help when you got the new layout system working.

**Comment by simon-wh** [comment]
@jomojomo95 Awesome! I'll hopefully have something functional soon.

**Comment by nmarrufo** [comment]
Yes!!! Hopeing on this soon. I saw that Razer Synapse was controlling my lights today during overwatch but was hoping i could have full control of it for all games and globally with Aurora!!! Thanks @simon-wh

**Comment by mastamike911** [comment]
LIFX, Hue, and all sorts of other lights and IoT devices could be integrated if Aurora hooked into Home Assistant. There is a local API that gets set up when you create a Home Assistant instance and you can access it both via [REST](https://home-assistant.io/developers/rest_api/) and [Web Sockets](https://home-assistant.io/developers/websocket_api/). Doing something like that would make Aurora SUPER powerful!

@simon-wh Feel free to hit me up if you want more info on Home Assistant. Been using it for my home for about a year now. I may be able to help you with integrating it too, if I ever have free time.

**Comment by simon-wh** [comment]
@mastamike911 Could you give me some examples of things you think Aurora could do with Home Assistant integration so I can get a better idea of what you're thinking of?

**Comment by mastamike911** [comment]
@simon-wh It would probably work similarly to how AtmoOrb works right now (though I admit I haven't used AtmoOrb), but instead it can find any light hooked up to Home Assistant and allow the user to control any of them.

I would think optimally, the interface would give you a dropdown/multi-select of Home Assistant lights to choose from, and then generate a section in Aurora layout for each of the lights chosen. You could then have any layer affect those devices.

**Comment by akswalia23** [comment]
Could you allow the Aurora chroma app to then control hue, nanoleaf and other razer integrated lights as I believe razer will be supporting many lights in the future

**Comment by fraannk** [comment]
As of right now, when having Hue lights paired with the Razer Synapse 3 software, and you open Aurora, the Hue lights just turn off. Are there any way to prevent this, and let the Razer app control it instead?

**Comment by kathampy** [comment]
The Hue Sync app breaks G-SYNC. Another reason to have Hue lights directly controlled via Game > Aurora rather than another screen sampler.

**Comment by Gurjot95** [comment]
Both nano leaf and philip hue are working with latest chroma link update to aurora.

**Comment by Gurjot95** [comment]
Afaik, you don't need chroma device to run synapse. Synapse is enough to detect your Hue device. Even if that is the case, there is chroma emulator available which you can install.

**Comment by DjRicko** [comment]
AtmoHue is in the works, which is a bridge between AtmoLight and Hue, should be possible to rip most of the code from there to change the AtmoOrb support to also work with Hue?
