### ISSUE TITLE
High Latency (Ping) @ Overwatch

### ISSUE THREAD

**Issue by wuwu37** [antonpup/Aurora#359]
I'm using Aurora for my Overwatch since last 2 months and it was working great until the last update. The latest update (beta v0.6.0b) causes my ping to go very high and literately unplayable. The high latency only occurs whenever there are lighting animation (Hero picking phase/ Ultimate charged & usage/ skill animation). If the lighting is static the latency will slowly reduce to normal rate, until the next animation it increases again.

Due to this I had temporary deleted the .dll files in the Overwatch folder to allow me to play the game probably. I'm currently using Corsair Strafe RGB with Corsair M65 RGB.

**Comment by kasyx09** [comment]
Intesting. I have a higher latency too but I haven`t connected it with Aurora. I have to take a look a that also. DOOMFIST SOOOOOON :D

**Comment by antonpup** [comment]
I don't know what to say. Since the previous stable version, I only optimized the wrappers. So, I don't see how they can be causing you higher ping. The functionality wasn't changed either.

Is this with the new wrapper from 0.6.0 applied? Can you confirm that running 0.5.2 with its wrapper does not increase the ping?

**Comment by snichola** [comment]
For my own curiosity as well could you try running Overwatch in administrator mode and report back?

**Comment by kasyx09** [comment]
Wait with that. I`ve read that there is new hack called Nuking in Overwatch. It causes high latency in opponents team... I had lags yesterday but when I turn off Aurora and came back to the game, my ping was still high.

**Comment by antonpup** [comment]
I don't think that Aurora is responsible for network lag. I will admit that Aurora can cause fps drops on mid-low end machines. But I always work on improving performance.
