### ISSUE TITLE
Logitech G810 top lights not work...

### ISSUE THREAD

**Issue by midtowntr** [antonpup/Aurora#364]
I'm using Logitech G810...
In Aurora, we can't apply any effect to CapsLock, ScrollLock lights and also "Gaming Mode", "Light", "Mute", "Play/Pause", "Stop", "Prev Track", "Next Tract" buttons, in short term, the lights on top...
Thanks for this beautiful work...

**Comment by antonpup** [comment]
Those lights are not part of the LED SDK. So... Nothing I can do about that.
