### ISSUE TITLE
Aurora Problem

### ISSUE THREAD

**Issue by iFaaazT** [antonpup/Aurora#365]
Hello ! I already installed everything , but When I try to launch Aurora , Nothing.
In the Task Manager I can see Aurora , I already try to change compatibility.

**Comment by antonpup** [comment]
Do you already have Aurora running? Check the tray.

If not, send over your logs.

**Comment by iFaaazT** [comment]
Yes , I'm sure when I try to launch again he saying already running`

========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: DESKTOP-LBT68HF
User Name: ipod6
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

12/01/2017 13:43:42: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_py_script.py. Exception: System.Exception: Provided script, does not meet all the requirements
   à Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:ligne 32
   à CallSite.Target(Closure , CallSite , Type , Object )
   à System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   à Aurora.Devices.DeviceManager..ctor() dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:ligne 57
12/01/2017 13:43:42: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_script.cs. Exception: System.Exception: Provided script, does not meet all the requirements
   à Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:ligne 32
   à CallSite.Target(Closure , CallSite , Type , Object )
   à System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   à Aurora.Devices.DeviceManager..ctor() dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:ligne 71
[INFO] 12/01/2017 13:43:42: Loading Configuration
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: DESKTOP-LBT68HF
User Name: ipod6
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

12/01/2017 13:45:25: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_py_script.py. Exception: System.Exception: Provided script, does not meet all the requirements
   à Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:ligne 32
   à CallSite.Target(Closure , CallSite , Type , Object )
   à System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   à Aurora.Devices.DeviceManager..ctor() dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:ligne 57
12/01/2017 13:45:25: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_script.cs. Exception: System.Exception: Provided script, does not meet all the requirements
   à Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:ligne 32
   à CallSite.Target(Closure , CallSite , Type , Object )
   à System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   à Aurora.Devices.DeviceManager..ctor() dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:ligne 71
[INFO] 12/01/2017 13:45:25: Loading Configuration
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: DESKTOP-LBT68HF
User Name: ipod6
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

[ERROR] 12/01/2017 13:52:53: Aurora is already running.
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: DESKTOP-LBT68HF
User Name: ipod6
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

[ERROR] 12/01/2017 13:53:03: Aurora is already running.
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: DESKTOP-LBT68HF
User Name: ipod6
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

[ERROR] 12/01/2017 13:53:06: Aurora is already running.
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: DESKTOP-LBT68HF
User Name: ipod6
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

12/01/2017 13:53:23: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_py_script.py. Exception: System.Exception: Provided script, does not meet all the requirements
   à Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:ligne 32
   à CallSite.Target(Closure , CallSite , Type , Object )
   à System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   à Aurora.Devices.DeviceManager..ctor() dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:ligne 57
12/01/2017 13:53:24: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_script.cs. Exception: System.Exception: Provided script, does not meet all the requirements
   à Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:ligne 32
   à CallSite.Target(Closure , CallSite , Type , Object )
   à System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   à Aurora.Devices.DeviceManager..ctor() dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:ligne 71
[INFO] 12/01/2017 13:53:24: Loading Configuration
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: DESKTOP-LBT68HF
User Name: ipod6
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

[ERROR] 12/01/2017 13:54:26: Aurora is already running.
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: DESKTOP-LBT68HF
User Name: ipod6
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

[ERROR] 12/01/2017 13:54:39: Aurora is already running.
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: DESKTOP-LBT68HF
User Name: ipod6
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

[ERROR] 12/01/2017 13:54:58: Aurora is already running.
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: DESKTOP-LBT68HF
User Name: ipod6
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

12/01/2017 13:55:08: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_py_script.py. Exception: System.Exception: Provided script, does not meet all the requirements
   à Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:ligne 32
   à CallSite.Target(Closure , CallSite , Type , Object )
   à System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   à Aurora.Devices.DeviceManager..ctor() dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:ligne 57
12/01/2017 13:55:09: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_script.cs. Exception: System.Exception: Provided script, does not meet all the requirements
   à Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:ligne 32
   à CallSite.Target(Closure , CallSite , Type , Object )
   à System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   à Aurora.Devices.DeviceManager..ctor() dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:ligne 71
[INFO] 12/01/2017 13:55:09: Loading Configuration
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: DESKTOP-LBT68HF
User Name: ipod6
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

12/01/2017 14:04:10: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_py_script.py. Exception: System.Exception: Provided script, does not meet all the requirements
   à Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:ligne 32
   à CallSite.Target(Closure , CallSite , Type , Object )
   à System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   à Aurora.Devices.DeviceManager..ctor() dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:ligne 57
12/01/2017 14:04:12: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_script.cs. Exception: System.Exception: Provided script, does not meet all the requirements
   à Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:ligne 32
   à CallSite.Target(Closure , CallSite , Type , Object )
   à System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   à Aurora.Devices.DeviceManager..ctor() dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:ligne 71
[INFO] 12/01/2017 14:04:12: Loading Configuration
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: DESKTOP-LBT68HF
User Name: ipod6
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

[ERROR] 12/01/2017 16:08:20: Aurora is already running.
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: DESKTOP-LBT68HF
User Name: ipod6
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

12/01/2017 16:08:36: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_py_script.py. Exception: System.Exception: Provided script, does not meet all the requirements
   à Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:ligne 32
   à CallSite.Target(Closure , CallSite , Type , Object )
   à System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   à Aurora.Devices.DeviceManager..ctor() dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:ligne 57
12/01/2017 16:08:38: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_script.cs. Exception: System.Exception: Provided script, does not meet all the requirements
   à Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:ligne 32
   à CallSite.Target(Closure , CallSite , Type , Object )
   à System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   à Aurora.Devices.DeviceManager..ctor() dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:ligne 71
[INFO] 12/01/2017 16:08:38: Loading Configuration
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: DESKTOP-LBT68HF
User Name: ipod6
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

[ERROR] 12/01/2017 22:12:19: Aurora is already running.
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: DESKTOP-LBT68HF
User Name: ipod6
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

12/01/2017 22:12:46: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_py_script.py. Exception: System.Exception: Provided script, does not meet all the requirements
   à Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:ligne 32
   à CallSite.Target(Closure , CallSite , Type , Object )
   à System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   à Aurora.Devices.DeviceManager..ctor() dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:ligne 57
12/01/2017 22:12:48: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_script.cs. Exception: System.Exception: Provided script, does not meet all the requirements
   à Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:ligne 32
   à CallSite.Target(Closure , CallSite , Type , Object )
   à System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   à Aurora.Devices.DeviceManager..ctor() dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:ligne 71
[INFO] 12/01/2017 22:12:48: Loading Configuration
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: DESKTOP-LBT68HF
User Name: ipod6
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

[ERROR] 12/01/2017 22:13:25: Aurora is already running.

**Comment by iFaaazT** [comment]
Yes , I'm sure when I try to launch again he saying already running
[ERROR] 12/01/2017 22:12:19: Aurora is already running.
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: DESKTOP-LBT68HF
User Name: ipod6
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

12/01/2017 22:12:46: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_py_script.py. Exception: System.Exception: Provided script, does not meet all the requirements
   à Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:ligne 32
   à CallSite.Target(Closure , CallSite , Type , Object )
   à System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   à Aurora.Devices.DeviceManager..ctor() dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:ligne 57
12/01/2017 22:12:48: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_script.cs. Exception: System.Exception: Provided script, does not meet all the requirements
   à Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:ligne 32
   à CallSite.Target(Closure , CallSite , Type , Object )
   à System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   à Aurora.Devices.DeviceManager..ctor() dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:ligne 71
[INFO] 12/01/2017 22:12:48: Loading Configuration
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: DESKTOP-LBT68HF
User Name: ipod6
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

[ERROR] 12/01/2017 22:13:25: Aurora is already running.

**Comment by iFaaazT** [comment]
[ERROR] 12/01/2017 22:12:19: Aurora is already running.

### Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: DESKTOP-LBT68HF
User Name: ipod6
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

12/01/2017 22:12:46: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_py_script.py. Exception: System.Exception: Provided script, does not meet all the requirements
   à Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:ligne 32
   à CallSite.Target(Closure , CallSite , Type , Object )
   à System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   à Aurora.Devices.DeviceManager..ctor() dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:ligne 57
12/01/2017 22:12:48: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_script.cs. Exception: System.Exception: Provided script, does not meet all the requirements
   à Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:ligne 32
   à CallSite.Target(Closure , CallSite , Type , Object )
   à System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   à Aurora.Devices.DeviceManager..ctor() dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:ligne 71
[INFO] 12/01/2017 22:12:48: Loading Configuration
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: DESKTOP-LBT68HF
User Name: ipod6
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

[ERROR] 12/01/2017 22:13:25: Aurora is already running.

**Comment by iFaaazT** [comment]
Yes , I'm sure , because Aurora was working because I close it

Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: DESKTOP-LBT68HF
User Name: ipod6
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

12/01/2017 22:12:46: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_py_script.py. Exception: System.Exception: Provided script, does not meet all the requirements
   à Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:ligne 32
   à CallSite.Target(Closure , CallSite , Type , Object )
   à System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   à Aurora.Devices.DeviceManager..ctor() dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:ligne 57
12/01/2017 22:12:48: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_script.cs. Exception: System.Exception: Provided script, does not meet all the requirements
   à Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:ligne 32
   à CallSite.Target(Closure , CallSite , Type , Object )
   à System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   à Aurora.Devices.DeviceManager..ctor() dans D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:ligne 71
[INFO] 12/01/2017 22:12:48: Loading Configuration
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: DESKTOP-LBT68HF
User Name: ipod6
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

[ERROR] 12/01/2017 22:13:25: Aurora is already running.

**Comment by antonpup** [comment]
So, just to be clear. You never actually saw the Aurora window?

From the logs it seems that you're stuck on loading configurations.

Have you used a previous version of Aurora?

**Comment by iFaaazT** [comment]
I saw it one time , I have exit Aurora to restart my pc , after the restart , I dont saw Aurora anymore.

**Comment by antonpup** [comment]
Ok, try this. Delete the folder `C:\Users\*username*\AppData\Roaming\Aurora`. It will delete all configurations for Aurora, and hopefully make you launch.

**Comment by iFaaazT** [comment]
thank its working !

**Comment by iFaaazT** [comment]
Thanks Its working !
