### ISSUE TITLE
G910 can't get any lights to work with League of Legends

### ISSUE THREAD

**Issue by Stoneator** [antonpup/Aurora#366]
I've read a bunch of issues on this page and done lots of research but I can't seem to get anything to work with League. I've done the patching thing into the correct folder and I've also enabled the LightFX in the league config file but I don't really know what to do now.

I can get other lighting for supported games such as CS:GO to work etc but I can't figure out what I need to do to get League working

**Comment by antonpup** [comment]
Have you tried it in-game? The lights should work.

**Comment by Stoneator** [comment]
yeah I went in game and nothing changed

**Comment by Stoneator** [comment]
Is it really that simple? you change LightFX to 1 in the config, and you do the patch file thing? and it should work?

**Comment by antonpup** [comment]
You probably installed LightFX into the wrong folder. If not, try running League as admin?

**Comment by Stoneator** [comment]
ah yes, I had 2 league of legends folders for some reason and I had it downloaded into the wrong one, thanks :)
