### ISSUE TITLE
Help with new profile

### ISSUE THREAD

**Issue by s3cas** [antonpup/Aurora#369]
Hi guys,

Someone can help me create a profile for make a equaliser wave only when I start listing music with specific program? Like Media Player for Ex.

Thanks,

Cheers.

**Comment by antonpup** [comment]
In the future, you will be able to set layer's visibility based on various user-defined logic steps. So, in your case, if "itunes.exe" or "vlc.exe" is running. There is no way to isolate audio from a specific program, so it will always use entire system audio.

**Comment by s3cas** [comment]
So you are tell me if i create a layer for some specific program will work but if i get another sound from a external program like youtube meanwhile i listing music will be a mess wave sound because they will mix music from youtube with a program that i choose?

**Comment by antonpup** [comment]
In simple terms. Equalizer layer will always examine entire system sound. You will be able to turn the layer automatically on/off if a specific process is running.

**Comment by s3cas** [comment]
So can you help me to make this turn on/off to a specific process?

**Comment by antonpup** [comment]
It will be a feature in a later version.

**Comment by s3cas** [comment]
So for now I only can go at Aurora and check the box to turn on/off
