### ISSUE TITLE
Razer Chroma Apps for Logitech, possible?

### ISSUE THREAD

**Issue by IrealiTY** [antonpup/Aurora#37]
On the [razer chroma page](http://www.razerzone.com/chroma-workshop/#chroma-apps) are a few interesting apps listed. Is it possible to wrap them for Aurara to be used on Logitech Devices?

Tried 1-2 and no result.

**Comment by antonpup** [comment]
Looking into it. Some of them seem to completely ignore the dlls.

**Comment by antonpup** [comment]
Looked at Razer demos and how they interact with the SDK. And apparently my Razer Wrapper functions incorrectly. So I am going to take time later to rewrite the wrapper to function as close to the original Razer SDK as possible. It shouldn't be difficult, I've done it for Logitech already. Just time consuming and tedious.

This however, will not change the fact that some operating systems (mainly Windows 8 and below) require these wrappers to be run as admin. I am guessing for security reasons.

**Comment by Langhii** [comment]
Are there any new first beginnings for the razer app support?

**Comment by antonpup** [comment]
Not yet. I am investigating why wrappers don't work sometimes, and then I will rewrite Razer one.

**Comment by antonpup** [comment]
Will be looking into this today/tomorrow.

**Comment by antonpup** [comment]
Did it today. For the most part chroma apps work. Will do some minor tweaks and they should work next version.

**Comment by antonpup** [comment]
Here's a small video demonstration with a few Chroma SDK apps.

[![Chroma SDK app support Demo](http://img.youtube.com/vi/v6P9srU8IWE/0.jpg)](https://www.youtube.com/watch?v=v6P9srU8IWE)
