### ISSUE TITLE
My Razer Black widow chroma isn't initialized [enabled Chroma apps]

### ISSUE THREAD

**Issue by Nerfingtons** [antonpup/Aurora#370]
I have completed the first time instructions for my razer bw chroma and it still says it's not initialized any help appreciated.

**Comment by antonpup** [comment]
Do other Chroma SDK apps work? Try disabling and re-enabling Chroma apps?

**Comment by Nerfingtons** [comment]
nope its enabled but the razer sdk service isnt running

**Comment by Nerfingtons** [comment]
thats what gamedog said anyway

**Comment by antonpup** [comment]
Well.. if Razer SDK service isn't running.. then you can either try restarting the service or reinstall Synapse. (From quick googling around, both are suggested solutions)

**Comment by Nerfingtons** [comment]
ok willl try it now

**Comment by YielShelion** [comment]
Also have this issue on new PC, solved by uninstalling, reinstalling and restarting the pc after install.

**Comment by antonpup** [comment]
@YielShelion Reinstalling Razer Synapse? or Aurora?

**Comment by antonpup** [comment]
Any update on this?

**Comment by YielShelion** [comment]
@antonpup Razer synapse. This problem occur when razer is connected to windows 10 on which windows 10 automatically finds and install driver and razer synapse, which also broke the API.
Updating the synapse downloaded by the OS won't fix it, uninstall and manual redownload fix this problem.

**Comment by YielShelion** [comment]
I'm not sure if this relevant to this issue though.
