### ISSUE TITLE
Interactive effects not working

### ISSUE THREAD

**Issue by DeathAngel** [antonpup/Aurora#371]
interactive effects arent working in any profile except desktop

**Comment by antonpup** [comment]
Works fine here...

![](https://puu.sh/tkehU/88d95fb7ed.gif)

**Comment by DeathAngel** [comment]
yea if u have the window opened it works but once u start the game it doesnt anymore for some reason

**Comment by antonpup** [comment]
Just launched dota 2. Worked fine.

**Comment by DeathAngel** [comment]
strange... i tried gta 5 and bns and neither worked

**Comment by antonpup** [comment]
Same games could be taking full control of the keyboard. Not usual to see with games.
