### ISSUE TITLE
Ambilight doesnt like my setup?

### ISSUE THREAD

**Issue by Sokonomi** [antonpup/Aurora#373]
Theres been a ton of work regarding this new feature recently and I love that its getting so much attention. HOWEVER... It doesn't seem to like my configuration very much sofar. :') It just keeps screwing up for some reason.

Ive made a new profile for my favorite videoplayer (daums potplayer), to run ambilight during movies and such, but it keeps behaving weirdly, even with the new specific capture types.

**Everything**
Does what it says on the tin. Unfortunately for me, this adds about 50% more screen estate than my movies take up.

**Main monitor only**
This seems to act a little odd. The right half of my keyboard seems to be part of my main screen activity, but the left half seems to be assigned to the upper half of my left panel. (like its looking at the 3440x1440 framesize of my main monitor, but its 0,0 location starts on the wrong screen)

**Foreground application**
Seems to do exactly the same thing as main monitor only.

**Process specific**
Acts weird, cant get it to do anything.

To be fair though, my desktop isnt exactly conventional; http://i.imgur.com/0BUTMEG.jpg
There's my 3440x1440 main screen in the middle, plus two 1080p portraitmode sidepanels.

Perhaps its a good idea to make ambilight go by a user settable pixel zone?
To get my main screen 'in the shot' it would be ; w3440 h1440 x1080 y0

**Comment by antonpup** [comment]
I'll try to get ahold of a second monitor to test with.
