### ISSUE TITLE
League Of Legends Not Patching

### ISSUE THREAD

**Issue by 56curiious** [antonpup/Aurora#375]
Hello, so I have clicked the patch, navigated to the correct directory and I still don't get anything in-game other than a black keyboard. If I press a key, it will flicker a colour. I checked recently edited files inside of the LoL file and it showed thatr at the time, it had edited them correctly. It keeps telling me to patch, even after restarts etc.

**Comment by antonpup** [comment]
Are you sure you installed in the right directory? It works, take a look at #366 .

Also worth checking if you have [Visual C++ Redistributable Packages for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145) installed. You need both of x86 and x64.

**Comment by 56curiious** [comment]
Hello, I'll attach a photo to show you the directory. [http://imgur.com/a/Zb2PA](url)

**Comment by antonpup** [comment]
Try running League as admin? I haven't tested League on Windows 7, so I can't tell you what's broken with it. But I can tell you that Windows 7 has some weird restrictions.

**Comment by 56curiious** [comment]
Hello, so I ran League and aurora as admin and still get the issue. I turne my PC on today to see the same screen as before, [https://postimg.org/image/qabishrxl/b085e2a3/](url). It seems to detect it works, because the keyboard goes black, it just doesn't go from there.

**Comment by antonpup** [comment]
It goes black because Aurora detects the exe being in the foreground. But League isn't actually sending any information over (Thus it's just black). Make sure that you are applying the patch to the proper directory.

I just ran LoL and lighting was working fine (even updated to their new beta client).

I also had option in-game to enable AlienFX, which did turn on/off lighting with Aurora as expected.
![](https://puu.sh/toBdE/20522f7562.png)

**Comment by antonpup** [comment]
Screenshot of my League directory
![](https://puu.sh/toBnF/56bd97f6fb.png)

**Comment by antonpup** [comment]
Any update on this?

**Comment by 30wolf03** [comment]
Hi. This should be explained in the aurora app, that after patching you have to run League as admin and then turn on the AlienFX option in game and then in the next game it will work. 

I had to do some research to come to the idea to google for AlienFx as this word is not mentioned in the app. 

And after all this the LoL game integration is rather sad. It just blinks when low hp with no customization options. Which i am sure you can't do anything about as long as Riot doesn't provide more support i guess.

Also, thanks for all your work, i love you.

**Comment by 56curiious** [comment]
Hello, so I followed what 30Wolf03 said and it now worked. However, I had no clue or direction after file patching, not even a confirmation. As some feedback, it would be cool to have confirmation and then further direction after, i.e running as admin and enabling in game. It is however, all working so thank you to the both of you :3 👍
