### ISSUE TITLE
Aurora dont affect LED 

### ISSUE THREAD

**Issue by iFaaazT** [antonpup/Aurora#376]
After making all requirement , selecting my keyboard G910 , LED are not affected , nothing happen when I chose scripts or another , Aurora dont show led of the keyboard , Aurora Saying Logitech : Connected

**Comment by antonpup** [comment]
Make sure that SDK is enabled in LGS.

**Comment by iFaaazT** [comment]
Where can I check that ?

**Comment by iFaaazT** [comment]
Where can I check that ?

**Comment by iFaaazT** [comment]
Where can I check that ?

**Comment by antonpup** [comment]
"Allow games to control illumination"
![](https://puu.sh/tpAkh/595cdcaeea.png)

**Comment by antonpup** [comment]
Any update on this?
