### ISSUE TITLE
Razer's new Ornata keyboard isn't yet supported.

### ISSUE THREAD

**Issue by JoniSykes** [antonpup/Aurora#377]
Less of an issue, more of a request.
I imagine it's extremely similar to the Widow.

**Comment by JoniSykes** [comment]
The interactive effects don;t seem to be working on the ornata.

**Comment by antonpup** [comment]
Interactive effects aren't "restricted to devices". They either work, or they don't. Make sure you have GSI installed and what not. And make sure that the device itself works properly with Aurora.

**Comment by JoniSykes** [comment]
GSI is good according to the app. It says the config is installed and I can see it in the correct folder.
Should hero effects show in the preview section of dota? I can only see HP, Mana and Killstreak.
Any suggestions on what else to try?

**Comment by JoniSykes** [comment]
Should the key mappings for hero ability effects be empty in the json dota profile?
```
      {
        "$type": "Aurora.Settings.Layers.Layer, Aurora",
        "Name": "Dota 2 Hero Ability Effects",
        "Handler": {
          "$type": "Aurora.Profiles.Dota_2.Layers.Dota2HeroAbiltiyEffectsLayerHandler, Aurora",
          "Properties": {
            "$type": "Aurora.Profiles.Dota_2.Layers.Dota2HeroAbiltiyEffectsLayerHandlerProperties, Aurora",
            "_SecondaryColor": "189, 62, 48",
            "_PrimaryColor": "43, 140, 103",
            "_Sequence": {
              "$type": "Aurora.Settings.KeySequence, Aurora",
              "keys": {
                "$type": "System.Collections.Generic.List`1[[Aurora.Devices.DeviceKeys, Aurora]], mscorlib",
                "$values": []
              },
              "type": 0,
              "freeform": {
                "$type": "Aurora.Settings.FreeFormObject, Aurora",
                "Type": 1,
                "X": 0.0,
                "Y": 0.0,
                "Width": 30.0,
                "Height": 30.0,
                "Angle": 0.0
              }
            }
          }
        },
        "Enabled": true,
        "Type": 0,
        "Logics": {
          "$type": "System.Collections.ObjectModel.ObservableCollection`1[[Aurora.Settings.Layers.LogicItem, Aurora]], System",
          "$values": []
        },
        "LogicPass": true
      }
```

**Comment by antonpup** [comment]
Yes, it draws directly to the layer graphics. Setting keys for it is pointless.

**Comment by JoniSykes** [comment]
So if I'm on the preview screen, I can see hp and mana working. In game they stay full.
I will do more testing tomorrow, but it's bed time now.
Thanks for the help today.

**Comment by JoniSykes** [comment]
Happy to close this now. 
I think a series of re-installs of various things have resolved any issues I had previously.
My Ornata works fine.
