### ISSUE TITLE
Logitech G933 battery

### ISSUE THREAD

**Issue by holrits** [antonpup/Aurora#379]
Hi!

is it possible to make a battery indicator of the wireless headset G933, directly on the keyboard?

Regards Nicolai

**Comment by antonpup** [comment]
It's a neat idea, but I don't have a way of detecting headset's current battery charge.

**Comment by Legonzaur** [comment]
I wanted to do the same as @holrits, so I did some researches and I found [this repo](https://github.com/Sapd/HeadsetControl/blob/master/src/devices/logitech_g633_g933_935.c), from line 48 to line 86. 
It's kind of a hacky way.
I'll try to find more information about that.

You did an amazing work by with aurora btw

**Comment by Legonzaur** [comment]
Did [this script](https://cdn.discordapp.com/attachments/507595494915309578/700738376403386478/G933_Aurora_script_V1.0.zip) which uses [this program](https://github.com/Sapd/HeadsetControl) which allows users to show the battery of the G933 on their keyboard.

**Comment by adaswrew2** [comment]
> Just did [this script](https://cdn.discordapp.com/attachments/507595494915309578/701419737707577414/G933.cs) which allows users to show the battery of the G933 on their keyboard.

HI can you write how to use this script ? thanks :D
