### ISSUE TITLE
The Division for Corsair Straife

### ISSUE THREAD

**Issue by NursePinkamena** [antonpup/Aurora#382]
I install the Logitech patch, when I get into the Division the option to enable LED support is still grayed out.

**Comment by antonpup** [comment]
Make sure you have [Visual C++ Redistributable Packages for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145) installed. If not, then run both Aurora and Division as admin.

**Comment by NursePinkamena** [comment]
Tried both of those and even reinstalled the game and it will not work still.

**Comment by antonpup** [comment]
I'll test it tomorrow.

**Comment by antonpup** [comment]
I remember people had issues with other Logitech games, and said that installing LGS and then patching fixed it for them.

**Comment by NursePinkamena** [comment]
Installed LGS and installed patch again and ran aurora and division as admin I get the option to enable the keyboard support, but when I enable it and get in game my keyboard and mouse do not light up at all.

**Comment by antonpup** [comment]
Good. We are both on the same page. I just launched the division and experienced the same behavior (entire kb black), as well as a pile of errors.

I will be fixing that up now. Thank you for your report.
