### ISSUE TITLE
Support for Overwatch in Coolermaster Keys L

### ISSUE THREAD

**Issue by jmautari** [antonpup/Aurora#383]
Hi, big thanks to all people involved in this project!

A friend of mine has a Coolermaster Keys L keyboard and was excited to finally see some RGB action on his Coolermaster Keys L keyboard when playing Overwatch. Sadly only a few keys get highlighted like the attached picture (he picked Soldier 76)

![photo_2017-01-16_11-12-34](https://cloud.githubusercontent.com/assets/5205328/21984367/b1d10216-dbdc-11e6-8690-a17538b3505e.jpg)

He couldn't find any logs. He's using latest Coolermaster SDK on Windows 10.

**Comment by antonpup** [comment]
It's a very dim blue. You can see it on the picture. Anyways, it's fixed in the next version.

**Comment by jmautari** [comment]
Thanks!!
