### ISSUE TITLE
Support for Star Citzen

### ISSUE THREAD

**Issue by r4ptus** [antonpup/Aurora#384]
Are u planning to support Star Citizen in the near future?
so that the colors are changing if u sit in a spaccraft or when u are on ur feet?

**Comment by JoniSykes** [comment]
@r4ptus This isn't really an issue, but a feature request.
Perhaps @antonpup Can provide a better way of request features to avoid issues getting spammed?

**Comment by antonpup** [comment]
Duplicate of #190
