### ISSUE TITLE
Using of ALTGR

### ISSUE THREAD

**Issue by r4ptus** [antonpup/Aurora#385]
is there a way to use altgr as a key itself without that all the buttons light up when u press ctrl ? 
for example if i press altgr j,k,l turn red but when i press ctrl nothing happens.
atm ctrl and altgr trigger the butoons to turn red

**Comment by brainbug89** [comment]
> without that all the buttons light up when u press ctrl 
> but when i press ctrl nothing happens

Sorry but I don't understand your problem. Do you need help with the Shortcut layer?

**Comment by r4ptus** [comment]
on a german layout there is a key altgr instead of ur right alt which trigger some special keys on our keyboard u can activate it with alt + ctrl too 
sry for makin it unclear
im askin for an aditional short cut for seperat left alt and right alt
hope this clear things up

**Comment by gradius-v** [comment]
I second that request !

**Comment by antonpup** [comment]
ALTGr is treated in Windows as a rapid press of both CTRL and ALT. That is why you are seeing the flickering. I will see if I can fix it when I rework the Shortcut Assistant layer.

**Comment by brainbug89** [comment]
Okay so the same problem like #145
