### ISSUE TITLE
Memory leak in v0.6.0b?

### ISSUE THREAD

**Issue by MadScientist69** [antonpup/Aurora#387]
With the latest version of Aurora I startet getting following issue.
After leaving my PC idle running for a while Aurora suddenly consumes most of my memory.

It ends up using 12 GB. (out of 16) ram, and I can barely start task manager to kill the Aurora process.
This issue started happening with version 0.6.0b, older versions worked with without any issues.

I am running it on windows 10 64 bit with the logitech g910 keyboard.

**Comment by antonpup** [comment]
Strange... I'll look into it.

How long does it take to ramp up like that? Perhaps your logs are getting spammed with errors?

**Comment by MadScientist69** [comment]
It's difficult to say when it happens but it's around after 24 hours. Which logs do you mean?

**Comment by antonpup** [comment]
In the execution directory, there should be a folder called "logs".

Also did you install through the Web installer? (If so, you may not find the logs folder)

**Comment by antonpup** [comment]
What kind of layers are you running as well?

**Comment by MadScientist69** [comment]
I just use the default once and following for default desktop: http://modworkshop.net/mydownloads.php?action=view_down&did=17402
Found some huge log files in the mentioned log directory.

This is the latest log file compressed: (uncompressed size is 759 mb.)
[2017_12_01.log.gz](https://github.com/antonpup/Aurora/files/709612/2017_12_01.log.gz)

**Comment by antonpup** [comment]
Well.. first issue is, your performance counters need to be rebuilt. Run following command in command prompt two times: `lodctr /R`

After that, the latest log file should no longer show those errors. (And won't be huge). So do that, and then run Aurora again for a period of time and get back to me if this fixed your issue.

I've been running Aurora for the past 28 minutes or so, with ambilight, and equalizer (with smoothing). And it's been regulating RAM at around 200 MB. I'll break my performance counters and see if I get a leak.

**Comment by MadScientist69** [comment]
I ran the command twice as you specified with following result:
C:\Windows\system32>lodctr /R

Error: Unable to rebuild performance counter setting from system backup store, error code is 2
C:\Windows\system32>lodctr /R

Info: Successfully rebuilt performance counter setting from system backup store

I will leave it running again and see if the issues appear.

Thanks for your help so far!

**Comment by antonpup** [comment]
Any updates on this issue?

**Comment by MadScientist69** [comment]
Nope, the command you mentioned seems to have resolved it.
Aurora ran since then and uses around 100 - 150 mb. ram, and there are no new log files.
