### ISSUE TITLE
Unpatching Overwatch

### ISSUE THREAD

**Issue by baybolin12** [antonpup/Aurora#388]
Thinking of finally daring to patch overwatch. Can I unpatch it somehow? Do I need to reinstall the whole game?

**Comment by Paradyse19** [comment]
you Should be able to just delete the Razer files out of the Overwatch folder that would remove the Patch

**Comment by baybolin12** [comment]
I do not know the exact names of the files. Also, are there no edited files? Just additions?

**Comment by Paradyse19** [comment]
Yes just additions.
names are: RazerChromaSDK.dll and RazerChromaSDK64.dll

**Comment by baybolin12** [comment]
Thanks.
