### ISSUE TITLE
Activate Effects only on choosen buttons

### ISSUE THREAD

**Issue by Paradyse19** [antonpup/Aurora#389]
Hey there first of great work with the Aurora mod i really like it.

1 Thing i would like tho would be the configuration to Activate the interactive layer only on Specific buttons.

For example only pressing R or Space will activate the Rainbow effect not  every button.

kind Regards

**Comment by antonpup** [comment]
It's already part of the dev build. Except instead of selecting which keys have the effect, you select which keys DO NOT trigger the effect.
