### ISSUE TITLE
Logitech G810 & Overwatch

### ISSUE THREAD

**Issue by mysterryous** [antonpup/Aurora#39]
I've seen you mention in a few other posts that Overwatch controls the lighting on the keyboard but I've noticed with my G810 that Reinhardt, Bastion, Soldier 76, and Reaper have no sustained backlight coloring, while their action keys light up & the ripple effect appears briefly when selecting them. And strangely, Reaper's ripple effect seems to rapidly degrade and not finish rippling outward.

Additionally, McCree, Widowmaker, Torbjorn, and Roadhog all appear dark to barely existent.

I was wondering if there's any chance, similar to the option to enable color enhancing for Logitech devices, that those color patterns could somehow be enhanced or brightened up when Overwatch has started?

P.S. Extreme gratitude for Aurora, this has completely changed the experience with my keyboard. A+

**Comment by antonpup** [comment]
I am reworking the "Color Enhancing" for Logitech devices. It should now only trigger when a color is truly dark, and as a result will not skew the color scheme of everything.

[![Dota 2 Demo](http://img.youtube.com/vi/1xE7OMnQqHI/0.jpg)](https://www.youtube.com/watch?v=1xE7OMnQqHI)


Worst case scenario, I add color enhancing specifically for Overwatch with options for user to select the actuation threshold, as well as the color boost.

P.S. Glad you like it! :)

**Comment by mysterryous** [comment]
Fantastic, works much better!

**Comment by kfirtherussian** [comment]
can some body make link to overwatch profile

**Comment by diogotr7** [comment]
Just click reset profile in the profile options, it resets to default @kfirtherussian
