### ISSUE TITLE
Button always lit

### ISSUE THREAD

**Issue by puremonk** [antonpup/Aurora#391]
My |\ key (the one left to the enter button and above the shift and underneath the close bracets) is always lit in a blue color. When I go to the aurora debug it does not show that this key should be lit. What can I do to fix this? It never changes, even when i'm using a different color. It's also there when aurora isn't opened.
Info:
Logitech g910 Orion spectrum.

**Comment by antonpup** [comment]
Make sure you've selected a proper localization for your keyboard. It sounds like you have a US keyboard, so make sure you select "United States" for keyboard localization.

**Comment by puremonk** [comment]
I checked the location, and it was on automatic, but when i change it to the US nothing changes.
The key is also lit when I don't have aurora opened but just the logitech software, maybe this helps.

**Comment by puremonk** [comment]
I think I found the problem, the key isnt actually on the preview keyboard

**Comment by puremonk** [comment]
The preview keyboard has a \ above the enter and underneath the backspace. buy mine has the \ and | combined in one key, which is not on that preview, so i cannot assign it?

**Comment by JoniSykes** [comment]
I haven't checked, because I'm lazy and use Razer gear, but is your keyboard supported yet?
By Aurora I mean...
If not then we should label this as a enhancement/feature request.

**Comment by antonpup** [comment]
His keyboard is supported. It's an issue outside of Aurora.

Related issue: #235

**Comment by antonpup** [comment]
Any updates on this?

**Comment by puremonk** [comment]
well my keyboard is the orion spectrum and it's made for the orion spark. So i guess i'll just have to deal with it.

**Comment by antonpup** [comment]
That honestly shouldn't make a difference. The SDK is the same for both.

**Comment by puremonk** [comment]
But the layout on aurora is different from my keyboard, I even tried adding the ascii code in the script but that didn't help

**Comment by antonpup** [comment]
How is it different? It's a standard layout.
This is the keyboard I have (g910 spark with US layout):
![](http://gaming.logitech.com/3D/11678-ORION/images/keyboard.png)

And this is the (g910 spectrum with US layout):
![](http://gaming.logitech.com/3D/12295-ORION/images/keyboard.png)

Both of them have the same US key layout. Aurora's layout is based on my G910 spark, but it makes no difference because it's the same layout.

What is different about it that you tried changing? From \ to |? That's just a visual representation, I couldn't fit both characters into a 30 pixels in height space.

**Comment by puremonk** [comment]
![lgg910sp_15](https://cloud.githubusercontent.com/assets/25187568/22170786/d1c2cd08-df82-11e6-9184-7087274624e5.jpg)
this is my version

**Comment by antonpup** [comment]
That is the international version. Select the international layout.

(Which may actually not fix the issue) I'll add a fix on dev.

**Comment by antonpup** [comment]
Internaltional layout should work. I checked code, it has nesessary fixes.

**Comment by puremonk** [comment]
Thanks
