### ISSUE TITLE
Can't change direction of Animation

### ISSUE THREAD

**Issue by JoniSykes** [antonpup/Aurora#392]
Hi @antonpup!

How does one reverse the direction of an animation?
E.g Sandking Epicenter is a circle expanding outwards in waves.
I want to create an effect for Enigma's Black Hole, which as you can imagine, should be waves pulling inwards.

I'm afraid I haven't been able to figure this one out by myself and wondered if you could help.
Thanks.

**Comment by antonpup** [comment]
Look at Razor Plasma Field. It does a circle going outward and a circle going in. The animations are fairly straight forward, you just set the frames to be calculated for.

But if you want to reverse an animation without creating a reverse one, then there is no way to do that. I can add that into Animation Track.

**Comment by JoniSykes** [comment]
Great Idea! I forgot Razor Plasma Field!
Let me have another crack at it today :)

**Comment by antonpup** [comment]
Closing this, because it's not a real problem with Aurora.

**Comment by UnCanard14** [comment]
Hi @JoniSykes If you have finish your animation can you share it ? thank you =)
