### ISSUE TITLE
Percent effect layer

### ISSUE THREAD

**Issue by DiaoticHaze** [antonpup/Aurora#393]
When adding your own game using aurora, how does one go about adding values such as "health" instead of just hour, minute, second, ram etc.. For example Dota 2's health options.

**Comment by antonpup** [comment]
Well.. they'd have to be a part of a profile with their own GameState (for example RL: https://github.com/antonpup/Aurora/blob/master/Project-Aurora/Profiles/RocketLeague/GSI/GameState_RocketLeague.cs )

**Comment by DiaoticHaze** [comment]
I'm a little confused on what that measn xD I'm sorry, does that mean it is or isn't possible?

**Comment by antonpup** [comment]
If you want to add support for a new game, then you can copy one of the existing profiles, adjust the GameState with values that you wish to expose, and then it should work.

**Comment by DiaoticHaze** [comment]
oh ok, that makes a lot more sense. How do I adjust the GameState?

**Comment by antonpup** [comment]
Well.. If you want to make a variable that is accessible everywhere, then you add it to [GameState.cs](https://github.com/antonpup/Aurora/blob/master/Project-Aurora/Profiles/GameState.cs), otherwise you modify the GameState with the copied profile. It will be automatically parsed for values when registered in the ProfileManager.

**Comment by DiaoticHaze** [comment]
I'm trying to do it personally, because I'm still new to this. I tried copying the profile, but for one it didn't show up on aurora, and for two I couldn't find a place to edit the script. Could you do a video on this at some time? I'd be willing to donate money (10 or more USD) for your time spent.

**Comment by DiaoticHaze** [comment]
In my example I'm trying to take the health bar from a game called Osu and display it on my keyboard

**Comment by antonpup** [comment]
Well.. do you have a way of getting the current health amount from the game?

**Comment by DiaoticHaze** [comment]
I know it's accessible, but I don't have any programs downloaded to access their script...

**Comment by antonpup** [comment]
It would be a good idea to first find out how to access the health information before attempting to add it to Aurora. :P

**Comment by DiaoticHaze** [comment]
Any tips? D; I'm fairly new to scripting, what program should I use to access such files?

**Comment by DiaoticHaze** [comment]
how did you find the file for health in dota 2?

**Comment by antonpup** [comment]
Health and other information for Dota 2 and CSGo are exposed via [Game State Integration](https://developer.valvesoftware.com/wiki/Counter-Strike:_Global_Offensive_Game_State_Integration). Which as far as I know only those two games support.

**Comment by DiaoticHaze** [comment]
then how does Aurora also have a profile including health for payday 2?

**Comment by JoniSykes** [comment]
@DiaoticHaze  The best thing you can do is google your game + the a phrase such as 'Game State Integration' or 'scripting' etc... until you find out how that game exposes its data or how scripters have accessed it. With that information you can then set up the config/listeners in Aurora to access the info.
For example, @antonpup knows the Dota2's info is broadcast to a http URL if a config file is placed in a certain directory (This is a feature of the game, not Aurora). Aurora can then receive data from that URL and parse it to determine what the data means and what to do with it.

**Comment by antonpup** [comment]
For Payday 2, @simon-wh made a GSI-like mod for it. And we use that to receive game data.

**Comment by antonpup** [comment]
I am going to close this issue, as it's more of a question, not a real problem with Aurora.
