### ISSUE TITLE
Constantly trying to connect on 239.15.18.2

### ISSUE THREAD

**Issue by Virkkunen** [antonpup/Aurora#395]
I've noticed my network was getting quite congested lately, so I decided to investigate. Wireshark had show that my PC was constantly trying to connect on this IP, 239.15.18.2. I've searched google for that IP, and I've had many results pointing out it is related to AtmoOrb, and since Aurora last update, it has compatibility with AtmoOrb.
Disabling AtmoOrb in my program doesn't stop it, though, and it keeps congesting my network. A clean reinstallation also did not solve this issue.

**Comment by antonpup** [comment]
Issue related to #342. It was already addressed on the dev build.
