### ISSUE TITLE
overwatch no longer works with g910

### ISSUE THREAD

**Issue by IRONHIDE91x** [antonpup/Aurora#397]
hi
overwatch used to work fine but now when the game boots up the keyboard just goes blank and nothing works anymore 

please help

**Comment by IRONHIDE91x** [comment]
it also show just blank when enabling it in aurora

**Comment by antonpup** [comment]
Did you recently update Aurora? You will need to re-patch the Razer wrapper.

**Comment by antonpup** [comment]
Any updates on this?

**Comment by Galadvin** [comment]
Hey @antonpup ok so Overwatch is not working for me at all after update all i see is a couple of blue keys and thats it i have no clue what to do! pic is all that i see
![image](https://cloud.githubusercontent.com/assets/25308246/22221850/34e1893a-e17a-11e6-892e-7f2c1cef9930.png)

**Comment by antonpup** [comment]
@Galadvin I am guessing if you were to select another character (like tracer) it would be orange instead of blue?

I'll see if I broke anything.

**Comment by antonpup** [comment]
@Galadvin Actually.. I know what your issue is. You need to apply the Razer wrapper from 0.6.0b, as it changed from 0.5.1d.

**Comment by Galadvin** [comment]
@antonpup ill get that 2nd option a try but the answer is no when i pick a character its still blue

**Comment by Galadvin** [comment]
ok so i applied the patch and still dose not work still all the blue

**Comment by antonpup** [comment]
Are you sure you applied it into the correct directory? If you delete the two files: "RzChromaSDK.dll" and "RzChromaSDK64.dll". It should no longer work with Aurora and route directly to Razer. Confirm that is the case. If not, then you're in a wrong folder. Afterward, reapply the 0.6.0b patch, it will create those two files, and it should work. It was working for me, because I recorded a [video](https://www.youtube.com/watch?v=p0WiaQwmSYQ) with it for my RPi branch.

**Comment by Galadvin** [comment]
in the overwatch folder? or in the razer folder?

**Comment by antonpup** [comment]
Overwatch

**Comment by Galadvin** [comment]
ok so apparently my directory changed for overwatch it used to be C:\Program Files (x86)\Overwatch but that folder only has the RzChromaSDK files in it the new directory is C:\Program Files (x86)\Battle.net\Overwatch please take not

**Comment by antonpup** [comment]
Can you confirm that it is working on 0.6.0b with the new directory?

**Comment by Galadvin** [comment]
it is working now! awesome!!! thanks for the help!

**Comment by Semono** [comment]
Hey! I have a problem too. The Overwatch illumination is not working for me The keyboard goes black.      PS: I have the newest version of Aurora and i installed the wrapper for Razer.

**Comment by antonpup** [comment]
@Semono make sure you've applied the Razer wrapper into the correct folder.

**Comment by Semono** [comment]
Into the Overwatch directory, right? I am not pretty good at this so i may have done some stupid stuff. :)

**Comment by IRONHIDE91x** [comment]
yeh it still doesnt work for me on my g910 ive tryed everything

it works just out of utter randomness sometimes

**Comment by HellsChicken** [comment]
Still not working for me either.  In fact, I can't even figure out how to get back to the Logitech Overwatch profile.  I've deleted RzChromaSDK.dll and RzChromaSDK64.dll, and unchecked the "Enable Aurora to provide lighting effects with Overwatch" box, but my keyboard still stays in my default profile when launching it.  So, alas, I'm now in a worse state than I was before enabling this...

**Comment by antonpup** [comment]
@HellsChicken If you want to use LGS profile for Overwatch, then you will have to close Aurora or disable the Desktop profile.

**Comment by HellsChicken** [comment]
@antonpup Thanks for the quick reply!  Just figured that out and was going to edit my post when you replied :)

So, out of curiosity then, what does disabling the checkbox actually do?  I guess I expected it to revert to the Logitech profile, but does it just toggle between custom lighting default profile?  (Where in this case, they are both the same thing since the custom lighting doesn't seem to be working for Overwatch)

**Comment by antonpup** [comment]
@HellsChicken Aurora has a desktop profile which is active at all times. Disabling a profile will make Aurora not switch to that profile when a specified exe is in the foreground. Thus, it will revert to the Desktop profile on disabled profiles.

If Desktop profile is disabled, then Aurora will release all devices so their respective utilities can set lighting.

**Comment by HellsChicken** [comment]
@antonpup Ah, thanks!  Makes sense.  Also good to know now that just exiting Aurora will go back to LGS profiles.

**Comment by Tearhead** [comment]
Having the same problem as IRONHIDE, I also have a G910. Additionally, I'm having another issue where the preview for the keyboard on the Aurora app is completely blank on all profiles.

**Comment by simon-wh** [comment]
Possibly related to #312

**Comment by simon-wh** [comment]
If anybody still has this issue could they try using v0.6.1-dev4 and reapplying the wrapper? I'm going to close this issue as the situation with the wrappers has most certainly changed, if you are still experiencing this issue(after my suggestion) look at #1081 or, if that doesn't apply to you open a new issue. (Your particular keyboard shouldn't matter)
