### ISSUE TITLE
[Feature Request] Custom Button for Shortcut Assistant

### ISSUE THREAD

**Issue by viper1979** [antonpup/Aurora#399]
Hello, for some games, in my case SC2, it would be nice if we could define custom buttons to work with the "Shortcut Assistant" effect. 

Example: 
I would like to have some buttons in a different color when i press the SHIFT-Button but the current Shortcut Assistant Layer only supports CTRL, WIN and ALT Keys. 

Of course it is unlikly that someone uses 'normal' keys like A or C as a potential modifier key it would make sense to let you customize your own trigger buttons.

**Comment by adiac** [comment]
It would also be great if you could add key combinations to the shortcut assistant.

**Comment by Iruberiam** [comment]
I would also like to request that SHIFT and multiple shortcut key combinations are added.  I have keybinds in a game that use CTRL+SHIFT+ALT then a number. It would be a nice boost to an already awesome program.

**Comment by antonpup** [comment]
I'm reworking the Shortcut Assistant right now.

Would a "progressive assistance" be something that is useful? For example, you hold Win key, and it lights up the next keys that can be pressed. So if I had following shortcuts assigned:

- Win + E + X
- Win + E + U
- Win + E + U + Y
- Win + O

When holding Win, "Progressive assistance" would light up: E and O. And Regular would light up E, X, U, Y, O.
When holding Win + E, "Progressive assistance" would light up: X and U. And Regular would light up X, U, Y.

**Comment by viper1979** [comment]
Maybe the 'progressive assistance' could be handy for applications like Visual Studio where such shortcuts are more often used, but for games i think such a layer is mostly not needed. Just my opinion.

**Comment by antonpup** [comment]
@viper1979 I was thinking that procedural suggestion can be used in games like Star Citizen or Arma. Where you can enable tons of options with a range of shortcuts.

Or Photoshop #314

**Comment by adiac** [comment]
@antonpup Off course this could be uses in Games like these. But just in general I think such a feature could be really usefull.

**Comment by viper1979** [comment]
@antonpup i was not aware that games exists where such complicated progressive shortcuts exists. But then i would appreciate such an assistand as well.

**Comment by Iruberiam** [comment]
Yes, I think it would be useful, I mostly use Aurora for games but that's
not to say that gaming should be it's only purpose. It can only be
beneficial to add this feature imo as it will only be exposed to the user
if they actually set it up with more complicated shortcuts.

**Comment by ozoxchris** [comment]
For the Shortcut Assistant layer, can you add a function to specify Left and Right modifier keys? Such as L-Alt and R-Alt, etc. ?

**Comment by simon-wh** [comment]
This should be sorted with the Shortcut Assitant changes made a while back
