### ISSUE TITLE
Numpad Enter Ripple

### ISSUE THREAD

**Issue by mysterryous** [antonpup/Aurora#40]
When pressing the Enter key on the numpad, the ripple originates from the primary Enter key near the center of the keyboard. Not sure if there's a way to separate the two.

Was testing the ripple effect moving to my mouse and was very confused for a brief moment.

**Comment by antonpup** [comment]
The numpad enter hey is no different from the actual enter key. As a result, pressing it will trigger the actual enter key. I don't think this is important to fix, as not many users will be using the numpad enter key.
