### ISSUE TITLE
Issue with equalizer lighting effect.

### ISSUE THREAD

**Issue by rossmane** [antonpup/Aurora#401]
The Equalizer effect works fine with my headphones but not with my speakers? Solution or patch would be greatly appreciated!

**Comment by antonpup** [comment]
EQ listens to the audio from the default audio source. Changing your speakers to be default will make EQ work.

**Comment by rossmane** [comment]
Still no luck :(

**Comment by rossmane** [comment]
NVM, restarted without my headphones connected and it worked!

**Comment by rossmane** [comment]
Hmm. When I plugged my headphones back in the issue reoccurred. Could it be because my headphones are plugged into a microphone (Yeti)? or the fact that the microphone is a potential output device via USB?

**Comment by antonpup** [comment]
Please ensure that your speakers are your default audio device in the sound settings.

![](https://puu.sh/twXvJ/6591eb615e.png)

**Comment by simon-wh** [comment]
Any updates on this?
