### ISSUE TITLE
Dota 2 Killstreak effects not working?

### ISSUE THREAD

**Issue by baybolin12** [antonpup/Aurora#403]
Title sums it up I guess. Everything else is working perfectly while killstreaks do nothing.

**Comment by baybolin12** [comment]
Guess more is not working. I only have the health, mana and item slots working. The rest is gone.

**Comment by baybolin12** [comment]
Keep realising new stuff. Think the demo option in the hero loadouts ruin it. Going for a game now let's see what's up over there.

**Comment by baybolin12** [comment]
Everything is working apart from the team background colors. Could not test the killstreaks I was a support. Any thoughts on how I can fix it?

**Comment by antonpup** [comment]
What do you mean apart from team background colors? Those are supposed to fade after a few seconds after spawning.

**Comment by baybolin12** [comment]
Oh. That, I did not know. Guess everyting is working perfectly fine then. Just had an inconsistency in the start. Thanks anyway @antonpup!
