### ISSUE TITLE
[Feature Request] Mousepad Lighting

### ISSUE THREAD

**Issue by rossmane** [antonpup/Aurora#404]
Could you have a more in-depth inclusion of the razer firefly/Polaris mm800 RGB mousepads? They are affected by the application and look nice but they act like a single light rather than haveing the 16 customizable lighting zones.

**Comment by antonpup** [comment]
My main issue with doing more detailed lighting for mousepads is that I don't know exactly where the LEDs are located. So... they would look off and then it will be a nightmare debugging it.

**Comment by RacerXNFS** [comment]
A bit late on this, I know. But I've an idea. 

In the case of the Polaris, you can probably experiment with development using CUE alone. Recent versions have virtual "demo" accessories that can be used to play with the lighting, and I can happily confirm I've used that feature frequently to see how lighting works with Aurora. The demo devices are the Scimitar, Void headset, K95 RGB and MM800 Polaris, which as of now uses the "Peripheral Logo" lighting. It's 15 individually-mapped zones. (Oh, and I imagine once SDK support for the K95 Platinum is out, it'd probably help with that too.)

The Firefly, that I wish I could help with. Supposedly it's 15 zone lights, maybe an individually addressable brand zone. Maybe seek out a tester for that?

**Comment by simon-wh** [comment]
Fixed thanks to #1331!
