### ISSUE TITLE
i saw an issue saying you fixed the logitech stuff but it doesnt work

### ISSUE THREAD

**Issue by jamiejlj** [antonpup/Aurora#405]
the division and gta 5 still dont work my corsair strafe is black for the division and the police lights dont work for gta 5

**Comment by antonpup** [comment]
That fix isn't part of the public build.

Also, it sounds like your issue is separate. Make sure you have the c++ 2015 redistributetables installed, as well as LGS.

**Comment by jamiejlj** [comment]
I installed and setup LGS but my keyboard is still blank even after going into division settings and enabling logitec LED

**Comment by antonpup** [comment]
Like I said, dev build has the fix for the division. But GTA 5 works, I know that.

**Comment by jamiejlj** [comment]
I will try GTA5 now gimme a few mins

**Comment by jamiejlj** [comment]
still doesn't work. GTA just displays white no matter wat is happening in-game. I checked that keyboard lighting is turned on in-game settings

**Comment by antonpup** [comment]
Can you try with a previous version? v0.5.1d

**Comment by jamiejlj** [comment]
it works with 0.5.1d

**Comment by antonpup** [comment]
Did you reapply the Logitech wrapper with 0.6.0?

**Comment by jamiejlj** [comment]
idk i had everything setup right in 0.6.0 but when i reverted to 5.1d everything worked on gta

**Comment by antonpup** [comment]
Ok, with 0.6.0 I have changed the wrapper, so when you use 0.6.0, you will need to reapply the wrappers for it to work.

**Comment by jamiejlj** [comment]
works after i upgraded 5.1 to 6.0 via updater
