### ISSUE TITLE
[Feature Request] Control every single LED in the Logitech G502 Spectrum

### ISSUE THREAD

**Issue by grimsi** [antonpup/Aurora#409]
While the G502 works just fine, Aurora treats the multiple LEDs (Logo+3 DPI LEDs) as one single LED so youre only able to change them together. While this is sufficient for most use cases, it would be nice to have the possibility to control every single LED for more advanced effects.

**Comment by antonpup** [comment]
This is not possible on Logitech, because the LED SDK does not allow you to set multiple colors on mice/headsets.
