### ISSUE TITLE
Can't seem to get Aurora to work

### ISSUE THREAD

**Issue by cyborgium** [antonpup/Aurora#411]
Hello,

I'm quite new to Aurora, just installed it as I was excited to try out new RGB stuff with my Logitech G810.
Only, I cannot seem to get Aurora to work. For some reason (probably just me not being able to figure out how this works), none of the lighting profiles apply. I set up a desktop profile with a solid static color for easy testing, but nothing happens. It keeps doing the default rainbow wave.

Anyone knows what I'm doing wrong?

**Comment by antonpup** [comment]
There is no "default rainbow wave"... Default desktop profile has CPU and RAM usage meters, as well as the interactive effect.

Do you have LGS running?

**Comment by cyborgium** [comment]
I meant the default rainbow wave that LGS has as default, sorry. And no, I closed LGS. I also removed it from startup programms and restarted my pc just to be sure. 

Thanks for replying so quickly!

**Comment by antonpup** [comment]
LGS is required for LED SDK to function.

**Comment by antonpup** [comment]
Ok.. try this simple fix. Reinstall LGS, it should work after.

**Comment by cyborgium** [comment]
Alright, I re-installed LGS. Now all the lights of the keys are off, except for the media keys.

**Comment by antonpup** [comment]
Aurora works then.

**Comment by cyborgium** [comment]
Maybe it does work now, but i still cant seem to change any of the lighting effects. All the light remain off. It's probably something really obvious that im doing wrong, but I cant find out what it is...

**Comment by cyborgium** [comment]
Okay, I got it to work... the brightness was off in the settings tab. Must have accidentally turned it all the way down... im stupid

**Comment by antonpup** [comment]
Was it the alt+volume setting? I might just remove that, it causes quite a few problems for people.
