### ISSUE TITLE
Lock Keys

### ISSUE THREAD

**Issue by trwinowiecki** [antonpup/Aurora#412]
Every time Aurora is restarted it appears to remove the assigned keys on the capital Lock Layer. Also a Windows key lock layer would be awesome.

**Comment by antonpup** [comment]
There is no such thing as a win lock key... So... There is no way for Windows to detect if a Windows key is "locked". It's not a native Windows function.

**Comment by simon-wh** [comment]
@trwinowiecki I wasn't able to replicate it with a normal application restart. How are you closing Aurora?

**Comment by simon-wh** [comment]
Any updates on this?
