### ISSUE TITLE
Logitech G810 + Ram Error

### ISSUE THREAD

**Issue by bl4cktoxic** [antonpup/Aurora#413]
Overwatch and Csgo both got a freeze where the monitor stucks mid game but I still can hear the sound in the background even if I click something. In csgo I got a error message who focus on something with my RAM, can´t remember but I´ll try to screen it next time. Without Aurora there is not such an error and even Memtest said everything is fine. 

Thought with launching Overwatch in Adminmode would help but after a few days I got this freeze again. Yesterday the first time in Cs:go while playn faceit + the new anti-cheat client from faceit.

Does Aurora receive informations from the RAM especially while playn csgo or overwatch ?

Btw: are these ERRORS in the log normal about the cooler master and razor devices ?:
e.g:
[ERROR] 26.01.2017 08:48:54: Razer device, Exception! Message:System.Exception: No Chroma SDK available
[ERROR] 26.01.2017 08:48:54: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface bei Aurora.Devices.Clevo.ClevoDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:Zeile 65.
[ERROR] 26.01.2017 08:48:54: Cooler Master device control could not be initialized

Specs:
Win 10 Pro
Procssor: Intel Core I7 6700k
Graphics Card: MSI GTX 970
RAM: Corsair Vengance LPX DDR4 16GB Kit(2x 8GB) 3000MHz | XMP active for overclocking to 3000Mhz 
Mainboard: MSI Z170A Gaming Pro Carbon | XMP active for overclocking RAM 
Harddrive: 500GB Samsung SSD / 2,5 TB HDD
Mouse: Logitech Proteus Core G502
Keyboard: Logitech G810

**Comment by antonpup** [comment]
Those errors are perfectly normal. However, while I cannot say that Aurora is definitely at fault here, what I can say is that C# automatically collects garbage (ie clears up unused resources). What are Aurora's RAM and CPU usages while running in csgo or overwatch? For CSGO, there is currently a relatively large overhead with fps (Aurora renders at 100 fps instead of regular 30), but Overwatch has no such overhead. So I am inclined to say that there is something off with your hardware. It's possible that overclocking is messing with Aurora, if you have any. Try running [Prime95](http://www.mersenne.org/download/) for a few hours, see if that causes any issues.

Do your logs state any other errors?

**Comment by bl4cktoxic** [comment]
Don´t get me wrong, It´s not a RAM problem with overwatch. Only get those freezing screens of death while I can hear the sound in the background (If I click shoot I can hear that). I will investigate that further with admin mode on both programs. 
CS seems fine now with Aurora in admin mode, was maybe just a random thing with the RAM Error, bad thing I can´t remember what the error was. But just let us say CS it not a thing at the moment its more about overwatch.

Nevertheless I´ll capture the RAM and CPU usage while I play both games.
+Prime95 I´ll check that too

I only overclocked the RAM to reach the 3000Mhz with the XMP Mode from my Mainboard, nothing manual.

Error Logs are fine, only the normal ones with devices and so on.

Btw: Aurora runs on my C System drive (SSD) could that be a problem in someway ?

**Comment by antonpup** [comment]
This is the first report of any hardware-related issues with Aurora, so I doubt that C Drive location has any effect on it. It could also be a problem with GPU, since your described symptoms involve visuals freezing and not sound our input.

**Comment by bl4cktoxic** [comment]
The thing is everytime that happends, Aurora or my keyboardcolors freezing too. And the errors appeared with the installation of the razor patch on overwatch / installation from Aurora. I don´t want to be narrow-minded I´ll try every possible combo and test method tho.

**Comment by antonpup** [comment]
What is your LGS version? Do you have latest one installed? Reinstall LGS?

**Comment by bl4cktoxic** [comment]
Version is 8.89.68, I see there is an update on version 8.90 from Jan 4. 2017 I´ll download it and try this. Should the freeze come again I´ll post some numbers about RAM and CPU :)


Btw: a pretty damn nice thing you´ve done with Aurora and cool to have some close contact to you. 👍

**Comment by antonpup** [comment]
Any updates on this?

**Comment by bl4cktoxic** [comment]
Sry coudn´t test any further, CSGO RAM error was 100% not Aurora, just random game error.

Arma 3 crashes with Aurora if I exit it after a long game session (playn with mods) but I won´t blame Aurora for that either cause this game isn´t stable at all

I now test Overwatch everyday for like 4 -6 hours, if I don´t write something till 5th you can assume that everything runs fine if I launch both apps in admin mode.
Btw.: I read something about the razor app may cause some trouble with Overwatch, it could be possible that the patch could cause this error but I´m not sure about that...as I said, I´ll test it now.

**Comment by bl4cktoxic** [comment]
[ERROR] 30.01.2017 21:58:09: Exception during Node parsing. Exception: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: T. Path '', line 0, position 0.
   bei Newtonsoft.Json.JsonTextReader.ParseValue()
   bei Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   bei Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   bei Aurora.Profiles.Node`1..ctor(String json_data) in D:\Repositories\Git\Aurora\Project-Aurora\Profiles\Node.cs:Zeile 18.

Normal Error ? Aurora is not installed on D btw.

CS:GO Freezes like Overwatch and Aurora is getting slowly and stuck in the ALT layout after I killed the csgo task.

**Comment by antonpup** [comment]
That error is perfectly normal. That path is my Aurora project location.

As for freezes, I still don't know...

**Comment by bl4cktoxic** [comment]
I´m running tools like Nvidea Driver, MSI Gaming App, Nahimic 2, Bitdefender as my Antivirus and MSI Lan Manager but not active.

I try few things out. Any Idea what windows setting could be bad for Aurora ?

**Comment by bl4cktoxic** [comment]
Issue was caused bei Nahimic 2... dunno why but yeah...
