### ISSUE TITLE
Custom Profiles Won't Work

### ISSUE THREAD

**Issue by Gamer1045894** [antonpup/Aurora#415]
The funny thing is, everything used to work just fine. I'm still able to create and edit custom profiles, but they won't display on screen or work. I tried restarting the application and deleting profiles to no success.

Thanks for the help

![screenshot 186](https://cloud.githubusercontent.com/assets/25380202/22360673/de636544-e406-11e6-934d-213419a15fb5.png)

**Comment by antonpup** [comment]
Can you provide Aurora logs from the time when a custom profile should display, but doesn't?

Did you install Aurora though the Web Installer?

**Comment by Gamer1045894** [comment]
Yes, I did install Aurora through the official Website

I couldn't find the exact area where the error happened, so I uploaded the entire log
[2017_25_01.docx](https://github.com/antonpup/Aurora/files/736625/2017_25_01.docx)

**Comment by simon-wh** [comment]
Do you have any layers in the 'NightTime' section? I've just played around with it a bit and if your time is within the nighttime zone that's what you'll get shown no matter what you have selected.

**Comment by Gamer1045894** [comment]
No, I do not have any layers in the nighttime section.

**Comment by simon-wh** [comment]
Could you go to the Settings and disable the "Enable nighttime color zones for General Application lighting profiles" option? and see if that allows you to see the lighting in your custom profile?

**Comment by r3sist3nt** [comment]
I have the same error. There might be something wrong with the process detection. I'am trying to create a custom profile for Rust. The launcher is called rust.exe while the actual client is rustclient.exe.
When the profile is set to rust.exe, the keyboard will change to the profile. But just as long as the launcher is loading.. When the profile is set to rustclient.exe, the keyboard won`t change at all. Might be something with borderless fullscreen? If it helps, the game is based un Unity4d.

**Comment by r3sist3nt** [comment]
@antonpup I Tracked the issue down to Process.GetProcessById((int)processId).MainModule.FileName in GameEventHandler.cs
It looks like this Method of accessing the MainModule doesnt work on every process properly. 
A "System.ComponentModel.Win32Exception in System.dll" is thrown, every time when trying to access the MainModule. Normaly this shouldnt be thrown when compiled in x64, but its still occuring.
I'am working on a fix and will open a pull request as soon as everything is working

**Comment by simon-wh** [comment]
Any updates on this?

**Comment by r3sist3nt** [comment]
My changes are merged into the dev branch. You will need to compile it by yourself. 
If you dont know how, i can upload my binaries and you can use them(if you trust my code). This would be a nice way to test if my code also fixes the issue on other systems.

**Comment by eliyameri** [comment]
@r3sist3nt could you please upload your binaries? I don't know how to compile the program and custom profiles don't work for me either

**Comment by r3sist3nt** [comment]
I don't give support for this.. But feel free to try and give some feedback ;)
[https://raw.githubusercontent.com/r3sist3nt/Aurora/master/Aurora.exe](url)

**Comment by simon-wh** [comment]
Any updates?
