### ISSUE TITLE
[Bug] BF1 Lightnigh doesn't work as intended

### ISSUE THREAD

**Issue by grimsi** [antonpup/Aurora#416]
While playing BF1 my Logitech G502 Mouse turns black (lights off) and my Keyboard (Corsair K70 Lux RGB) only shows a solid color depending on the situation, eg "in menu", "dead", "gas", "fire" (which is fine in some cases, but in others it should theoretically have per-key-lightning, as advertised here: https://www.youtube.com/watch?v=GSxVwS-u4dM)

**Comment by antonpup** [comment]
You need to make sure you have the wrapper from 0.6.0 version installed. As versions prior to did not have scan codes supported.

**Comment by grimsi** [comment]
I installed Aurora v0.6.0b, do I have to update the wrappers manually when upgrading from an older version?

**Comment by grimsi** [comment]
Thats the first thing I did when trying to fix this issue, but didnt help.
Whats weird is that it works perfectly with the division which also uses Logitechs Lightning SDK afaik

**Comment by antonpup** [comment]
The division isn't supposed to work. So.... something isn't right here. The Division is currently broken on 0.6.0b, I had to apply a fix for it on dev build.

**Comment by grimsi** [comment]
Yeah, youre right, I just looked at the Logitech website how its actually supposed to look.
The Lightning worked, but it looked different on my keyboard, kinda weird now that I know how it's supposed to look like.

**Comment by antonpup** [comment]
I can confirm that BF1 lighting works on the dev build.

**Comment by grimsi** [comment]
I just pulled the dev branch and compiled it and the per-key lightning works.
The mouse, however, is still black.
If I close Aurora and give the Logitech Gaming Software the Control over the lightning of my mouse, it works fine.

**Comment by antonpup** [comment]
What does the mouse light up as? The background?

**Comment by grimsi** [comment]
No, it is black. The moment I start BF1 the light of my mouse turns off.
Very strange
