### ISSUE TITLE
Software not working

### ISSUE THREAD

**Issue by 09ymmit07** [antonpup/Aurora#417]
I have selected the correct keyboard, tried with LGS on and off, and restarted Aurora multiple times but it doesn't change the lighting of my G910 at all.

**Comment by antonpup** [comment]
Reinstall LGS.

**Comment by 09ymmit07** [comment]
I did, it kinda works now except it does a completely different thing than what I have set. Every thime I press a key my G keys blink, and the CPU usage keys are pink and don't change colour (set to blue) and the ram usage keys are blue and don't change (set to red)

**Comment by antonpup** [comment]
Do your logs show any errors?

**Comment by 09ymmit07** [comment]
Where would I find those?

**Comment by antonpup** [comment]
Rocket League is broken. But at least you got it working. I'll be closing this for now.

**Comment by 09ymmit07** [comment]
I didn't mean I got it working.

**Comment by antonpup** [comment]
Try running this command two times in command prompt:
`lodctr /R`

Second one should succeed, afterwards restart Aurora.

**Comment by 09ymmit07** [comment]
Doesn't succeed, no matter how many times I try. ''Error: unable to rebuild performance counter setting from system backup store, error code is 5''

**Comment by antonpup** [comment]
You will have to google around with that error. But that is why your cpu and ram usages aren't working.

**Comment by 09ymmit07** [comment]
Got it, I had to run as admin. It still doesn't work though.
