### ISSUE TITLE
not to much serious interactive layer

### ISSUE THREAD

**Issue by crowdh** [antonpup/Aurora#418]
it's about the enter on the numeric pad (logitech g910) 
while i hit (interactive layer) it does nothing (in the numeric  section) But the "enter" in letter section interact! 

https://www.youtube.com/watch?v=iodcjfe-8Vg

as you will see on this short video! 

thank you all!

**Comment by antonpup** [comment]
Windows does not differentiate between Numpad Enter and regular Enter. Not much I can do about it.

**Comment by crowdh** [comment]
but on my lg sofware the numeric enter work :s

**Comment by antonpup** [comment]
LGS's key effects also work with G-keys, and those are 100% not part of Windows. They have access to different techniques than I do. So, they can do more refined effects.

**Comment by crowdh** [comment]
ohh  i see   ;P thank you
