### ISSUE TITLE
CS:GO missing light profiles

### ISSUE THREAD

**Issue by TechnoPeter** [antonpup/Aurora#419]
It seems like since the big 0.6.0 Update, some features that the previous versions had are missing from the CS:GO profile, for example Health Indicator.

**Comment by antonpup** [comment]
No features for CSGO have been removed (if anything they were added).

Reset your CS:GO Profile and you will see the layers with previously existing features/settings.

**Comment by g-uru** [comment]
i can confirm CSGO features work as described.
