### ISSUE TITLE
Logitech G910 and missing dll

### ISSUE THREAD

**Issue by Atha42** [antonpup/Aurora#42]
Tried to wrap razer chroma thingy for overwatch, no problem to patch but when you launch the game there is an error message saying MSVCP140.dll is missing.
You can still play the game but no modification on keyboard plus heavy fps drop ingame until you shut aurora down.

**Comment by antonpup** [comment]
You have to make sure to have Visual Studio C++ 2015 Redistributable
installed. https://www.microsoft.com/en-us/download/details.aspx?id=48145

I will try to get it automatically install like how steam does it, prior to
Aurora use. Or it will be a part of the installer. But for now, you have to
install it manually.

P.S. if you get any more Overwatch issues, I have found that Windows 8 and
below have to run the game and Aurora as admin.

On Thu, Jun 16, 2016 at 3:29 PM, Atha42 <notifications@github.com> wrote:

> Tried to wrap razer chroma thingy for overwatch, no problem to patch but
> when you launch the game there is an error message saying MSVCP140.dll is
> missing.
> You can still play the game but no modification on keyboard plus heavy fps
> drop ingame until you shut aurora down.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/antonpup/Aurora/issues/42>, or mute the thread
> <https://github.com/notifications/unsubscribe/ADQ3CzPkdtIoRAk4HpRNMMirT79bWaP3ks5qMc5dgaJpZM4I335Z>
> .
>



-- 
-Anton

**Comment by Atha42** [comment]
I use Windows 7 and followed the tutorial step by step. :/

**Comment by antonpup** [comment]
Did you install both x64 and x86 versions? Since you're on Win7, you're gonna have to run as admin. It's a change on Blizzard's side I think. As during Alpha this was not the case.

if installing both does not resolve that error, let me know.

**Comment by Atha42** [comment]
I added x64 version, no more missing dll nor fps drops, but still no keyboard change, i may have missed something in aurora configuration... I'll come back if I don't find where I messed up.

Anyway keep up the good work. ^^

**Comment by antonpup** [comment]
That's good. Now you gotta set Overwatch to run as Admin. Do so by right clicking overwatch.exe and going into properties, and then setting it to run as admin.

![http://puu.sh/ptkHw/b25566a0af.png](http://puu.sh/ptkHw/b25566a0af.png)

**Comment by Atha42** [comment]
<img src='http://exgirlfriendrecovery.com/wp-content/uploads/2015/12/working.jpg'>

Thank you for your help and for your work. :)
