### ISSUE TITLE
ARK Survival Evolved issues

### ISSUE THREAD

**Issue by DMZDesolace** [antonpup/Aurora#424]
I'm attempting to create a new profile for ARK, but when the game is loaded Aurora won't switch to the profile. Both Foreground App Scan and Windows event options have the same issue.

Note: The game uses Unreal Engine 4 (shootergame.exe), and uses BattleEye anti-cheat.

Issue #147 - Is opened to add Native ARK support, but i believe that the profile not switching is a different issue. Please correct me if i'm wrong, thanks.

**Comment by antonpup** [comment]
ARK is probably run as admin, so try running Aurora as admin as well.

There is a permissions issue where if a normal process attempts to retrieve information about an admin process, it will not allow it to do so.

**Comment by DMZDesolace** [comment]
Thanks for the info.

Running Aurora as Admin, and the game without BattleEye makes the Profile run successfully.
However, if the game is run with the anti-cheat, the profile still will not load.

(Note: i made a separate profile for the anti-cheat executable [ShooterGame_BE.exe] which loads initially, then switches to the Default profile. I checked Task Manager, and the process is still ShooterGame.exe]

Any ideas why this might be? i would expect the Foreground App Scan to work in this case.

**Comment by antonpup** [comment]
It probably means that exe name is reported as something else or anti-cheat is doing some weird permissions magic. It's also possible that battle eye has an overlay, and when you're running the game, it reports exe as battle eye's.

**Comment by r3sist3nt** [comment]
I found a bug in the Process detection with x64 games, ark might be also effected by this. I opened a PR with the fix.
I will test later if it also fixed the issue for ark.

**Comment by stbatuhan** [comment]
Hi, i didn't test it now but you can add extra option for ark. Maybe if someone has a problem then application can search for the active tasks. And if there is Ark then can start that profile. Or if there is active one is battle-eye then app can search for ark or h1z1 or smt else to activate right profile.
