### ISSUE TITLE
Equalizer

### ISSUE THREAD

**Issue by WannabeLynx** [antonpup/Aurora#426]
Is there a way to get the Equalizer not showing over all keys?
It would be awesome if I could leave the F1 - F12 and the Numpad blank. :3 

thanks for the help :)

**Comment by simon-wh** [comment]
This will be possible in the next version through the 'Key/Region exclusion' option available to all layers

**Comment by WannabeLynx** [comment]
Oh sweet! I figured out how i can make keys black when not used so the equalizer wont be on them :)

Keep up the good work!
