### ISSUE TITLE
Rise of the Tomb Raider lighting effects partially working in G910

### ISSUE THREAD

**Issue by stumpfoll** [antonpup/Aurora#427]
Hello, I configured Aurora with the Aurora Wrapper Patch for Razer and I created a profile for the game. The light effects are working but there's a continuous blinking. It should work like this [https://www.youtube.com/watch?v=WeIQKa_h78o](https://www.youtube.com/watch?v=WeIQKa_h78o), here's how mine is working. [https://vimeo.com/202082093](https://vimeo.com/202082093)

**Comment by antonpup** [comment]
Yeah, it's a bug that also happens on other wrappers. I'll take a look at it.

**Comment by antonpup** [comment]
My apologies for the delay, I just tested this on Dev branch and everything seems to be working fine. No flickering like you have, it even lights up pressed keys white. So, I am assuming that I fixed this problem while working on other Wrapper fixes.

Should be working next version.
