### ISSUE TITLE
Start with Windows not working

### ISSUE THREAD

**Issue by smh51** [antonpup/Aurora#43]
Hello,

I have a G810 and when i tick the checkbox start with windows, nothing happens at windows startup. I have to launch aurora manually.

Is it a known bug or the issue is just by my side ?

Anyway, it's not a big deal. Keep up the good work !!

OS : Windows 10 x64
LGS 8.83.85
Keyboard : G810
Mouse : G500

**Comment by medifin** [comment]
I have this issue too

**Comment by antonpup** [comment]
Anything in the logs?

**Comment by smh51** [comment]
nothing too obvious in the log :+1: 

[INFO] 18/06/2016 14:23:22: Device, Logitech, was initialized
[ERROR] 18/06/2016 14:23:22: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 18/06/2016 14:23:22: Device, Corsair, was not initialized
[INFO] 18/06/2016 14:23:22: No Chroma SDK available
[ERROR] 18/06/2016 14:23:22: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   à Aurora.Devices.Razer.RazerDevice.Initialize() dans d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:ligne 52
[INFO] 18/06/2016 14:23:22: Device, Razer, was not initialized
18/06/2016 14:23:24: Listening for game integration calls...
[INFO] 18/06/2016 14:43:43: Device, Logitech, was shutdown

**Comment by antonpup** [comment]
Can I see the entire log? In the beginning it shows os info and launch parameters.

**Comment by IrealiTY** [comment]
same issue here, didn't manually restart the program and it gave me this log file after launching windows:

```
========================================
Operation System: Windows 10 Home
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 4
User DomainName: xxxx-HOME
User Name: xxxx
SystemPageSize: 4096
Version: 4.0.30319.42000
========================================

[INFO] 18/06/2016 12:59:26: Program started with '-silent' parameter
[INFO] 18/06/2016 12:59:26: Program started with '-delay' parameter with delay of 5000 ms
[INFO] 18/06/2016 12:59:32: Device, Logitech, was initialized
[ERROR] 18/06/2016 12:59:32: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 18/06/2016 12:59:32: Device, Corsair, was not initialized
[INFO] 18/06/2016 12:59:32: No Chroma SDK available
[ERROR] 18/06/2016 12:59:32: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 52
[INFO] 18/06/2016 12:59:32: Device, Razer, was not initialized
```

but Aurora was not launched at all

**Comment by smh51** [comment]
========================================
Operation System: Windows 10 Home
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: XXX-DESKTOP-PC
User Name: xxx
SystemPageSize: 4096
Version: 4.0.30319.42000
========================================

[INFO] 18/06/2016 22:03:21: Device, Logitech, was initialized
[ERROR] 18/06/2016 22:03:21: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 18/06/2016 22:03:21: Device, Corsair, was not initialized
[INFO] 18/06/2016 22:03:21: No Chroma SDK available
[ERROR] 18/06/2016 22:03:21: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   à Aurora.Devices.Razer.RazerDevice.Initialize() dans d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:ligne 52
[INFO] 18/06/2016 22:03:21: Device, Razer, was not initialized
18/06/2016 22:03:22: Listening for game integration calls...

**Comment by antonpup** [comment]
I suspect it's an issue with Keyboard Layouts. Will look into it after profile import/export.

**Comment by antonpup** [comment]
Issue has been located. Turning off Skype Overlay will resolve the issue. It will be fixed in the next version.
