### ISSUE TITLE
CoolerMaster Masterkeys RGB S and Overwatch

### ISSUE THREAD

**Issue by cjbeames** [antonpup/Aurora#433]
### What are you experiencing an issue with?

- [x] Aurora
- [x] Aurora supported game, Overwatch, Windows 10
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, CM MasterKeys RGB S UK
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [x] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
First of all all the keys should be illuminated. Secondly Aurora cause large drops in FPS

### Actual behavior:
The \ # and return key do not light up, these are the keys that are different to the US version.
Running Aurora with Overwatch causes the game to drop FPS massively everytime the keyboard reacts to the game. For example; getting an ult, ability off cool down. 
Important to not that if I close the Aurora software the keys light up again and if I play Overwatch without Aurora the performance returns to normal.
Also these are two separate issues really, new here and not sure how this is works.
### How often does this problem occur?
Consistently

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Run Aurora
2. Look at keyboard
3. Not all lights working
4. Run Overwatch
5. Play long enough for the keyboard to react
### What is the version of Aurora you are experiencing this issue with?

My version is the latest as of writing this, sorry I can't seem to locate the aforementioned about tab.

### Does the previous version of Aurora have this issue?
Not sure this is the first version I have used.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by brainbug89** [comment]
Maybe nexttime create two separate issues.

> The \ # and return key do not light up, these are the keys that are different to the US version.

And what kind of keyboard layout are you using? Could be a wrong layout setting. Can you light up these keys at Desktop mode at Aurora? Also see _Preferred Keyboard Layout_ at Devices settings.

For the FPS drops I can't help, because I don't own Overwatch.

> My version is the latest as of writing this, sorry I can't seem to locate the aforementioned about tab.

See Settings (gear icon, left bottom) > About

**Comment by cjbeames** [comment]
OK, thanks, I will know for next time.

As stated next to the device it is the UK CoolerMaster. I've tried with the software automatically assigning the layout and forcing UK. Same issue both ways.

**Comment by antonpup** [comment]
Overwatch performance issue - I do not know. Low end pc?

As for not lit keys, I will see what I can do.

**Comment by cjbeames** [comment]
The FPS drops are very large and occur exactly in time with a change in the lighting effects. Not sure what is classed as a low end PC really. I've only had it a few months, custom build... 6th gen Intel i5 GTX 1060 8GB RAM

**Comment by snichola** [comment]
Can you try running Overwatch as administrator and see if it has any effect?

**Comment by cjbeames** [comment]
There is only one account on my PC, that should make it the admin by default no?

**Comment by snichola** [comment]
You have an administrator account but not every application runs with
administrator privileges.  I observed some weird behavior with the cooler
master implementation and overwatch which cleared up when overwatch was run
as admin.  I'm not sure if that only affected my machine.

Go to your overwatch installation folder.  Right click on the overwatch
executable and then click run as administrator.

**Comment by cjbeames** [comment]
That seems to have solved the problem. So far so good anyway. Is there a way to get the launcher to run the games as admin?

**Comment by snichola** [comment]
If you right click the executable and hit properties then go to the
compatibility tab there should be a check box to always run as
administrator.  I need to find a better solution to this at some point.

**Comment by snichola** [comment]
Just to be clear only change overwatch to run as administrator.

**Comment by cjbeames** [comment]
Yeah, that is what I did. Like you said. But normally I use the launcher to get into the game as then I do not need to sign in every time. This might be out of your remit but can you get the Blizz launcher to run the game as admin?

**Comment by snichola** [comment]
If you have set the overwatch executable to always run as admin it should
still work even if you launch the game with blizzard's launcher.  At least
as far as I remember.  I can check it later.

**Comment by cjbeames** [comment]
Set both the "overwatch launcher" and "overwatch" executables to run as administrator and then launched them via the Blizzard client and the problem was back.

**Comment by antonpup** [comment]
So what I gather from this conversation, is that running Overwatch as admin reduces the fps drops? Do you also run Aurora as admin?

**Comment by snichola** [comment]
If you're asking me, no I don't run Overwatch as admin.  I built a new pc and I know you made improvements to the wrapper where now I can't see a difference in FPS between running the game with or without admin permissions.  Before I was would drop 20-30 frames if I didn't run the game as administrator.

cjbeames did you try setting only the overwatch game executable to always run as administrator?  Not the launcher.

The one selected below.
![image](https://cloud.githubusercontent.com/assets/903133/22670701/67bb2982-ec98-11e6-8e0f-d59f51e28cdb.png)

**Comment by cjbeames** [comment]
The FPS drops that were caused by Auroa were not present when launching Overwatch directly as administrator (without Blizzard client)
Setting the game to always run as admin and then using the Blizzard client to launched cause the FPS drops to come back. 
If anyone else wants to test this, Lucio is a good character to do this with as his specific lighting is by far the most active and will produce much more noticeable results. 
If you would like me to try anything out or provide any more data let me know.

**Comment by simon-wh** [comment]
Directing further discussion to #1002
