### ISSUE TITLE
Ambilight effect delay

### ISSUE THREAD

**Issue by latworx** [antonpup/Aurora#436]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [x] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [x] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Ambilight effect change the led colour follows the colour of the monitir

### Actual behavior:
Its follows, but with some quite unacceptable delay. Sometimes more than 500ms-1 sec

### How often does this problem occur?

This problem occurs every time

### What is the version of Aurora you are experiencing this issue with?

My version is the latest one

### Does the previous version of Aurora have this issue?
Cant clarify on this as i just using the aurora

Dont know whether this issue is normal for the ambilight. Cant it improves at least its not significant?

**Comment by antonpup** [comment]
The delay is normal. It prevents Aurora from locking up while trying to screenshot the desktop.

**Comment by latworx** [comment]
I see. It cannot be more faster ya? If the delay is the best period its need, its ok then 🙂

**Comment by antonpup** [comment]
It can be set faster if the process of screenshotting the desktop is optimized. It's not on the table for me at the moment.
