### ISSUE TITLE
rpi_script limit?

### ISSUE THREAD

**Issue by latworx** [antonpup/Aurora#439]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [x] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [X] Other, (the script not running in certain case)

### Expected behavior:
The Raspberry Pi script running without problem

### Actual behavior:
The script si not running (and not shown in Devices and Wrappers)

### How often does this problem occur?

This problem occurs when i put several DeviceKey in PI_LED_MAPPING

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

When i put more than 13 lines of key map for LEDs, the script will not runnning

### What is the version of Aurora you are experiencing this issue with?

My version is v0.6.0b

### Does the previous version of Aurora have this issue?
Didnt tried it before

### Please include any logs, screenshots, or files that are related to this issue:
http://s000.tinyupload.com/index.php?file_id=28006830513045053292

Hi @antonpup, if i uncomment one of the line commented, the script will not running, and not shown in the Devices and Wrappers list, as it is not exist. Is it always a limit for it? Im notice that u were give an example for 13 lines only. Can i have more?

**Comment by antonpup** [comment]
This is a syntax issue, you need to put a comma after each entry. So if you wanted to add 14th and 15th, you would do:
``` C#
{ DeviceKeys.F6, new int[] { 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39 } },
{ DeviceKeys.F5, new int[] { 22 } },
{ DeviceKeys.F4, new int[] { 23 } }
```

**Comment by latworx** [comment]
Oh my... Im pretty sure i've check these.. Im might need rest afterwork hour instead of strain my eyes  for straight 10 hours.. Thanks
