### ISSUE TITLE
Breathing effect bug with keyboard+mouse

### ISSUE THREAD

**Issue by jarlave** [antonpup/Aurora#440]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
If I add the both Logos from the Keyboard(G910 orion spectrum) and the one from the Mouse(G900) to an breathing layer, all logos should have the breathing effect.

### Actual behavior:
If I only add the Keyboard logos to the breathing layer it works just fine, but after I add the Logo from the G900, only the logo from the mouse is breathing, the logos on the keyboard only updates if I write something.

### How often does this problem occur?

Every time after I add the Mouse to the breathing layer

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Create a breathing layer with both random colors
2. add keyboard logos (works fine atm)
3. add mouse logo (keyboard logos stopped breathing)

### What is the version of Aurora you are experiencing this issue with?

My version is v0.6.0b

### Does the previous version of Aurora have this issue?
tried 0.6.0, same issue

### Please include any logs, screenshots, or files that are related to this issue:

http://pastebin.com/uc7NugPJ

**Comment by antonpup** [comment]
Thank you for reporting this. I made a fix on the dev branch. Will be fixed in next release.
