### ISSUE TITLE
Wrong keys light up. (Logitech g910, swedish/nordic layout)

### ISSUE THREAD

**Issue by EmilFer** [antonpup/Aurora#444]
I've discovered a bug on the g910 which leads to wrong keys being lit up when using an interactive layer.

I have a Swedish layout Logitech g910 Orion Spectrum.
It only happens when num lock is off and only the numpad keys are affected.

When num lock is off the following keys light up instead of the normal ones.

- 1 - End
- 2 - Down arrow
- 3 - Page down
- 4 - Left arrow
- 5 - (Nothing lights up)
- 6 - Right arrow
- 7 - Home
- 8 -Up
- 9 - Page up
- 0 - Insert
- Comma - Delete

(This one is always incorrect) - Enter - Lights up the enter key below backspace instead of the numpad one.

I know this is what the buttons do when num lock is off and I can understand why it happens.
If I disable Aurora and use logitechs own effect it always lights the correct keys.

**Comment by antonpup** [comment]
Nothing I can do about this problem. See #418 for more details.

But in short, Windows reports those keys are being pressed, and thus I process them as being pressed. Logitech can detect key presses on the hardware level, giving them extra key detection like the G-key, which are not part of Windows Keys.
