### ISSUE TITLE
[Feature Request] Support for K95 Platinums Light Edge

### ISSUE THREAD

**Issue by Gleydar** [antonpup/Aurora#445]
Corsairs new K95 Platinum has a Light Edge on the upper half of the keyboard. If it would be possible to support setting the color of this Edge and Corsairs logo, that would be totally amazing.

**Comment by antonpup** [comment]
The CUE SDK first needs to support this before I can add it to Aurora. I can add the layout, but I it won't be functional.

**Comment by sll552** [comment]
There was an update for the SDK and there is already a commit to CUE.NET which adds Lightbar support https://github.com/DarthAffe/CUE.NET/commit/e6719c06a8924cca9afd9491b4c26362e7bf0952

**Comment by HAL9OO0** [comment]
I just got a the K95 platinum, my first per key RGB keyboard and really love this program. It would be really  awesome if the lightbar could get supported! But anyways really great work with that program, there is more customizability than in any software I saw and is really intuitive.

**Comment by Darknites** [comment]
I just found this program and loving it so far. It would be sweet to put the light bar to use for CPU and Ram usage.

**Comment by AffableTowel** [comment]
Another voice to say that lightbar support would be really neat. Thanks for the great software!

**Comment by BetterCallConnolly** [comment]
Just another voice to say that this feature is very much desired.  I have the Corsair K95 Platinum, M65 Pro, the Polaris mousemat but a Logitech G633 Artemis.  I would love to be able to use all of these, with the light bar in the k95 platinum being supported by Aurora.

**Comment by SqugSCX** [comment]
+1

**Comment by Mistercrit** [comment]
I'm commenting to say that I would love if the K95 Platinum were now supported in Aurora. Considering it is my primary keyboard of use, and the SDK has been updated, there's no reason not to add it.

**Comment by MrReeds** [comment]
+1

**Comment by simon-wh** [comment]
I've added light edge support in the latest commit, it'll be available in the next release
