### ISSUE TITLE
Aurora using more than 2GB of my RAM :)

### ISSUE THREAD

**Issue by wEisB0145** [antonpup/Aurora#446]
### What are you experiencing an issue with?
- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?
- [ ] Crash
- [x] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Normally it should not use 2GB of my RAM, right? Or doesn't it like me?? :(

### Actual behavior:
Using too much RAM

### How often does this problem occur?
This problem occurs: well if I don't shutdown my PC for a few days

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. running your computer with aurora a few days

### What is the version of Aurora you are experiencing this issue with?
My version is Aurora 0.6.0b Beta

### Does the previous version of Aurora have this issue?
The previous version, Aurora 0.5.2 Beta , did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:
http://imgur.com/a/OKWTz
http://pastebin.com/pjj6kUmc

**Comment by antonpup** [comment]
Thank you for reporting this.

This issue is possibly related to #387 try what is mentioned there.

**Comment by wEisB0145** [comment]
Well the problem is that Ill get an error when trying to rebuild my performance counter
`Error: Unable to rebuild performance counter setting from system backup store, error code is 2` (with admin privileges)
`Error: Unable to rebuild performance counter setting from system backup store, error code is 5` (without admin privileges)

**Comment by antonpup** [comment]
I believe the issue is related to how I handle the log file. I will be changing that, so hopefully, it won't fill people's memory.

What you should try is, run Aurora as administrator, and see if that produces the same issue after a few days. If it doesn't, then my fix should work. If it does, we will investigate further.

**Comment by simon-wh** [comment]
Try v0.6.2b, should be all sorted
