### ISSUE TITLE
GTA online background not showing up for me

### ISSUE THREAD

**Issue by poundage1991** [antonpup/Aurora#447]
### What are you experiencing an issue with?

- [ ] Aurora
- [x] Aurora supported game, (GTA 5)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
When I'm on my GTA online character the background of my g910 stays green as if i was playing franklin
### Actual behavior:
Explain here what happened instead.
It should turn dark blue like the video
### How often does this problem occur?

This problem occurs... (Fill in here)
Everytime
### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Start the GTA V online mode
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (Fill in here)
beta0.6.0b
### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.
This is my first time using Aurora

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by antonpup** [comment]
I saw your comment on Youtube. At the time of the recording, I thought that online mode was green. In reality, the online mode displays the color of your crew. So if your crew color is blue, it will show blue. If your crew color is orange, it will show orange.

**Comment by poundage1991** [comment]
That makes a lot more sense. thanks for the info
