### ISSUE TITLE
Effects dont work.

### ISSUE THREAD

**Issue by PatrickJesp** [antonpup/Aurora#45]
When i open a game, i see the colours change, but dont work properly. And overwatch doesnt even change the colours. Pathced the game, but dont really know what to do.

**Comment by antonpup** [comment]
For Overwatch, look at issue #42

**Comment by antonpup** [comment]
What kind of issues were you experiencing with other profiles?

**Comment by PatrickJesp** [comment]
Tried Rocket League. The whole keyboard was just yellow and in gta, the F1-12 key didnt blink when i got the cops on me. 
- Ill take a look at 42

**Comment by antonpup** [comment]
Can you post your log?

**Comment by Titan1s** [comment]
Hey Anton excellent work, love the work you're doing. I'm having the same issue with Overwatch and couldn't find the answers in #42. Should I open another issue or piggyback on this one. 

Thanks for any help.

**Comment by PatrickJesp** [comment]
Can seem to upload the log as a file...  Please note that im not sure, that i know what im doing in the Aurora. Just downloaded it.


[INFO] 19-06-2016 00:00:36: Device, Logitech, was shutdown
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: DESKTOP-EHA9PTD
User Name: Patrick
SystemPageSize: 4096
Version: 4.0.30319.42000
========================================

[INFO] 19-06-2016 00:01:37: Device, Logitech, was initialized
[ERROR] 19-06-2016 00:01:37: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 19-06-2016 00:01:37: Device, Corsair, was not initialized
[INFO] 19-06-2016 00:01:37: No Chroma SDK available
[ERROR] 19-06-2016 00:01:37: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   ved Aurora.Devices.Razer.RazerDevice.Initialize() i d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:linje 52
[INFO] 19-06-2016 00:01:37: Device, Razer, was not initialized
19-06-2016 00:01:37: Listening for game integration calls...
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: DESKTOP-EHA9PTD
User Name: Patrick
SystemPageSize: 4096
Version: 4.0.30319.42000
========================================

[INFO] 19-06-2016 00:15:18: Program started with '-install_logitech' parameter
[INFO] 19-06-2016 00:15:18: Logitech LED SDK patched successfully
[INFO] 19-06-2016 00:28:10: Device, Logitech, was shutdown
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: DESKTOP-EHA9PTD
User Name: Patrick
SystemPageSize: 4096
Version: 4.0.30319.42000
========================================

[INFO] 19-06-2016 00:28:19: Device, Logitech, was initialized
[ERROR] 19-06-2016 00:28:19: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 19-06-2016 00:28:19: Device, Corsair, was not initialized
[INFO] 19-06-2016 00:28:19: No Chroma SDK available
[ERROR] 19-06-2016 00:28:19: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   ved Aurora.Devices.Razer.RazerDevice.Initialize() i d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:linje 52
[INFO] 19-06-2016 00:28:19: Device, Razer, was not initialized
19-06-2016 00:28:19: Listening for game integration calls...
[INFO] 19-06-2016 00:28:24: Device, Logitech, was shutdown
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: DESKTOP-EHA9PTD
User Name: Patrick
SystemPageSize: 4096
Version: 4.0.30319.42000
========================================

[INFO] 19-06-2016 00:28:31: Device, Logitech, was initialized
[ERROR] 19-06-2016 00:28:31: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 19-06-2016 00:28:31: Device, Corsair, was not initialized
[INFO] 19-06-2016 00:28:31: No Chroma SDK available
[ERROR] 19-06-2016 00:28:31: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   ved Aurora.Devices.Razer.RazerDevice.Initialize() i d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:linje 52
[INFO] 19-06-2016 00:28:31: Device, Razer, was not initialized
19-06-2016 00:28:32: Listening for game integration calls...
[INFO] 19-06-2016 00:29:11: Device, Logitech, was shutdown
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: DESKTOP-EHA9PTD
User Name: Patrick
SystemPageSize: 4096
Version: 4.0.30319.42000
========================================

[INFO] 19-06-2016 00:29:13: Device, Logitech, was initialized
[ERROR] 19-06-2016 00:29:13: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 19-06-2016 00:29:13: Device, Corsair, was not initialized
[INFO] 19-06-2016 00:29:13: No Chroma SDK available
[ERROR] 19-06-2016 00:29:13: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   ved Aurora.Devices.Razer.RazerDevice.Initialize() i d:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:linje 52
[INFO] 19-06-2016 00:29:13: Device, Razer, was not initialized
19-06-2016 00:29:14: Listening for game integration calls...
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: DESKTOP-EHA9PTD
User Name: Patrick
SystemPageSize: 4096
Version: 4.0.30319.42000
========================================

[INFO] 19-06-2016 00:36:17: Program started with '-install_logitech' parameter
[INFO] 19-06-2016 00:36:17: Logitech LED SDK patched successfully
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: DESKTOP-EHA9PTD
User Name: Patrick
SystemPageSize: 4096
Version: 4.0.30319.42000
========================================

[INFO] 19-06-2016 00:38:02: Program started with '-install_logitech' parameter
[INFO] 19-06-2016 00:38:02: Logitech LED SDK patched successfully
[INFO] 19-06-2016 00:39:41: Trying to get game path for: 730
[INFO] 19-06-2016 00:41:06: Device, Logitech, was shutdown

**Comment by PatrickJesp** [comment]
The # 42 doesnt seem to fix the problem.

**Comment by antonpup** [comment]
Do you have both x64 and x86 versions of Visual Studio C++ 2015 redistributable installed?

It seems that games are not using the wrapper to communicate with Aurora.

**Comment by PatrickJesp** [comment]
Yes, i just installed both, and tried overwatch again.  Please note that im not even sure, that i've installed it correctly.  I was told to download a folder called Aurora-master, but i dont whats its for. :P

**Comment by antonpup** [comment]
Ok. I will look at this issue after I finish the profile import/export.

**Comment by smh51** [comment]
same here : 
rocket league display unique background color when the game start, but doesn't display team/boost colors when playing.

I was playing cs:go before 

logs below : 
[ERROR] 19/06/2016 09:39:46: Exception during OnNewGameState. Error: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: T. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   à Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   à Aurora.Profiles.Node..ctor(String json_data) dans d:\Repositories\Git\Aurora\Project-Aurora\Profiles\Node.cs:ligne 14
   à Aurora.Profiles.CSGO.GSI.Nodes.RoundNode..ctor(String JSON) dans d:\Repositories\Git\Aurora\Project-Aurora\Profiles\CSGO\GSI\Nodes\RoundNode.cs:ligne 14
   à Aurora.Profiles.CSGO.GSI.GameState_CSGO.get_Round() dans d:\Repositories\Git\Aurora\Project-Aurora\Profiles\CSGO\GSI\GameState_CSGO.cs:ligne 54
   à Aurora.Profiles.CSGO.GameEvent_CSGO.UpdateLights(EffectFrame frame, GameState new_game_state) dans d:\Repositories\Git\Aurora\Project-Aurora\Profiles\CSGO\GameEvent_CSGO.cs:ligne 459
19/06/2016 09:39:46: {
	"provider": {
		"name": "Counter-Strike: Global Offensive",
		"appid": 730,
		"version": 13538,
		"steamid": "76561198159562481",
		"timestamp": 1466321986
	},
	"player": {
		"steamid": "76561198159562481",
		"name": "-smH*",
		"activity": "menu"
	},
	"previously": {
		"map": true,
		"round": true,
		"player": {
			"steamid": "76561198185205659",
			"name": "Kobefuki",
			"team": "CT",
			"activity": "playing",
			"state": {
				"health": 34,
				"armor": 96,
				"helmet": true,
				"flashed": 0,
				"smoked": 0,
				"burning": 0,
				"money": 2900,
				"round_kills": 1,
				"round_killhs": 0
			},
			"weapons": {
				"weapon_0": {
					"name": "weapon_knife_push",
					"paintkit": "am_zebra",
					"type": "Knife",
					"state": "holstered"
				},
				"weapon_1": {
					"name": "weapon_hkp2000",
					"paintkit": "default",
					"type": "Pistol",
					"ammo_clip": 13,
					"ammo_clip_max": 13,
					"ammo_reserve": 52,
					"state": "holstered"
				},
				"weapon_2": {
					"name": "weapon_m4a1",
					"paintkit": "cu_m4a4_evil_daimyo",
					"type": "Rifle",
					"ammo_clip": 30,
					"ammo_clip_max": 30,
					"ammo_reserve": 37,
					"state": "active"
				}
			},
			"match_stats": {
				"kills": 10,
				"assists": 4,
				"deaths": 8,
				"mvps": 0,
				"score": 26
			}
		}
	}
}
[ERROR] 19/06/2016 10:02:59: Exception during OnNewGameState. Error: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: T. Path '', line 0, position 0.
   à Newtonsoft.Json.JsonTextReader.ParseValue()
   à Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   à Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   à Aurora.Profiles.Node..ctor(String json_data) dans d:\Repositories\Git\Aurora\Project-Aurora\Profiles\Node.cs:ligne 14
   à Aurora.Profiles.CSGO.GSI.Nodes.RoundNode..ctor(String JSON) dans d:\Repositories\Git\Aurora\Project-Aurora\Profiles\CSGO\GSI\Nodes\RoundNode.cs:ligne 14
   à Aurora.Profiles.CSGO.GSI.GameState_CSGO.get_Round() dans d:\Repositories\Git\Aurora\Project-Aurora\Profiles\CSGO\GSI\GameState_CSGO.cs:ligne 54
   à Aurora.Profiles.CSGO.GameEvent_CSGO.UpdateLights(EffectFrame frame, GameState new_game_state) dans d:\Repositories\Git\Aurora\Project-Aurora\Profiles\CSGO\GameEvent_CSGO.cs:ligne 459
19/06/2016 10:02:59: {
	"provider": {
		"name": "Counter-Strike: Global Offensive",
		"appid": 730,
		"version": 13538,
		"steamid": "76561198159562481",
		"timestamp": 1466323379
	},
	"player": {
		"steamid": "76561198159562481",
		"name": "-smH*",
		"activity": "menu"
	},
	"previously": {
		"map": true,
		"round": true,
		"player": {
			"team": "CT",
			"state": {
				"health": 66,
				"armor": 95,
				"helmet": true,
				"flashed": 0,
				"smoked": 0,
				"burning": 0,
				"money": 10000,
				"round_kills": 0,
				"round_killhs": 0
			},
			"weapons": {
				"weapon_0": {
					"name": "weapon_knife",
					"paintkit": "default",
					"type": "Knife",
					"state": "holstered"
				},
				"weapon_1": {
					"name": "weapon_hkp2000",
					"paintkit": "default",
					"type": "Pistol",
					"ammo_clip": 13,
					"ammo_clip_max": 13,
					"ammo_reserve": 52,
					"state": "holstered"
				},
				"weapon_2": {
					"name": "weapon_p90",
					"paintkit": "default",
					"type": "Submachine Gun",
					"ammo_clip": 48,
					"ammo_clip_max": 50,
					"ammo_reserve": 100,
					"state": "active"
				}
			},
			"match_stats": {
				"kills": 6,
				"assists": 4,
				"deaths": 8,
				"mvps": 0,
				"score": 16
			}
		}
	}
}

**Comment by antonpup** [comment]
For Rocket League, I will probably need to update the pointers. It will come as a minor update, for most users this will be applied automatically.

As for Overwatch not working, add me on Steam and I will debug it with you personally.[http://steamcommunity.com/id/pupant/](http://steamcommunity.com/id/pupant/) (Please comment on my profile before adding me, as I have a lot of pending friend requests)
