### ISSUE TITLE
Game detection not working in latest code

### ISSUE THREAD

**Issue by gradius-v** [antonpup/Aurora#450]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [x] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, (Game detection not working)

### Expected behavior:
game should be detected

### Actual behavior:
it isn't

### How often does this problem occur?
Every time

### What is the version of Aurora you are experiencing this issue with?
latest code

### Does the previous version of Aurora have this issue?
latest release works

### Please include any logs, screenshots, or files that are related to this issue:
http://pastebin.com/RHjxVEhc

**Comment by antonpup** [comment]
Related to #430 It's a known issue, we're not entirely sure why it broke. But we have merged @r3sist3nt 's fix on dev branch, hopefully, it is more stable.
