### ISSUE TITLE
Equalizer Layer not working with MusicBee

### ISSUE THREAD

**Issue by sll552** [antonpup/Aurora#451]
### What are you experiencing an issue with?
- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?
- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, Equalizer Layer does not pick up audio playing via MusicBee

### Expected behavior:
Equalizer Layer working normally when playing music through MusicBee

### Actual behavior:
Nothing happens when sound is produced by MusicBee. It works fine with other sources like a Youtube video in Chrome or VLC.

### How often does this problem occur?
Every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Start Aurora as admin with a profile that has an active Equalizer Layer
2. Start playing music with MusicBee

### What is the version of Aurora you are experiencing this issue with?
My version is 0.6.0b

### Does the previous version of Aurora have this issue?
Don´t know

### Please include any logs, screenshots, or files that are related to this issue:

I tried running Aurora without admin but then nothing is working. Then I tried switching the output in MusicBee from WASAPI to DirectSound which did not help either. I could not see any error or stacktrace in the logs.

**Comment by sll552** [comment]
Hi,
I don't know what might have fixed it but after restarting my PC with Aurora on autorun, it works now.

The only thing I don't really understand is how the ignored processes work in the settings. I created a profile for MusicBee and added "chrome.exe" to the excluded processes in the settings. I expected Aurora now to ignore a foreground chrome browser when I open it over MusicBee. This way I wanted to have the Equalizer layer to be active only if chrome is opened over MusicBee and to be inactive when I start some other program. But if I now open chrome the lighting just freezes instead of either switching to the desktop profile or continuing with the MusicBee profile.

**Comment by simon-wh** [comment]
@sll552 The excluded process option in the current stable release I think is intended to stop lighting when that application is in the foreground and probably return it to the default lighting (CUE, LGS, etc). However, in the current dev stuff it doesn't really do anything significant (which I'm going to fix). Aurora detects applications based on the foreground window, it doesn't do anything like ignoring the foreground window if it is excluded and finds the next one.
