### ISSUE TITLE
Corsair K70 not initialized

### ISSUE THREAD

**Issue by Tenns** [antonpup/Aurora#453]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [x] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
It should detect my corsair K70 RGB and say connected in the settings.

### Actual behavior:
Explain here what happened instead.
It doesn't detect my K70 and says not initialized in the settings.

### How often does this problem occur?

This problem occurs... Every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. launch aurora?
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... beta v0.6.0b

### Does the previous version of Aurora have this issue?
The previous version, 0.5.x, did have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/YXbLkW8U
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by brainbug89** [comment]
`[ERROR] 15/02/2017 14:56:31: Corsair device, CUE Exception! ErrorCode: ServerNotFound`

Is CUE2 running? Are you using the latest CUE2 version (2.9)? Is SDK at CUE2 settings enabled? If yes to all: try reinstalling CUE2.

**Comment by Tenns** [comment]
@brainbug89 Already reinstalled, and i just did it again but still doesn't work...

**Comment by Tenns** [comment]
I found the problem, CUE needs to be running...
