### ISSUE TITLE
Certain Keys Not Lighting Up

### ISSUE THREAD

**Issue by BlurpyxD** [antonpup/Aurora#454]
### What are you experiencing an issue with?

- [x] Aurora

### What kind of an issue is it?

- [x] Visual bug

### Expected behavior:
The keys should light up with the selected effects.

### Actual behavior:
The keys stay dark 100% of the time

### How often does this problem occur?
Every time

### What is the version of Aurora you are experiencing this issue with?
My version is beta v0.6.0b

### Does the previous version of Aurora have this issue?
The previous version did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:
http://imgur.com/OKuT7gF
http://imgur.com/XqDDteh

**Comment by brainbug89** [comment]
Layout of keyboard and Aurora aren't the same. Did you choose the correct layout at Settings > Devices & Wrappers > Preferred Keyboard Layout?

**Comment by BlurpyxD** [comment]
I did, already fixed it though, some kind of file was preventing my changes in the program to apply irl
