### ISSUE TITLE
Deathadder Not Doing Chroma Lighting Effects in Overwatch

### ISSUE THREAD

**Issue by drkpie** [antonpup/Aurora#455]
I searched on here but didn't find a solution, I'm sorry if I missed it.

### What are you experiencing an issue with?

- [ ] Aurora
- [X] Aurora supported game, (Overwatch)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:

Normally when you open Overwatch it'll do the Chroma lighting effects and it'll change the colour to the hero you play. It stopped doing this a little while ago, but my keyboard (K70 RGB) is still able to do the colour effects. I have patched Overwatch, Synapse, etc., and have done so every time there's an update. I also have Aurora enabled under Chroma Apps in Synapse.

### Actual behavior:

The mouse stopped doing the Chroma lighting effects a little while ago, but my keyboard (K70 RGB) is still able to do the colour effects. I have patched Overwatch, Synapse, etc., and have done so every time there's an update.

### How often does this problem occur?

This problem occurs every time.

### Please describe the steps to reproduce this issue:

The issue can be reproduced by doing following steps:

1. Opening Overwatch, you'll see the keyboard change to orange which is correct, but the mouse will continue to cycle through colours instead of changing orange as well. 

### What is the version of Aurora you are experiencing this issue with?

My version is beta v0.6.0b

### Does the previous version of Aurora have this issue?

The previous version, (I'm not sure, I think it was 0.5.2 beta), did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

Did a reinstall of Aurora to see if that would help, it didn't, I opened the log file and it's blank so that's why there's no log file in this section right now.

**Comment by antonpup** [comment]
Works on dev branch with G910 mouse. I'll run current public version to see if I can replicate the issue there.

**Comment by drkpie** [comment]
That was a pretty quick response haha, thank you, let me know if I'm just being dumb somewhere!

**Comment by antonpup** [comment]
Likewise, works on 0.6.0b.

Have you selected a mouse in the settings? You can select any, it should work.

**Comment by drkpie** [comment]
I didn't know you could select any mouse, I just did and it works. Thank you so much!
