### ISSUE TITLE
After checking "Disable Headset Lighting" the headset lighting is still on.

### ISSUE THREAD

**Issue by Mavi222** [antonpup/Aurora#456]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (Logitech G933)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Checking the "Disable headset lighting" should disable headset lighting
### Actual behavior:
The Headset lighting doesn't get disabled. It is still on.

### How often does this problem occur?

This problem occurs every time.
### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Checking the "Disable headset lighting" in the Devices & Wrappers settings
2. Looking at the headset if it the lighting is disabled.

### What is the version of Aurora you are experiencing this issue with?

My version is... v0.6.0b

### Does the previous version of Aurora have this issue?
I am not sure if it did do that in the previous version. I don't want to try to downgrade the Aurora at the moment. If you will need me to downgrade and test it for you, I will do it for sure!

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by Running-Banana** [comment]
What headset do you have? If it is logitech, the logitech SDK is so limited that you will have to check "Disable Mouse Lighting" for it to disable both.

**Comment by Mavi222** [comment]
Hmm, that's weird, I think I already tried to do that and it didn't work, but now when I tried it again it works with "Disable Mouse Lighting" also checked. Thanks a lot! I didn't mind the mouse colors anyway!
