### ISSUE TITLE
Not working in games, only on desktop

### ISSUE THREAD

**Issue by vinochino** [antonpup/Aurora#458]
Hi guys,

Installed Aurora per web installer exe and its working fine on the desktop. But ich can't get it to work in games. Tested with Overwatch, GTA V and on both games I don't get anything triggered. In GTA the keyboard (logitech g910) turns white but that's it, no siren color if im wanted or such. When Overwatch starts it becomes completely black ( lights off) and nothing will ever trigger any color or ability. Here is my log file : http://pastebin.com/LZXGwKfq

Of course I installed all SDK patches for Overwatch and Logitech. Game detection seems to work because the keyboard becomes "black" if I start OW e.g. But not the Keypresses or ability indicators.
I tried to run as Admin and also deleted all Appdata folder and did a clean install. Nothing changed.

Could you please help me , I don't now what else I can do now.
Thanks!

**Comment by antonpup** [comment]
The wrappers aren't making a connection with Aurora. Make sure that you are installing the wrapper patches in the correct location. And make sure that you have [Visual C++ Redistributable for Visual Studio 2015
](https://www.microsoft.com/en-us/download/details.aspx?id=48145) installed (both vc_redist.x64.exe and vc_redist.x86.exe, repair if already installed).

If that fails, run Aurora and the game in question both as admin.

**Comment by vinochino** [comment]
Hey thanks for your reply,

I checked and repaired all Visual C++ packages and that did it. Strange because I've never had problems with this. Thanks a lot it's now working as intended.
