### ISSUE TITLE
W10 reports "Aurora-updater Stopped working"

### ISSUE THREAD

**Issue by Iruberiam** [antonpup/Aurora#459]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [x] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.

### Actual behavior:
Explain here what happened instead.

### How often does this problem occur?

This problem occurs... (Every time check for updates is clicked)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Click "Check for updates" in aurora
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (v0.6.0b)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.
These errors only started on the 2nd of Feb.  I don't know what version it was before.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

http://pastebin.com/hm6zysYc

**Comment by antonpup** [comment]
It's been fixed on dev branch a few days ago. https://github.com/antonpup/Aurora/commit/495ca9d4d3c24423762638bf45900d8b91f53a52

**Comment by Iruberiam** [comment]
That's great thank you.  I did a search but didn't find a related issue.
