### ISSUE TITLE
Color effects the Division

### ISSUE THREAD

**Issue by Matzebhv** [antonpup/Aurora#46]
I'm not shure how to setup logitech software corectly to make "the Division" work. 
Logitech has an Profile for this game, which loads on start. No additional lightning effects will happen.
Also, if shortcut assistant is enabled, pressing left STRG key ( which is mapped by default ) will make the loaded Profile stop working, lights went off.
Anyway, excellent work. Dota and Overwatch worked like a charme.
Device: Logitech G910@Win10_64

**Comment by smh51** [comment]
Did you activate the feature in the game settings ?
settings -> 3rd party

**Comment by antonpup** [comment]
You will have to provide me with more info about The Division. Have you enabled the "3rd party lighting" like @smh51 mentioned? Does The Division have any performance issues? As for LGS profile, remove it, LGS will ALWAYS override whatever lighting it can.

**Comment by Matzebhv** [comment]
Hi, sorry for my late reply.
Yes, 3rd Party lightning is enabled. 
If i disable LGS Profile absolutly no light comes up. 
You have 2 settings in LGS -> One like you describe for Dota / CSGO ( do i have to dis or enable arx control / LED backlightnig here?) and one in the division profile.
Have tried every combination, won't work.
BTW, LGS sucks totally wont't save my settings correctly on reboot.
And no, performance is o.k.

**Comment by antonpup** [comment]
Do you have GTA 5? Does lighting work with that?

If it doesn't work, you can add me on Steam. To debug this further. [http://steamcommunity.com/id/pupant/](http://steamcommunity.com/id/pupant/), just make sure to comment on my profile so I know who to add.

**Comment by antonpup** [comment]
Did your manage to resolve your issue?
