### ISSUE TITLE
Option for disabled apps to return to default lighting similar to desktop

### ISSUE THREAD

**Issue by lowensodium** [antonpup/Aurora#460]
### What are you experiencing an issue with?

- [x ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [x ] Aurora Wrapper
- [ ] Aurora Profile
- [ x] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [x ] Enhancement suggestion
- [x ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.

Profiles that are set to not "Enable Aurora to provide lighting effects with this profile" do not disable the desktop profile if there is one running.  I would expect them to.

### Actual behavior:
Explain here what happened instead.

This particular instance is probably specific to Corsair keyboards and games that support more than 1 API like Diablo 3.

Diablo 3 supports both Razer and Corsair control natively.  While using a Corsair keyboard, starting Diablo 3 with or without a profile for it does not work for light control.  Disabling Aurora works correctly.

I think Diablo 3 is trying to prefer the Corsair CUE api over the Razer Chroma API.  If Aurora is is running a desktop profile, I think it prevents Diablo 3 form controlling the CUE api.

If I disable the Desktop profile, Diablo 3 is able to control the keyboard as I would expect.

I think this issue would be resolved if there was an option in a profile to disabled aurora Desktop Profile and disable Aurora lighting effects.

Right now, if I disable the desktop profile manually, and have a profile for Diablo 3 that is set to NOT enable Aurora, it works correctly.

### How often does this problem occur?

This problem occurs... everytime

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1.  enable a desktop profile
2.  create profile for Diablo 3 that is set to Not enable Aurora
3.  Launch Diablo 3

### What is the version of Aurora you are experiencing this issue with?

My version is... (beta v0.6.0b)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by brainbug89** [comment]
Did you patched Diablo 3 with the Aurora wrapper? Diablo 3 needs to be patched to be able to send lighting information to Aurora.

And yes, if you enable the Desktop mode, Aurora controlling the keyboard lighting. I don't know how CUE SDK handles more then one app at the same moment.

> 2. create profile for Diablo 3 that is set to Not enable Aurora

This option just disable the game mode, so Aurora will using the Desktop mode (if Desktop mode wasn't disabled).

**Comment by lowensodium** [comment]
Yes, the Aurora Wrapper dlls files are in the diablo 3 dir.  I am not 100% sure, but I think that Diablo 3 is only using the Corsair API if it detects it, even if the Razer dlls are present.  Shutting down the desktop profile while Diablo 3 is running instantly turns control of the Keyboard's light over to the game.

> This option just disable the game mode, so Aurora will using the Desktop mode (if Desktop mode wasn't disabled).

Correct.  There is no way for a profile to disable the desktop profile unless there is another profile  you are enabling.  If there was, I could just let Diablo 3 take control by having a profile that disabled the desktop profile when it detected Diablo 3 was running.

**Comment by lowensodium** [comment]
I guess what I am saying is that this is a feature request to allow profiles to be able to disable the desktop profile without needing to enable another profile.

**Comment by simon-wh** [comment]
Am I special or something? This has been in for ages with the "Excluded processes" option in settings which returns the devices to default lighting the apps in the list are in the foreground
