### ISSUE TITLE
Overwatch Effect Customization?

### ISSUE THREAD

**Issue by Rocket-Scientist2** [antonpup/Aurora#461]
### What are you experiencing an issue with?

- [ ] Aurora
- [x] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, (Customization)

### Expected behavior:
Hoping to be able to change effect colours, put layers underneath effects, etc.

### Actual behavior:
Any layers seem to overwrite Overwatch effects, unable to change colour of provided effects.

### How often does this problem occur?

This problem occurs... Everytime

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Open Overwatch tab
2. Add fill layer
3. Stretch across entire keyboard

### What is the version of Aurora you are experiencing this issue with?

My version is... v0.6.0b

![image](https://cloud.githubusercontent.com/assets/15883173/23110681/b9c21894-f6e8-11e6-99af-b4ec237c523c.png)

**Comment by brainbug89** [comment]
The Overwatch effects are controlled by Overwatch and not by Aurora. Only Overwatch devs can change them.

**Comment by Rocket-Scientist2** [comment]
Ah ok, makes sense.

**Comment by simon-wh** [comment]
I suppose it may be a helpful addition to be able to put layers above and below the lights from the wrapper/game. I'll look into adding this for the next version.

**Comment by simon-wh** [comment]
I've completed the feature I mentioned above which will be available in the next development release.
