### ISSUE TITLE
Aurora bugging out when turning on with Logitch 910 

### ISSUE THREAD

**Issue by MattPacheco1234** [antonpup/Aurora#462]
### What are you experiencing an issue with?

- [X] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [X ] Other, (Fill in another type of issue here)

### Expected behavior:
Trying to use Aurora, turn it on and use

### Actual behavior:
Aurora tries to work, Using a logitch 910 and the logitech software is changing the colour to green and bugging out the Aurora. It tries to work, sometimes Aurora is controlling 80% of my keyboard (with aurora colours are set to blue) and logitech gaming software is bugging it green some keys 

### How often does this problem occur?
Very rarely it works fine, 99% of the time it does a described 

### Please describe the steps to reproduce this issue:

1. Turing on Aurora 
2. ...
3. ....

### What is the version of Aurora you are experiencing this issue with?
0.6.0b
### Does the previous version of Aurora have this issue?
Maybe once

### Please include any logs, screenshots, or files that are related to this issue:
http://pastebin.com/PVwBZxgV

**Comment by antonpup** [comment]
I was told that if you have an effect in LGS enabled, or if you have an interactive effect set in LGS. Then LGS will override the SDK calls.

Please disable any effects and try again. If that doesn't help, reinstall LGS.

**Comment by MattPacheco1234** [comment]
So i found that it was an issue with a profile called Riot Rainbows, i dont know whats causing the issue but i go back to default profile everything works fine
