### ISSUE TITLE
Flashing random colors on right ctrl and left alt while pressing left alt with interactive layer.

### ISSUE THREAD

**Issue by pitek1** [antonpup/Aurora#464]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [x] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Using the interactive layer feature the left alt button should, like others, light once on the key press.

### Actual behavior:
The left alt button started a "disco", interestingly, with the right ctrl button at the same time. All other buttons behave normally.

### How often does this problem occur?
This problem occurs...  every time I press alt.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

0. Using Corsair K70 RGB LUX
1. Set interactive layer with random colours.
2. Long press the left alt button.
3. DISCO!

### What is the version of Aurora you are experiencing this issue with?

My version is... 0.6.0b

### Does the previous version of Aurora have this issue?
The previous version, did not have this issue.

**Comment by antonpup** [comment]
I am assuming that your left Alt is actually an Alt Grave, used on foreign keyboard layouts. Windows treats Alt Gr as Alt+CTRL, so there's little I can do to detect it.

**Comment by brainbug89** [comment]
If you mean right Alt (Alt Gr) (like described at #311 ), see: https://github.com/antonpup/Aurora/issues/385#issuecomment-273242579 Windows detects rapidly pressed Ctrl and Alt keys while pressing Alt Gr.

**Comment by pitek1** [comment]
Ok, thank you for your response.
