### ISSUE TITLE
[Request] Key Color Toggle

### ISSUE THREAD

**Issue by Crosmanairsoft** [antonpup/Aurora#465]
Could you add the same functionality as the "Lock Color Layer" to any other key? I would like the ability to use the same kind of lighting toggle functionality to the Windows lock key on my Corsair K95. Thanks in advance!

**Comment by antonpup** [comment]
Windows doesn't offer a way detect any other "lock" keys. The win-lock or input-lock keys offered by keyboard manufacturers are not part of the Windows SDK. Thus, I do not have access to their "states".
