### ISSUE TITLE
Problem with Aurora at startup with Razer Blackwidow chroma.

### ISSUE THREAD

**Issue by Nedo93** [antonpup/Aurora#466]
### What are you experiencing an issue with?

- [x ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x ] Other, (Startup problem)

### Expected behavior:
Aurora should start setting my lightning profile, overlying Razer's Synapse profile.

### Actual behavior:
It will setup my profile (for example a fully red keyboard) but the layers are overlied by Razer Synapse's layer in an intermittent and discontinuos way. For a fraction of second it will show Aurora's layer, and for another fraction, it will show Synapse's layer continuosly.

### How often does this problem occur?

This problem occurs... (sometimes)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Create a lightning profile
2. Save the profile
3. Restart pc and wait untill Aurora is fully started

### What is the version of Aurora you are experiencing this issue with?

My version is... (v0.6.0b)

### Does the previous version of Aurora have this issue?
The previous version, I'm not really sure which was, but it didn't have this issue, although it wouldn't load profiles correctly.

### Please include any logs, screenshots, or files that are related to this issue:

Log: http://pastebin.com/LVBVt92f

**Comment by antonpup** [comment]
I don't have a Razer keyboard to replicate this. But it sounds like an issue with Razer SDK, which is outside of Aurora's scope. Report this to Razer, if you can.

**Comment by Nedo93** [comment]
But it's really strange because I recently formatted my pc and with previous windows installation, with same aurora and Synapse version, there were no problems. 
It's nothing too annoying considering that when it happens, if I just close Aurora from Task manager and restart it, the problem will not occur again, was just to know if this was a known bug.
