### ISSUE TITLE
Aurora wont update Equalizer when changing Audio Output in soundcard driver options

### ISSUE THREAD

**Issue by Bionicle06** [antonpup/Aurora#468]
### What are you experiencing an issue with?
- [x] Aurora Lighting issue
- [x] Other, (I have a soundcard where i can switch between my speakers (connected directly to the soundcard) and my headphones (connected to the front audio jack)

### What kind of an issue is it?
- [x] Visual bug
- [x] Other, (Equalizer profile wont update anymore and is stuck with the last audio that was played when i change the audio output)

### Expected behavior:
The equalizer profile shouldn't stop working when i switch between them.

### Actual behavior:
When i change from speakers to headphones the equalizer profile won't get the sound anymore and is stuck with the last audio signal (screenshot will explain it better, i guess), i need to restart Aurora to get it working again. 

### How often does this problem occur?
It occurs when i switch between speakers and headphones e.g. for playing csgo or something

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:
(I have a Sound Blaster Z soundcard and there i can switch between speakers and headphones.

1. Aurora is started, and there is an equalizer profile activated
2. Hearing any music or a video 
3. Switch between speakers and headphones, if your soundcard has a option like mine.

### What is the version of Aurora you are experiencing this issue with?
My version is the latest one v0.6.0b.

### Please include any logs, screenshots, or files that are related to this issue:
[Music is on, Audio Output on Speakers](http://imgur.com/a/Oqsi7)
[Music is off, Audio Output changed to Headphones, Equalizer is stuck](http://imgur.com/a/JiWep)

**Comment by antonpup** [comment]
I am pretty sure that on dev branch, I made it detect currently active sound source and switch to it. I'll double check later.

**Comment by Bionicle06** [comment]
Okay, sorry for the duplicate. It wasn't fixed in the newest version, it seemed a bit more bugged in general but i think that was my fault. The booth versions act mostly the same.

**Comment by simon-wh** [comment]
Try v0.6.2b, closing for now
