### ISSUE TITLE
Temperature Display

### ISSUE THREAD

**Issue by jdubnz** [antonpup/Aurora#469]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [x] Other, (Enhancement)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [x] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

Is it possible to get the keyboard to display CPU and GPU temperature like it does usage? or Fan speed?

**Comment by Ghanigan** [comment]
I feel like this could be possible through Open Hardware Monitor? (http://openhardwaremonitor.org/)

**Comment by brainbug89** [comment]
See #303 and #68 maybe ask @VoronFX he has some nice scripts already: https://github.com/antonpup/Aurora/issues/149#issuecomment-269305453

**Comment by VoronFX** [comment]
Definitely possible, but not yet build in. It will take some time to implement and right now I am too lazy and have other things to do. So I am not contributing at the moment. Maybe someone else will find time and will for this. Or I will contribute again after some break (I hope I will).
IMHO: I consider temp and fan speed as pretty useless values in compare to load. They are auto managed by system and they does no impact except extremely high values. On the other side they may display whether you ready to fry eggs with your PC or no.

**Comment by brainbug89** [comment]
> They are auto managed by system and they does no impact except extremely high values. On the other side they may display whether you ready to fry eggs with your PC or no.

Not at mine. I like to observe the temps to know wheter I need to adjust my water cooling system. :wink:

**Comment by antonpup** [comment]
> On the other side they may display whether you ready to fry eggs with your PC or no.

I absolutely love cooking up eggs or heating up my coffee on my FX8320.

But anyway, I am not opposing the idea of adding this. Adding this won't be difficult anyway.

**Comment by jdubnz** [comment]
Had a play with some of the scripts @VoronFX wrote. Great work. I want to use this on my G810, but obviously I'm missing the Macro G keys.

How should I change the script to get the CPU cores to be represented by the: NumLock   /   *   - keys? 
Cheers!

**Comment by VoronFX** [comment]
@jdubnz , change these lines
``` CSharp
private readonly DeviceKeys[] cpuCoresKeys = 
{ DeviceKeys.G6, DeviceKeys.G7, DeviceKeys.G8, DeviceKeys.G9 };
```
to
``` CSharp 
private readonly DeviceKeys[] cpuCoresKeys =
{ DeviceKeys.NUM_LOCK, DeviceKeys.NUM_SLASH, DeviceKeys.NUM_ASTERISK, DeviceKeys.NUM_MINUS };
```

**Comment by jdubnz** [comment]
Thanks! Working great :)
