### ISSUE TITLE
Mouse and headset functionality?

### ISSUE THREAD

**Issue by wdellanoce** [antonpup/Aurora#470]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Went to set up my mouse to use Aurora (Razer Deathadder) and headset (Razer Man o War) But no option is available. Is this functionality available? if not I will disregard.

### Actual behavior:
No option to select it..

### How often does this problem occur?
All the time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

### What is the version of Aurora you are experiencing this issue with?

My version is... (Aurora v0.6.0b)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by antonpup** [comment]
You can select any mouse, and it will work.
