### ISSUE TITLE
Custom profile for call of duty black ops 3 doesn't work

### ISSUE THREAD

**Issue by eliyameri** [antonpup/Aurora#472]
I made a custom profile that is supposed to run when the BO3 exe is open, with only specific keys lit up. When I go into the game it doesn't activate, but rather seems to be using the default razer chroma features (like the keyboard going red when you're shot). Is there a way to like skip that and use my own profile instead? Right now i'm using a workaround to setup a profile in the desktop mode and then activating that when I'm in the game but i'd rather have it happen automatically.

**Comment by simon-wh** [comment]
The default razer chroma features should only appear if you've patched the game. In which case you could remove the patch. However, I think now in the [latest development releases](https://github.com/antonpup/Aurora/releases) the custom profile should display instead of the wrapper lighting.

**Comment by simon-wh** [comment]
@eliyameri Can you try what was mentioned above?
