### ISSUE TITLE
Skyrim not recognised

### ISSUE THREAD

**Issue by TristanSchaaf** [antonpup/Aurora#474]
### What are you experiencing an issue with?
- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [X? ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [X] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
When I made new profile linked to the program "TESV.exe" I expect it to activate when TESV.exe is started, or at least the active window.

### Actual behavior:
The profile never activates

### How often does this problem occur?
All the time. But as far as I can tell only with TESV

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1.  Make a profile, assigned to skyrim
2.  Give it any layer
3.  Test and fail

### What is the version of Aurora you are experiencing this issue with?
V0.6.0b

### Does the previous version of Aurora have this issue?
I have no previous version, nor ever had.

Also, sidenote, is it possible to copy layers or day/night? Haven't found it...
Tried running TESV with and without SKSE and with and without the help of Mod Organizer.

**Comment by RancidHyena** [comment]
I added SKSE to Aurora, but there was no change. When I used TESV.exe it worked. Are you using Logitech Gaming Software? My old LGS profile was fighting with it, but after disabling the LGS profile for Skyrim the profile I used on Aurora worked fine.

**Comment by antonpup** [comment]
It's possible that you are running Aurora as a regular user and Skyrim as administrator. Processes running as non-admin do not have permissions to look at details of admin running processes. Try running Aurora as admin.

**Comment by TristanSchaaf** [comment]
Running Aurora as Admin works. Haven't thought about that. Thanks!
