### ISSUE TITLE
Ambilight in game (The Forest) only works in window mode

### ISSUE THREAD

**Issue by Filterz** [antonpup/Aurora#475]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x ] Aurora Lighting issue
- [x ] Other, (AmbiLight)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x ] Other, (Not sure)

### Expected behavior:
Ambilight should be working in fullscreen.

### Actual behavior:
Ambilight works only in window mode.

### How often does this problem occur?

This problem occurs... (Every Time)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

While playing around with the game "The Forest" and setting up lights, i added the ambilight layer.
Unfortenetly Ambilight works only in window mode. If i start the game in fullscreen its not working. I tried different settings. The problem remains the same. Not sure what im doing wrong. 

Settings:
Ambilight Effect Type: Default
Ambilight Capture Type: Main Monitor only

### What is the version of Aurora you are experiencing this issue with?

My version is... (v.0.6.0b)

**Comment by Dlaw2017** [comment]
I'm having the same issue with Grid. Not sure what's going on.

**Comment by antonpup** [comment]
Ambilight does not work with DirectX (or fullscreen) applications. Thus you are able to get Ambilight working while in borderless mode.
