### ISSUE TITLE
UDP broadcast storm on network

### ISSUE THREAD

**Issue by n1zzo** [antonpup/Aurora#476]
Hi,
I've just noticed that when I open aurora it starts sending a lot of UDP packets all over the network.
I'm running Aurora 0.6.0b Beta on Windows 10.
I have attached a wireshark capture of the phenomenon.
Please let me know if I can provide some more information.

### What are you experiencing an issue with?
- [x] Aurora
- [x] Aurora Updater

### What kind of an issue is it?
- [x] Other, Network issue

### Expected behavior:
The application should not broadcast continuously on the network.

### Actual behavior:
Explain here what happened instead.

### How often does this problem occur?
This problem occurs...every time the software is running, even when it is docked.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Open up aurora.

### What is the version of Aurora you are experiencing this issue with?
My version is... beta v0.6.0b

### Does the previous version of Aurora have this issue?
The previous version, 0.5.1d, did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:
This is a wireshark capture of the packet sent by aurora.
[auroracapture.zip](https://github.com/antonpup/Aurora/files/818683/auroracapture.zip)

**Comment by brainbug89** [comment]
Already fixed at develop branch, see #423 #395 #342

**Comment by antonpup** [comment]
Thank you for the report, but like @brainbug89 already said, it's been fixed on dev. Should be fixed next version.
