### ISSUE TITLE
Paragon

### ISSUE THREAD

**Issue by TSGcrafter** [antonpup/Aurora#478]
### What are you experiencing an issue with?

- [ ] Aurora
- [x] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [x] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

**Comment by TSGcrafter** [comment]
Paragon is a very fastly growing game by Epic, it currently has about 4 Million active players, so you have a big target audience, and they feature peole that develop for Paragon or make fanart on the menu screen. 

And: This is an awesome project, please keep it up! 😄 Hope you have a wonderful day

**Comment by fero666** [comment]
+1

**Comment by simon-wh** [comment]
There doesn't appear to be any realistic way to add support for this. Closing until plausible. You can make a generic profile for it to show stuff like shortcuts, but you won't be able to make changes based on the current in-game information.
