### ISSUE TITLE
ASUS Aura Support

### ISSUE THREAD

**Issue by TSGcrafter** [antonpup/Aurora#480]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [x] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

Support for Asus Aura would be great, so you can sync your PC with your peripherals

**Comment by antonpup** [comment]
I do not have an Aura supported motherboard, so someone else will have to add support for it.

**Comment by brainbug89** [comment]
See #329 Asus Aura doesn't have an API/SDK

**Comment by simon-wh** [comment]
Duplicate, closing

**Comment by DavidEdberg** [comment]
A SDK is in early beta now
https://www.asus.com/campaign/aura/ae-en/SDK.html
