### ISSUE TITLE
Corsair MM800 Functionality

### ISSUE THREAD

**Issue by wdellanoce** [antonpup/Aurora#481]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
 I should be able to set up my Corsair MM800 RGB POLARIS Gaming Mouse Pad  to sync with my Keyboard and mouse.
### Actual behavior:
Explain here what happened instead.
I see no option to set it, and when I turn on SDK, it turns off the lights. I also do not see an option to install a Corsair Wrapper as I did with Logitech and Razer.
### How often does this problem occur?

Every Time
### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. 
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (Fill in here)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by antonpup** [comment]
If you select any mouse, it will work.

**Comment by simon-wh** [comment]
I'm going to use this issue for proper mousepad lighting support (i.e having an extra option to select the mousepad)

**Comment by brainbug89** [comment]
> i.e having an extra option to select the mousepad

This would be also nice for headsets. (atm Steelseries headset doesn't light up when using a mouse other than generic)

**Comment by simon-wh** [comment]
Fixed thanks to #1331!

**Comment by simon-wh** [comment]
Fixed thanks to #1331!
