### ISSUE TITLE
Issue with CM Masterkeys Pro L

### ISSUE THREAD

**Issue by Popopopper** [antonpup/Aurora#482]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (CM Masterkeys Pro L)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
The pause key should sync up with the rest of the keys when using the gradient setting, and the profile keys should light up

### Actual behavior:
The pause key lags behind the surrounding keys when it changes color

### How often does this problem occur?

This problem occurs... (Always)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Set the keyboard to use the gradient setting with animation
2. Assign all keys (or at least a few surrounding keys) to the gradient setting 
3. Turn on the animation

### What is the version of Aurora you are experiencing this issue with?

My version is... v0.6.0b

### Does the previous version of Aurora have this issue?
The previous version, v0.6.0, did have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by chlronald** [comment]
And the number 4 key didn't light up.

**Comment by simon-wh** [comment]
I believe this issue is pretty much the same as #549 so I'm going to close this to use that as the main one
