### ISSUE TITLE
G910v2  '\' key is not lighting up properly

### ISSUE THREAD

**Issue by Dwightojo** [antonpup/Aurora#487]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [X] Aurora supported device, G910
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [X] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
The '\' key should light up like the rest of the keyboard.

### Actual behavior:
The '\' key does not light up properly.

### How often does this problem occur?

This problem occurs every time.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Connect a Logitech G910v2
2. Start Aurora
3. Try to light the '\' key.

### What is the version of Aurora you are experiencing this issue with?

My version is 0.6.0b

### Does the previous version of Aurora have this issue?
I did not try the previous version.

### Please include any logs, screenshots, or files that are related to this issue:

NA

### Possible cause:
The layout of the keyboard has been slightly altered for v2 (only the '\' key was moved. So it looks like this is the issue.

**Comment by antonpup** [comment]
Have you selected proper keyboard localization in settings? Please look though those to find your physical layout.

**Comment by Dwightojo** [comment]
yep that was it. Thanks!
