### ISSUE TITLE
logitech g900 mapping

### ISSUE THREAD

**Issue by Praha00** [antonpup/Aurora#489]
Hey guys, 

i installed aurora a couple of days ago. I have a logitech g910 keyboard and a logitech g900 mouse. I have a problem. When i play games i have custom mouse buttons to use in game with the standard logitech software. I think aurora messed up my mapping. Is there a way to fix this issue?

Gr praha00

**Comment by antonpup** [comment]
Aurora only uses LED SDK for Logitech devices. So no, It shouldn't have changed any mappings. It's an issue on Logitech's end.

With that said, I have the same setup, and my mappings are all fine. G910, G900, G933, all with G-key maps of some kind.

**Comment by Praha00** [comment]
i have this problem since i installed aurora. Now i can use my custom mappers anymore when i play csgo :/
