### ISSUE TITLE
Corsair mouse and Razer mouse pad: No light on mouse..

### ISSUE THREAD

**Issue by WilliamRandol** [antonpup/Aurora#490]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
When a Razer Firefly mouse pad is plugged in and a Corsair M65 mouse both should have the lighting effects applied to them.

### Actual behavior:
The Corsair mouse has no lighting effects applied.

### How often does this problem occur?

This problem occurs... Only when both the mouse and mouse pad are plugged in at startup.  If I unplug the mouse pad when booting and wait for Aurora to start then attach the mouse pad It works fine.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Start a system with both a Corsair M65 mouse and a Razer Firefly mouse pad.

### What is the version of Aurora you are experiencing this issue with?

My version is... beta v0.6.0b

### Does the previous version of Aurora have this issue?
--The previous version, (Fill in the version here), did/did not have this issue.--
Unknown, I have never used a previous version.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by WilliamRandol** [comment]
So with the last few times I have rebooted, this has not been an issue. I don't know what is up. I will post with more if i can get a better idea of the actual cause if this issue.

**Comment by simon-wh** [comment]
Fixed thanks to #1331!
