### ISSUE TITLE
Overwatch Colours not working anymore.

### ISSUE THREAD

**Issue by PlsHelpmeSenpai** [antonpup/Aurora#491]
### What are you experiencing an issue with?

- [ ] Aurora
- [x] Aurora supported game, (Overwatch)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, (Fill in another type of issue here)

### Expected behavior:
The overwatch colour profile should load right away, and then switch colours according to the different heros available.

### Actual behavior:
Orange colour doesn't load on the main screen, and the light flickers after selecting a hero.  So there is never consistent lighting and even going black out for some reason.

### How often does this problem occur?
Every time since March 9th

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Launching overwatch (either from battle net or running it as admin)
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (v0.6.0b)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by somadden** [comment]
Do you have all packages installed?
Visual C++ Redistributable Packages for Visual Studio 2015 x86 and x64
Microsoft .NET Framework 4.5

**Comment by PlsHelpmeSenpai** [comment]
Yes I have all of those packages installed. I even reinstalled em just to be sure.  Ill try it out now to see if it works.

**Comment by PlsHelpmeSenpai** [comment]
It does not work in game, but when i alt-tab out it shows the profile perfectly for some reason.

**Comment by somadden** [comment]
I was reading through the developers comments and he suggested to try disabling any antivirus and firewalls. Then running both overwatch.exe and aurora.exe as admin to see if it fixes it.

**Comment by antonpup** [comment]
You might have accidentally added overwatch.exe into exceptions. Or overwatch is running as admin, and Aurora isn't. Running Aurora as admin would fix that permissions issue.

**Comment by PlsHelpmeSenpai** [comment]
I ran both as admin and it still doesn't work.  When overwatch is running in the background and i alt-tab out of it the colour profile then works on my desktop.  It turns black when i go back to overwatch though.

**Comment by antonpup** [comment]
Try adding a layer to the overwatch profile. Like fill it entirely with a solid color red. If profile is loaded properly, when you are in-game, instead of keyboard being black, it will be red. And when you tab out, it will display game lighting without red (like how you described).

**Comment by PlsHelpmeSenpai** [comment]
Even after I fill the keyboard red, it wont be red when i go in game.  I goes back to black.

**Comment by simon-wh** [comment]
Possibly related to #397 and #312

**Comment by simon-wh** [comment]
Also, @PlsHelpmeSenpai could you try the [latest development release](https://github.com/antonpup/Aurora/releases) to see if it makes a difference after repatching?

**Comment by PlsHelpmeSenpai** [comment]
Ayyy it works now. Thanks
