### ISSUE TITLE
Overwatch Lighting isn't working g810

### ISSUE THREAD

**Issue by somadden** [antonpup/Aurora#494]
### What are you experiencing an issue with?

- [ ] Aurora
- [x] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (g810)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Keys should turn on when starting overwatch.

### Actual behavior:
Keys go black.

### How often does this problem occur?
Everytime

### Please describe the steps to reproduce this issue:

1. Launch Overwatch
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... 0.6.0b

### Does the previous version of Aurora have this issue?
New install

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/g8jm6tN7

**Comment by PlsHelpmeSenpai** [comment]
Yea bro i'm having the same issue with my g410.  It just goes black, and flashes sometimes.

**Comment by somadden** [comment]
Solved it, I needed VS 2015 x64. I only had 2015 x86. 
Suggested changes to avoid this.

1. Update instructions on github to say download both x86 and x64 installs
2. On https://aurora.modworkshop.net/ add a download page.  Attached is HTML code for the page to match your theme.
[download.txt](https://github.com/antonpup/Aurora/files/849578/download.txt)
