### ISSUE TITLE
Support Razer non-RGB devices

### ISSUE THREAD

**Issue by EZTEQ** [antonpup/Aurora#495]
Razer devices that are non-RGB (monochrome) should be supported.
Is there any work on this or some tips where to start contributing?

The Razer Blackwidow Ultimate 2016 has individual lighting for each key, so this would be a good fit for Aurora.

**Comment by simon-wh** [comment]
The only Razer devices that are supported by the Chroma SDK are Chroma devices. So there isn't much we can do to support the non-RGB Razer devices unless we were to create our own API to interact with them.
