### ISSUE TITLE
Aurora Startup Crash

### ISSUE THREAD

**Issue by xaerofarb** [antonpup/Aurora#496]
### What are you experiencing an issue with?

- [x ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

LOGS http://pastebin.com/ctcSCSeG

**Comment by Blizzardfall** [comment]
Have you tried in safe mode or without any software running on background?
In my case, I couldn't launch Aurora if Rivatuner Statistics Server(a software that comes with MSI Afterburner) is running.

**Comment by xaerofarb** [comment]
There are no applications running in the backplane. I have not tried it in safe mode. When I shut down all the programs and tried it, I got the same error :( Sry bad english...

**Comment by xaerofarb** [comment]
http://pastebin.com/fk4cSb44

**Comment by simon-wh** [comment]
@xaerofarb could you try using the [latest development release](https://github.com/antonpup/Aurora/releases) to see if there is any difference?

**Comment by simon-wh** [comment]
Please refer to #605 relating to this issue. @xaerofarb please post any follow-up regarding the latest dev release on that issue.
