### ISSUE TITLE
Backslash(\) does not light up on Logitech G910 keyboard.

### ISSUE THREAD

**Issue by Blizzardfall** [antonpup/Aurora#5]
![2016-06-06_12-21-30](https://cloud.githubusercontent.com/assets/19769002/15811213/3ecbee8a-2be1-11e6-840f-44adf5ba2fb2.png)
As title says, \ key on my Logitech G910 does not light up at all when using Aurora.

Maybe it's regional thing If you can't reproduce the issue, since backslash is Korean Won symbol in Korea.

**Comment by antonpup** [comment]
It's a regional issue. I will add a layout for that.

**Comment by antonpup** [comment]
Make sure your LGS is updated to the latest version. I tested this on version 8.83.85.

**Comment by antonpup** [comment]
Oh, I see from your other post, your Aurora is using a UK layout. While your keyboard in LGS is shown in another one. Next update will let you select which keyboard layout you prefer to have in Aurora.

**Comment by Bassist067** [comment]
Thank you for the great software! It' nice to see such a piece of code for my precious G910. Though, I have a Russian layout along with the English one. My LGS is 8.96.88 and it seems the slash key (the one from the left of Enter key).

Any ideas?

**Comment by simon-wh** [comment]
@Bassist067 Are you using the [latest development release](https://github.com/antonpup/Aurora/releases) and have you got the Russian layout selected in settings?
