### ISSUE TITLE
Support for SC2?

### ISSUE THREAD

**Issue by Johnnybeefcake** [antonpup/Aurora#50]
I wanted to know if support for Starcraft 2 is going to be a thing. I downloaded this to add a little more excitement to my g910 and it works wonderfully. I would love if it could work with the ability of the selected unit in SC2. That's what I was hoping to be able to do when buying this keyboard. So far, I'm really impressed with Aurora. It's replaced LGS in terms of lighting effects.

Edit : Just noticed the G keys don't seem to react to anything.

**Comment by antonpup** [comment]
I can support it if there's a way to get information out of the game without memory reading. If there have been projects for SC2 that involve in-game stats, or keyboard lighting effects, then I can see how they're retrieving the info.

As for the G-Keys, they're not supported in the Logitech SDK, as soon as they are supported, I will enable them.

**Comment by Johnnybeefcake** [comment]
Thanks for the really fast reply. I can try scouring the net to see if such thing exists for SC2. As for the G-keys, that's all good. Here's hoping they're supported soon

**Comment by Johnnybeefcake** [comment]
https://dev.battle.net/

I'm 90% sure they'd have an API for Starcraft 2 since there's a Protoss in the banner up top. From what I've seen, you make an account, verify, and then request an API for a game, giving an explanation of what you require the API for. Not sure if this is what you're looking for, but it's all I've found on the matter

**Comment by antonpup** [comment]
That API does not seem to retrieve game information, but rather retrieves overall profile information. Not useful for Aurora, but still neat though.

**Comment by Johnnybeefcake** [comment]
Aah well that's a bummer. Hopefully something crops up.
