### ISSUE TITLE
Logitech G410 - German version - three keys not controllable

### ISSUE THREAD

**Issue by OttoWerse** [antonpup/Aurora#501]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (Logitech G410 - German Layout (QWERTZ))
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
All keys should be controllable through Aurora

### Actual behavior:
FN, backlight off and gaming mode keys are not affected by aurora and can only be controlled by Logitech g.

### How often does this problem occur?

This problem occurs permanently

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Turn on Computer
2. Wait until Aurora and Logitech G have loaded
3. See that the three keys are blue or whatever you've set in Logitech G instead of what you set them to in Aurora

### What is the version of Aurora you are experiencing this issue with?

My version is 0.6.0b

### Does the previous version of Aurora have this issue?
Yes

### Please include any logs, screenshots, or files that are related to this issue:

I wouldn't know anything that could describe this issue visually or in logging form, or at least not where to get those logs from, sorry.

**Comment by brainbug89** [comment]
IIRC the 'backlight off' key and the 'gaming mode' key aren't part of the Logitech lighting API (or at least they aren't added to the Aurora layout).

But the FN key should work imho.

**Comment by OttoWerse** [comment]
I don't know if they're supported yet, or if they even are accessible through Logitech's API, I just noticed that there is no way to control them in Aurora, but they are RGB, so I'd assume there is some way to control them, similar to how you can also address the media keys and other special keys on other Keyboards. I could be wrong, I don't know much about Logitech's API.

I'm pretty, actually 100%, sure it isn't working for me, but I think this issue is specific to the QWERTZ-Layout version of the G410, I don't know, though since I don't own any other variant of it.

**Comment by antonpup** [comment]
Those keys are not part of the Logitech LED SDK. When they get added, I will look into updating the layout.
