### ISSUE TITLE
Add Uninstaller which removes wrapper patches

### ISSUE THREAD

**Issue by LouieMjr** [antonpup/Aurora#502]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [x] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, (Overwatch has a default lighting system that works with razer keyboards before i install aurora. After using aurora i uninstalled it and now the default lighting that is automatic with overwatch and razer isnt working at all.)

### Expected behavior:
Explain here what should happen.
Basically it should work automatically, i dont get the default lighting that should just work when i load up the game or when i change characters. This is not a profile that i created. This is a lighting system that was automatic by overwatch and razer and now it isnt working after getting rid of aurora!

### Actual behavior:
Explain here what happened instead.
Nothing is happening my lights wont change when i start up overwatch.

### How often does this problem occur?

This problem occurs... (Everytime i load up overwatch)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. lighting was working before Aurora
2. installed and Used aurora lighting for overwatch
3. uninstalled aurora and now the default lighting for overwatch doesnt display

### What is the version of Aurora you are experiencing this issue with?

My version is... (none its uninstalled)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by njblilbadboy** [comment]
Nevermind i fixed. Basically what i did was go into Program files x86 and deleted the files that aurora added or updated in overwatch and when i loaded up overwatch after that i got an error that said some resources couldnt be located and it prompted a quick update for overwatch to fix what i deleted and then loaded up overwatch and lighting worked again!

**Comment by njblilbadboy** [comment]
But if there is a better way to do this when someone uninstalls Aurora, if you can kindly explain how ? im sure it would help out quite a few people. Thank you!

**Comment by simon-wh** [comment]
What method did you use to 'uninstall' Aurora?

**Comment by njblilbadboy** [comment]
I have iobit uninstaller to uninstall programs, that's what I used
