### ISSUE TITLE
Brazilian (ABNT2) Keyboard Layout

### ISSUE THREAD

**Issue by Medroid** [antonpup/Aurora#504]
### What are you experiencing an issue with?
- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [X] Aurora supported device, (K70 Lux RGB Brazilian Layout)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [X] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?
- [ ] Crash
- [ ] Performance problems
- [X] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [X] Device issue
- [ ] Other, (Fill in another type of issue here)

### Actual behavior:
There is no support for ABNT2 keyboard layout (brazilian), so the "/" key doesn't light up. And some labels are wrong.

### How often does this problem occur?
Every time

### Please describe the steps to reproduce this issue:
Using a keyboard with ABNT2 layout

### What is the version of Aurora you are experiencing this issue with?
My version is 0.6.0b

### Does the previous version of Aurora have this issue?
Yes

### Please include any logs, screenshots, or files that are related to this issue:

Actual Keyboard Layout:
![900px-kb_portuguese_brazilsvg_](https://cloud.githubusercontent.com/assets/26511343/24076144/8cbeab52-0c08-11e7-9cbc-b6213bca8257.png)

**Comment by simon-wh** [comment]
@Medroid I've added support for the layout in the commit above but I wasn't able to test the / key as it isn't present on my keyboard on the on-screen keyboard I use for testing. [This build](https://www.dropbox.com/s/slv6b15cv7oufho/v0.6.1-dev3%20ABNT2%20test.zip?dl=0) will log the necessary details of the key press for that key if it isn't currently working properly. Could you test it and post what the log says when you press the / key if it doesn't light properly through the interactive layer?

**Comment by Medroid** [comment]
Hi,

Thanks for the update. As soon as possible I will test it and let you know.

Thanks!

Enviado do Email<https://go.microsoft.com/fwlink/?LinkId=550986> para Windows 10

De: Simon W<mailto:notifications@github.com>
Enviado:quarta-feira, 6 de setembro de 2017 15:16
Para: antonpup/Aurora<mailto:Aurora@noreply.github.com>
Cc:Medroid<mailto:matheus.patrick@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Assunto: Re: [antonpup/Aurora] Brazilian (ABNT2) Keyboard Layout (#504)


@Medroid<https://github.com/medroid> I've added support for the layout in the commit above but I wasn't able to test the / key as it isn't present on my keyboard on the on-screen keyboard I use for testing. This build<https://www.dropbox.com/s/slv6b15cv7oufho/v0.6.1-dev3%20ABNT2%20test.zip?dl=0> will log the necessary details of the key press for that key if it isn't currently working properly. Could you test it and post what the log says when you press the / key if it doesn't light properly through the interactive layer?

**Comment by Medroid** [comment]
@simon-wh it worked.

Thanks.

**Comment by jrodella** [comment]
Hello
I have Corsair STRAFE RGB (ABNT2 layout) and downloaded this build (0.6.1 dev3 ABNT2 test) and illumination works very well, but the additional key fixed on this build [ / ? ] does not trigger illumination effects.
When I set an Interactive Layer, all keys works except /?.
The illumination wave runs on all keys, but the keypress of /? not starts the wave.
