### ISSUE TITLE
help sync led corsair k70 rgb rapidfire and razer mamba te and firefly razer mousepad

### ISSUE THREAD

**Issue by Levandowski21266** [antonpup/Aurora#506]
i have corsair k70 rgb rapidfire and razer mamba te and firefly razer mousepad and i go to sync all device.
my problem is razer mamba te missed in the support mouse.
how can I do to fix?

**Comment by DogeAmazed** [comment]
@Levandowski21266 In [the development builds](https://github.com/antonpup/Aurora/releases), there is an option to use an "Generic Peripheral". You can use this option until the Razer Mamba is supported.

**Comment by simon-wh** [comment]
@Levandowski21266  You can get the latest one here: https://github.com/antonpup/Aurora/releases

**Comment by olokos** [comment]
are there any plans to support mamba?

**Comment by simon-wh** [comment]
@olokos Mamba is under #119, but I won't be implementing it until the rewrite is completed as I'm going to be primarily focusing on that and only really doing major bug fixes for the current version

**Comment by simon-wh** [comment]
Also firefly is under #880 and #552 so I'm going to close this
