### ISSUE TITLE
H1Z1: KotK Support

### ISSUE THREAD

**Issue by Zallee90** [antonpup/Aurora#507]
Would love to see support for this game.

**Comment by antonpup** [comment]
I believe it was either H1Z1 or DayZ that had Razer lighting support. But it did not work because BattlEye would prevent loading of Aurora's uncertified wrapper dlls.

**Comment by Zallee90** [comment]
Ah, ok.. :/ Are we able to make timers for how long a key should have a certain color in the future? eg. If i apply a bandage i know it takes 3 secs, so the key binded to the bandage can be another color during the "cooldown".
 And to bind an area of keys to light up when i press another key? eg. If i press M for map, all the keys within 3 keys from M lights up in green until i press M again to close map. 

Love the software, but miss having it on the game i play the most.. :P Hehe!

**Comment by simon-wh** [comment]
There doesn't appear to be any realistic way to add support for this. Closing until plausible. You can make a generic profile for it to show stuff like shortcuts, but you won't be able to make changes based on the current in-game information.
