### ISSUE TITLE
Andromeda Support

### ISSUE THREAD

**Issue by Morrivar** [antonpup/Aurora#508]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [x] Other, Aurora broke Mass Effect: Andromeda's Logitech Gaming Software integration

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, Aurora broke Mass Effect: Andromeda's Logitech Gaming Software integration

### Expected behavior:
Disable Aurora, launch Andromeda, enjoy Logitech g910 integration

### Actual behavior:
Disable Aurora, launch Andromeda, only default profile works, no Andromeda integration

### How often does this problem occur?

This problem occurs... every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Play Andromeda and enjoy fancy integration
2. Install Aurora to enjoy similar integration with other games
3. Disable Aurora
4. Launch Andromeda
5. Cry because your keyboard isn't doing the fancy things.

### What is the version of Aurora you are experiencing this issue with?

My version is... v0.6.0b

### Does the previous version of Aurora have this issue?
The previous version, no idea

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by antonpup** [comment]
It doesn't work anymore because Aurora patches Logitech's LED SDK to go through Aurora. So without Aurora, you cannot get LED effects.

**Comment by brainbug89** [comment]
>Play Andromeda and enjoy fancy integration
Install Aurora to enjoy similar integration with other games
Disable Aurora
Launch Andromeda
Cry because your keyboard isn't doing the fancy things.

Shouldn't Andromeda (Logitech lighting) work with Aurora? Did you try this (don't disable Aurora and play Andromeda)?

**Comment by SilentZen** [comment]
Just tested The Division again and it works with latest dev copy of Aurora showing at 0.6.0b. Tried Mass Effect Andromeda and no in game lighting enabled. no LogitechLed.dll in either game.
Copied LogitechLed.dll to same directory as Andromeda executable and tried again still no in game lighting.

**Comment by TristanPra** [comment]
Hi ! Is aurora supporting andromeda without a logitech keyboard? I have a corsair strafe and it seems it just turn off lights when lauching game. Is there a way to enjoy effects on this device ?

**Comment by simon-wh** [comment]
@TristanPra the lighting effects that go through Aurora will work on any devices that are supported by Aurora. Could you make sure you've applied the patch and see if anything changes? If it still isn't working then please open a new issue.
