### ISSUE TITLE
Aurora + Logitech G810 + Razer Mamba TE

### ISSUE THREAD

**Issue by swoolly** [antonpup/Aurora#51]
I have a problem when using Aurora with my Logitech G810 keyboard as well as my Razer Mamba TE Mouse.

When Aurora is open it disables my mouse lighting settings that are set in the Razer software, making it a solid colour. I can't see an option to disable this, or change my mouse settings in Aurora. 

I also have a problem with Overwatch, where the mouse then deactivates all LED's when overwatch is open, not changing colour with character as per the default Razer settings.

Any ideas?

**Comment by antonpup** [comment]
I'll add an option to disable certain devices from being updated. As for mouse lighting, you can set it by applying effects on the "Mouse" region of the virtual keyboard.
![](http://puu.sh/pI2hx/f420c8eabd.png)

For Overwatch not working, please see if issue #42 will resolve your problem.

**Comment by antonpup** [comment]
Did you ever resolve your Overwatch issue?

**Comment by pwn3du** [comment]
I have a similar problem with a razer mamba TE and a logitech g910 keyboard.  When I get Aurora to work, then the keyboard lights as it should in Overwatch, but the mouse will be completely dark.  If I disable Aurora (and remove the patch .dlls) then the mouse works correctly, but the keyboard does not (obviously).  I attempted the fix in #42 and that didn't help.  I can't for the life of me figure out why Aurora can't pass the SDK info on to the Razer in Overwatch, given that I see it working properly sitting at the desktop.  Any ideas?  I'd love to get this all working properly and I feel like it's very close.

**Comment by antonpup** [comment]
@pwn3du Umm... Aurora doesn't pass anything mouse/headset/keypad/mousepad related from Razer to Aurora yet. It's just the keyboard lights at the moment. I'll see about including it. Does the mouse light up one solid color? There's only demos of Overwatch lighting with keyboards, nothing about mice or headsets.

**Comment by swoolly** [comment]
Sorry for such late reply! Been busy.

Didn't notice the lighting effect option of the mouse in the program, thanks! Still a shame Aurora overrides any Synapse settings when open, as there is a lot of customization on the Mamba TE. 

As for Overwatch not working, issue #42 didn't resolve it. It's temperamental to get Overwatch to work with Aurora, and when I do the mouse doesn't change colours like it used to like @pwn3du says. Infact, since having Aurora installed my mouses lights doesn't react to Overwatch at all, even after deleting all files. 

@antonpup With mice, well my Mamba TE, Overwatch will change the colour of the mouse depending what character you choose. Nothing life changing, but would be nice to have it all working together!

**Comment by pwn3du** [comment]
When Aurora isn't used it lights up according to the color of your selected class. I haven't noticed any animation or anything when playing.  

I guess I figured the first thing implemented in Aurora would be a pass-thru that would allow Razer devices to work as if Aurora was not being used at all so I was puzzled when it didn't work.

I would very much like this feature since it would allow use of the better Razer SDK for everything since Logitech doesn't seem to really care if their products get supported or not.  Thanks for working on this.  I'm a developer myself, so if you need testing of a more technical nature, just let me know.

**Comment by antonpup** [comment]
@swoolly If you can explain to me what kind of effects you want from Synapse, I can try to recreate them in Aurora.

@pwn3du Yeah, Razer Wrapper isn't completely done. Reason for that is that people have issues connecting Overwatch with Aurora. Once I figure out why, then I will finish it. It's planned to have all Razer apps work with Aurora.

**Comment by pwn3du** [comment]
@antonpup seems like it isn't a matter of needing to reimplement the razer mouse effects in Aurora.  I think all that should be necessary is once the Razer SDK entrypoints are hooked in the Aurora DLLs, it should be able to just relay them to the underlying Razer DLL in the case when a Razer device is involved.  When a Logitech device is involved, then it needs to reproduce the effect through the Logitech SDK.  Or is the issue that you aren't hooking and redirecting ALL calls from the Razer DLLs?

**Comment by antonpup** [comment]
@pwn3du Currently I am redirecting ALL calls to Aurora. Original plan was to fallback to original SDK in the event connection with Aurora was not made. But like I said, if the IPC isn't reliable at all, then it will always use the original SDK, leaving Aurora useless.

**Comment by pwn3du** [comment]
right, I get that.  I guess what I was saying is that when Aurora starts up, it's seeing my keyboard and mouse.  At that point it knows the mouse is a razer mouse, so it should be trivial for it to just forward all Razer SDK mouse api entrypoints to the original Razer SDK DLL and my mouse would continue to work as normal in Overwatch.  The only reason anything new would need to be implemented effect-wise was if I was using a Logitech or Corsair mouse.  Or am I still missing something?

**Comment by antonpup** [comment]
@pwn3du Right. In terms of any Razer app at the moment, it only reports keyboard lighting to Aurora. Aurora itself does update the Razer mouse lighting, except when it's Overwatch, the mouse lighting is never updated from default black color.

For further clarification, when I said " I am redirecting ALL calls to Aurora", I'm only redirecting keyboard effects at the moment. But they do not fallback to original SDK.

I'll redirect mouse effects to Aurora for next version.

**Comment by antonpup** [comment]
Mouse effects are now redirected. Will be a part of next version.

**Comment by pwn3du** [comment]
Looking at the code, unless I'm misunderstanding it, it looks like you've only supported the Razer Deathadder Chroma and not the Mamba or Mamba TE.  Is this correct?

**Comment by antonpup** [comment]
No. the Wrapper only claims to be a Blackwidow Chroma for keyboard and a Deathadder Chroma for mouse. So if a Chroma app requests all connected devices. The wrapper will report back that 1 Blackwidow and 1 Deathadder are connected. It will then redirect lighting to Aurora, and Aurora is responsible for lighting up devices, not the Wrapper.

In short, I didn't add or remove any device support. The Mamba devices will work just fine.

**Comment by antonpup** [comment]
Small demo: 
[![Chroma SDK app support Demo](http://img.youtube.com/vi/v6P9srU8IWE/0.jpg)](https://www.youtube.com/watch?v=v6P9srU8IWE)

**Comment by pwn3du** [comment]
That's not quite what I was meaning....

Basically with the way it's set up, when using Aurora the game will think I have a Deathadder even if I actually have some other type of Razer mouse, is that correct?  Doesn't that mean that other mice with different lighting capabilities (different zones/configurations) won't be fully or properly driven by the game?

**Comment by antonpup** [comment]
Well, specifically for mice, I am only supporting 1 color. So I take the color of the logo and send that to Aurora.

But in terms of compatibility, I select the hardware that is most supported in terms of layouts for other products listed [here](http://developer.razerzone.com/chroma/razer-chroma-led-profiles/).

So yes, if a chroma app developer decides to only support a Razer Naga, and specifically checks if Razer Naga is connected. Then it will not work. But there are several ways with Razer SDK to light up devices.

- CreateEffect - Device based, only Blackwidow and Deathadder will work
- CreateKeyboardEffect - Will work for any keyboard
- CreateMouseEffect - Will work for any mouse

**Comment by pwn3du** [comment]
Fair enough.  I'm not willing to lose the increased lighting zone support of my Mamba though, so I guess that still means no Aurora for me :).  At some point maybe I'll take the source and look into passing through all Razer mouse types directly to the Chroma SDK based on which mouse is connected.  It seems like this really should be fairly easy to do, but until then I'll just live without my keyboard behaving nicely :).
