### ISSUE TITLE
Logitech G502 support in UI

### ISSUE THREAD

**Issue by Dwightojo** [antonpup/Aurora#510]
### What are you experiencing an issue with?
- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, Logitech G502
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?
- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, It is not supported

### What is the version of Aurora you are experiencing this issue with?

My version is... 6.0b

I would like to see some love for this other great logitech mouse.
http://gaming.logitech.com/en-us/product/g502-proteus-spectrum-rgb-gaming-mouse

**Comment by antonpup** [comment]
You can use any mouse setting to get mouse lighting. It just won't be 100% perfect in terms of effects. But at least it will work.

**Comment by jdubnz** [comment]
I use the g502 and have selected G900 in the Preferred mouse. Works a charm

**Comment by Ardakilic** [comment]
I also own a g502, and selected G900. Works for now.

**Comment by TheNorwegianBeck** [comment]
Used to work for me too, doesn't work anymore.

**Comment by simon-wh** [comment]
@TheNorwegianBeck Are you assigning lighting to the lights on the mouse? The mouse won't light up on its own unless you're using a profile that includes it or a game that lights the mouse.

**Comment by TheNorwegianBeck** [comment]
@simon-wh Went trough all of the profiles, all of them even the desktop profile. Does not use the mouse's light, have it set to g900, im using a g502

**Comment by simon-wh** [comment]
@TheNorwegianBeck Create a Solid Colour Layer and when you're assigning keys click on the lighting areas on the mouse. In the preview it should be lit up as well as your physical mouse.

**Comment by TheNorwegianBeck** [comment]
@simon-wh Assigned to two keys + the mouse logo, still doesnt light up, even the one in the editor doesnt light up.

**Comment by simon-wh** [comment]
@TheNorwegianBeck Could you take a screenshot of it? Including at least the Layer and Preview.

**Comment by TheNorwegianBeck** [comment]
![aurora](https://cloud.githubusercontent.com/assets/17355570/26118079/dfd1b2f6-3a68-11e7-8620-7ad03b297776.PNG)
 Here

**Comment by simon-wh** [comment]
@TheNorwegianBeck You didn't include the layer you created. What layer are you using?

**Comment by TheNorwegianBeck** [comment]
![aurora2](https://cloud.githubusercontent.com/assets/17355570/26118334/d046e38c-3a69-11e7-8a91-837117dd1efc.PNG)

**Comment by TheNorwegianBeck** [comment]
![aurora3](https://cloud.githubusercontent.com/assets/17355570/26118411/1579ef8a-3a6a-11e7-82cb-305a65a11653.PNG)
Also one where they are all assigned normally, still doesnt work.

**Comment by simon-wh** [comment]
@TheNorwegianBeck Could you try and see if you experience the same issue on the [latest development version](https://github.com/antonpup/Aurora/releases/tag/v0.6.0-dev2)?

**Comment by TheNorwegianBeck** [comment]
@simon-wh Still doesnt work sadly. It worked a couple of weeks ago, but suddenly it has decided not to.

**Comment by simon-wh** [comment]
@TheNorwegianBeck I don't have a Logitech mouse and I'm still able to get it to display in the preview. It's strange that you're not able to get at least that.

**Comment by TheNorwegianBeck** [comment]
@simon-wh Where does the program store profiles? I deleted the old one, but when i started the new one it remembered the green layer. Maybe i can try to delete the profiles?

**Comment by TheNorwegianBeck** [comment]
Found it, seemed to fix the problem by deleting the folder for aurora in roaming.

**Comment by simon-wh** [comment]
@TheNorwegianBeck You can click on the Profiles Manager above the Layer Manager and either reset the profile you're using or open the Profile Folder.

**Comment by TheNorwegianBeck** [comment]
@simon-wh Deleting everything from aurora in the roaming folder fixed it.

**Comment by zejjnt** [comment]
Is there any possibility to get some kind of control of the original G502 (three colors on the DPI indicator, blue on the G-logo)?
It would be nice to integrate it in breathing or that wave-thingy when you press a button.

**Comment by derekpurdy** [comment]
is there any progress on getting support for the G502?

**Comment by simon-wh** [comment]
See #710
