### ISSUE TITLE
main screen auto-select problem with ultrawide

### ISSUE THREAD

**Issue by ZephyrArcturus** [antonpup/Aurora#514]
Hello.

i love the ambilight feature integrated in aurora and would like to use it on a daily basis

the problem is : i've got 2 screens, a standard 16:9 and an ultrawide 21:9 monitor

because of the ultrawide nature of my main screen, aurora doesn't detect it as my primary screen (it is set as primary screen in windows, of course) and only selects my secondary screen

i saw that multi-monitor setups were "fixed" but i cannot choose my ultrawide as the ambilight screen

could you please add a setting allowing us to choose which monitor to use and not only the "main" one?

**Comment by antonpup** [comment]
Will look into, but I believe dev branch has this issue resolved.

**Comment by simon-wh** [comment]
@ZephyrArcturus Could you try the [latest development release](https://github.com/antonpup/Aurora/releases) to see if it resolves your issue?

**Comment by ZephyrArcturus** [comment]
@antonpup @simon-wh the issue is fixed with the 0.6.1 dev2 update!
thanks a lot for the awesome work
