### ISSUE TITLE
Chroma Apps no longer working correctly

### ISSUE THREAD

**Issue by mark6ikx** [antonpup/Aurora#515]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Chroma apps should launch

### Actual behavior:
Chroma apps should launch, but might only launch on mouse and mousepad. All apps I used before would work fine, and this isnt even every app, Shadow Warrior 2 for example works fine, yet hue and Shovel Knight only load on mouse and mousepad. 

I have uninstalled and reinstall both Synapse and Aurora.

### How often does this problem occur?
Every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Launch chroma app
2. See mouse and mousepad change to chroma app
3. Keyboard just goes blank

### What is the version of Aurora you are experiencing this issue with?

My version is... (0.6.0b - the newest version)

### Does the previous version of Aurora have this issue?
No Idea

### Please include any logs, screenshots, or files that are related to this issue:
None needed

**Comment by ersan** [comment]
This is happening after the update to Synapse that came out today if that wasn't apparent.  The BlackWidow will have all keys go black while Aurora is active.

**Comment by mark6ikx** [comment]
Oh I didn't even realise there was an update. I'm sure it was doing it 2 days ago aswell though. Been tearing my hair out over this one

**Comment by Nedo93** [comment]
Having the same problem, if there is no way to resolve the issue I will try to rollback to the previous version of Synapse.

**Comment by mark6ikx** [comment]
Nedo93 do other games still work fully though like shadow warrior 2 and overwatch?

Thats the issue i have

**Comment by mark6ikx** [comment]
Strange, all I've done is install Synapse, Aurora and Logitech Gaming Software.

**Comment by Nedo93** [comment]
Same, I have Logitech Gaming Software too.

**Comment by mark6ikx** [comment]
Are we sure its not that? All my chroma stuff worked beforehand or have you had it installed a while? (I got my new peripherals on Saturday)

**Comment by WilliamRandol** [comment]
My Chroma stuff stopped working with aurora after the update. I do not have Logitech but I do have Corsair.

**Comment by ersan** [comment]
Overwatch will work if you haven't applied the Aurora Wrapper Patch for Razer because it communicates directly with Razer Synapse.  The issue here is that Aurora itself is not working with the new Razer Synapse update - the keyboard just sits with all lights off.

**Comment by mark6ikx** [comment]
Ok thats understandable ersan, any idea why my keyboard is not working for games like Black Ice and Hue even when Aurora is turned off/disabled/uninstalled.

So far I have removed Logitech Gaming Service, Aurora and Synapse, uninstalled the drivers and Chroma SDK, and then I've reinstalled Synapse, with a restart before and after installation. The issue was my mouse and mousepad would react, but not the keyboard, and then after exiting the game the game specific lights would stick.

I'm not saying your wrong by the way, it seems that we all have been affected differently I just want to make clear what my issue is.

Are we sure its Aurora or has something gone wrong with Synapse?

Are there more files for Aurora that I may of not uninstalled?

**Comment by Nedo93** [comment]
I'm 99% sure that the problem is the new Synapse's update, let's wait for Antonpup to reply to see if it's a known or possible issue.

**Comment by mark6ikx** [comment]
Agreed


________________________________

**Comment by mark6ikx** [comment]
Agreed

**Comment by ersan** [comment]
@mark6ikx from what I understand when you patch a Razer-enabled game it patches a file that is part of the game itself so you would have to restore the game file(s) to their original state to get them working again.  I think overwatch has some sort of verify integrity/repair feature which will restore the original files.

**Comment by mark6ikx** [comment]
@ersan I never patched Razer as I wanted to keep them seperate, even so if they had patched I've reinstalled both. 

Initially as far as I'm aware they never patched and worked.

Thanks though

**Comment by latworx** [comment]
well, seems like most of us encounter the same prob. waiting for answer. thanks in advance

**Comment by ersan** [comment]
I'm having quite a bit of difficulty removing Aurora and getting native Overwatch Razer support back as well.

**Comment by antonpup** [comment]
Aurora's Razer Wrapper patch simply extracts two dll files that redirect lighting information to Aurora instead of directly to Razer Synapse. If you wish to remove Aurora's Razer Wrapper, you can do so by deleting "RzChromaSDK.dll" and "RzChromaSDK64.dll" from game's directory (folder where you pointed Aurora to install patch to). After that, The game will use Razer's original sdk files.

**Comment by ersan** [comment]
I deleted those files, uninstalled Aurora, and rebooted and it still isn't working - maybe it's an unrelated issue but Aurora definitely doesn't work with the new Razer Synapse - all the lights are off.

**Comment by antonpup** [comment]
I don't have any Razer products, so... not much I can do in terms of testing. I'll look around for potential fixes.

**Comment by ersan** [comment]
I actually seem to have solved this problem by following the steps in this reddit post: https://www.reddit.com/r/razer/comments/4hwphi/overwatch_chroma_app_not_working/d2vazpx/

I uninstalled the Razer SDK components and reinstalled them using the link above and everything started working again.

**Comment by Nedo93** [comment]
Not working for me :/

**Comment by mark6ikx** [comment]
I can confirm Overwatch is working fine with my systems along with Shovel Knight, Livelock, Worms, and Shadow Warrior 2 with Aurora disabled on start up and not running. However, enabling Aurora prevents the keyboard being using in cases such as Shovel Knight, Livelock and Worms, whilst overwatch and Shadow Warrior 2 still being fine. With troubles reverting to default profile (Synapse) upon exiting any game specific lighting, whilst Aurora is running.

Strange enough.

Hue (game) on the other hand is only working on Firefly & Mambe TE, and will not work on Blackwidow X Chroma regardless of Aurora running or not. This is with full fresh install of Hue with Aurora disabled too.

The underlying issue appears to be somewhat with Synapse. I have disabled Aurora for the time being during my "play" hours, I'll be looking tomorrow evening if the issues have subsided at all or if anything has changed. Hopefully I can get the logitech games to work and chroma, then I'll be a happy bunny (easter reference).

Good day all.

**Comment by itzfe3ix** [comment]
I have an issue with the Overwatch profile, it doesnt show any layers nor binds or effects. It doesnt load the profile form the chroma and when i open Overwatch, my keyboard (G910) just goes blank, i tried different things. I installed SDK alone and Synapse and aurora, but nothing seems to work. Can someone help me?

**Comment by simon-wh** [comment]
@itzfe3ix It should work when you go in game, it appears that overwatch no longer does the menu lighting on startup since the recent updates.
