### ISSUE TITLE
Lighting feature suggestions

### ISSUE THREAD

**Issue by noisyboi** [antonpup/Aurora#518]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [XXX] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

I apologize if this has been suggested before, but I would really like to see if possible Lighting that can be triggered on and off with a button, let me give you an example of what I mean:

Lets say I have a macro on my keyboard, When I press it I want to also trigger a lighteffect that is on that specific key, or whatever area I have defined, that lighting effect keeps going until I turn off the macro

This somewhat similiar to the "lock color layer" but with much more freedom and could be bound to any key, adding a timer would be nice too since that could essentially allow for cooldown timer effects as well.

**Comment by simon-wh** [comment]
Logic for layers is being worked on here and there, which would allow for parts of the layer to be changed/triggered when a particular variable is reached. For example, you could have something that was "when x key is pressed set opacity to 1" on a solid colour layer, which would allow you to have what you are looking for. If you have any other ideas for actions that should be included in this let me know!

**Comment by Wibble199** [comment]
Can be achieved with the toggle key layer or timer key layer.
