### ISSUE TITLE
Overwatch Issues

### ISSUE THREAD

**Issue by distnz** [antonpup/Aurora#52]
Hi team,

I went to play overwatch today and the keyboard effects now arent working, they were working the other day and nothing has chnged, except for an overwatch update. Can anyone else confirm if they have issues after the latest overwatch update? Im on a G910 and it was working perfectly, but now nothing, They LEDs just go blank, and the aurora software just shows a blank keyboard

**Comment by LaurentTripleOr** [comment]
Did you tried repatching the game?

**Comment by antonpup** [comment]
Can confirm, the overwatch implementation does not work at the moment. I will look into it.

**Comment by distnz** [comment]
Oh excellent, im not going mad :P

**Comment by antonpup** [comment]
So, I repatched it and it works. Try that and make sure you're running Overwatch as admin as explained in issue #42 . See if that works.

**Comment by jdubnz** [comment]
I had this working a few days ago after folling the steps in Issue 42. Has since stopped working again. Tried repatching and still no luck.

**Comment by antonpup** [comment]
Can you please add me on steam, I am unable to reproduce these issues. Even after reinstalling Windows, Aurora functions just fine with Overwatch.

[http://steamcommunity.com/id/pupant](http://steamcommunity.com/id/pupant) (Please comment before adding)

**Comment by jdubnz** [comment]
Have done. Unfortunately I will be away from my desktop for a week. But will still be able to chat on steam. Only things that might be slightly different is Aurora is installed on C drive, Overwatch on D drive. But I gave Aurora the location so that shouldn't be an issue. As of yet I have not tried reinstalling Overwatch to fix the issue.

**Comment by antonpup** [comment]
I have tested Overwatch on my laptop, also couldn't get lighting to work. It ended up working after I installed "Visual Studio C++ 2015 Redistributable" for both 86 and 64 bit. It's listed as one of the steps in #42 not sure if you installed both. But I got it to work like that on a completely isolated machine.

Visual Studio C++ 2015 Redistributable download: 
https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by antonpup** [comment]
I am now also getting inconsistencies with Overwatch. Looking into it.

**Comment by distnz** [comment]
I'm finding it roughly 50\50 if lighting works or not. When it does work its amazing, when it doesn't it is either completely ignored an there's no change, or its lights out. I've tried everything mentioned here but with no noticeable affect on the outcomes. Cheers guys.

**Comment by antonpup** [comment]
@distnz Does the lighting ever just stop working mid-game? I am finding that it is not connecting with Aurora at Razer's Initialization.

**Comment by distnz** [comment]
I've not had that happen to me. Its always upon first game, I can tell at the hero select screen what kind of day its going to be

**Comment by antonpup** [comment]
@distnz Are you going to be around for a little while? I need someone to test a potential fix. Add me on steam if you can. [http://steamcommunity.com/id/pupant/](http://steamcommunity.com/id/pupant/)

**Comment by distnz** [comment]
Unfortunately not tonight, drew the short straw, on late shifts tonight (its nearly 730pm here in NZ)

**Comment by antonpup** [comment]
@distnz @jdubnz Please try using the following "RzChromaSDK.dll" and "RzChromaSDK64.dll". Copy them into your Overwatch directory. Also, make sure to right click on them, go to properties, and make sure to "Unblock" them. Just in-case windows marks them as blocked. Exact changes for these files can be found in this commit: [https://github.com/antonpup/Aurora/commit/292a25a729109846f734f8b1f65dc8449af1e3af](https://github.com/antonpup/Aurora/commit/292a25a729109846f734f8b1f65dc8449af1e3af)

[RZChroma_no_init_check.zip](https://github.com/antonpup/Aurora/files/345798/RZChroma_no_init_check.zip)

**Comment by jdubnz** [comment]
Didn't think I'd get another Kiwi on here! Mine has never stopped working mid game. It just remains as my desktop profile lighting when I launch overwatch. Sorry I can't help with the testing untill next week!

**Comment by antonpup** [comment]
Any results?

**Comment by distnz** [comment]
Hrm, have had a play with it and its a bit buggy. Dosent launch immediatley, and keys go an awful browny orange until i actually start a game, then they seem to work, with a horrible grey blue colour on the unused keys. Then mid game they just stopped working :( Also noted after a reboot they stopped working, unless i deleted the files and recopied an unblocked them

**Comment by antonpup** [comment]
@distnz 
> keys go an awful browny orange until i actually start a game

This is normal, in the Main Menu Overwatch changes the color to a blown-orange.

> a horrible grey blue colour on the unused keys

Can you provide a picture or something? Unused keys are supposed to not light up at all.

> noted after a reboot they stopped working, unless i deleted the files and recopied an unblocked them

Well, that could be one of the reasons why it stops working for people. Thanks.

**Comment by distnz** [comment]
Just jumped on to photo now, and i noticed Overwatch updated again. So now i seem to have different results. Now im back to having to run everything as admin, i still have to copy over the files, and now the unused keys remain that browny orangey dim. Altho i didnt have it drop on me mid game this time

**Comment by jdubnz** [comment]
That grey blue colour might be from setting the keys to white, as opposed to black. The g810 "white" is a greyish blue, whereas black is off. (I think)

**Comment by jdubnz** [comment]
Running everything as admin fixed all problems for me. All correct key colours, and no dropping out. Did not have to recopy files after a system reboot. All working as it should atm, with those new files.

**Comment by antonpup** [comment]
Can you try running Aurora as administrator. Then repatch Overwatch. That might resolve the Overwatch issues, if Aurora has admin access to create dll files.

**Comment by antonpup** [comment]
Please try the wrapper patch with version 0.5.0.

**Comment by jdubnz** [comment]
Was working previously can confirm it is still working. updated and repatched, no need for those custom files.
