### ISSUE TITLE
Logitech G902 Bug

### ISSUE THREAD

**Issue by UltimateUltimo** [antonpup/Aurora#521]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (Logitech G902 Orion Spark)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
The | or \ button should be displaying different colours that I have assigned to my whole keyboard using Aurora

### Actual behavior:
The button stays at a certian colour constantly and even if I try to change the colour in Aurora it still stays constant. If I put an interactive layer, the colour moves out from a different place than where I have pressed the | or \ button.
Edit: Its colour can be changed by the Logitech Gaming Software but when Aurora kicks in, the colour will be the same as the last colour that was displayed when the LGS software was open.

### How often does this problem occur?
This problem occurs all the time I start up the Aurora app

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Get a Logitech G902 Orion Spark
2. Start the Aurora App and you will see the button below backspace is a constant colour

### What is the version of Aurora you are experiencing this issue with?

My version is v0.6.0b

### Does the previous version of Aurora have this issue?
I did not use older versions of Aurora.

### Please include any logs, screenshots, or files that are related to this issue:
Photo of keyboard with RGB from left to right: https://gyazo.com/07063188041ffa05295a9f2a9c0bc264

**Comment by r3sist3nt** [comment]
Have you installed the Logitech gaming software? Can you switch profiles there?

**Comment by UltimateUltimo** [comment]
Yeah its there. I can switch profiles but only in the LGS software does that key light up correctly. Aurora doesn't seem to recognise that key.

**Comment by antonpup** [comment]
Make sure that you are using a proper keyboard layout in the settings. If you have a US keyboard layout, use a US layout in settings.

**Comment by UltimateUltimo** [comment]
Its fixed now. I had to reinstall the OS on my PC, then when I redownloaded Aurora, the lighting is working perfectly.
