### ISSUE TITLE
RGB ZOTAC lighting?

### ISSUE THREAD

**Issue by caw1** [antonpup/Aurora#524]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ x ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ x ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

Is there any possibility to add the lighting of a ZOTAC AMP Extreme to the Aurora profiles? i´ve searched a lot to find out if there is a sdk for it but didnt find anything :-/

**Comment by antonpup** [comment]
If there is no SDK available, then there's not much that I can do in terms of adding support.

**Comment by caw1** [comment]
yeah i understand, i thought maybe some of you have some infos that there is a sdk available. :( but thanks for the reply :)
