### ISSUE TITLE
Aurora stops working on W10 Creators Edition

### ISSUE THREAD

**Issue by aquariorjr** [antonpup/Aurora#529]
### What are you experiencing an issue with?

- [X] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue

### What kind of an issue is it?

- [X] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [X] Crash without message error
- [X] App doesn't work/start

### Expected behavior:
After the Creators Edition mojority update of Windows 10, Aurora stops working, the aplication simply stops after I've started it.

### Actual behavior:
I can't use the Aurora anymore.

### How often does this problem occur?

This problem occurs every single time when I try to start it.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Start the Windows
2. Start Aurora app
3. See the app closing automatically without displaying an error message.

### What is the version of Aurora you are experiencing this issue with?

My version is the latest one (checking the updater on April's 12th).

### Does the previous version of Aurora have this issue?
I don't know.

### Please include any logs, screenshots, or files that are related to this issue:

Logs: https://pastebin.com/99yna1pM

**Comment by antonpup** [comment]
Please look at issue #528 for a solution. Thank you.
