### ISSUE TITLE
Equalizer not working

### ISSUE THREAD

**Issue by UltimateUltimo** [antonpup/Aurora#530]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (Logitech G910 Orion Spark)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Visual equalizer should change to the music that is playing

### Actual behavior:
Visual equalizer is not working or stuck

### How often does this problem occur?
Every time you add an enhancement to your speaker device while Aurora is running, and you start to play music after applying the enhancement, the visual equalizer will not work

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. With Aurora open go to your Speaker's Properties
2. Add or remove an enhancement in there
3. Start playing music with any visual equalizer settings on

### What is the version of Aurora you are experiencing this issue with?
My version is... (v0.6.0b)

### Does the previous version of Aurora have this issue?
Not tested with previous versions of Aurora

**Comment by simon-wh** [comment]
I wasn't able to replicate the issue you're describing. Can you see if you're still experiencing the problem with the [latest development release](https://github.com/antonpup/Aurora/releases)?

**Comment by simon-wh** [comment]
Closed until further details provided.

**Comment by UltimateUltimo** [comment]
Alright here's a better explanation to replicate the issue
1)Play some music and let the equalizer work (I put it as the top layer and the effect type is Power Spectrum)
2)Go to Control Panel
3)Go to Hardware and Sound
4)Go to manage Audio devices (A window will appear with all your sound devices)
5)Left click on the default device you are using.
6)Click Properties
7)Go to Enhancements
8)Click the checkbox on one of the enhancements (You should still be listening to the music)
9)Click apply

Its after you click apply that the bug happens. I installed the latest version of Aurora that was released and the equalizer freezes from the time you click apply. I just tested it and the bug happened.

**Comment by simon-wh** [comment]
@UltimateUltimo I tested it following what you did there and still couldn't replicate it. Are you definitely using v0.6.1-dev2?

**Comment by UltimateUltimo** [comment]
Nope. I tried it again and the same issue happened, here's a small recording: https://youtu.be/hQYvThU8A6Q

Could be my OS since its not the retail version

**Comment by simon-wh** [comment]
I've had a look at this again and I was able to replicate the issue if I change the spatial sound setting which may be linked to the issue you've been getting. Could you try [this build](https://www.dropbox.com/s/e0ufxj9zcubhwhy/v0.6.1-dev3%20visualizer%20test.zip?dl=0) to see if it resolves your issue?

**Comment by UltimateUltimo** [comment]
Seems like the bug is fixed! The equalizer doesn't freeze after adding enhancements or enabling Spatial sound.
