### ISSUE TITLE
CS GO Percent(gradient) Effect layer with the /player/state/health

### ISSUE THREAD

**Issue by caw1** [antonpup/Aurora#531]
### What are you experiencing an issue with?

- [ ] Aurora
- [x] Aurora supported game, CS GO
- [ ] Aurora Wrapper
- [x] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [X] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [x] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

Hi,

i´d like to have a Percent(gradient) Effect layer with the /player/state/health but, i do not find any maxhealth. where can i find it?

thanks for ure help!

kind regards

**Comment by antonpup** [comment]
For csgo, max health is 100. You can also get the pre-made hp layer by resetting the csgo profile.
