### ISSUE TITLE
Aurora Startup Crash

### ISSUE THREAD

**Issue by grimsi** [antonpup/Aurora#532]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Aurora should start

### Actual behavior:
Crash at startup

### How often does this problem occur?

This problem occurs always at startup

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Install Aurora and Dependencies (.NET 4.5 and C++ Redist 2015)
2. Start Aurora
3. Profit?

### What is the version of Aurora you are experiencing this issue with?

My version is the newest Version from the Aurora Homepage (Major: 0.6.0b, Minor: 0.5.2), also tried to build "dev-presentable" myself, same behaviour

### Does the previous version of Aurora have this issue?
Didn't check the previous version, but I think it was 0.6.0a

### Please include any logs, screenshots, or files that are related to this issue:

Screenshot: http://imgur.com/gallery/hMlPX
Log File: https://pastebin.com/UWTWz7dz

**Comment by UnCanard14** [comment]
I had the same problem
You must uninstall Aurora
Before reinstalling it yous must remove a file in
C:\Users\Users\AppData\Roaming\Aurora

1) Uninstall Aorora
2) Remove fil "Aurora" in C:\Users\Users\AppData\Roaming\Aurora
3) And re-install Aurora

**Comment by grimsi** [comment]
Thanks, that worked like a charm!But now im wondering why Aurora doesnt delete this folder when you uninstall it...Am 15.04.2017 1:13 nachm. schrieb UnCanard14 <notifications@github.com>:I had the same problem
You must uninstall Aurora
Before reinstalling it yous must remove a file in
C:\Users\Users\AppData\Roaming\Aurora
Uninstall AororaRemove fil "Aurora" in C:\Users\Users\AppData\Roaming\AuroraAnd re-install Aurora

**Comment by UnCanard14** [comment]
Closed #532
