### ISSUE TITLE
Aurora crashes on Windows 10 after updating to the Creators Update (V 10.0.15063)

### ISSUE THREAD

**Issue by dfg260** [antonpup/Aurora#536]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
something

### Actual behavior:
Explain here what happened instead.
it chashes instantly

### How often does this problem occur?

This problem occurs always

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. update windows 10 to the "creators update"

### What is the version of Aurora you are experiencing this issue with?

My version is 0.6.0b

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.
only tried with 0.6.0b

### Please include any logs, screenshots, or files that are related to this issue:

Log: https://pastebin.com/1x0vcgCQ

**Comment by antonpup** [comment]
Please look at issue #528 for a solution. Thank you.
