### ISSUE TITLE
After Windows Update software doesn't launch

### ISSUE THREAD

**Issue by batuhanapatay** [antonpup/Aurora#537]
The software doesn't launch after the big windows update. I deleted all the files and installed again nothing has changed. (Roaming folder as well)

### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Should launch

### Actual behavior:
Nothing happens

### How often does this problem occur?

Every time after the windows update. The latest big one. 

### Please describe the steps to reproduce this issue:
Just doesn't start.

### What is the version of Aurora you are experiencing this issue with?

The latest one. I don't know because it doesn't launch.
[2017_17_04.zip](https://github.com/antonpup/Aurora/files/925974/2017_17_04.zip)

### Does the previous version of Aurora have this issue?
I don't know.

### Please include any logs, screenshots, or files that are related to this issue:
C:\Program Files\Aurora\logs 

Added as attachment. 
[2017_17_04.zip](https://github.com/antonpup/Aurora/files/925978/2017_17_04.zip)

**Comment by antonpup** [comment]
Please look at issue #528 for a solution. Thank you.
