### ISSUE TITLE
guide for aurora

### ISSUE THREAD

**Issue by UnCanard14** [antonpup/Aurora#538]
Hello @antonpup I started a guide for aurora, and I would like your opinion on the layout. At the moment it is in french but when it is finished I will translate it. It made me think I can translate Aurora in french if you want =)
https://gitlab.com/UnCanard14/GuideForAurora/tree/master
The guide is in .odt I will do this in .md

**Comment by antonpup** [comment]
I saw it when you posted it the first time. I don't speak French, but it looks well organized. If you want to also convert it to HTML, I could post it up on the website as well.

**Comment by UnCanard14** [comment]
OK thank you I will do that.

**Comment by UnCanard14** [comment]
Hi @simon-wh I started a guide for aurora but there is options I don't understand their function, and I do not have all the games :/ cordially.
https://gitlab.com/UnCanard14/GuideForAurora/blob/master/WhatsThePoint.txt

**Comment by simon-wh** [comment]
@UnCanard14 
General Settings:
> Application Detection Method
The two options effectively are:
Windows Events: More efficient but doesn't work 100% of the time (App reading gets triggered from events in windows)
Foreground App Scan: Less efficient but should work 100% of the time (Loop that gets the current process every second)

> Enbale timed blackout of the keyboard
Determines if the keyboard should effectively be turned off at certain times. i.e. if you leave your computer on overnight it could turn off the lighting as it isn't needed

> Aplly timed blackout to game events
I assume it is supposed to make it so the above blackout would apply if you're playing games, but in the current version it doesn't appear to do anything.

> Excluded processes
Processes where the lighting should be shut down which allows you to use native lighting (i.e LGS game effects for a game that LGS supports but Aurora does not)

> Enable nighttime color zones for General Application lighting profiles
Enables the ability to have separate lighting layers at night (will probably be reworked for v0.7.0)

Away Effect:
> Away Effect Type: Dim
Dims the current lighting on the keyboard when the away effect is running.

New Layer
> Percent effect layer
See the default layers: "CPU Usage" and "RAM Usage", I feel as though they are a pretty good demonstration.

> Lock Color Layer
Allows certain keys to be lit up depending on whether one of the lock keys (Caps lock, Scroll lock, Num lock) is enabled or disabled. e.g. Lighting up the numpad red when num lock is off and green when it is on.

> option of certain games
?

**Comment by simon-wh** [comment]
Direct towards #428
