### ISSUE TITLE
G keys and logo stay lit whatever profile/effect is on

### ISSUE THREAD

**Issue by koaxfr** [antonpup/Aurora#54]
as the title says no matter what profile the G keys stay the same color settled by logitech gaming software. Keyboard layout is the right one and you can see in aurora the g keys/logo change color, but not the physical keyboard.

**Comment by antonpup** [comment]
The G-keys and logos are not supported by the Logitech SDK. When they are supported, I will enable updating for those lights.

**Comment by koaxfr** [comment]
wow that is a very fast answer thanks! btw great work ! really amazing
