### ISSUE TITLE
Aurora cannot start after Windows 10 Creators Update.

### ISSUE THREAD

**Issue by Synithin** [antonpup/Aurora#540]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Aurora.exe should start with Windows when computer turns on or when exe file is launched

### Actual behavior:
Aurora.exe starts with computer then immediately crashes/closes. Same for the .exe file, pressed it launches for 1 second then immediately crashes.

### How often does this problem occur?

This problem occurs... (Every Time)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Installing Creators Update on Windows 10 and launching the program.
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (0.6.0b)

### Does the previous version of Aurora have this issue?
The previous version, (did not), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

https://pastebin.com/AjbrMj00

**Comment by UnCanard14** [comment]
You can look at it #528

**Comment by Synithin** [comment]
#528 Fixed the problem for me, thank you. Odd that it only started occuring after the update. But again It is solved.
