### ISSUE TITLE
Sound Bug/Lag with G933 and G35 in connection with LGS

### ISSUE THREAD

**Issue by Zeeanq** [antonpup/Aurora#541]
### What are you experiencing an issue with?

- [x ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [x ] Other, (Logitech Gaming Software)

### What kind of an issue is it?

- [ ] Crash
- [x ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x ] Other, (Sound Bug)

### Expected behavior:
No Laggy/Buggy sound!

### Actual behavior:
If i start aurora and lgs my sound ist buggy like hell.
I cannot here anything without lagging.
i have a g933 and a g35 but both of them are lagging. If i close lgs then aurora isn't able to map the colors.

### How often does this problem occur?
Sometime. But most of the time after 30 minutes of startup the pc

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. PC Startup
2. Going on Teamspeak 3
3. Then after 30 Minutes my G933 ist lagging like hell.

### What is the version of Aurora you are experiencing this issue with?
v 0.6.0b

### Does the previous version of Aurora have this issue?
I don't know. 

### Please include any logs, screenshots, or files that are related to this issue:
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: AWESOME-SYSTEM_
User Name: xx
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

[INFO] 20.04.2017 22:53:35: Program started with '-install_logitech' parameter
[INFO] 20.04.2017 22:53:35: Logitech LED SDK patched successfully

**Comment by magnus97** [comment]
i had the same issue and a lgs update fixed it for me.

**Comment by Zeeanq** [comment]
This issue is permanent on my system.
LGS 8.92.67

**Comment by simon-wh** [comment]
@Zeeanq Could you try using the [latest development release](https://github.com/antonpup/Aurora/releases) to see if it makes a difference?

**Comment by simon-wh** [comment]
@Zeeanq Could you try updating lgs and trying the latest development release as mentioned before? Closing for now.
