### ISSUE TITLE
Custom profiles don't load

### ISSUE THREAD

**Issue by eliyameri** [antonpup/Aurora#542]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [x] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [x ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
I make a custom profile for a game,  when I go into the game it should switch to that profile

### Actual behavior:
Profile stays on the desktop profile, doesn't change to my custom one

### How often does this problem occur?

This problem occurs every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Make new profile, pick the programs .exe
2. Set your lighting themes
3. Go into the game

### What is the version of Aurora you are experiencing this issue with?

My version is 0.6.0b

### Does the previous version of Aurora have this issue?
The previous version, 0.5.1d, did have this issue.

**Comment by antonpup** [comment]
If game is run as admin, and Aurora isn't. Aurora would not be able to detect it. Try running Aurora as admin.

**Comment by eliyameri** [comment]
That didn't work either. I managed to get a log file

**https://pastebin.com/ytBVmiXQ**

**Comment by eliyameri** [comment]
@antonpup Well i've been trying to get the profile to work for rainbow six siege, and im beginning to think it's just a problem with that game specifically. I tried other programs and one other game and it worked for the other games
