### ISSUE TITLE
Very bad lag with my lighting profiles

### ISSUE THREAD

**Issue by eliyameri** [antonpup/Aurora#543]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Setting a breathing layer, there should be a smooth transition between colours. Same with a wave layer. On interactive layers (key fade) the key should be lighting up as soon as I press the button, not with a delay.

### Actual behavior:
When i set a breathing layer for example, the transition between the two colours is very laggy, like there's stutters in between the colour changes. Another problem is that the interactive layers also stutter (if i set something like arrow flow) and if I set key fade, the key actually lights up maybe around half a second after I've pressed it

### How often does this problem occur?
Happens 99% of the time, sometimes if I'm lucky it doesn't happen when i start Aurora but it starts lagging again after that.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Set any sort of moving layer

### What is the version of Aurora you are experiencing this issue with?

My version is 0.6.0b

### Does the previous version of Aurora have this issue?
The previous version 0.6.0 did have this issue.

### Please include any logs, screenshots, or files that are related to this issue:
I tried getting a log but in the logs folder it doesn't update. It still has logs from a couple of days ago

**Comment by antonpup** [comment]
If you have a Corsair keyboard, make sure that you have enabled 16 million colors setting. (I don't have CUE installed, but I know when that option is disabled in CUE, then device has issues with displaying gradient colors).

**Comment by simon-wh** [comment]
Any updates on this?
