### ISSUE TITLE
G810 media keys & M65 mouse

### ISSUE THREAD

**Issue by alster551** [antonpup/Aurora#544]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x ] Device issue
- [x ] Other, (Fill in another type of issue here)

### Expected behavior:
For the keyboard there are no way to include the media keys and caps/numlock indicators

Mouse should change with keyboard

### Actual behavior:
Mouse does not light up at all

### How often does this problem occur?

This problem occurs every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1.  Connecting mouse/keyboard
2.  Running Aurora
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... beta v0.6.0b

### Does the previous version of Aurora have this issue?
Yes

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by antonpup** [comment]
Have you selected a mouse in the settings?

As for media/lock indicators, those aren't part of Logitech LED SDK.
