### ISSUE TITLE
Aurora not properly working with CM Masterkeys Pro L RGB

### ISSUE THREAD

**Issue by OrbitTurtle** [antonpup/Aurora#549]
Heyo!

I own a Cooler Master Masterkeys Pro L RGB and I tried out aurora on rocket league but it doesn't seem to be changing the color of my keyboard, it just stays on a static blue and isn't giving me a boost indicator or a score indicator.
I don't know if I am doing something wrong or if the program isn't optimized for the masterkeys pro L series yet.

If you'd like someone to test aurora on a cooler master masterkeys pro L I can help you out ;)

**Comment by antonpup** [comment]
Rocket League support has been broken for ages. That's why it doesn't work.

**Comment by OrbitTurtle** [comment]
> Rocket League support has been broken for ages. That's why it doesn't work.

So it should basically work on other games? Are you going to fix rocket league? Or is it something in the game that broke it?

**Comment by OrbitTurtle** [comment]
Also, I just noticed the P1 to P4 keys aren't lighting up ;)

**Comment by antonpup** [comment]
It should work with other games. I just can't be bothered to find new pointers for Rocket League.

**Comment by simon-wh** [comment]
Could you see if everything is working for other games?

**Comment by hsnabn** [comment]
Aurora seems working fine on 0.6.0b except for two things:
- Applying to Numpad 4 affects Numpad 5 -- applying to Numpad 5 affects Numpad 6
- P1 through P4 (read next point) keys do not work
- Applying to Pause key does not work -- however, applying to P4 applies to Pause key successfully

**Comment by brainbug89** [comment]
I looked into the docs of the CoolerMasterSDK and [line 92-94](https://github.com/antonpup/Aurora/blob/462df29fb572a0fbad2d21ea81b2a8ea97a6d1a4/Project-Aurora/Project-Aurora/Devices/CoolerMaster/CoolerMasterDevice.cs#L92) seems to be correct according to the given numbers in the documentation.

**Comment by simon-wh** [comment]
Does anyone have the numpad lighting problem on Cooler Master devices other than the Masterkeys Pro L? As I might just add a minor change to the coords for the lighting of those numpad keys even though it should be correct according to the docs.

**Comment by simon-wh** [comment]
@hsnabn I've added a commit that hopefully will resolve the numpad mapping, however the P1-P4 keys and pause keys match the documentation just like the numpad ones. Could you try downloading the [CM SDK](http://makerhub.coolermaster.com/custom-lighting/) and use the example to try setting the lights to see what coordinates work for those keys? You can find the listed coords under SDK in the zip.

**Comment by froe** [comment]
Pause,P1-P4 works with the given coordinate 

Pause 0,17

P1      0,18
.
.
P4      0,21

Also something else.

numpad 4-6 works with 3,18  3,19  3,20

all of this tested with the example exe found in the sdk folder.

**Comment by simon-wh** [comment]
@froe Hmm, I'm really unsure why it isn't working properly then because that would say that the coords given are correct, but the mapping we have is the same as what is listed. I'll try and look into this a bit more.

**Comment by hsnabn** [comment]
In the latest version v0.6.1-dev3, The P1-P4 keys light up correctly, as well as Numpad 4-5, but Numpad 6 does not work.

In the SDK example, coordinates work and light up the keys as per @froe's observations (i.e. according to the SDK document).

**Comment by froe** [comment]
any solution yet ?

**Comment by kythre** [comment]
I had this problem with my 4 key (and P1-4) then I installed release_major_0_6_1-dev3 and it switched to my 5 key. I then switched to release_major_0_6_1-dev2 and everything seems to be in working order now.

**Comment by simon-wh** [comment]
@kythre I'll try switching it back in the next build to what you have listed there. I don't know why it's such a hassle to get this working consistently.

**Comment by Millidan** [comment]
Hello, when are you going to release the new build with the fixed lighting for 4-5-6 keys on the MasterKeys Pro L? 

Thank you

**Comment by simon-wh** [comment]
@Millidan I'm not sure, I wanna fix a few more bugs then I'll try and get it out. I believe there are some more bugs with some of the stuff I've introduced so I don't want to release a really buggy dev build to be the goto one

**Comment by simon-wh** [comment]
@Millidan I've release [v0.6.1-dev4](https://github.com/antonpup/Aurora/releases). Could you try that and see if it sorts it out for you?

**Comment by Millidan** [comment]
@simon-wh Hey, Unfortunately I had to RMA my CM keyboard and I will have it back within a week .

**Comment by Millidan** [comment]
I've got my MK Pro L back and downloaded v0.6.1-dev4 and everything works perfectly, Thank you <3

**Comment by Millidan** [comment]
@simon-wh Actually in this new build the Enter key doesn't light up anymore XD

**Comment by simon-wh** [comment]
@Millidan Could you try out [this build](https://ci.appveyor.com/project/antonpup/aurora/build/artifacts) from the commit above?

**Comment by Millidan** [comment]
@simon-wh Tried that build, All the keys light up perfectly. Thank you for the effort.

**Comment by simon-wh** [comment]
Can someone with a Pro L try out [this build](https://ci.appveyor.com/project/antonpup/aurora/build/0.6.1-dev4-304/artifacts) to verify that Pro L support has not been affected by the changes for the MK750?
