### ISSUE TITLE
Razer Firefly

### ISSUE THREAD

**Issue by koaxfr** [antonpup/Aurora#55]
any support for the mousepad razer firefly? Aurora detects an mouspad but cant modify anything from it.

**Comment by antonpup** [comment]
Sure, I can try adding something for it. It will most likely just take the same color as the mouse/headset.

**Comment by koaxfr** [comment]
sounds good ! My mouse doesnt have any rgb lighting on it anyway nor does my headset.

**Comment by antonpup** [comment]
I made adjustments for Razer Devices. Razer Headsets and Mousepads will now be treated as a peripheral device.

This will be included in the next version of Aurora. Thank you for the suggestion. :)
