### ISSUE TITLE
Logitech Wrapper Not Working for The Division

### ISSUE THREAD

**Issue by Atom88884444** [antonpup/Aurora#550]
### What are you experiencing an issue with?
- [x] Aurora supported game, The Division
- [x] Aurora Wrapper

### What kind of an issue is it?
- [x ] Other, Game controlled lighting effects don't work.

### Expected behavior:
Keys should light up based on health, cooldowns, ammo, etc.

### Actual behavior:
Only static lighting effects that I add in Aurora work. There are a lot of errors in the log but I don't really know what to make of them. I've tried disabling the profile and settings in LGS but that just gets rid of the effects entirely. I've deleted and reinstalled the wrappers as well. The only thing I haven't done is reinstall Aurora. I've only included a small portion of the log since it is too big for pastebin but it basically repeats the same few warnings over and over again many times.

### How often does this problem occur?
This problem occurs every time.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Patch Logitech LED SDK in Aurora
2. Launch The Division

### What is the version of Aurora you are experiencing this issue with?
My version is beta v0.6.0b

### Please include any logs, screenshots, or files that are related to this issue:
https://pastebin.com/QbCPMynP

**Comment by antonpup** [comment]
I am sure I've fixed this in the dev version a few months ago. But I will check again.

**Comment by Atom88884444** [comment]
Any updates?

**Comment by antonpup** [comment]
I have to do other things besides Aurora development. In any case, even if I was to look into this issue immediately, the changes would go to the dev branch, which would still need to be prepared for a release.

So update, I haven't checked anything yet. Was working on the Diablo 3 issue.

**Comment by Atom88884444** [comment]
Ok, that's fine I was just wondering. Thank you so much for all your hard work.

**Comment by antonpup** [comment]
You could test with the latest pre-release. I just put it up. Should be under the Releases tab on Github.

Direct further questions to @simon-wh

**Comment by simon-wh** [comment]
The issue should be fixed so closing due to no follow up. @Atom88884444 Could you try the latest pre-release to confirm that the issue has been resolved?

**Comment by Atom88884444** [comment]
Yeah it's working now thanks

**Comment by Wizzzzzard** [comment]
I just signed up, I downloaded Aurora last night hoping to get my bw chroma working with the division led keyboard support but no luck, the option to enable it in game is greyed out, Aurora appears to be working because it changed the lighting profile after installing it.

After reading this post I spent ages looked for the pre-release tab and eventually I found the link below.
https://github.com/antonpup/Aurora/releases/tag/v0.6.1-dev

I don't know if it's the right one but it doesn't allow me to enable the LED keyboard support option in game either.

Can anyone help?

**Comment by simon-wh** [comment]
@Wizzzzzard Did you make sure to patch the game after updating?

**Comment by Wizzzzzard** [comment]
Hi, thanks for the reply.

I clicked Patch Logitech LED SDK a number of times.

**Comment by slupton89** [comment]
Same problem with it not working after patching. It doesn't seem like the patch button does anything.
