### ISSUE TITLE
Address individual LEDs on Razer Firefly

### ISSUE THREAD

**Issue by GallopingCow** [antonpup/Aurora#552]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [x] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [x] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
I would absolutely love more/better support for the Razer Firefly mousepad. Aurora will currently recognize it as a mouse and activate all of the LEDs in a color, but it would be great to be able to address each of the LEDs individually to create waves around the mousepad.

### Actual behavior:
Explain here what happened instead.

### How often does this problem occur?

This problem occurs... (Fill in here)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. 
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (Fill in here)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by antonpup** [comment]
There is a slight issue with this. There's not enough space for a full mousepad design in Auroras UI. Maybe Simon can add it later on. But as of right now, I cannot add it due to how cramped the UI already is.

**Comment by GallopingCow** [comment]
I don't see how this would even be necessary as there is already a dropdown for mouse orientation and it would simply use the same position. It would be super nice to have the option to rotate the mousepad and have greater flexibility in the position of the mouse/pad using arc degrees or clock position in relation to the keyboard, but really I think my most missed feature is having the Equalizer Layer "climb" up from the bottom-center of the mousepad as seen [here](https://insider.razerzone.com/index.php?threads/rock-your-razer-chroma-devices-with-the-audio-visualizer.8796/).

**Comment by antonpup** [comment]
At the core, Aurora operates by mapping regions on an image to keys or lights. There exist two mappings, one mapping is for the image, it dictates which regions of the image to read for the color. And second mapping is the virtual keyboard seen on the main UI. If I were to make the two mappings different. Then free styling on the keyboard will not function properly, as there will either be a jump in assigned key light. Another issue is that if you don't have a key represented in the virtual keyboard, you will not be able to assign those keys.

So it is best to keep the two mappings as close to 1:1 as possible. If I was to add "invisible mouse mat lights" especially rotating ones (like you mentioned) will cause the disconnect between image mapping and virtual keyboard mapping.

Rotating is especially a big problem, because a square rotated by 45 degrees takes up more physical space to represent the same sized square. Thus it would make image mapping with margins on top and bottom, and without a virtual keyboard mapping for it, would break the freestyle entirely.

**Comment by GallopingCow** [comment]
Thanks for the excellent explanation. A part of me thought it might work this way with the color mapping, but I was hoping the backend was different somehow.

Would it be possible to add a rectangular box around the mouse in the existing space to define the lights? This would squeeze the mouse mat horizontally, but you would at least be able to have the full height of the keyboard represented.

**Comment by antonpup** [comment]
You can't, they would then be overlapping with the mouse image/lights on the virtual layout. Then another problem is, each mouse is of different size. I believe "generic peripheral" is 6x6 pixels or so. And as a result, it won't map properly to real life mousemat lights. If top of mousemat has 20 lights, but the selected mouse is of 12 pixels with of image mapping, so you would lose some light, or they will be abnormally same mapping.

And so, if i was to create a circle originating from center of mousemat, it wouldn't light up in a uniform circle motion, but rather an oval-like motion. Which I would find unacceptable for a feature. I would prefer to make everything as close to 1:1 for simplicity on user's end and development end.

**Comment by GallopingCow** [comment]
The Razer Firefly only has lights around the sides and bottom, so I had envisioned a U shaped line just going around the mouse image with the mouse centered over it.

Even if this is treated as two new columns worth of keys on a keyboard, a row height of 8 pixels would be enough to turn on all of the lights.

Please forgive me if my persistence is annoying. It's just a feature I would really love to see.

**Comment by brainbug89** [comment]
Mousepad support would be nice. Also for the Corsair MM800 Polaris or the Steelseries QcK Prism.

**Comment by Dlaw2017** [comment]
I also agree, I have both the Firefly and Polaris, and I would love to control the lights on them individually.

**Comment by simon-wh** [comment]
Fixed thanks to #1331!
