### ISSUE TITLE
DPI light on M65?

### ISSUE THREAD

**Issue by Dlaw2017** [antonpup/Aurora#553]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (Corsair M65 Pro RGB)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [x] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Just wondered if I'm missing something, or I really can't control the DPI light on my new mouse? I've been using Aurora with my K70 and Firefly, and I just got my new M65 and MM800 RGB Polaris today.

### Actual behavior:
Light is out.

### How often does this problem occur?

This problem occurs... (every time.)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. 
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (0.6.0b)

### Does the previous version of Aurora have this issue?
I haven't tried

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by brainbug89** [comment]
I think you can't change the DPI light through the CUE SDK. The DPI light is controlled within the CUE DPI setting.

**Comment by Dlaw2017** [comment]
Not true, all lighting is handed off to Aurora.

**Comment by brainbug89** [comment]
Maybe `CorsairLedId B5` and `CorsairLedId B6` needs to be added to `CorsairDevice.cs`

**Comment by Dlaw2017** [comment]
Is that something I can do? I'm not home right now, but if so I'll try it tonight.

**Comment by Dlaw2017** [comment]
And I misread your first post, I thought you said it can be changed via CUE.

I downloaded the SDK, but I can't make sense of the documentation. Again, I'll mess with it when I get home.

**Comment by simon-wh** [comment]
Apparently, the DPI light cannot be changed through the SDK according to [this issue](https://github.com/DarthAffe/CUE.NET/issues/43)

**Comment by Dlaw2017** [comment]
Well that stinks. I guess I'll post over on Corsair forums and see if we can't get it added.

**Comment by Dlaw2017** [comment]
Whelp, went over there and posted. Friday. I know it's the weekend, but some kind of response would have been nice. Oh well, I'll wait a couple more days.
