### ISSUE TITLE
Game Support for Player Unknown Battlegrounds

### ISSUE THREAD

**Issue by Boiijek** [antonpup/Aurora#555]
### What are you experiencing an issue with?

- [ ] Aurora
- [x ] Aurora supported game, (Player Unknown Battlegrounds)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

Profile does not change when game has been launched. Have already set the target file but to no avail.
I am aware it is a new game so you might have to add support for it but I am just letting you know. Wonderful program otherwise

**Comment by TristanPra** [comment]
It could be great to have lights on the game ! looking forward to news !

**Comment by simon-wh** [comment]
Currently, there doesn't appear to be any way to realistically implement support for PUBG. Closing until further notice.
