### ISSUE TITLE
Turkish Localization for Logitech G810

### ISSUE THREAD

**Issue by KurbagaKermit** [antonpup/Aurora#557]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?
- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [x] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
In Interactive Layer type mode, 4 keys flashing/colouring etc. wrongly.

### Actual behavior:
First of all, I love this program. Thank you for this bro o7
Like a said, i have Localization problem for "Ö", "Ç", ":" and ";" buttons. 

This link will show you the Turkish keyboard layout = http://prnt.sc/f548td
OR
In Turkish Keyboard

  "<" -- "Ö"
  ">" -- "Ç"
  "?" -- ":"
  " \ " -- ";"

I have only visual problem for only this 4 keys, my keyboard working nicely. So it's not critical but a little bit annoying :(

In International Keyboard:
Pressing "<" button, triggering "?" button. 
Pressing ">" button, triggering " \ " button.
Pressing "?" button, triggering ">" button.
Pressing " \ " button, triggering "<" button.

### How often does this problem occur?
This problem occurs every time.

### What is the version of Aurora you are experiencing this issue with?
My version is beta v0.6.0b.

### Does the previous version of Aurora have this issue?
Nope, I'm newbie.

My English is not perfect, sorry for this. I hope I could tell my problem. Have a nice day

**Comment by simon-wh** [comment]
When you say Pressing x button, triggering x button. Using "Pressing "<" button, triggering "?" button." does it mean when you press "<" on your keyboard the button displayed as "?" in Aurora is triggered?

**Comment by KurbagaKermit** [comment]
@simon-wh  yes, that's right.
