### ISSUE TITLE
Game-specific lighting effects and volume overlay aren't working in new pre-release

### ISSUE THREAD

**Issue by Atom88884444** [antonpup/Aurora#558]
### What are you experiencing an issue with?
- [x] Aurora

### What kind of an issue is it?
- [x] Performance problems

### Expected behavior:
Opening a game with lighting effects should cause those lighting effects to appear. Changing the volume should also make the function keys light up in accordance to the volume.

### Actual behavior:
Only the desktop profile ever displays. Also, changing the volume freezes all of the lighting until I stop changing it and does not light up the keys like it should. I've reinstalled Aurora, updated all of the wrappers, run it as administrator, and changed the app detection method back and forth multiple times.

### How often does this problem occur?
This problem occurs every time.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Launch Aurora
2. Open game OR Change volume

### What is the version of Aurora you are experiencing this issue with?
My version is v0.6.0-dev

### Does the previous version of Aurora have this issue?
The previous version, v0.6.0b did not have this issue, although I updated in order to see if it would fix my problems with another game, however, due to changes in the way that profiles work in this update, I cannot go back to the previous version while still keeping my profiles.

### Please include any logs, screenshots, or files that are related to this issue:
- http://s000.tinyupload.com/?file_id=62520983211808923527

**Comment by simon-wh** [comment]
I was able to replicate the issues you were experiencing, however, I was not getting the same exceptions that were shown in the log you attached. Although, I have resolved the issues I was experiencing that were similar to what you described, could you see if this [build](https://puu.sh/vOfor/cfdfd621a0.zip) sorts everything out?

**Comment by Atom88884444** [comment]
Yes, that build fixes my issues. Thank you so much!
