### ISSUE TITLE
Is there anyway to setup up the mad catz strike 7 keyboard with aurora?

### ISSUE THREAD

**Issue by zachwolfgang** [antonpup/Aurora#559]
I dont know much about aurora, but i know in the faq it says it will support anything that has an sdk, well i have the sdk for the mad catz strike 7 and i was wondering if there is a way to configure it or do they just mean they will be able to add it one day if the product has an sdk? any help is greatly appreciated

**Comment by simon-wh** [comment]
From what I was able to find it seems that the SDK for that keyboard is only for the touchscreen that it has. Which I don't think would be much use for integration with Aurora.
