### ISSUE TITLE
League of Legends lightFX not working

### ISSUE THREAD

**Issue by ColinCee** [antonpup/Aurora#563]
I have a logitech G910 and I have followed all the steps to patch league of legends, but in the end nothing happens when I get into game. Also the league of legends layers are empty, I'm not sure if its supposed to be.

[2017_14_05.txt](https://github.com/antonpup/Aurora/files/999061/2017_14_05.txt)

http://i.imgur.com/dH7Lsjo.png

I've have looked at issues [#42](https://github.com/antonpup/Aurora/issues/42) and [#291](https://github.com/antonpup/Aurora/issues/291) but I still can't fix it.

### What are you experiencing an issue with?

- [ x] Aurora Lighting issue

### What kind of an issue is it?

- [x] Other, (League of legends LightFX doesn't work.)

### Expected behavior:
I'm not even sure what is supposed to light up.

### Actual behavior:
Whenever I'm in game there is no lighting.

### How often does this problem occur?

This problem occurs... (Fill in here)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

Take damage or die in game, nothing happens in they keyboard, all black.

### What is the version of Aurora you are experiencing this issue with?

My version is... 0.6b

### Does the previous version of Aurora have this issue?
My first time using aurora, not sure.

**Comment by computerboy0555** [comment]
Had the same issue, make sure that inside the game the option of "Alienware lightfx" is active. not sure where is it exactly.

**Comment by ColinCee** [comment]
Thanks, I got it to work now

**Comment by Dioburando** [comment]
I can't find it I looked everywhere and still can't find it I even saw videos of its location but it's not there for me

**Comment by Dioburando** [comment]
Did league of legends removed it in the past months??

**Comment by computerboy0555** [comment]
@Dioburando Have you applied the patch as needed? the option should be here https://imgur.com/a/MtyLq
