### ISSUE TITLE
CS:Go Enhancement

### ISSUE THREAD

**Issue by KensonN** [antonpup/Aurora#567]
CS:GO just released an update with game state integration for timeouts, match pausing, and for the bomb defuse countdown. I'm sure y'all can integrate this somehow

**Comment by simon-wh** [comment]
I'll definitely try and make use of those additional features

**Comment by simon-wh** [comment]
I've added support for reading the added data, what I found was not as good as I was expecting but it's been put in and will be available in the next release.
