### ISSUE TITLE
Access Violation on Windows 10 version 1703

### ISSUE THREAD

**Issue by TheLinthus** [antonpup/Aurora#570]
Aurora **exit on code 0xff** or **crash with Access Violation Exception** (seems to be more rare get the Access violation Exception)

### Expected behavior:
Opening the main window GUI.

### Actual behavior:
Aurora closes immediately when the GUI should be displayed.

### How often does this problem occur?
This problem occurs every single time.

### What is the version of Aurora you are experiencing this issue with?
My version is 0.6.0b

### Please include any logs, screenshots, or files that are related to this issue:

VS2015 Debbug Log: https://pastebin.com/zNurS5sk

The problems started to happens after Windows 10 version 1703's update.
If you change Program.cs:246 **WinApp.Run(MainWindow);** for **while(true)** the program runs without any problem, but no GUI. Maybe some new countermeasure is blocking something on the program GUI.
It worked very well before the update, including with some modifications.

Debug with Access Violation:
`The program '[6784] Aurora.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.`

**Comment by simon-wh** [comment]
Does Visual Studio show you any exception? Or does it just close?

**Comment by TheLinthus** [comment]
Sometimes
`The program '[9528] Aurora.exe' has exited with code 255 (0xff).`
and sometimes
`The program '[6784] Aurora.exe' has exited with code -1073741819 (0xc0000005) 'Access violation'.`

The problem is, I can't debbug, because it is happening on `System.Windows.Application.Run(Window)`

**Comment by TheLinthus** [comment]
Found out **d3d9.dll** causes Access Violation error.

**Comment by TheLinthus** [comment]
# Solved
### The problem
The **d3d9.dll** is used for some monitoring applications, such **MSI Afterburner**, due poor implementation of something, it may causes other DX9 applications to crash, and **Windows Presentation Foundation (WPF)** uses it. This issue only came up with the latest Windows update.
### Solution
Disable **MSI Afterburner** from start with Windows, then restart your computer
