### ISSUE TITLE
Key light toggle?

### ISSUE THREAD

**Issue by TheLunaLeo** [antonpup/Aurora#572]
Would it be possible or is it already possible to add a layer that would change color each time the button is pressed: for example my  keyboard has the win lock button i want it to be one color when its on and one color when its off

**Comment by simon-wh** [comment]
I will try and make this possible through the development of Layer Logic (i.e. Layers having an area where particular events/checks change an aspect of the layer).

**Comment by Wibble199** [comment]
This is now complete as of 92f2771.

**Comment by SvetlozarValchev** [comment]
This still doesn't solve the win lock key issue. Aurora doesn't detect the 'profile', 'backlight' and 'winlock' keys so they can't be used with the 'Toggle Layer'. It does detect 'Mute Volume' and Media buttons (stop, forward, back, play/pause), although they don't have a backlight. The former 3 buttons mentioned do have an RGB light, but they are not registered by Aurora.
