### ISSUE TITLE
Aurora crashes on startup

### ISSUE THREAD

**Issue by lunks** [antonpup/Aurora#575]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
Aurora should open.
### Actual behavior:
Aurora crashes.

### How often does this problem occur?

This problem occurs everytime. It seems it started to happen after I installed overwatch. Getting the latest dev version didn't work.

### Please describe the steps to reproduce this issue:
Not applied (run, crashes)

### What is the version of Aurora you are experiencing this issue with?

My version is... 0.6.0 installed using installer, 0.6.0dev2 just running the program directly after extracting it.

### Does the previous version of Aurora have this issue?
Not sure

Screenshot:
![crash](https://cloud.githubusercontent.com/assets/91118/26508097/ab0f3e3a-4229-11e7-88f8-2bb8c3a80ae8.png)

**Comment by simon-wh** [comment]
Try deleting the save folder (%appdata%/Aurora)

**Comment by lunks** [comment]
It still doesn't run. Logs say only:

``` 
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Executing Directory: C:\Users\pnasc\Downloads\release_major_0_6_0-dev2
Launch Directory: C:\Users\pnasc\Downloads\release_major_0_6_0-dev2
Processor Count: 4
User Name: pnasc
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: False
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

[INFO] 5/26/17 18:26:55: Loading Configuration
[INFO] 5/26/17 18:26:55: Loading Profiles
[INFO] Profiles directory for Desktop does not exist.
[INFO] Profiles directory for Dota 2 does not exist.
[INFO] Profiles directory for CS:GO does not exist.
[INFO] Profiles directory for GTA 5 does not exist.
[INFO] Profiles directory for Rocket League does not exist.
[INFO] Profiles directory for Overwatch does not exist.
[INFO] Profiles directory for Payday 2 does not exist.
[INFO] Profiles directory for The Division does not exist.
[INFO] Profiles directory for League of Legends does not exist.
[INFO] Profiles directory for Hotline Miami does not exist.
[INFO] Profiles directory for The Talos Principle does not exist.
[INFO] Profiles directory for Battlefield 3 does not exist.
[INFO] Profiles directory for Blacklight: Retribution does not exist.
[INFO] Profiles directory for Magic: The Gathering - Duels of the Planeswalkers 2012 does not exist.
[INFO] Profiles directory for Middle-earth: Shadow of Mordor does not exist.
[INFO] Profiles directory for Serious Sam 3 does not exist.
[INFO] Profiles directory for Robot Roller-Derby Disco Dodgeball does not exist.
[INFO] Profiles directory for XCOM: Enemy Unknown does not exist.
[INFO] Profiles directory for Evolve Stage 2 does not exist.
[INFO] Profiles directory for Metro: Last Light does not exist.
[INFO] Profiles directory for Guild Wars 2 does not exist.
[INFO] Profiles directory for Worms W.M.D does not exist.
[INFO] Profiles directory for Blade and Soul does not exist.
[INFO] 5/26/17 18:26:56: Loading Device Manager
```

**Comment by simon-wh** [comment]
Does it shut down without displaying anything?

**Comment by lunks** [comment]
Yes, it does.

**Comment by Eps77** [comment]
I also have the same exact issue

**Comment by simon-wh** [comment]
Could anyone with the issues mentioned here test [this build](https://goo.gl/GE1n8H) to see if the issue persists?

**Comment by Eps77** [comment]
Working!

**Comment by simon-wh** [comment]
@lunks could you also try the build posted above to see if it resolves your issues as well?

**Comment by lunks** [comment]
It also crashes similarly. I see Aurora and Aurora-Updater on task manager, then it crashes. Logging (after deleting everything and running it again) only seems to indicate it crashes on ` Loading Device Manager`, @simon-wh:

```
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Executing Directory: C:\Users\pnasc\Downloads\v0.6.0-dev3+TEST
Launch Directory: C:\Users\pnasc\Downloads\v0.6.0-dev3+TEST
Processor Count: 4
User Name: pnasc
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: False
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

[INFO] 6/1/17 17:01:27: Loading Configuration
[INFO] 6/1/17 17:01:27: Loading Plugins
[INFO] 6/1/17 17:01:27: Loading Applications
[INFO] 6/1/17 17:01:27: Loading Device Manager
```

**Comment by lunks** [comment]
`Aurora.pdb` attached:
[Aurora.zip](https://github.com/antonpup/Aurora/files/1045913/Aurora.zip)

**Comment by simon-wh** [comment]
@lunks Could you try [this build](https://goo.gl/LBw1vr) and get the log output?

**Comment by lunks** [comment]
Same thing:

```
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Executing Directory: C:\Users\pnasc\Downloads\v0.6.0-dev3 TEST
Launch Directory: C:\Users\pnasc\Downloads\v0.6.0-dev3 TEST
Processor Count: 4
User Name: pnasc
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: False
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

[INFO] 6/1/17 18:02:26: Loading Configuration
[INFO] 6/1/17 18:02:26: Loading Plugins
[INFO] 6/1/17 18:02:26: Loading Applications
[INFO] 6/1/17 18:02:27: Loading Device Manager
```

**Comment by lunks** [comment]
Is there a better way I can help you debugging it? I'm a dev even though this is my gaming-only PC.

**Comment by simon-wh** [comment]
If you were able to get it running through Visual Studio on a debug build and find the exception that is causing it to crash that would be very helpful.

**Comment by lunks** [comment]
@simon-wh Ok, downloading Visual Studio to give it a spin. If there's anything else, let me know.

**Comment by lunks** [comment]
While trying to install Visual Studio its installer didn't run also, so I suspected something was wrong on my side. After a little debugging it looks like MSI Afterburner is the culprit, like in #173.

After closing Afterburner and running the newer version it worked fine. The stable version now gives me the same dialog box as on the issue description, which is expected.

Thanks a lot for helping out! Cheers! 🍻
