### ISSUE TITLE
CSGO lights dont work

### ISSUE THREAD

**Issue by jebus-chris** [antonpup/Aurora#576]
### What are you experiencing an issue with?

- [ ] Aurora
- [x] Aurora supported game, (csgo)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
The game should launch and the lights should trun on

### Actual behavior:
I launch the game and the lights dont change at all (i have pached the software and unpatched many times)

### How often does this problem occur?
 (Every time i launch)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. launching csgo with the software 

### What is the version of Aurora you are experiencing this issue with?
0.6.0 dev2
### Does the previous version of Aurora have this issue?
 (0.6.0 dev), did have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

https://pastebin.com/bhs9ha3Z

**Comment by simon-wh** [comment]
Does the issue occur with the previous public build(v0.6.0b)?

**Comment by jebus-chris** [comment]
well i tryed to install it but it keeps failty crashing

**Comment by jebus-chris** [comment]
http://prntscr.com/fciuu8

**Comment by rabbled** [comment]
delete or rename your existing "Aurora" folder within C:\Users\*your username*\AppData\Roaming

run aurora again

**Comment by jebus-chris** [comment]
could you add me on steam and try to walk me through it. I cannot seem to find it

**Comment by rabbled** [comment]
press windows key + r, enter %appdata%

**Comment by jebus-chris** [comment]
ok

**Comment by jebus-chris** [comment]
it does not come up

**Comment by jebus-chris** [comment]
i got it fixed thank you
