### ISSUE TITLE
Lightning issue switching between razer and aurora profiles resulting in flickering

### ISSUE THREAD

**Issue by MGThePro** [antonpup/Aurora#577]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [X ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [X ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
The profile set in Aurora should be shown on the device and that of the official peripheral should be ignored

### Actual behavior:
Both kind of show on my keyboard, resulting in flickering switching back and forth between the profiles of Aurora and Razer Synapse

### How often does this problem occur?
This problem occurs on some (but not all) starts of aurora

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. -
2. -
3. -
sadly I don't know how to reproduce it

### What is the version of Aurora you are experiencing this issue with?

My version is beta 0.6.0-dev-2

### Does the previous version of Aurora have this issue?
I had the same issue on another Version, I think it was v0.6.0(b) (not exactly sure)

### Please include any logs, screenshots, or files that are related to this issue:
log: https://pastebin.com/Y62C82KM
not sure if it helps though

**Comment by simon-wh** [comment]
@MGThePro Are you using both a Razer keyboard and a Razer mouse? and are you trying to have Aurora be used for just the keyboard and Razer Synapse used just for the mouse? Could you try the [latest development release](https://github.com/antonpup/Aurora/releases) to see if it makes a difference?

**Comment by MGThePro** [comment]
I do not have another RGB Device connected to my computer. This Problem doesn't happen to me anymore, but I don't know if the newest development release fixed it for me because I do not know if I have installed it before (not fresh installation = still says beta 0.6.0-dev2 in about)

**Comment by simon-wh** [comment]
@MGThePro I forgot to update the version in the About. If you installed the newest version it should be the 0.6.1-dev. When did the issue fix? was it after you installed the new version?

**Comment by MGThePro** [comment]
Oh if you only forgot to change that in 0.6.1-dev then the new version seems to have fixed it for me

**Comment by simon-wh** [comment]
Awesome, glad to see that it is fixed!
