### ISSUE TITLE
League AZERTY issue

### ISSUE THREAD

**Issue by sofianegargouri** [antonpup/Aurora#578]
### What are you experiencing an issue with?

- [ ] Aurora
- [x] Aurora supported game, (League of Legends)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
AZER should be in blue for AZERTY keyboards

### Actual behavior:
QWER are highlighted

### How often does this problem occur?

This problem occurs everytime

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Intall Aurora
2. Configure League and LightFX

### What is the version of Aurora you are experiencing this issue with?

My version is 0.6.0b

### Does the previous version of Aurora have this issue?
First time I use Aurora

### Please include any logs, screenshots, or files that are related to this issue:

![image](https://cloud.githubusercontent.com/assets/4323986/26530007/1716d422-43cd-11e7-85e0-59fbb2c21c34.png)

**Comment by simon-wh** [comment]
You can change the highlighted keys in the "Color Zones" tab
