### ISSUE TITLE
Installed Aurora. cant get the game to work for CSGO.

### ISSUE THREAD

**Issue by rzn94** [antonpup/Aurora#579]
### What are you experiencing an issue with?

- [ ] Aurora
- [x] Aurora supported game, (CS:GO)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
csgo profile should be working.
### Actual behavior:
 i installed the old verison of logitech cs:go interactions and i got it to work. but it was delayed with 1 minute. so i downloaded Aurora the same way. followed all instructions and when im in windows application aurora and click csgo. i get it to work when i test it. when i click patch Aurora GSI. i find the config files in cfg folder. i look on youtube for answeres and this guy says the patch button dont work.  https://www.youtube.com/watch?v=inphGpCn3Jk
i have installed it the same way as he did. and i have looked on former issues and went to %appdata% and deleted folder. and reinstalled. nothing happends. when i get ingame the keyboard go from "csgo" mode as it shows in desktop and it goes to the standard "wave" format. wtf am i doin wrong?

### How often does this problem occur?

This problem occurs... (every time)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. 
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (0.6.0b)

### Please include any logs, screenshots, or files that are related to this issue:

 my log: https://pastebin.com/7kguY2NZ

**Comment by rzn94** [comment]
this is what it says inside the gamestate intregation file:
""Aurora"
{
 "uri" "http://localhost:9088/"
 "timeout" "5.0"
 "buffer"  "0.1"
 "throttle" "0.1"
 "heartbeat" "0.5"
 "data"
 {
   "provider"            "1"
   "map"                 "1"
   "round"               "1"
   "player_id"           "1"
   "player_state"        "1"
   "player_weapons"      "1"
   "player_match_stats"  "1"
 }
}"

is this correct? it seems like the cfg wont work with game

**Comment by simon-wh** [comment]
Yes that GSI config appears to be correct. When you descibe how the keyboard is displayed in-game is it showing the desktop effects when you are ingame or is it showing the CS:GO effects and not updating? I couldn't quite understand what you were describing in your main post. You can try the latest [development release](https://github.com/antonpup/Aurora/releases/tag/v0.6.0-dev2) to see if that changes anything.

**Comment by rzn94** [comment]
This is what happends, https://www.youtube.com/watch?v=PyLoNDt_xkQ&feature=youtu.be

**Comment by brainbug89** [comment]
Looks like Aurora doesn't detect csgo running.

Try running Aurora as admin. Try changing the Application Detection Method (see Aurora settings).

**Comment by rzn94** [comment]
Changed it from Windows Event to Foreground app scan. still dosnt work...

**Comment by simon-wh** [comment]
Did you try running it as admin? Can you post the log from the attempt you made in the video?

**Comment by rzn94** [comment]
https://pastebin.com/AdXjuERH

**Comment by rzn94** [comment]
i always run it as admin

**Comment by simon-wh** [comment]
Could you try [this build](https://puu.sh/w6G1d/49373328c4.zip) to see if it makes a difference?

**Comment by rzn94** [comment]
now it talks with the game. only thing that dont work now is the team colors on the keyboard but i can programm that my self. thx alot for the help.

**Comment by simon-wh** [comment]
What's the issue with the team colours?

**Comment by rzn94** [comment]
never mind i just saw it was a setting that it dims after 10 secounds i removed it and all works perfectly

**Comment by simon-wh** [comment]
Closing as issue is resolved with latest commit to dev.
