### ISSUE TITLE
Custom cooldown effects for Generic Profiles

### ISSUE THREAD

**Issue by antonpup** [antonpup/Aurora#58]
Suggestion by a user:

> Well, with "cooldown" I'm referring to a feature that would for instance allow you to set a primary key color, and a cooldown (or secondary, if you wish) color. When you press the key, it should change color from primary to cooldown, and then wait for a configurable period of time before fading back to primary. Its useful for things like "health potions", where you can only drink a health potion once every 30 seconds. This way you can have some sort of feedback from the keyboard, without having to worry about reading data from the game.

**Comment by jdubnz** [comment]
This would be awesome! Allow for more customization of custom profiles for unsupported games. Like sign colours on Witcher 3! Another possible feature, pushing 1 key will change other keys colours?

**Comment by antonpup** [comment]
This will not be a part of the upcoming update. But since support for Guild Wars 2 is being added, this suggestion takes higher priority for the following version.

**Comment by BFGinga** [comment]
Any progress on this? Not sure how to do it if it has been added to the program :)

**Comment by simon-wh** [comment]
@BFGinga It will be made possible through the upcoming layer logic

**Comment by Wibble199** [comment]
Can now be achieved with the timer layer.
