### ISSUE TITLE
No setup for League of Legends

### ISSUE THREAD

**Issue by Eps77** [antonpup/Aurora#580]
When I select league of legends its just black keys no layers or anything tried to reinstall still nothing anyone lead me to a league.json or something any help would be appreciated.     

Sorry I cleared all the chat out its late if you want to just delete ill make a New one couldnt figure out how to delete this topic.
![g910lol](https://cloud.githubusercontent.com/assets/29091134/26624423/72cc71ba-45b6-11e7-9373-c1d946322a88.jpg)

Logitech910

**Comment by simon-wh** [comment]
League of Legends doesn't display anything by default as the lighting effects are sent from the game and are displayed on the keyboard through Aurora so you'll only see the effects when you are in-game.

**Comment by Eps77** [comment]
Yeah I couldnt get it to work loading in the game tried to uninstall reinstall now i have a new problem Aurora wont load at all 
![aurerror](https://cloud.githubusercontent.com/assets/29091134/26660556/6990328e-463e-11e7-888b-b37df036c271.jpg)

**Comment by simon-wh** [comment]
Did you try deleting the save folder like mentioned in the other issue you commented on?

**Comment by Eps77** [comment]
I did a search for it I couldnt find it ive uninstalled and reinstalled a couple times
