### ISSUE TITLE
Disabling Desktop mode doesn't work anymore

### ISSUE THREAD

**Issue by brainbug89** [antonpup/Aurora#581]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [x] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Aurora lighting should be disabled at desktop if the option "Enable Aurora to provide lighting effects for desktop" is disabled.

### Actual behavior:
The latest version of Aurora shows lighting effects for desktop.

### How often does this problem occur?
every time at latest version

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. goto Desktop Settings and disable "Enable Aurora to provide lighting effects for desktop"
2. open Windows desktop

### What is the version of Aurora you are experiencing this issue with?
v0.6.0-dev2

### Does the previous version of Aurora have this issue?
previous version (v0.6.0b) worked fine

### Please include any logs, screenshots, or files that are related to this issue:
Log has this error:
`[ERROR] 31.05.2017 18:30:37: Exception in GetActiveWindowsProcessnameSystem.Exception: Eine Ausnahme vom Typ "System.Exception" wurde ausgelöst.
   bei Aurora.Utils.ActiveProcessMonitor.GetActiveWindowsProcessname() in D:\Repos\Aurora\Project-Aurora\Project-Aurora\Utils\ActiveProcessMonitor.cs:Zeile 92.`

System: Windows 7 Professional, 64 bit

**Comment by DeeHechEss** [comment]
i have this same issue
