### ISSUE TITLE
Support for Ajazz ak33

### ISSUE THREAD

**Issue by ThatBulgarian** [antonpup/Aurora#583]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [x ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [x ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
You should support the Ajazz k33

### Actual behavior:
You dont support the ajazz ak33

### How often does this problem occur?
All the time until you support the ajazz ak33

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Buy an ajazz ak33
2. Plug it in
3. Open Aurora
4. Cry

### What is the version of Aurora you are experiencing this issue with?
Latest

### Does the previous version of Aurora have this issue?
Probably

### Please include any logs, screenshots, or files that are related to this issue:
If it's possible, please do.

**Comment by simon-wh** [comment]
There doesn't appear to be any SDK available for that keyboard, without which makes it basically impossible to add support for it without having direct access to the keyboard. If they release an SDK for the keyboard or an unofficial one appears then I'll be sure to try and make support for it, but until then there isn't much I can do.

**Comment by beigexperience** [comment]
I have an A-jazz AK 52, if I reverse engineer the way the supplied app by the manufacturer sets individual keys RGB values would you accept a patch?
