### ISSUE TITLE
Custom Lighting for number of wanted stars possible?

### ISSUE THREAD

**Issue by IsaacGHoward** [antonpup/Aurora#584]
### What are you experiencing an issue with?

- [ ] Aurora
- [x] Aurora supported game, (GTA 5)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [x] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

It would be really cool if the program let you customize lighting effects per wanted level, so like 1 star is basic lights flashing while like 5 stars is the whole keyboard.

**Comment by simon-wh** [comment]
The information for GTA 5 is taken from the keyboard lighting data that is usually sent to Logitech keyboards. For Wanted Level the only information we get is whether you have cops or not, we don't know the star rating due to the siren effects that GTA 5 normally sends.

**Comment by IsaacGHoward** [comment]
@simon-wh then why is there a wanted star dropdown in the aurora effects for gta v? Is there any purpose for it?

**Comment by simon-wh** [comment]
Where is this dropdown?

**Comment by IsaacGHoward** [comment]
@simon-wh  GTA V Settings --> Show Profile overview and options -->Preview

**Comment by simon-wh** [comment]
The wanted level determines the rate at which the displayed sirens swap sides. That option is only under preview so you can get an idea of what is displayed, the information we get from the game is all colours, not raw data. Theoretically, you could calculate what the wanted level is based on how fast the colours are switching but I don't really see that being super reliable.

**Comment by IsaacGHoward** [comment]
@simon-wh oh okay didnt actually notice that it increases speed, but that is pretty cool. Thanks for the info
