### ISSUE TITLE
How to delete profiles?

### ISSUE THREAD

**Issue by SirBoxBoxington** [antonpup/Aurora#585]
I created desktop and game profiles. I want to delete some of them but don't know how to do so. Deleting them manually from the profile folder doesn't work because they reappear.

**Comment by simon-wh** [comment]
If you are trying to delete the profile with the file 'default' it will reappear as that is the one that Aurora traditionally uses as the current profile. You can delete the additional ones you've created that have a name other than 'default' in the folder or you can reset them.

**Comment by brainbug89** [comment]
Saving and deleting profiles within Aurora feels very strange. When I want to save my profile a new one gets created. So I need to rename it and delete the old one with the same name. The save buttons works as a create button and not like save.

**Comment by simon-wh** [comment]
@brainbug89 Are you using the most recent public release or the latest development release? The profile system has been overhauled in the development branch as the previous system wasn't very intuitive.

**Comment by SirBoxBoxington** [comment]
@simon-wh  I'm using the beta v0.6.0b, I downloaded it from aurora.modworkshop.net. I tried deleting the ones that I created, not the default profile. Whenever I restart Aurora they reappear.

**Comment by simon-wh** [comment]
@SirBoxBoxington The profiles are saved when you exit Aurora, so you need to be deleting them after you close the application.
