### ISSUE TITLE
Problem with detection on Clevo device

### ISSUE THREAD

**Issue by klebs** [antonpup/Aurora#586]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (Clevo device)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Program should be detecting Clevo Keyboard

### Actual behavior:
After installation, program initially detects the keyboard and works fine. upon restart of the program or laptop, the keyboard is no longer detected

### How often does this problem occur?

This problem occurs every time the program is restarted or the laptop is restarted

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Install and run program
2. Close program completely/ turn off computer
3. Run program/ turn on computer

### What is the version of Aurora you are experiencing this issue with?

My version is... v0.6.0b

### Does the previous version of Aurora have this issue?
Have not used a previous version

### Please include any logs, screenshots, or files that are related to this issue:

https://pastebin.com/m6X6csH2

**Comment by klebs** [comment]
Update: Program works fine when run as administrator, however doesn't load on startup.

**Comment by brainbug89** [comment]
Check if Clevo Keyboard is enabled at Aurora Settings > Device Manager

**Comment by klebs** [comment]
Where is the device manager setting located?

**Comment by brainbug89** [comment]
![devicesettings](https://cloud.githubusercontent.com/assets/21130949/26755399/cab32990-488c-11e7-9d13-df4851d02888.PNG)

**Comment by simon-wh** [comment]
Any updates on this?
