### ISSUE TITLE
Numpad 4 On MasterKey L mapped wrong

### ISSUE THREAD

**Issue by k3ter** [antonpup/Aurora#587]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other

### Expected behavior:
Numpad 4 lights should light up numpad 4 on Coolermaster Masterkey L with United states layout.

### Actual behavior:
Numpad 4 lights up Numpad 5 on Coolermaster Masterkey L with United States layout, and Numpad 5 lights up Numpad 6, and Numpad 6 doesn't light anything up.

### How often does this problem occur?

This problem always occurs.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Using a Masterkey L keyboard with United States layout
2. Try to light up Numpad 4
3. See that Numpad 5 is lit up.

### What is the version of Aurora you are experiencing this issue with?

My version is v0.6.0b

### Does the previous version of Aurora have this issue?
Coolermaster Masterkey L was not supported in previous versions. 

### Please include any logs, screenshots, or files that are related to this issue:

http://imgur.com/VD4ocnf
http://imgur.com/PkQ7Y69
http://imgur.com/x7IgGsK

**Comment by brainbug89** [comment]
Which keyboard layout did you choose at Device settings?

**Comment by hsnabn** [comment]
I can confirm this issue. Layout selected is United States.

**Comment by brainbug89** [comment]
Possible fix could be to change line [92-94 of CoolerMasterDevice.cs](https://github.com/antonpup/Aurora/blob/462df29fb572a0fbad2d21ea81b2a8ea97a6d1a4/Project-Aurora/Project-Aurora/Devices/CoolerMaster/CoolerMasterDevice.cs#L92) to:

```c#
{DeviceKeys.NUM_FOUR, new int [] {3, 17} },
{DeviceKeys.NUM_FIVE, new int [] {3, 18} },
{DeviceKeys.NUM_SIX, new int [] {3, 19} },
```

**Comment by simon-wh** [comment]
I'm going to close this issue and use #549 instead for this problem
