### ISSUE TITLE
Dead By Daylight Support ?

### ISSUE THREAD

**Issue by wibblepegs** [antonpup/Aurora#588]
Any chance of a profile for this game ?

Would be amazing the killers heartbeat making the keyboard flash red etc

I just left a similar message on the dead by daylight steam forum and faded was sugesting Game State Integration and that he also worked with Anton P on Aurora.

I reckon you could make this happen if you had a wee chat :)

I have attached a link to the steam discussion here http://steamcommunity.com/app/381210/discussions/0/1291817837638832466/?tscn=1496752337

Thanks

**Comment by brainbug89** [comment]
If the Dead by Daylight devs add GSI, it would be possible.

**Comment by wibblepegs** [comment]
Hopefully it happens mate would love to see it in aurura

**Comment by simon-wh** [comment]
Closing until support is feasible/possible.
