### ISSUE TITLE
Aurora Over-rides Default Lighting Schema

### ISSUE THREAD

**Issue by SoupOrJuice** [antonpup/Aurora#59]
Just a quick thing, I'm not sure if there's a way to avoid this but Aurora over-rides the default lighting schema for certain games. Example in question, I'm playing Evolve and LGS (I'm using a Logitech 910) has some cool effects for the keyboard built-in. However, if I alt+tab, Aurora turns it back into the Desktop effects (CPU and RAM usage, etc.). When I go back into the game, the lighting schema doesn't change back to the Evolve lighting effects, it stays in the Desktop lighting mode from Aurora.

Any way to fix this or avoid it w/o disabling the desktop lighting altogether?

**Comment by antonpup** [comment]
If you patch the Logitech Wrapper with Aurora, all Logitech lighting effects will go through aurora. Which will map effects based on process name, and will recover them when tabbing back in.

Logitech wrapper install can be found under the GTA 5 Profile.

**Comment by antonpup** [comment]
Did this answer your question?

**Comment by SoupOrJuice** [comment]
Oh, sorry -  yes it did. I had to restart after using your advice but it
works like a charm now.
