### ISSUE TITLE
Keeps wiping all profiles

### ISSUE THREAD

**Issue by OttoWerse** [antonpup/Aurora#590]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [x] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, (Complete wipe of all data)

### Expected behavior:
Profiles should be present.

### Actual behavior:
All Profiles and all their data is gone from the GUI.
The .json files are however still present inside the Profile folder, they just cannot be loaded inside Auroras GUI (the list appears empty)

### How often does this problem occur?
Every time the program is restarted.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Open Aurora
2. Create a profile
3. Close Aurora
4. The profile is now gone

### What is the version of Aurora you are experiencing this issue with?
Aurora 0.6.0b Beta

### Does the previous version of Aurora have this issue?
This issue appeared out of nowhere without any changes or updates made, I am not sure if it is related to the version of Aurora.

### Please include any logs, screenshots, or files that are related to this issue:
https://pastebin.com/RgxapZ8N
https://pastebin.com/c7MGKq5y
https://pastebin.com/zShWksQB
I am not sure when exactly this happened, the Profiles were still working fine up until the second I maximised Aurora again and since my PC has been running non-stop for quite a while I have included multiple logs created during it's uptime.

**Comment by simon-wh** [comment]
Are you using [v0.6.0-dev2](https://github.com/antonpup/Aurora/releases/tag/v0.6.0-dev2)? If not, try using that version and see if the issue still persists.

**Comment by OttoWerse** [comment]
Thanks for the reply, the issue doesn't seem to be present in the dev Version anymore, however, some of my profiles are still broken.
I guess the old version somehow corrupted their data, they do show up in the GUI of the dev version, but when I activate them they're just empty profiles with no layers. I can't really notice any patterns though, it seems to be just random which profiles survived and which profiles got corrupted.

Anyways, I'll just have to recreate them, at least Aurora works at all now.

**Comment by simon-wh** [comment]
If you get any continued problems with profiles saving/corruption then post them here.
