### ISSUE TITLE
Aurora doesn't detect my K95 Platinum with the newest 2.14.17 CUE (It works fine with 2.13.80)

### ISSUE THREAD

**Issue by H4RDW4R3** [antonpup/Aurora#592]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [x] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (Corsair K95 Platinum)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
no problems?!

### Actual behavior:
- 0.6.0b crashes with the 2.14 CUE
- 0.6.0b_dev2 doesn't crash but doesn't detect the device neither
- both versions do not work with the newest 2.14 CUE (new SDK ?!)
- flickering in the "device manager" tab

### How often does this problem occur?

This problem occurs every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. update CUE to the latest 2.14
2. restart PC
3. run aurora

### What is the version of Aurora you are experiencing this issue with?

My versions are 0.6.0b and 0.6.0b_dev2

### Does the previous version of Aurora have this issue?
The previous version, (0.6.0), did have this issue too... Even worse tho

### Please include any logs, screenshots, or files that are related to this issue:

Can't provide logs... Just downgraded my CUE version and it works fine again

**Comment by brainbug89** [comment]
K70, CUE 2.14.58 (beta) and Aurora (v0.6.0-dev2) is working fine for me. And the latest CUE version is 2.13 on official [Corsair website](http://www.corsair.com/de-de/downloads). Wherer did you get the 2.14.17 from?

**Comment by H4RDW4R3** [comment]
@brainbug89

I just scanned in CUE for updates and the 2.14 came up (It was the 2.14.17 when I remember right). I can't find the 2.14 on the website of corsair either... Maybe the 2.14 for the K95 is still a beta and the SDK is not working perfect. 

0.6.0_dev2 and 2.13.80 working still fine again tho

I don't know what CEE is... So I can't answer that question :/
Just having the keyboard for around four days now

**Comment by simon-wh** [comment]
Closing for now. If it is an SDK issue then the issue would be more relevant to [CUE.NET](https://github.com/DarthAffe/CUE.NET) which Aurora uses to interface with the CUE SDK.

**Comment by brainbug89** [comment]
just FYI @H4RDW4R3 CEE is [Corsair Effects Engine](http://forum.corsair.com/v3/showthread.php?t=139027) by Elestriel. It's nice to test if CUE SDK with apps other than Aurora is working with CUE.
