### ISSUE TITLE
K95 Not initialized

### ISSUE THREAD

**Issue by Klimpzz** [antonpup/Aurora#593]
### What are you experiencing an issue with?

- [x ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen. 
Find my keyboard
### Actual behavior:
Explain here what happened instead.
It says not initialized
### How often does this problem occur?

My version is... (beta v0.6.0b)

### Does the previous version of Aurora have this issue?NO
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: https://pastebin.com/AZQzXFAY

Thanks for a great program! i have use it for a Couple of months. but I re instaled my computer yesterday and now when i tried to use it it dont find my corsair MM800 or my K95. But my logitech stuff works, I have tried Cue.Net_test but it crashes. CueNetTestOld works but my K95 Only flashes a couple of times. 

Sorry for bad english

**Comment by simon-wh** [comment]
Have you definitely got CUE installed and running?

**Comment by Klimpzz** [comment]
Yes i am sure. 

![print screen](https://user-images.githubusercontent.com/29307262/26989041-d25b2d04-4d51-11e7-97ac-c9b0772792d4.jpg)

**Comment by Klimpzz** [comment]
Yes i am sure 
![print 1](https://user-images.githubusercontent.com/29307262/26989122-290c72ac-4d52-11e7-86d3-010f4bb0448d.jpg)

**Comment by Klimpzz** [comment]
![print 2](https://user-images.githubusercontent.com/29307262/26989217-89248e18-4d52-11e7-82d0-4c2d3f408c3d.jpg)

**Comment by simon-wh** [comment]
Could you try the [latest prerelease](https://github.com/antonpup/Aurora/releases/tag/v0.6.0-dev2)? I don't think it'll make a difference as it seems like your issue might be related to CUE/CUE.NET which may be out of our control, I could be wrong though.

**Comment by brainbug89** [comment]
Please update to latest CUE version (2.14) from [here](http://www.corsair.com/support/downloads).

**Comment by Klimpzz** [comment]
i have tried that version of CUE. But same thing with that. I installed that version who have work in the past. 
And i feel really stupid but i dont understand how to install that version of Aurora.

**Comment by simon-wh** [comment]
@Klimpzz You can just extract it and run Aurora.exe after closing any other Aurora version you have open.

**Comment by simon-wh** [comment]
Any updates on this?
