### ISSUE TITLE
Cant download/ Install Aurora

### ISSUE THREAD

**Issue by TwitMyTwatter** [antonpup/Aurora#594]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [x ] Other, (Can't download Aurora, States that a connection with the server couldn't be established)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ x] Other, (Server, Download issue)
### Expected behavior:
Download goes good

### Actual behavior:
Download Failed: A connection with the server could not be established

### How often does this problem occur?
Every time I try to download

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1.  Try to download
2. Does not download
3. 

### What is the version of Aurora you are experiencing this issue with?
I have no idea cause I can't download it

### Does the previous version of Aurora have this issue?
No idea

### Please include any logs, screenshots, or files that are related to this issue:
http://prntscr.com/fhx1y6

**Comment by simon-wh** [comment]
The server that hosts the releases is currently having some issues. You can download the full package here under the releases area or wait until the servers are fully up and running again.
