### ISSUE TITLE
Feature Request: Shortcut Assistant Layer -> New Key Areas for Combined Modiefier Keys (CTRL + ALT ( + SHIFT ) + <Key>)

### ISSUE THREAD

**Issue by TomCoursow** [antonpup/Aurora#596]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [x] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
It would be nice to have additional Key List Box Areas to assign Multi Combined Modiefier Shortcut Keys like...
- CTRL + ALT + \<KEY\>
- CTRL + SHIFT + \<KEY\>
- CTRL + SHIFT + ALT + \<KEY\>
- SHIFT + ALT + \<KEY\>

This swould be an very awesome feature for Programmers! With that I could highlight some of the most important IDE Programming Shortcuts in IntelliJ for example. (STRG + ALT + SHIFT + <T> = Refactor)

### Actual behavior:
Currently, a Shortcut Assistant Layer is only able to Higlight Shortcuts for...
- CTRL + \<KEY\>
- WINDOWS + \<KEY\>
- ALT + \<KEY\>

**Comment by simon-wh** [comment]
This feature has already been added in the development version. If you would like to try it out now you can download the latest pre-release.

**Comment by TomCoursow** [comment]
I downloaded the latets dev release. How does the new shortcut layer work? I can not assign colors to keys there...

**Comment by simon-wh** [comment]
Each layer has a single colour associated with all the of the Shortcuts. You assign the shortcuts under the "Shortcuts" section by adding a new shortcut then pressing the assign button and pressing the keys on your keyboard you wish to add as a shortcut.

**Comment by TomCoursow** [comment]
Thank you :)
I found out that you realy have teo press the key in exactly the same order to work (when in progressive suggestion mode)

For example for the "IntelliJ Show UML Diagram" Shortcut (CTRL + ALT + U)
I have to assign 2 shortcuts:
CTRL + ALT + U and ALT + CTRL + U
so that i can be sure that highlight realy works no matter which key i press first if i tap them nearly at the same time.
This could be imroved, but I like the feature very much thank you :)
