### ISSUE TITLE
Add League of Legends AlienFX?

### ISSUE THREAD

**Issue by saltykun** [antonpup/Aurora#6]
I'm personally not sure if it's still supported in the game as the option is hidden to non-alienware hardware users but it would be nice to use it with my Razer keyboard

**Comment by antonpup** [comment]
Will look into LightFX support of League. Hopefully it's not anything like their Logitech LED support (which only changes the keyboard to a blue color).

**Comment by IrealiTY** [comment]
Nah it's more elaborate than that - I used to have that on my old Laptop, adjusted some colors for HP bars (but this was in 2013)

**Comment by antonpup** [comment]
> adjusted some colors for HP bars

How much customization does League offer for LightFX? If I were to provide 5 lights for a device, would that be sufficient?

**Comment by IrealiTY** [comment]
Can't give you detailed information at the moment. Sorry.
I don't recall any settings or adjustments were possible.

**Comment by saltykun** [comment]
I believe it was an AlienFX thing so it wasn't very complex and used Alienware's "zone lighting" and not per key, should be very similar to Payday The Heist's

IIRC it was relatively basic stuff like having the whole keyboard go from green to red based on health, flashing blue on pings, and changing to white on death

**Comment by Diluted22** [comment]
This guy made a profile for Crosairs K70. http://forum.corsair.com/v3/showthread.php?t=134204 not sure if this helps or not

**Comment by antonpup** [comment]
@Diluted22 I'm pretty sure that Corsair profiles don't integrate with games.

I did write a LightFX Wrapper here's a checklist:
- [x] Locate a LightFX dll location for League of Legends
- [x] Successfully allow League of Legends to connect to Aurora and send some commands
- [ ] League of Legends seems to use Masks to apply light colors/effects, so successfully get lighting information from the game.

I think that the controls for this profile will be pretty simple, background will be whatever LightFX sets as color, there will be Color Zones, and that's about it. As I don't think LightFX provides info like HP or Mana at all times.

**Comment by antonpup** [comment]
Support for League of Legends, Hotline Miami, and Talos Principle will be added in the next version.
