### ISSUE TITLE
G910 G logo and G keys

### ISSUE THREAD

**Issue by Xtreme976** [antonpup/Aurora#60]
I love the program and its way better than the default logitech one, but could there be a way for the G keys and logos to be controlled by the app. It is my understanding that they are seen as diferent keys, but is there no way? Its really weird having all the keyboard configured and those keys stay the same :/

Also, is there a way that aurora only activates in games and not on the desktop?

Keep up the good work, love the app!

**Comment by antonpup** [comment]
The G-keys and Logos are not part of the Logitech SDK. As soon as they are added to the SDK, I will add support for them.

There is no way to disable Aurora completely for Desktop usage. Aurora is designed to hopefully replace the default keyboard led utility. If it doesn't do something that you want, you can always suggest it.

**Comment by Xtreme976** [comment]
The only thing that bothers me with the program is the lack of control of the logos and G keys
I hope they integrate it in the SDK soon! It would make a great program even better!
Can't think of why they wouldn't allow apps to control those since games like CS go and dota control it
