### ISSUE TITLE
Peripherals stop working while Aurora is active [Overwatch]

### ISSUE THREAD

**Issue by TekkertheChaot** [antonpup/Aurora#601]
### What are you experiencing an issue with?

- [x] Aurora

### What kind of an issue is it?

- [x] Performance problems

### Actual behavior:
When I play Overwatch with Aurora activated my input lag increases and often my peripherals stop working for up to 3 seconds (including input and lighting effects)

### How often does this problem occur?
Everytime when I play Overwatch with Aurora active in the background

### What is the version of Aurora you are experiencing this issue with?

My version is v0.6.0b

I wasn't able to find a to my problem related ticket. 
Hope this wil help.

**Comment by simon-wh** [comment]
What devices do you have? Also, could you try the [latest development release](https://github.com/antonpup/Aurora/releases) to see if it is any different on that build?

**Comment by simon-wh** [comment]
Any updates on this?

**Comment by TekkertheChaot** [comment]
I'm sorry Simon, I haven't got any notifications about this ticket until now.
So, sorry for leaving you hanging there 2 months

To answer your comment from about a month ago: I use the Logitech G810 Orion Spectrum (keyboard) and the Logitech G502 Proteus Spectrum (mouse). 
Since posting here, I continued playing with aurora active in the background and the issue seem's to be gone after a major Windows update (something after the Creators update). The issue still appears in heavy fights (much effects on screen) even though my CPU performance isn't peeking out to its maximum.

I will definitely try the development release and report back end of this week to stress-test it out.

**Comment by simon-wh** [comment]
@TekkertheChaot Thanks for getting back to me. Currently, @VoronFX is working on changes which will hopefully eliminate most if not all input lag issues which can be seen over here #561.
