### ISSUE TITLE
My keyboard Dims and then do nothing

### ISSUE THREAD

**Issue by AKBoy14** [antonpup/Aurora#604]
The other day I was playing GTAV and the LEDs on the keyboard (K70 Rapidfire) works perfectly (changing with the characters and police), but then, when I played tonight, all the LED were just white and not changing (not the first time it happened, other games like CSGO and Overwatch works perfectly), then I tried to solve the issue and for some reason, now the software doesn't work properly, it opens with the profile I use, and then it start dimming the LED and then it doesn't do anything, If I preview other profile it will change but when I click the desktop profile it doesn't change, I have uninstalled and installed several times and the problem persist.

**Comment by simon-wh** [comment]
What version are you running? Could you try the [latest development release](https://github.com/antonpup/Aurora/releases) if you haven't already to see if it makes a difference?

**Comment by AKBoy14** [comment]
Thanks, this version seems to be working, the version I previously had was the 0.6.0b Beta, strangely it stopped working out of the blue, other than that, I don't see the option to use my scripts that show the GPU and CPU usage and the ping, and GTA still doesn't work :'(, it used to work before but now it only show white light and it doesn't change.

**Comment by simon-wh** [comment]
The GTA fix will be in the next release. The scripts can be used under the Script Layer if they are compatible with the version you're using.
