### ISSUE TITLE
Only opens and closes

### ISSUE THREAD

**Issue by joaquinberardi** [antonpup/Aurora#605]
### What are you experiencing an issue with?
- [ x] Aurora

### What kind of an issue is it?
- [x ] Crash

### Expected behavior:
The software should start.

### Actual behavior:
 I just finished installing aurora and it just opened once. Then I restarted my pc and the software just doesnt open (open and closes, cant even see the UI)

### How often does this problem occur?
This problem occurs everytime

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. double click on the software exe
2. nothing else

### What is the version of Aurora you are experiencing this issue with?

My version is 0.0.6.0

### Does the previous version of Aurora have this issue?
The previous version did.

### Please include any logs, screenshots, or files that are related to this issue:
Nothing can ve shown because it doesnt do anything.

**Comment by brainbug89** [comment]
Look at the traybar, there should be an Aurora icon. Otherwise pls provide a log. You can find the log files here: ` %appdata%/Aurora/logs/`

**Comment by simon-wh** [comment]
Could you check if you have MSI Afterburner installed? That is known to have caused this kind of issue with Aurora in the past.

**Comment by ArsamS** [comment]
I have the same problem. Log: https://pastebin.com/rfSXPXCV

**Comment by Wizzzzzard** [comment]
I had possibly the same problem , last night I installed Aurora-web-setup.exe in hope of getting my chroma keyboard working in the division, I read in a post that the pre-release version works and found release_major_0_6_1-dev.zip under a pre-release tab, I extracted that to a folder and ran it but it didn't fix my problem, when I tried to go back and run the installed version again I started getting the same error and now only the extracted "release_major_0_6_1-dev.zip" works.

**Comment by simon-wh** [comment]
Can anyone with this issue try v0.6.2b?
