### ISSUE TITLE
Logitech G910 Logos are not affected

### ISSUE THREAD

**Issue by CaptiveCreeper** [antonpup/Aurora#606]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [x] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (Fill in problematic devices)
Logitech G910
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
The two logo keys should change color based on what the app tells it
### Actual behavior:
Explain here what happened instead.
They stay to what ever logitech software has set
### How often does this problem occur?

This problem occurs... (Fill in here)
Always

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Apply a color to either of the logos on the G910

### What is the version of Aurora you are experiencing this issue with?

My version is... (beta v0.6.0b)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.
I downloaded it today so I dont know
### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by TristanSchaaf** [comment]
Tested with my G910 Orion Spectrum. Logo's are able to change color without problems.

**Comment by CaptiveCreeper** [comment]
Huh thats odd. Do you have any idea why my logos wouldnt be controlled by Aurora for me?

**Comment by TristanSchaaf** [comment]
I have no clue on why that is. I guess you've tried restarting Aurora. How did you fill the logo's? Does a fill layer change the color's or not? If you change the color in the Logitech gaming software, do they change with it?

I am not a programmer though, just a webdeveloper. So i don't know how to fix this with a patch. I'm know a little bit about debugging and seeing as my G910 works normally it could be the problem is exclusive to your computer. (if you can, try plugging your keyboard in another computer with aurora installed).

**Comment by CaptiveCreeper** [comment]
The logos display whatever the logitech software left them (including the changing rainbow spectrum). And the problem has persisted after reopening Aurora as well as restarting my computer.

**Comment by sportega** [comment]
OK so I had a similar problem and was able to fix it by updating the Logitech program
