### ISSUE TITLE
Supported games that require patching don't work

### ISSUE THREAD

**Issue by EvilDobermann** [antonpup/Aurora#607]
### What are you experiencing an issue with?

- [ ] Aurora
- [x] Aurora supported game, (Dota2, CS:GO, Rocket League, Payday 2)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
The keyboard should react to the game, f.e. light the F1-F12 keys green or red depending on HP in game or the keyboard should be blue/orange in Rocket league.

### Actual behavior:
I just get static lights. In Rocket league the keyboard is always blue, even when I pick the orange team. In CS:GO the keyboard is all white with red F-keys and blue numeral keys. The key colors dont react to ammo and HP. Same goes for Payday 2.

### How often does this problem occur?

This problem occurs... always

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. It is this way all the time.
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... beta 0.6.0b

### Does the previous version of Aurora have this issue?
This is my first time using Aurora. Never tried any previous releases.

### Please include any logs, screenshots, or files that are related to this issue:

https://pastebin.com/AZLGmPqw

Additional Info:
I use a Logitech G910 and followed the first time instructions to install the device in Aurora correctly. Thanks for any help!

**Comment by brainbug89** [comment]
Rocket league doesn't work atm, because the memory pointers are outdated.

Are the other effects for CS:GO (like burning, flash, kill indicator, green chat modus) are working?

**Comment by EvilDobermann** [comment]
Okay, I reinstalled my Logitech Gaming Software and everything Valve related works fine now. CS:GO is working, same for Dota2. Only Payday 2 is giving me trouble still. Did how the instruction told me, but no. Thanks for the clarification about Rocket league, though!

**Comment by simon-wh** [comment]
I think BLT for Payday 2 is currently broken due to an update so the
integration will not work until BLT is fixed.

**Comment by EvilDobermann** [comment]
I'm using the regular version you get by clicking the download link in the description on the main page which says "get the latest release here". It is v0.6.0b. Description says it is beta. So that is why it isn't working. Thanks for clarification.

**Comment by simon-wh** [comment]
Have you got Payday integration working?

**Comment by EvilDobermann** [comment]
Nope, I didn't. I was too lazy to "downgrade" to the non-beta release.

**Comment by olokos** [comment]
Same issue here, nothing works, just static background in csgo like described here. K70 LUX RGB USA

**Comment by simon-wh** [comment]
@olokos Are you talking about PD2 as well? If so, can you and @EvilDobermann try the solution mentioned at #681

**Comment by olokos** [comment]
I'm talking about CSGO

**Comment by simon-wh** [comment]
@olokos Oh, sorry, I misread your comment. Did you definitely apply the GSI patch? If so could you try again and post your log file if it still doesn't work?

**Comment by olokos** [comment]
Where's GSI patch? I will try it but I never heard of it.

**Comment by simon-wh** [comment]
@olokos It's in the CSGO profile overview

**Comment by olokos** [comment]
can you direct me where it is? I'm not going to lie, I'm quite lost in this interface

**Comment by simon-wh** [comment]
![](https://puu.sh/x87nn/a8967cdc93.png)

You need to click "Show Profile Overview/Options" as shown, then click "Patch GSI"

**Comment by olokos** [comment]
Seems like this is the issue. It should be noted to user specifically that this needs to be done in order for it to work.
