### ISSUE TITLE
ALTGR treated as ALT in shortcut assistant layer (International layout).

### ISSUE THREAD

**Issue by diogotr7** [antonpup/Aurora#609]
This key has different functions in the International layout, so I'd like to set different shortcut assistant modifier keys for it.

It is located right after spacebar and before the second windows key.

I'm using the Logitech g810

**Comment by brainbug89** [comment]
It's not possible, see https://github.com/antonpup/Aurora/issues/464#issuecomment-281491291 and https://github.com/antonpup/Aurora/issues/385#issuecomment-273242579

**Comment by diogotr7** [comment]
Bummer, thanks for answering, and sorry for duplicate issue.
