### ISSUE TITLE
Shortcuts Assistant Improvements

### ISSUE THREAD

**Issue by Baosplaya** [antonpup/Aurora#61]
Just a quick suggestion: It would be nice it there was an option so if you press one of the shortcut keys (Alt/Win/Ctrl) all other keys will turn off. 

This would really help with keeping the focus on there spesfic keys.

**Comment by antonpup** [comment]
Can do.

**Comment by antonpup** [comment]
I added an option for "dimming the background keys". It won't completely turn them off, but they will be 66% darker.

**Comment by Baosplaya** [comment]
Wow, you're really into this project. Keep it coming, you're doing a great job!
