### ISSUE TITLE
GTA5 won't work anymore

### ISSUE THREAD

**Issue by AKBoy14** [antonpup/Aurora#611]
My keyboard use to work with GTA5, but now it won't work, I've play other games like CSGO, Payday and Overwatch and the software have worked flawlessly, but GTA always have been troublesome, I got to work once but then I stopped playing for a while and when I got back... poof... it doesn't work anymore, I have the latest version of Visual C++ 2013 and 2015 (64 and 86), CUE Software (K70 Rapidfire) and Logitech Software (G700s) I don't know If Aurora works with the latest versions of said programs or if I need specific versions, I made my keyboard work with the LogiLed2Corsair where you edit the regedit, and the keyboard change colors, but with aurora the keyboard turns white and doesn't do anything :(

**Comment by simon-wh** [comment]
Are both GTA 5 and Aurora being run as Admin?

**Comment by AKBoy14** [comment]
yes, I have Aurora and Steam set to run as admin, since my GTA is the steam version, I have to launch it from steam, but it used to work before so I don't know why it doesn't work now

**Comment by AKBoy14** [comment]
@simon-wh is there a way that I could hot-fix my keyboard to make it work, adding something on the registry or I don't know, I'm running out of ideas.

**Comment by simon-wh** [comment]
If there is a significant issue with the GTA 5 implementation then most likely it will require an Aurora update to fix. I'm updating GTA currently to try and sort out the issue but my Internet is quite slow so it is taking a while.

**Comment by AKBoy14** [comment]
I don't see people reporting about GTA 5, so I believe that the problem is something in my pc, but I don't know what could it be, CSGO, Payday 2 and Overwatch worked the last time I played them, but the difference between those games is that in those game you patch either the game or Aurora GSI, and in GTA 5 you have to patch the Logitech LED SDK, I think that the problem in my pc is about the Logitech LED SDK because Aurora knows that I'm on GTA but doesn't change the colors :\

**Comment by simon-wh** [comment]
Have you patched GTA recently? An LGS update might mean you need to patch it again.

**Comment by AKBoy14** [comment]
Yes, and when I patch it, the LogitechLed.dll in the LGS folder change from 8.94.92 (my version of LGS) to 8.75.30.0 and says "Aurora Wrapper for Logitech SDK"

**Comment by simon-wh** [comment]
And it still doesn't work after you do that?

**Comment by AKBoy14** [comment]
No, the other thing that I could think of is the Visual C++ and the .Net, I'm running with Microsoft Visual C++ 2015 Redistributable (x86 and x64) 14.0.23.0.26, and the .Net I believe it is the last version since my PC won't either show me where it is nor let me install any other version because "Same or higher version of .NET Framework 4.5 has already been installed on this computer"

**Comment by simon-wh** [comment]
Do other games that require the Logitech patch work? e.g. Evolve Stage 2, The Division?

**Comment by simon-wh** [comment]
Also, could you try the [latest prerelease](https://github.com/antonpup/Aurora/releases) to see if it makes a difference, make sure to repatch the Logitech wrapper.

**Comment by AKBoy14** [comment]
I wouldn't know since I don't own those games, I'm not currently at home but as soon as I can I would try the latest released :)

**Comment by AKBoy14** [comment]
Nothing, I downloaded the lastest prerelease that its supposed to be the v0.6.1-dev but in aurora it says its the beta v0.6.0-dev2, don't know if it's suppose to be that version, anyways, Evolve Stage 2 shows the red and orange colors ingame, but GTA still all white and does nothing, I am running out of ideas as for why it doesn't work anymore, anyway, thanks for the help

**Comment by simon-wh** [comment]
I've got it fixed on the Dev branch. It'll be available in the next release
