### ISSUE TITLE
[Question] Using macros

### ISSUE THREAD

**Issue by Globe999** [antonpup/Aurora#612]
Hi!

I'm new to this software and I'm trying to figure out if there's a way to use my macros on CUE 2 while using Aurora. If not, is it possible to recreate them in Aurora?

Also, is it possible to support PUBG & BF1? Would really be awesome :D

Thanks :D

**Comment by simon-wh** [comment]
The only thing that changes when Aurora in CUE is the lighting effects. It doesn't do anything with Macros they will still work the same way as they usually do. There are separate issues for the games you mentioned #130 and #555
