### ISSUE TITLE
Discord Support

### ISSUE THREAD

**Issue by KillMeImSalty** [antonpup/Aurora#613]
Today Discord announced their collaboration with Logitech: https://twitter.com/discordapp/status/876937721616375808 I thought it would be cool to have it in Aurora since there is already support for Skype, although it's slowly getting replaced by teamspeak and discord etc.

**Comment by simon-wh** [comment]
Duplicate of #297

**Comment by brainbug89** [comment]
#297 was closed because it didn't seemed to be possible, but now with https://twitter.com/LogitechG/status/876934012161241089 shouldn't it work with the Logitech wrapper?

**Comment by thu2468** [comment]
@simon-wh The applet path is C:\Program Files\Logitech Gaming Software\ArxApplets
