### ISSUE TITLE
[Overwatch] Reaper's color not displayed properly

### ISSUE THREAD

**Issue by diogotr7** [antonpup/Aurora#614]
### What are you experiencing an issue with?

- [ ] Aurora
- [x] Aurora supported game, (Overwatch)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, (Minor Issue)

### Expected behavior:
Keyboard turns dark red when playing Reaper

### Actual behavior:
Keys other than the movement keys, the keytboard doesn't light up at all.
### How often does this problem occur?
Everytime I play Reaper

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Open overwatch
2. Pick Reaper

### What is the version of Aurora you are experiencing this issue with?

My version is... (0.6.0b)

I have tried messing with the Color Enhancement slider but that does not solve the  issue. Maybe Aurora could get the colors to display from overwatch and set them to something custom. I only had this problem with reaper, so at least setting his color to something "redder" would be good.

**Comment by simon-wh** [comment]
The lighting information for Overwatch is sent from the game. So all the lighting they have for certain characters is their choice and we have no control over it. I've got a Colour Change/Filter feature already planned which may be able to fix your issue but other than that there isn't much we can do about it.

**Comment by diogotr7** [comment]
Just wanted to say that the HSV color enhancing solved this issue, Thanks!
