### ISSUE TITLE
Aurora doesn't work anymore

### ISSUE THREAD

**Issue by JeremyD357** [antonpup/Aurora#615]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

Here is what i get : 

http://imgur.com/a/RTgpX

How can i do ? thank for the help :)

**Comment by diogotr7** [comment]
If you updated to dev then rolled back you need to delete the aurora folder in %appdata%. At least that's what i did and it worked.

**Comment by simon-wh** [comment]
As @diogotr7 said, you need to delete %appdata%/Aurora or you can update to the latest pre-release
