### ISSUE TITLE
Lighting not working on Corsair 

### ISSUE THREAD

**Issue by baqirhabsyi** [antonpup/Aurora#616]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (Corsair K65 Rapidfire)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Keyboard LED lighting.

### Actual behavior:
No lighting saw, but mouse RGB lighting is working normally. Using Logitech G502 Spectrum as mouse.

### How often does this problem occur?
This problem occurs when using Aurora

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1.  Just use Corsair K65 Rapidfire.
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is v0.6.0b

### Does the previous version of Aurora have this issue?
This is my first install.

### Please include any logs, screenshots, or files that are related to this issue:
[https://pastebin.com/rGxTMZGy](Logs.)

**Comment by simon-wh** [comment]
Did you enable the SDK in CUE's settings? Also, what version of CUE are you running?

**Comment by simon-wh** [comment]
Possibly related to #593

**Comment by simon-wh** [comment]
Any updates on this?
