### ISSUE TITLE
Corsair K55 RGB not supported.

### ISSUE THREAD

**Issue by bakoff** [antonpup/Aurora#617]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ X ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ X ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
I though that some ligthing effects must work with another keyboard profile, even if it's not officially supported.

### Actual behavior:
No lighting.

### How often does this problem occur?
This problem occurs everytime.

### Please describe the steps to reproduce this issue:
Just try a Corsair K55 RGB keyboard. and try some GTA V, Rocket League lighting tests.

### What is the version of Aurora you are experiencing this issue with?
My version is beta v0.6.0b.

### Does the previous version of Aurora have this issue?
I don't know if the previous version had this issue.

**Comment by simon-wh** [comment]
That device isn't supported by the CUE SDK so there isn't much I can do to support it.

**Comment by Sparqey** [comment]
I'm sorry for bumping old threads but Corsair released a K55 CUE SDK just wanted to let u know
Its a 3 zoned RGB colored keyboard if u need to get profiles converted over to this for games like csgo i could be able to do it
