### ISSUE TITLE
The given key was not present in the dictionary

### ISSUE THREAD

**Issue by DeeHechEss** [antonpup/Aurora#618]
### What are you experiencing an issue with?

- [ x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
It should start normally
### Actual behavior:
Explain here what happened instead.
It crashed when it tries to start the program
### How often does this problem occur?

This problem occurs... (Fill in here)
Every time
### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Uninstall Aurora
2. Reinstall Aurora
3. Open Aurora

### What is the version of Aurora you are experiencing this issue with?

My version is... (Latest verion that the latest web downloader uses as of 24.6.17)

### Does the previous version of Aurora have this issue?
The previous version, (0.6.0.b), did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

https://pastebin.com/aX50DUJy
http://imgur.com/a/p7e5H

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
This issue has been brought up many times. It's been fixed in the latest pre-release and you can deal with it without updating by deleting %appdata%/Aurora
