### ISSUE TITLE
Shovel Knight?

### ISSUE THREAD

**Issue by Dlaw2017** [antonpup/Aurora#621]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [x] Other, (Shovel Knight support)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [x] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Just wondered if you could add Shovel Knight support?

### Actual behavior:
Explain here what happened instead.

### How often does this problem occur?

This problem occurs... (Fill in here)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. 
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (Fill in here)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by brainbug89** [comment]
Try the apply the Razer wrapper patch of Aurora to Shovel Knight.

**Comment by Dlaw2017** [comment]
I just tried that as well as the Light FX patch, and none of them seem to do the trick.

**Comment by txeptsyip** [comment]
Try to apply the Razer wrapper patch of Aurora to Shovel Knight.

i am confused as to what that means do i click the blue cog icon and just press install aurora wrapper patch?

**Comment by brainbug89** [comment]
> i am confused as to what that means do i click the blue cog icon and just press install aurora wrapper patch?

Aurora > General Settings > Device & Wrappers > Install Aurora Wrapper Patch for Razer > now you need to navigate to the game files of Shovel Knight (there should be two files in this folder: `RzChromaSDK.dll` and `RzChromaSDK64.dll`) > Press OK

Aurora will patch the originial .dll's with the Wrapper one.

**Comment by diogotr7** [comment]
Shovel Knight tested working with Razer chroma patch.
