### ISSUE TITLE
Option to Keep Key Illuminated When Held Down [Request]

### ISSUE THREAD

**Issue by User5432112345** [antonpup/Aurora#623]
When using the "key fade" mode on an  interactive layer, the keys begin fading to the secondary color immediately after being pressed even if they are held down.  It would be good to have the option to keep them on the primary color for as long as the key is held down, then to begin fading on release.  I think this should be the default behavior, but having the option would be even better.

**Comment by simon-wh** [comment]
This was added thanks to PR #676 and is available in development releases.
