### ISSUE TITLE
Razer Wrapper not working

### ISSUE THREAD

**Issue by mastamike911** [antonpup/Aurora#624]
I seem to be having a problem using the Razer Wrapper in the latest "dev" version of Aurora. I've tried testing it on something simple like KeyboardVisualizer or something more complex like Diablo III, but the results are the same each time... The desktop profile is all that I get. 

My equipment:
- Razer Mamba TE
- Razer Firefly
- Cooler Master MasterKeys Pro S

I've tried running Aurora as Admin, as well as moving it to the top of the list in Synapse. I'm not sure what else I could try.

### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [x] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
When using the Razer Wrapper, I expect Razer supported games/apps would work like they should as a Chroma App.

### Actual behavior:
The Aurora Desktop profile is still showing up, and errors are being logged in the log file.

### How often does this problem occur?

This problem occurs... always.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Install Razer wrapper on a Chroma supported app (like KeyboardVisualizer).
2. Run app.

### What is the version of Aurora you are experiencing this issue with?

My version is... beta v.0.6.0-dev2

### Does the previous version of Aurora have this issue?
Unsure. I have not tried a previous version.

### Please include any logs, screenshots, or files that are related to this issue:

This exception gets posted over and over again.

6/26/2017 2:48:42 PM: [IPCServer] Pipe connection established
[WARNING] 6/26/2017 2:48:42 PM: Exception during GameStateUpdate(), error: System.ArgumentNullException: Value cannot be null.
Parameter name: path4
   at System.IO.Path.Combine(String path1, String path2, String path3, String path4)
   at Aurora.Profiles.Application..ctor(LightEventConfig config) in B:\Repos\Aurora\Project-Aurora\Project-Aurora\Profiles\Application.cs:line 111
   at Aurora.Profiles.LightingStateManager.GameStateUpdate(IGameState gs) in B:\Repos\Aurora\Project-Aurora\Project-Aurora\Profiles\LightingStateManager.cs:line 703

**Comment by simon-wh** [comment]
Just got it fixed, will be available in the next release.
