### ISSUE TITLE
Default lighting (CUE, LGS, etc) not showing when desktop is disabled

### ISSUE THREAD

**Issue by Dagda52** [antonpup/Aurora#625]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [x] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (K95 RGB)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [x] Other, (Overviwe for dektop)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Disabling overview for desktop should enable CUE default lighting profiles programed in CUE software. and other automatic cue profiles should be working too even if this option is disabled
### Actual behavior:
Disabling overview for desktop is shutting down completely the keyboard from all light.

### How often does this problem occur?

This problem occurs... (Every time)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Enable Aurora
2. Enable Corsair SDK
3. Disabling aurora to provide effects for desktop in the desktop setting tab

### What is the version of Aurora you are experiencing this issue with?

My version is... (0.6.1-dev)

### Does the previous version of Aurora have this issue?
The previous version, (0.6.0b Beta), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
What you're talking about is more like a possible enhancement rather than an issue. Aurora has never been designed to switch back to CUE lighting when desktop has been disabled. I don't know if it is necessarily feasible either because without looking into it at all I imagine it would require the connection to the SDK to be turned off by default and turned on once a supported game is in the foreground and toggled any time you tab out of the game.

**Comment by LZStealth** [comment]
I'd also noticed this problem in the newer version (on my K70). Deleting the config in AppData and returning to v0.6.0 fixed this issue for me and returned to CUE profiles when disabling desktop within Aurora. e.g. Aurora in game and CUE for desktop / non-Aurora stuff.
Not sure what has changed between this time however, but i'm guessing this is a Corsair specific change.

It's a shame we cant overlay items like volume ontop of CUE settings (not sure if that'll become available with the CUE SDK now allowing shared or exclusive control).

**Comment by brainbug89** [comment]
> What you're talking about is more like a possible enhancement rather than an issue. Aurora has never been designed to switch back to CUE lighting when desktop has been disabled. I don't know if it is necessarily feasible either because without looking into it at all I imagine it would require the connection to the SDK to be turned off by default and turned on once a supported game is in the foreground and toggled any time you tab out of the game.

It worked before (like I said here #581 v0.6.0b works fine), because @antonpup added it after I asked for: "Added option to restore LEDs on desktop profile"

**Comment by simon-wh** [comment]
@brainbug89 did you not see that I had crossed through my previous comment because I was wrong? I added an option/setting to it when I was fixing this issue because who doesn't want more control over how the application behaves?

**Comment by brainbug89** [comment]
Oh I didn't saw it was crossed out, because I only read the notification mail.
Nice you fixed it. :+1:
