### ISSUE TITLE
I cant open it.

### ISSUE THREAD

**Issue by emironder** [antonpup/Aurora#626]
i've installed aurora but its not working. im opening program and i can see it in task manager but a little later it closes without error. 

windows 10 64 logitech g410
![image](https://user-images.githubusercontent.com/20914294/27659470-41782962-5c5c-11e7-8e55-e2966b0ec241.png)

**Comment by simon-wh** [comment]
Can you upload the logs from %appdata%/Aurora/logs and are you running software like MSI Afterburner(It has been known to cause these kinds of issues)?

**Comment by simon-wh** [comment]
Duplicate of #605. Please post any follow up in that issue.
