### ISSUE TITLE
Aurora minimizing bug

### ISSUE THREAD

**Issue by driftking47007** [antonpup/Aurora#629]
### What are you experiencing an issue with?

- [x ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
Whenever I minimize the lights should stay on the breathing effect between orange and white.
### Actual behavior:
Explain here what happened instead.
Whenever I minimize it, it just stops the effects and goes back to normal
### How often does this problem occur?

This problem occurs... (Fill in here)
This happens everythig
### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Choosing custom lighting effects
2. Minimizing the program

### What is the version of Aurora you are experiencing this issue with?

My version is... (Fill in here)
beta v0.6.0b
### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.
This is my first time using aurora.
### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
What profile/application are you applying the effect to?

**Comment by driftking47007** [comment]
I applied it to the BS application all the way to the bottom, I didn't know how to add my own application in, so I just used the Blade and Soul one.

**Comment by simon-wh** [comment]
The lighting you see when you've selected Blade and Soul is just a preview and will be shown on the keyboard when the game is running. When you minimise Aurora it defaults to the Desktop if the foreground application is not one that has its own profile. If you want to see the breathing lighting effects normally you need to apply it to the desktop application, not a game.
