### ISSUE TITLE
Mass effect andromeda on corsair?

### ISSUE THREAD

**Issue by txeptsyip** [antonpup/Aurora#639]
is there a way to get it to work or does it have to be supported by aurora?

i have applied the patch for logitech (there is no patch for corsair? i am using a K95 with the latest version of CUE)

**Comment by brainbug89** [comment]
> i have applied the patch for logitech (there is no patch for corsair?

You need to patch the wrappers for the game, not for your device. The patched files sending the lighting informations to Aurora instead to e.g. Logitech and Aurora then sends it to the API of your device (like CUE ). So patching the Logitech files should work theoretical.
Is MEA sending lighting information (maybe some options needs to be activated at the settings of Mass Effect)? Is your Corsair keyboard shown as conntected at Aurora settings? (Can you change lightings at Desktop mode?)

**Comment by txeptsyip** [comment]
> That's right. You need to patch the wrappers for the game, not for your device. The patched files sending the lighting informations to Aurora instead to e.g. Logitech and Aurora then sends it to the API of your device (like CUE ). So patching the Logitech files should work theoretical.
Is MEA sending lighting information (maybe some options needs to be activated at the settings of Mass Effect)? Is your Corsair keyboard shown as conntected at Aurora settings? (Can you change lightings at Desktop mode?)

ah right yes i can change the desktop lights (i was messing about with the sound display thing and ambient light)

from what you said in a thread about shovel night you navigate to the game and patch for razer should that be the same for logitech? (when i click patch aurora for logitech it just says all done and does not let me select anything when i click patch for razer it brings up a select folder type window)

**Comment by simon-wh** [comment]
@txeptsyip The Razer and Logitech wrappers work differently. The Razer and LightFX ones require to be in the game directory, the Logitech one is global. If you can't get it to work you can try installing LGS which may help.

**Comment by txeptsyip** [comment]
@simon-wh i have the LGS installed already as i have a G502 proteus spectrum and had a G710+

**Comment by txeptsyip** [comment]
updated to latest LGS version ran MEA with my G710+ plugged in the G710+ lights went out (as it does they flash when in combat) closed LGS and MEA patched logitech ran MEA without running LGS again nothing happened to either keyboard

closed MEA ran LGS ran MEA again nothing happened to either keyboard again

restarted the computer made sure everything was up (aurora CUE LGS) ran MEA and nothing happened to either keyboard yet again

**Comment by simon-wh** [comment]
@txeptsyip can you try using the [latest development release](https://github.com/antonpup/Aurora/releases) if you aren't already? Make sure you repatch after you install.

**Comment by txeptsyip** [comment]
@simon-wh so i downloaded v0.6.1-dev deleted the files from aurora and put the files from the zip into there (i did do that correctly right? it did complain about crashing on start up but i found running it as admin fixed that - it is installed to C:\program files)

i also did the same to LGS

i then restarted (as LGS wanted me to do that) plugged in my G710 alongside the corsair and then patched logitech restarted (again just to make sure) and then ran MEA

nothing from either keyboard

tried MEA without LGS up nothing again

**Comment by txeptsyip** [comment]
@simon-wh 

so i just downloaded the division and applied the patch and sod all happens and as that would appear to be a game that should 100% work i think something is borked on my end

should i try the CUE1 or w/e people call it (your screenshots for first run corsair seem to be for an older version of CUE)

**Comment by brainbug89** [comment]
Use the latest version of CUE (2.14.67). When you run Aurora and then open CUE2 and click on Lighting Effects (on keyboard), there should be the message "Lightings are controlled by thrid-party application" shown.

**Comment by txeptsyip** [comment]
@brainbug89 yes the new dev version of aurora i installed does that i have been using the desktop ambilight/equalizer things quite a bit

previously on the older version of aurora if i turned desktop lighting aurora control off it would let CUE control the lights again now i have to close down Aurora to get them back

i am currently using the latest dev version of Aurora the latest version of CUE 2.14.67 and the latest version of the logitech software

also if i knew how to completely delete the settings and everything for LGS that could help as for some reason it has two auroras

**Comment by simon-wh** [comment]
@txeptsyip The issue you mentioned with the lighting returning to CUE when desktop is disabled has been fixed in the dev branch and will be available in the next release. If you want to delete all the save files for Aurora you can delete the %appdata%/Aurora folder. Also, just to verify you can't get lighting for The Division and MEA to work after patching on the latest development release?

**Comment by txeptsyip** [comment]
@simon-wh that would be correct yes

i am going to try removing anything to do with LGS and Aurora from my computer and i will then try again and see if that fixes anything

**Comment by txeptsyip** [comment]
update

so i acquired a G910 orion spectrum (and dear lord these switches feel horrible mushy and inconsistent what the hell is logitech thinking?)

with a fresh install of LGS MEA and division work perfectly

when i patch logitech it stops all reactive lighting in MEA and division on the G910 (aurora set for G910 btw)

(i did not have the K95 RGB platinum plugged in CUE might have been running in the background)

could logitech have changed something in a recent update to LGS?

**Comment by ersan** [comment]
Same situation, Mass Effect Andromeda does not work.

**Comment by Dagda52** [comment]
Yeah Adromeda doesnt do anything at all compared to other games that at least have partial effectos like bf1

**Comment by simon-wh** [comment]
It could be a case similar to other games like H1Z1 and possibly Warframe where the game doesn't load the wrapper due to an Anti-cheat or similar. @Dagda52 @ersan @txeptsyip Just to clear it up, is it the case where after patching, MEA just doesn't change anything or does it make the keyboard go blank and doesn't display anything beyond that? If it just doesn't change anything and continues desktop lighting then I think my statement might be the case for MEA.

**Comment by Dagda52** [comment]
In the case of MEA and warframe, yeah the keyboard is just in the desktop lighting it doesn´t change, i even tried puting the dlls in windows/system32 ans syswow64 like when you install razer sdk.

**Comment by simon-wh** [comment]
@Dagda52, In that case I'm going with my theory about the Anti-Cheat blocking the wrapper
