### ISSUE TITLE
World of Warcraft support?

### ISSUE THREAD

**Issue by Tojaken** [antonpup/Aurora#64]
Would there be any chance at getting support for World of Warcraft. I currently love the set up for the other games and i beleave that there is sdk.

**Comment by antonpup** [comment]
My apology for the delay. Was taking a break.

WoW does not have an easy to use SDK. There is a project with WoW for G910, [http://home.earthlink.net/~waldokind/WoW_G910_Home/Welcome_Gamers.html](http://home.earthlink.net/~waldokind/WoW_G910_Home/Welcome_Gamers.html). I have contacted this guy, and I might expand upon his method of supporting WoW. But I would like to see if there is a better alternative.

**Comment by Tojaken** [comment]
i did find that first when i was looking for lighing effects but it never worked. here is hopeing its was all me and java just hated me when i tryed to get it to work and link in to logitech gaming

**Comment by antonpup** [comment]
So something just phased me, and I realized that that linked program. Will work perfectly fine with Aurora, as long as you apply Aurora's Logitech Wrapper, and keep Aurora running in the background. This obviously isn't "full support", but it still allows RGB lighting with WoW.

**Comment by mastamike911** [comment]
Has anyone been able to make the WoW G910 work completely with Aurora? It seems like Aurora needs whatever application that is controlling the LEDs to be in the foreground, but that causes a problem when you need WoW G910 to be running AND WoW itself. The WoW G910 program can control the LEDs on my keyboard just fine when its window is active, but once I alt+tab into WoW, Aurora sets the LEDs back to the desktop profile.

**Comment by darkdex52** [comment]
> My apology for the delay. Was taking a break.
> 
> WoW does not have an easy to use SDK. There is a project with WoW for G910, http://home.earthlink.net/~waldokind/WoW_G910_Home/Welcome_Gamers.html. I have contacted this guy, and I might expand upon his method of supporting WoW. But I would like to see if there is a better alternative.

Link is dead. Is there any other current project/support for WoW?

**Comment by comepso** [comment]
> > My apology for the delay. Was taking a break.
> > WoW does not have an easy to use SDK. There is a project with WoW for G910, http://home.earthlink.net/~waldokind/WoW_G910_Home/Welcome_Gamers.html. I have contacted this guy, and I might expand upon his method of supporting WoW. But I would like to see if there is a better alternative.
> 
> Link is dead. Is there any other current project/support for WoW?

Here is new website http://www.jdsoftcode.net/g910-home.html
