### ISSUE TITLE
K95 Platinum Key light issue

### ISSUE THREAD

**Issue by woloss** [antonpup/Aurora#641]
### What are you experiencing an issue with?
- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?
- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [x] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
All key lights work properly.

### Actual behavior:
Key "\ | /" over "Enter" don't light at all.
In game, this key + g2-g6 don't work as well. (tried in Overwatch).

### How often does this problem occur?
This problem occurs when Aurora launched

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Set K95 device
2. Start the game like Overwatch with Aurora Wrapper for Razer
3. Problem occur

### What is the version of Aurora you are experiencing this issue with?
My version is 0.6.0 dev-2

### Does the previous version of Aurora have this issue?
The previous version, 0.6.0b, did have this issue.

Also, not bad to see implementation of Light Bar anytime soon.

**Comment by simon-wh** [comment]
What keyboard layout do you have? Also, certain keys might not light in Overwatch because the lighting in Overwatch is designed and sent from Overwatch so if it doesn't light specific keys then it is because Overwatch doesn't set lighting for those keys.

**Comment by woloss** [comment]
Ok, thank you. United States Layout help with that issus. About Overwatch, well, I understood. Thank you, will wait for Light Bar support :)
