### ISSUE TITLE
No switching to AdditionalProfiles for games

### ISSUE THREAD

**Issue by CermakPOI** [antonpup/Aurora#646]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [x] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, (Fill in another type of issue here)

### Expected behavior:
When switching to Heroes of the Storm or Planetside 2 the Profile should switch.

### Actual behavior:
Desktop profile is still active.
I tried "Windows Evetns" and "Foreground App Scan", running as normal user and Admin.
I tried running HOTS in Window mode.

### How often does this problem occur?

This problem occurs always.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. create Profile for Games::
heroes of the storm.exe or/and
HeroesOfTheStorm_x64.exe
planetside2_x64.exe
2. start Game
3. Normal Apps work (Notepad++, Battle.net client)

### What is the version of Aurora you are experiencing this issue with?
My version i tested with: 0_6_0 and 0_6_1-dev

### Does the previous version of Aurora have this issue?
I started useing Aurora with 0_6_0

### Please include any logs, screenshots, or files that are related to this issue:
https://pastebin.com/dNbTpbgf

**Comment by simon-wh** [comment]
Can you post the contents of %appdata%\Roaming\Aurora\Profiles\desktop\HOTS.json and %appdata%\Roaming\Aurora\Profiles\overwatch\Planetside.json

**Comment by CermakPOI** [comment]
[AdditionalProfiles.zip](https://github.com/antonpup/Aurora/files/1146426/AdditionalProfiles.zip)
[Profiles.zip](https://github.com/antonpup/Aurora/files/1146430/Profiles.zip)

**Comment by simon-wh** [comment]
@CermakPOI If you create a new profile for other applications that are not HOTS or Planetside does it switch to them if you have them open (I'm not sure if that is what you meant by "Normal apps work")? I think there might be a permission issue with it detecting the games being open, could you also try running Aurora as admin to see if it makes a difference?

**Comment by CermakPOI** [comment]
Normal App: Notepad++
I tried as Admin - same. Is HOTS/Planetside 2 working for anybody?

**Comment by simon-wh** [comment]
I think it must be a permissions issue that HOTS/Planetside 2 is preventing Aurora from reading it as the foreground process. I'll see if I can try and find a workaround.

**Comment by simon-wh** [comment]
This should be fixed through the PR made by #738 which will be available in the next release.
