### ISSUE TITLE
Aurora opens before Corsair CUE on boot up, causing it to work incorrectly.

### ISSUE THREAD

**Issue by User5432112345** [antonpup/Aurora#648]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [x] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
With both Corsair's CUE and Aurora set to start on boot, CUE and Aurora should start in such a way that Aurora can control Corsair devices.

### Actual behavior:
Aurora opens before CUE, and then Corsair devices are unresponsive to Aurora, responding instead to CUE only. Closing and reopening Aurora fixes the problem. A workaround also exists in setting a delay before Aurora opens on startup by using a batch file (and using a shortcut to an executable made from the batch file can do this silently). 

### How often does this problem occur?

On bootup, every time.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Set CUE and Aurora to run on startup.
2. Boot up computer.

### What is the version of Aurora you are experiencing this issue with?

0.6.0b

### Does the previous version of Aurora have this issue?
Unknown.

**Comment by simon-wh** [comment]
I believe I've fixed this issue in the dev branch as I was also having issues with CUE and Aurora on startup and they are now resolved. The issue I fixed was the working directory on startup being C:\Windows instead of the Aurora directory causing it to not being able to find the CUE SDK dll.

**Comment by User5432112345** [comment]
Thanks for the response and for addressing this problem.

One other question:  Is it correct that Aurora cannot control Corsair devices without CUE running in the background?  It would be nice to be able to have Aurora as the only open program running my RGB peripherals, but I understand if the Corsair SDK imply doesn't allow it.

**Comment by simon-wh** [comment]
I'm not entirely sure if CUE is required as I haven't really looked into it. But considering you have to enable the SDK in CUE I'm assuming it means that the SDK runs through CUE so it would be required for it to be open.
