### ISSUE TITLE
After 0.6.0-dev2 install, CM Keyboard no longer initializes.

### ISSUE THREAD

**Issue by User5432112345** [antonpup/Aurora#653]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Actual behavior:
After installing v0.6.0-dev2, my CM Masterkeys Pro S is no longer initializing in Aurora, and cannot be controlled from it. The log file (attached) contains the following: "[ERROR] 7/11/2017 7:45:10 PM: There was an error initializing Cooler Master SDK. An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)".  My mouse (Corsair Sabre) still seems to be working correctly in Aurora.

<del>Additionally, after the install, v0.6.0b is not working at all, and fatally crashes on boot, showing the attached message. This problem persists even after removing both versions of Aurora and reinstalling using the web installer.</del> I fixed this by deleting the folder (user name)/AppData/Roaming/Aurora and reinstalling. Doing the same and reinstalling the dev version did not solve the issue with my keyboard, however. 

### What is the version of Aurora you are experiencing this issue with?
0.6.0-dev2

### Please include any logs, screenshots, or files that are related to this issue:
[AuroraLog.txt](https://github.com/antonpup/Aurora/files/1140582/AuroraLog.txt)

**Comment by simon-wh** [comment]
The issue with CM keyboards not working in the latest dev is due to the 32-bit dll being included instead of the 64-bit version by accident. It won't be a problem in the next development release.
