### ISSUE TITLE
Aurora Crashing on launch

### ISSUE THREAD

**Issue by UltimateUltimo** [antonpup/Aurora#655]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### How often does this problem occur?

This problem occurs every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Try running the executable file
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is 0.6.1-dev

### Does the previous version of Aurora have this issue?
The previous version, 0.6.0b Beta ,did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

Screenshot - [![Screenshot from Gyazo](https://gyazo.com/fedf09a90d6e54ed98b413ec7dec9e62/raw)](https://gyazo.com/fedf09a90d6e54ed98b413ec7dec9e62)

**Comment by simon-wh** [comment]
Delete %appdata%/Aurora

**Comment by UltimateUltimo** [comment]
Thx!
