### ISSUE TITLE
Corsair K55 now has CUE SDK

### ISSUE THREAD

**Issue by Sparqey** [antonpup/Aurora#656]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Add the K55 Keyboard
### Actual behavior:
None

### How often does this problem occur?
This problem occurs Every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:
Try a Corsair K55 RGB keyboard.

### What is the version of Aurora you are experiencing this issue with?

My version is... (Fill in here)

### Does the previous version of Aurora have this issue?
Yes

### Please include any logs, screenshots, or files that are related to this issue:
http://forum.corsair.com/v3/showthread.php?t=169000

### Extra
Corsair added the CUE SDK for the K55 so i assume that makes it possible to inplement it into Aurora

**Comment by brainbug89** [comment]
Can't read anything bout K55 RGB in the linked thread.

**Comment by Sparqey** [comment]
http://i.imgur.com/J8GdiOs.png

**Comment by simon-wh** [comment]
Because CUE supports the keyboard doesn't mean that the CUE SDK supports it. The latest CUE SDK does not say that it supports the K55.

**Comment by BEMZ01** [comment]
Looking through the SDK supported devices list https://corsairofficial.github.io/cue-sdk/#supported-devices
It seems that K55 RGB is supported through the CUE SDK. However, the actual keyboard has only three lighting zones which may be screwing up the software.
![image](https://user-images.githubusercontent.com/48926280/115011275-5c959a00-9ea6-11eb-8758-b8f051ab027f.png)
