### ISSUE TITLE
Brazilian keyboard layout

### ISSUE THREAD

**Issue by viniciushvc** [antonpup/Aurora#659]
Hi there, can i change the layout of Logitech 810, because my keyboard has a key "\" over "ENTER" but aurora is different, and this key don't change the color.

**Comment by brainbug89** [comment]
What layout (US, UK, DE, FR, ...) is your keyboard? And which layout you selected at Aurora settings?

**Comment by viniciushvc** [comment]
thanks, I did not know that, thanks, I use this keyboard in Brazil with layout US

**Comment by simon-wh** [comment]
Duplicate of #504
