### ISSUE TITLE
How to delete desktop profile

### ISSUE THREAD

**Issue by borntalent** [antonpup/Aurora#66]
How do i disable the desktop profile as i like the logitech chromo wave in my G910 from the logitech software?

**Comment by antonpup** [comment]
You cannot, but you should be able to recreate Logitech's profile in Aurora.

**Comment by borntalent** [comment]
@antonpup  can you guide me to it if possible? as with your desktop one my G keys do not change to chroma colors

**Comment by antonpup** [comment]
@borntalent The G-keys and logos are not supported in the SDK. Once they are, I will add support for them.

But you should be able to create a new Color Zones, fill it to the size of the virtual keyboard, and select Rainbow effect. (I think that's what you want, yes?)

**Comment by borntalent** [comment]
@antonpup  yup got it! Thanks man and keep up the good work!
