### ISSUE TITLE
CUE crashes with aurora

### ISSUE THREAD

**Issue by FrancoCJ** [antonpup/Aurora#660]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [x] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [x] Other, (CUE 2)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

I play a lot of overwatch, and i keep noticing that sometimes after leaving the game (like closing it) the k/b gets stuck with the lights of the last heroe I used, and CUE 2 doesnt respond, i have to close it from the task manager and re launch it

### What is the version of Aurora you are experiencing this issue with?

My version is beta 0.6.0b

### Does the previous version of Aurora have this issue?
I really dont know when it started happening

**Comment by brainbug89** [comment]
I noticed the same with csgo. Are you using the latest version of CUE 2.15?

**Comment by FrancoCJ** [comment]
just checked and its 2.12
Gonna update to 2.15 and if I keep having those I'll be back

I hate that cue2  cant auto updte nor manual update from the app

**Comment by User5432112345** [comment]
I just wanted to report that I have experienced similar crashes. The lighting locks on whatever is being shown at the time of the crash and all input from all connected keyboards and mouses is also locked.

I am using a Masterkeys Pro S RGB + Corsair Sabre with CUE 2.14.67 running alongside Aurora (v0.6.0b). I have not noticed crashes like this at any time that Aurora is not running (even with CUE running)  

Incidentally, crashes like this one are the only reason I am not currently running Aurora at all times, but I understand that Aurora is still under development.

**Comment by brainbug89** [comment]
With 2.15 I haven't notice any problems yet.

> I hate that cue2 cant auto updte nor manual update from the app

This was fixed some time ago. With new CUE version you can use the built-in update function.

**Comment by FrancoCJ** [comment]
> This was fixed some time ago. With new CUE version you can use the built-in update function.

I had the 2.12 and the search for updates wasn't working, good to know that its fixed

**Comment by simon-wh** [comment]
@FrancoCJ Can you post your Aurora logs? I think this might be more of a CUE issue rather than an Aurora issue but maybe the logs will give some helpful information.

**Comment by simon-wh** [comment]
@FrancoCJ Could you get the information I asked for above, please? Closing for now
