### ISSUE TITLE
Overwatch effect stops working if I alt tab

### ISSUE THREAD

**Issue by ThallesAdorno** [antonpup/Aurora#661]
### What are you experiencing an issue with?

- [ ] Aurora
- [x] Aurora supported game, Overwatch
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, Light effecta 

### Expected behavior:
Alt tab wouldn't affect it

### Actual behavior:
When I alt tab, the mouse (I have no keyboard), Logitech G502, goes back to the static color I normaly use

### How often does this problem occur?

This problem occurs... Every time I alt tab overwatch and open it again (I'm using fullscreen), It's only fixed if I enter in another game

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Get into a game, select character
2. Alt tab
3. Alt tab back to overwatch

### What is the version of Aurora you are experiencing this issue with?

My version is... v0.6.0b

### Does the previous version of Aurora have this issue?
Don't know, started using it today

**Comment by simon-wh** [comment]
Could you try the [latest development release](https://github.com/antonpup/Aurora/releases) to see if it makes a difference?

**Comment by ThallesAdorno** [comment]
Tried it, still have the issue

**Comment by ersan** [comment]
Not seeing this issue here, when I tab back into the game it resumes the Overwatch lighting.

**Comment by simon-wh** [comment]
@ThallesAdorno Is you App Detection method set to Windows Events? If so could you try setting it to Foreground app scan?

**Comment by simon-wh** [comment]
@ThallesAdorno Any updates on this?

**Comment by ThallesAdorno** [comment]
I'm terribly sorry for not answering before, my classes are back and I'm not playing OW right now (usually only one game at a time). I plan to buy an RGB keyboard (and ditch my 5 dolars one) until the end of the year. When it happens I will update you about it (I'll do a new thread so you can rest about this one). Thank you for your support, it really surprised me that you even asked again, when I buy my keyboard I will make sure to make a donation. Thanks for everything again, you are an amazing dev

**Comment by simon-wh** [comment]
@ThallesAdorno Thank you! I hope that the suggestion I made will resolve the issue you were experiencing when you're can test it.

**Comment by Nivyox** [comment]
Hey, I am having the exact same problem. I am sorry that I'm like 9 months late. The suggestion you made did not solve it for me @simon-wh

**Comment by simon-wh** [comment]
@Nivyox What version of Aurora are you using?

**Comment by Nivyox** [comment]
my bad for bumping this, i just downloaded the latest dev version and it got fixed, thank you though!

**Comment by simon-wh** [comment]
@Nivyox No problem! I'm glad your problem is sorted!
