### ISSUE TITLE
Warframe

### ISSUE THREAD

**Issue by Sabalom** [antonpup/Aurora#663]
Warframe recently added support for razer chroma, is it possible to have this on aurora?

**Comment by simon-wh** [comment]
If it has Razer Chroma you should be able to just patch it using the Razer Wrapper in Settings and get the effects until proper support is added.

**Comment by Dagda52** [comment]
Does someone figured out in wich folder do you put the sdk files? cos i tried in every folder and it didn´t work

**Comment by diogotr7** [comment]
I can't get it to work either.

**Comment by Dagda52** [comment]
Maybe its like h1z1 and some anticheat can´t let load the dlls

**Comment by ersan** [comment]
Can't get it to work either, not sure if it's significant but I noticed that it does not have support for the BlackWidow Chroma, only for the BlackWidow Chroma V2 - I tested this using just the Razer software and my keyboard does not light up because it is a BlackWidow Chroma Stealth, my mousepad does light up however.

I'm not sure if Aurora is intercepting lighting commands for a specific keyboard type or not but this game does not work with the original BlackWidow Chroma.

**Comment by ersan** [comment]
Indeed, doesn't work - once you put the DLL's in the main folder none of the lighting effects work.  Without the DLL's they work fine in the Razer app.

**Comment by simon-wh** [comment]
It does seem like it might be a similar case to H1Z1 where it doesn't load the dlls. I'll get Warframe downloaded to see if I can verify.

**Comment by simon-wh** [comment]
@ersan Can you find any DLL's from Razer normally in the Warframe files?

**Comment by Dagda52** [comment]
@simon-wh i think he meant once you put the wraper dlls from aurora, the razer effects in this game will not load unless you delete those dll´s and let razer synapse catch the game instead.

**Comment by icexuick** [comment]
Hope someone finds the solution, would be neat!

**Comment by f3rs3n** [comment]
@simon-wh Razer DLL's are normally found in Warframe\Tools\Windows\x86 and x64.

**Comment by DBIANX** [comment]
Has anyone been able to make it work? i really hope so

**Comment by diogotr7** [comment]
With recent changes to the wrapper i hoped this would work but upon patching the game, the wrapper files were deleted on patching. I made them read-only but the game wont load the dll's regardless.
I'm afraid the game has some sort of anti cheat so implementation is probably impossible right now.

**Comment by PixelHir** [comment]
I can confirm that Warframe fully works now.
