### ISSUE TITLE
Fatal crash

### ISSUE THREAD

**Issue by bobtb98** [antonpup/Aurora#668]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ x] Other, (Was called order to contact author)

### What kind of an issue is it?

- [ x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Program should start

### Actual behavior:
Program crash

### How often does this problem occur?
not sure

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. double clicked the program
2.  this message appear 
3.  this happen after I downloaded and use the pre beta version

### What is the version of Aurora you are experiencing this issue with?

My version is... (0.06b)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue
(there are some issues with the overwatch game ...... will create a seperate report for that .)

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/ShVC9Vb
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
Delete %appdata%/Aurora
