### ISSUE TITLE
When start Aurora 0.4.8 my Logitech G633 headset light will turn off

### ISSUE THREAD

**Issue by shikkoku** [antonpup/Aurora#67]
I must open LGS and click on light icon to turn on or reconnect my headset. Can fix it?

**Comment by antonpup** [comment]
The headset lights are tied to the mouse lighting. So, if your mouse is set to rainbow effect, your headset will also be rainbow.

If you're having connection issues, that isn't an issue with Aurora. Contact Logitech for that.

**Comment by shikkoku** [comment]
Thank you for your reply. I set my mouse to rainbow effect, my headset work fine now.

But no change on my mouse(still using LGS setting effect). My mouse is Logitech G502.

**Comment by antonpup** [comment]
The G502 might be an SDK issue. Because it's an RGB device, thus it should be colored like the headset.

**Comment by shikkoku** [comment]
I replaced the mouse to Logitech G303. Now my mouse colored like the headset.

**Comment by antonpup** [comment]
Yeah. I'm fairly certain that G502 isn't supported by the SDK for some reason. It should be working fine.
