### ISSUE TITLE
Suggestion: Global Layers

### ISSUE THREAD

**Issue by diogotr7** [antonpup/Aurora#670]
I think a good addition would be layers that get applied to every program.

For example, I have a layer that turns the caps lock key red when it's on, and I'd like it to be applied to every application.

**Comment by simon-wh** [comment]
This will be possible with the new Overlay/Underlays system which is planned for v0.7.0. I'll leave this open as a reminder for the option to have Overlays/Underlays always active.

**Comment by diogotr7** [comment]
This has been implemented as of v0.7.0 with desktop overlays.
