### ISSUE TITLE
Razer Lancehead TE and Razer Ornata Chroma support

### ISSUE THREAD

**Issue by lolrepeatlol** [antonpup/Aurora#672]
Please add real Ornata and Lancehead support. 

Thanks :P

**Comment by simon-wh** [comment]
The Lancehead TE doesn't appear to be supported by the [Chroma SDK](http://developer.razerzone.com/works-with-chroma/compatible-devices/) so there isn't much I can do about that. Also, the Ornata is supported and doesn't seem to have any lighting other than the standard keys so just use one of the other Razer keyboard layouts that are similar to it like the Blackwidow
