### ISSUE TITLE
High CPU % and Game/mouse/keyboard lag

### ISSUE THREAD

**Issue by thu2468** [antonpup/Aurora#673]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [x] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
should not lag

### Actual behavior:
Lag games b.c of cpu goes up
Also FPS Goes down in game

### How often does this problem occur?
Every time i use my repeat while press mouse macro

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Use macro
2. High CPU goes up for aurora
3. Game Lags

### What is the version of Aurora you are experiencing this issue with?
6.0b
### Please include any logs, screenshots, or files that are related to this issue:
https://surl.im/i/odfup.jpg The high CPU % when macro active
https://surl.im/i/672n9.jpg The Macro i use

**Comment by simon-wh** [comment]
Are you using this in a game that doesn't have support in Aurora. So the Desktop effects are being displayed? If so, I'm pretty sure the source of the lag is the Interactive Layer, so you can try disabling that for now until I get something implemented to reduce lag when using macros.

**Comment by simon-wh** [comment]
I think the improvements I made in the commit above are the best I can do right now to improve performance for this case. Something I just considered, do you really need a macro that repeats so frequently? If you continue having performance issues in the dev builds with the macro you should either stop using the interactive layer or you should try reducing the rate of your macro.
