### ISSUE TITLE
G910 Stuck lighting \| bug 

### ISSUE THREAD

**Issue by Xanarinera** [antonpup/Aurora#674]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Just trying to run the default desktop software

### Actual behavior:
So Ive just formatted my pc and reinstalled aurora (great program btw) and now for some reason the \| key sticks to the last colour that the lgs software had it running at before aurora starts up

### How often does this problem occur?
Every time since formatting, however i did do a firmware update on my g900 (mouse) after as well, and the lighting will go from keyboard to mouse but not the other way around since that update 

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. the issue is persistent and has been do this since first startup of aurora,
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is beta v0.6.0b

### Does the previous version of Aurora have this issue?
I did have this issue prior to reinstall but it went away after a few days no idea why sorry 

### Please include any logs, screenshots, or files that are related to this issue:

http://s000.tinyupload.com/index.php?file_id=10841787296114110377

**Comment by simon-wh** [comment]
Does anything change if you use the Solid Colour layer and select it to light that particular key? Does it change to the colour set for the layer?

**Comment by Xanarinera** [comment]
It changes the colour if I'm using the lgs software but as soon a I minimise and aurora takes control it sticks again(to the colour I just set in lgs). 
I'll try changing the layer on aurora, I'm away at work for the next few days, so I'll update when I get home. Thanks

**Comment by Xanarinera** [comment]
Ok so i tried setting a solid colour layer on that key and the surrounding keys and it didn't work sadly.
Here a pic of what i did http://s000.tinyupload.com/index.php?file_id=88883813499348751344

**Comment by simon-wh** [comment]
What Keyboard layout have you selected? It seems you have a US keyboard but you don't have the US keyboard layout selected.

**Comment by Xanarinera** [comment]
Wow so i changed it from auto select to us layout and it fixed it
