### ISSUE TITLE
Numpad Enter/Return activates normal Enter/Return events

### ISSUE THREAD

**Issue by DogeAmazed** [antonpup/Aurora#675]
### What are you experiencing an issue with?
- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?
- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Numpad Enter/Return is getting used.

### Actual behavior:
Enter/Return is getting used.

### How often does this problem occur?
Every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:
1. Enable Interactive Layer with e.g. Key Fade
2. Press Numpad Enter/Return

### What is the version of Aurora you are experiencing this issue with?
My version is... beta 0.6.1

### Does the previous version of Aurora have this issue?
The previous version, (beta 0.6.0b), did have this issue.

### Please include any logs, screenshots, or files that are related to this issue:
N/A

**Comment by simon-wh** [comment]
This is something we cannot do anything about as all the information we get when the key is pressed in this case is that enter has been pressed. There is no way to differentiate between the numpad enter and the normal enter.

**Comment by shadowlif** [comment]
@simon-wh Well it is possible, because the hook have an flag set for that. So I need to create an pull request in the GlobalMouseKeyHook repo, so the API expose the flags?

**Comment by simon-wh** [comment]
If you can get it working then go for it. I was just going with what I was aware of before as currently I'm not able to do any investigation into it right now.

**Comment by shadowlif** [comment]
Do you prefer to include the repo like ColorBox or updating the original?

**Comment by simon-wh** [comment]
@DogeAmazed Well, do you want to setup a PR for the original repo and include the project here until the changes are merged?
