### ISSUE TITLE
How to add a memory reading profile like Rocket League?

### ISSUE THREAD

**Issue by TheFacelessOne** [antonpup/Aurora#677]
Title says it all, i'd like to make profiles for my games and memory reading seems like the simplest way to do it... but I don't know how to go about doing it.

**Comment by shadowlif** [comment]
Well, you need to find the base addresses an the offsets of the variables of your game. These are most of the time changing if you build your project new, but persist after restart.
To get started with it, you can try to use CheatEngine to find base addresses. Also there are lots of tutorials how to find these.

**Comment by TheFacelessOne** [comment]
I've used cheat engine before and know how to find the addresses... I don't know how to implement them into Aurora...

**Comment by shadowlif** [comment]
Well, you just need to create a new profile. You can use the RocketLeague one as an example, just copy and edit it as you need to.

For Memory Reading:
You can look into https://github.com/antonpup/Aurora/blob/100b4185866a7679d438b8b57ba61a9de9fac635/Project-Aurora/Project-Aurora/Profiles/RocketLeague/GameEvent_RocketLeague.cs and https://github.com/antonpup/Aurora/blob/100b4185866a7679d438b8b57ba61a9de9fac635/Project-Aurora/Project-Aurora/Pointers/RocketLeague.json

`GameEvent_RocketLeague` reads the JSON and then uses the addresses and offsets from it to read everything from memory.
e.g. for team it reads `(((((rocketleague.exe + 23761212) + 64) + 244) + 36) + 1472) + 908` by using the `MemoryReader` (https://github.com/antonpup/Aurora/blob/100b4185866a7679d438b8b57ba61a9de9fac635/Project-Aurora/Project-Aurora/Utils/MemoryReader.cs)

If you have more questions, just ask.
