### ISSUE TITLE
Aurora help

### ISSUE THREAD

**Issue by Printb2** [antonpup/Aurora#678]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x ] Aurora supported device, (Logitech G810)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x ] Other, (Keyboard doesnt change lighting effects when lauching games)

### Expected behavior:
Profile of game should light up the keyboard

### Actual behavior:
LIghtning did not change

### How often does this problem occur?

This problem occurs... (everytime)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Open Aurora
2. Open supported game
3. No lighting changes should happen

### What is the version of Aurora you are experiencing this issue with?

My version is... (0.6.0b)

### Does the previous version of Aurora have this issue?
The previous version, (First time using Aurora), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by diogotr7** [comment]
Do you have that profile enabled?

Checkbox hat says "Enable lightning effects for xxx" under "show profile overview/options"

**Comment by Dagda52** [comment]
and veryfi if you are not in night mode too

**Comment by simon-wh** [comment]
@Printb2 Could you tell us what games you tried and if you applied the patches to them if applicable? Also, just to verify, are the desktop effects working as expected?

**Comment by simon-wh** [comment]
@Printb2 Any updates?
