### ISSUE TITLE
Corsair Glaive UI support

### ISSUE THREAD

**Issue by DeniSmooth** [antonpup/Aurora#679]
When possible, please place the new Corsair Glaive. Thank you!

**Comment by simon-wh** [comment]
The Corsair Glaive doesn't appear to be supported by the CUE SDK yet, so I don't think there is much I can do about it until it is supported.

**Comment by DeniSmooth** [comment]
I understand. For now I'm using Glaive as "Sabre RGB". Everything works fine, only the side leds are not recognized, because they do not exist on the Sabre xD

**Comment by simon-wh** [comment]
Well, if that is the case then the SDK does support that mouse, it just isn't listed anywhere. I'll try and get a proper layout for it when I end up trying to add proper layouts for all supported devices.

**Comment by DeniSmooth** [comment]
Thanks!!!

**Comment by noisyboi** [comment]
Il would ove to see this get added as I recieved a Glaive today :) if th ere is anything I can do to help just ask ;)

**Comment by DeniSmooth** [comment]
I see that now I accept the Glaive device, but no effect on Overwatch still does not work as side lights with the integration of the game and I realized that if I put a rainbow effect, also do not work the side LEDs of the Glaive. In the sector where they show the options of mice, like G900, Katar, M65, not yet the Glaive. Am I doing something wrong?

**Comment by noisyboi** [comment]
NBo, you have  not done anything wrong. Glaive has not yet been added

**Comment by darosultan** [comment]
I've patched CUE.NET to send raw USB packets instead of using Corsair's SDK dll (since it's bugged for Glaive atm) and it works with Aurora. Available in my repo. Just clone, build and place CUE.NET.dll and HidSharp.dll in Aurora's folder. Use Sabre layout in the app.

**Comment by Gurjot95** [comment]
Glaive should be supported properly with Side LED using official SDK in the latest PR #1331

There is no dedicated layout for Glaive yet but you can use Corsair Sabre layout in the meanwhile, Scroll wheel LED can be used as Glaive Side LED in layout. This issue can be closed now.
