### ISSUE TITLE
GPU Temperature/Usage Displayed on the keyboard

### ISSUE THREAD

**Issue by M05T3RT** [antonpup/Aurora#68]
Hi antonpup, great work. Got my Logitech G910 this week and was very disappointed until I got Aurora to use my backlighting to it's full potential. I would like to suggest adding GPU indicators on the keys, similar to the CPU and RAM usage. It is not a necessity, but would be really nice to have. Temperature would probably be the most used variable to monitor on a GPU.

Logitech should definitely learn a few things from you in term of backlighting control.

**Comment by antonpup** [comment]
Will see what I can do.

- CPU Temperature
- GPU Temperature
- Mobo Temperature (not sure if useful at all?)
- GPU Usage

**Comment by M05T3RT** [comment]
Awesome, those would all be great. I'm sure someone out there might use motherboard temperature.
Thanks

**Comment by Pandry** [comment]
Maybe the MoBo would not be so useful...

**Comment by brainbug89** [comment]
I use OpenHardwareMonitor to monitor my temps (CPU, GPU, MoBo). Maybe you can use WMI to get the values. So you don't need to add support for every MoBo etc. yourself. :wink:

**Comment by VoronFX** [comment]
Checkout my scripts. There are some features you are asking for, and even more.
https://github.com/VoronFX/Aurora

**Comment by VoronFX** [comment]
Also I am currently working on providing access to all this info from Aurora itself.
In my opinion temp, memory info and a lot of other things are almost useless cause they are auto controlled. What is useful is cpu usage, gpu usage, network connection. 
But anyway I will add as much as I can.

**Comment by brainbug89** [comment]
> Checkout my scripts. There are some features you are asking for, and even more.

Looks nice! :+1: 

I would like to see OpenHardwareMonitor (with [WMI](http://openhardwaremonitor.org/wordpress/wp-content/uploads/2011/04/OpenHardwareMonitor-WMI.pdf)) support for the Percent Effect Layer. So we can display all values (like temps, memory, fan speed, used HDD space etc.) which OHW providing, on the keyboard.

**Comment by VoronFX** [comment]
Work in progress. Need some time.

**Comment by DogeAmazed** [comment]
If we want to get support without using OpenHardwareMonitor w/ WMI, we need to create an wrapper for NVAPI and also for other GPU vendors.
Here's an wrapper for NVAPI: https://github.com/falahati/NvAPIWrapper

**Comment by VoronFX** [comment]
@DogeAmazed It's not a problem. I've already extracted such wrapper from OpenHardwareMonitor and using it my scripts. The problem is to integrate it into Aurora itself. Even this is not a problem, it's just a task that needs time and wish to be done. Currently I am too busy to work on it, but I believe I will do it sometime, but not now.
