### ISSUE TITLE
Payday 2 not working

### ISSUE THREAD

**Issue by Gtasian** [antonpup/Aurora#681]
### What are you experiencing an issue with?

- [ ] Aurora
- [X ] Aurora supported game, (Payday 2)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [X ] Other, (Game is recognized but ingame actions are not)

### Expected behavior:
Lights should reflect in game data

### Actual behavior:
Game is recognized but nothing is reflected

### How often does this problem occur?

This problem occurs... (Every time)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. start payday 2
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (beta v0.6.0b)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.
This is my first version.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
Did you install BLT and PD2 GSI mod?

**Comment by Gtasian** [comment]
Yes, both are installed. The GSI mod is turned on in BLT and the "Preview" for pd2 seems to work in Aurora as well. Aurora recognizes the game being started and will light up in the pd2 config but doesn't reflect any in game activity.

**Comment by simon-wh** [comment]
@Gtasian Can you post the log file from BLT when you have both Aurora running and GSI installed?

**Comment by Kisco** [comment]
Just to add more info: I was messing around with it and the only think that worked was health and ammo (but i was only using the given preview messing around with sliders.)

**Comment by Gtasian** [comment]
https://pastebin.com/UKPCqmg0

I tried two setups; the first with mods I normally play with and the latest setting with just BLT and GSI checked in lua mods option.

**Comment by simon-wh** [comment]
@Gtasian GSI requires BeardLib to function. From your log it shows that you have BeardLib disabled which results in GSI erroring out.

**Comment by simon-wh** [comment]
@Gtasian Yeah, I have made those changes in the dev branch so it is clear that BeardLib is required.
