### ISSUE TITLE
No longer working on Logitech g910

### ISSUE THREAD

**Issue by otterm0use** [antonpup/Aurora#69]
I can no long change the colour of, or interact with any of the keys.  I recently installed Samsung Magician, I had to restart, afterwards I can no longer able to interact with any of my keys in Aurora.

I tried uninstalling Samsung Magician, then I also uninstalled Aurora and Logitech Gaming Software,  I then reinstalled in this order: Logitech Gaming Software > Samsung Magician > Aurora. Unfortunately this did not work.  I then tried a system restore to see if installed a windows update or something affected it also. which also did not work.  

Any help you could give me would be great.  

For the record, I can still change LEDs and adjust colours in the Logitech Gaming Software.

![aurora example](https://cloud.githubusercontent.com/assets/20467185/16859835/404421d2-4a00-11e6-9264-8a09f7db89d7.jpg) This is what the program looks like when I start windows now.

**Comment by antonpup** [comment]
Post your most recent log? This is rather odd.

**Comment by otterm0use** [comment]
Here's my most recent log:

**Comment by antonpup** [comment]
You didn't attach one.

**Comment by otterm0use** [comment]
That's strange, I'll attach it again.

**Comment by antonpup** [comment]
Do it through the site.

**Comment by otterm0use** [comment]
https://docs.google.com/spreadsheets/d/115qloDrX3GXZSxQrYE6d1lXyT89KPc2Wo6IgCwq0tYw/edit?usp=sharing

**Comment by otterm0use** [comment]
oh sure. I just made a google slide but ok.

**Comment by otterm0use** [comment]
[2016_14_07.txt](https://github.com/antonpup/Aurora/files/364974/2016_14_07.txt)

**Comment by otterm0use** [comment]
There you go.

**Comment by antonpup** [comment]
After googling around, it appears issue is Samsung Magician's Rapid Mode. Turn it off, it seems to lose data while caching.

**Comment by otterm0use** [comment]
Unfortunately I never had RAPID Mode enabled.  I did set the "OS Optimization" to Maximum Performance.  I played around a little, trying the different settings to see if anything works, which it has not.

**Comment by antonpup** [comment]
Well, this is a very peculiar issue. I honestly do not know why this is happening. It should've crashed, but it did not. Do keyboard lights still work? You should just not be able to assign keys.

**Comment by antonpup** [comment]
I know this is too late, but I believe another user had the same issue. Aurora has an option to set global brightness with ALT + VOL UP/DOWN. I believe you have set global brightness all the way down, which produced you the issues you had. Once again, my apologies for a late solution. You might not even be using Aurora anymore. xD
