### ISSUE TITLE
Away effects not working anymore on dev2 preview?

### ISSUE THREAD

**Issue by twalts** [antonpup/Aurora#691]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [X] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [X] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
After a set amount of time (in my case one minute) the keyboard and mouse should begin performing the animation of my choice.

### Actual behavior:
No matter how long I wait, the keyboard continues to perform its default lighting effects.

### How often does this problem occur?

This problem occurs... everytime.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Set the away effect delay to any timeframe.
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... 0.6.0-dev2

### Does the previous version of Aurora have this issue?
The previous version did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
The away effects have been fixed in the development branch and will be included in the next release (either development or stable 0.6.1)
