### ISSUE TITLE
Support for the Logitech G Pro Mouse (Overwatch)

### ISSUE THREAD

**Issue by remnantOW** [antonpup/Aurora#696]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x ] Aurora supported device, (Logitech G Pro)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x ] Other, (I would like for this mouse to be added to Aurora)

### Expected behavior:
Explain here what should happen.
I would love for you to add the Logitech G Pro to Aurora, specifically with an overwatch profile
### Actual behavior:
Explain here what happened instead.

### How often does this problem occur?

This problem occurs... (Fill in here)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. 
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (Fill in here)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
I don't see that device listed in the Logitech LED SDK documentation so I think it might not be supported by it. In which case, there isn't much I can do to support it. If it is actually supported by the sdk you should be able to select a similar device in the options and the lighting should apply to your mouse if you set it.
