### ISSUE TITLE
No support for K95 RGB Platinum

### ISSUE THREAD

**Issue by SqugSCX** [antonpup/Aurora#697]
The program doesen't have support for a k95 rgb platinum keyboard, I managed to get the G1-G6 keys working by using the freestyle tool and selecting every one of the G1-G18 keys on the on-screen layout. But I can't get the top bar of the RGB Platinum to work, which would be very nice to be a health bar in CS:GO. I hope you can add support for the Corsair K95 RGB Platinum! Thanks!

**Comment by simon-wh** [comment]
Duplicate of #445
