### ISSUE TITLE
g910 keyboard goes dark after starting

### ISSUE THREAD

**Issue by mhakans** [antonpup/Aurora#698]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
should show effects
### Actual behavior:
Explain here what happened instead.
keyboard goes dark after starting the application
### How often does this problem occur?

This problem occurs... (everytime)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. just starting the application
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (v0.6.0b)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
Does the keyboard preview show lighting that isn't displayed on your keyboard?

**Comment by mhakans** [comment]
yes but its not like its used to be. it looks very dim on the preview but nothing on keyboard

**Comment by simon-wh** [comment]
Could you check the keyboard brightness in settings?

**Comment by mhakans** [comment]
ok that was the problem. but i dont ever remember changing it. its weird. thanks for the help

**Comment by simon-wh** [comment]
You might have accidentally changed it using Alt+Volume.
