### ISSUE TITLE
Logitech wrapper does nothing in the 0.6.1-dev2

### ISSUE THREAD

**Issue by AKBoy14** [antonpup/Aurora#699]
like the title says, the Logitech wrapper does nothing for me, I click the patch button, and the loading wheel on the side of the arrow appears like if it was doing something, but then nothing happen, no message saying that it's patch, or that it failed, and when i check the Logitech folder, nothing happen with the LogitechLed.dll files,

**Comment by simon-wh** [comment]
I fixed this earlier in the dev branch. The fix will be available in the next dev release or 0.6.1

**Comment by AKBoy14** [comment]
ok, thanks :)
