### ISSUE TITLE
Missing regional keyboard keys in Overwatch

### ISSUE THREAD

**Issue by LukasACH** [antonpup/Aurora#7]
In Overwatch, some regional keys miss the lighting effect. For example in this swiss layout, which should be the same as german one, the red marked keys stay black. In the rest of the application, they work perfectly.
![kblayout](https://cloud.githubusercontent.com/assets/16141905/15838076/86ffc004-2c3c-11e6-908c-8c2312a80799.PNG)

**Comment by antonpup** [comment]
The problem with Overwatch support is that it uses a Razer Wrapper to retrieve the lighting info. If Razer doesn't support lighting for those keys, then I cannot get colors for those keys. I will see if they actually support those keys, but I don't think so.

**Comment by antonpup** [comment]
This issue should be resolved in the next update.
