### ISSUE TITLE
Worked for a long time - stopped - now errors during reinstall

### ISSUE THREAD

**Issue by Jangalang** [antonpup/Aurora#703]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
The installer should install the program and it should function normally

### Actual behavior:
Explain here what happened instead.
The Microsoft Visual software will not install over/ignore the versions already installed so that also fails (even though it's worked fine for months up until 2 days ago & once the installation completes the error message occurs
![capture234](https://user-images.githubusercontent.com/30613050/28808041-d96cac74-763e-11e7-85af-179ab63cfde3.PNG)

### How often does this problem occur?

This problem occurs... (Every time)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Attempting install 
2. Failing install
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (0.6.0b and above)

### Does the previous version of Aurora have this issue?
The previous version, (0.6.0), did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by Jangalang** [comment]
Well now the Visual Studio installed, but Aurora still crashes. Attempting another restart.

**Comment by simon-wh** [comment]
Delete %appdata%/Aurora/Config.json
