### ISSUE TITLE
Support for the Razer Chroma Mug?

### ISSUE THREAD

**Issue by gyroknight** [antonpup/Aurora#704]
Hey guys, awesome app you've got here. Any chance support for the Razer Chroma Mug Holder will be added? The mug holder seems to get stuck on whatever effect was active in Synapse before Aurora's launch (in my case, clockwise wave) and doesn't respond to whether the mug is in the holder or not, which normally occurs based on whether the base plate is pressed or not. Unplugging and replugging in the holder causes it to revert to its default powered state, spectrum cycling. The holder does have Chroma support, so it should be accessible via the SDK. I'm on beta 0.6.1-dev2.

**Comment by Gurjot95** [comment]
Fixed with Chroma Link update.
