### ISSUE TITLE
How do I uninstall Aurora???? I need help asap!

### ISSUE THREAD

**Issue by MobsterDolphin** [antonpup/Aurora#709]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.

### Actual behavior:
Explain here what happened instead.

### How often does this problem occur?

This problem occurs... (Fill in here)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. 
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (Fill in here)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by Kisco** [comment]
why its the best program ever, give a reason and then I will help you.

**Comment by MobsterDolphin** [comment]
reason 1: it crashes BF1
reason 2: I got a razor keyboard so I no longer need it
reason 3: I dont want it

**Comment by Kisco** [comment]
alright so there is two versions depending on how long you have had it. Im going to start off with the first one and guess you have the same one. Head over to "C:\Program Files\Aurora" or the location that you installed it and scroll all the way down to the bottom for "unins000.exe" then follow the steps given.

**Comment by simon-wh** [comment]
@MobsterDolphin You shouldn't need to actually uninstall it as long as it isn't actually running, which you can stop by disabling the start with windows option in Aurora. If you really want to uninstall it delete the folder C:\Program Files\Aurora if you installed it through the web installer or whatever folder you installed it into.
