### ISSUE TITLE
Add a mouse? - G502 (with images made)

### ISSUE THREAD

**Issue by Kisco** [antonpup/Aurora#710]
I made this mouse image which is the g502, Link to the image is here - http://imgur.com/a/Va354

Note: If you would want anything fixed up just ask. No feelings if you already made one I just made this in my free time.

Edit: Updated link

**Comment by Kisco** [comment]
@simon-wh Forgot to add the DPI lights! Will fix up tomorrow (3 am right now)

**Comment by simon-wh** [comment]
@Kisco Okay, thanks.

**Comment by Kisco** [comment]
Updated! @simon-wh - http://imgur.com/a/Va354

**Comment by Kisco** [comment]
Fixed some edges, added dpi lighting and also corrected the outside color to be darker the the lines inside.

**Comment by simon-wh** [comment]
Do you have photoshop files for them?

**Comment by Kisco** [comment]
paint.net lol :V

**Comment by Kisco** [comment]
i could transfer the layers to photoshop if you would like

**Comment by simon-wh** [comment]
I've got paint.net installed, so you can throw over the paint.net files and I'll work with them

**Comment by Kisco** [comment]
alright - https://mega.nz/#!iYYBVSIB!zE8Py0X2hYzogi-uMYjqCk_VjJuS4U5wx8enioIbZRw (with images and layers)

**Comment by TomSputz** [comment]
Just curious - any progress with this?

**Comment by simon-wh** [comment]
@TomSputz I haven't had time to get around to putting this in yet.

**Comment by TomSputz** [comment]
@simon-wh Of course :) It's gotta be a lot of work put into this

I've just recently got the mouse, and have found out it actually has 2 lighting zones that aren't ordinarily controllable. I don't know if you have access to them through the logitech SDK, but a heads up

**Comment by diogotr7** [comment]
@TomSputz the dpi lights are always the same color as the main G logo. To light them all up you have to create 2 dpi profiles lower than you currently use the mouse ( as long as you don't actually use the sniper button, of course)

**Comment by TomSputz** [comment]
@diogotr7 Yes - that was the point I was making - you *can* actually control those individually - https://www.reddit.com/r/G502MasterRace/comments/6t0is6/how_to_overwrite_the_internal_g502_memory_with/ - Though I'm not sure the SDK can control that (I have tried to separate them, it works)

**Comment by TomSputz** [comment]
@Kisco How did you make the pictures by the way? They're really nice

**Comment by TomSputz** [comment]
Okay I got into contact with the guys developing the SDK, and sadly you cannot control the lighting individually as of right now. Nevermind

**Comment by Kisco** [comment]
@TomSputz late reply but on the download it shows the mouse image i used as a reference then just took the time to outline it. Simple but time consuming :P

**Comment by simon-wh** [comment]
Added with PR #1146
