### ISSUE TITLE
suggestion: controls for media / caps lock, num lock, scroll lock g810

### ISSUE THREAD

**Issue by mr22fabulous** [antonpup/Aurora#711]
The addition of customisable lighting options for the media control lights and lock key lights on the logitech g810 would be a great addition to aurora, allowing lighting profiles to be spread across the whole keyboard.

**Comment by diogotr7** [comment]
I don't think the logitech sdk allows for that :/

**Comment by simon-wh** [comment]
As far as I'm aware and as @diogotr7 mentioned it isn't possible to control those lights through he SDK. Sorry.

**Comment by mr22fabulous** [comment]
Ah ok, I wouldn't know that myself since I'm not experienced with that kind
of stuff. Thanks for the reply though :)

**Comment by argente69** [comment]
ah, ok tnx, I didn't know that
