### ISSUE TITLE
How do you import external modules for use in a Python script?

### ISSUE THREAD

**Issue by GreenTurtwig** [antonpup/Aurora#712]
Never used IronPython before and so a bit stuck with importing an external module for use in a Python script. Done a lot of Googling, but no luck so far.
Any help would be appreciated. 🐈

**Comment by simon-wh** [comment]
This isn't exactly an issue with the project. I assume you're asking about external python modules, in which case you should probably ask over at the IronPython side of things. It seems like a common enough kind of question though so you should be able to find an answer.

**Comment by GreenTurtwig** [comment]
I've scoured through quite a few searches to no avail unfortunately. Which is what initially lead me to submit an issue in the first place.
I'll have another search session tommorow and if I have any luck, post the results here for anybody with the same issue.

**Comment by GreenTurtwig** [comment]
Right, once again did a lot of searching and nothing I've tried has worked, once again. At this point I'm ready to give up with the script (and Aurora) and figure something else out, hopefully it'll actually work out. :-/

**Comment by GreenTurtwig** [comment]
Ended up scrapping IronPython and just made the script in C#, everything works perfectly fine now. 👍
