### ISSUE TITLE
Cooler Master Masterkeys Pro L stops working with Aurora when preferred mouse is selected.

### ISSUE THREAD

**Issue by hsnabn** [antonpup/Aurora#713]
### What are you experiencing an issue with?

- [x] Aurora
- [x] Aurora supported device, Cooler Master Masterkeys Pro L and Logitech G Pro (I know, not officially supported, but it worked fine on previous version)

### What kind of an issue is it?

- [x] Visual bug
- [x] Aurora Lighting issue

### Expected behavior:
Masterkeys Pro L working as usual alongside Logitech G Pro mouse.

### Actual behavior:
After starting the application and selecting the keyboard, then selecting the mouse, the LEDs on the keyboard freeze. This is not solved with a restart of the device service or application; only by setting preferred mouse to 'None'.

### How often does this problem occur?

This problem occurs every time the steps are reproduced.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Fresh install of Aurora v0.6.1-dev2 (delete configs).
2. Open Aurora.
3. Settings --> Devices & Wrappers
4. Preferred Keyboard --> Masterkeys Pro L
5. Preferred Mouse --> (Any mouse)

### What is the version of Aurora you are experiencing this issue with?

My version is v0.6.1-dev2.

### Does the previous version of Aurora have this issue?
The previous version, v0.6.0b, did not have this issue. (Not very helpful, I know)

### Please include any logs, screenshots, or files that are related to this issue:

Log file: [Pastebin](https://pastebin.com/yTEkWZtw)

**Comment by simon-wh** [comment]
The issue has been fixed and will be included in the next dev release.
