### ISSUE TITLE
Only let Aurora run while playing games (Suggestion)

### ISSUE THREAD

**Issue by Running-Banana** [antonpup/Aurora#714]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [x] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.

I would like to use my default Corsair keyboard profiles from CUE but whenever I launch a game like CS:GO I would like it to switch over to Aurora.

**Comment by simon-wh** [comment]
This is possible if you disable the desktop profile (and have the option enabled in settings if you're using the latest dev release.)

**Comment by Running-Banana** [comment]
Whenever I try to launch the latest dev release I get a error that GameStateListener couldn't start.

**Comment by simon-wh** [comment]
You don't need to use the Dev release to use the feature. It is only that if you're using the Dev release that the option must be enabled for it to work on the Dev release. Could you open another issue for the error you are receiving.
