### ISSUE TITLE
League of legends Lightning not working

### ISSUE THREAD

**Issue by thu2468** [antonpup/Aurora#715]
### What are you experiencing an issue with?

- [x] Aurora
- [x] Aurora supported game, (Fill in the game)
- [x] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [x] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Lightning for league of legends
### Actual behavior:
no lightning

### How often does this problem occur?
All the Time

### Please describe the steps to reproduce this issue:
Click Patch League of legends
Launch Game, Go into Game

### What is the version of Aurora you are experiencing this issue with?
beta v0.6.0-dev2

### Does the previous version of Aurora have this issue?
Didnt try with previus

### Please include any logs, screenshots, or files that are related to this issue:

https://surl.im/i/e77vs.jpg

**Comment by simon-wh** [comment]
Can you try using the latest pre-release as there were some issues with games such as LoL before the latest version? The image you linked doesn't mean anything as there isn't supposed to be any lighting displayed in the LoL preview because we don't know what the lighting information from the game is at that point.

**Comment by thu2468** [comment]
So you want me to try running league with Aurora v0.6.1-dev2?

**Comment by simon-wh** [comment]
Yes

**Comment by G3rtz** [comment]
i have the same problem, with the dev2 version.

**Comment by simon-wh** [comment]
@thu2468 @G3rtz Could you try the suggestion I made in #728 if it applies to you as well?

**Comment by G3rtz** [comment]
Well, my Problem was the config file. After adding the lightfx parameter it works. :) Thanks for your attention. :)
