### ISSUE TITLE
Script's variables of int type not properly deserialized

### ISSUE THREAD

**Issue by VoronFX** [antonpup/Aurora#716]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [x] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, (Fill in another type of issue here)

Script's variables of int type, stored in VariableRegistry, are not properly deserialized and resets to default. 
This is caused by failing type check here https://github.com/antonpup/Aurora/blob/dev/Project-Aurora/Project-Aurora/Settings/VariableRegistry.cs#L57
```CSharp
if (this.Value == null || variableRegistryItem.Default.GetType() != this.Value.GetType())
     this.Value = variableRegistryItem.Default;
```
Deserialized values has type long instead of int. Workaround is simply to use long values.
Bug is insignificant and has an easy workaround (use long instead of int). 
I am creating this just to make a remind that it exists.

**Comment by simon-wh** [comment]
The issue has been sorted, thanks for letting me know!
