### ISSUE TITLE
Option to enable Diablo 3/Homefront for corsair devices when aurora desktop is enabled

### ISSUE THREAD

**Issue by Dagda52** [antonpup/Aurora#717]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [x] Aurora Profile
- [x] Aurora supported device, (Strafe. 65, K70, K95)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [x] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

Just a suggestion, when Enable Aurora to provide desktop effects [x] is ticked, well aurora RGB takes all the keyboard lighting effects to itself, and some native games that uses corsair sdk dlls dont work, because aurora takes priority, and games like the mentioned in the title dont lit up the keyboard with they own effects anymore until ticking off  [ ] that aurora provided desktop effects.

**Comment by simon-wh** [comment]
You can achieve this through using the excluded processes option, I'm not sure if the public release has it working in the same way. But the dev branch has it so that it will act in the same way as disabling desktop except when one of the added processes is in the foreground.

**Comment by Dagda52** [comment]
oh ok thanks

**Comment by Dagda52** [comment]
Wait Wait, i think this isn`t working either look at this pictures with diable 3 in background http://imgur.com/xUkm0J9, i don`t know if i did it right, but these are my steps.

1. Add Diablo III64.exe process in Excluded processes
2. Open Diablo III Game
3, Aurora Desktop Effects Still persists
4. Exit diablo, Close aurora
4. Open aurora again, Add Aurora process to see if this work.
5. Open DIablo 3, and aurora desktop still persists
6. Added more Diablo 3 processes, 
7. Open diablo 3
8. Aurora process still persists.
9. Change application detection metod to foreground app scan
10. nope

this happens in all aurora versions

The only way to see corsair sdk games to work is to disable desktop on aurora or enable the option added in aurora dev 2 after disabling desktop here too.

Here is a picture with diablo 3 in background while aurora dektop mode is off

http://imgur.com/a/Mg9sw
