### ISSUE TITLE
Excluding Processess not working as intended

### ISSUE THREAD

**Issue by Dagda52** [antonpup/Aurora#719]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [x] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
When adding a process exe like a game, aurora should turn off when that process is running in foreground.

### Actual behavior:
Aurora is still persistent and active even when the process is added in the excluded proccess tab

### How often does this problem occur?

This problem occurs... (Every time)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:
as suggested here https://github.com/antonpup/Aurora/issues/717 i tried adding the desired process for aurora to ignore and shut down when the process is on foreground in the case of diablo 3

1. Add Diablo III64.exe process in Excluded processes
2. Open Diablo III Game
3. Aurora Desktop Effects Still persists
4. Exit diablo, Close aurora
5. Open aurora again, Add Aurora process to see if this work.
6. Open DIablo 3, and aurora desktop still persists
7. Added more Diablo 3 processes, 
8. Open diablo 3
9. Aurora Desktop effects still persists.
10. Change application detection metod to foreground app scan
11. Still persistent
12. Tried all above after restarting PC
13. Tried the same with any other app.

### What is the version of Aurora you are experiencing this issue with?

My version is... (0.6.0b and above)

### Does the previous version of Aurora have this issue?
Dont know not tested

### Please include any logs, screenshots, or files that are related to this issue:

Diablo 3 added in exlusion processes and runing in foreground/ background
 http://imgur.com/xUkm0J9

how should look
http://imgur.com/a/Mg9sw

Tested with other apps too, aurora still active when those are added in exluded processes tab.

The only work aroud is diabling aurora desktop profiles, but if you want aurora effects like performance counters and other scripts there is no way to exclude an app for being excluded for now.

**Comment by simon-wh** [comment]
As I said in #717 I wasn't aware if the public version worked in the same way. But the dev branch definitely has it working as I mentioned in that issue.

**Comment by Dagda52** [comment]
@simon-wh I mentioned in the versions of aurora im experiencing the issue is 0.6.0b and above, meaning i tested dev branchs too and they are not working either.

**Comment by simon-wh** [comment]
There hasn't been a Dev release that contains the changes for it yet.

**Comment by Dagda52** [comment]
@simon-wh I'm a little confused, You mean as an internal dev branch that hasn't released yet?, because when you said "But the dev branch definitely has it working" i really thought as in 0.6.1 dev1 and 2 at first, so in that case my apologies, since i was testing that feature too in 0.6.1 dev1 and 2 with other apps and games looks like this http://imgur.com/a/hTlXo, in the case of MEA, it should look like this http://imgur.com/a/e0Dp0 with excluded apps and aurora deskop lighting on.

But in any case thanks for your time.

**Comment by simon-wh** [comment]
When I refer to the dev branch I'm talking about the dev branch I'm talking about [this](https://github.com/antonpup/Aurora/tree/dev), the actual code changes that if you want to use them you must build it yourself until a release has been made from the branch. As you can see on the [releases page](https://github.com/antonpup/Aurora/releases) there have been commits to the dev branch since the last dev release which includes the change I'm referring to. If a change has been included in a release I'll mention  
 that, but if I just say it is in the dev branch then at that point in time it has not been included in a release. Sorry If I confused you, I'm going to make a release once I do #445 and #482 / #549

**Comment by Dagda52** [comment]
@simon-wh oh im gonna try those then, thanks for the link, and thanks for all the fast answers :)

**Comment by simon-wh** [comment]
@Dagda52 When I was talking about the release and the commits since it. The changes are in a commit that is after that release, the change isn't in that version.
