### ISSUE TITLE
Additional Game Support: PLAYERUNKNOWN'S BATTLEGROUNDS

### ISSUE THREAD

**Issue by TwentyFour-24** [antonpup/Aurora#722]
### What are you experiencing an issue with?

- [x] Aurora supported game, (PLAYERUNKNOWN'S BATTLEGROUNDS)

### What kind of an issue is it?

- [x] Enhancement suggestion

Hello there,
are there any plans, or moreover is there any chance to get Aurora working with PLAYERUNKNOWN'S BATTLEGROUNDS (PUBG) in the future?

**Comment by simon-wh** [comment]
Duplicate of #555
