### ISSUE TITLE
Debugger timed out issue while debugging Aurora

### ISSUE THREAD

**Issue by VoronFX** [antonpup/Aurora#727]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [x] Other, (Debugging Aurora)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, (Debugger bug)

Have you experienced "debugger timed out" on starting Aurora from studio? It hangs immediately after start, then message with "debugging operation taking longer that it should" appears and finally error dialog "Evaluating the function timed out and needed to be aborted in an unsafe way.".

I've recently began to experience this issue. Firstly it was happening sometimes and now, after reboot and some windows updates, it reached 100% chance of happening so I was unable to continue debug something and begin to search for an origin of cause. 

The problem is a bit complex and caused by that Main method of aurora calls to ```System.Diagnostics.Debug``` (in Logger) in parallel thread while initializing the app by ```var WinApp = new System.Windows.Application();``` in main thread.

Is more like the problem of VS debugger than Aurora's architecture, so I've reported it to Microsoft. But nevertheless to continue working I had to resolve it. So If you are also experiencing it or will start experiencing it you will already know by what it caused. 

Here is example of clear new project that causes this issue to appear.
```CSharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DebuggerTimeoutBugTest
{
	class Program
	{
		static Task Task = Task.Run(() =>
		{
			System.Diagnostics.Debug.WriteLine("");
		});

		static void Main(string[] args)
		{
			new System.Windows.Application();
		}
	}
}
```

**Comment by simon-wh** [comment]
The issue only appeared after I added the Mutex.WaitOne check to the Main method and when I'm debugging I just comment that out because if it is active I get the issue the entire time.

**Comment by VoronFX** [comment]
I believe the problem is not in mutex. Or maybe mutex also causes it, or just making it worse.
In dev branch I am using now, I can't see any mutex and the problem still exists. The sample project also has no kind of mutex and still causes problem.
Maybe it's just bad idea to do some initialization before/simultaneously with initializing main application.
Why not init everything in main form on load event for example? 
I've solved the problem by commenting System.Diagnostics.Debug.WriteLine in logger for myself. But it took me a nice some hours while I've found the origin and what is going on.

**Comment by simon-wh** [comment]
In my testing, it hasn't even reached the point where it is creating a new instance of the Application by the time the debugger dies. I think the example you've got is another example of the issue and that Mutex could be in the same position as the Application in our case.

**Comment by simon-wh** [comment]
Having moved the instance creation for the Logger class to a method that is called straight after the call of Mutex.WaitOne I've yet to have the issue show again after starting the debugger multiple times. Anytime I got the issue before it always showed a thread at the Debug.WriteLine and the primary at the start of the Program.Main method. I'm pretty confident that our situation is caused by the Mutex but can also be caused by Application.
