### ISSUE TITLE
Overwatch effect whit Logitech mouse and headset

### ISSUE THREAD

**Issue by shikkoku** [antonpup/Aurora#73]
When I play Overwatch my G633 headset and G303 mouse lights will turn off, only G910 keybroad has Overwatch effect. Is that normal?

**Comment by antonpup** [comment]
Yes it's normal, Overwatch profile does not have any mouse effects yet. I will be addressing that later.

**Comment by notthatwillsmith** [comment]
On a G502, the G light on the mouse is on, but the lights that indicate DPI setting never turn on. This isn't ideal.

**Comment by notthatwillsmith** [comment]
It seems like it's only happening in Overwatch though. The normal functionality is that the DPI lights come on when you make an adjustment. That also happens if Aurora is turned off or in other games. But if Aurora is turned on in Overwatch, DPI adjustments don't turn the DPI lights on.

**Comment by antonpup** [comment]
Added mouse effects for Overwatch in version 0.5.0
