### ISSUE TITLE
Test for updated Rocket League pointers

### ISSUE THREAD

**Issue by th3an7** [antonpup/Aurora#730]
Hi everyone
First of all - thank you for this awesome project, it works really well for me now when you introduced support for SteelSeries products.

Anyway, I am writing this because Rocket League pointers were not update for a long time - that's why I've serach the Internet for tutorials how can I do this myself and probably help you with updating them.

I think I've found correct pointers for boost but I need someone with RGB keyboard to confirm, that they are working fine. For me, as I am using only Rival 300 mouse, they are working OK (colors are changing when chose "Boost amount" in Aurora) but I need to be sure that I am finding them as I am supposed to be and probably try to find the rest of them.
The updated pointers can be found in already proposed commit #729 

I've got one question tho - is it possible to make boost layer which changes only brightness and not a colour? For example - if I have full boost (100), backlight is set to MAX brightness and when it's used, it gradually fade out till completely turned off with boost amount of 0. 
Now, with my updated pointers, it's just either max brightness for boost amount of 1-100 and turned off for only 0.

**Comment by simon-wh** [comment]
You can test using the Debug Window in Aurora as it will show you how the lighting will be displayed on the keyboard. If you have multiple monitors you can throw it on another while running Rocket League, or you can put it beside it when running in windowed. For your question, you should be able to use a gradient layer which goes from the colour with 0 alpha to the colour with 255 alpha, or you can have it going from black to the colour so the background colour doesn't come through.

**Comment by th3an7** [comment]
Oh nice, thanks :)

I've found it out how can I test it and it changes as it should. I've also found pointers for respectively teams score which are also working in Aurora and for my mice :)

I don't know how can I find which team I am in tho... any advice? Some initial value like 1 for Orange, 2 for Blue etc.?

**Comment by simon-wh** [comment]
I'm not sure, I've never updated the RL pointers before, I know how to do the boost amount, but I'm not sure how you could find what team you're in. You could try changing teams in a private match and see what values change?

**Comment by th3an7** [comment]
Yeah, that's what I'm doing...
I'll look further - maybe I will find something :)

**Comment by diogotr7** [comment]
Hey @th3an7 I wasn't able to get the boost values to work after updating the pointer and offsets on the rocketleague.json file. When the game is starting up the background color changes briefly to orange but nothing else happens. 

I'm using Aurora 0.6.1-dev2, G810 keyboard and G502 mouse. 

Afaik rocket league hasn't updated since this issue was created.

**Comment by th3an7** [comment]
@diogotr7 Yeah, I know... It sometimes work, sometimes not... I am certainly sure that the boost values are right. The one thing I am not sure is that they could be changing when you're playing online. I've tested them offline in exhibition match and they were working most of the times...

Anyway, I'll post a new values for team scores here, so I would appreciate if you could test them.

**Comment by diogotr7** [comment]
I'm sorry I didn't mention it earlier, but the team scores are working perfectly, at least in competitive doubles. It's the boost I can't get to work.

**Comment by th3an7** [comment]
Are they working for both teams? Sometimes I got troubles for getting blue
team score... The orange was always OK.

Will look on the boost again :P

**Comment by diogotr7** [comment]
The more matches I play, the weirder it gets. One match it worked 100% perfect. The second one it stayed blue pretty much the entire match and changed to fully orange randomly.

**Comment by th3an7** [comment]
That what I was talking about... Will post updated pointers for blue team
and hopefully I'll find correct boost pointers again :P

**Comment by th3an7** [comment]
@diogotr7 can you try these ones? 

https://github.com/th3an7/Aurora/commit/c5cf4977892d7631ba96f1ec5fbe3ec653e89858#diff-776b581251c2e619d7c68bc6dcff2dbb

The thing is, those values are changed everytime you join a new server. They are working when you're playing your first game after game start, but when you find another one - everything gets f***** up...
Temporary solution is to close the game after every match... and that's annoying af.

**Comment by busaku** [comment]
new pointers did not working - i got a blue number pad and the rest is orange ;)
boost did not track too :(

**Comment by diogotr7** [comment]
@th3an7 I wasn't able to get those working at all unfortunately

**Comment by th3an7** [comment]
Hmm... I give up then... You can search for the specific pointers with Cheat Engine :P 
Pointers are changed everytime you start a game, connect to a new server etc. because everything is loaded into memory which cells are always changing.

Only some parts of the game's pointers stays the same (but unfortunately not those we are looking for)

**Comment by busaku** [comment]
U can't give up! I love aurora and i love rocket league.
May can i help? But iam only a python programmer :/

**Comment by LukasACH** [comment]
If anyone ist still interested in finding the correct pointers:
- If you have found the correct Memory Address in Cheat-Engine, select "Pointer scan for this address" and save to disk.
- Then you must do actions that would change the position of the value in memory, like change match, restart the game etc. (in different order multiple times)
- Rescan the memory under "Pointer scanner" -> "Rescan memory" OR find the new address using the normal Cheat Engine Interface.
- Repeat the steps above until you have only few Pointers left, and check if they result in the desired values
