### ISSUE TITLE
(0.6.1 dev2) - Unable to use the original software and Aurora at the same time

### ISSUE THREAD

**Issue by iimma** [antonpup/Aurora#734]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [x] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, (Fill in another type of issue here)

### Expected behavior:
Hi, in the 0.6.0b version, when i uncheck the box "Enable Aurora to provide lighting effects for desktop" in desktop settings, i can use coolermaster's original software aswell as Aurora. Ex:Use cs go configurations but when i return to the desktop i still can use the original software
by the way, my keyboard is masterkeys Pro L

### Actual behavior:
In the 0.6.1 dev2 i cant do this. i have to close one or the other to make it work, and its anoying, i want to use the original features aswell as aurora's features.

### How often does this problem occur?

This problem occurs... (Fill in here)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. uncheck the box "Enable Aurora to provide lighting effects for desktop" in desktop settings
2. try to use original software to control lights in the desktop.
3. you can't

### What is the version of Aurora you are experiencing this issue with?

My version is... (0.6.1dev2)

### Does the previous version of Aurora have this issue?
The previous version, (0.6.0, did not have this issue.)

### Please include any logs, screenshots, or files that are related to this issue:

i havent, i deleted the 0.6.1 dev2 and use only 0.6.0, but this version is not showing light in some keys, in the latest version this is fixed.

Im from argentina, my english is not so good, I apologize for the spelling mistakes I'm sure I have.
Thanks 4 your work, is awesome, lifechanging haha

**Comment by simon-wh** [comment]
In version v0.6.1-dev2 you need to enable the option "Show default lighting(CUE, LGS, etc) when desktop is disabled "

**Comment by iimma** [comment]
Great, thanks, perfect build so.
