### ISSUE TITLE
Did not recognized active application (Third party Game)

### ISSUE THREAD

**Issue by busaku** [antonpup/Aurora#736]
### What are you experiencing an issue with?
- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?
- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, (Fill in another type of issue here)

### Expected behavior:
Aurora should recognized active application or game. but its always in desktop mode

### Actual behavior:
Its always in desktop mode

### How often does this problem occur?
every time

### Please describe the steps to reproduce this issue:
1 add one game (like Playersunknown Battlegounds or Diablo 3)
2 Conficurate some keys in Aurora
3 Start game
4 See, that nothing happend

### What is the version of Aurora you are experiencing this issue with?
6.0 and 6.0 v2
(windows10 64bit)

### Does the previous version of Aurora have this issue?
dont know

### Please include any logs, screenshots, or files that are related to this issue:
Dont know, what did u need. its only dont recognized the front-application. i have tested it with google chrome, and it works fine.. only with this game not..

**Comment by simon-wh** [comment]
Can you post the log file? You can open the folder through the settings in Aurora. Also, what is the full name of the versions you tried? Because there are multiple 6.0's and 6.0 v2's

**Comment by busaku** [comment]
beta v0.6.1-dev2
i have tried to go back to official version, but the wont start after i started the 0.6.1-dev2 one time.

Here is my log:
https://pastebin.com/CxN7RNR6

**Comment by simon-wh** [comment]
To go back you need to delete %appdata%/Aurora/Config.json

**Comment by busaku** [comment]
Now iam back to v0.6.0b - and diablo works fine, thx :)
but Playerunknowns battlegrounds are not recognized :(

**Comment by simon-wh** [comment]
The issue should be sorted through the PR #738, the changes will be included in the next release.

**Comment by busaku** [comment]
Hey, i have the reason why, it dont work:
If i start the game over steam (Shortcut on Desktop) it did not worked.

But if is start the Game.exe directly Aurora leave the Desktop-Mode and switch in my PUBG directly!
- But i cant play without steam (PUBG need Steam :( )

So.. maybe i need a nother "exe"-path or i need other setups for this game?

**Comment by simon-wh** [comment]
@busaku I had it detecting properly when running PUBG as admin through steam fine with the changes I referred to from #738

**Comment by busaku** [comment]
How did u start it over steam as an administrator?
If i say TslGame -> RightClick -> Setup -> Compatibility -> Run as Administrator

It did not detected from aurora and it did not work . Got an error ingame: "Failed to initialize STEAM"

Did u use another method to run it as an admin?

**Comment by simon-wh** [comment]
I set it to run as admin in compatibility and launched it through steam

**Comment by busaku** [comment]
yh... then i got bouth errors.. no aurora, no game :D 
did u use TslGame.exe or TslGame_BE ?

**Comment by simon-wh** [comment]
TslGame.exe

**Comment by busaku** [comment]
yh, everything i try: I got the same error.. No Steam, No Aurora ;)
But in the other thread you say u fix it in the next version. so iam looking forward to it ;)

thanks in advance for your help

**Comment by simon-wh** [comment]
The running as admin was just to demonstrate that the changes in the pr worked, you do not need to run it as admin.

**Comment by busaku** [comment]
ah, okay :)

thank u - and nicework - i love aurora :)
