### ISSUE TITLE
Shortcut Assistant Layer Highlights Numpad Keys

### ISSUE THREAD

**Issue by nichubbard** [antonpup/Aurora#737]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
If you have a shortcut assistant set up for a combination such as CTRL+UP, and you press
the CTRL key, the up arrow is highlighted.

### Actual behavior:
The numpad 8 key (also up) is highlighted. Even when numlock is on. The up arrow is not highlighted.

### How often does this problem occur?

Every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Create a Shortcut Assistant Layer
2. Set up a shortcut such as LControlKey + Up
3. Press Control

### What is the version of Aurora you are experiencing this issue with?

My version is... 0.6.1-dev2

### Does the previous version of Aurora have this issue?
Unsure if this occurred with the older shortcut assistant style

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.
Screenshot: [http://i.imgur.com/IPt7Gpp.png](http://i.imgur.com/IPt7Gpp.png)

**Comment by simon-wh** [comment]
I've sorted it and it will be available in the next release
