### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by slupton89** [antonpup/Aurora#739]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Trying to open Aurora

### How often does this problem occur?
Every time

### What is the version of Aurora you are experiencing this issue with?

6.1 dev2

### Does the previous version of Aurora have this issue?
Worked fine a few days ago, nothing has changed. Downloaded another copy and it still shows the crash.

### Please include any logs, screenshots, or files that are related to this issue:
http://imgur.com/a/EQFl7

**Comment by simon-wh** [comment]
I'm not sure why you're experiencing that issue, I and many people have used v0.6.1-dev2 and haven't had that issue. If anyone knows why this is happening I'd appreciate the help as the mentioned file is an embedded resource.

**Comment by Dagda52** [comment]
I had this issue too but i deleted the aurora folder in users/roaming folder and then it worked, and probably because i had installed razer sdk on top the dlls provided by razer sdk conflicts aurora since they are enabled globally conflicting aurora razer wrapper since all games that uses razer dlls now reads dlls from system32/syswow64 and makes the software thinks there are a razer keyboard, mouse and headset installed and working and installs globally.

**Comment by Dagda52** [comment]
http://developer.razerzone.com/works-with-chroma-v1/download/

**Comment by slupton89** [comment]
Deleting the Aurora folder in Roaming fixed it. I still don't know what caused the crash to happen. I used aurora to get the division to work on my blackwidow and it worked fine, then a couple days later when I tried to play again it started crashing. I never changed any settings in aurora other than selecting my  keyboard and patching the logitech sdk.
