### ISSUE TITLE
No plan support for Roccat RGB or Alienware device ?

### ISSUE THREAD

**Issue by shikkoku** [antonpup/Aurora#74]

**Comment by antonpup** [comment]
As stated in the read me. Support for following devices is planned: SteelSeries, LightFX, LightPack.

**Comment by shikkoku** [comment]
LightFX as same as AilenFX?

**Comment by DanielMckibbin** [comment]
Just noticed this issue after creating a new issue for Roccat support. Have you made any progress at all on LightFX?

**Comment by antonpup** [comment]
I added Roccat Ryos support in a recent commit (see more here #264 ).  Nothing about AlienFX/LightFX.
