### ISSUE TITLE
Layer Preview CS:GO multiple Teams bug

### ISSUE THREAD

**Issue by brainbug89** [antonpup/Aurora#741]
### What are you experiencing an issue with?

- [x] Aurora supported game, (csgo)

### What kind of an issue is it?

- [x] Visual bug

### Expected behavior:
Undefined, CT and T should only be displayed once.

### Actual behavior:
Undefined, CT and T are displayed multiple times.

### How often does this problem occur?

everytime

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. goto CS:GO Settings
2. Show Profile Overview/Options
3. Preview
4. Select Team

### What is the version of Aurora you are experiencing this issue with?

v0.6.1-dev2

### Does the previous version of Aurora have this issue?
unknown

### Please include any logs, screenshots, or files that are related to this issue:

http://imgur.com/XNH8bJF

**Comment by simon-wh** [comment]
Issue has been resolved in the commit above and will be included in the next release
