### ISSUE TITLE
RGB LED strip control?

### ISSUE THREAD

**Issue by Sokonomi** [antonpup/Aurora#743]
I don't know where else to ask this, but I was wondering if there was a way to control RGB LED strips.
Any DIY tutorials out there about how to make something that can be controlled by Aurora?

**Comment by simon-wh** [comment]
Have a look at the pi-lighting branch

**Comment by Sokonomi** [comment]
I don't want to struggle with the pain in the ass that is Raspbian. :')

Atmo-Orb can swing it with just a simple 5 dollar arduino board. I was hoping somebody smart had converted that setup to one that's able to run standard 5050 LED strips by now.

**Comment by simon-wh** [comment]
You don't have to use a pi, you can just use that branch as an example of how to implement control for custom leds
