### ISSUE TITLE
Increased RAM usage over time, causing heavy lag

### ISSUE THREAD

**Issue by TristanSchaaf** [antonpup/Aurora#744]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [x] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
No or not noticeable performance loss or RAM consumption

### Actual behavior:
steadily increasing RAM consumption with about 1 - 3 mb every 10 seconds. Not noticeable until it reaches critical and gives drastic lag spikes every 10-30 seconds especially when input device (keyboard & mouse) used heavily. (for example; shaking the mouse). I've seen Aurora hogging up to 6,6 GB of RAM
In the time writing this, after resetting Aurora, it started with about 70mb of RAM, now uses 130(few minutes)

### How often does this problem occur?

The entire time, steadily increase of RAM usage

### Please describe the steps to reproduce this issue:

1. Open Aurora
2.  Monitor the RAM usage while computer is idle besides that.
3. Marvel at the numbers

### What is the version of Aurora you are experiencing this issue with?
My version is... 0.6.0b

### Does the previous version of Aurora have this issue?
Not tested

### Please include any logs, screenshots, or files that are related to this issue:
No logs directory in Program Files/Aurora

Might be related to issue #740

**Comment by simon-wh** [comment]
I think this issue should be resolved in the dev builds, could you try using the [latest development release](https://github.com/antonpup/Aurora/releases) (you might want to use v0.6.1-dev as dev2 has game integration check). You could also look at the solution mentioned in #387 if the dev release doesn't fix it.

**Comment by TristanSchaaf** [comment]
dev2 seems to work. Haven't tested in-game though.
