### ISSUE TITLE
g810 media keys are not customizable

### ISSUE THREAD

**Issue by zimbosaurus** [antonpup/Aurora#745]
So I might be missing something here but I am unable to change lighting on the round media buttons. It really bugs me when those buttons are a different color than everything else. They're always the color from the last used profile in LGS. is this something that can be added, or is there some technical issue that can't be resolved?

**Comment by diogotr7** [comment]
Thia issue has been answered 4 or 5 times already, try searching :)

Anyways, the sdk doesn't support those keys unfortunately. 
It bugs me too :(

**Comment by zimbosaurus** [comment]
Oh, sorry. I did search but barely anything came up, guess I did it wrong somehow.

Well, that's kinda dumb. You think they'll ever add it?
