### ISSUE TITLE
When i change the version from v.6.0 to v.0.6.0 dev2 gradient effects lose the saved colors

### ISSUE THREAD

**Issue by mmateusu** [antonpup/Aurora#746]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [x] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Should be normal.

### Actual behavior:
Change the colors of the Gradient effects.

### How often does this problem occur?
Everytime i install the v0.6.1 dev2 version.

The issue can be reproduced by doing following steps:

1. Create a profile in the stable version of aurora containing anything with the gradient effect
2. Install the new version
3. Color changes.

### What is the version of Aurora you are experiencing this issue with?
v0.6.1 dev2 version.
### Does the previous version of Aurora have this issue?
The previous version, v0.6.0 did not have this issue.

**Comment by simon-wh** [comment]
What application/profile are you testing it with and what layer are you using? I tried Rocket League with the boost indicator and the gradient carried over and is retained when using the development version.

**Comment by mmateusu** [comment]
i made my desktop profiles and they don't work when im merge to the new version, actually, they work, but only the solid colors still the same, if you are wondering which ones, i posted them here. one exemple :https://modworkshop.net/mydownloads.php?action=view_down&did=20646
in the description i posted a video on youtube on how he must behave, but, when i use the same archive in the "new" version, the layers with gradient effects don't save the previous colors

**Comment by simon-wh** [comment]
I've sorted it and it'll be available in the next release

**Comment by mmateusu** [comment]
When it will be? (sorry for being anxious)

**Comment by simon-wh** [comment]
I'm not sure, hopefully soon.

**Comment by mmateusu** [comment]
Ok sir thanks for the attention <3
