### ISSUE TITLE
Cooler Master Masterkeys Pro L (nordic), Enter-key does not light up

### ISSUE THREAD

**Issue by kaporten** [antonpup/Aurora#747]
**Aurora version:** v0.6.1-dev2
**Keyboard:** Cooler Master Masterkeys Pro L (nordic)
**Keyboard Layout:** Nordic

**Issue:**
The Enter key does not light up, for any layer type. 
The numpad-Enter key does, but the regular Enter key does not.

Exiting Aurora (reverting to CM profiles), the key lights up just fine again, so the LED isn't broken.
All other keys seem to behave as they should.

Testing with same version of Aurora, same PC/Layout, but with the Logitech G910 Orion Spectrum keyboard, the Enter key lights up fine.

So it seems to be an issue either with Cooler Master boards, possibly only CM boards with Nordic layout.

**Comment by simon-wh** [comment]
@kaporten Does your keyboard have the short enter key the same as the US keyboard layouts? If so, the fix should be pretty easy.

**Comment by kaporten** [comment]
Hi - no it has this kind of enter key:
https://www.vortez.net/articles_file/35597_cooler%20master%20masterkeys%20pro%20l%20intro.jpg

**Comment by simon-wh** [comment]
Could you follow this issue comment: https://github.com/antonpup/Aurora/issues/549#issuecomment-323605451 and tell me what co-ords light up your enter key?

**Comment by kaporten** [comment]
Sure, the main enter-key is Row 2, Column 14.
The numpad-enter is Row 4, Column 21 if that's relevant to know.

**Comment by brainbug89** [comment]
> Sure, the main enter-key is Row 2, Column 14.

https://github.com/antonpup/Aurora/blob/34c1886f04dad3e3e38450f22558aecd2261b7cc/Project-Aurora/Project-Aurora/Devices/CoolerMaster/CoolerMasterDevice.cs#L91

Does other layouts have the same problem? I don't have the doc atm to check if the coords are correct.

**Comment by simon-wh** [comment]
@brainbug89 The docs have to coords at 2,14 for international layouts with the large enter key and 3,14 for  US layout. However, this https://github.com/antonpup/Aurora/blob/34c1886f04dad3e3e38450f22558aecd2261b7cc/Project-Aurora/Project-Aurora/Devices/CoolerMaster/CoolerMasterDevice.cs#L422 is supposed to switch it to the backslash key which has 2,14 as its coord. I have no idea why it isn't working properly, similar to the weird situation for the numpad key lighting.

**Comment by ashleymorris2** [comment]
I have this same issue with coolermaster s on UK layout

**Comment by simon-wh** [comment]
Could people with this issue try [v0.6.1-dev4](https://github.com/antonpup/Aurora/releases)?

**Comment by bedbug1226** [comment]
I still have this issue with the v0.6.1-dev4 with the us layout using the Cooler Master Masterkeys Pro L.

**Comment by simon-wh** [comment]
Can anybody still experiencing this issue try the [latest build](https://ci.appveyor.com/project/antonpup/aurora/build/artifacts), I believe this issue has been fixed

**Comment by rsanger** [comment]
Fixed for me using 86a4643a, with Pro L US layout.

Vs. the v0.6.1-dev4 release which mapped 'enter' to '\\' and mapped '\\' to nowhere.
