### ISSUE TITLE
Rocket League update

### ISSUE THREAD

**Issue by penskyc** [antonpup/Aurora#75]
Hello, looks like there was a rocket league update on 7/7. I only seee the blue lights on load and it stays that way every since, no boost or score indicators.

**Comment by antonpup** [comment]
Yes, it's broken. I will be switching to a different system later.

**Comment by jdubnz** [comment]
I noticed this too. Since the update today, it no longer has any lighting effects for R. And yes I have re-enabled it.

**Comment by antonpup** [comment]
I updated pointers today before release. RL profile should work for the mean time.

**Comment by antonpup** [comment]
I found an issue, and I will be pushing an update tomorrow to fix it. Thank you for bringing this to my attention @jdubnz , I should really test my code the day of the release.

**Comment by jdubnz** [comment]
All working properly with for me with 0.5.1a
