### ISSUE TITLE
Corsair M65 Pro no DPI indicator LED lighting

### ISSUE THREAD

**Issue by JmLykins** [antonpup/Aurora#750]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
DPI indicator light should be on

### Actual behavior:
DPI Indicator light is off.

### How often does this problem occur?

This problem occurs... (every time)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Light is always off with aurora, light turns on when the corsair utility has control of device
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (0.6.1-dev2)

### Does the previous version of Aurora have this issue?
The previous version, (0.6.0b), did have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
The DPI Indicator cannot be controlled through the CUE SDK. See https://github.com/DarthAffe/CUE.NET/issues/43
