### ISSUE TITLE
Steelserie's mouse slows keyboard animations (Masterkeys Pro L)

### ISSUE THREAD

**Issue by iimma** [antonpup/Aurora#753]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ x] Performance problems
- [ x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
The keyboard should turn on smoothly the lights
GIF:
`https://gyazo.com/39f179de16185de8ce0678dc688d819f`
### Actual behavior:
Explain here what happened instead.
The keyboard is showing laggy effects
GIF
`https://gyazo.com/9f3feaf912aeccd57395b35d166750e8`

### How often does this problem occur?

This problem occurs... (When i turn on steerseries mouse on the device manager)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Turn on the keyboard on the device manager
2. Then the mouse.
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (v0.6.1 dev3)

### Does the previous version of Aurora have this issue?
The previous version, (v0.6.0), did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by brainbug89** [comment]
I have a Steelseries mouse and it's not lagging for me. Could you try to restart the SSE3 client. Do you have the latest version of SSE3?

**Comment by iimma** [comment]
I tried everything

**Comment by simon-wh** [comment]
I've pushed a commit which should solve the issue where Steelseries being slow slows down your other devices. However, It doesn't solve the fact that Steelseries was being slow in the first place. For that, I think the issue may be related to SSE3 client, but I'm not sure as I haven't been able to consistently replicate it.
