### ISSUE TITLE
Add a keyboard?

### ISSUE THREAD

**Issue by lightwarcraft** [antonpup/Aurora#754]
Just wondering if you could add in the Logitech G213 Keyboard, if not if theres a way for aurora to just find my keyboard and I customize it as a "custom" or "not listed" keyboard. I like the key wave effects in the program but I can't use them because my keyboard isn't listed. Thanks!

**Comment by simon-wh** [comment]
That keyboard doesn't appear to be supported by the Logitech SDK, so there isn't much I can do to support it.
