### ISSUE TITLE
[Request] [Equalizer] Add option to choose audio device to display on keyboard

### ISSUE THREAD

**Issue by diogotr7** [antonpup/Aurora#755]
If we could change the audio device it would be possible for the EQ layer to only display music, for example.

It would allow voicemeeter banana users to isolate certain applications while stil playing all the sound to the user.

**Comment by iimma** [comment]
good idea, for example my keyboard light works only with the audio that my monitor is taking out of my hdmi port. i'm not able to use realtek's devices or any other audio device.

**Comment by diogotr7** [comment]
If anyone is going through old issues, you can achieve this with the newest windows update and Virtual audio cable. Force the default output of aurora to virtual cable, then in windows recording devices, select "Listen to this device". If you want to isolate a single application, like spotify, force the output to the same virtual cable.
