### ISSUE TITLE
Updates Break Desktop Profiles

### ISSUE THREAD

**Issue by userforusing** [antonpup/Aurora#757]
This is 

### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [x] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
This is concerning pre-made desktop profiles that are downloadable from the modworkshop. 
Profile should display as intended.

### Actual behavior:
Explain here what happened instead.
Colours of the profiles are off, inverted or randomised.

### How often does this problem occur?

This problem occurs... (Fill in here)
Seems to happen everytime a new Aurora version is published.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Activate a Profile.
2. Update Aurora.
3. Colours are wrong, switching, reinstalling profiles does not help.

### What is the version of Aurora you are experiencing this issue with?

My version is 0.61 -dev3

### Does the previous version of Aurora have this issue?
The previous versions, **did** have this issue.

### Please include any logs, screenshots, or files that are related to this issue:
Latest Log: https://pastebin.com/zt1b3qSP

I've noticed this behaviour over the last few versions now and was just wondering if this is something normal in regards to updating the software? Do the authors of the profiles have to update them from within the new version of Aurora? Basically, all profiles I have are broken now, some survive an update or two, others don't.

**Comment by simon-wh** [comment]
Can you give me an example of a profile that experiences this issue?

**Comment by userforusing** [comment]
Yes I can. The most recent that I used was this [one](https://modworkshop.net/mydownloads.php?action=view_down&did=20582)

**Comment by stephenej** [comment]
This [profile](https://modworkshop.net/mydownloads.php?action=view_down&did=17402) also no longer works for me with latest dev build (0.61 -dev3). I've reset all preferences and such and the profile no longer applies anything.

**Comment by simon-wh** [comment]
@stephenej That profile you linked was created before the Layer system was implemented and there is no system to carry over the old settings to the layer system

**Comment by simon-wh** [comment]
@userforusing The reason the profile you linked has problems with colours carrying over is because it was created after the change that previously caused problems with gradients that was reversed in v0.6.1-dev3, as far as I can tell it was only the gradients that were affected. I'm fairly certain that the gradient breaking change only appears in dev builds in which case I'm going to leave it as is as the current state of it in dev3 is the same as v0.6.0b. If you want to get gradients to carry over you'll need to open the profile in a text editor and replace instances of "colorGradients" with "color_gradients". I'm going to close this unless there are different cases of stuff not carrying over.

**Comment by userforusing** [comment]
Thank you for investigating this. I do have a follow-up question though.
Looking at the file in notepad there are only "color_gradients" entries. So shouldn't those be the correct values? When I do change them though, Aurora replaces them back again at startup.

**Comment by simon-wh** [comment]
You have to change them before you drop the profile into Aurora. Once a newer version of Aurora has been launched it will have removed the "colorGradients" and added a default "color_gradients". So you'll need to edit the file when you download it.
