### ISSUE TITLE
G Keys not working g910 Spectrum

### ISSUE THREAD

**Issue by AndersAnderson** [antonpup/Aurora#76]
Hello dear Developer,

i got this beautiful Keyboard and your awesome Software today.
After a little konfiguration everything worked fine, except for the g keys.

They are not changing the Color as expected.
Neither in Desktop mode, not in Cs:Go.

Did i forget anything which might be necessary for it to work properly?

Greetz Anders

**Comment by Blizzardfall** [comment]
You can't configure G-keys and logo with any 3rd party software(Like [Artemis](https://github.com/SpoinkyNL/Artemis)). This is normal.
It's Logitech SDK problem, not the software. They've said they will fix the issue, but no news yet.

**Comment by AndersAnderson** [comment]
Ok, thats unfortunate.

Well than that issue can be closed :)

**Comment by antonpup** [comment]
Once Logitech SDK adds support for those keys, I will enable them in Aurora.
