### ISSUE TITLE
Razer not detecting chroma app

### ISSUE THREAD

**Issue by BigMan7o0** [antonpup/Aurora#760]
so i am not sure if this is an issue on your end, or razer synapse, but it will NOT detect aurora as a chroma app, which means i can not have any effects on my keyboard. it worked like a month ago, but then my pc had some issues, and i had to re install windows, and wipe all my previous apps and data. ever since then this will not work for razer products.

**Comment by simon-wh** [comment]
Did you follow the setup instructions for Razer?

**Comment by BigMan7o0** [comment]
yes, i did. i also tried un-installing aurora, and razer synapse. i tried toggling the chroma apps off, then back on, and it didn't work.
and also, since i didn't mention it in my original post, i am running everything as administrator,

and now after trying to re-install aurora again i am getting the following error message (it re-occurs every time i try): http://imgur.com/a/gRPWJ

as for the error i am convinced i am just being dumb and doing something wrong lol.

**Comment by simon-wh** [comment]
For that last issue, you'll need to delete %appdata%/Aurora/Config.json. It's a known issue when going back to v0.6.0b after using a dev release.

**Comment by BigMan7o0** [comment]
ok yeah i figured the error was me doing something wrong lol. 
after re installing it, it still wont show as a chroma app in synapse, and wont allow lighting control over my keyboard or headset.

**Comment by simon-wh** [comment]
Can you have a look at what is shown in the Devices section for Razer? Could you also make sure that the SDK has been enabled and post the log file if you can't get it working?

**Comment by BigMan7o0** [comment]
ok this time a re install of synapse seems to have worked.
i don't know why it worked this time, but not last time. most likely some form of user error, but god only knows with razer synapse lol.

**Comment by simon-wh** [comment]
Okay, I'm glad you got it sorted.
