### ISSUE TITLE
CM Masterkeys Pro L WHITE - will it be supported?

### ISSUE THREAD

**Issue by LePayper** [antonpup/Aurora#761]
Hello!

I am after using the google search tool for around 2 hours trying to understand how do Masterkeys Pro L WHITE is supposed to have customized lighting - well I found only those that are on CM site, and to use them, You have to have compiled .exe on top of everything, because if You minimize it, the "custom" effects are gone  - which makes it not really useful. 

Then I found Aurora - man, that was it - it supports SDK keyboards right? I immediately downloaded package, installed it, I am about to choose my model - YES MASTERKEYS PRO L.... not detected.

So there lies the problem - will be there an support from Aurora developer team for CM Masterkeys Pro L White ? Because if Cooler Master cannot implement their - holy - "create your own custom lightning" feature into product that they say it is implemented, I think someone else should do it.

I may be wrong - maybe I am just not that good at programming and using code to light up each LED to create an effect that will be working like stock ones. But how I am supposed to even start trying?

Can someone please tell me the truth - is White version actually abandoned by CM and there will be no custom lightning ?

**Comment by simon-wh** [comment]
CM Masterkeys Pro L White is supported in the [development builds](https://github.com/antonpup/Aurora/releases)

**Comment by LePayper** [comment]
Thank You very much
