### ISSUE TITLE
D.VA and Zarya Colors change when using HSV (Overwatch)

### ISSUE THREAD

**Issue by mmateusu** [antonpup/Aurora#762]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
The colors should stay Pink as they do when you use the "Linear" color enhancement

### Actual behavior:
They change to a red-ish

### How often does this problem occur?
Everytime you use the HSV enhancement

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Open Aurora
2. Open Overwatch
3. Use HSV color enhancement
4. Choose D.VA or Zarya ingame
### What is the version of Aurora you are experiencing this issue with?

My version is 0.6.1 dev 3

### Does the previous version of Aurora have this issue?
I'm afraid so

**Comment by diogotr7** [comment]
Can confirm this. It's annoying because you can only get reaper and doomfist to even display at all with hsv

**Comment by mmateusu** [comment]
Up

**Comment by LukasACH** [comment]
I will look into this

**Comment by simon-wh** [comment]
Issue fixed through PR #766. Thanks @LukasACH! The fix will be available in the next release
