### ISSUE TITLE
Sound cracks when having Aurora running

### ISSUE THREAD

**Issue by Ulvsonn** [antonpup/Aurora#763]
### What are you experiencing an issue with?

- [X ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [X ] Other, (Sound)

### Expected behavior:
Explain here what should happen.
Sound should not interfere with Aurora.
### Actual behavior:
Explain here what happened instead.
When having Aurora active, any sound coming from any source of my pc starts cracking. It starts after an hour or so and gets worse as time passes. Have to quit aurora or restart to "fix" it.
### How often does this problem occur?

This problem occurs... (Everytime)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Start Aurora
2. Wait an hour or a bit more
3. Sound quality should be deteriorating over time
4. Rage quit Aurora
### What is the version of Aurora you are experiencing this issue with?

My version is... (V0.6.0b)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by DogeAmazed** [comment]
Is it a typo that your version is 0.3.0b? 
If you mean 0.6.0b, try the [newest development build](https://github.com/antonpup/Aurora/releases) and check if the bug exists there.

**Comment by Ulvsonn** [comment]
It was a typo indeed. My bad.
I'll try with that version and update this thread.

**Comment by Ulvsonn** [comment]
Yup. Still having the same issue. I'll work all day tomorrow without opening Aurora and see if the noise is still present.

**Comment by DogeAmazed** [comment]
Well, thats good for Aurora. 
Is your sound device USB? If yes, there might be some interferences with your keyboard. I've got this on my setup (Razer BlackWidow Chroma and G930), when I set the light intensity to maximum and charging my headset.

**Comment by Ulvsonn** [comment]
No, I'm testing with standard 3.5mm sound plug, HD audio from HDMI and Displayport. 

I just updated my USB drivers and haven't experienced the issue. However, if I start aurora, it starts as soon as lighting effects start.
I'm desperate lol.

**Comment by Ulvsonn** [comment]
Update:

Rolled back like 4 or 5 versions of Logitech Gaming Software and the problem stopped. Unfortunately, if I start Aurora, it returns... halp!

**Comment by simon-wh** [comment]
Have you tried on v0.6.2b? There have been a significant number of changes. Closing for now
