### ISSUE TITLE
Aurora process priority

### ISSUE THREAD

**Issue by VoronFX** [antonpup/Aurora#767]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [x] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [x] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

I've noticed that recently (don't know from which version exactly) Aurora started to run with lowered process priority and this is causes visual effects on keyboard to lag under high load.

I considering the keyboard illumination as an GUI and when it lags I feel uncomfortable. It's like when game freezes, everyone hates it but now I have an freezing keyboard also.

As a developer I am a heavy PC user. Running Visual Studio, Aurora, Chrome with tons of tabs opened and a bunch of messengers make my weak CPU to be on high load very often.

My scripts provides a lot of animations, especially on high CPU load so this lags are very noticeable and annoying me. In worst cases I can see illumination hangs for several seconds.

I understand that this probably was made to not steal cycles from games, but if user has a game that is grabbing all his CPU he may be considering ~buying a new one~ setting high priority for the game process.

Of course I've easily workaround this for myself by setting permanent process priority for Aurora, but what I am talking here is the best default behavior. Personally I think Aurora should run with normal priority (or even higher like a media process). As another approach this can be leaved to user choice by providing a corresponding setting. 
What you think about it?

**Comment by simon-wh** [comment]
I feel as though we would want to try and avoid having Aurora set at high priority at all times in case there is a scenario where it could be reducing the performance of the game being played. It depends on a person to person basis so it would probably make sense to ensure that it has at least a normal priority at all times and maybe have an option to make it run at a higher priority.

**Comment by VoronFX** [comment]
Yeah that is probably the best approach. Setting high priority is good in theory, cause I believe GUI should be responsive and fluid, but in reality almost no one GUI uses high priority, sadly even games. So we also shouldn't break this bad tradition to not affect other apps.

**Comment by simon-wh** [comment]
I've added an option to run Aurora at high priority which is disabled by default
