### ISSUE TITLE
Away Effects Suggestion

### ISSUE THREAD

**Issue by argente69** [antonpup/Aurora#768]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [x] Other, (suggestion)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

Hello, I have a suggestion, you guys could add a feature to create or assign current profiles to the away effects, it would be a nice improvement. Thanks

**Comment by brainbug89** [comment]
My idea was to create a new profile like the Desktop mode and name it AFK mode.

Also I want it to cycle or random-select different layers for some random away effects.

**Comment by diogotr7** [comment]
You can now do this per layer with overrides.
