### ISSUE TITLE
Not working with Dvorak

### ISSUE THREAD

**Issue by Arachnophobe** [antonpup/Aurora#770]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
Keypress should line up with actual key.
### Actual behavior:
Explain here what happened instead.
When I press a key, the lighting effect is coming from the Qwerty layout.
### How often does this problem occur?

This problem occurs... (Fill in here)
Constant.
### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Set Keyboard to Dvorak.
2. Set a keypress effect.
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (Fill in here)
The latest.
### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.
Uh, probably.
### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
I've added the dvorak layout, it'll be available in the next release.
