### ISSUE TITLE
Overwatch no longer works

### ISSUE THREAD

**Issue by Dagda52** [antonpup/Aurora#771]
### What are you experiencing an issue with?

- [ ] Aurora
- [x] Aurora supported game, (Overwatch)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, (Overwatch update 1.14.1.2.39425 apparently cannot longer load custom razer dll´s)

### Expected behavior:
When dll´s placed in game folder, overwatch keyboard effect should work on any keyboard

### Actual behavior:
Effects are now razer exclusive again (tested on a blackwidow), 

### How often does this problem occur?

This problem occurs... (Every time)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Check overwatch new update
2. Launch the game
3. The keyboard is black even if the dll´s are there

### What is the version of Aurora you are experiencing this issue with?

My version is... (any version)

### Please include any logs, screenshots, or files that are related to this issue:

https://pastebin.com/z47vFhHA

### Additional info
you´r competitor artemis, still works with overwatch, not as the level of razer default but still reads razer dll´s (default dll´s and your custom dlls)

**Comment by lattedesu** [comment]
Can confirm, doesn't work on my end, too.

**Comment by diogotr7** [comment]
It works for me on Aurora 0.6.0dev3 and the latest August 29 overwatch patch. 

It just worked straight away without any fixes or tweaks.

I have a g810 and a g502

**Comment by lattedesu** [comment]
Same combo, g810 + g502, doesn't work. It' becomes black and stays like that. Re-patching didn't help.

**Comment by diogotr7** [comment]
I just tested it over remote desktop http://i.imgur.com/suP1S2h.jpg .

And yes, it updates when I choose heroes and use abilities.

**Comment by Dagda52** [comment]
nope every other razer chroma games works, except for this game, and its like h1z1 and warframe

**Comment by Dagda52** [comment]
Well it works again, how strange, i was yesterday patching it like a toons of time, i even installed razer chroma sdk and patched dlls so the dll's can be loaded globally guess is something on my end and lattedesu end. IDK

**Comment by Dagda52** [comment]
adding that you need to enter a match now to make the effects works.

So apparently i rushed a little in conclussions, guess still works but differently

**Comment by diogotr7** [comment]
Yeah, I noticed that sometimes the orange that used to appear on the main menu doesn't appear anymore, you actually need to enter a game.

**Comment by simon-wh** [comment]
The main menu colour could be a change in the overwatch update rather than an issue with Aurora. Does anyone know if this is/isn't the case?

**Comment by diogotr7** [comment]
It only started happening when the junkrat changes hit, so August 29th. Afaik Aurora hasn't changed so the issue is probably the overwatch update.

**Comment by simon-wh** [comment]
As far as I can tell Overwatch doesn't create any lighting when it's in the main menu currently, so they must've removed the main menu lighting that has been referred to.

**Comment by lattedesu** [comment]
Can confirm ingame works. Possibly on overwatch's end. Thanks for investigating.

**Comment by Poolitzer** [comment]
Can confirm ingame not working.
