### ISSUE TITLE
Alienware laptop keyboard layout support

### ISSUE THREAD

**Issue by nyan257** [antonpup/Aurora#774]
Is there support for the layout of the alienware laptop keyboard?

**Comment by nyan257** [comment]
Also, where do i install the alien fx plugin hook and the razer chroma hook? sorry

**Comment by simon-wh** [comment]
Alienware laptops are not supported, I'm not sure what you're talking about with "alien fx plugin hook" and "razer chroma hook".

**Comment by simon-wh** [comment]
You can see the list of supported devices in the readme for this project.
