### ISSUE TITLE
Aurora can't connect my corsair Strafe

### ISSUE THREAD

**Issue by LightShaft** [antonpup/Aurora#775]
### What are you experiencing an issue with?

- [X] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [X] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [X] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Should initialize my Corsair Strafe.

### Actual behavior:
Wanted to fix the problem with Overwatch because the profile wasn't working anymore, now my keyboard can't be initialized on Aurora so there's no lights working now (except for the profile I have on CUE2 ofc, latest update btw)

### How often does this problem occur?
Everytime

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1.  Launch Aurora
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?
v0.6.0b but the latest dev release give me the same result

### Does the previous version of Aurora have this issue?
No, maybe an automatic update made the bug, I don't know

### Please include any logs, screenshots, or files that are related to this issue:
https://i.imgur.com/4wpZUX6.png
https://i.imgur.com/04fmkL7.png

**Comment by simon-wh** [comment]
Could you post your log file? The images you've linked don't really provide any helpful information.

**Comment by LightShaft** [comment]
Yes sir, please forgive me for that
[2017_02_09.txt](https://github.com/antonpup/Aurora/files/1272278/2017_02_09.txt)

**Comment by simon-wh** [comment]
From the log it looks like the error you were getting is the same as one that is mentioned [here](https://github.com/DarthAffe/CUE.NET/issues/55) which you can see what is mentioned about it over there. Regarding Overwatch being dark in the menu as far as I can tell it doesn't send any lighting when in the menu initially, so Blizzard must have changed something, you can see the talk about that specifically [here](https://github.com/antonpup/Aurora/issues/771)
