### ISSUE TITLE
Ambilight extreme CPU usage and Main monitor selection broken

### ISSUE THREAD

**Issue by Mikewl** [antonpup/Aurora#778]
So testing the ambilight layer on the current beta (v0.6.1-beta3) I get 30% CPU usage (to be fair, 2x Full HD and 1x 2560x1440 screen) then wanting to limit that to a single screen i.e. my main monitor Then only the f1-f12 keys light up and the area seems to be around the mid lower section of the screen.

Trying to limit it to a single process still uses the same large amount of CPU usage.

**Comment by simon-wh** [comment]
The issue appears to be as a result of how the current system of taking screenshots works as it will always just stitch the monitors you have beside each other in whatever order they are in windows, whereas the region we use to get the right part is determined using the region that windows make to lay everything out which results in a mismatch. From looking at it it'll likely require a switch in screenshot method for both issues (CPU usage and bad regions) which might be a while.

**Comment by lucasvanhalst** [comment]
The performance of ambilight could probably be improved by using the desktop duplication api https://msdn.microsoft.com/en-us/library/windows/desktop/hh404487(v=VS.85).aspx 

I use a program that has ambilight as its main feature (https://github.com/psieg/Lightpack) and desktop duplication performs about 4 times better and it doesn't make the windows lag.

**Comment by ntreik** [comment]
hi sorry for reviving this issue, but still cpu usage too high for ambilight and my i5 6600k.
Anyway looking to upgrade, do you believe im better with more threads or more single core power to run amblight without taking much from new cpu?

**Comment by diogotr7** [comment]
The desktop duplication was recently merged (thanks @lucasvanhalst ) and I decided to make some UI changes and under the hood improvements. Looking for feedback. @ntreik if you could give this build a try that would be awesome. https://ci.appveyor.com/project/antonpup/aurora/builds/26114907

Please backup your profiles!

**Comment by ntreik** [comment]
Hi just tried reduces cpu usage to almost half but my SteelSeries headset is not changing colors anymore. . its connected alright in device manager but only listening to stelseries app

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
Από: Diogo Trindade <notifications@github.com>
Στάλθηκε: Wednesday, July 24, 2019 4:52:00 PM
Προς: antonpup/Aurora <Aurora@noreply.github.com>
Κοιν.: ntreik <kostaszaras@msn.com>; Mention <mention@noreply.github.com>
Θέμα: Re: [antonpup/Aurora] Ambilight extreme CPU usage and Main monitor selection broken (#778)


The desktop duplication was recently merged (thanks @lucasvanhalst<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flucasvanhalst&data=02%7C01%7C%7C820483471abd4925224a08d7103e1a50%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636995731221165628&sdata=f9UtkIoMplaG1epet2lXSezJ89sLUAonK3YR05wTCSI%3D&reserved=0> ) and I decided to make some UI changes and under the hood improvements. Looking for feedback. @ntreik<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fntreik&data=02%7C01%7C%7C820483471abd4925224a08d7103e1a50%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636995731221165628&sdata=DfW3fM8%2BjS3aJLK%2F7PcXOzdWdBg8KcyI3CR2boM3DYI%3D&reserved=0> if you could give this build a try that would be awesome. https://ci.appveyor.com/project/antonpup/aurora/builds/26114907<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fci.appveyor.com%2Fproject%2Fantonpup%2Faurora%2Fbuilds%2F26114907&data=02%7C01%7C%7C820483471abd4925224a08d7103e1a50%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636995731221175636&sdata=rzlnnqF3dTCCRyq8M8o41kUQFqtsVeC0kmz8e%2BlHy5s%3D&reserved=0>

Please backup your profiles!

**Comment by diogotr7** [comment]
The Desktop Duplication API is now available with v0.7.0. Please make another issue if it still causes excessive cpu usage

**Comment by Asryan2a** [comment]
Hi,

I've received this item today : https://www.aliexpress.com/item/32974224895.html?spm=a2g0s.9042311.0.0.79be4c4dR8UQlI

I've installed it and looks ok but I noticed that Ambibox uses 7 to 10% of CPU ressources thus heat my CPU more than usual when the screen capture mode is ON.

Is there any way to fix that?

Thanks for the help !
