### ISSUE TITLE
Spectogram Help

### ISSUE THREAD

**Issue by Shastarocks** [antonpup/Aurora#779]
I was wondering if there is a way to use the spectogram but only on a certain part of the keyboard, like if I wanted to just put it on the num pad or just across a row of keys. Is there a way to do this using Aurora?

**Comment by Shastarocks** [comment]
also is there any plugins like how you got on CS or Dota just up for download to anyone?

**Comment by Shastarocks** [comment]
Or make a community on SDK or profiles people have made

**Comment by diogotr7** [comment]
I know you can exclude keys from the EQ in the latest dev but that's not really what you're asking.

**Comment by simon-wh** [comment]
@Shastarocks you could use the exclude keys to achieve what you're talking about as @diogotr7 mentioned. I'm not sure exactly what you're talking about with your other two comments, but I am working on a plugin system which currently allows you to add proper layers, but I plan to make it so it can add support for application as well. I imagine once that is done if anyone does use it it'll be uploaded [here](https://modworkshop.net/mydownloads.php?action=browse_cat&cid=299)
