### ISSUE TITLE
xcom enemy unknow profile dont work with enemy within 

### ISSUE THREAD

**Issue by Ravor9** [antonpup/Aurora#781]
### What are you experiencing an issue with?

- [x ] Aurora supported game, (Fill in the game)

### What kind of an issue is it?

- [x] Enhancement suggestion

### Expected behavior:
This isnt a bug. But would be nice to work for both games (just a copy past for enemy within 

### Actual behavior:
xcom enemy unknow profile dont work with enemy within 

### What is the version of Aurora you are experiencing this issue with?
0.60b

### Does the previous version of Aurora have this issue?
idk

Just want to thanks the dev team and people who collaborate with the project. I dont know nothing about programming but you guys rock

**Comment by simon-wh** [comment]
I can't find any evidence of Enemy Within having support for Alienware LightFx which is how the support for Enemy Unknown is implemented. If it does have support for it, you should be able to just apply the LightFX wrapper to the game folder which you can find in the settings for Aurora.
