### ISSUE TITLE
Not booting right

### ISSUE THREAD

**Issue by mmateusu** [antonpup/Aurora#782]
### What are you experiencing an issue with?

- [ x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ x] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Act normally

### Actual behavior:
When i initialize the PC, aurora "starts" with it but with no clue that is actually open instead. (besides task manager).
It shows the Desktop profile like it should but does not integrate with anything

### How often does this problem occur?
Everytime i boot.
### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Turn on PC

### What is the version of Aurora you are experiencing this issue with?

Aurora v0.6.1-dev3

### Does the previous version of Aurora have this issue?
i don't recall

### Please include any logs, screenshots, or files that are related to this issue:
https://puu.sh/xufM2/55ebf0806f.png

**Comment by SilentZen** [comment]
I have the same issue, after boot aurora starts but taskbar icon never appears, keyboard (corsair) and mouse (logitech) and headset (razer) light up , extra scripted devices like blinkstick and lights controlled via pi do not.
Kill process and try again sometimes works but not every time. (usually keens a few tries killing and restarting.
Let me know if there is anything I can provide to help.

**Comment by mmateusu** [comment]
Yeah, that's the way I'm doing it but it's not supposed to work like that right?
And I forgot to add but, I'm experiencing some inputlag when Aurora is open at this conditions
(G810 keyboard)

**Comment by simon-wh** [comment]
Could you post your log file?

**Comment by mmateusu** [comment]
[Logs.zip](https://github.com/antonpup/Aurora/files/1288725/Logs.zip)
From 3 days ^
From Yesterday v
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Executing Directory: C:\Users\GABRIEL\Desktop\release_major_0_6_1-dev3
Launch Directory: C:\Users\GABRIEL\Desktop\release_major_0_6_1-dev3
Processor Count: 4
User Name: Matheus
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.6.1-dev3
========================================

[INFO] 07/09/2017 20:26:55: Program started with '-silent' parameter
[INFO] 07/09/2017 20:26:59: Loading Configuration
[INFO] 07/09/2017 20:27:03: Loading Plugins
[INFO] 07/09/2017 20:27:05: Loading KB Layouts
[INFO] 07/09/2017 20:27:11: Loading Input Hooking
[INFO] 07/09/2017 20:27:12: Loading Applications
[INFO] 07/09/2017 20:27:22: Loading Device Manager
[INFO] 07/09/2017 20:27:22: Device, Logitech, was initialized
[ERROR] 07/09/2017 20:27:22: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 07/09/2017 20:27:22: Device, Corsair, was not initialized
[ERROR] 07/09/2017 20:27:22: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   em Aurora.Devices.Razer.RazerDevice.Initialize()
[INFO] 07/09/2017 20:27:22: Device, Razer, was not initialized
[ERROR] 07/09/2017 20:27:23: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   em Aurora.Devices.Clevo.ClevoDevice.Initialize()
[INFO] 07/09/2017 20:27:23: Device, Clevo Keyboard, was not initialized

**Comment by simon-wh** [comment]
It seems like this issue is very similar to #749, I feel like it is just a slight variation of it where in this case nothing ui related loads and in the other a bit loads. I'll close this and direct any talk about this problem to #749
