### ISSUE TITLE
When copy and paste profile, Aurora Crashes

### ISSUE THREAD

**Issue by mmateusu** [antonpup/Aurora#783]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Actual behavior:
When i copy and paste the profile to make a second profile like that one, it crashes

### How often does this problem occur?

Everytime i do this

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Copy a made profile
2. Click on him
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is 0.6.1 (dev-3)

### Does the previous version of Aurora have this issue?
i think not
### Please include any logs, screenshots, or files that are related to this issue:

Error (can't select the text): https://imgur.com/a/dfyQ2
Process to recreate in my PC: https://youtu.be/HcXs3Q2Ok9Q

**Comment by simon-wh** [comment]
Thank you for the detailed report! I've fixed the issue in the commit above and the fix will be included in the next release.
