### ISSUE TITLE
K95 Plat G3-G6 Keys not illuminating

### ISSUE THREAD

**Issue by Running-Banana** [antonpup/Aurora#784]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [X] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [X] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
The G3-G6 should be illuminated, in the software they show illuminated

### Actual behavior:
The G3-G6 aren't illuminated but still show in the software they are illuminated

### How often does this problem occur?

This problem occurs... (Fill in here)
Every time I use aurora 

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Load up any profile
2. Profit?

### What is the version of Aurora you are experiencing this issue with?

My version is beta v0.6.1-dev3

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue. Idk this one

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
This issue was fixed with PR #759 and will be included in the next release.
