### ISSUE TITLE
logitech g910 program issue

### ISSUE THREAD

**Issue by overwatchsquad** [antonpup/Aurora#79]
every time i try to launch aurora it cant detect keyboard or crashes without a crash report

**Comment by antonpup** [comment]
Did you extract Aurora into a folder on your computer? Is your anti-virus blocking Aurora because it's an unknown software?

**Comment by overwatchsquad** [comment]
Yes i extracted it and no anti virus software is blocking it

**Comment by overwatchsquad** [comment]
![keyboars](https://cloud.githubusercontent.com/assets/20590657/17051104/64be7974-4fbc-11e6-93b9-278523d65d1a.png)

**Comment by overwatchsquad** [comment]
i got to this point what to i do next to apply it its not working for the logitech i have it in the settings set for logitech but it keeps saying razer

**Comment by antonpup** [comment]
That's a Logitech keyboard layout. For Overwatch, you have to apply a Razer wrapper. There's nothing wrong.

**Comment by overwatchsquad** [comment]
yeah i got the program to open now but when i apply it nothing happens it doesn't work

**Comment by antonpup** [comment]
Try again with version 0.5.0

**Comment by antonpup** [comment]
Closed. Feel free to reopen this issue if you are still having problems.
