### ISSUE TITLE
k65 lux not working 

### ISSUE THREAD

**Issue by stalonage** [antonpup/Aurora#791]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [X] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [X] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ X] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [X ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
None of the profiles are working as should .

### Actual behavior:
When I set profiles and leave the app it stops working and it doesn't fully display the color profile 

### How often does this problem occur?

My version is... Betav.0.6.0.b

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by olokos** [comment]
Try to apply gsi patch under application profile that you want to use in aurora.

**Comment by simon-wh** [comment]
@stalonage What applications are you experiencing this with? To apply any necessary patches you need to click the "Show Profile Overview" button which will show a description for the application and will direct you if you need to make any changes.
