### ISSUE TITLE
Volume Overlay

### ISSUE THREAD

**Issue by magnus97** [antonpup/Aurora#793]
### What are you experiencing an issue with?

- [x ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
A visual bar/strip/line should be over the selected keys/area that is selected with color spanning across the 

### Actual behavior:
Explain here what happened instead.
The visuals freze while changing volume and for the amount of time that is specified in the volume overlay

### How often does this problem occur?

This problem occurs always

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Change volume.

### What is the version of Aurora you are experiencing this issue with?

My version is Aurora 0.6.1-dev3

### Does the previous version of Aurora have this issue?
The previous versions, did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

https://i.imgur.com/iv5DbfI.png

**Comment by brainbug89** [comment]
hmm just tested it and Volume Overlay doesn't work at all for me atm.

**Comment by magnus97** [comment]
ye i noticed it on my work computer and tested it on my home computer and also got someone with another keyboard also to test it and it just dosent work for some reason.

**Comment by simon-wh** [comment]
What does your log show when your change volume? I think the issue may be related to an error getting the device volume using NAudio.

**Comment by magnus97** [comment]
where can i find this log file?

**Comment by magnus97** [comment]
found the log file and this is the error https://pastebin.com/E0sCFy46

**Comment by magnus97** [comment]
also to shoot in im also using a logitech g933 as a audio device and logitech does some device tweaking outside of windows when it comes to its audio setup for eqalizer and surround sound

**Comment by simon-wh** [comment]
The error you're getting is the same one I was referring to. I don't think the device tweaking you're referring to affects it at all as I've experienced the error lately on multiple devices that didn't experience it previously.

**Comment by simon-wh** [comment]
I've fixed the issue with the commit above which will be available in the next release.
