### ISSUE TITLE
Ambilight brightness

### ISSUE THREAD

**Issue by insanityman00** [antonpup/Aurora#795]
### What are you experiencing an issue with?

- [x ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ x] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
higher brightness in ambilight

### Actual behavior:
Ambilight look great, but is to dark, especially average color option.

### What is the version of Aurora you are experiencing this issue with?
My version is beta v0.6.0b
 It would be nice to have possibility to increase ambilight brightness more than it is possible to do now.
Especially average color is in my opinion too dark.
I can adjust brightness by alt + volume + or -, but it is not enough imo.
It would be nice too if we had an option to define a specific area of the monitor and to inverse ambilight effect.

**Comment by insanityman00** [comment]
I think that Ambilight is the best option in Aurora software because it doesn't just looks so great, in some cases it expands experience and makes it more complete in movies or some games. Unfortunately i am new in programming so i won't be able to improve anything, but i thought that i can share my idea with others. 
There are really three things i would change or add to Ambilight mode. First of all it's more brightness. In many situations it looks great, keyboard is visible, but not distracting, but there are situations that Ambilight is barely visible or depending on the angle of eyes isn't visible at all.
Second thing is effect like mirror reflection of the screen. In some situatiions it makes more sense.
Last thing in Ambilight option is adjustable screen area to track colors. It would be perfect if user could set different areas for different processess. I will give You two examples. For video players like vlc etc it would be nice to have whole or almost whole screen tracked and copied to the keyboard. My example is first Alien movie, there are many scenes with flames on the screen or flashes, it would be nice to have a mirror reflection of whole screen on my keyboard, it would really expand my movie experience. Second case is gaming. My example will be Crysis game. It would be awesome to have an option for adjusting bottom area of the screen and copying it's colors to the keyboard. For example when i'm crouching  in the high grass and moving forward it would be awesome to see on my keyboard colors of what i am passing in the game. What i mean is the keyboard to create an illusion of screen extension. It's just an illusion, but because keyboard shows only colors and not a specific objects it makes ambilight perfect for that. Right now Ambilight works in games a little bit too chaotic because of too big screen tracking area. Bottom tracking would be usable only in games, but in my opinion it would increase immersion greatly.
Maybe it's an idea for whole new standalone Ambilight software for rgb dynamic lighting keyboards supported by Aurora software?

**Comment by Wolfieeewolf** [comment]
Look up Philips amBX. I think that's what you are after. If the amBX SDK get implemented this would be possible. amBX technology allows sound and video to be interpolated and mapped to a 3 dimensional space. You then setup your lights in your physical space with lights in front of you, beside you and behind you. lots of games are supported see http://www.mobygames.com/game-group/technology-ambx/offset,0/so,0a/ and https://web.archive.org/web/20150915051521/http://www.ambx.com/wiki/List_of_compatible_games

it's old tech so don't expect new game to work out of the box. You need to use the SDK to add amBX support to it. If you can get enough interest and get it working with modern leds and the like I'm sure you would have people interested again and there would be more games supported for this. At the moment it's not well known about or people don't understand how it works so they pass it off as just another stupid computer addon. The idea behind how amBX works is great. It was just poorly implemented thus making people not what to try it. 

I have two amBX systems setup (hoping for a 3rd if I can find one) as well as a Razer keyboard and Ambilight on my monitors, I love it. It adds so much more to the game. Feels weird playing games without it on now.

**Comment by diogotr7** [comment]
A brightness option is included in the latest v0.7.0 release
