### ISSUE TITLE
Gradient Layer improvements 

### ISSUE THREAD

**Issue by NM1r** [antonpup/Aurora#797]
### What are you experiencing an issue with?
- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?
- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [x] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### What is the version of Aurora you are experiencing this issue with?

My version is 0.6.0b.

Suggestions:
Add the away effect to the column on the left like desktop settings, so you are able to apply layers to the away effect.
Add the volume overlay as a layer.
Add the skype overlay as a layer.
(If used as a layer the settings from the general settings get overwritten)
Add more options to the gradient layer like stretching the gradiant image so the keyboard displays only a part of it for example for a rainbow animation which shows only a part of the colour spectrum at once.
Add a button to select all keys.

In addition some system to switch between different profiles via key combination would be great.

On Logitech G810 multimedia keys and lock indicators aren't settable, is that limited by Logitech?
Logitech Gaming Software is able to set them.
What about Ambilightusing the lower border of the display?

Thank you for your attention.

**Comment by diogotr7** [comment]
The media keys aren't supported by the sdk unfortunately.

**Comment by simon-wh** [comment]
1. Away effect and overlays are already planned to be reworked for v0.7.0
2. Can't you achieve that effect with what is available currently?
3. You can just use freestyle and cover the entire keyboard which would be a better way of going about it as it'd cover keys that you don't have in your layout if you were to share it with someone using a different keyboard
4. The development releases have the ability to switch profiles using keybinds
5. The media keys aren't supported by the sdk as mentioned above
6. There are plans to expand the capabilities of Ambilight, including screen regions.

**Comment by NM1r** [comment]
No since Aurora displays everytime the full spectrum (e.g. red to red) while Logitech rainbow displays only a part (eg. red to green, later on yellow to blue ...).

**Comment by simon-wh** [comment]
@NM1r I don't think I fully understand what you want to achieve, could you give a visual demonstration?

**Comment by NM1r** [comment]
Rainbow:
![img_20171001_233532](https://user-images.githubusercontent.com/31937075/32627370-82701d5e-c592-11e7-9580-b10daed23095.jpg)
Logitech
![img_20171001_233305](https://user-images.githubusercontent.com/31937075/32627398-923ab906-c592-11e7-8e36-892a11a44fc6.jpg)
Aurora

I noticed that the dev release isn't able to start with windows.

**Comment by diogotr7** [comment]
Added with #1836
