### ISSUE TITLE
Aurora dev surpresses Logitech Gaming Software

### ISSUE THREAD

**Issue by NM1r** [antonpup/Aurora#798]
### What are you experiencing an issue with?
- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?
- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
If "Enable Aurora to provide lightning effects for desktop" is unchecked, LGS should control the keyboard lightning.

### Actual behavior:
Keyboard lights are turned off except for the media keys (G810).

### How often does this problem occur?
Everytime

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Uncheck "Enable Aurora to provide lightning effects for desktop"

### What is the version of Aurora you are experiencing this issue with?
My version is v0.6.1-dev3

### Does the previous version of Aurora have this issue?
The previous version, 0.6.0b Beta, did not have this issue.

LGS does only control the keyboard if you open the light settings in the LGS application.

**Comment by simon-wh** [comment]
You have to enable the "Show Default lighting(CUE, LGS, etc) when Desktop is disabled" option in settings.

**Comment by NM1r** [comment]
Okay, sorry.
Why did you decide to have such an option? It seems rather pointless to me.
