### ISSUE TITLE
Aurora fails to start after using dev version

### ISSUE THREAD

**Issue by NM1r** [antonpup/Aurora#799]
### What are you experiencing an issue with?
- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?
- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Aurora launches.

### Actual behavior:
Instead of the main window an error message occurs. F keys light up in blue, number row in orange, media keys in white.

### How often does this problem occur?
Everytime

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Start Aurora v0.6.1-dev3
2. Close and delete Aurora v0.6.1-dev3
3. Start Aurora v0.6.0 Beta

### What is the version of Aurora you are experiencing this issue with?
My version is v0.6.0 Beta

### Does the next version of Aurora have this issue?
The next version, v0.6.1-dev3, does not have this issue.

Dev3 still works.
 I started Aurora application from extracted zip file folder without messing with the files in it, no instance of Aurora is running. Under the same circumstances dev launches, beta crashes.
Error message is attached.
![screenshot 49](https://user-images.githubusercontent.com/31937075/30523025-fe6b2044-9bd9-11e7-9b98-bb6907c39485.png)

**Comment by simon-wh** [comment]
You need to delete %appdata%/Aurora/Config.json
