### ISSUE TITLE
Exception when moving colorzone to high or to low

### ISSUE THREAD

**Issue by AndersAnderson** [antonpup/Aurora#80]
Hi Team,

for some reason there is a problem when trying to move a colorzone higher when it is first or lower when it is last.

I get an exception and the program is forceclosing.

I will attache the Exception.

Greetz
Anders
![aurora exception colorzone](https://cloud.githubusercontent.com/assets/20558865/17054553/1d4f3f82-5008-11e6-89d3-336d4d0c1da3.PNG)

**Comment by antonpup** [comment]
Interesting. I've fixed this issue before. Which profile was this happening in?

**Comment by AndersAnderson** [comment]
I tried it today, it happened in Desktop Profile, CS:Go and an Selfmade Profile. 
I think it would happen in every Profile.

**Comment by antonpup** [comment]
Yes. I see. I've fixed it early on, but didn't push an update out. [(This commit)](https://github.com/antonpup/Aurora/commit/1373b55dfbafa400173ba429ac9383480ff7054e). It will be fixed in the next version. My apologies.
