### ISSUE TITLE
game not being detected?

### ISSUE THREAD

**Issue by MiniKiller215** [antonpup/Aurora#804]
doesn't detect my game's exe i added + what games will be supported fully? later on

**Comment by MiniKiller215** [comment]
Games are not being detected at all , addd game wont at all , csgo is buggy for some reason idk why

**Comment by MiniKiller215** [comment]
CSGO GSI isnt working either
http://prntscr.com/gozqfu

**Comment by simon-wh** [comment]
Where do you have CSGO installed?

**Comment by MiniKiller215** [comment]
On E drive

**Comment by MiniKiller215** [comment]
Thats where most of my games are

**Comment by simon-wh** [comment]
Could you give a full path to the csgo directory?

**Comment by MiniKiller215** [comment]
never mind cs is on my main drive 
C:\Program Files (x86)\Steam\steamapps\Common\Counter-Strike Global Offensive
used to be on 
E:\Steam\steamapps\common\Counter-Strike Global Offensive

**Comment by MiniKiller215** [comment]
Why wouldnt aurora be detecting games as in their process that i add

**Comment by simon-wh** [comment]
Could you post your log file after attempting to Patch GSI for CSGO?

**Comment by MiniKiller215** [comment]
where would that be located?

**Comment by simon-wh** [comment]
You should be able to go to Settings then Debug and click "Show Logs Folder". If you don't have that then the path is %appdata%/Aurora/Logs/

**Comment by MiniKiller215** [comment]
found it ^^

**Comment by simon-wh** [comment]
Are you still having issues in v0.6.2b? Closing for now.
