### ISSUE TITLE
Not saving settings on default lightning

### ISSUE THREAD

**Issue by Slazke** [antonpup/Aurora#805]
### What are you experiencing an issue with?

- [x ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x ] Other, not saving settings
### Expected behavior:
It does not save the changes i make to the default lightning (the standard interactive layer), so if i fx change it to equalizer it goes back to standard after a reboot of the PC

### Actual behavior:
Explain here what happened instead.

### How often does this problem occur?
every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. open aurora
2. change defualt lighting
3. reboot
### What is the version of Aurora you are experiencing this issue with?
Beta v0.6.0b
### Does the previous version of Aurora have this issue?
every single one

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
This issue should be fixed in the dev branch
