### ISSUE TITLE
K95 Platinum G# keys and Light Edge issues

### ISSUE THREAD

**Issue by DunKalevra** [antonpup/Aurora#807]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (K95 Platinum)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
- Keys G1 to G6 should light normally;
- Light Edge keys can be clicked when assign keys.

### Actual behavior:
- G1 is mapped to light as G3, G2 is mapped as G6 and the other G# keys don't light up.
- When trying to assign keys the red text "please select key(s) you want to assign" make the 5 Light Edge keys in the right not clickable.

### How often does this problem occur?
Both problems occurs every time.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

First issue:
1. Choose a profile that lights up all keys;
2. G3 to G6 keys will not light up;
3. Use Region/key exclusion to exclude G3 and G6, it will make G1 and G2 lights will turn off.

Second issue:
1. Select a profile and try to assign keys to the last 5 Light Edge keys to the right.

### What is the version of Aurora you are experiencing this issue with?

My version is beta v0.6.1-dev3

### Does the previous version of Aurora have this issue?
The previous version I tried did not included K95 Platinum Layout (0.6.0b).

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
The lighting of the G keys was sorted out by #759. I've sorted out the issues with the light edge with the above commit
