### ISSUE TITLE
Suggestion: Unfocused Apps

### ISSUE THREAD

**Issue by Dreadp1r4te** [antonpup/Aurora#808]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [X] Other, (Suggestion)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [X] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Create a rule/checkbox that allows Aurora to "prefer" a certain app (and its corresponding app profile) if that app is detected running; i.e., Spotify Music or the desktop version of Google Play Music, so visualizer support and lighting can continue while music plays in background.

### Actual behavior:
Switching away from Spotify or the relevant music app causes the keyboard to revert to the desktop profile. Setting the desktop profile to the Equalizer effect works, but I have a Corsair CUE profile for default lighting, and only want the Equalizer profile running when a music app is running. 

### How often does this problem occur?

This problem occurs... Everytime

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. N/A, Suggestion
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (0.6.0b)

### Does the previous version of Aurora have this issue?
N/A, Suggestion

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
I've got exactly this planned already for v0.7.0 using the Layer Logic, I'll use this for tracking the feature.

**Comment by Dreadp1r4te** [comment]
Excellent, thanks for the awesome job! Really glad to see Aurora evolved to include bridging all the various RGB products and add awesome new features to them! Is there a donation link available somewhere?

**Comment by simon-wh** [comment]
@Dreadp1r4te You can see the details of the development team and donations [here](https://github.com/antonpup/Aurora#development-team)

**Comment by diogotr7** [comment]
You can now do this with overlay layers.
