### ISSUE TITLE
Aurora not Autostarting on Windows 10

### ISSUE THREAD

**Issue by AndersAnderson** [antonpup/Aurora#81]
Hi,

i found out that Aurora in my case is not autostarting on windows 10.

It is however in the Autostart-Tab of my Taskmanager as activated.
I checked twice if I set the Setting in Aurora to start and i did.
Also i put a shortcut of Aurora in the Autostart Folder.

Is there anyt hing i might be missing or any workaround?

Greetz 
Anders

**Comment by antonpup** [comment]
If you have a corsair device. CUE will load after Aurora has started. As a result, Aurora does not detect CUE devices on startup. This should be addressed in next version.

**Comment by AndersAnderson** [comment]
I got a Logitech G910 with the latest Logitech Gaming Software.
Maybe its the same issue but with Logitech.

**Comment by shikkoku** [comment]
I just set autostart in Aurora setting and work fine whit my G910 keyborad on Windows 10 x64.

**Comment by antonpup** [comment]
This should be fixed with version 0.5.0
