### ISSUE TITLE
Can you support Roccat RGB Products

### ISSUE THREAD

**Issue by ChaosgamesTV** [antonpup/Aurora#811]
Hey,
on your website you say that you want to support everything that has an SDK. Roccat has one.
I use Aurora for a long time now with my G810 Keyboard and my Corsair Polaris mousepad. But my roccat mouse did not work.

A support would be realy nice;).

**Comment by ChaosgamesTV** [comment]
Hey also have a nee technologie for some cool effects Maybe they will bring an SDK later this Year.
http://aimo.roccat.org/de/Overview/

**Comment by superdachs** [comment]
I've got a suora fx rgb keyboard today and would contribute to development with testing and even coding if someone would shows me where to start. :)

**Comment by simon-wh** [comment]
@superdachs Thanks! I'm going to take another look at what Roccat have available for their SDK soon and see what I can do. I'll let you know if I get anything!

**Comment by Khurune** [comment]
Getting my suora fx rgb in the next few days, just waiting for it to arrive. Willing to test some trial / alpha builds of the wrapper. 

Thanks for your hard work.

**Comment by simon-wh** [comment]
Once you get it do you want to try the [latest build](https://ci.appveyor.com/project/antonpup/aurora/build/artifacts)? It has the PR #1006 for Roccat support and some improvements I made, so I'm not 100% certain if it'll still work.

**Comment by Khurune** [comment]
Had board a few days now. Will test that build out later on today once I'm back from work.

**Comment by Khurune** [comment]
@simon-wh Installed latest build, how ever I can't test due to SuoraFX not currently being compatible with TalkFX.

**Comment by simon-wh** [comment]
Support for what SDKs are available has been done in the dev branch.

**Comment by BernhardWebstudio** [comment]
Do you accept PR's with "hacks", meaning inofficial SDKs, in this case imitating what is done in https://github.com/Wolf2789/ROCCAT-SuoraFX-Effects-Animator ?

**Comment by simon-wh** [comment]
Yep
