### ISSUE TITLE
Aurora not launching on start up

### ISSUE THREAD

**Issue by jdubnz** [antonpup/Aurora#813]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Should launch on start up. Checked in start up manager and anti virus, both have it ticked to launch on start up, no delay.

### Actual behavior:
Doesn't launch

### How often does this problem occur?

Everytime.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. 
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... v.0.6.0b

### Does the previous version of Aurora have this issue?
Yes.

### Please include any logs, screenshots, or files that are related to this issue:

Log: https://pastebin.com/EhkqKsvK

Aurora is run as admin everytime.

**Comment by simon-wh** [comment]
Could you try the [latest development release](https://github.com/antonpup/Aurora/releases) to see if you still have the issue?

**Comment by jdubnz** [comment]
Tried it and problems are all solved thank you!
