### ISSUE TITLE
Tray icon does not show up

### ISSUE THREAD

**Issue by Wuestengecko** [antonpup/Aurora#814]
### What are you experiencing an issue with?

- [X] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [X] Other, I'm not sure how to categorize this.

### Expected behavior:
On startup, the tray icon should show up in system tray.

### Actual behavior:
Light effects start, but the tray icon does not show.

### How often does this problem occur?

This problem occurs everytime.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Start Aurora.
2. Try to open the main window via system tray.
3. Realize that there is no icon.

### What is the version of Aurora you are experiencing this issue with?

My version is... v0.6.1-dev3

### Does the previous version of Aurora have this issue?
The previous version, v0.6.1-dev2, did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

https://pastebin.com/V6UQaZbK

**Comment by simon-wh** [comment]
Did you check %appdata%/Aurora/Logs for the latest log file?

**Comment by Wuestengecko** [comment]
Indeed, there is one. Edited it into OP.

**Comment by Wuestengecko** [comment]
The issue I experienced here might very well be the same as in #749, unfortunately I did not check RAM usage back then. As I'm running into the mentioned issue too right now for some time, I'll assume it is indeed a duplicate.
