### ISSUE TITLE
Logitech G502 mice lighting not synced with app

### ISSUE THREAD

**Issue by andrewwilliam26** [antonpup/Aurora#817]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (Logitech G502)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
sync the rgb lights with the aurora app

### Actual behavior:
my logitech g502 mice isnt syncing with the aurora app. I've read that some people use the g900 in the settings but still, my g502 wouldnt sync with the app. Instead it would still sync with LGS

### How often does this problem occur?

This problem occurs... everytime

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. use g502 mice
2. select g900 from settings
3. set a lighting profile for that mouse (e.g static color)

### What is the version of Aurora you are experiencing this issue with?

My version is... beta v0.6.1-dev3

### Does the previous version of Aurora have this issue?
havent use previous version, first time using aurora

**Comment by simon-wh** [comment]
Has the Logitech integration definitely connected? You should be able to check under Device Manager what the status of it is, also logs would be helpful. Either click "Show Logs Folder" from Settings -> Debug or go to %appdata%/Aurora/logs

**Comment by simon-wh** [comment]
Closing due to lack of follow up
