### ISSUE TITLE
reset on pc startup.

### ISSUE THREAD

**Issue by Elias8477** [antonpup/Aurora#818]
Hello, it's the second day I used Aurora and (its morning for me right now) when I started up my pc it gave the "first time instructions" and it reset my settings for my keyboard (what keyboard I've selected and keyboard layout) the rest is how it was, the color settings etc. are just the same.
I don't think this is normal so help would be appreciated! I've downloaded the program from the official site, not from here, on the GitHub.

**Comment by simon-wh** [comment]
I think the issue is related to a saving issue which requires a safe shutdown of the application for it to properly save the configuration changes. I believe I've sorted this out in the development branch so it shouldn't be an issue anymore.

**Comment by Elias8477** [comment]
So, I don't need to do anything? No update or patch to install?

**Comment by simon-wh** [comment]
It should be fine now, but you could get the development releases which should be better than the current stable build. I think the changes I made for saving haven't been put in a release yet.
