### ISSUE TITLE
Overwatch profiles not working at all (G910)

### ISSUE THREAD

**Issue by blingblong** [antonpup/Aurora#820]
### What are you experiencing an issue with?

- [ x] Aurora
- [x ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ x] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Right after applying the patch to overwatch in aurora, the keyboard flashes the correct colors for a second and then everything turns black. In the layers tab there are no layers, unlike in all other game profiles in aurora. Would those missing be the issue? I have done all tricks explained all around the forums and nothing works. My keyboard is just stuck on black.

### Actual behavior:
Lighting does not work normally. 

### How often does this problem occur?
Always.

### What is the version of Aurora you are experiencing this issue with?
Newest, 060b

**Comment by Poolitzer** [comment]
Having a G910 Orion Spectrum here, works like a charm

**Comment by blingblong** [comment]
Dunno what witchcraft you use :D Mine used to work a month ago, but has now suddenly stopped after a major update in overwatch. Seems like I can't get it to work again.

**Comment by Poolitzer** [comment]
Maybe the developer has an idea how to fix it xD

**Comment by Tehu-Tehu** [comment]
does it happen in a match aswell or just the lobby ?

**Comment by simon-wh** [comment]
Have a look at #771
