### ISSUE TITLE
Doesn't recognize CSGO while using GamersClub Anti Cheat

### ISSUE THREAD

**Issue by luanveras3** [antonpup/Aurora#822]
i am facing some problems to run the Aurora and the CSGO while using the GamersClub AntiCheat. 

### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [x] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [x] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
Should works fine with and without the AntiCheat 

### Actual behavior:
Explain here what happened instead.
Aurora doesn't recognize the CSGO program

### How often does this problem occur?

This problem occurs... (Fill in here)
Everytiime

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Install the GamersClubs Anti Cheat, 
2. Run it 
3. Try to Open the CSGO 

### What is the version of Aurora you are experiencing this issue with?

My version is... (Fill in here)
Beta V0.6

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.
I Don't know

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
It is likely that anti-cheat is interfering with the GSI system that Aurora utilizes for doing lighting. Do you normally have it working without using that Anti-cheat? Because if so I doubt there is much I can do to change anything.

**Comment by luanveras3** [comment]
Yes, without using this anti cheat works great.

Maybe if I change the sequence that aurora read the open programs, I could
make it work.

But thanks anyway

Em 3 de out de 2017 11:47, "Simon W" <notifications@github.com> escreveu:

It is likely that anti-cheat is interfering with the GSI system that Aurora
utilizes for doing lighting. Do you normally have it working without using
that Anti-cheat? Because if so I doubt there is much I can do to change
anything.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/antonpup/Aurora/issues/822#issuecomment-333865666>, or mute
the thread

**Comment by simon-wh** [comment]
The anti-cheat probably disables GSI which is required for the CS:GO functionality to work so I don't know how much I can actually do about this.
