### ISSUE TITLE
Req: Quake Champions suppot

### ISSUE THREAD

**Issue by Yakumounr** [antonpup/Aurora#825]
The latest version of Quake Champions just launched with Razer Chroma support built in, it would be great if you could add that to Aurora so that those with Corsair Strafe RGB and similar non Razer products could have lighting effects as well :o)

**Comment by Yakumounr** [comment]
I've tried just using the Razer Chroma wrapper, and though the game appears to lock the razer .dll files in the same folder as the game exe, aurora doesn't seem to do anything.

Aurora's desktop profiles are working with my keyboard so it's not that.
I've tested the current release version or Aurora and also v0.6.1-dev3 ( tip for anyone reverting from the beta back to the production release, I had to delete %appdata%\Aurora\   or the production build crashed on launch)

**Comment by simon-wh** [comment]
Could you post the log file after trying to get it work?

**Comment by Yakumounr** [comment]
"[ERROR] 09/10/2017 04:59:43: Razer device, Exception! Message:System.Exception: No Chroma SDK available"
Do end users have to install the Razer SDK as well then? I don't recall seeing this mentioned anywhere

Here's the full log:

`========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Processor Count: 8
User DomainName: -------
User Name: Yakumo
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.0.6.0
========================================

09/10/2017 04:58:17: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_py_script.py. Exception: System.Exception: Provided script, does not meet all the requirements
   at Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) in D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:line 32
   at CallSite.Target(Closure , CallSite , Type , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Aurora.Devices.DeviceManager..ctor() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:line 57
09/10/2017 04:58:18: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_script.cs. Exception: System.Exception: Provided script, does not meet all the requirements
   at Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) in D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:line 32
   at CallSite.Target(Closure , CallSite , Type , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Aurora.Devices.DeviceManager..ctor() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:line 71
[INFO] 09/10/2017 04:58:18: Loading Configuration
[INFO] 09/10/2017 04:58:19: Loading Device Manager
[ERROR] 09/10/2017 04:58:19: Logitech LED SDK could not be initialized. (LogiLedSetTargetDevice or LogiLedSaveCurrentLighting failed)
[INFO] 09/10/2017 04:58:19: Device, Logitech, was not initialized
[INFO] 09/10/2017 04:58:19: Corsair device, Initialized with x64-SDK
[INFO] 09/10/2017 04:58:19: Device, Corsair, was initialized
[INFO] 09/10/2017 04:58:19: No Chroma SDK available
[ERROR] 09/10/2017 04:58:19: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 09/10/2017 04:58:19: Device, Razer, was not initialized
[INFO] 09/10/2017 04:58:19: Could not connect to Clevo WMI Interface
[ERROR] 09/10/2017 04:58:19: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 65
[INFO] 09/10/2017 04:58:19: Device, Clevo Keyboard, was not initialized
[ERROR] 09/10/2017 04:58:19: Cooler Master device control could not be initialized
[INFO] 09/10/2017 04:58:19: Device, Cooler Master, was not initialized
[INFO] 09/10/2017 04:58:19: Device, AtmoOrb, was initialized
[INFO] 09/10/2017 04:58:19: Loading KB Layouts
[INFO] Baseline X = 0
[INFO] Baseline Y = 37
[INFO] 09/10/2017 04:58:19: Input Hooking
[INFO] 09/10/2017 04:58:19: Starting GameEventHandler
[INFO] 09/10/2017 04:58:19: Starting GameStateListener
[INFO] 09/10/2017 04:58:19: Device, Corsair, was shutdown
09/10/2017 04:58:19: Listening for game integration calls...
09/10/2017 04:58:19: Loading WinApp...
09/10/2017 04:58:19: Loaded WinApp
09/10/2017 04:58:19: Loading ResourceDictionaries...
09/10/2017 04:58:19: [AuroraCommandsServerIPC] Pipe created 36610825
09/10/2017 04:58:19: [IPCServer] Pipe created 7995840
[INFO] 09/10/2017 04:58:19: Device, AtmoOrb, was shutdown
09/10/2017 04:58:19: Loaded ResourceDictionaries
09/10/2017 04:58:19: Loading ConfigUI...
[ERROR] 09/10/2017 04:59:22: Logitech LED SDK could not be initialized. (LogiLedSetTargetDevice or LogiLedSaveCurrentLighting failed)
[INFO] 09/10/2017 04:59:22: Device, Logitech, was not initialized
[INFO] 09/10/2017 04:59:22: Corsair device, Initialized with x64-SDK
[INFO] 09/10/2017 04:59:22: Device, Corsair, was initialized
[INFO] 09/10/2017 04:59:22: No Chroma SDK available
[ERROR] 09/10/2017 04:59:22: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 09/10/2017 04:59:22: Device, Razer, was not initialized
[INFO] 09/10/2017 04:59:22: Could not connect to Clevo WMI Interface
[ERROR] 09/10/2017 04:59:22: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 65
[INFO] 09/10/2017 04:59:22: Device, Clevo Keyboard, was not initialized
[ERROR] 09/10/2017 04:59:22: Cooler Master device control could not be initialized
[INFO] 09/10/2017 04:59:22: Device, Cooler Master, was not initialized
[INFO] 09/10/2017 04:59:22: Device, AtmoOrb, was initialized
[INFO] 09/10/2017 04:59:29: Device, Corsair, was shutdown
[INFO] 09/10/2017 04:59:29: Device, AtmoOrb, was shutdown
[ERROR] 09/10/2017 04:59:33: Logitech LED SDK could not be initialized. (LogiLedSetTargetDevice or LogiLedSaveCurrentLighting failed)
[INFO] 09/10/2017 04:59:33: Device, Logitech, was not initialized
[INFO] 09/10/2017 04:59:33: Corsair device, Initialized with x64-SDK
[INFO] 09/10/2017 04:59:33: Device, Corsair, was initialized
[INFO] 09/10/2017 04:59:33: No Chroma SDK available
[ERROR] 09/10/2017 04:59:33: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 09/10/2017 04:59:33: Device, Razer, was not initialized
[INFO] 09/10/2017 04:59:33: Could not connect to Clevo WMI Interface
[ERROR] 09/10/2017 04:59:33: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 65
[INFO] 09/10/2017 04:59:33: Device, Clevo Keyboard, was not initialized
[ERROR] 09/10/2017 04:59:33: Cooler Master device control could not be initialized
[INFO] 09/10/2017 04:59:33: Device, Cooler Master, was not initialized
[INFO] 09/10/2017 04:59:33: Device, AtmoOrb, was initialized
[INFO] 09/10/2017 04:59:33: Retrying Device Initialization
[ERROR] 09/10/2017 04:59:33: Logitech LED SDK could not be initialized. (LogiLedSetTargetDevice or LogiLedSaveCurrentLighting failed)
[INFO] 09/10/2017 04:59:33: Device, Logitech, was not initialized
[INFO] 09/10/2017 04:59:33: No Chroma SDK available
[ERROR] 09/10/2017 04:59:33: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 09/10/2017 04:59:33: Device, Razer, was not initialized
[INFO] 09/10/2017 04:59:33: Could not connect to Clevo WMI Interface
[ERROR] 09/10/2017 04:59:33: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 65
[INFO] 09/10/2017 04:59:33: Device, Clevo Keyboard, was not initialized
[ERROR] 09/10/2017 04:59:33: Cooler Master device control could not be initialized
[INFO] 09/10/2017 04:59:33: Device, Cooler Master, was not initialized
[INFO] 09/10/2017 04:59:38: Retrying Device Initialization
[ERROR] 09/10/2017 04:59:38: Logitech LED SDK could not be initialized. (LogiLedSetTargetDevice or LogiLedSaveCurrentLighting failed)
[INFO] 09/10/2017 04:59:38: Device, Logitech, was not initialized
[INFO] 09/10/2017 04:59:38: No Chroma SDK available
[ERROR] 09/10/2017 04:59:38: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 09/10/2017 04:59:38: Device, Razer, was not initialized
[INFO] 09/10/2017 04:59:38: Could not connect to Clevo WMI Interface
[ERROR] 09/10/2017 04:59:38: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 65
[INFO] 09/10/2017 04:59:38: Device, Clevo Keyboard, was not initialized
[ERROR] 09/10/2017 04:59:38: Cooler Master device control could not be initialized
[INFO] 09/10/2017 04:59:38: Device, Cooler Master, was not initialized
[INFO] 09/10/2017 04:59:43: Retrying Device Initialization
[ERROR] 09/10/2017 04:59:43: Logitech LED SDK could not be initialized. (LogiLedSetTargetDevice or LogiLedSaveCurrentLighting failed)
[INFO] 09/10/2017 04:59:43: Device, Logitech, was not initialized
[INFO] 09/10/2017 04:59:43: No Chroma SDK available
[ERROR] 09/10/2017 04:59:43: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 09/10/2017 04:59:43: Device, Razer, was not initialized
[INFO] 09/10/2017 04:59:43: Could not connect to Clevo WMI Interface
[ERROR] 09/10/2017 04:59:43: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 65
[INFO] 09/10/2017 04:59:43: Device, Clevo Keyboard, was not initialized
[ERROR] 09/10/2017 04:59:43: Cooler Master device control could not be initialized
[INFO] 09/10/2017 04:59:43: Device, Cooler Master, was not initialized
[INFO] 09/10/2017 04:59:44: Device, Corsair, was shutdown
[INFO] 09/10/2017 04:59:44: Device, AtmoOrb, was shutdown
[ERROR] 09/10/2017 05:00:06: Logitech LED SDK could not be initialized. (LogiLedSetTargetDevice or LogiLedSaveCurrentLighting failed)
[INFO] 09/10/2017 05:00:06: Device, Logitech, was not initialized
[INFO] 09/10/2017 05:00:06: Corsair device, Initialized with x64-SDK
[INFO] 09/10/2017 05:00:06: Device, Corsair, was initialized
[INFO] 09/10/2017 05:00:06: No Chroma SDK available
[ERROR] 09/10/2017 05:00:06: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 54
[INFO] 09/10/2017 05:00:06: Device, Razer, was not initialized
[INFO] 09/10/2017 05:00:06: Could not connect to Clevo WMI Interface
[ERROR] 09/10/2017 05:00:06: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in D:\Repositories\Git\Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 65
[INFO] 09/10/2017 05:00:06: Device, Clevo Keyboard, was not initialized
[ERROR] 09/10/2017 05:00:06: Cooler Master device control could not be initialized
[INFO] 09/10/2017 05:00:06: Device, Cooler Master, was not initialized
[INFO] 09/10/2017 05:00:06: Device, AtmoOrb, was initialized
09/10/2017 05:00:13: [IPCServer] Pipe connection established
09/10/2017 05:03:44: [IPCServer] Pipe connection lost
09/10/2017 05:03:44: [IPCServer] Pipe created 56251872
[INFO] 09/10/2017 05:03:44: Device, Corsair, was shutdown
[INFO] 09/10/2017 05:03:44: Device, AtmoOrb, was shutdown
`

**Comment by Yakumounr** [comment]
If there's anything further needed please let me know :)

**Comment by simon-wh** [comment]
@Yakumounr That error is just for interacting with Razer devices, not the game. I don't see any errors that would conclude any possible issues, Could you run the [latest development release](https://github.com/antonpup/Aurora/releases) and reapply the wrapper to see if it makes a difference?

**Comment by Yakumounr** [comment]
Hi, I did note in my second post that I had tried v0.6.1-dev3 already, but here is a new log from a fresh install of that today. It doesn't work in the game, if I don't create a QuakeChampions profile the Aurora Desktop Lighting effects work on the keyboard, if I do create a QuakeChampions profile that stops the Desktop effects, but the Chroma effects from the game are never triggered either way.

(Aurora also crashed when I tried to delete a layer from the profile)

Here's the log :
[2018_01_20.log](https://github.com/antonpup/Aurora/files/1648796/2018_01_20.log)

**Comment by simon-wh** [comment]
Hm, I'm not sure, the log isn't really saying anything of help. I've got a friend who has the game so I'll try and look into it once I try and sort out some of the other games that have issues that I've already got.

**Comment by diogotr7** [comment]
I just tried this game on the latest bleeding-edge build and got a similar result. The only relevant lines were these:

`[INFO] 22:58:20: [IPCServer] Pipe connection established`
`[INFO] 23:01:59: [IPCServer] Pipe connection lost`
`[INFO] 23:01:59: [IPCServer] Pipe created 38583594`


I'd also like to add that the first line appears when i open the game, but the following two appear when i close it. I don't know how relevant this is but I don't really have any good info. The chroma effects are enabled in-game and I know from a friend of mine with a razer keyboard that they indeed do work.

I'm glad to help if more testing is needed.

**Comment by diogotr7** [comment]
quake champions appears to work with the updates to the wrapper. please test this and get back to me. https://ci.appveyor.com/project/antonpup/aurora/build/0.6.2b-442

**Comment by diogotr7** [comment]
Further changes have been made to the wrapper and now quake works as it's supposed to.

**Comment by Yakumounr** [comment]
I removed all traces of aurora's install folder,  %appdata%\Aurora and any installed wrapper files, installed Aurora-setup-v0.6.2b-442.exe from your post 10 days ago, made sure iCUE had the SDK enabled. 
Check my keyboard is set correcting in the Devices and Wrappers tab.
Installed the Razer wrapper into "Steam\steamapps\common\quakechampions\client\bin\pc\"   so the RzChromaSDK64.dll file was in the same folder as quakechampions.exe
Added a profile for QuakeChampions, added a layer of the type "Wrapper Lighting Layer"

Clicking through the other profiles Aurora clearly has control of the keyboard lighting as the lights change and respond if on the desktop profile.
Starting QuakeChampions (with Chroma support enabled in game) the keyboard just goes black and stays that way.

Full log file : 
`[INFO] 01:03:20: 
========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\WINDOWS\system32
Executing Directory: C:\Program Files\Aurora
Launch Directory: C:\Program Files\Aurora
Processor Count: 8
SystemPageSize: 4096
Environment Version: 4.0.30319.42000
Is Elevated: True
Aurora Assembly Version: 1.0.0.0
Aurora File Version: 0.6.2b-442
========================================

[INFO] 01:03:20: Loading Configuration
[INFO] 01:03:20: Loading Plugins
[INFO] 01:03:20: Loading KB Layouts
[INFO] 01:03:20: Loading Input Hooking
[INFO] 01:03:20: Loading Applications
[INFO] 01:03:21: Loading Device Manager
[ERROR] 01:03:21: Logitech LED SDK could not be initialized. (LogiLedSetTargetDevice or LogiLedSaveCurrentLighting failed)
[INFO] 01:03:21: Device, Logitech, was not initialized
[INFO] 01:03:21: Corsair device, Initialized with x64-SDK
[INFO] 01:03:23: Device, Corsair, was initialized
[ERROR] 01:03:23: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 64
[INFO] 01:03:23: Device, Razer, was not initialized
[ERROR] 01:03:23: Roccat device, Exception! Message:System.Exception: No devices connected
   at Aurora.Devices.Roccat.RoccatDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Roccat\RoccatDevice.cs:line 213
[INFO] 01:03:23: Device, Roccat, was not initialized
[ERROR] 01:03:24: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 71
[INFO] 01:03:24: Device, Clevo Keyboard, was not initialized
[INFO] 01:03:24: No Cooler Master devices successfully Initialized!
[INFO] 01:03:24: Device, Cooler Master, was not initialized
[INFO] 01:03:24: Device, AtmoOrb, was initialized
[ERROR] 01:03:24: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 58
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 55
[INFO] 01:03:24: Device, SteelSeries, was not initialized
[INFO] 01:03:24: Device, SteelSeriesHID, was not initialized
[INFO] 01:03:24: No Wooting devices successfully Initialized!
[INFO] 01:03:24: Device, Wooting, was not initialized
[INFO] 01:03:24: Starting GameStateListener
[INFO] 01:03:24: Retrying Device Initialization
[ERROR] 01:03:24: Logitech LED SDK could not be initialized. (LogiLedSetTargetDevice or LogiLedSaveCurrentLighting failed)
[INFO] 01:03:24: Device, Logitech, was not initialized
[ERROR] 01:03:24: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 64
[INFO] 01:03:24: Device, Razer, was not initialized
[INFO] 01:03:24: Listening for game integration calls...
[INFO] 01:03:24: Loading ResourceDictionaries...
[ERROR] 01:03:24: Roccat device, Exception! Message:System.Exception: No devices connected
   at Aurora.Devices.Roccat.RoccatDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Roccat\RoccatDevice.cs:line 213
[INFO] 01:03:24: Device, Roccat, was not initialized
[ERROR] 01:03:24: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 71
[INFO] 01:03:24: Device, Clevo Keyboard, was not initialized
[INFO] 01:03:24: No Cooler Master devices successfully Initialized!
[INFO] 01:03:24: Device, Cooler Master, was not initialized
[ERROR] 01:03:24: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 58
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 55
[INFO] 01:03:24: Device, SteelSeries, was not initialized
[INFO] 01:03:24: [IPCServer] Pipe created 21647132
[INFO] 01:03:24: [AuroraCommandsServerIPC] Pipe created 6451435
[INFO] 01:03:24: Loaded ResourceDictionaries
[INFO] 01:03:24: Loading ConfigUI...
[INFO] 01:03:24: Device, SteelSeriesHID, was not initialized
[INFO] 01:03:24: No Wooting devices successfully Initialized!
[INFO] 01:03:24: Device, Wooting, was not initialized
[DEBUG] 01:03:24: Trying to get game path for: 570
[DEBUG] 01:03:24: Trying to get game path for: 730
[DEBUG] 01:03:24: Trying to get game path for: 219150
[DEBUG] 01:03:24: Trying to get game path for: 257510
[DEBUG] 01:03:24: Trying to get game path for: 209870
[DEBUG] 01:03:24: Trying to get game path for: 49470
[DEBUG] 01:03:24: Trying to get game path for: 241930
[DEBUG] 01:03:24: Trying to get game path for: 41070
[DEBUG] 01:03:24: Trying to get game path for: 270450
[DEBUG] 01:03:24: Trying to get game path for: 200510
[DEBUG] 01:03:24: Trying to get game path for: 43160
[DEBUG] 01:03:24: Trying to get game path for: 239140
[DEBUG] 01:03:24: Trying to get game path for: 200010
[DEBUG] 01:03:24: Trying to get game path for: 232090
[INFO] 01:03:29: Retrying Device Initialization
[ERROR] 01:03:29: Logitech LED SDK could not be initialized. (LogiLedSetTargetDevice or LogiLedSaveCurrentLighting failed)
[INFO] 01:03:29: Device, Logitech, was not initialized
[ERROR] 01:03:29: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 64
[INFO] 01:03:29: Device, Razer, was not initialized
[ERROR] 01:03:29: Roccat device, Exception! Message:System.Exception: No devices connected
   at Aurora.Devices.Roccat.RoccatDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Roccat\RoccatDevice.cs:line 213
[INFO] 01:03:29: Device, Roccat, was not initialized
[ERROR] 01:03:29: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 71
[INFO] 01:03:29: Device, Clevo Keyboard, was not initialized
[INFO] 01:03:29: No Cooler Master devices successfully Initialized!
[INFO] 01:03:29: Device, Cooler Master, was not initialized
[ERROR] 01:03:29: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 58
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 55
[INFO] 01:03:29: Device, SteelSeries, was not initialized
[INFO] 01:03:29: Device, SteelSeriesHID, was not initialized
[INFO] 01:03:29: No Wooting devices successfully Initialized!
[INFO] 01:03:29: Device, Wooting, was not initialized
[INFO] 01:03:34: Retrying Device Initialization
[ERROR] 01:03:34: Logitech LED SDK could not be initialized. (LogiLedSetTargetDevice or LogiLedSaveCurrentLighting failed)
[INFO] 01:03:34: Device, Logitech, was not initialized
[ERROR] 01:03:34: Razer device, Exception! Message:System.Exception: No Chroma SDK available
   at Aurora.Devices.Razer.RazerDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Razer\RazerDevice.cs:line 64
[INFO] 01:03:34: Device, Razer, was not initialized
[ERROR] 01:03:34: Roccat device, Exception! Message:System.Exception: No devices connected
   at Aurora.Devices.Roccat.RoccatDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Roccat\RoccatDevice.cs:line 213
[INFO] 01:03:34: Device, Roccat, was not initialized
[ERROR] 01:03:34: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   at Aurora.Devices.Clevo.ClevoDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:line 71
[INFO] 01:03:34: Device, Clevo Keyboard, was not initialized
[INFO] 01:03:34: No Cooler Master devices successfully Initialized!
[INFO] 01:03:34: Device, Cooler Master, was not initialized
[ERROR] 01:03:34: SteelSeries GameSense SDK could not be initialized: System.IO.FileNotFoundException: Core Props file could not be found at "C:\ProgramData/SteelSeries/SteelSeries Engine 3/coreProps.json"
   at SteelSeries.GameSenseSDK.GameSenseSDK.init(String sseGameName, String sseGameDisplayname, Byte iconColorID) in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\GameSenseSDK.cs:line 58
   at Aurora.Devices.SteelSeries.SteelSeriesDevice.Initialize() in C:\projects\aurora\Project-Aurora\Project-Aurora\Devices\SteelSeries\SteelSeriesDevice.cs:line 55
[INFO] 01:03:34: Device, SteelSeries, was not initialized
[INFO] 01:03:34: Device, SteelSeriesHID, was not initialized
[INFO] 01:03:34: No Wooting devices successfully Initialized!
[INFO] 01:03:34: Device, Wooting, was not initialized
[INFO] 01:07:12: [IPCServer] Pipe connection established
[INFO] 01:09:26: [IPCServer] Pipe connection lost
[INFO] 01:09:26: [IPCServer] Pipe created 36736776
[INFO] 01:09:48: Device, Corsair, was shutdown
`

**Comment by diogotr7** [comment]
Sorry if that wasn't clear. Further commits have been made and quake has now proper support in the UI. Here: https://ci.appveyor.com/project/antonpup/aurora/build/0.6.2b-451/artifacts . Please get back to me if it works

**Comment by Yakumounr** [comment]
Aurora-setup-v0.6.2b-451.exe works !! thank you so much =)

**Comment by Podbod12** [comment]
Works for me too! Cheers everyone involved!!
