### ISSUE TITLE
Volume Overlay Not Working

### ISSUE THREAD

**Issue by selmansavas** [antonpup/Aurora#829]
### What are you experiencing an issue with?

- [x ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Keyboard lights should dim and light up in sync with volume level, from down left to up right.

### Actual behavior:
Nothing happening

### How often does this problem occur?

This problem occurs... (everytime)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Installed aurora
2. Opened it
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (v0.61b- dev3)

### Does the previous version of Aurora have this issue?
The previous version, (0.60), did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
The Volume Overlay has been fixed in the dev branch and will be working in the next release.
