### ISSUE TITLE
The program crashes when I tick the "Start with Windows" option

### ISSUE THREAD

**Issue by KfirP** [antonpup/Aurora#832]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
It should just let me tick the option and run on startup

### Actual behavior:
It crashes as soon as I tick it, not keeping the option ticked

### How often does this problem occur?

This problem occurs every time I try to tick it

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. 
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is beta v0.6.0b

### Does the previous version of Aurora have this issue?
I don't know

### Please include any logs, screenshots, or files that are related to this issue:

https://pastebin.com/FMUxJpNg
also attached here
[2017_11_10.log](https://github.com/antonpup/Aurora/files/1374752/2017_11_10.log)

**Comment by simon-wh** [comment]
Try the [latest development release](https://github.com/antonpup/Aurora/releases)

**Comment by KfirP** [comment]
I tried it, now it doesn't crash... But on startup I can see the process is running but it doesn't apply on the keyboard. So I need to end the process and run the program manually.

**Comment by simon-wh** [comment]
Probably the same issue #749
