### ISSUE TITLE
Aurora Download Not Working

### ISSUE THREAD

**Issue by wallrys** [antonpup/Aurora#834]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, (Fill in another type of issue here): aurora-web-setup.exe fails saying "Download failed: The server name or address could not be resolved."  My internet connection is stable and working.
### Expected behavior:
It should download properly.

### Actual behavior:
It won't download.

### How often does this problem occur?

Every time I try to download aurora.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1.  go to project-aurora.com
2. click download.
3. try to run the downloaded file.

### What is the version of Aurora you are experiencing this issue with?

My version is whatever is live on the website.

### Does the previous version of Aurora have this issue?
First time ever trying to download.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

https://imgur.com/a/6ffXD

**Comment by mitchtjohnston** [comment]
+1 to this request. I am also experiencing this issue.

**Comment by simon-wh** [comment]
It is a temporary issue as the server that hosts the download files is migrating currently.

**Comment by simon-wh** [comment]
For now, you can download Aurora manually [here](https://github.com/antonpup/Aurora/releases) on github, or [here](https://project-aurora.com/history.php) on the website. I'm going to update the web installer so that it can use the correct domain, but it may go out of action again in the near future temporarily.
