### ISSUE TITLE
Some profiles aren't being recognized on the latest release (0.6.1-dev3)

### ISSUE THREAD

**Issue by RaPoZaUm** [antonpup/Aurora#837]
As an exemple, when I'm trying to open this new profile https://modworkshop.net/mydownloads.php?action=view_down&did=17402 on the software, it just shows default one, not showing any custom layer. Just like I did nothing.

**Comment by simon-wh** [comment]
That profile shows as default because the profile you linked was made before the layer system was implemented so it isn't compatible with newer aurora versions
