### ISSUE TITLE
Steelseries QcK Prisim

### ISSUE THREAD

**Issue by magnus97** [antonpup/Aurora#841]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (Steelseries QcK Prisim)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [x] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### What is the version of Aurora you are experiencing this issue with?

My version is... 0.6.1 dev-3

I have looked into the code of what is happening on the steelseries comunication and saw that there is functonality there for the mousepad but for some reason it dosent light up.

**Comment by magnus97** [comment]
Started to dig more into the code and running it in vs found out that it uses on line 161 in SteelSeriesDevice.cs that it dosent get through the if statement as there is no Peripheral in the Dictionary key list

**Comment by drhead** [comment]
I am using the same build of Aurora and the mousepad does light up with Aurora.  I am using SteelSeries Engine 3.11.11 and I have Aurora's mouse set to "Generic Peripheral".  The entire mousepad lights up with whatever color I set the "Mouse/Headset" zone to (the 12 color zones cannot be treated independently).

**Comment by Wontell** [comment]
Will it be possible to add actual mouse pad configuration with zones? right now there is no mouse pad image in the configurator like there is for keyboard and mouse

**Comment by simon-wh** [comment]
@Wontell I'm currently working on reworking the device layout system which will allow for proper support of devices other than keyboards and mice, which means that I'll be adding the ability to properly light mouse pads

**Comment by Gurjot95** [comment]
Should work now.
