### ISSUE TITLE
Payday 2 Issue

### ISSUE THREAD

**Issue by patmanblu3** [antonpup/Aurora#844]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [X] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [X] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
RGB lighting
### Actual behavior:
Static lights
Explain here what happened instead.
Lighting doesn't react to anything, In the mods section it says the GSI mod is for an older BLT version so I'm guessing that's why its not working but I don't know.  I'd really like to get this working if possible. 
### How often does this problem occur?

This problem occurs... (Fill in here)
Every time
### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Launch Payday 2
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (Fill in here)
Latest version
### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
Going to let #1160 take over as the main issue for this as it's got helpful detail in it
