### ISSUE TITLE
Not starting with Windows.

### ISSUE THREAD

**Issue by RaPoZaUm** [antonpup/Aurora#845]
On Beta 0.6.1 dev3, even though I set it to Start with Windows, it does not.

**Comment by simon-wh** [comment]
Can you open Task Scheduler -> Task Scheduler Library and find "AuroraStartup". Can you check if it is enabled and if it is could you try running it to see what happens?

**Comment by RaPoZaUm** [comment]
It was pointing to the Program Files instalation (old version, not 0.6.1 dev3) and I correct it, but it says now Invalid Directory (something like this, my Windows isn't in ENG)

**Comment by simon-wh** [comment]
@RaPoZaUm Could you try deleting the entry in Task Scheduler and toggling the start with windows in Aurora?

**Comment by RaPoZaUm** [comment]
Yay! It worked now! Hopefully nothing breaks it...
