### ISSUE TITLE
Ajazz AK-33 keyboard support?

### ISSUE THREAD

**Issue by StarrHD** [antonpup/Aurora#847]
- [x] Aurora Wrapper
- [x] Aurora supported device, (Ajazz AK33 RGB)
- [x] Other, (no device support)

**Comment by diogotr7** [comment]
That keyboard has been discussed before here and as far as i know it doesn't have an sdk, so there is not much that can be done to support it.

**Comment by StarrHD** [comment]
do you mean this? (http://a-jazz.com.cn/download_en.aspx)

**Comment by simon-wh** [comment]
Duplicate of #756, #583, #505. Please use the search function before opening an issue.
