### ISSUE TITLE
"Aurora has stopped working" at boot or launch

### ISSUE THREAD

**Issue by Overfloow** [antonpup/Aurora#848]
[2017_30_10.log](https://github.com/antonpup/Aurora/files/1428536/2017_30_10.log)
### What are you experiencing an issue with?
- [x] Aurora Lighting issue

### What kind of an issue is it?
- [x] Crash

### Actual behavior:
When i boot or when I lauch aurora, aurora work properly (RGB profil is correctly loaded) but i have this crash report:

> https://img4.hostingpics.net/pics/662573auroraerror.png

When I click OK, aurora stop

### How often does this problem occur?
Every time

### Explanation
At first, Aurora worked perfectly, one day I left my computer on all day while I was at work for some downloads

When I returned to my computer, it was totally frozen, aurora took 100% use of my CPU.

I restarted my computer, uninstalled and reinstalled aurora.

Since, this error message appears at each startup or when I try to launch the application
.
I reinstalled the latest version of aurora and the previous version several times, and then tried to clone the git to the location indicated by the error message without success.

Sorry for my french and thanks in advance

**Comment by simon-wh** [comment]
Delete %appdata%/Aurora/Config.json
