### ISSUE TITLE
Destiny 2 support

### ISSUE THREAD

**Issue by Poolitzer** [antonpup/Aurora#849]
Does Destiny 2 has something like this? There is a .razerchroma file. Is this something Aurora supports?

**Comment by apintocr** [comment]
I've created a destiny2 color profile.
Feel free to improve it, contributions are welcome.
https://gitlab.com/apinto/aurora-profile-destiny2

**Comment by Poolitzer** [comment]
Holy Shit. that sounds amazing

Cant wait to try it

**Comment by apintocr** [comment]
![image](https://user-images.githubusercontent.com/1459530/32561650-aee808a4-c4a4-11e7-9331-58d1df54dc95.png)
@Poolitzer theres the color scheme.

**Comment by Poolitzer** [comment]
Uhh. It doesnt work at all :( Its just black

I have the 0.6.0b beta, do I need a newer version?

I did these steps: https://modworkshop.net/mydownloads.php?action=view_down&did=21126

**Comment by Poolitzer** [comment]
Thanks, work like a charm. I gonna test it tonigth :D

**Comment by Poolitzer** [comment]
I took the last release and followed the steps provided here:
https://modworkshop.net/mydownloads.php?action=view_down&did=21126

I copied your profile to my appdata folder and to the admin ones, cause I had to start Aurora as the admin.

**Comment by apintocr** [comment]
@Poolitzer great it worked!

**Comment by Poolitzer** [comment]
Sorry, it changed. You have to read again :(

**Comment by RaPoZaUm** [comment]
I'm using this profile on my G810 (the one from modworkshop) and everything works fine, except the Super.

**Comment by simon-wh** [comment]
Related to Razer Chroma support, does the lighting work if you apply the razer wrapper to the game directory (make sure you don't have any profile for Destiny when testing this)?

**Comment by luxiel** [comment]
Hey!
So, I just tried to use this profile, had the Razer Chroma wrapper installed in the same folder the game's .exe is, and still no luck at all...Keyboard, mouce and headset just go black.

Keyboard: Corsair K70 LUX RGB
Headset: Corsair VOID Wireless
Mouse: Razer Naga Chroma

**Comment by diogotr7** [comment]
I extracted the razerchroma file (burningtower.razerchroma) and got 2 xml files, one containing this:

https://pastebin.com/f19wcgM7

And [this](https://github.com/antonpup/Aurora/files/1518362/BURNING_TOWER_README.pdf) pdf

**Comment by simon-wh** [comment]
The razer chroma file must be a profile that you can import that doesn't actually have any interaction with the game's data. In that case, direct yourself to the custom profile that was made and linked above.
