### ISSUE TITLE
Not all keys can be controlled on the Logitech G810

### ISSUE THREAD

**Issue by Destructive55AZ** [antonpup/Aurora#854]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [G810 ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [Does not control certain keys ] Other, (Fill in another type of issue here)

### Expected behavior:
All keys are controlled via aurora, 
### Actual behavior:
the multimedia keys, game mode key, lock indicators and the \| key all do not register and are stuck

### How often does this problem occur?

This problem occurs... 100% of the times

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Use G810 with Aurora
2. Select all in gradient or something like that
3. Notice how the keys listed above are stuck in the color last used by logitech software or default.

### What is the version of Aurora you are experiencing this issue with?

My version is... (v0.6.0b)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
The SDK does not allow you to modify the lighting on those keys.
