### ISSUE TITLE
Back up all settings and profile ect

### ISSUE THREAD

**Issue by MIk3ut** [antonpup/Aurora#855]
Does anyone know if its possible to backup all you setting and profiles? its taken me ages to set it all up and dont want to do it again if I have to format sometime in the future.

Also thank you so much for creating this wonderful software, very much appreciate the work you have done its truly amazing

**Comment by diogotr7** [comment]
Just backup this folder:

C:\Users\User\AppData\Roaming\Aurora

**Comment by MIk3ut** [comment]
Thanks buddy thats great
