### ISSUE TITLE
Aurora stop working

### ISSUE THREAD

**Issue by ETHUNNAR** [antonpup/Aurora#858]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [x] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
My aurora profile starts on my keyboard
### Actual behavior:
Explain here what happened instead.
My profile does not show on my keyboard
### How often does this problem occur?

This problem occurs... (every time for the past week or two)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. 
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (Beta v0.6.1-dev3)

### Does the previous version of Aurora have this issue?
The previous version, (just start using Aurora), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
Could you post your log file or some sort of error?

**Comment by ETHUNNAR** [comment]
not really my led lights from Aurora just doesn't show

**Comment by simon-wh** [comment]
You gotta be more specific. What device are you using? Did you follow the setup steps for the device? If the lighting isn't working and you have correctly set it up then without the log I can't do anything, you can find it by going to Settings -> Debug and pressing "Open Logs folder"

**Comment by ETHUNNAR** [comment]
im using a logitech 810 and what whould i do when i open the log folder

**Comment by simon-wh** [comment]
You upload the log file with the current date using pastebin.com

**Comment by ETHUNNAR** [comment]
https://pastebin.com/gR0Fwgid

**Comment by simon-wh** [comment]
It shows that the Logitech device is being initialised in the log without any errors. However, there are some errors related to the Volume overlay (which have been fixed already in the dev branch), could you try disabling the volume overlay to see if it makes a difference?

**Comment by ETHUNNAR** [comment]
how do i do that

**Comment by ETHUNNAR** [comment]
i just did it and it made no difference

**Comment by simon-wh** [comment]
Are you able to control the lights on your G810 through LGS?

**Comment by ETHUNNAR** [comment]
yes

**Comment by simon-wh** [comment]
Is it a case where you see lighting on the virtual keyboard but it doesn't display on your keyboard?

**Comment by ETHUNNAR** [comment]
no i see the lighting from the LGS but not from Aurora virtuel or on my keyboard

**Comment by simon-wh** [comment]
Does it definitely show that Logitech is connected in Settings -> Device Manager?

**Comment by ETHUNNAR** [comment]
![image](https://user-images.githubusercontent.com/33461453/32618090-ff1d933e-c576-11e7-9045-697113e14090.png)

**Comment by simon-wh** [comment]
@ETHUNNAR I'm really confused why it isn't working, could you try reinstalling LGS?

**Comment by ETHUNNAR** [comment]
me too. I just reinstalled LGS but it still dosen't work

**Comment by the27club** [comment]
I believe I am having the similar issue. Anytime I open Aurora, it just shows the keys as a stationary color on my G910. If I close Aurora, it goes back to LGS lighting and works fine. Open Aurora again, and the colors stay stationary again. This did not happen the last version and I am using the latest version.

**Comment by simon-wh** [comment]
@the27club Are the lights updating on the virtual keyboard on Aurora, but not on your physical keyboard? Also, what version are you using? v0.6.1-dev4?
