### ISSUE TITLE
Logitech 910 Spectrum

### ISSUE THREAD

**Issue by FilthyBoy** [antonpup/Aurora#861]
I cannot find the instructions for first time setup for the logitech keyboard and that is causing issues with games like overwatch.

**Comment by Bloodcloak** [comment]
To get the first time setup instructions
Open aurora, click on the blue gear in the bottom left corner of the window. Then click on the "Devices & Wrappers" tab. There you should see a button that says "View First-time instructions for Logitech". That should then open another window with instructions on how to set up aurora with Logitech Gaming Software.

Once you are done with the setup. You may need to go back to the "Devices & Wrappers" tab mentioned before and select the "Logitech - G910" option in the "preferred keyboard" drop down menu for the lighting to work.

Still doesn't work? Try clicking the "Install Aurora Wrapper Patch for Logitech" button in the "Devices & Wrappers" tab.

If that doesn't work, could you be more specific on the issues you are encountering?

**Comment by FilthyBoy** [comment]
Thank you for replying, The issue I am encountering with overwatch is that while in a spawn room the keys used in game flicker and once I leave a spawn room, the lights on the keys shut off all together

**Comment by simon-wh** [comment]
What does it show in Aurora (using the debug window) when playing Overwatch? Also, what version are you running and could you try to reinstall the razer wrapper?

**Comment by FilthyBoy** [comment]
![aurora-overwatch](https://user-images.githubusercontent.com/33529581/32700882-8a586086-c799-11e7-8d99-96053869b436.jpg)
I am running beta v0.6.0b, this problem only occurs in overwatch so far, when i use the program while browsing the internet the colors are fine

**Comment by simon-wh** [comment]
@FilthyBoy You could try the [latest development release](https://github.com/antonpup/Aurora/releases) to see if it makes a difference? (You should also reapply the wrappers)

**Comment by FilthyBoy** [comment]
That did it, thank you so much for your help

**Comment by simon-wh** [comment]
Awesome, I'll hopefully push out another dev release pretty soon to try and get some necessary fixes out there.
