### ISSUE TITLE
[SOLVED] Aurora League of Legend Profile overrides everything

### ISSUE THREAD

**Issue by tr0teK** [antonpup/Aurora#862]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
After uninstalling Aurora it should not switch anymore to League of Legends profile

### Actual behavior:
Everytime I boot up my pc or shut it down it always switches to the League of Legends settings (even tho I have uninstalled Aurora and even changed the Lightning Settings. Same issue when I go into a Linux destribution. this damn league of legends profile is ALWAYS active

### How often does this problem occur?

This problem occurs... everytime

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Activate League of Legends Profil
2. Optional maybe: install the league of legends thing in options
3. restart pc and see how the lightning always switches to that light setting

### What is the version of Aurora you are experiencing this issue with?

My version is... the latest one

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.
yes

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by Dioburando** [comment]
i have ni idea but did you delete the patch in league i mean the light fx thing

**Comment by tr0teK** [comment]
There is no uninstall light fx patch. Also the patch is beeing installed into the game folder and the bug has nothing to do with any application. the lightning issue I have always happens when the Keyboard is loading anything, starting up or whatever. it always switches to that months old profile i made which I already deleted and never used again. It also is active in any Linux OS or BIOS or whatever.

**Comment by diogotr7** [comment]
Try to press the lightning key and numbers at the same time. That's the hardware combination to change color patterns. You can also press lightning and +/- to change the speed of the effects.

**Comment by tr0teK** [comment]
I have the Corsair K70 Lux not sure if I can do that.

**Comment by tr0teK** [comment]
I made some screenshots to show you how it looks like:

When i switch bios mode, turn pc on or off, close corsair utility engine or uninstall the drivers completely:
https://i.imgur.com/ApX5wIP.jpg

When I put it into the Steam Link:
https://i.imgur.com/r7SQPk9.jpg

When I boot up Linux and use that:
https://i.imgur.com/aUSfLy2.jpg

It seems like that old profile I made in Aurora for League of Legends has burned itself into the Corsair K70 Lux keyboard and I can't seem to get rid of it.

**Comment by diogotr7** [comment]
Oh, I'm sorry. I assume people have the same hardware as me...

Anyway, my keyboard doesn't have a flash memory but probably yours does. I don't know how to change it but wouldn't CUE alow you to do that?

My mouse has 2 modes: Flash memory and Computer-stored profiles; maybe there's something like that for corsair?

Sorry I'm not helping much but I don't own any corsair devices.

**Comment by tr0teK** [comment]
I checked CUE and didn't see any flash mode. I tried forcing the newest firmware update on the keyboard but it didn't change anything. But how is it possible that Aurora flashes the league of legends profile on my keyboard memory ?
