### ISSUE TITLE
Aurora Overwatch not working?

### ISSUE THREAD

**Issue by Rekcuf97** [antonpup/Aurora#865]
### What are you experiencing an issue with?

- [ ] Aurora
- [ x] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ x] Other, (Nothing happens)

### Expected behavior:
I believe the keyboard is supposed to light up WASD and keys that are supposed to be used

### Actual behavior:
Nothing happens, with the keyboard being blank with no leds turned on.

### How often does this problem occur?

This problem occurs... Never worked

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. 
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... Latest

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by FHeilmann** [comment]
Did you go into a practice session? In my experience the lighting doesn't come up until the first game is joined. Also did you patch the Overwatch synapse DLLs?

**Comment by Rekcuf97** [comment]
Yes i have patched overwatch as stated. Also had tried it in a game but still no change

**Comment by simon-wh** [comment]
Could you post your logs to see if there are any issues showing up in that?

**Comment by Rekcuf97** [comment]
Hi, it started working. Thanks for the replies!
