### ISSUE TITLE
Not starting with windows at any cost

### ISSUE THREAD

**Issue by mmateusu** [antonpup/Aurora#868]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [x] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Startup with the computer and does not show in the initializate tab

### Actual behavior:
Not starting with windows

### How often does this problem occur?
All the time

### What is the version of Aurora you are experiencing this issue with?
beta v0.6.1-dev3

### Does the previous version of Aurora have this issue?
don't know

### Please include any logs, screenshots, or files that are related to this issue:
https://imgur.com/a/HMSUe

**Comment by diogotr7** [comment]
It should be starting with the task scheduler, as that allows starting with administrator previleges.

If you want to add aurora to the task manager startup tab, add a registry key here:

HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run

DISCLAIMER: I don't know if this works, maybe @simon-wh could verify

**Comment by simon-wh** [comment]
Can you open Task Scheduler, click on Task Scheduler Library on the left and try and find the "AuroraStartup" task and see if it is enabled? If it is could you try running it and see if it works?

**Comment by mmateusu** [comment]
I tried to run it and nothing happens, i saw an error that said that the location was wrong, i fixed the location and nothing happens again

**Comment by mmateusu** [comment]
So, i did what @diogotr7  said and that actually adds the aurora to task manager.

**Comment by simon-wh** [comment]
@mmateusu Using the Task Scheduler isn't supposed to add it to the task manager, it needs to run under the task scheduler so it can run as admin, it will not start on windows using the registry method as it will not run it as admin.

**Comment by mmateusu** [comment]
So, what do i do?

**Comment by simon-wh** [comment]
@mmateusu You need to get the Task scheduler method to work. You can try and delete the entry in the Task Scheduler for aurora and toggle the option in Aurora for starting with Windows and it should recreate it with the correct information. Once it has created it again try to start the task to see if it works.

**Comment by mmateusu** [comment]
So, im sorry for taking this long i was doing some work for college, and, yeah, that solution worked, i deleted the task from task scheduler and he created another one brand new and working, i dunno what happened to make that one bug but its working now, thanks
