### ISSUE TITLE
Gigabyte RGB Fusion Support

### ISSUE THREAD

**Issue by wanildopneto** [antonpup/Aurora#873]
I don't have any issues with this app.

I just want to know if it you guys could add support for Gigabyte's RGB Fusion.
Here's the SDK:
https://www.gigabyte.com/mb/rgb/sdk

**Comment by Cheddaz** [comment]
Will this ever be compatible? I’m sure plenty others are anticipating this as well.

**Comment by simon-wh** [comment]
@Cheddaz I'm going to be working on big changes after my exams which will allow for control of devices other than keyboards & mice

**Comment by vincentoliviers** [comment]
any news on this ?

**Comment by Alia5** [comment]
The Gigabyte Fusion SDK also provides support for their laptops.
I recently got one and could provide testing and debugging.

Due to my lack of knowlegde in C# and of the Project, I cannot do the initial implementation and the native DLL-wrapper, though.

**Comment by wlanowski** [comment]
> The Gigabyte Fusion SDK also provides support for their laptop keyboards
> I recently got one and could provide testing and debugging.
> 
> Due to my lack of knowlegde in C# and of the Project, I cannot do the initial implementation and the native DLL-wrapper, though.

@Alia5 Do you know, whether the SDK supports laptop keyboards like those of the AERO-15-Series?

**Comment by Alia5** [comment]
I have an Aero-15 here ;)
Afaik it does.

**Comment by wlanowski** [comment]
I wrote to the support of GIGABYTE. The answer was, that it is not supported...

But maybe they even dont know their own tool. In the documentation of the SDK i can't find anything about our Aeros.

**Comment by Wontell** [comment]
I would also like to request Gigabyte RGB support, especially to be able to use Razer Chroma to Control Gigabyte motherboard RGB

**Comment by KmuTech** [comment]
I want RGB fusion support too.

**Comment by Jnss98b** [comment]
Any news on this?

**Comment by wlanowski** [comment]
Unfortunately I do not believe, that GIGABYTE SDK is compatible with AERO-keyboards. I cant find any hints on keyboard-support in the SDK-documentary and examples. Additionaly the linked [RGB fusion tool](https://github.com/tylerszabo/RGB-Fusion-Tool) can not find my AERO-keyboard.

I have no idea about configure the AERO-keyboards through terminal/command line...

**Comment by Jnss98b** [comment]
Damn it Gigabyte! You had one job.

**Comment by SuperSandro2000** [comment]
I am more interested in linking my motherboard to my Razer keyboard and mouse.

**Comment by Jnss98b** [comment]
Well, the RGB Fusion sdk does cover the motherboard so you should be fine when Aurora utilizes the sdk

**Comment by MaxPainNL** [comment]
Please add this feature so I can use Razer Synapse with my motherboard and ram

**Comment by ScottNorton** [comment]
I'm stopping in to voice support for RGB Fusion support! The AORUS eGPU box would look neat synchronized with my Razer Orochi on my win 10 tablet gaming rig

**Comment by brugvp** [comment]
Also stopping by to support the addition of RGB Fusion. Would be an awesome feature. Would even like to donate to the project if it helps developers. You're doing what no brand is doing properly. Unified RGB all the way

**Comment by Cheerpipe** [comment]
Try this

https://github.com/Cheerpipe/RGBFusion390SetColor

Working on a Z390 Aorus Master. Should work on any RGBFusion compatible hardware.

**Comment by Tavisco** [comment]
+1 on this!

**Comment by mikedmor** [comment]
+1
RGB Fusion is pretty trash, I would love to see another open sourced tool get integrated into Aurora so that i could finally get my gigabyte motherboard to sync with the rest of my RGB and would gladly donate to get this going.

**Comment by Cheerpipe** [comment]
> +1
> RGB Fusion is pretty trash, I would love to see another open sourced tool get integrated into Aurora so that i could finally get my gigabyte motherboard to sync with the rest of my RGB and would gladly donate to get this going.

Try https://github.com/Cheerpipe/RGBFusion390SetColor

Working pretty well with a scripted device.

**Comment by brugvp** [comment]
Sorry I'm a total noob. I don't know how to use it with aurora. My Aurora folder don't have a scripts/devices, so I've created it and placed the script there but it didn't show up in device manager... Am I doing something wrong?

**Comment by Cheerpipe** [comment]
> Sorry I'm a total noob. I don't know how to use it with aurora. My Aurora folder don't have a scripts/devices, so I've created it and placed the script there but it didn't show up in device manager... Am I doing something wrong?

You have to put RGBFusion390Sender.dll in Aurora folder.

![image](https://user-images.githubusercontent.com/972765/69385045-dec36400-0c9c-11ea-8edf-21d32d24e680.png)

**Comment by mikedmor** [comment]
I gave that a try myself but it doesnt seem to appear in the Device Manager. I just placed RGBFusion390Sender.dll in my Aurora folder, then restarted Aurora. Is there something else i need to do?

**Comment by Cheerpipe** [comment]
Put RGBFusion390Sender.dll in Aurora folder and RgbFusionNative.cs in Aurora\Scripts\Devices\

If Aurora does not show RGB Fusion in Device Manager, upload your aurora log files.

**Comment by mikedmor** [comment]
That worked for me, I now see the RGB Fusion MB Direct. It doesn't seem to work reliably though. After getting it working and playing around for a minute it stopped and returned back to its defaults. Definitely seems like progress though!

**Comment by mikedmor** [comment]
Figured i would share some more info. I found out that after reboot i was able to reliably getting it to start working again by running 

`RGBFusion390SetColor --areas`

After that Aurora began to sync with my x570 Gigabyte motherboard and all the RGB attached to it. Hopefully that helps out some, let me know if you need anything else. Thank you @Cheerpipe!

**Comment by Tavisco** [comment]
Very noob question²: RGB Fusion is appearing as a device on Aurora, but, how to use it? By default it only turned off all LEDS.

**Comment by Tavisco** [comment]
Oooh, analysing the code was able to determine that all motherboards LEDS are bound to G1 key, so, applying effects to it affects the board color. Neat!

**Comment by Cheerpipe** [comment]
> Figured i would share some more info. I found out that after reboot i was able to reliably getting it to start working again by running
> 
> `RGBFusion390SetColor --areas`
> 
> After that Aurora began to sync with my x570 Gigabyte motherboard and all the RGB attached to it. Hopefully that helps out some, let me know if you need anything else. Thank you @Cheerpipe!

Forget to mention that my tool have to be running in background and Gigabyte rgbfusion should be opened at least one time to build areas database.

You can load RGBFusion390SetColor without any command line parameter.

**Comment by sashayohan** [comment]
I added the file to the startup
Hkey_Local_Machine → SoftWare → Microsoft →Windows → Current Version → Run
"C:\Program Files (x86)\GIGABYTE\RGBFusion\RGBFusion390SetColor.exe"

**Comment by csutorasr** [comment]
What about [this](https://github.com/tylerszabo/RGB-Fusion-Tool)?

**Comment by XenHat** [comment]
I've made a self-extracting archive of the tool written by @Cheerpipe for anyone who needs it.
It includes the files which are still compatible with the AUROS X570 Master (the new CS file doesn't work for me).

[RgbFusionNative-0.0.2-sfx.zip](https://github.com/antonpup/Aurora/files/4270115/RgbFusionNative-0.0.2-sfx.zip)

**Comment by JonathanSamelson** [comment]
Hi there,

I have an issue when using RGBFusion390SetColor. When it sets a color to the motherboard, for instance with the default profile from desktop, I've got many error messages like this: 
![image](https://user-images.githubusercontent.com/19322574/77256031-ed7e4f80-6c6b-11ea-93c2-7509b404408d.png)


In device tab I have this:
![image](https://user-images.githubusercontent.com/19322574/77256015-d2abdb00-6c6b-11ea-9c68-564d0ce35519.png)

Does anyone got the same issue? SetColor works fine in command line.

**Comment by DunKalevra** [comment]
> Hi there,
> 
> I have an issue when using RGBFusion390SetColor. When it sets a color to the motherboard, for instance with the default profile from desktop, I've got many error messages like this:
> "Wrong --setarea: command in GetLedCommands: {ex.Message)"
> 
> In Device Manager tab I have this:
> ![image](https://user-images.githubusercontent.com/19322574/77256015-d2abdb00-6c6b-11ea-9c68-564d0ce35519.png)
> 
> Does anyone got the same issue? SetColor works fine in command line.

This error is caused when the modeIntegrated, modeAnalog and modeDigital goes to a value above what is supposed to, and that happens when Aurora assigns a color to the G6 key. If you see in the RgbFusionNative.cs script, the G6 key is used to pass the values so you can choose the mode. If you, for example, assign a color R=1, G=1 and B=1, you will be passing the mode "Breath" to the integrated, analog and digital pins.

To make it work with the other profiles that assign the G6 key to some color by default I edit the lines where it assign the G6 key to this:
`else if(key.Key == DeviceKeys.G6)
                {
					modeIntegrated = key.Value.R;	
					if (modeIntegrated > 11)
						modeIntegrated  = 0;
					modeAnalog = key.Value.G;
					if (modeAnalog > 11)
						modeAnalog  = 0;
					modeDigital = key.Value.B;
					if (modeDigital > 11)
						modeDigital  = 0;
                }`

Hope it helps.

**Comment by Cheerpipe** [comment]
> To make it work with the other profiles that assign the G6 key to some color by default I edit the lines where it assign the G6 key to this:

Thanks, i reworked the scripted device for better compatibility. It should out of the box now.

**Comment by Cheerpipe** [comment]
> What about [this](https://github.com/tylerszabo/RGB-Fusion-Tool)?

It does not work with newer mainboards like aorus z390 and wont work smoth with aurora and animated modes.

**Comment by TheRealBrownie** [comment]
I don't see RGB Fusion in the Device Manager. I put RGBFusion390Sender.dll in the Aurora Folder and RGBFusion390SetColor.exe in the RGBFusion Folder.
Am I doing something wrong?

**Comment by TheRealBrownie** [comment]
> > I don't see RGB Fusion in the Device Manager. I put RGBFusion390Sender.dll in the Aurora Folder and RGBFusion390SetColor.exe in the RGBFusion Folder.
> > Am I doing something wrong?
> 
> You also need to put RgbFusionNative.cs in Aurora\Scripts\Devices\
Now i did that aswell, but still not seeing it in the Device Manager...

**Comment by Cheerpipe** [comment]
Shoud be something in your log files. 

Ussualy on C:\Users\<USERNAME>\AppData\Roaming\Aurora\Logs

**Comment by TheRealBrownie** [comment]
[2020-04-27 17.09.03.log](https://github.com/antonpup/Aurora/files/4540437/2020-04-27.17.09.03.log)

**Comment by lewinernst** [comment]
Hi everyone - the tool works in powershell for me and the device manager shows both the z390 version and the .cs posted in this thread as connected if i add them. However, i can't find where i can control the device in aurora - it still only shows mouse and keyboard.

**Comment by Cheerpipe** [comment]
> Hi everyone - the tool works in powershell for me and the device manager shows both the z390 version and the .cs posted in this thread as connected if i add them. However, i can't find where i can control the device in aurora - it still only shows mouse and keyboard.

Hi.

My scripted device takes color from G6 key (i am using Logitech G910 profile profile with a G915 and ude G6 key to set the color of the mainboard).

foreach (KeyValuePair<DeviceKeys, Color> key in keyColors)
            {
                //Iterate over each key and color and send them to your device
				if(key.Key == **DeviceKeys.G1**)
                {
                    //For example if we're basing our device color on Peripheral colors
                    SendColorToDevice(key.Value, forced);
                }
            }
You can change this to whatever key you want) or use DeviceKeys.Peripheral_Logo to sync your motherboard with your mouse.

**Comment by lewinernst** [comment]
> You can change this to whatever key you want) or use DeviceKeys.Peripheral_Logo to sync your motherboard with your mouse.

Awesome-it's working now. One thing i noticed though is that when setting 255 0 255 for example it matters what color was previously set. If it comes from one color it will be purple, from another pink.
Also - have you tried assigning each zone to one key to enable mobo-wide effects yet? What about about setting a wave effect from aurora - is that possible? 
If youre interested i would be up for some dms and integrating that functionality.

**Comment by Cheerpipe** [comment]
> > You can change this to whatever key you want) or use DeviceKeys.Peripheral_Logo to sync your motherboard with your mouse.
> 
> Awesome-it's working now. One thing i noticed though is that when setting 255 0 255 for example it matters what color was previously set. If it comes from one color it will be purple, from another pink.
> Also - have you tried assigning each zone to one key to enable mobo-wide effects yet? What about about setting a wave effect from aurora - is that possible?
> If youre interested i would be up for some dms and integrating that functionality.

Yes, you can bind different keys to different zones using the first parameter of the --sa command:

--sa:1:{3}:{0}:{1}:{2} == zone 1 of your mainboard
--sa:2:{3}:{0}:{1}:{2} == zone 2 of your mainboard
--sa:n:{3}:{0}:{1}:{2} == zone n of your mainboard

Just use different keys for different zones.

I recommned you to crete a buffer with keys you want to use and create a single request to RGBFusion with all color changes instead of create multuple scripted devices.

**Comment by lewinernst** [comment]
> I recommend you to create a buffer with keys you want to use and create a single request to RGBFusion with all color changes instead of create multiple scripted devices because it uses SMBus and is not very fast and don’t play well with simultaneous calls

Guess you were entirely right about this one, it goes completely horrific but if i don't create separate devices i can only check if one of the colors has changed since `device_color` only allows for a single value. Have you looked into integrating it as its own device with multiple "keys" yet?

Thanks so much for your help btw.

**Comment by Cheerpipe** [comment]
> > I recommend you to create a buffer with keys you want to use and create a single request to RGBFusion with all color changes instead of create multiple scripted devices because it uses SMBus and is not very fast and don’t play well with simultaneous calls
> 
> Guess you were entirely right about this one, it goes completely horrific but if i don't create separate devices i can only check if one of the colors has changed since `device_color` only allows for a single value. Have you looked into integrating it as its own device with multiple "keys" yet?
> 
> Thanks so much for your help btw.

Yes, i want to implement some kind of transaction feature to set color for diffetent areas but with just one command.

I already have this feature working in my NZXT HUE Ambient led strip. My idea is to have some like his.

Controller.TransactionStart();
Controller.TransactionSet(zone1,color1) ;
Controller.TransactionSet(zone2,color2) ;
Controller.TransactionSet(zone3,color3) ;
Controller.TransactionSet(zone4,color4) ;
Controller.TransactionCommit();

So you can set bind different keys to different zones and commit the led transaction with the last key.

I will also check if leds are really changed and apply new colors only to those leds with new colors to speedup the wrapper. Maybe this weekend.

The truth is i am not a real developer. Sorry if my software is not perfect or developed slowly.

**Comment by lewinernst** [comment]
Hi, i actually made a small tweak which allows for the motherboard to do a full rainbow effect running through the different zones of the mobo - working on a pull request to your repo right now, but struggling with the spanish 😅😅

**Comment by Cheerpipe** [comment]
Transaction mode is ready. It allows you set colors per area with just one setcolor operation and decent tramerste. Did you use it?

What a have to dig in is figure out how to control individual lights on the argb strips.

**Comment by lewinernst** [comment]
I did submit a pull request based on your latest commit, maybe we can continue this talk on the pull request https://github.com/Cheerpipe/RGBFusionCli/pull/10

**Comment by DonavanElian** [comment]
Is the rgb fusion working with the aurora project?

**Comment by DonavanElian** [comment]
I tried to install but I'm not getting

**Comment by Mitonix** [comment]
Where can I get RGBFusion390Sender.dll?

**Comment by Mitonix** [comment]
I use the Gigabyte Z370 Aorus Gaming 5, but I can't change the colors of the motherboard. In addition, a connection to RGB Fusion is displayed under the Device Manager. What could be the reason for this?

**Comment by Cheerpipe** [comment]
Can you try this build?

https://ci.appveyor.com/project/antonpup/aurora/builds/33231558

**Comment by Mitonix** [comment]
I have already tested the build.

![Aurora 2](https://user-images.githubusercontent.com/63264821/83410790-58d86080-a417-11ea-9813-013b8d61888b.PNG)

**Comment by Cheerpipe** [comment]
Hi. Thanks for your bravery :D.

Is it working for you?

What motherboard are you using?

How are working yor leds? 

Is there any artifact or glitch in your lights? 

Changes are slow or fast? Dis you try some animated mode?

Are colors for separate areas working.

Thanks again.

**Comment by arthurbernardodonascimento** [comment]
Hello, I don't know how to install the software?

Motherboard: H370 AORUS GAMING 3

**Comment by Cheerpipe** [comment]
Try installing this versión and report back.

https://ci.appveyor.com/project/antonpup/aurora/builds/33980785/artifacts

**Comment by arthurbernardodonascimento** [comment]
![Sem título](https://user-images.githubusercontent.com/69159918/89203771-81054c80-d58b-11ea-8f78-fcda221b3a53.png)

Just click start, right?

**Comment by Cheerpipe** [comment]
First, select a keyboard and mouse in "Device & Wrappers" Tab, then Start RGBFusion Device in "Device Manager" tab.

It is important to note than RGB Fusion must be installed but not running so kill any instance of RGBFusion.exe.

**Comment by arthurbernardodonascimento** [comment]
![Capturar](https://user-images.githubusercontent.com/69159918/89205939-e73f9e80-d58e-11ea-8aa7-75e3710b5be9.JPG)

It worked !

Motherboard: N370 AORUS GAMING 3

Leds: are working

Defect: none

Thank you very much

**Comment by csutorasr** [comment]
Is this working with Aorus X570? Where can I find RGBFusion390Sender.dll?

**Comment by ReeSilva** [comment]
It almost works like a charm, but my XPG SSD and RAM are not lightning. TBH, the RAM module is on just one led. I'll try to understand the code to see how can I help. But, if anyone faced this issue and have tips to give, I'll accept :D

EDIT: Nevermind, I found out an way. For those who wants to know how to fix, you have to set up a different profile for each hardware on RGB Fusion Software. If you setup a single profile that updates everything (i.e., game) it will not work.

**Comment by Iahrons** [comment]
Hello, I have a B450  AORUS ELITE and tried my best (pasting files) and got nothing. 

I want to use aurora with my MB and other stuff and cant find the proper files (dll and others).

Tks in advance

**Comment by enlight3d** [comment]
Hey, tried 3 differents builds that I found on this issue (and reinstalled the rgbfusion version provided here too) and can't get it working with my mobo. I have an aorus z370 gaming 5. Would be really happy to make this work just as @Ashudu managed to make the gaming 3 work ! Also, thing to note is that on latest build, if I enable rgbfusion, I get like 300ms reported of delay !

**Comment by Knutura** [comment]
How do I download

**Comment by Bf2multi100** [comment]
I too am confused. 

I tried everything, but im missing something. 

I need help getting the RGBfusion module installed....

I have everything working but my mobo, and it looks awesome so far!

**Comment by Bf2multi100** [comment]
For anyone checking this thread in the future.

Ive compiled the updated code from CheerPipe, and produced my own Fork on the project to simpler setup process that works with the original code.


I was so confused by the original setup documentation, it did NOT include any EXE or any direct instructions besides, place EXE in this folder, but EXE was not compiled and found in the master project.


Anyways, ive solved my own frustration with the delay on this response, and compiled the visual C## code, and made the EXE myself.

After trial and error, im happy to say, as long as the RGBFusionCLI.exe program is running, Project aurora is properly updating my Z39 aorus pro gaming motherboard, and 2 front RGB fans properly. 

I have only 1 snag, which is im having trouble getting RGBFusionCLI to auto start with windows and Aurora, ill work on that and report back if needed.

This is NOOOTT an april fools joke, here is a screenshot of aurora and my task manager (i use malwarebytes and EXE is not a virus) of RGBFusionCLI working as intended.

Here is my fork of the project, with updated directions to make it easier for hopefully ANYONE looking to get this working as intended.

https://github.com/Bf2multi100/RGBFusionCli

![RGBFusionCLI and task manager proof](https://user-images.githubusercontent.com/77888222/113293778-cebd8a80-92bb-11eb-9b82-1678715c7bf1.jpg)

**Comment by Bf2multi100** [comment]
> How do I download

Check the last link ive sent, it should help you with my fork ive added.

https://github.com/Bf2multi100/RGBFusionCli

**Comment by pironic** [comment]
> Where can I get RGBFusion390Sender.dll?

https://github.com/Cheerpipe/RGBFusion390SetColor/releases/download/0.0.4/RGBFusion390SetColor_v0.0.4.zip 

I know it's late but i found this thread based on a google hit... so i wont be the last.
