### ISSUE TITLE
Memory Leak. Possibly related to Skype Integration

### ISSUE THREAD

**Issue by daveb778** [antonpup/Aurora#874]
I'm on version v0.6.1-dev3 and i've noticed that when im running fornite the app just start eating ram and the icon from the taskbar disappears as well.
![image](https://user-images.githubusercontent.com/18433196/32993619-aa928af4-cd28-11e7-83d4-aad1eb0ca211.png)

**Comment by simon-wh** [comment]
Could you provide your log file from when this occurred?

**Comment by daveb778** [comment]
What's the name of the log file, im in the app directory but i dont see one.

**Comment by diogotr7** [comment]
C:\Users\User\AppData\Roaming\Aurora\Logs

**Comment by daveb778** [comment]
Ok here you go.
[2017_11_19.log](https://github.com/antonpup/Aurora/files/1485843/2017_11_19.log)

**Comment by daveb778** [comment]
So it turns out its not only fortnite causing it other games are too.

**Comment by daveb778** [comment]
I just went back and tried dev2 and its just eating memory with no games open. It turns out it seems to be an issue with the skype integration addon, once ive turned these options off that seemed to fix it.
![image](https://user-images.githubusercontent.com/18433196/33236640-baf8b054-d227-11e7-99ca-dfe1fa613c2b.png)
Then my ram usage becomes stable.
![image](https://user-images.githubusercontent.com/18433196/33236642-d14fe4d0-d227-11e7-9ca3-3b8e71ca00fa.png)

**Comment by diareuse** [comment]
Can confirm that it was happening with no apps open and no particular overlay set on pre-dev4.
Been testing dev4 for a two weeks now and no leaks [OOMs] appeared whatsoever having the same profile and playing same games as before.

I had Skype integration disabled from the beginning.

**Comment by simon-wh** [comment]
@daveb778 I can't replicate an increase in memory usage with the Skype integration enabled, I always have it enabled and I've left it on for a while and had no issues. Could you try dev4 or the [latest build](https://ci.appveyor.com/project/antonpup/aurora/build/artifacts) and tell me if you still experience the issue?
