### ISSUE TITLE
Game Factorio support

### ISSUE THREAD

**Issue by itzandroidtab** [antonpup/Aurora#878]
Could you guys add support for the game Factorio? Sinds it has razer Chroma support sinds the new update.

Version: 0.15.38
Date: 24. 11. 2017
  Features:
    - Added Razer Chroma and Razer Chroma Link support (https://www.razerzone.com/chroma)

**Comment by Mavi222** [comment]
Came here to ask the same. http://steamcommunity.com/games/427520/announcements/detail/1460718682944077082 here is an announcement link (the keyboard light is at the bottom)

**Comment by simon-wh** [comment]
Try applying the razer wrapper to the game directory

**Comment by itzandroidtab** [comment]
After I applied the razer wrapper only the mouse seems to work 
(Corsair Sabre RGB). My keyboard turns off the LED's and doesn't do anything (Corsair K70).

![screenshot_aurora](https://user-images.githubusercontent.com/9889898/33392824-7a323f36-d53d-11e7-9285-5bc3857ca52d.png)

**Comment by MortnMX** [comment]
I would like the same. I'm using Logitech G910.
How can I apply the razor wrapper?
Are there any other news?

**Comment by Wuestengecko** [comment]
Hi, same issue as itzandroidtab - after applying the Razer wrapper patch to

    ...\SteamApps\common\Factorio\bin\x64

the keyboard just stays black when starting the game.

Interestingly, both with and without the wrapper patch applied, Aurora's keyboard bitmap window shows the mouse/peripheral in Factorio's orange when the game window has focus (everything else is black). This results in the mouse being lit in said orange when the wrapper patch is applied (as the game seems to be unable to connect to Aurora at all), or when Aurora has higher priority than Factorio in the Synapse settings. I do not have any profile for Factorio, in fact this happens after clearing the %appdata%\Aurora folder.

Note that the RzChromaSDK.dll and RzChromaSDK64.dll do NOT exist in a fresh Factorio install (i.e. without wrapper patch).

Aurora 0.6.1-dev3
Factorio 0.16.6-experimental
Devices: Razer Blackwidow Chroma keyboard, "Generic peripheral" (actually a Razer Naga Hex V2)

@MortnMX you can apply the wrapper to any game from within Aurora by going to settings (gear icon) -> Devices & Wrappers -> Install Aurora Wrapper Patch for [technology]

**Comment by simon-wh** [comment]
I don't own the game but plan to get it and will try and sort this out.

**Comment by keentom** [comment]
I got it to work once but after I tried to find out how to tell you guys it doesnt anymore.
Any ideas?

**Comment by pfgithub** [comment]
By default there seems to be a file called `ChromaAppInfo.xml` containing this if it's useful:

```xml
<?xml version="1.0" encoding="utf-8"?>
<application>
    <title>Factorio</title>
    <description>Factory building game.</description>
    <author name="Factorio" contact="https://www.factorio.com/"/>
    <device_supported keyboard="1" mouse="1" headset="1" mousemat="1" keypad="0" chromalink="1"/>
	<category game="1">
</application>
 
```

**Comment by Iruberiam** [comment]
Any news on this? I'm using v0.6.1-dev4-344, installed the wrapper to the game directory and the game doesn't appear to be affecting the keyboard. I created a profile for Factorio and the keys display as specified by Aurora the game triggered events don't get shown. I'm on a Logitech G910

**Comment by diogotr7** [comment]
Factorio support has now been added

**Comment by Happyrobot33** [comment]
This doesnt seem to be implemented yet into the main release and the pre releases dont seem to effect my keyboard at all. help?

**Comment by simon-wh** [comment]
@Happyrobot33 Try a recent build like [this](https://ci.appveyor.com/project/antonpup/aurora/build/0.6.2b-463/artifacts)

**Comment by Happyrobot33** [comment]
had to do a full uninstall then reinstall the it worked. thanks
