### ISSUE TITLE
Razer Synapse Help

### ISSUE THREAD

**Issue by CoinflipWOlfe** [antonpup/Aurora#879]
### What are you experiencing an issue with?

- [ x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ x] Aurora Wrapper
- [ ] Aurora Profile
- [x ] Aurora supported device, (Fill in problematic devices)
Razer Chroma
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x ] Other, (Fill in another type of issue here)
Can't find mouse on list of mice

### Expected behavior:
Explain here what should happen.

Preferred Mouse : Razer Naga Chroma

### Actual behavior:
Explain here what happened instead.

https://puu.sh/ysRXl/4cf1737044.png

### How often does this problem occur?

This problem occurs... (Fill in here)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. 
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... Most Recent

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:
 See Above

I'm trying to add my Razer Naga Chroma to the program. I was able to add my Logitech G910 but Razer Naga Chroma doesn't seem to be an option. Is there no support for the device?

**Comment by simon-wh** [comment]
Just select a mouse which has a similar led layout. There doesn't need to be an exact option for your mouse for it to work.
