### ISSUE TITLE
Support for Battlefield and Metro Last Light

### ISSUE THREAD

**Issue by AndersAnderson** [antonpup/Aurora#88]
Hi Antonpup,

first of all, thanks for the great work.
I would love to see Support for Metro Last Light and Battlefield 3.
Both Are AlienwareFX Games, so i hope its no too big dfeal to implement.

Thanks and keep up the good work.

Anders

**Comment by antonpup** [comment]
Battlefield 3 already has completed support, will be in next version. Metro should also work, as LightFX wrapper is done, so it should work with any game.

Basically, next update.

**Comment by antonpup** [comment]
Metro works with a minor issue (will be fixed before release), BF3 support was added a few commits ago. So, yes. Both of the mentioned games will have official support.
