### ISSUE TITLE
Razor firefly mousepad not showing up in the UI

### ISSUE THREAD

**Issue by Stijnno23** [antonpup/Aurora#880]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ x] Aurora supported device, (Razor firefly mousepad)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ x] Other, (The mousepad doesn't show up in Aurora)

### Expected behavior:
I saw some videos that the mousepad is visible in the UI, but with mine it isn't somehow.

### Actual behavior:
No visuals for the razor firefly in the Aurora UI

### How often does this problem occur?
Always

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. 
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (v0.6.0b)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/ -> https://imgur.com/a/1A2Vq 
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by stevenobird** [comment]
It is not showing up, but it is being interpreted as peripheral hardware.

I am using the Firefly and a Mamba TE, both are being cololorized when using Aurora.

But yes, I agree that LED Mousepads should also be able to be customized.

**Comment by Abcmsaj** [comment]
Odd as I had the Overwatch lighting effects working on my Firefly last night, pre-Aurora install, and then I installed Aurora and the wrapper for Overwatch and now my Corsair K65 works with OW but my Razer Firefly does not

**Comment by simon-wh** [comment]
Fixed thanks to #1331
