### ISSUE TITLE
CM Masterkeys + Razer wrapper stops Naga Chroma from special features

### ISSUE THREAD

**Issue by Thelgow** [antonpup/Aurora#882]
### What are you experiencing an issue with?

- [X] Aurora
- [X] Aurora supported game, (Fill in the game)
Overwatch, Diablo3
- [X] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [X] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
The Razer Naga has a feature in Diablo3 to turn the led's red, if near dead they blink fast. Activating Berserker switches it to Orange.
When the wrapper is enabled, or more precisely when RzChromaSDK.dll and RzChromaSDK64.dll are present in the folder the Naga features stop working, whether Aurora is running or not. If I remove or rename those 2 dll's then the Naga interacts normally.
Same behavior in Overwatch. Overwatch is simpler and each character has a designated color the mouse gets assigned to. 

Also the Diablo3 wrapper is missing features of lighting up the board when using some skills like Barbarian Berserker and when Legendary items drop. 

### Actual behavior:
Explain here what happened instead.
Mixed with above
### How often does this problem occur?

This problem occurs... (Fill in here)
Everytime the Wrapper dll's are present
### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Run wrapper feature to create dll's files
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... beta v0.6.0b

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.
Dont know
### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
Is the game lighting working with the keyboard and not the mouse when you have applied the wrapper?

**Comment by Thelgow** [comment]
Yes, if the wrapper files are present, the keyboard lighting features work, but the mouse loses them.  
I have since upgraded to version beta v0.6.1-dev3.  
This let me tie the mouse into Aurora as well. Overwatch just turned all lighting off until I reapplied the wrapper. Now both keyboard and mouse work simultaneous as expected.
Diablo3 was the same, I had to reapply the wrapper. It appears to still be missing the full integration of coloring options, so in this case I dont know if its possible to have it only control the mouse as I'd prefer my own regular Desktop layer to apply if thats the case.

**Comment by simon-wh** [comment]
So is your issue sorted then? Related to the last bit, I'm not entirely sure what you mean.

**Comment by Thelgow** [comment]
Its more of a case of all or nothing. Diablo3s wrapper doesnt have all the features for the keyboard, but the Mouse will work fine when by itself.  
So I have to decide either not have the wrapper files in, disassociate the Naga from Aurora and get the color to work on just the mouse, Or disable the wrapper all together and let aurora run the mouse to keep at least the Desktop profile on the keyboard going.  
With the coloring not fully implemented I have to opt for no wrapper/color options.

**Comment by simon-wh** [comment]
Okay, I think I'll point the remainder of this issue to #539
