### ISSUE TITLE
Rocatt support

### ISSUE THREAD

**Issue by senposage** [antonpup/Aurora#884]
### What are you experiencing an issue with?

- [ X] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [X ] Enhancement suggestion
- [ X] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
support for roccat rgb devices (kone,kone pure xtd ryosmk fx0

**Comment by simon-wh** [comment]
Duplicate of #811
