### ISSUE TITLE
SDK for 'zones-based' keyboard (G213)

### ISSUE THREAD

**Issue by vergilet** [antonpup/Aurora#888]
I've asked dev team of Logitech SDK about zones and they answered the next:

> We currently do not have the functionality for this in our release version of LGS and LED SDK. However I would like you to know that your requested functionality is already implemented and will be included in our next release. Be on the lookout for that!

Will you support G213 in Aurora when that happened?

**Comment by simon-wh** [comment]
It depends on the current state of Aurora at that time. Closing until an option
