### ISSUE TITLE
Overwatch/patcher not working anymore

### ISSUE THREAD

**Issue by Poolitzer** [antonpup/Aurora#889]
### What are you experiencing an issue with?

- [x ] Aurora supported game, (Overwatch)

### What kind of an issue is it?

- [x] Visual bug
- [x] Device issue

### Expected behavior:
The ligth should show up

### Actual behavior:
The keyboard gets dark (no ligth at all

### How often does this problem occur?

This problem occurs every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Download the newest Aurora Version and own a G910
2. Patch to the overwatch path
3. Run overwatch

### What is the version of Aurora you are experiencing this issue with?

My version is beta v0.6.1-dev3

### Does the previous version of Aurora have this issue?
One of the previous version did not have this issue. (So I know how it had looked bevore)

### Please include any logs, screenshots, or files that are related to this issue:
Dont think they are necessary, but hey, just ask.

Either its because of overwatch or because of Aurora. Maybe interesting: Im forced to run Aurora as an Admin, but Overwatch runs on another account.

**Comment by simon-wh** [comment]
See #771
