### ISSUE TITLE
Razer Tartarus/Orbweaver Support?

### ISSUE THREAD

**Issue by Electrifyer** [antonpup/Aurora#89]
Just wondering if there will ever be support for the two keypads made by Razer. Or am I just missing something completely?

**Comment by antonpup** [comment]
I can add support for keypads. It will be treated like a peripheral device, so solid colors for now.

**Comment by Electrifyer** [comment]
Thanks! I really appreciate how you're so open for requests and questions.

**Comment by antonpup** [comment]
:) I want to make Aurora as useful to the general public as possible. So taking suggestions/requests is kind of important.

With regards to the keypads, I will try and see if I can get individual lighting to fit into the virtual keyboard layout. This won't be taking priority, but is on the table.

**Comment by antonpup** [comment]
Included in version 0.5.0

**Comment by mavanmanen** [comment]
As Colore has full support for the keypads, will this ever be added?
Could be put to the left of the keyboard in the view.

**Comment by simon-wh** [comment]
@mavanmanen Might be on the list of things to do for v0.7.0

**Comment by KnottyDyes** [comment]
Any chance this can get resurrected?

**Comment by Aquind** [comment]
Same...was support for orbweaver ever created?
