### ISSUE TITLE
Razer Wrapper not working

### ISSUE THREAD

**Issue by Poolitzer** [antonpup/Aurora#890]
### What are you experiencing an issue with?

- [x] Aurora Wrapper

### What kind of an issue is it?

- [x] Visual bug
- [x] Device issue

### Expected behavior:
A game with Razer Support (Like Overwatch) should ligthen the keyboard.
### Actual behavior:
The keyboard is just black

### How often does this problem occur?

This problem occurs every time.

### What is the version of Aurora you are experiencing this issue with?

My version is beta v0.1.6-dev3
### Does the previous version of Aurora have this issue?
On of the previous version, did not have this issue.

Please read through it. It isn't the same issue you related me to the prevoius time. I dont have any ligthning, even in the match. I hope you read until this text :D

Interesting fact: Im forced to run Aurora as an Admin, but I dont run Overwatch as one.

**Comment by simon-wh** [comment]
Can you post your latest log file after attempting to get lighting?

**Comment by Poolitzer** [comment]
Jeah, give me about 5 Minutes
Am 29.11.17, 21:44, Simon W <notifications@github.com> schrieb:
Can you post your latest log file after attempting to get lighting?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/antonpup/Aurora","title":"antonpup/Aurora","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/antonpup/Aurora"}},"updates":{"snippets":[{"icon":"PERSON","message":"@simon-wh in #890: Can you post your latest log file after attempting to get lighting?"}],"action":{"name":"View Issue","url":"https://github.com/antonpup/Aurora/issues/890#issuecomment-347990353"}}}

**Comment by Poolitzer** [comment]
So, thats my definition of 5 minutes. Im sorry.

https://pastebin.com/FDXEcHgu

**Comment by Eps77** [comment]
Im having the same issue with Diablo 3 and i have tried multple versions of Aurora

**Comment by simon-wh** [comment]
Have you reapplied the wrapper on the current version of Aurora you are using?

**Comment by Poolitzer** [comment]
How can I do this? Just pressing Patch Overwatch? Yes, rigth now.

**Comment by simon-wh** [comment]
Yes

**Comment by Poolitzer** [comment]
Didnt help...

**Comment by Yakumounr** [comment]
Could this also be why Quake Champions doesn't work? it's a Razer Chroma enabled game,  I attached a log as asked and asked if any more info was needed but never got a further response : https://github.com/antonpup/Aurora/issues/825

**Comment by Poolitzer** [comment]
Hm. Have you tried Overwatch yet?

**Comment by Yakumounr** [comment]
I don't own any other Chroma enabled games, sorry.

**Comment by simon-wh** [comment]
I'm not sure where the issue you're having lies. Is the wrapper file definitely in the Overwatch directory alongside the Overwatch exe?

**Comment by Eps77** [comment]
I dont play overwatch just diablo

**Comment by Poolitzer** [comment]
@simon-wh definitly.

**Comment by Poolitzer** [comment]
Can confirm, on dev-4 not working. Log included.
[2018-01-30 18.51.54.log](https://github.com/antonpup/Aurora/files/1678805/2018-01-30.18.51.54.log)

**Comment by Poolitzer** [comment]
Hurray. It works again. Seems to was an Overwatch issue, they fixed it.
