### ISSUE TITLE
Ambilight doesn't work properly when Super Hexagon is in fullscreen mode

### ISSUE THREAD

**Issue by s1cp** [antonpup/Aurora#892]
### What are you experiencing an issue with?
- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?
- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Ambilight layer should detect and display the game's colors while in fullscreen mode.

### Actual behavior:
Ambilight layer only gets the last frame of the game window before going fullscreen.

### How often does this problem occur?
Always.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Add an Ambilight layer
2. Set the effect type to default
3. Set capture type to any of those available
4. Play Super Hexagon in fullscreen mode

### What is the version of Aurora you are experiencing this issue with?
My version is beta v0.6.0b

### Does the previous version of Aurora have this issue?
Didn't check.

### Please include any logs, screenshots, or files that are related to this issue:
I don't think any are necessary.

**Comment by s1cp** [comment]
[2017_29_11.log](https://github.com/antonpup/Aurora/files/1516455/2017_29_11.log)

This is the latest generated log.

**Comment by diogotr7** [comment]
As far as i know this works properly with v0.7.0. Closing since it's been inactive for a while
