### ISSUE TITLE
Suggesting Support for Total War Warhammer

### ISSUE THREAD

**Issue by Shendrach** [antonpup/Aurora#893]
Hi, I'd just like to suggest Aurora support for Total War Warhammer (I and II). Currently it is the leading epic scale fantasy strategy game. And I think it will remain that way. And there is even TW: Warhammer III to be published. Since you could use almost the same aurora profile for all three games and it would be very nice to also have a game from the grand scale strategy genre for aurora, I'd be very happy if this would become true.

**Comment by simon-wh** [comment]
I don't think this will be on the timeline for support in Aurora. I haven't looked into it, but I assume there is mod support that could theoretically allow for giving game info to Aurora. My plan is to make it as easy as possible for other people to add support for new games, as it just isn't viable for me to add them all, right now I barely have enough time to work on Aurora itself.
