### ISSUE TITLE
Razer Blackwidow v2 The Division problem

### ISSUE THREAD

**Issue by TyFl0sGr** [antonpup/Aurora#894]
### What are you experiencing an issue with?

- [ ] Aurora
- [x ] Aurora supported game, (The Division)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [X ] Other, (It is simply not starting i got the led support from the options in game too)

### Expected behavior:
Explain here what should happen.
It normally should act as it acts at logitech keyboards.
### Actual behavior:
Explain here what happened instead.
Simply its not working i any of my lights dont light up in game

### How often does this problem occur?

This problem occurs always.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Open Razer Synapse-Aurora
2. Open The Division.exe
3. Cry becouse its not working.

### What is the version of Aurora you are experiencing this issue with?

My version is... v0.6.0b

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
Have you applied the razer wrapper?

**Comment by TyFl0sGr** [comment]
yes i did yet it isnt workin

**Comment by simon-wh** [comment]
Do you have a log file of when you were attempting to get this to work?

**Comment by juleztb** [comment]
Have the same problem on my combination of Corsair K95 Platinum and Razer Naga Trinity + Razer Firefly.
It just stays dark.
I would happyly suply a log  though I don't know where to find it.

**Comment by simon-wh** [comment]
@juleztb Are you running v0.6.1-dev4?

**Comment by juleztb** [comment]
Yes. Using the v0.6.1-dev4
And as you asked, I just found the "show logs folder" button within the debug tab.
Adding my logs here:
https://pastebin.com/8XXA3uBR
https://pastebin.com/qQQVMDeu
I'm not reading anything in there containing Division though.
Btw I tried it both in the standard version as I downloaded it, without a special layer in the Division Tab, as well as with an added "Wrapper Lightning Layer" tab, that I created.

**Comment by simon-wh** [comment]
@juleztb With v0.6.1-dev4 the wrapper lighting layer is required for wrapper lighting to work (for future reference). In the second log, it shows that it has connected to the wrapper (see lines starting with [IPCServer]), so it appears to connect but it doesn't receive any lighting information, did you reapply the wrapper after updating to v0.6.1-dev4?

**Comment by juleztb** [comment]
Yes, I did reapply the wrapper both before and after updating to 0.6.1-dev4

**Comment by simon-wh** [comment]
@juleztb Hm, I am not sure why it isn't working, as I don't own the Division I can't debug it specifically, but I'll be making some fixes to the wrappers (hopefully) soon so after that, people who own the game can test it.

**Comment by juleztb** [comment]
Tried it again. Works now.
I seem to be some kind of idiot...wow...
I did indeed reapply the wrapper after updating. But what I did not do was activating the "LED Keyboard Support" option ingame. After switching that one on, it worked like a charm.
