### ISSUE TITLE
Interactive effects bug with Logitech G410

### ISSUE THREAD

**Issue by saintonotole** [antonpup/Aurora#90]
Hi. I discovered that the aurora didn't catch pressing backslash key on my G410 keyboard, and as a result, interactive effects for this button does not work.
![aurora g672l](https://cloud.githubusercontent.com/assets/16139311/17455903/f18dd76e-5bce-11e6-92f2-6203c158e24f.png)

**Comment by antonpup** [comment]
I applied a fix that will hopefully work in the next version.

**Comment by Johnnybeefcake** [comment]
Same thing happens with the \ key on the G910. It's displayed next to the enter key rather than above it in Aurora.

**Comment by antonpup** [comment]
This should be fixed in version 0.5.0
