### ISSUE TITLE
Which Keyboard is the cheapest can support Aurora?

### ISSUE THREAD

**Issue by davidanger** [antonpup/Aurora#903]
I just want to buy one for Aurora. I mean truely support not like the G213(cannot support single key color setting).
Is any suggest?
THX

Or, how about DIY a RGB keyboard?
Need what kind of protocol to let the Aurora control it?

**Comment by diogotr7** [comment]
From my rough search, the cheapest keyboard with PER-KEY backlightning is the razer cynosa.

https://pcpartpicker.com/products/keyboard/#m=50,11,108,162,230&b=46&sort=price

Again, this might not be correct.
