### ISSUE TITLE
Corsair Link support

### ISSUE THREAD

**Issue by deivater** [antonpup/Aurora#904]
I know, there is thread already, but it is closed :)
Support for corsair link would be sick. Can´t imagine, how nice it will looks, with my Corsair node pro and RGB Fans. If this feature will be added, I will send you a paypal donation, because this is the feature, I´m waiting for :)  Aurora is awesome.
Thank you for your work.

Edit: that last bullet side doesn´t work.
I would like to try out some cool profiles.

best regards 
Kevin

**Comment by deivater** [comment]
http://forum.corsair.com/forums/showthread.php?t=120092

**Comment by simon-wh** [comment]
Duplicate of #546
