### ISSUE TITLE
[Question] Style guides for mouse/kb drawings? Looking for artists

### ISSUE THREAD

**Issue by FHeilmann** [antonpup/Aurora#907]
Hi, I am trying to add new mice (namely Steelseries) to Aurora, but I am somewhat stuck trying to replicate the visual style of the mice already added.

Is there some kind of style guide (colors, linewidths, etc.) that will allow me to replicate the existing style on these new mice? Or maybe someone can give me some hints about how to achieve this visual style without having to spend hours on each mouse?

Finally if someone gifted enough wants to help me out with this, I am currently looking to add all mice listed on this page: https://steelseries.com/gaming-mice (with 1 generic Rival 300 in place of the special editions) to Aurora.

**Comment by simon-wh** [comment]
I don't know how the current images were designed so I can't help you, sorry!
