### ISSUE TITLE
i believe , other rbg mouse can be support  aurora the lighting program.

### ISSUE THREAD

**Issue by Arilade** [antonpup/Aurora#908]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
i have trust gxt 21789 gaming mouse it has 1.6m rbg lighting leds and doesnt support i want it. how can i do.

### Actual behavior:
the program doesnt trigger to my mouse. but it supports logitech g300s. i believe it can be .

### How often does this problem occur?
since buying that mouse.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. 
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

last version

### Does the previous version of Aurora have this issue?
no  0.6.0

**Comment by DogeAmazed** [comment]
I don't think the Trust GXT-Software has an SDK included. I also can't check this because I don't have hardware by Trust.
Without SDK it's getting kind'a hard.
