### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by Pigeoncraft** [antonpup/Aurora#91]
I experience a pretty high CPU usage while Aurora is running. Around constant 20%. This causes my games such as Overwatch to studder.

I attached my Log:

[2016_06_08.txt](https://github.com/antonpup/Aurora/files/405207/2016_06_08.txt)

Other Specs Below:

[PcInfo.txt](https://github.com/antonpup/Aurora/files/405208/PcInfo.txt)

**Comment by antonpup** [comment]
Is Aurora exerting this behavior while idle as well? While idle, in the background, Aurora should be taking up at most about 2-3%. And about 5% while in focus.
Here's my usage on a 8320, OC with 4 cores on.
![http://puu.sh/qsgx1/42efae4203.png](http://puu.sh/qsgx1/42efae4203.png)

And this is how it is while Keyboard Audio Visualizer for Razer is running.
![http://puu.sh/qsh49/1a73a35156.png](http://puu.sh/qsh49/1a73a35156.png)

My measurements were with the unreleased Razer wrapper and some Aurora changes. But it still should not be taking up more than 10% at any time. What is your set up as well? It might be an issue with one of the device implementations. I am running G910, Sabre RGB, and a VOID RGB.

**Comment by antonpup** [comment]
I tested with the currently released version, and while running the same keyboard audio visualizer for Razer, I get about 6-8% usage.
![http://puu.sh/qshNt/49907267ed.png](http://puu.sh/qshNt/49907267ed.png)

Aurora idle (in background): 0-2%
Aurora in focus: 6-11%

It is certainly an inefficiency with the current release version. But it should not be as high as 20%.

**Comment by Pigeoncraft** [comment]
At idle without anything its around 20%.

I may try a clean boot later and see if I still have the issue.

![2016-08-06 18_26_00-task manager](https://cloud.githubusercontent.com/assets/1438540/17459904/4e0666c6-5c03-11e6-949e-7755fe184204.png)

**Comment by antonpup** [comment]
Try my current dev version. See if that gives you the same results.

[Release_pre0_5_0.zip](https://github.com/antonpup/Aurora/files/405254/Release_pre0_5_0.zip)


But what RGB devices do you have connected?

**Comment by Pigeoncraft** [comment]
![2016-08-06 18_50_55-task manager](https://cloud.githubusercontent.com/assets/1438540/17459995/bc53ee0c-5c06-11e6-8607-422452c53fa5.png)

Its a bit better. Hover around 15% now. With some random spikes of up to 30 - 35% Mainly opening new windows (Explorer, Chrome, etc)

**Comment by antonpup** [comment]
Spikes are most likely due to Aurora retrying for device SDKs. But try running Aurora as admin. I'll take out my Strafe RGB tonight and see if I get the same problems.

**Comment by Pigeoncraft** [comment]
Running as admin dropped it even more. Around 10% average. Ill have to try to launch OverWatch to see if I still get stutters. Where is the main loop located in the project that is related? Or is it spread out?

**Comment by antonpup** [comment]
Make sure to repatch Overwatch with the new razer wrapper from the version I gave you. The timer for LightEvents is located here: https://github.com/antonpup/Aurora/blob/master/Project-Aurora/GameEventHandler.cs#L115 And whenever a new game state is sent, it is handled here: https://github.com/antonpup/Aurora/blob/master/Project-Aurora/GameEventHandler.cs#L228

**Comment by Pigeoncraft** [comment]
Still having some pretty bad stutters in game although not as bad. I will take a deeper look into the code tonight if I get some more free time.

**Comment by Pigeoncraft** [comment]
![2016-08-07 20_23_45-task manager](https://cloud.githubusercontent.com/assets/1438540/17468438/eb21352e-5cdc-11e6-8edd-affc8b9eacb1.png)


I have been tweeking some things with the timers and I am averaging so far at around 1% CPU. Although I need to test some more stuff to make sure I didn't break anything. I'm going to test a couple of games right now to check usage there.

**Comment by Pigeoncraft** [comment]
![2016-08-07 20_29_33-](https://cloud.githubusercontent.com/assets/1438540/17468532/af8c3fee-5cdd-11e6-99c1-47b974a794a2.png)


Overwatch is fully playable now with no frame skips or anything.

Aurora stays around 1-2%. Sometimes going to 4-5%. Let me check one more thing and clean up and ill commit.

**Comment by antonpup** [comment]
If you're messing with timings, CSGO profile requires 100 fps, due to the smooth bomb effect.

Other than that, everything else was configured for 30 or so fps.

**Comment by Pigeoncraft** [comment]
Ok I put a check in for CSGO. Although I haven't been able to test it.

My average CPU is still pretty low. But I keep getting spikes about every 4 seconds.

Here is a analysis

C:\Users\snhp1\OneDrive\Pictures\2016-08-07 21_19_44-Project-Aurora - Microsoft Visual Studio.png

I'm trying to think of a faster more stable way to get the active window because that seems to be the main issue right now.

**Comment by Pigeoncraft** [comment]
I got rid of the cpu spikes by adding a listener and only updating the current process name when the window changes. The only bug I have found so far is that when you close a game it wont update the current process name unless you click. Might be able to add a listener for when a window is closed later on.

But I am going to commit what I have now.

I now average 0.3% CPU usage at idle.
