### ISSUE TITLE
PUBG support with G910

### ISSUE THREAD

**Issue by Gunichou** [antonpup/Aurora#911]
Hi there and first thanks for this app.
I'd like to use with my G910 and PUBG.
Do you think it's possible to use with PUBG like with CS GO ?
I like to have my keyboard lighting in white when i'm flashed, making a fire draw when i use molotov ...

**Comment by WettoAdrena** [comment]
It seems Razer may be coming up with support for PUBG soon:
https://insider.razerzone.com/index.php?threads/chroma-for-pubg-confirmed.27919/

If Razer comes up with it, it's easy to adapt it into Aurora.
