### ISSUE TITLE
Shortcut Assistant Enhancement suggestion

### ISSUE THREAD

**Issue by A-RANDOM-TITAN** [antonpup/Aurora#914]
I would like to see the ability to use any key for the Shortcur Assistant.
i use Aurora to help me with Adobe Illustrator, Photoshop and CAD software.

Shortcuts start also with "Shift", "Tab" and "^" not only with "Ctrl", "Win" and "Alt".
Also the abilliti to have diverent keys higlited when pressing "Alt+Ctrl" "Ctrl+Shift" etc.
The Best case Scenario Would be if you could chose those keys yourself.

sincerely
M. Shahid

**Comment by simon-wh** [comment]
Using the [latest development release](https://github.com/antonpup/Aurora/releases) you should be able to achieve this using the updated Shortcut assistant layer.
