### ISSUE TITLE
Aurora is incompatible with CM MasterKeys Pro M with ABNT2 (Brazilian) layout

### ISSUE THREAD

**Issue by WettoAdrena** [antonpup/Aurora#915]
### What are you experiencing an issue with?
- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (CM MasterKeys Pro M in ABNT2 layout)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?
- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [X] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Keyboard should be recognized and backlight effects should work.

### Actual behavior:
Keyboard backlight stops working, won't come back even if you press the backlight configuration keys or close Aurora.

### How often does this problem occur?
Every time.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1.  Get a Brazilian ABNT2 Layout CM MasterKeys M (already checked with other owners, same problem)
2.  Open Aurora
3.  Keyboard gets recognized by Aurora, but the backlight dies out, using any backlight control keys on the keyboard will get nothing.
4. To get the backlight to work again, you need to remove and insert the keyboard back after closing Aurora.

### What is the version of Aurora you are experiencing this issue with?
0.61, but tried the older versions as well.

### Does the previous version of Aurora have this issue?
Yes

### Please include any logs, screenshots, or files that are related to this issue:
https://pastebin.com/tMdq9HaA

**Comment by simon-wh** [comment]
Do you still been experiencing this issue on v0.6.2b?

**Comment by WettoAdrena** [comment]
It works on the last update, thanks!
