### ISSUE TITLE
Aurora startup error (Key not found)

### ISSUE THREAD

**Issue by wEisB0145** [antonpup/Aurora#918]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Well... starting up :/

### Actual behavior:
Well I cannot start Aurora anymore, I am using the latest build (not the stable one since that one got me a memory leak :( )

### How often does this problem occur?

This problem occurs well every startup

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Start Aurora....

### What is the version of Aurora you are experiencing this issue with?

My version is 0.6.1 dev3

### Does the previous version of Aurora have this issue?
Nope

### Please include any logs, screenshots, or files that are related to this issue:

https://pastebin.com/R8zqZfaG
:(
I like aurora-

**Comment by simon-wh** [comment]
Delete %appdata%/Aurora/Config.json
