### ISSUE TITLE
Aurora started up and crashed

### ISSUE THREAD

**Issue by S2P2** [antonpup/Aurora#919]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Aurora start with Windows normally.

### Actual behavior:
This window appeared

> Aurora has stopped working
> 
> Aurora fatally crashed. Please report the follow to author: 
> 
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Aurora.Profiles.Application.LoadSettings(Type settingsType)
>    at Aurora.Profiles.Application.Initialize()
>    at Aurora.Profiles.LightingStateManager.Initialize()
>    at Aurora.Program.Main(String[] args)

I press OK and open Aurora.exe in the folder and it start normally.

### How often does this problem occur?
1/1 startup

### Please describe the steps to reproduce this issue:
not sure.

### What is the version of Aurora you are experiencing this issue with?

My version is 0.6.1 dev3

### Does the previous version of Aurora have this issue?
I have used 0.6.0b and never seen this before

### Please include any logs, screenshots, or files that are related to this issue:

log file : https://pastebin.com/EZbmXvpT

**Comment by simon-wh** [comment]
You might need to delete the Plugins/Plugin-Example.dll file that is mentioned in the logs.

**Comment by simon-wh** [comment]
Also, update
