### ISSUE TITLE
lighting effects stops when someone talks on discord or when i speak

### ISSUE THREAD

**Issue by darthpouch** [antonpup/Aurora#920]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
being able to talk and listen to other people while using this app without it stopping my lighting effects

### Actual behavior:
When i talk, the function keys all go red. when someone else talks on discord, they turn purple and it stops the lighting animations.

### How often does this problem occur?

This problem occurs... (every time there's a voice heard)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. im using 2 layers both with breathing effect.
2. start talking into a mic connected to the computer like a gaming headset. im using logitech g930
3. also go into a discord voice channel and have another person talk there.

### What is the version of Aurora you are experiencing this issue with?

My version is... (beta v0.6.0b)

### Does the previous version of Aurora have this issue?
never used it before this version

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by dfg260** [comment]
![IMG](https://i.imgur.com/88qcfel.png)
Disable Discords Keyboard Illumination feature.

**Comment by LukasACH** [comment]
I don't know if they fixed it yet, but to stop LGS form asking everytime, delete or rename the discord integration executable inside the LGS installation folder.
