### ISSUE TITLE
Corsair K55 Support

### ISSUE THREAD

**Issue by thorman123** [antonpup/Aurora#922]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [X] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [X] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
Corsair K55 Should be supported

### Actual behavior:
Explain here what happened instead.
It is not

### How often does this problem occur?

This problem occurs... (Fill in here)
Every Time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Opening Aurora
2. going to settings
3. finding k55

### What is the version of Aurora you are experiencing this issue with?

My version is... (Fill in here)
Beta 0.6.0B

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.
Did

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
The keyboard does not need to be in the settings (atleast the drop-down) for it to be supported. If it is supported by the CUE sdk then it should connect and work through the sdk, if it doesn't work when both of those are the case then there isn't really anything I can do.
