### ISSUE TITLE
aurora window not opening

### ISSUE THREAD

**Issue by Ne7-github** [antonpup/Aurora#924]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [x] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.

### Actual behavior:
aurora prompts my logitech and corsair set up then the window for aurora does not show up

### How often does this problem occur?

This problem occurs... (everytime)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. install dev3
2. extract to folder
3. open aurora.exe

### What is the version of Aurora you are experiencing this issue with?

My version is... (major 0_6_1-dev3)

### Does the previous version of Aurora have this issue?
The previous version, (major 0_6_1-dev2), did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: https://pastebin.com/0HjW0DDj
For screenshots, you can use: http://imgur.com/imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
You should delete Plugins/Plugin-Example.dll from the Aurora directory, even though it probably won't make a difference. Could you also try renaming(if you don't want to lose profiles) or deleting %Appdata%/Aurora to see if that allows it to run?

**Comment by simon-wh** [comment]
Update if you still have this issue
