### ISSUE TITLE
I'm an idiot

### ISSUE THREAD

**Issue by BeardyMcBeardFace** [antonpup/Aurora#925]
I was mucking about with the Desktop settings and accidentally changed the CPU usage around. Now its all messed up and I cant fix it. Is there any way to restore it to the defaults? Or can anyone send me screencaps of their settings so I can get it fixed?

On another note, trying to make a few custom ones and running into trouble. Are there any resources or guides about to do this? Was thinking having the numpad show the system clock would be pretty cool.

Any profiles I can import? Or creation guides?

**Comment by BeardyMcBeardFace** [comment]
Fixed the CPU issue. Just dug into the code to find the default. Still looking for any resources for customization and profiles if anyone has them :)

**Comment by diogotr7** [comment]
@BeardyMcBeardFace You could've just cliked profiles, then reset profile, but i guess that works too :p.

As for profiles, there are some [here](https://modworkshop.net/mydownloads.php?action=browse_cat&cid=299) and on the more corsair-centered [reddit](https://www.reddit.com/r/RGBProfiles/). These corsair profiles are not fully implemented yet, but some of them do work pretty well.

There's a Pack for CUE 2.9 somewhere where most of them are supported by Aurora. So overall, not many. Have fun!

**Comment by BeardyMcBeardFace** [comment]
Thanks! that certainly Makes it easier
