### ISSUE TITLE
K95 Platinium AZERTY layout

### ISSUE THREAD

**Issue by LightD31** [antonpup/Aurora#926]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (K95 Platinium AZERTY)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
G keys should be illuminate

### Actual behavior:
Only G1 and G2 are illuminated
### How often does this problem occur?

This problem occurs all the time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Add a layout on G keys

### What is the version of Aurora you are experiencing this issue with?

My version is beta v0.6.1-dev3 

### Does the previous version of Aurora have this issue?
I don't know

### Please include any logs, screenshots, or files that are related to this issue:
N/A

**Comment by simon-wh** [comment]
I believe this has been sorted by PR #759 which will be available in the next release.
