### ISSUE TITLE
Nothing is working.

### ISSUE THREAD

**Issue by jizichun** [antonpup/Aurora#928]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [x] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.

### Actual behavior:
There is no lighting on keyboard and mouse after windows update yesterday. And the keyboard graphic has some wired glitch.

### How often does this problem occur?

This problem occurs... (Everytime)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. 
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (0.6.1-dev3
<img width="904" alt="aurora lighting" src="https://user-images.githubusercontent.com/32007466/34460044-9f27866a-edb7-11e7-8acb-04f75e0b9cdd.PNG">
)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
Do you have a log file you can provide?

**Comment by jizichun** [comment]
[2018_01_16.log](https://github.com/antonpup/Aurora/files/1648332/2018_01_16.log)

**Comment by simon-wh** [comment]
It doesn't appear to be able to connect to the CUE SDK(Assuming you have a Corsair device based on your keyboard layout). Is CUE running and the SDK enabled?

It also doesn't appear to be displaying the effects on the virtual keyboard, which is quite strange.

**Comment by jizichun** [comment]
Yup cue is running and ask enabled, I might try reinstall it.

**Comment by simon-wh** [comment]
Could you move(while aurora is closed) %appdata%/Aurora to %appdata%/Aurora1 or similar and launch again to see if it is any different?

**Comment by jizichun** [comment]
Thanks, It fix the issue :D

**Comment by simon-wh** [comment]
@jizichun Awesome! I think you may have accidentally enabled the "Disable Keyboard Lighting" option or similar, you should be able to safely copy over any profiles you had that you want to use again.
