### ISSUE TITLE
Issue with shortcut assistant

### ISSUE THREAD

**Issue by BeardyMcBeardFace** [antonpup/Aurora#929]
Small issue with the shortcut assistance preset. Aurora seems to always think I am holding down alt. has been working fine for the past week, then yesterday it starting doing this, resulting my my, ctrl, tab, f4, v and E always being yellow. not sure why.

Anyone else have this issue and know how to resolve it? Tried reseting the profile and that didn't work, issue still persisted on the default.

![aurora](https://user-images.githubusercontent.com/34904349/34465045-44d48a00-ef01-11e7-9a5e-e90c9f46f125.PNG)

**Comment by simon-wh** [comment]
Could you update to the [latest development release](https://github.com/antonpup/Aurora/releases)? The issue probably is coming up because Aurora isn't being run as admin.

**Comment by BeardyMcBeardFace** [comment]
Im on the latest dev release. Will try as admin and let you know in a few days if the issue persists.

**Comment by BeardyMcBeardFace** [comment]
Issue still persists. Hitting the right alt keyu seems to fix the issue, but it comes back every so often.

**Comment by BeardyMcBeardFace** [comment]
More information on this. Seems to happen whenever I first boot it up, or if I open a new application. For example, I launch Hearthstone and the issue occurs. Hit alt and it goes away.

**Comment by simon-wh** [comment]
Hm, I'm not sure, I haven't been able to replicate it. I'll try and have a look at it to see if I can see anything out of place.

**Comment by simon-wh** [comment]
Could you try [this build](https://ci.appveyor.com/project/antonpup/aurora/build/0.6.1-dev4-319/artifacts) and let me know if it solves your issue.

**Comment by BeardyMcBeardFace** [comment]
I've downloaded and extracted the file, but what am I supposed to do with
it from here? I don't see any executable, do I simply over write the
existing aurora files with this? Where is the existing aurora app stored? I
can't find it locally.

**Comment by BeardyMcBeardFace** [comment]
Apologies, must have missed that (no coffee yet today). Will check again.

**Comment by BeardyMcBeardFace** [comment]
Seems to fix the issue when I load up hearthstone, which was the most
common cause. I'll keep at it and if it acts up again I'll let you know.
Many thanks :)

**Comment by simon-wh** [comment]
Awesome! I'll close this for now, it can be reopened if you run into the same issues as before again.
