### ISSUE TITLE
Suggestion: Internal PC clock display on numpad

### ISSUE THREAD

**Issue by BeardyMcBeardFace** [antonpup/Aurora#930]
I would love this to be an ability. Show the current time in hours and minutes on the numerical pad.

Is there any way to do this or to have this functionality added to the software?

Something along the lines of Hour in one colour, minutes in another. Fade into each key as the time passes. If the hour and minute are the same (ex, 5:45 then the 5 would fade between the 2 colours).

**Comment by deivater** [comment]
Awesome idea, but sadly I dont think, that this programm is still in development. Even the links doesn´t work. I use it all the time. Much better, than Corsair´s Cue 2. Hope for a Corsair Link support, so I can synch my LEDs and my RGB fans.

**Comment by simon-wh** [comment]
@BeardyMcBeardFace That's an interesting concept but I don't think it is something that I'll be adding to Aurora. It sounds like something that could be made as a script if you or someone you know can code it.
