### ISSUE TITLE
Both updates and profile web links are incorrect

### ISSUE THREAD

**Issue by wld7** [antonpup/Aurora#934]
The link located in "Settings" "Updates" incorrectly points to http://aurora.lastbullet.net/history.php  (link is dead should reflect new name http://aurora.modworkshop.net/history.php). This is on the pre release Aurora 0.6.1-dev3 build as well as current stable build. 

The current "Check for Updates" link is correctly pointing too https://project-aurora.com/vcheck.php (confirmed using wireshark on  pre release Aurora 0.6.1-dev3).

**Comment by deivater** [comment]
same problem, but it persists for months. I dont think that Aurora is still in development. That is sad :(

**Comment by simon-wh** [comment]
@deivater I'll deal with it soon hopefully, I've got January exams that I'm working for and will have time after to continue working on this.

**Comment by wld7** [comment]
No Problem thanks for the awesome program. Just thought i should let you
know before you roll out the next update. Good luck on the exams.

**Comment by deivater** [comment]
@simon-wh thank you for the update :). Corsair Link LED support would be crazy, than I could control all my led stuff with Aurora. If Aurora gets this feature, I will make a paypal donation to you. This is the thing, that I am waiting for ;)

**Comment by simon-wh** [comment]
Issue fixed, will be available in next release.

@deivater I'm not sure when I'll be getting onto expanding into other forms of devices as there are a lot of issues currently that I need to deal with.
