### ISSUE TITLE
Overwatch lighting with Aurora doesn't work [G810]

### ISSUE THREAD

**Issue by KaeJae** [antonpup/Aurora#936]
Hello, I got my G810 today and I wanted to try Aurora out. It's a very cool application and I'm loving it so far however despite all my efforts I can't get it to work with Overwatch. I did look up my issue online but none of them work. When I hover on Overwatch thru Aurora app, the keys are all black, whenever I hover on Rocket League or Payday it works. I go in game and all the color on keyboard is completely black. I did patch my game and tried running both apps on admin, no luck. I have the latest version installed, my game is installed on another drive, I'm thinking that might be the issue? I really have no clue and would appreciate some help.

Thank you.

**Comment by LukasACH** [comment]
In the main menu after launch, the keyboard stays black, but it should change as soon as you join a match. Could you provide your log file after an Overwatch launch?

**Comment by JesuisOriginal** [comment]
same here, its all blacked out and wont light.

**Comment by simon-wh** [comment]
Closing due to lack of follow up. Advice would be to make sure you're on v0.6.1-dev4 and enure that the Overwatch wrapper has been patched.
