### ISSUE TITLE
Game state listener could not start and so app won't launch. 

### ISSUE THREAD

**Issue by Tensounder54** [antonpup/Aurora#937]
### What are you experiencing an issue with?

- [x ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [x] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
The app should start

### Actual behavior:
https://imgur.com/a/t7PDJ

### How often does this problem occur?
This problem occurs every time I try to launch the aplication

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. installing aurora and launching the application.

### What is the version of Aurora you are experiencing this issue with?

My version is the latest release from the aurora website.

### Does the previous version of Aurora have this issue?
I don't know 

### Please include any logs, screenshots, or files that are related to this issue:
Log attached.
[2018_04_01.log](https://github.com/antonpup/Aurora/files/1602207/2018_04_01.log)

**Comment by simon-wh** [comment]
It looks like you had multiple Aurora instances or another application was interfering with Aurora. Either way, could you try the [latest development release](https://github.com/antonpup/Aurora/releases) to see if it makes a difference.
