### ISSUE TITLE
Shortcut Assistant Layer Feature Suggestion: Multiple Key Combo Shortcuts (Example: ctrl+shift, alt+shift, ctrl+alt+shift, etc.)

### ISSUE THREAD

**Issue by TeraBrite** [antonpup/Aurora#938]
I love the shortcut assistant layer but not all shortcuts use just 2 keys. Some common shortcut combos that require more than one key are:
**alt + ctrl + __
shift + ctrl + __
alt + shift + ctrl + __
win + ctrl + __
win + shift + __**

Also, even though it's not a multi key combo, I noticed "**shift + __**" is a popular shortcut that is missing as well. Kinda makes sense because that's used for caps, but there's quite a few keyboard shortcuts out there that use shift.

I would love to have access to more key combos like these which trigger the shortcut assistant keys I chose to light up or at least the ability to create custom trigger key combinations myself so I can have unlimited possibilities. I use a lot of professional applications (Photoshop, Vegas, Premiere, After Effects, Cubase, Blender) that have a lot of difficult to remember multi-key shortcut combinations and I want to create profiles for each application that have all of the possibilities laid out for me, but I can't do it with just:

**ctrl + __
Win + __
alt + __**

Thanks!

**Comment by simon-wh** [comment]
I'm pretty sure this is achievable in the [current development release](https://github.com/antonpup/Aurora/releases) using the redesigned shortcut assistant.
