### ISSUE TITLE
Dota 2 Heroes Animations

### ISSUE THREAD

**Issue by ramongtx** [antonpup/Aurora#94]
I have Aurora working for my Razer Chroma on Windows 10, and it works very well (thanks for the great work, guys!). The only problem I've been having is that hero skills animations are not working for me on Dota 2 - the integration works perfectly, mana/health/kills, but no skill animations. Anyone care to shed a light on why could this be happening?

**Comment by antonpup** [comment]
Not all heroes have animations. Which hero did you not have effects with?

**Comment by ramongtx** [comment]
I tried the ones I saw on a demo video: Razor and Riki

**Comment by antonpup** [comment]
You are right. Looking into it.

**Comment by antonpup** [comment]
Fixed in today's version.
