### ISSUE TITLE
Add support for Logitech G413.

### ISSUE THREAD

**Issue by olvrb** [antonpup/Aurora#940]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
The keyboard should light up like the preview.
### Actual behavior:
No lighting is changed whatsoever.
### How often does this problem occur?

This problem occurs... 
All the time: the keyboard is not supported.
### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Plug in keyboard
2. Open Aurora in Administrator mode.
3. Try to apply effect.

### What is the version of Aurora you are experiencing this issue with?

My version is... 
beta v0.6.0b
### Does the previous version of Aurora have this issue?
The previous version did/did not have this issue.
Yes.

**Comment by untitledlives** [comment]
I was able to get my g413 to work but its so sparatic at best. Then it would show the overwatch theme only when it was in background but not when it was selected in foreground. after the install I could not even get the logitech built in game detection to work. Since then I gave up.

**Comment by olvrb** [comment]
Yeah, i wouldn't expect it to work since Aurora only supports RGB keyboards atm.

**Comment by simon-wh** [comment]
The g413 doesn't appear to per-key lighting or supported by the logitech sdk so I don't think it's going to work.
