### ISSUE TITLE
Aurora keeps saying it is already running

### ISSUE THREAD

**Issue by rustyking98** [antonpup/Aurora#941]
### What are you experiencing an issue with?

- [x ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.

### Actual behavior:
Explain here what happened instead.

### How often does this problem occur?

This problem occurs... (Fill in here)

Everytime I open the app it says Aurora is already running. Exiting. Tried uninstalling and clearing appdata and then reinstalling but still doesn't work. Worked normally for the first 2 days but suddenly not working today.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Just opening the app causes the crash
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (Fill in here)  0.6.0b

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.
no other version

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

Screenshot of crash:
https://imgur.com/nEfqcIN

Log link:
https://www.dropbox.com/s/7sfe91s309uk1jv/2018_06_01.log?dl=0

**Comment by simon-wh** [comment]
Is it running in the background (with a tray icon) that you just aren't noticing? If you can't find a tray icon then you should end the process in task manager. Either way, the [latest development release](https://github.com/antonpup/Aurora/releases) will attempt to show the current instance of Aurora rather than exiting when it discovers it is already running.
