### ISSUE TITLE
K70 Keyboard not working with Overwatch

### ISSUE THREAD

**Issue by GygaByte42** [antonpup/Aurora#944]
### What are you experiencing an issue with?

- [ ] Aurora
- [x] Aurora supported game, Overwatch
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [x] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
K70 RGB keyboard should respond to me changing characters in Overwatch.

### Actual behavior:
K70 RGB Keyboard stays black and doesnt light up when Overwatch is Opened.

### What is the version of Aurora you are experiencing this issue with?

My version is V0.6.0b

I believe I installed the patch correctly. Idk why it isnt responding. Aurora works normally to light up my keyboard.

**Comment by simon-wh** [comment]
Is it still not changing when you go in-game? If not, could you try the [latest development release](https://github.com/antonpup/Aurora/releases) and re-apply the wrapper to see if that makes a difference.

**Comment by allard1997** [comment]
Can confirm that Overwatch (patch 1.19.1.3.42936 - latest af of rn) is working with Aurora v0.6.1-dev3.
