### ISSUE TITLE
Extension to HyperX Mars RGB

### ISSUE THREAD

**Issue by fabriciano55** [antonpup/Aurora#946]
Are there any future extension projects for HyperX Mars RGB ?

**Comment by simon-wh** [comment]
Duplicate of #898

**Comment by avengerx** [comment]
Hi there, what about this: https://www.hyperxgaming.com/en/NGENUITY

Worth a try?

**Comment by fabriciano55** [comment]
Hello, this software is not compatible with Keyboard MARS RGB

Thanks for the feedback.


*Fabriciano Rodrigues*



Em qua., 27 de jan. de 2021 às 18:46, avengerx <notifications@github.com>
escreveu:

**Comment by avengerx** [comment]
yes, that's true :(
Might need to reverse engineer it, but hoping its protocol to be similar to the other keyboards from the brand. Well, of course reverse-engineering it won't include it in Aurora, so just maybe some other open source RGB project.

**Comment by fabriciano55** [comment]
Previously I talked with some developers of the Aurora project, and
they informed me that I will not have updates that will suit me. I can
only change the keyboard and be happy!
thanks for the support friend.


Em qua, 27 de jan de 2021 19:42, avengerx <notifications@github.com>
escreveu:
