### ISSUE TITLE
Corsair Harpoon Mouse Support

### ISSUE THREAD

**Issue by silvershoe** [antonpup/Aurora#947]
Hello. I'm a user of this amazing program, from Korea, south.
Bought a new mouse of Corsair to use Aurora and it didn't work. :(
In detail, when I run Aurora. Harpoon's light got turned off and doesn't work.
If you're glad, could you make this mouse to be supported or help me to solve this issue? 

### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### What is the version of Aurora you are experiencing this issue with?

My version is Beta v0.6.0b

### Does the previous version of Aurora have this issue?
The previous version, (v0.5.0), have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

at first, I'm sorry about the log, not written by english fully.

2018-01-11 오후 6:19:03: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_py_script.py. Exception: System.Exception: Provided script, does not meet all the requirements
   위치: Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) 파일 D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:줄 32
   위치: CallSite.Target(Closure , CallSite , Type , Object )
   위치: System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   위치: Aurora.Devices.DeviceManager..ctor() 파일 D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:줄 57
2018-01-11 오후 6:19:03: An error occured while trying to load script C:\Program Files\Aurora\Scripts\Devices\example_script.cs. Exception: System.Exception: Provided script, does not meet all the requirements
   위치: Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) 파일 D:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:줄 32
   위치: CallSite.Target(Closure , CallSite , Type , Object )
   위치: System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   위치: Aurora.Devices.DeviceManager..ctor() 파일 D:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:줄 71
[INFO] 2018-01-11 오후 6:19:03: Loading Configuration
[INFO] 2018-01-11 오후 6:19:04: Loading Device Manager
[ERROR] 2018-01-11 오후 6:19:04: Logitech LED SDK could not be initialized. (LogiLedSetTargetDevice or LogiLedSaveCurrentLighting failed)
[INFO] 2018-01-11 오후 6:19:04: Device, Logitech, was not initialized
[INFO] 2018-01-11 오후 6:19:04: Corsair device, Initialized with x64-SDK
[INFO] 2018-01-11 오후 6:19:04: Device, Corsair, was initialized
[INFO] 2018-01-11 오후 6:19:04: Razer device, Initialized
[INFO] 2018-01-11 오후 6:19:04: Device, Razer, was initialized
[INFO] 2018-01-11 오후 6:19:05: Could not connect to Clevo WMI Interface
[ERROR] 2018-01-11 오후 6:19:05: Clevo device, Exception! Message:System.Exception: Could not connect to Clevo WMI Interface
   위치: Aurora.Devices.Clevo.ClevoDevice.Initialize() 파일 D:\Repositories\Git\Aurora\Project-Aurora\Devices\Clevo\ClevoDevice.cs:줄 65
[INFO] 2018-01-11 오후 6:19:05: Device, Clevo Keyboard, was not initialized
[ERROR] 2018-01-11 오후 6:19:05: Cooler Master device control could not be initialized
[INFO] 2018-01-11 오후 6:19:05: Device, Cooler Master, was not initialized
[INFO] 2018-01-11 오후 6:19:05: Device, AtmoOrb, was initialized
[INFO] 2018-01-11 오후 6:19:05: Loading KB Layouts
[INFO] Baseline X = 0
[INFO] Baseline Y = 37
[INFO] 2018-01-11 오후 6:19:05: Input Hooking
[INFO] 2018-01-11 오후 6:19:05: Starting GameEventHandler
[INFO] 2018-01-11 오후 6:19:05: Starting GameStateListener
2018-01-11 오후 6:19:05: Listening for game integration calls...
2018-01-11 오후 6:19:05: [AuroraCommandsServerIPC] Pipe created 20554616
2018-01-11 오후 6:19:05: Loading WinApp...
2018-01-11 오후 6:19:05: Loaded WinApp
2018-01-11 오후 6:19:05: Loading ResourceDictionaries...
2018-01-11 오후 6:19:05: [IPCServer] Pipe created 36610825
[INFO] 2018-01-11 오후 6:19:05: Device, Corsair, was shutdown
[INFO] 2018-01-11 오후 6:19:05: Razer device, Shutdown attempt
[INFO] 2018-01-11 오후 6:19:05: Device, Razer, was shutdown
[INFO] 2018-01-11 오후 6:19:05: Device, AtmoOrb, was shutdown
2018-01-11 오후 6:19:05: Loaded ResourceDictionaries
2018-01-11 오후 6:19:05: Loading ConfigUI...

**Comment by simon-wh** [comment]
Could you try running the [latest development release](https://github.com/antonpup/Aurora/releases)?

**Comment by silvershoe** [comment]
Thanks for your reply. I've tried the latest. But sadly, it didn't work.
The same issue. When Aurora turns on, the LED got off.
And similar with this issue, one of Corsair Sabre's light doesn't work.

http://www.corsair.com/~/media/corsair/product-images/mice/sabre-rgb/large/cg_sabre_03.png

It has one more LED at the left of the index finger. But in Aurora, it displays only 3.

**Comment by simon-wh** [comment]
Is the only LED not working that one you mentioned that isn't included?

**Comment by silvershoe** [comment]
Only one of four isn't working.
And those mice are works good as mice but just LED doesn't works good.
I'm sorry I'm not a good english speaker. If I didn't understand the sentence right and wrote wrong answer, please refer my jpg 
![kakaotalk_20180121_010132472](https://user-images.githubusercontent.com/35330881/35193536-6dbb4120-fee7-11e7-90af-45ddb5e86b3b.jpg)

**Comment by Gurjot95** [comment]
Try latest build.
