### ISSUE TITLE
FN Button Problem and a wish

### ISSUE THREAD

**Issue by Soeren18** [antonpup/Aurora#948]
### What are you experiencing an issue with?

- [ x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x ] Other, (It is nice when you can close the Program in to the Windows Tray)

### Expected behavior:
Explain here what should happen.

### Actual behavior:
Explain here what happened instead.

### How often does this problem occur?

This problem occurs... (Fill in here)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. The FN Button can´t get a another color (G410)
2. Just go in the Color Settings and try to give FN a color
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... (v0.6.0b)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
Are you not able to set the colour of the fn key using something like the Solid Colour layer? Is it the case where the fn key is not showing on the virtual keyboard? If so could you try and select a keyboard layout that looks as close as to what you have?

**Comment by simon-wh** [comment]
Apparently the FN key is not supported by the Logitech SDK, so there isn't much I can do.
