### ISSUE TITLE
Aurora working odd, close it, reopen doesnt show in tray. End in taskmanager, relaunch, same.

### ISSUE THREAD

**Issue by Thelgow** [antonpup/Aurora#949]
### What are you experiencing an issue with?

- [X ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ X] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [X ] Other, (Fill in another type of issue here)

### Expected behavior:
To work normally

### Actual behavior:
Sometimes keyboard had default layer working, rainbow, but with a subtle left to right wave of lights being off. This has happened 3 times, no idea the cause.
Main concern now is I close the app in the system tray and try to relaunch it.  
Nothing shows in the system tray. Check task manager and its there. End process, launch Aurora and same thing, nothing in the tray.
This repeats until I restart my machine.

### How often does this problem occur?

This problem occurs intermittently. about 3 times since Dec 1st.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. When it happens, kill Aurora from task manager, relaunch, no difference.
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is... release_major_0_6_1-dev3

### Does the previous version of Aurora have this issue?
Unknown

**Comment by Thelgow** [comment]
Maybe a coincidence, didnt reboot yet but aurora came back on my 6th end process/relaunch.

**Comment by simon-wh** [comment]
Do you have a log file from when this was happening that you could post?

**Comment by Thelgow** [comment]
Where would I find a log file? I see a \logs folder but only contents 2017_25_11, which only has entries from November 25th.  
Also I've had 2 occasions now after a reboot, once I log in, aurora.exe has stopped/doesnt launch and I have to manually launch it.

**Comment by simon-wh** [comment]
Go to Settings -> Debug -> Show Logs folder and see what's in there.

**Comment by Thelgow** [comment]
[2018_01_12.log](https://github.com/antonpup/Aurora/files/1649383/2018_01_12.log)
Heres a log from what I believe was the 12th when I made this post, and had to do a bunch of relaunches.

**Comment by simon-wh** [comment]
@Thelgow Could you try version [v0.6.1-dev4](https://github.com/antonpup/Aurora/releases)?
