### ISSUE TITLE
Crash on start 5.0

### ISSUE THREAD

**Issue by AndreasTheDead** [antonpup/Aurora#95]
hello,
when i startz the programm after the update i get this:

[2016_11_08.txt](https://github.com/antonpup/Aurora/files/414101/2016_11_08.txt)

mfg Andreas

**Comment by antonpup** [comment]
Have you tried running Aurora as administrator? Unfortunately the provided logs don't show signs of any fatal error.

**Comment by Frostcoin** [comment]
same here also running as admin

**Comment by antonpup** [comment]
@Frostcoin Can you provide me with a latest log? Does any other error come up? Did the previous version work?

**Comment by Frostcoin** [comment]
no but could be something i did wrong, i'll get back to you. its saying no profiles found

**Comment by Frostcoin** [comment]
added the profiles from git to the appdata folder.
could it be because i have a razor naga mouse and a logitech g910 keyboard?

**Comment by Frostcoin** [comment]
Aurora.rz file gets created and then program stops, nothing about it in the log only profiles not found

**Comment by antonpup** [comment]
@Frostcoin Profiles not found is normal, it creates the necessary files. Can you send me last 15 or so lines of the latest log?

**Comment by Frostcoin** [comment]
`========================================
Operation System: Windows 10 Pro
System Architecture: 64 bit
Environment OS Version: Microsoft Windows NT 6.2.9200.0
System Directory: C:\Windows\system32
Processor Count: 8
User DomainName: DESKTOP-CFD615L
User Name: I7-Thor
SystemPageSize: 4096
Version: 4.0.30319.42000
========================================

8/11/2016 11:21:57 PM: An error occured while trying to load script C:\Users\I7-Thor\Desktop\release_major_0_5_0\Scripts\Devices\example_py_script.py. Exception: System.Exception: Provided script, does not meet all the requirements
   at Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) in d:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:line 32
   at CallSite.Target(Closure , CallSite , Type , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Aurora.Devices.DeviceManager..ctor() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:line 53
8/11/2016 11:21:57 PM: An error occured while trying to load script C:\Users\I7-Thor\Desktop\release_major_0_5_0\Scripts\Devices\example_script.cs. Exception: System.Exception: Provided script, does not meet all the requirements
   at Aurora.Devices.ScriptedDevice.ScriptedDevice..ctor(Object script) in d:\Repositories\Git\Aurora\Project-Aurora\Devices\ScriptedDevice\ScriptedDevice.cs:line 32
   at CallSite.Target(Closure , CallSite , Type , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Aurora.Devices.DeviceManager..ctor() in d:\Repositories\Git\Aurora\Project-Aurora\Devices\DeviceManager.cs:line 67
[INFO] 8/11/2016 11:21:59 PM: Device, Logitech, was initialized
[ERROR] 8/11/2016 11:21:59 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 8/11/2016 11:21:59 PM: Device, Corsair, was not initialized
[INFO] 8/11/2016 11:21:59 PM: Razer device, Initialized
[INFO] 8/11/2016 11:21:59 PM: Device, Razer, was initialized
[INFO] 8/11/2016 11:21:59 PM: Loading KB Layouts
[INFO] 8/11/2016 11:21:59 PM: Retrying Device Initialization
[ERROR] 8/11/2016 11:21:59 PM: Corsair device, CUE Exception! ErrorCode: ServerNotFound
[INFO] 8/11/2016 11:21:59 PM: Device, Corsair, was not initialized
[INFO] Baseline X = 7
[INFO] Baseline Y = 0
[INFO] Baseline X = 0
[INFO] Baseline Y = 0
[INFO] Baseline X = 44
[INFO] Baseline Y = 37
[INFO] 8/11/2016 11:21:59 PM: Input Hooking
[INFO] 8/11/2016 11:21:59 PM: Starting GameEventHandler
[INFO] 8/11/2016 11:21:59 PM: Starting GameStateListener
8/11/2016 11:21:59 PM: Listening for game integration calls...`

**Comment by antonpup** [comment]
Okay, this is really strange. I have added a bit more logging to help me locate the issue. Please try running the version attached. During the crash, it should come up with an error message and it should log it in the file.

[Release_0_5_0_more_debug.zip](https://github.com/antonpup/Aurora/files/414324/Release_0_5_0_more_debug.zip)

**Comment by TheAzodiac** [comment]
Hey Antonpup!
I love Aurora so much with my Logitech G910 and G933!
I just updated from BETA 0.4.6 to 0.5.0! 
But now when I execute Aurora.exe, there's nothing happen. In the Task Manager, you see Aurora is appearing for 2 Seconds and dissapears after that. No WIndows at all. And yes, I started it as Administrator. 
BUT when I start the "debug-Version", which you've posted 20 Minutes ago, Aurora shows a debug Window AND the mein window itself. And everything is just working fine! But when I close the Debug Window, Windows is forcing to close Aurora because of a error message, Aurora has a problem.
I just wanted to share this with you all :)

Greetings, Azodiac

**Comment by antonpup** [comment]
@TheAzodiac Can you screenshot this debug window? There shouldn't be any windows other than Aurora itself. Also post your log.

**Comment by TheAzodiac** [comment]
@antonpup Here's the Screenshot and the Log itself from Aurora and Aurora Debug.
![aurora debug window](https://cloud.githubusercontent.com/assets/20979278/17607286/22135544-6025-11e6-8fe7-f767b1d6a50c.PNG)
[2016_12_08.txt](https://github.com/antonpup/Aurora/files/414360/2016_12_08.txt)
[2016_12_08.txt](https://github.com/antonpup/Aurora/files/414364/2016_12_08.txt)

**Comment by antonpup** [comment]
Thank you. That will help me. I am looking into this.

**Comment by antonpup** [comment]
I see. I have found the issue, it's due to German installations of Windows having differently named user groups.

I have attached another version with a fix. It should work without the error. If so, I will push it as 0.5.1.

[Release_0_5_0_IPC_perms_fix.zip](https://github.com/antonpup/Aurora/files/414405/Release_0_5_0_IPC_perms_fix.zip)

**Comment by TheAzodiac** [comment]
@antonpup  Thank you very much! It works just fine now! Huge respects from me :+1:

**Comment by antonpup** [comment]
I have pushed version 0.5.1 with the fix. Please update and try it.

**Comment by Frostcoin** [comment]
I went to bed yesterday so i havent tried yet. Will do asap. Hope it will also work for me since i do not have a german install.

Do you have a bitcoin or ethereum address so i can send you a donation? 

Highest regards and keep up the good work and great support =D A+++++++++++++

**Comment by antonpup** [comment]
@Frostcoin No bitcoin, just a paypal and steam. You can find them on the main page of the repo, scroll down.

If you still experience the crash on startup, I will be pushing another update tomorrow to deal with an issue with Rocket League, so I can also include any additional fix for startup.

**Comment by Frostcoin** [comment]
The program launches now, but it says: No keyboard detected, please ensure that you have SDK enabled for your keyboard. 
Logitech g910

If you create a Bitcoin wallet I can send you a donation, i don't do paypal.
I'll be gone for the weekend, will check progress after

**Comment by antonpup** [comment]
Make sure that "Enable SDK" is checked in LGS. You can find the exact steps in Aurora's settings, under the Devices tab. "First time install instructions for Logitech".

Also ensure that your LGS is up to date.
