### ISSUE TITLE
Aurora 'fatally crashing'

### ISSUE THREAD

**Issue by nuzzle000** [antonpup/Aurora#950]
[2018_13_01.log](https://github.com/antonpup/Aurora/files/1628511/2018_13_01.log)

### What are you experiencing an issue with?

- [x ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
I click on the desktop shortcut to open Aurora, it opens

### Actual behavior:
I click on the desktop shortcut to open Aurora, it crashes 
![screenshot 10](https://user-images.githubusercontent.com/35398212/34908010-aee04730-f880-11e7-9013-d948e0674bbd.png)

### How often does this problem occur?

This problem occurs... (Every time)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Install recommended version of Aurora (0.6.0b Beta)
2. Install the latest version of Aurora (0.6.1-dev3)
3. Manually replace the files for 0.6.0b Beta, with the files for 0.6.1-dev3
4. Delete 0.6.1-dev3 manually because there is no option to uninstall
5. Reinstall Aurora (0.6.0b Beta)
6. Try to open Aurora

### What is the version of Aurora you are experiencing this issue with?

My version is... (Aurora 0.6.0b Beta)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by JmLykins** [comment]
I am guessing you updated to a newer version of Aurora and started receiving these errors. I deleted the Aurora folder located in C:\Users\"INSERTUSERNAME"\AppData\Roaming\Aurora and it fixed my errors. Deleting the entire folder will remove any settings or configuration such as lighting profiles. You can back them up by moving the profiles folder before deleting everything. I would suggest sticking with the recommended 0.6.0b Beta like I am for now as the other builds still have issues.

**Comment by nuzzle000** [comment]
Thank you, I will try doing that once I get home later today. Thanks for your help, much appreciated.

**Comment by simon-wh** [comment]
To fix that you need to delete %appdata%/Aurora/Config.json
