### ISSUE TITLE
Aurora causes LGS to Lag so keyboard lighting is not smooth at all

### ISSUE THREAD

**Issue by Zodsmar** [antonpup/Aurora#951]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [x] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
For example, the desktop mode. When you click the keyboard the colors should be smooth. 

### Actual behavior:
If I push G 1/4 the keyboard lights up, then 1/2 then all. Its very choppy and not smooth at all. Even with CSGO good example is the bomb plant it hardly goes red and is very off and choppy and not smooth at all. (Also I noticed if I open LGS and go to Gaming Integration tab with Aurora open it lags super bad. As soon as I close Aurora no more lag or anything.)

### How often does this problem occur?
Every time.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. 
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

v0.6.0b (newest as of this writing)

### Does the previous version of Aurora have this issue?
No idea this is the first time I am using Aurora

### Please include any logs, screenshots, or files that are related to this issue:
No logs

**Comment by simon-wh** [comment]
Could you try using the [latest development release](https://github.com/antonpup/Aurora/releases)?

**Comment by Zodsmar** [comment]
Should I open Aurora, leave it open then restarts LGS or restart LGS before I open Aurora?

**Comment by simon-wh** [comment]
Apparently it's just a general issue with LGS, so when it appears just restart LGS.

**Comment by Zodsmar** [comment]
Tried what you asked. Still lags and hardly is responsive

**Comment by simon-wh** [comment]
This seems to be an issue with LGS and not Aurora, so I'm going to close this.
