### ISSUE TITLE
ACGAM devices

### ISSUE THREAD

**Issue by JeremyD357** [antonpup/Aurora#954]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, (Fill in another type of issue here)

Do you think you can add ACGAM devices support in Aurora ? it's would be fking awesome thanks for all you've already done. :)

**Comment by simon-wh** [comment]
There does not appear to be an SDK available for those devices so there isn't much I can do to support them without access to the device.
