### ISSUE TITLE
Equalizer is not working with Realtek audio.

### ISSUE THREAD

**Issue by cubeslice** [antonpup/Aurora#956]
By the way, I do know that there is a thread on this, but nothing has happened to it in a couple months.

### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Equalizer should work with every device.

### Actual behavior:
Equalizer only works with devices with the default windows drivers, not other drivers (e.g. Realtek, Nahimic)

### How often does this problem occur?

This problem occurs everytime

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Install Realtek Audio drivers
2. Switch to the device with the Realtek drivers
3. ...
4. Doesn't work anymore :(

### What is the version of Aurora you are experiencing this issue with?

My version is... beta v0.6.1 dev3

### Does the previous version of Aurora have this issue?
The previous version, v0.6.0 , did have this issue.

**Comment by simon-wh** [comment]
Just because the other thread is inactive doesn't mean you should create a new one. You should comment on the existing one.

Duplicate of #875
