### ISSUE TITLE
When Overwatch starts the lights turn off (K95 Platinum)

### ISSUE THREAD

**Issue by ShoePak** [antonpup/Aurora#963]
### What are you experiencing an issue with?

- [ ] Aurora
- [x ] Aurora supported game, (Overwatch)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
The Keyboard lights up and when i choose a character a profile resembling their colors appears

### Actual behavior:
The Keyboard stays un-lit no matter what

### How often does this problem occur?

This problem occurs... (Everytime)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. run aurora
2. run overwatch
3. go to practice range
4.no lights appear

### What is the version of Aurora you are experiencing this issue with?

My version is... (I tried it on the three on the github home page)

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.
I don't know

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by diogotr7** [comment]
Go into training and see if the lights turn on. There are no lights when you first start the game, you have to go into a match.

**Comment by ShoePak** [comment]
I don't know what I did but i got it to work

**Comment by ShoePak** [comment]
I think I had selected the wrong folder for the razer wrapper
