### ISSUE TITLE
Full Logitech setup - wierd issue

### ISSUE THREAD

**Issue by DreamlessTinkerer** [antonpup/Aurora#969]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [x] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Overwatch Integration

### Actual behavior:
Mouse and headset change just fine from hero to hero. Keyboard stays locked on desktop profile. Changes do register on Aurora, i see the hero colors on the virtual keyboard light up properly, but it doesn't relay to the keyboard.

### How often does this problem occur?
Every time

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. installed
2. logitech patched
3. overwatch patched

### What is the version of Aurora you are experiencing this issue with?
I've tried a full uninstall of LGS and reinstall of LGS and all three current versions, by that I mean i uninstall LGS and reinstall it every time i change versions of Aurora.

### Does the previous version of Aurora have this issue?
Do not know, recently acquired this gear and started using your software

### Please include any logs, screenshots, or files that are related to this issue:
Anything I can provide, Just let me know what and how to acquire it.

**Comment by DreamlessTinkerer** [comment]
Also seems to ignore the EQ lol, Headset and mouse are rocking out but the keyboard is just sitting there in plain desktop mode, virtual keyboard in the Aurora app shows the EQ motions. Also just like to say that the sheer effort and time that must have gone into this work is astounding. I'm sure it's probably something misconfigured on my end. I've reviewed all of what I could relating to the logitech issues and this seems to be new. I've notice that the keyboard and headset are registered under atmoOrb, if I disable it, they go dark. Not too sure how to proceed troubleshooting.

**Comment by simon-wh** [comment]
If you disconnect the headset from your computer so you only have the mouse and keyboard does it change anything? Also, could you throw in your log file from when this is occurring (%appdata%/Aurora/Logs or click "Show logs folder" (or whatever it's called) in Settings -> Debug)
