### ISSUE TITLE
 Device Add Request: Support For Asus Cerberus Keyboard

### ISSUE THREAD

**Issue by G1itch710** [antonpup/Aurora#971]
As the title says, would be awesome if the devs could add support for the Asus cerberus range of keyboards, not sure if its possible though.

**Comment by simon-wh** [comment]
https://rog.asus.com/forum/showthread.php?94004-Driver-for-CERBERUS-backlit-keyboard It's not a possibility. Also, it doesn't appear to have per-key lighting so even if it had an available SDK it wouldn't be able to do much.

**Comment by G1itch710** [comment]
Hi thanks for the reply, i should clarify i meant this one: 
https://www.asus.com/au/Keyboards-Mice/CERBERUS-MECH-RGB/HelpDesk_Download/ n

not sure if it would still be possible, but that one does have full RGB and per key lighting and also a driver

**Comment by simon-wh** [comment]
Asus aura is the main SDK for doing custom lighting to Asus devices which only appears to support the claymore keyboards. Without an SDK I can't really do much
