### ISSUE TITLE
Gradient animation resets periodically

### ISSUE THREAD

**Issue by ozio** [antonpup/Aurora#972]
### What are you experiencing an issue with?
- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?
- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Gradient animation visualize smooth and clean.

### Actual behavior:
Animation layer resets gradient position in about every 2:30, you can see behavior at 2:10 here: http://recordit.co/J32rz5J2vD

### Please describe the steps to reproduce this issue:
Gradient layer config:

```json
{
  "$type": "Aurora.Settings.Layers.Layer, Aurora",
  "Name": "Gradient",
  "Handler": {
    "$type": "Aurora.Settings.Layers.GradientLayerHandler, Aurora",
    "Properties": {
      "$type": "Aurora.Settings.Layers.GradientLayerHandlerProperties, Aurora",
      "_GradientConfig": {
        "$type": "Aurora.Settings.LayerEffectConfig, Aurora",
        "primary": "164, 46, 72",
        "secondary": "35, 219, 126",
        "speed": 4.0,
        "angle": -10.0,
        "animation_type": 1,
        "animation_reverse": true,
        "brush": {
          "$type": "Aurora.EffectsEngine.EffectBrush, Aurora",
          "type": 2,
          "wrap": 2,
          "color_gradients": {
            "$type": "System.Collections.Generic.SortedDictionary`2[[System.Single, mscorlib],[System.Drawing.Color, System.Drawing]], System",
            "0": "241, 103, 69",
            "0.2169231": "255, 198, 93",
            "0.4245055": "123, 200, 164",
            "0.6165934": "76, 195, 217",
            "0.8150382": "185, 121, 177",
            "1": "53, 40, 53"
          },
          "start": {
            "$type": "System.Drawing.PointF, System.Drawing",
            "IsEmpty": true,
            "X": 0.0,
            "Y": 0.0
          },
          "end": {
            "$type": "System.Drawing.PointF, System.Drawing",
            "IsEmpty": false,
            "X": 1.0,
            "Y": 0.0
          },
          "center": {
            "$type": "System.Drawing.PointF, System.Drawing",
            "IsEmpty": true,
            "X": 0.0,
            "Y": 0.0
          }
        }
      },
      "_SecondaryColor": "127, 214, 63",
      "_PrimaryColor": "98, 189, 65",
      "_Sequence": {
        "$type": "Aurora.Settings.KeySequence, Aurora",
        "keys": {
          "$type": "System.Collections.Generic.List`1[[Aurora.Devices.DeviceKeys, Aurora]], mscorlib",
          "$values": []
        },
        "type": 1,
        "freeform": {
          "$type": "Aurora.Settings.FreeFormObject, Aurora",
          "Type": 1,
          "X": -10.4578857,
          "Y": -22.0603485,
          "Width": 802.39624,
          "Height": 250.920029,
          "Angle": 0.0
        }
      }
    }
  },
  "Enabled": true,
  "Type": 0,
  "Logics": {
    "$type": "System.Collections.ObjectModel.ObservableCollection`1[[Aurora.Settings.Layers.LogicItem, Aurora]], System",
    "$values": []
  },
  "LogicPass": true
}
```

### What is the version of Aurora you are experiencing this issue with?
My version is 0.6.0b

**Comment by simon-wh** [comment]
Could you see if you experience the issue on the [latest development release](https://github.com/antonpup/Aurora/releases)?

**Comment by ozio** [comment]
Yes. 0.6.1-dev4 also has this bug. I just counted that animation resets every 27th gradient round.

**Comment by simon-wh** [comment]
Fixed with the commit above, fix will be available in the next release or you can get it now by getting the [build for the commit](https://ci.appveyor.com/project/antonpup/aurora/build/0.6.1-dev4-287/artifacts). Also, many thanks for including the config of the Layer, without that inclusion it likely would've taken me longer to debug it!

**Comment by ozio** [comment]
Reproducing again on the actual version
