### ISSUE TITLE
Add capslock script

### ISSUE THREAD

**Issue by Wolfieeewolf** [antonpup/Aurora#973]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [x] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [x] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

Would like to see a script added so when I press my capslock key that all the letters light up when caps is enabled and off when not. Could also work with numlock and FN keys as well

**Comment by Wolfieeewolf** [comment]
Maybe you could just add a layer type as Text Document layer so you can have it active when you open things like Notepad and Word.

**Comment by simon-wh** [comment]
Have you seen the "Lock Color Layer" it should allow you to achieve what you want. If you don't have it you may need to update to the [latest development version](https://github.com/antonpup/Aurora/releases?
