### ISSUE TITLE
Aurora Lighting Effects not smoothly animated

### ISSUE THREAD

**Issue by Dreadp1r4te** [antonpup/Aurora#974]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [X] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [X] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Animations should take full advantage of all RGB combinations to provide smooth and seamless transitions where applicable.

### Actual behavior:
Animations seem jerky, as if they skip colors between original and destination color. The timing also sems off. Occurs on both Corsair Strafe RGB and Rival 700 mouse. 

### How often does this problem occur?

This problem occurs every time an animation plays. 

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Enable any animated effect layer.
2. Assign layer to all keys.
3. Set colors for a high contrast change, i.e., red to blue
4. Observe jerkiness of animation

### What is the version of Aurora you are experiencing this issue with?

My version is... Beta v0.6.1-dev4

### Does the previous version of Aurora have this issue?
Yes.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
Can you provide the profile that you're using which experiences this the worst? It makes it a bit easier for me to identify performance issues in particular places.

**Comment by Dreadp1r4te** [comment]
You can view it easily on "Away" animation if you set it to the Matrix
effect. It occurs on any profile with animations however.

**Comment by simon-wh** [comment]
Are they not smoothly animated on the virtual keyboard or on your keyboard? Because it's not unusual for the preview to be a bit behind, but it should be fine when actually on your device. You can have a look at the debug tab of settings to have a look at the bitmap which is being shown on your devices and see if that is smooth or not. If it is, and it is not smooth on your devices then it might be an issue with the devices taking too long to update with the colours.

**Comment by Dreadp1r4te** [comment]
The animations are smooth on the bitmap but lag on the keyboard. For
comparison, all animations from CUE2 are perfectly smooth, in addition to
CEE being smooth. It's only with Aurora that it lags.

**Comment by simon-wh** [comment]
Are they lagging on your physical keyboard or the keyboard preview? If it is lagging on the physical keyboard have a look at what the update time shown in the Device Manager is for your device.

**Comment by Dreadp1r4te** [comment]
I don't see an entry for Update Time in the device manager settings. Where
would I find that?

**Comment by simon-wh** [comment]
![image](https://user-images.githubusercontent.com/10797576/36235855-dcd4ebfe-11ea-11e8-983e-334564d3db46.png)
It's the number that can be seen to the left of the Stop button.

**Comment by Dreadp1r4te** [comment]
Mine shows 0 ms.

**Comment by simon-wh** [comment]
So to be 100% clear what exactly is lagging. If the debug bitmap is smooth and there is no delay for it updating, then, in theory, it should be smooth when it is shown in CUE and on your actual keyboard. The only place that should be noticeably lagging is the virtual representation of the keyboard you see when looking at Aurora.
