### ISSUE TITLE
Overwatch not recognizing default Logitech Profile even after uninstall.

### ISSUE THREAD

**Issue by Gabriel2290** [antonpup/Aurora#975]
### What are you experiencing an issue with?

- [x ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [x] Other, When I uninstalled Aurora, Overwatch now has a black profile on g810 keyboard.

### Expected behavior:
I figured if I uninstalled Aurora, Logitech would now recognize the default Overwatch profile, but it does not.

### Actual behavior:
Black lighting profile when Overwatch starts

### How often does this problem occur?
Every time OW is launched.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Launching Overwatch
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?
betav.0.6.0b

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
I don't really understand what your issue is
