### ISSUE TITLE
Feature Request: separated lighting options for Atmoorb

### ISSUE THREAD

**Issue by Exion84** [antonpup/Aurora#978]
Hi, I'm using the Atmoorb integration in Aurora but have some difficulties with the actual implementation. For example: If I use a rainbow-color-effect on my keyboard and mice the orb only glowes in a static white. Only if i switch to a single color it is able to affect the orb. Also at the moment it is not able to create an own lighting layer for the orb only (for example a rainbow-color-layer for the keyboard and ambilight-layer for the orb). Is it may be possable to add an own configuration layer for the Atmoorb?

Thanks for your awesome work! I absolutly love the Aurora projekt!

**Comment by simon-wh** [comment]
This will be possible once I've finished rewriting the device layout system to properly support devices outside of keyboards & mice
