### ISSUE TITLE
[Enhancement] Dota 2: Flash certain keys when HP is below certain percentage 

### ISSUE THREAD

**Issue by senkus** [antonpup/Aurora#98]
The Logitech Software offers this, I found it very useful in the heat of battle.
Logitech flashes the function keys (i.e. the health bar) in red (black in between flashes) when health is below 30%.

**Comment by antonpup** [comment]
Yes. I completely forgot about this. I'll see about including this for next version.

**Comment by antonpup** [comment]
Just an update, this feature is now included as a standard option for any Percent Effect Layer for next major aurora version.
