### ISSUE TITLE
Feature Request: Support for Razer Base Station Chroma, Steelseries Devices

### ISSUE THREAD

**Issue by Xp3r10n** [antonpup/Aurora#981]
Would it be possible to provide support for the Razer Base Station Chroma and Steelseries devices such as the rival 310/600/700?

**Comment by simon-wh** [comment]
The rival 310/600/700 should be working properly through the Steelseries support that has already been implemented. Just need to select a mouse that has a similar lighting layout and it should be fine. The Razer Base Station chroma will be supported when I finish reworking the device layout system.

**Comment by Gurjot95** [comment]
Fixed with latest Chroma Link update.
