### ISSUE TITLE
Keyboard Support: Glorious Modular Mechanical Keyboard

### ISSUE THREAD

**Issue by AustScar5** [antonpup/Aurora#982]
Can support for the Glorious Modular Mechanical Keyboard be added to Aurora? Would love to be able to use the lighting effects in games.

**Comment by simon-wh** [comment]
I wasn't able to find any sdk available for that keyboard. Are you aware of any way to communicate with the software or hardware directly to set lighting?

**Comment by AustScar5** [comment]
There is a software download at (https://www.pcgamingrace.com/pages/gmmk-software-download).

**Comment by simon-wh** [comment]
I had seen the software, but I didn't see any way to communicate with the software to give lighting effects to the keyboard.
