### ISSUE TITLE
crashed

### ISSUE THREAD

**Issue by S2P2** [antonpup/Aurora#983]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [x] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### How often does this problem occur?
once

### Please describe the steps to reproduce this issue:
I don't know, just playing Overwatch and caused this

### What is the version of Aurora you are experiencing this issue with?
0.6.1-dev4

### Does the previous version of Aurora have this issue?
The previous version, 0.6.1-dev3, did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:
https://pastebin.com/ERJTAdaB
crashed window : https://imgur.com/7aVn9Gp

**Comment by drhead** [comment]
I have also experienced this crash.  The application continues to run just fine and I can still modify settings if the crash dialog box is ignored and it will "crash" again twice, but still work fine.

**Comment by simon-wh** [comment]
I believe this has been fixed in the dev branch, could you try the [latest build](https://ci.appveyor.com/project/antonpup/aurora/build/artifacts) and tell me if you still experience the issue?
