### ISSUE TITLE
Cooler Master Pro L - "6" key on 10 key pad will not light

### ISSUE THREAD

**Issue by kelaymon** [antonpup/Aurora#984]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x ] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Explain here what should happen.
Using a Cooler Master Pro L RGB. Used a freestyle selection to select the entire keyboard for a grandient interactive layer.
### Actual behavior:
Explain here what happened instead.
All keys light except the "6" on the 10 key pad. When I manually select keys for this layer and only select the "6" key, the "5" key on the 10 key pad lights up instead.
### How often does this problem occur?

This problem occurs... (Fill in here)
Every time
### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Current settings: Interactive layer with gradient. Seamless rainbow, speed 2, effect angle 0, animation x and y
2. Freestyle selection of whole keyboard (or even selection of the "6" key alone)
3. I have tried multiple layer layouts and all do the same thing: "6" does not light, but instead lights "5"

### What is the version of Aurora you are experiencing this issue with?

My version is... (Fill in here)
0.6.1-dev3
### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.
unknown
### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
Update to v0.6.1-dev4
