### ISSUE TITLE
coolermaster masterkeys pro s equalizer issue 

### ISSUE THREAD

**Issue by aliak1** [antonpup/Aurora#988]
### What are you experiencing an issue with?

- [x] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [x ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x ] Visual bug
- [x ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ x] Other, (Fill in another type of issue here)
only when i chose the equalizer mod the keyboard lighting dont work perfectly and only the numbers and f1,f2...f12 and <> right win key and fn and ctrl light in low brightness blue  and red lights and the keyboard lights work on a mod look like interactive layer when it should sync with the music
### Expected behavior:
Explain here what should happen.
it should sync with the music volume 
### Actual behavior:
Explain here what happened instead.
it work like interactive  layer
### How often does this problem occur?

This problem occurs... (Fill in here)

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. run the software 
2.  chose my keyboard
3. chose the equalizer mod

### What is the version of Aurora you are experiencing this issue with?

My version is... (0.6.0)

### Does the previous version of Aurora have this issue?
The previous version, (i didnt used older version), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
I'm can't picture what effect you're describing, would you be able to take a video of it?

**Comment by aliak1** [comment]
https://www.youtube.com/watch?v=I-BtYhSNqvM 
this is a video shows my issue

**Comment by simon-wh** [comment]
I see that you're using v0.6.0b, could you try [v0.6.1-dev4](https://github.com/antonpup/Aurora/releases). There have been fixes made to the Equalizer(now visualizer) layer since v0.6.0b that may fix your issue.
