### ISSUE TITLE
[Overwatch] Some character background lighting not working on G810

### ISSUE THREAD

**Issue by BobbleSu** [antonpup/Aurora#990]
### What are you experiencing an issue with?

- [ ] Aurora
- [x] Aurora supported game, (Overwatch)
- [x] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Unused keys (all other than WASD, Q, Shift, E) should be lit in a character specific color throughout the match and on the character select screen.

### Actual behavior:
On characters where this color is already rather dim with Chroma keyboards (Doomfist, Reaper, Moira) it's not shown at all using Aurora, the keys are unlit. On other characters (Soldier, Bastion, Widow) they are barely visible. The "Color Enhancing" option in the Aurora Overwatch profile does NOT help even at maximum strength.

### How often does this problem occur?

This problem occurs every time.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Start any match or training match, select Doomfist, Reaper, or Moira.
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is beta v0.6.0b

### Does the previous version of Aurora have this issue?
Sorry, my first time using Aurora.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by diogotr7** [comment]
This is fixed in the dev versions, just set the color enhancing to hsv.

**Comment by BobbleSu** [comment]
Oh! I had no idea there's a year worth of updates, I just used the main version from the website. 
HSV solves all my problems, thank you so much.

**Comment by BobbleSu** [comment]
Not sure if I should close this, the thread seems to disappear and I'd rather have it here for people to find it via google.

**Comment by simon-wh** [comment]
The issue only disappears from the open issues, you can still find it through google and by searching all the issues.
