### ISSUE TITLE
[Overwatch] Animated lighting effects flicker with  "Color Enhancing" enabled on G810

### ISSUE THREAD

**Issue by BobbleSu** [antonpup/Aurora#991]
### What are you experiencing an issue with?

- [ ] Aurora
- [x] Aurora supported game, (Overwatch)
- [x] Aurora Wrapper
- [ ] Aurora Profile
- [ ] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [x] Visual bug
- [ ] Localization issue
- [ ] Enhancement suggestion
- [ ] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Animated lighting effects like the blue waves when Reinhardt is holding his shield should animate smoothly with and without Color Enhancing enabled.

### Actual behavior:
Animated lighting effects like the blue waves when Reinhardt is holding his shield flicker with Color Enhancing enabled, the effects seem "noisy" and uneven.

### How often does this problem occur?

This problem occurs every time.

### Please describe the steps to reproduce this issue:
The issue can be reproduced by doing following steps:

1. Start any match or training match, select Reinhardt, hold right mouse button to hold up his shield.
2. 
3. 

### What is the version of Aurora you are experiencing this issue with?

My version is v0.6.0b.

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.
This is my first time using Aurora.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
There have been changes to the colour enhancing since v0.6.0b which you can find in [v0.6.1-dev4](https://github.com/antonpup/Aurora/releases) could you try out that version and see if you experience it on that as well?

**Comment by BobbleSu** [comment]
HSV indeed solved the problem, thank you. :)
