### ISSUE TITLE
Killing Floor 2 support?

### ISSUE THREAD

**Issue by Soulflare3** [antonpup/Aurora#993]
Is it possible to get Aurora support added for Killing Floor 2?

KF2 has Logitech LED support by default, but I can't seem to get it to work with Aurora at the moment. There is a LogitechLedEnginesWrapper.dll in \killingfloor2\Binaries\Win64\

**Comment by simon-wh** [comment]
I own Killing Floor 2, so when I'm looking at adding more game support I'll have a look at it.

**Comment by diogotr7** [comment]
Killing floor 2 works using lightfx.
