### ISSUE TITLE
Support for Skiller Mech SGK3

### ISSUE THREAD

**Issue by KiemPlant** [antonpup/Aurora#995]
### What are you experiencing an issue with?

- [ ] Aurora
- [ ] Aurora supported game, (Fill in the game)
- [ ] Aurora Wrapper
- [ ] Aurora Profile
- [x] Aurora supported device, (Fill in problematic devices)
- [ ] Aurora Scripts
- [ ] Aurora Updater
- [ ] Aurora Lighting issue
- [ ] Other, (Fill in another issue here)

### What kind of an issue is it?

- [ ] Crash
- [ ] Performance problems
- [ ] Visual bug
- [ ] Localization issue
- [x] Enhancement suggestion
- [x] Device issue
- [ ] Other, (Fill in another type of issue here)

### Expected behavior:
Hello

I would love to see support for the Sharkoon Skiller Mech SGK3 (RGB) keyboard, I know you probably will not add this, but I don't enjoy the limited features that came with my Sharkoon Skiller Mech SGK3. I would really appreciate adding support for this keyboard. I would love to sync my keyboard with my Logitech G502 :)

You might say: "Just buy a Logitech g810 keyboard"  but I just got this keyboard and I LOVE the way it looks in my setup :)

Thanks.

### Actual behavior:

It doesn't detect my keyboard (of course I didn't even try).

### How often does this problem occur?
-

### Please describe the steps to reproduce this issue:
-

### What is the version of Aurora you are experiencing this issue with?
Latest version, doesn't really matter.

### Does the previous version of Aurora have this issue?
The previous version, (Fill in the version here), did/did not have this issue.

### Please include any logs, screenshots, or files that are related to this issue:

For logs, you can use: http://pastebin.com/
For screenshots, you can use: http://imgur.com/
For files, you can use: http://www.tinyupload.com/ , https://www.dropbox.com/ , or attach them to the issue.

**Comment by simon-wh** [comment]
I wasn't able to find any SDK available to interact with that keyboard, so there isn't much I can do to support it.

**Comment by strarsis** [comment]
@simon-wh: FWIW: The config profile exported to JSON file from the Sharkoon Windows software (for that `Sharkoon SKILLER SGK30` keyboard) contains some interesting information:
```json
   "Device": "DPIStages" : null,
      {
         "DeviceBasicInfo" : {
            "DevciesChipmodel" : "VS11K09A",
````
From what I understand the `VS11K09A` is the embedded RGB controller of the keyboard, and specs/firmware/drivers exist for it. I am not sure how this could be integrated into Aurora though.

**Comment by kiam001** [comment]
https://github.com/Matusson/SGK3-LED-API

**Comment by kiam001** [comment]
CC @simon-wh
